### ISSUE TITLE
Helm install of cost-analyzer chart failing

### ISSUE THREAD

**Issue by bboppana** [kubecost/cost-analyzer-helm-chart#1000]
Helm install of cost-analyzer chart is failing with the below error even with awsstore.useAwsStore: false set in values file. 

Error: Deployment.apps "cost-analyzer-awsstore" is invalid: spec.template.spec.containers[0].image: Required value

After setting awsstore.useAwsStore.imageNameAndVersion in values file, deployment was successful.

awsstore template is not working as expected.

Please let me know if i am missing something.

gz#616

**Comment by kbrwn** [comment]
Hi @bboppana would you try out the [kubecost nightly](https://github.com/kubecost/docs/blob/master/release-process.md#nightly-releases) to see if this issue persists? There were some changes to the aws-store deployment: https://github.com/kubecost/cost-analyzer-helm-chart/pull/995

**Comment by AjayTripathy** [comment]
@kbrwn I think this is reversed actually. This should not be an issue in prod but there was an issue in nightly/develop branch that may have caused. Is this an issue when installing from our production repo? Instructions here: https://www.kubecost.com/install.html#show-instructions

**Comment by AjayTripathy** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/pull/1001 Either way, when this reaches develop the issue will be fixed in develop, and nightly as well.

**Comment by bboppana** [comment]
@AjayTripathy @kbrwn 

I am using production repo. Here is my helm command.

 helm upgrade -i cost-analyzer artifactory/cost-analyzer -f kubecost-values.yaml --namespace kubecost --version 1.83.2

We install it thru artifactory.

**Comment by AjayTripathy** [comment]
That's a bit surprising, as https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/templates/awsstore-deployment-template.yaml#L1 should prevent the template from ever executing. Is there any way you could post your values.yaml with sensitive data redacted?

**Comment by AjayTripathy** [comment]
Ah-- I think I may see what happened. We merged a change to develop that added the useAwsStore block and set it to false. In previous versions, the way to disable the block is to simply delete the whole awsStore block as we check for its existence to deploy the template.

**Comment by bboppana** [comment]
Deployment was successful after removing the awsstore block from values file. Thanks
