### ISSUE TITLE
Adding Labels and Annotations to prometheus and grafana charts

### ISSUE THREAD

**Issue by bboppana** [kubecost/cost-analyzer-helm-chart#1009]
We want to add Labels/Annotations to prometheus and grafana charts from global values files for cost-analyzer. Right now there is no option to add them to the sub-charts.

Can the option to add Labels/Annotations be added to the prometheus/Grafana sub-charts? 

gz#635

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-31) by [Unito](https://www.unito.io)

**Comment by bboppana** [comment]
I am able to add Labels/Annotations to prometheus pods by modifying the global values file.

**Comment by bboppana** [comment]
Able to add annotations to grafana pods but not labels.

Grafana chart needs to have something like this to be added.

{{- with .Values.podLabels }}
{{ toYaml . | indent 8 }}
{{- end }}

**Comment by dwbrown2** [comment]
@bboppana that's correct. Grafana subchart just supports annotations currently -- https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/charts/grafana/templates/deployment.yaml#L11

Grafana itself is optional for the core Kubecost product. You also have the ability to bring your own Grafana if you already have it running. 

Let us know what would help you most and if we you want us to leave this open as a feature request!

**Comment by bboppana** [comment]
@dwbrown2 

Yes, please leave this open as a feature request. 
We are using grafana comes with kubecost right now and we have plans to see whether we can use our existing grafana deployed in EC2.
As we use labels for cost attribution to teams in EKS, we want the option of adding labels to grafana also.

**Comment by dwbrown2** [comment]
Sounds good, marking as help wanted. This should be a quick change but Kubecost team is in the middle of a release right now.
