### ISSUE TITLE
Enhance "pricingSourceCounts" endpoint to include number of matches for storage between CSV and billing data

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1019]
To ensure all storage is accounted for in the CSV file, could you provide an endpoint which would indicate the number of matches for storage between the CSV file and the billing data?

gz#654

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-35) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
@AjayTripathy isn't there already an existing endpoint used for nodes?

**Comment by AjayTripathy** [comment]
Yes, we should just extend that endpoint to return additional data.
