### ISSUE TITLE
provide warning in the UI that use of non-valid Prometheus characters in label settings and/or filters can potentially merge with other labels

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#102]
**Describe the bug**
From the kubernetes spec: 

> Labels are key/value pairs. Valid label keys have two segments: an optional prefix and name, separated by a slash (/). The name segment is required and must be 63 characters or less, beginning and ending with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between. The prefix is optional. If specified, the prefix must be a DNS subdomain: a series of DNS labels separated by dots (.), not longer than 253 characters in total, followed by a slash (/).

Prometheus only supports underscores in label names, so if you have an aggregation on label foo.bar and on foo-bar, they will both be merged to the label foo_bar in prometheus and therefore all costs will be charged to foo_bar in kubecost.

**Expected behavior**
Kubecost should reject invalid prometheus label characters as first class aggregation labels (owner, product, etc.)

**Comment by dwbrown2** [comment]
@AjayTripathy any updates in your thinking here?

**Comment by AjayTripathy** [comment]
I suspect we're just going to have to live with this one. I think it's worth warning in the UI if you try to add these or filter by them.

**Comment by kirbsauce** [comment]
@AjayTripathy, should we rework this as a request for a warning in the UI?

**Comment by AjayTripathy** [comment]
Yes, I'd say feel free to rename this issue and we can get it prioritized.

**Comment by dwbrown2** [comment]
Could we even just start with a quick addition to our API docs? Then bring this to the product in a future release?

**Comment by kirbsauce** [comment]
Assuming this is related to the labels set in /settings.html, and the like, I can't seem to find the applicable doc to enhance.  With a pointer and/or details I can take a stab at a doc update.

**Comment by AjayTripathy** [comment]
https://github.com/kubecost/docs/blob/master/allocation.md#allocation-schema-version-176 Maybe the properties field here?

**Comment by Adam-Stack** [comment]
test

**Comment by Adam-Stack-PM** [comment]
@AjayTripathy Closing out do to age. Reopen if you still feel this is important.
