### ISSUE TITLE
high load balancer costs for short-lived load balancer Service objects

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1022]
User has tests which spin up, among other things, nginx and a load balancer, wait for a connection to something, make a few calls to see if everything looks good, then spins everything down.  He says these run every 15 minutes and last about 5 minutes.  Kubecost is reporting these load balancers cost anywhere from $4-$8/run.  Our load balancer cost is $0.025/hour.

gz#667

**Comment by kbrwn** [comment]
gz#655

**Comment by dwbrown2** [comment]
Discussed Niko picking this up this week! Updates to come.
