### ISSUE TITLE
Fractional GPU support

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1023]
The user has expressed an interest in being able to charge fractional GPUs.  An example of how fractional GPUs are set can be found here -> https://docs.run.ai/developer/inference/submit-via-yaml/#submit-inference-workloads-allocating-fractions-of-a-gpu

gz#668

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-36) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
Supper for this is coming in Kubecost 2.0 release.
