### ISSUE TITLE
add functionality to recover sku id metrics for VMs

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1024]
As sku ids are at the lowest level, it would be useful to recover sku id metrics and map them to the appropriate VMs.

gz#670

**Comment by dwbrown2** [comment]
Any more context on what this would be used for?

**Comment by kirbsauce** [comment]
I'm very well-versed on the details, but I believe there are metrics (cpu/mem/etc) for skus, and these could be bucketed and rolled up to/associated with a labeled VM.  Will look for @AjayTripathy for confirmation.

**Comment by dwbrown2** [comment]
GCP just added more granularity to compute billing rates on a per instance level. It should now be possible as of very recently to map discounts back to individual assets, e.g. nodes. Will, is this the same request? Let me know if it's something simpler. If it's just tell me my discounts for N1's in Account X, we should already support that.

**Comment by kirbsauce** [comment]
@ErnestG4 , wanted to make sure you saw the question from @dwbrown2 on 4/27

**Comment by kirbsauce** [comment]
@AjayTripathy is this handled by our most recent improvements for GCP billing accuracy?

**Comment by AjayTripathy** [comment]
Yes! Let's note this and see if we can get feedback from relevant users!
