### ISSUE TITLE
Chart Dependency Issue

### ISSUE THREAD

**Issue by rlandesman** [kubecost/cost-analyzer-helm-chart#1025]
**Describe the bug**
Hi all! I'm currently unable to lint the kubecost helm chart due to a dependency issue with the `Chart.yaml` file. When linting, I get the following issue (despite having only enabled the prometheus subchart, not the other two).

```bash
[ERROR] /var/folders/.../kubecost/cost-analyzer/1.84.0/cost-analyzer: chart metadata is missing these dependencies: grafana,prometheus,thanos
```

**Expected behavior**
Sub-charts are declared as dependencies if the user enables them, otherwise they are removed.

gz#673

**Comment by AjayTripathy** [comment]
Hi @rlandesman could you share a little bit more about how you're downloading/installing the app? What version of helm are you using? What linter? I'm guessing this doesn't prevent install, just linting?

**Comment by rlandesman** [comment]
Hi @AjayTripathy, any progress on this? My automated `helmfile lint` tests are failing due to this issue and I'd like to get it sorted. Let me know if I can help out at all!

**Comment by AjayTripathy** [comment]
Hi @rlandesman thanks for following up. Subcharts/dependencies haven't been playing well with other methods of deployments and I'm hesitant to re-add a block for dependencies as opposed to just letting the charts live in a subdirectory which seems to just work. 

There's quite a few related bugs with running a dependencies block and we aim for compatibility across as many versions as possible  ( eg https://github.com/helm/helm/issues/8955) . Is there some sort of obvious solution I've missed?

**Comment by rlandesman** [comment]
I read around a bit and it seems that this is a know issue among the Helm community. I believe the recommended path forward would be to use the managed dependencies section in the `Chart.yaml`. Could you bring this up with the other maintainers of this chart and see how they feel about this? It seems to be the path forward in terms of modernizing the chart and keeping it up to date with upstream Helm recommendations.

Thanks again!

**Comment by jeisonarenales** [comment]
Hi, @rlandesman I'm getting the same issue in my pipeline. Did you figure out how to solve it?

**Comment by rlandesman** [comment]
> Hi, @rlandesman I'm getting the same issue in my pipeline. Did you figure out how to solve it?

Not a pretty resolution but we just run helmfile with the `--selector name!=kubecost` flag to avoid linting it.

**Comment by keithhand** [comment]
Hi @jeisonarenales and @rlandesman, I have a solution that modifies the `Chart.yaml` to include the dependency blocks with specific local file paths. You're welcome to check out those changes [here](https://github.com/kubecost/cost-analyzer-helm-chart/pull/1192), and you can fork the chart right now if you need. We are currently working on testing to make sure those changes go across smoothly, and I'll make sure to post an update here with an official version number once they are in the chart.

**Comment by keithhand** [comment]
Hi @rlandesman and @jeisonarenales, changes to the dependency block got merged to the development branch/nightly build yesterday. These changes should resolve this issue. You can test these changes using the nightly chart by following the instructions [here](https://guide.kubecost.com/hc/en-us/articles/4407601825431-Kubecost-Release-Process#nightly-releases) or using the next release of the application, planned for the first Tuesday of every month. I will close this out, but please re-open it if your issues persist.
