### ISSUE TITLE
Allow saved reports based on multiple pod labels

### ISSUE THREAD

**Issue by sellers** [kubecost/cost-analyzer-helm-chart#1028]
**What problem are you trying to solve?**
As a team, I want to be able to save a report that shows the costs of my applications by multiple labels so that I can have one report that captures all of my apps using a set of labels

**Describe the solution you'd like**
In the Reports UI under filters, I'd like to be able to add an additional filter based on labels: and not have it replace the existing filter based on labels

**Describe alternatives you've considered**
The alternative I have is to create multiple reports for the different labels that I want to group on (e.g if I have an owner: xxx  and a newowner-tag:xxx I have to have two reports because we changes our convention for tagging) 

**How would users interact with this feature?**
The same way they do now, but to change a filter for a label, they would have to add the new one and click the (x) to remove the old one instead of having it auto replace. 

gz#681

**Comment by kbrwn** [comment]
hi @sellers you can pass a comma separated list of labels to pass multiple labels to a report. Example: `app:cost-analyzer,app:prometheus`

**Comment by dwbrown2** [comment]
@sellers did that feature/recommendation meet you use case? Let us know if we can get you anything else!

**Comment by kbrwn** [comment]
@sellers closing this out. Feel free to re-open if you need any further assistance.

**Comment by sellers** [comment]
Yes, this does address my request. (sorry, was out of pocket since last week).  I didn't realize I could do the common separated list in the UI and was instead using the (+) to add more lines which were replacing.  Kudos.
