### ISSUE TITLE
make configmap name configurable

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1037]
Currently, there is a requirement that the configmaps are named a certain way.  This prevents the ability to identify Kubecost resources in the cluster by name.

The ask is to make the configmap name configurable.

gz#697

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-38) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
We've made a large number of configmap names configurable for our upcoming release, expected in 1.87.0
