### ISSUE TITLE
Allow configuration of the `imagePullPolicy` rather than hard-coding `always`

### ISSUE THREAD

**Issue by dcherman** [kubecost/cost-analyzer-helm-chart#104]
Would be nice to be able to configure the imagePullPolicy to save on startup speed when a given node has already previously pulled a given image

**Comment by dwbrown2** [comment]
+1 on this. I'm definitely supportive. We may not be able to squeeze into this week's release, but could look to address soon after. We would welcome a PR here too if you're interested!

**Comment by dwbrown2** [comment]
@mbolt35 going to investigate this week

**Comment by mbolt35** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/pull/113

**Comment by dwbrown2** [comment]
LGTM, @dcherman anything else you would want here?

**Comment by dcherman** [comment]
Nope this looks great!

**Comment by dwbrown2** [comment]
Marking this as closed but please feel free to reopen if there are any outstanding tasks!
