### ISSUE TITLE
Support accurate PV costs for Pods that share PVCs

### ISSUE THREAD

**Issue by nikovacevic** [kubecost/cost-analyzer-helm-chart#1040]
**What problem are you trying to solve?**
When a pod shares a PVC with other pods, the associated PV cost can be duplicated per pod instead of being divided among the pods. The allocated PV costs should be shared among pods, so that they don't get duplicated.

**Describe the solution you'd like**
PV costs for shared PVCs should be shared among the associated pods.

**Describe alternatives you've considered**
The workaround here is to only allow one-to-one relationships of pods and PVCs.

gz#708<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1125'>Zendesk ticket #1125</a>)<br>gz#1125</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-39) by [Unito](https://www.unito.io)

**Comment by Sijoma** [comment]
Hi all, @kbrwn brought me here. We are using Kubecost and run into this issue with our elasticsearch StatefulSets. We raised this as a support-ticket some time ago. 

The situation: we have two pods running elasticsearch itself and the metrics-exporter. 

I would be interested whether one could configure to only attribute these costs to elasticsearch itself instead of also the stateless metrics-exporter.

**Comment by nikovacevic** [comment]
Hi @Sijoma thank you for the question.

First, I'm going to make sure I understand the situation:
* There is a StatefulSet, which controls two (or more) pods
* Each of those pods has a PVC claiming a single, shared PV
* Within each of those pods, there are two containers (`elasticsearch` and `metrics-exporter`)
* You would like to have a way to assign 100% of each pod's PV costs to `elasticsearch`, and 0% of PV costs to `metrics-exporter`

Do I have that right?

If so -- then, for now there is no way to manually configure different sharing of costs, resources, etc. with different pods/containers/etc. If there is a PVC expressing a relationship between a pod and a PV, then all containers within that pod will share the costs of the PV evenly.

In other parts of Kubecost, when sharing of costs and resources is ambiguous, we have implemented cost-weighted sharing. (For example, if we were to do that here, and `elasticsearch` were 10x more expensive than `metrics-exporter`, then `elasticsearch` would be given 10x more PV cost than would be given `metrics-exporter`.) Would a proposal like that also satisfy your needs?

**Comment by Sijoma** [comment]
Hi @nikovacevic , yes that is correct.

I don't want to attribute any costs of the PV to the metrics-exporter as it is not using that PV. I'm not sure but my feeling is that there are many examples where this is the case? 

E.g. when you use linkerd a sidecar container also attaches to the pod. Would the costs of the PV also be shared evenly? 

You proposal sounds like it is in the right direction. I'm just not sure if its 10x more or 90% of the costs.

**Comment by nikovacevic** [comment]
I'm open to other proposed solutions, but I don't think Kubecost has a way of knowing whether a container "uses" a PV or not, which itself is an ambiguous term. (Would that include reads and writes? Would that be measured in bytes written and read, or time accessing the disk? It's difficult to pin down, and more difficult to monitor such metrics at scale.)

So I've opened a new ticket here with the proposed solution, so that you can track progress: https://github.com/kubecost/cost-analyzer-helm-chart/issues/1265

Do you have any other questions about this issue? If not, then we'll likely close this particular ticket now that https://github.com/kubecost/cost-model/pull/1036 is merged and set to be released next week.

**Comment by Sijoma** [comment]
I'm all good. Its not the biggest issue at the moment for us.

**Comment by nikovacevic** [comment]
Okay, thank you. Closing this ticket, but we will update the other ticket when we have a solution for cost-weighting.

**Comment by AdamStack18** [comment]
@kbrwn, could you provide the context behind why you reopened this issue? It will help me route it accordingly.
