### ISSUE TITLE
v1beta1 ClusterRoleBinding and v1beta1 Ingress are unavailable in v1.22+

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-analyzer-helm-chart#1046]
**Describe the bug**

It is not possible to install the chart in K8s v1.22.
This is because the chart uses APIs that have been deprecated for some time and removed in version v1.22.

Specifically the Ingress (https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122) and the ClusterRoleBinding (https://kubernetes.io/docs/reference/using-api/deprecation-guide/#rbac-resources-v122)

```
rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
``` 

**To Reproduce**

1. Try to install the chart in a cluster running K8s v1.22

**Expected behavior**

Be able to install the chart.

**Screenshots**

Not relevant

**Collect logs (please complete the following information):**

Not relevant

gz#733

**Comment by pierluigilenoci** [comment]
Is this issue fixed?

**Comment by kirbsauce** [comment]
yes, this should be fixed in 1.86.0.

**Comment by pierluigilenoci** [comment]
@kirbsauce I would definitely say no:

<img width="1187" alt="Screenshot 2021-09-09 at 18 39 25" src="https://user-images.githubusercontent.com/36044817/132727129-5a880999-a6b9-43fb-974c-499e3c61d26c.png">

**Comment by kbrwn** [comment]
@pierluigilenoci Closing this out as it should be fixed by a previous release. If you notice otherwise please feel free to reopen. Often times these "is deprecated in" messages are warnings that do not prevent kubecost from proceeding to install with the correct apiVersion type.
