### ISSUE TITLE
Allow drill down into label aliases on Cost Allocation page

### ISSUE THREAD

**Issue by nikovacevic** [kubecost/cost-analyzer-helm-chart#1051]
**What problem are you trying to solve?**
We should allow drill down into aggregations by label aliases on the Cost Allocation page.

**Describe the solution you'd like**
It should work like labels.

**How would users interact with this feature?**
Just like drilling down into labels.

gz#746

**Comment by kbrwn** [comment]
Resolved by v1.87.0
