### ISSUE TITLE
UI Bar Overlap

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1053]
Long cluster names can cause UI components to overlap. 

The proposed solution is to truncate long names and append "...".

gz#748

**Comment by kirbsauce** [comment]
@nikovacevic

**Comment by dwbrown2** [comment]
@kirbsauce have a screenshot or more context about where in the app this happens?

**Comment by dwbrown2** [comment]
What page is this on?

**Comment by kirbsauce** [comment]
My understanding is the cost allocation page, as this is the only place I can see a namespace name consumes horizontal real estate.  My plan is to create a namespace on my test cluster and deploy a bare-bones app, as simply narrowing the browser doesn't repro the issue.

**Comment by nikovacevic** [comment]
Just affects new React pages. Looks like this:
![Screenshot from 2021-08-31 16-12-00](https://user-images.githubusercontent.com/8070055/131582482-4e3c622d-8977-4a8a-96c9-e5b8e36e6b09.png)

**Comment by kirbsauce** [comment]
Ah, so it's a long cluster name, not a long namespace name.  A picture is worth a thousand words...or at least one word in this case.

**Comment by dwbrown2** [comment]
PR merged and expected to be in our next release.
