### ISSUE TITLE
Provide indication as to where to focus for the recommendation

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1056]
**What problem are you trying to solve?**
Create a more descriptive UI which allows the user to focus on the driving metrics for a recommendation.  For example...
![image](https://user-images.githubusercontent.com/46360304/131759470-0aadf12b-caf5-4265-b825-98464360baed.png)

Here, disregarding the highlighted efficiency values, cpu recommendations for what is identified as an over-provisioned pod are to increase the requests, but the real driver for the recommendation is a reduction in memory.

**Describe the solution you'd like**
Any sort of highlight, or possibly a greying of the non-contributing metrics, which would in turn highlight the adjustments to act on the recommendation.

**Describe alternatives you've considered**
Documentation, but not as an alternative but rather as a supplement

**How would users interact with this feature?**
Via the UI, but would likely require this information to be passed back through the APIs to the front-end, so potentially via API too?

kbrwn for review

gz#754

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-40) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
I think I know where this is going but any more context would be helpful... From my reading, the request is to help the user focus as much as possible on what's actionable. In this case, both cpu and memory recs are actionable so I may be missing broader context.

**Comment by kirbsauce** [comment]
This example is for over-provisioned pods, so my understanding is this particular cpu recommendation would be action against an under-provisioned pod, where ram is over-provisioned.  Actionable yes, but intuitively, if I'm looking at over-provisioned recommendations, I'm expecting to see reducing as opposed to increasing.  This issue is filed in a general nature, but the context of the example is over-provisioning.

**Comment by kirbsauce** [comment]
Touching this as two other users have voiced confusion over inverted recommendations as it relates to the overall intent of the page (over-provisioned workloads).
cc @teevans
