### ISSUE TITLE
Ensure CSV export numbers match UI/k8s resource indicators (Gi, Mi, etc)

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1058]
**What problem are you trying to solve?**
It's tedious to have to make adjustments to the cpu and ram numbers in a CSV export

**Describe the solution you'd like**
CSV export to match what I see in the UI

**Describe alternatives you've considered**
Writing a macro?

kbrwn for review

gz#756

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-42) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
Appreciate the report, but can we start sharing just a bit more context in this reports if possible?

Is this CSV export in right-sizing recommendations? Specifically asking for conversion between bytes and Mb, Gb, etc?

**Comment by kirbsauce** [comment]
Apologies...yes, the request sizing recommendations page was the specific example.  My assumption was there were likely other pages which this would apply to but I can't seem to find any.

**Comment by dwbrown2** [comment]
This feels relatively low priority to me, but let me know if there's impact I'm missing. 

Adding a unit to the field will generally make it harder to sort / run computations against which is what a lot of teams are doing with CSV.
