### ISSUE TITLE
Spot Checklist fails to load with a freshly-created deployment

### ISSUE THREAD

**Issue by michaelmdresser** [kubecost/cost-analyzer-helm-chart#1059]
**Describe the bug**

Right after creating a deployment, the spot checklist will fail to load with the following error:
```
error(s) estimating savings: 1 error occurred:\n\t* failed to get allocations: all AllocationSets for ASR cluster-one/NAMESPACE/deployment/DEPLOYMENTNAME were empty\n\n
```

**To Reproduce**

1. Create a new deployment
2. Load the spot checklist
3. Observe error in console

**Expected behavior**

The spot checklist should still load.

gz#763

**Comment by michaelmdresser** [comment]
I believe this happens because the checklist is initially built from the K8s API, which is always up to date, but it then tries to pull cost information from ETL to estimate savings. ETL does not yet have the data, so it fails. I think the correct way to handle this is to have empty savings estimates when this happens.

**Comment by dwbrown2** [comment]
+1 on that suggestion, with maybe a later solution saying "Collecting cost data..."

**Comment by michaelmdresser** [comment]
Resolved in code, should be fixed in the next release. Agreed, we can add better messaging too.
