### ISSUE TITLE
Grafana links from Kubecost have an extra / in the URL

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1060]
user is reporting URLs of the form 
<grafana>//d/JOUdHGZZz/kubecost-cluster-metrics
<grafana>//d/at-cost-analysis-pod/pod-cost-and-utilization-metrics?from=now-1d&orgId=1&var-costStorageStandard=0.044&var-costStorageSSD=0.187&var-costDiscount=30&var-namespace=yyy&var-pod=xxx

We have more information via screenshots not shared here for privacy reasons.

gz#765

**Comment by dwbrown2** [comment]
Thanks for reporting! These aren't breaking Grafana dashboard page loads
are they?

Webb
Kubecost, Co-founder

**Comment by kirbsauce** [comment]
My understand is yes, but only for custom Grafana.  values.yaml file looks good but we're seeing the added '/' in settings.html.  Next step is to try after removing it from settings.html.

**Comment by kirbsauce** [comment]
This turned out to be an issue with the setting being duplicated in the UI with an additional slash.  Closing.
