### ISSUE TITLE
Request right-sizing suggests requests that are higher than expected.

### ISSUE THREAD

**Issue by michaelmdresser** [kubecost/cost-analyzer-helm-chart#1061]
**What problem are you trying to solve?**

Request right-sizing suggests higher requests than it used to (pre-max change) because the old algorithm used quantiles+headroom and needed a larger headroom. Because the new algorithm uses max usage, we should adjust the default headroom percentages (and probably make them adjustable on the UI because the new algorithm is more performant).

**How would users interact with this feature?**

Adjustable percentage of headroom, more granular list of headrooms, or changing "profile" names to not make a 90% target usage as scary as it looks (currently I believe it is called "Development" and I think should actually be "Production").

gz#766

**Comment by dwbrown2** [comment]
I pretty strongly believe that we need to bring back quantile metrics to do this correctly for all situations! Happy to elaborate if interested.

**Comment by michaelmdresser** [comment]
I'd like to hear your thoughts about why quantile is required here.

**Comment by dwbrown2** [comment]
The simple explanation is that on my dev cluster I actually don't care about the max at all. For example, I'm perfect fine being cpu throttled 5-10% of the time if it will save me meaningful % of cost. It's not crazy to see a scenario where median usage is 500 millicpu, p90 is 1 cpu, and max is 2+ cpu. Strictly taking a discount of max won't get to my desired level.

**Comment by michaelmdresser** [comment]
Quantile support added in the v2 request sizing API, see docs: https://github.com/kubecost/docs/pull/371. Progress is proceeding on the FE integration.
