### ISSUE TITLE
Allow drill-down into unallocated

### ISSUE THREAD

**Issue by nikovacevic** [kubecost/cost-analyzer-helm-chart#1069]
## What problem are you trying to solve?
We should allow drill down into unallocated aggregations on the Cost Allocation page.

## Describe the solution you'd like
It should work like all other drill-downs: show the allocations that cannot be allocated to an aggregation.

## How would users interact with this feature?
Just like all other drill-downs.

**Comment by kbrwn** [comment]
Resolved by v1.87.0
