### ISSUE TITLE
ETL cache lifecycle

### ISSUE THREAD

**Issue by B-Souty** [kubecost/cost-analyzer-helm-chart#1073]
Hi,

my persistent volume is filling up with ETL cache data. Is it worth keeping several months worth of it? Is there a setting to garbage collect them after a set amount of time?

gz#822

**Comment by kbrwn** [comment]
@B-Souty You can set the length of the data to build off of the values.yaml file. [L219-L222](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L219-L222)

You might also find some useful info in the[ storage documentation.](https://github.com/kubecost/docs/blob/master/storage.md)

**Comment by B-Souty** [comment]
@kbrwn Thanks, exactly what I was looking for.
