### ISSUE TITLE
Aggregating Assets by Category provides shifting results for Compute

### ISSUE THREAD

**Issue by nikovacevic** [kubecost/cost-analyzer-helm-chart#1087]
**Describe the bug**
Aggregating by Category for a complete date range should provide stable, accurate results. However, refreshing the results creates shifting total numbers. Drilling into Compute category then provides a stable result (although the shared costs seem to interfere with clarity here, too.)

**To Reproduce**
1. Go to Assets page and pick a historical date range (e.g. last week)
2. Aggregate by Category and note the total and Compute total
3. Refresh the results a few times and note whether or not the numbers change

**Expected behavior**
The numbers should be stable and accurate.

**Screenshots**
![Screenshot from 2021-09-28 18-32-01](https://user-images.githubusercontent.com/8070055/135183757-31029ff4-9b92-4eb8-9807-a307cea8c7d8.png)
![Screenshot from 2021-09-28 18-32-12](https://user-images.githubusercontent.com/8070055/135183759-10c5494c-faf3-4da2-9d29-1b62b65281da.png)
![Screenshot from 2021-09-28 18-32-24](https://user-images.githubusercontent.com/8070055/135183762-7679aea8-ba34-46aa-a467-e10304fc8b1b.png)
![Screenshot from 2021-09-28 18-32-40](https://user-images.githubusercontent.com/8070055/135183764-2eabe934-5380-4454-b69c-81f8e349a29d.png)

**Comment by dwbrown2** [comment]
@Sean-Holcomb still on hold for this one? My understanding is that this only happens in specific edge cases...

**Comment by Sean-Holcomb** [comment]
This issue was addressed by https://github.com/kubecost/cost-model/pull/966
