### ISSUE TITLE
Infinite spinner when hiding _idle_

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1089]
**Describe the bug**
v1.87.0

Setting _idle_ to hide in cost allocation presents infinite spinner

**To Reproduce**
1. Cost allocation
2. Aggregate by cluster (cluster visible, with _idle_ line item)
3. Set _idle_ to "Hide"

/allocations.html?context=W10%3D&agg=cluster&filters=W3sicHJvcGVydHkiOiJjbHVzdGVyIiwidmFsdWUiOiJjbHVzdGVyLW9uZSJ9XQ%3D%3D&idle=hide

I also see this in the Chrome console:
```
Uncaught (in promise) TypeError: (0 , q.captureError) is not a function
    at index.jsx:788
    at f (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at f (runtime.js:63)
    at e (runtime.js:154)
    at runtime.js:164
```

**Expected behavior**
_idle_ line item should be removed

**Screenshots**
![image](https://user-images.githubusercontent.com/46360304/135309443-4436c01a-7647-4fbb-80fb-fb95cded43c1.png)

![image](https://user-images.githubusercontent.com/46360304/135309676-d5ad3c99-6a38-4af1-9225-9cee135b534d.png)

**Comment by kirbsauce** [comment]
This has been reproduced by engineering and will be fixed in the next release.

**Comment by Adam-Stack-PM** [comment]
@kirbsauce Closing this issue out due to age and there is another bug we are tracking related to this item.
