### ISSUE TITLE
Cost analyzer frontend listens on IPv4 interface in IPv6 only cluster

### ISSUE THREAD

**Issue by mikestef9** [kubecost/cost-analyzer-helm-chart#1092]
**Describe the bug**
Running kubecost in a cluster with IPv6 only pods. The cost analyzer frontend container listens on IPv4 interface, instead of IPv6. This prevents load balancer health checker from accessing and getting status of kubecost.

**To Reproduce**
Launch kubecost in an IPv6 cluster. Verify pod is running with only IPv6 address

```
kubectl describe pod kubecost-cost-analyzer-5d4c7b8976-7zztq -n kubecost

Name:         kubecost-cost-analyzer-5d4c7b8976-7zztq
Namespace:    kubecost
Priority:     0
Node:         ip-192-168-189-168.us-west-2.compute.internal/2600:1f13:dca:9b02:4fce:dd73:4824:90b2
Start Time:   Sat, 02 Oct 2021 12:58:21 -0700
Labels:       app=cost-analyzer
              app.kubernetes.io/instance=kubecost
              app.kubernetes.io/name=cost-analyzer
              pod-template-hash=5d4c7b8976
Annotations:  kubernetes.io/psp: eks.privileged
Status:       Running
IP:           2600:1f13:dca:9b02:e8b0::5
IPs:
  IP:           2600:1f13:dca:9b02:e8b0::5
Controlled By:  ReplicaSet/kubecost-cost-analyzer-5d4c7b8976
...
```

Get listen addresses of kubecost cost analyzer container
```
kubectl exec -i -t kubecost-cost-analyzer-5d4c7b8976-7zztq -n kubecost --container cost-analyzer-frontend -- netstat -tunlp

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:9090            0.0.0.0:*               LISTEN      1/nginx: master pro
tcp        0      0 :::9001                 :::*                    LISTEN      -
tcp        0      0 :::9003                 :::*                    LISTEN      -
```

**Expected behavior**
I expect the cost analyzer frontend container to listen on IPv6 `:::9090`, not IPv4 `0.0.0.0:9090`. 

**Collect logs (please complete the following information):**

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-frontend` and paste the output here:

```
kubectl logs kubecost-cost-analyzer-5d4c7b8976-7zztq -n kubecost cost-analyzer-frontend
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2021/10/02 19:58:56 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
2021/10/02 19:58:56 [notice] 1#1: using the "epoll" event method
2021/10/02 19:58:56 [notice] 1#1: nginx/1.21.1
2021/10/02 19:58:56 [notice] 1#1: built by gcc 10.3.1 20210424 (Alpine 10.3.1_git20210424)
2021/10/02 19:58:56 [notice] 1#1: OS: Linux 5.4.141-67.229.amzn2.x86_64
2021/10/02 19:58:56 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2021/10/02 19:58:56 [notice] 1#1: start worker processes
2021/10/02 19:58:56 [notice] 1#1: start worker process 22
2021/10/02 19:58:56 [notice] 1#1: start worker process 23
2021/10/02 19:58:56 [notice] 1#1: start worker process 24
2021/10/02 19:58:56 [notice] 1#1: start worker process 25
```

**Comment by AjayTripathy** [comment]
Hi @mikestef9 thank you for this detailed bug report. While I agree that we should make this work by default for ipv6, as a workaround until we can do that, you should be able to configure the port(s) that the cost-analyzer-frontend listens on with .Values.service.targetPort and .Values.service.port (https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-service-template.yaml#L1). 

Does that proposed workaround help?

**Comment by mikestef9** [comment]
I'm not sure how changing the port would help here, because the container would still listen on ipv4 addresses, not ipv6, just with a different port.

**Comment by AjayTripathy** [comment]
Ah, sorry, let me see if I can clarify my thinking for the proposed workaround. The "port" is actually an arbitrary string, so you can inject a parameter to the "listen" directive to force ipv6 [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml#L104
)
This is the directive you might inject: [::]:80 ipv6only=on;

So once injected the directive reads
`listen [::]:80 ipv6only=on;`

Which should force ipv6
Again-- just a bit of a hack I thought I'd propose while we sort this out on our end :)

**Comment by mikestef9** [comment]
Ahh I see. Thx that worked like a charm! I'll keep this issue open to track the fix by default for ipv6.

**Comment by AjayTripathy** [comment]
(Just a note to the future implementer, this [article](https://ma.ttias.be/enable-ipv6-connectivity-for-nginx/) was useful and I actually think we want to by default listen to both the ipv4 and ipv6 so ideally we edit the helm chart to do something like this by default

```
server {
        listen          :9090;
        listen          [::]:9090;
        server_name     a.b.c;
}
```
