### ISSUE TITLE
Support custom priorityClass in cost-analyzer deployment manifest

### ISSUE THREAD

**Issue by AshutoshNirkhe** [kubecost/cost-analyzer-helm-chart#1097]
**What problem are you trying to solve?**
Currently I can't pass my own (pre-created) priority class to the helm chat values.

**Describe the solution you'd like**
Currently helm takes care of create a new priority class if we set 'priority.enabled' to true. But we can't pass our pre-created priority class. We just need to add an 'else' condition to https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L806 to support custom priority class name/value and should be good.

**Describe alternatives you've considered**

**How would users interact with this feature?**

gz#892

**Comment by AjayTripathy** [comment]
Hi @AshutoshNirkhe we're a bit backed up on supporting additional features, but we'd gladly review a PR here that meets your needs! Otherwise, we can expect to get to this in a few releases.
