### ISSUE TITLE
Provide ability to export reports at the granularity of the chart as opposed to the summary table  

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1099]
**What problem are you trying to solve?**
Given the following report, I would like the csv export to contain the daily breakdown, as indicated by the chart.  Currently, it outputs the table, which is the aggregation over the window.
![image](https://user-images.githubusercontent.com/46360304/136440264-4857b1e9-ac81-4121-907f-399daa831001.png)

**Describe the solution you'd like**
For this example, I would like the daily breakdown.

**Describe alternatives you've considered**
Post-processing the response of a direct API request as a stepping stone, but there are scalability issues.

**How would users interact with this feature?**
Either via separate download buttons next to the chart and table or the download button is a dropdown w/chart and table options.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-47) by [Unito](https://www.unito.io)

**Comment by nikovacevic** [comment]
I don't really understand the request. Given that a CSV is a table of columns (e.g. CPU, RAM, Efficiency, etc.) and rows (e.g. kubecost, __idle__, etc.) how would one express a third dimension? The JSON payload for these queries does that with an array of objects (i.e. an AllocationSetRange of AllocationSets, each representing a one day window). If you want the equivalent, I think the closest would be to make seven 1d queries (one for each day in the range) with `format=csv` and then the daily detail is found in one of those CSVs.

Other ideas would be to combine them, I guess? Like columns `CPU, RAM, ..., 2021-10-30-Total, 2021-11-01-Total, ...`, but that sounds kind of strange to me.

Let me know if any of these ideas move the ball forward. Happy to just on a call to help, if you're interested.

**Comment by kirbsauce** [comment]
@nikovacevic , I'll be sending over some information that should help make sense of the ask

**Comment by kirbsauce** [comment]
I realize now that the issue is better explained if the chart in the original post is "cumulative" instead of "Daily".

**Comment by mclean0328** [comment]
@kirbsauce and I spoke with a customer recently and when downloading CSV from the assets page, it defaults to downloading the aggregated information and the sheet is not broken down by day.  The customer desire would be to see the asset data per day, as represented in the graph at the top of the page. We did consider using the API to get this information, but any format other than json forces you to the aggregated data.

<img width="1413" alt="Screen Shot 2023-01-05 at 5 14 08 PM" src="https://user-images.githubusercontent.com/50640513/210890579-3d22dab7-5fe9-4543-942d-a899e18319fd.png">

**Comment by nikovacevic** [comment]
Can you help me understand what is wrong/missing from the Asset API? If you have `accumulate=false` you'll receive JSON data (which hydrates that chart) per-day.

**Comment by nikovacevic** [comment]
e.g. http://demo.kubecost.io/model/assets?window=7d&accumulate=false&aggregate=type
![Screenshot from 2023-01-05 17-23-29](https://user-images.githubusercontent.com/8070055/210904935-be06c12a-4e11-4d6a-a4d6-919a0e7c8a90.png)

**Comment by mclean0328** [comment]
I don't think there is anything missing from the API in regards to the data being returned in JSON.  As you mentioned, the returned data is broken up by day which is what the customer wants.  The ask is regarding data returned and then dumped to CSV.  If you try to download the report from the UI to CSV or use the API to dump to CSV using `&format=csv`, the CSV sheet is exported with accumulated data and the data is not broken up by day.

**Comment by nikovacevic** [comment]
So if we added a "Download JSON" that pulled down the raw JSON API result, that would suffice?

**Comment by nikovacevic** [comment]
> We did consider using the API to get this information, but any format other than json forces you to the aggregated data.

This is what I'm wondering about. You already can directly use the API, and it will be formatted with JSON. Simply don't pass `format=csv`.

**Comment by mclean0328** [comment]
I'll let @kirbsauce weigh in when he has a second.  We are currently working with the customer on using the JSON output for their purposes.  This request is more for easy of use on their end.  They would prefer to just download a CSV to get the daily breakdown and not use JSON.

**Comment by kirbsauce** [comment]
For this particular customer, we're pursuing a number of options. One thing we've noted is that, while documented and WAI, the inconsistency in data segmentation by adding "format=csv" seems non-standard. They want to click a button on the UI and have the resulting csv time-sliced. The end-users, in this case, are not going to be able to programmatically parse and process JSON. We display time-sliced and aggregated data on the UI. When you click the download button, we have decided the user is best served with the aggregated data. They would like the time-sliced data.
