### ISSUE TITLE
Istio compatibility

### ISSUE THREAD

**Issue by sjmiller609** [kubecost/cost-analyzer-helm-chart#110]
**What problem are you trying to solve?**

We want to run Kubecost inside of Istio, which is one of the popular kubernetes service meshes.

**Describe the solution you'd like**

Helm installation works out of the box with Istio 1.3.0+. In my experience, some handling of Istio is required by components running within. For example, Istio works by attaching a container (i.e. sidecar) to all pods running an Envoy proxy. Istio/Kube (I'm not sure which should be responsible) does not clean these up appropriately when Kube Jobs complete, see this:
```
_ kubectl get pods -n kubecost
NAME                                                      READY   STATUS    RESTARTS   AGE
cost-analyzer-checks-1569940200-dkzld                     1/2     Running   0          4h29m
cost-analyzer-checks-1569940800-wxgmb                     1/2     Running   0          4h19m
cost-analyzer-checks-1569941400-qwxxf                     1/2     Running   0          4h9m
cost-analyzer-checks-1569942000-zc95c                     1/2     Running   0          3h59m
.... omitted a lot of 'em
cost-analyzer-checks-1569954600-n7cvv                     1/2     Running   0          29m
cost-analyzer-checks-1569955200-lcsg2                     1/2     Running   0          19m
cost-analyzer-checks-1569955800-z8wz9                     1/2     Running   0          9m37s
kubecost-cost-analyzer-5c9dcfd579-pd9zc                   4/4     Running   3          4h28m
kubecost-grafana-844d4b9844-8jz8c                         4/4     Running   5          4h36m
kubecost-prometheus-alertmanager-85bbbd6b7b-b5z96         3/3     Running   0          4h36m
kubecost-prometheus-kube-state-metrics-857c5d4b4f-gsxm9   2/2     Running   2          4h36m
kubecost-prometheus-node-exporter-tgbm5                   1/1     Running   0          4h36m
kubecost-prometheus-pushgateway-7689458dc9-frqcz          2/2     Running   0          4h36m
kubecost-prometheus-server-7b8b759d74-xrx2f               3/3     Running   0          4h36m
```
Above: Jobs are stuck at 1/2 because jobs must handle Istio like this https://github.com/istio/istio/issues/15041

There is also one other problem I have detected - this error message is presented by the front end when port-forwarding as described in the installation instructions, only when istio is enabled on the namespace
```
Unable to reach a Kubecost server, please ensure the service is available at http://localhost:9090/api or another address below.
```

**Describe alternatives you've considered**

In the meantime, I will try to make some kind of workaround for cleaning up the istio sidecars. I will debug to figure out why /api endpoint is not coming up when istio is enabled.

**How would users interact with this feature?**

It would allow helm installation of Kubecost into a namespace with istio enabled.

**Comment by dwbrown2** [comment]
A couple thoughts. First, I think we should expose a `kubecostChecks.enabled`, because my understanding if that you guys won't need it for your use case. Also, we can look to expose a quit endpoint for Istio too if needed. 

Let us know what you find while debuging this `/api` access issue. We'd need a little bit more information but happy to help here if we can.

**Comment by dwbrown2** [comment]
@sjmiller609, thanks to @mbolt35 we have a quick PR (https://github.com/kubecost/cost-analyzer-helm-chart/pull/113) that allows you to avoid this Istio issue outright! It should be in our build tonight/tomorrow. With this change, you can just pass `kubecostChecks.enabled: false` in your values.

Any progress on the `/api` access issue? Let us know how we can help here.

**Comment by sjmiller609** [comment]
Thanks Webb. I’ll let you know if I do dig in, we are just running it without istio for now, which is fine for assessing the product. This is not a high urgency.

**Comment by AjayTripathy** [comment]
@garreeoke This now works with your portname changes correct?

**Comment by dwbrown2** [comment]
A number of users are now running with Istio today, so I'll go ahead and close! Please feel free to re-open if there's more needed here. 

cc @kirbsauce
