### ISSUE TITLE
Duplicate metrics with kube-state-metrics v2

### ISSUE THREAD

**Issue by andreb89** [kubecost/cost-analyzer-helm-chart#1110]
**Describe the bug**
We had to deactivate the emitting of kube-state-metrics v1 of Kubecost, because labels were colliding and Prometheus threw errors, e.g. "many-to-many matching not allowed: matching labels must be unique on one side". We are using kube-state-metrics v2.

We set the following in the deployment config:

kubecostMetrics:
  emitPodAnnotations: false
  emitNamespaceAnnotations: false
  emitKsmV1Metrics: false

The Prometheus errors disappeared after that. This was some weeks ago. Since then I haven't looked into the costs in Kubecost specifically. So I didn't notice, that the cost allocation didn't work anymore as before the change above. Now if I click on a namespace, the deployments, statefulsets and pods are not listed anymore, only daemonsets and jobs. In some cases there is now a big block of __unallocated__ costs, in other cases not even that shows up.

Is there something wrong here with the deployment configuration, do I need to change anything with the metric emitting or can you give me any other advice here? Is Kubecost dependent on emitting the above metrics? Since that does not work for me, because of the colliding metrics.

**To Reproduce**
1. Deploy Kubecost with the above configuration
2. Check the cost allocation after a while

**Collect logs (please complete the following information):**
No error logs or anything else worth mentioning in the Kubecost logs.

gz#957

**Comment by AjayTripathy** [comment]
Hi @andreb89 thanks for the feedback. As a temporary fix, you can still do one of the following:
* remove the kube_pod_labels and kube_node_lables from the KSMv2 configs
* blacklist them from kubecost or ksmv2 metrics scraping on your prometheus

We will add additional diagnostics to make our metrics enumeration more clear (Expected in v1.89.0 mid Novembter)
We will look to support finer grained controls over what metrics kubecost emits (No ETA yet-- we'll still have to design this)

**Comment by andreb89** [comment]
@AjayTripathy thanks for the reply and mentioned temporary fixes. 

I updated the endpoint spec of the Kubecost ServiceMonitor as follows, so the duplicate metrics (kube_pod_labels and kube_namespace_labels) from the emit of KSM v1 metrics are dropped:

```
spec:
  endpoints:
  - honorLabels: true
    interval: 1m
    metricRelabelings:
    - action: drop
      regex: kube_(namespace|pod)_labels
      sourceLabels:
      - __name__
    path: /metrics
    port: tcp-model
    scheme: http
    scrapeTimeout: 10s
```

As a result, no more Prometheus errors and the old node capacity metrics (kube_node_status_capacity_cpu_cores & kube_node_status_capacity_memory_bytes) are also available. For now, I hope that with this setup/configuration Kubecost will compute costs correctly again.

**Comment by kbrwn** [comment]
@andreb89 thanks for the update! Let us know if you are having further issues with kubecost after making this change.
