### ISSUE TITLE
 Thanos-store should deploy PV/PVC by default

### ISSUE THREAD

**Issue by kbrwn** [kubecost/cost-analyzer-helm-chart#1114]
**What problem are you trying to solve?**

EmptyDir for thanos-store data volume can lead to out of space errors on node the pod is scheduled to.

**Describe the solution you'd like**

Thanos-store should make use of a PVC/PV to prevent this. 

**Describe alternatives you've considered**

Users can already define a PV/PVC so it may not be needed to force it on users. 

**How would users interact with this feature?**

helm values. yaml or --set cmd

**Comment by AjayTripathy** [comment]
Done! https://github.com/kubecost/cost-analyzer-helm-chart/pull/1121
