### ISSUE TITLE
Cluster node sizing recomendation should take region into consideration

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1117]
**What problem are you trying to solve?**
I'd like to use the cluster sizing recomendations, but it is recomendeding an instance size that is not available within my AWS region.

**Describe the solution you'd like**
AWS doesn't always have all instance sizes available in all regions. Kubecost should take that into consideration when making these type of recomendations.

**Describe alternatives you've considered**
none

**How would users interact with this feature?**
UI/API - Savings > Cluster Nodes Can Be Right-Sized

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-49) by [Unito](https://www.unito.io)

**Comment by srpomeroy** [comment]
The reion in question is `EU west 2 London` and the instance family in question is `A1`.

**Comment by kirbsauce** [comment]
@srpomeroy , Is this at all related to https://github.com/kubecost/cost-model/issues/985?

**Comment by srpomeroy** [comment]
It is. Didn’t realize we had two issues open on it. Shall we close this one?
