### ISSUE TITLE
Add support for Danish Krone (DKK)

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1118]
**What problem are you trying to solve?**
My cloud provider invoices me in Danish Krone (DKK), I would like to be able to view the cost in Kubecost with the same currency symbol.

**Describe the solution you'd like**
The ability to select DKK as a supported currency.

**Describe alternatives you've considered**
none

**How would users interact with this feature?**
Set via UI or helm values.

**Comment by kirbsauce** [comment]
fixed by https://github.com/kubecost/cost-analyzer-frontend/pull/467
