### ISSUE TITLE
image "kubecost1/sql-init" with chart version is not exist

### ISSUE THREAD

**Issue by ozbillwang** [kubecost/cost-analyzer-helm-chart#1134]
**Describe the bug**
the image uses Chart.AppVersion as part of tag, but one of the images using in this chart are not updated with latest chart version. 
```
image: {{ .Values.remoteWrite.postgres.initImage }}:prod-{{ $.Chart.AppVersion }}
```
For example, if I pull the image `gcr.io/kubecost1/sql-init` with tag `prod-1.88.0`, it is not exist, the rest images are fine.

```
$ docker pull gcr.io/kubecost1/sql-init:prod-1.88.0
Error response from daemon: manifest for gcr.io/kubecost1/sql-init:prod-1.88.0 not found: manifest unknown: Failed to fetch "prod-1.88.0" from request "/v2/kubecost1/sql-init/manifests/prod-1.88.0".
```

Check the image online, and seems 1.60.1 is the latest.

![image](https://user-images.githubusercontent.com/8954908/140676533-31fdece6-b6c5-499c-ae81-a2efd14c1e23.png)

gz#1000

**Comment by kbrwn** [comment]
hello @ozbillwang are you deploying the 'master' or 'development' branch of this repository? The code that makes use of this image is not yet in a major release (although it may be in a nightly) so I wouldn't expect it to have the container tag `prod-1.88.0`

**Comment by ozbillwang** [comment]
I run the `helm package` with latest release, and show this image.  Not sure this code comes from master or any other branch.

**Comment by Hoshiyo** [comment]
Hi @AjayTripathy @ozbillwang , do you use an other image to replace sql-init with latest release 1.90.1 or an alternative way to use `remoteWrite` ?

**Comment by ozbillwang** [comment]
no. with default values.yml, we don't need this image at all

**Comment by AjayTripathy** [comment]
This is deprecated-- we don't need this. Expect sql-init to be removed in an upcoming release. remotewrite should be used with a promQL database that supports it.
