### ISSUE TITLE
gcpSecretName not propagated into the application correctly

### ISSUE THREAD

**Issue by fourstepper** [kubecost/cost-analyzer-helm-chart#1135]
**Describe the bug**
When specifying the secret name for GCP integration in the helm chart via `gcpSecretName`, the key doesn't get properly propagated into the application, even though all the prerequisites seem to exist in the container.

```
/ $ ls /models/key.json
/models/key.json
/ $ echo $GOOGLE_APPLICATION_CREDENTIALS
/models/key.json
```

The error from `curl ../model/etl/status | jq`

```
....
    "cloud": {
      "redacted": {
        "cloudConnectionStatus": "Failed Connection",
        "cloudAssets": {
          "coverage": {
            "start": "2021-08-03T00:00:00Z",
            "end": "2021-11-15T00:00:00Z"
          },
          "lastRun": "2021-11-08T11:55:42.174587027Z",
          "nextRun": "2021-11-08T14:55:42.174169884Z",
          "progress": 1,
          "refreshRate": "3h0m0s",
          "resolution": "24h0m0s",
          "startTime": "2021-11-08T11:55:42.172201827Z"
....
```

The key and other settings are, however, correct - when I copy the contents of the key mounted to `/models/key.json` in cost-model container and paste it in the form at `/keyinstructions.html`, everything works out well and the cloud connection reports success once rebuilt.

`curl /model/etl/asset/cloud/rebuild?commit=true`
`curl ../model/etl/status | jq`

```
...
    "cloud": {
      "redacted": {
        "cloudConnectionStatus": "Connection Successful",
        "cloudAssets": {
          "coverage": {
            "start": "2021-10-24T00:00:00Z",
            "end": "2021-11-08T12:06:10Z"
          },
          "lastRun": "2021-11-08T12:06:11.331263027Z",
          "nextRun": "2021-11-08T12:06:10.643527397Z",
          "progress": 0,
          "refreshRate": "3h0m0s",
          "resolution": "24h0m0s",
          "startTime": "2021-11-08T12:06:10.643527282Z"

...
```

**EDIT: It seems that, by default, kubecost is reaching for a legacy key path (`/var/configs/key.json`), however I haven't been successful finding this reference in the code base of cost-model. If I copy `/models/key.json` to `/var/configs/key.json` and run rebuild, everything seems to work correctly.**

```
cost-model E1108 13:42:04.881686       1 log.go:17] [Error] ETL: CloudAsset[heu-infra-global]: Build[SjwMP]: QueryCloudAssets error: bigquery: constructing client: cannot read credentials file: open /var/configs/key.json: no such file or directory
```

**To Reproduce**
Detailed in the description

**Expected behavior**
The key should be propagated into the application from the secret automatically

**Collect logs (please complete the following information):**

```
$ helm ls -n kubecost
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
kubecost        kubecost        1               2021-11-08 12:52:28.392449 +0100 CET    deployed        cost-analyzer-1.88.0    1.88.0
```

gz#1002

**Comment by AjayTripathy** [comment]
Hi @fourstepper thank you for the detailed report--we're looking into this.

**Comment by kbrwn** [comment]
@fourstepper thanks again for submitting this bug report. This functionality is a bit older so this may have got overlooked. Assigning to engineer @mbolt35 for further review.

**Comment by mbolt35** [comment]
@fourstepper Thanks for all the information here - made this fix much simpler to track down!

**Comment by fourstepper** [comment]
@mbolt35 glad I could help :)
