### ISSUE TITLE
Cost allocation page UX enhancements

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1137]
1)
When viewing reports, It can be difficult to understand why the sum of costs for an individual item in the bar chart does not equal the total cost in the line item of the lower summary.  This is solved when you set the cost metric to "Cumulative Cost" will this hold true.  Some indicator that one is looking at a rate would help.

@nikovacevic wrote "I'd love to improve this. We could just start by adding " / day" or " / mo." after each value in the table. It's wordy, but also obvious. And/or we can change the table headers. Or we can give some other visual cue that users are viewing rate data instead of cumulative. Switching to a line chart is a nice idea, too. Any other thoughts?"

2)
When setting filters, it's not obvious how to, say, filter on two namespaces.  Making the '+' additive or adding an additional example would improve usability.

@nikovacevic wrote "let's add a comma-separated example to the helper text. We could probably make a better UX here by appending and making you click the little "x" to clear it if you want to."

**Comment by nikovacevic** [comment]
@nealormsbee do you think we can tackle this one while we're in there swapping over to the Summary Allocation API?

**Comment by nealormsbee** [comment]
Ab-so-lutely
