### ISSUE TITLE
Daily total cost discrepancy between AWS ec2 cost and kubecost

### ISSUE THREAD

**Issue by kishore0709** [kubecost/cost-analyzer-helm-chart#1143]
**Describe the bug**
We can see there is ~$10 difference of daily total cost in kubecost when compared with AWS EC2 instances billing(daily).

Kubecost is showing ~10$ less cost on daily basis than AWS ec2 daily billing.

Could you please help find the issue how and where are we missing.

Thanks!
Kishor.

gz#1044

**Comment by AjayTripathy** [comment]
Hi Kishore, have you set up your [AWS cloud integration](https://github.com/kubecost/docs/blob/master/aws-cloud-integrations.md) and have you taken a look at our [pricing methodology](https://github.com/kubecost/docs/blob/master/aws-node-price-reconcilitation-methodology.md) ?

**Comment by kbrwn** [comment]
@kishore0709 Please consider joining the #support channel at [kubecost.slack.com](https://kubecost.slack.com/) to get more help!
