### ISSUE TITLE
Deployment controllers and service section data not showing up in kubecost dashboard

### ISSUE THREAD

**Issue by mpsanj** [kubecost/cost-analyzer-helm-chart#1149]
Hi Team, we have been looking into kubecost for getting cost in AKS at namespace level, and it sounds like a good fit for our needs.
Deployment controller aren't be identified, gets into a generic section called no controllers as shown in the image, why is this happening ?

<img width="1197" alt="kubecost-screenshot" src="https://user-images.githubusercontent.com/43144863/143175219-e7cb54f9-1e2e-4c4e-b948-091aec6b2d0f.png">

We are passing a custom values file with the helm chart kubecost/cost-analyzer, which disables prometheus, grafana and adds an ingress resource

```
global:
  grafana:
    domainName: grafana-xxx.com
    enabled: false
    proxy: false
    scheme: http
  notifications:
    alertmanager:
      enabled: false
  prometheus:
    enabled: false
    fqdn: http://prometheus-server.monitoring.svc.cluster.local
  thanos:
    enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  paths: ["/"] 
  hosts:
    - kubecost.xx.com
  tls: []

prometheus:
  alertmanager:
    enabled: false
    persistentVolume:
      enabled: false
  nodeExporter:
    enabled: true

networkCosts:
  enabled: true

kubecostProductConfigs:
  azureStorageSecretName: kubecost-storage

```

Chart version: cost-analyzer-1.86.1
Not sure why the deployment controllers and service section doesnt show up ?

[kubecost-bug-report-1637727299197.txt](https://github.com/kubecost/cost-analyzer-helm-chart/files/7592728/kubecost-bug-report-1637727299197.txt)

**To Reproduce**

 Install the specified chart version with the values file provided

**Expected behavior**

Deployment controller and service allocation showing data

**Collect logs (please complete the following information):**

 - Run `helm ls` and paste the output here:
 
% helm ls -n kubecost
NAME    	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART               	APP VERSION
kubecost	kubecost 	1       	2021-11-23 23:43:31.361066 +0530 IST	deployed	cost-analyzer-1.86.1	1.86.1     

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-server` and paste the output here:

(⎈ |staging-np-pune-aks:default)sanjay.m@GL0574-X0 /Users/sanjay.m 
% kubectl logs kubecost-cost-analyzer-5b8755fdf6-6k8rw   -n kubecost -c cost-analyzer-server
2021/11/23 18:14:00 Thanos is disabled for the API endpoints.
2021/11/23 18:14:00 Server is ready. 
2021/11/24 04:14:57 Checking prometheus endpoint!
2021/11/24 04:14:57 Using Prometheus at http://prometheus-server.monitoring.svc.cluster.local

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-model` and paste the output here:

kubernetes.io/hostname:aks-nodepool1-27401777-vmss000001 kubernetes.io/os:linux kubernetes.io/role:agent node-role.kubernetes.io/agent: node.kubernetes.io/instance-type:Standard_E8s_v3 poollabel:ancillary2 poolname:nodepool1 providerID:azure:///subscriptions/de50a670-dd24-4abd-afa8-e0bb87e589a3/resourceGroups/mc_staging_staging-np-pune-aks_centralindia/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-27401777-vmss/virtualMachines/1 topology.kubernetes.io/region:centralindia topology.kubernetes.io/zone:0] accelerator nvidia}
I1124 04:32:07.101889       1 azureprovider.go:908] [Warning] no pricing data found for centralindia,Standard_E8s_v3,ondemand: &{map[agentpool:nodepool1 beta.kubernetes.io/arch:amd64 beta.kubernetes.io/instance-type:Standard_E8s_v3 beta.kubernetes.io/os:linux failure-domain.beta.kubernetes.io/region:centralindia failure-domain.beta.kubernetes.io/zone:0 kubernetes.azure.com/cluster:MC_staging_staging-np-pune-aks_centralindia kubernetes.azure.com/mode:system kubernetes.azure.com/node-image-version:AKSUbuntu-1804gen2containerd-2021.07.03 kubernetes.azure.com/os-sku:Ubuntu kubernetes.azure.com/role:agent kubernetes.io/arch:amd64 kubernetes.io/hostname:aks-nodepool1-27401777-vmss000002 kubernetes.io/os:linux kubernetes.io/role:agent node-role.kubernetes.io/agent: node.kubernetes.io/instance-type:Standard_E8s_v3 poollabel:ancillary2 poolname:nodepool1 providerID:azure:///subscriptions/de50a670-dd24-4abd-afa8-e0bb87e589a3/resourceGroups/mc_staging_staging-np-pune-aks_centralindia/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-27401777-vmss/virtualMachines/2 topology.kubernetes.io/region:centralindia topology.kubernetes.io/zone:0] accelerator nvidia}
I1124 04:32:07.101919       1 azureprovider.go:908] [Warning] no pricing data found for centralindia,Standard_E8s_v3,ondemand: &{map[agentpool:nodepool3 beta.kubernetes.io/arch:amd64 beta.kubernetes.io/instance-type:Standard_E8s_v3 beta.kubernetes.io/os:linux failure-domain.beta.kubernetes.io/region:centralindia failure-domain.beta.kubernetes.io/zone:0 kubernetes.azure.com/agentpool:nodepool3 kubernetes.azure.com/cluster:MC_staging_staging-np-pune-aks_centralindia kubernetes.azure.com/mode:user kubernetes.azure.com/node-image-version:AKSUbuntu-1804gen2containerd-2021.09.06 kubernetes.azure.com/role:agent kubernetes.azure.com/storageprofile:managed kubernetes.azure.com/storagetier:Premium_LRS kubernetes.io/arch:amd64 kubernetes.io/hostname:aks-nodepool3-27401777-vmss000000 kubernetes.io/os:linux kubernetes.io/role:agent node-role.kubernetes.io/agent: node.kubernetes.io/instance-type:Standard_E8s_v3 poollabel:ancillary2 poolname:nodepool3e8 providerID:azure:///subscriptions/de50a670-dd24-4abd-afa8-e0bb87e589a3/resourceGroups/mc_staging_staging-np-pune-aks_centralindia/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool3-27401777-vmss/virtualMachines/0 storageprofile:managed storagetier:Premium_LRS topology.kubernetes.io/region:centralindia topology.kubernetes.io/zone:0] accelerator nvidia}
I1124 04:33:07.107876       1 azureprovider.go:908] [Warning] no pricing data found for centralindia,Standard_E8s_v3,ondemand: &{map[agentpool:nodepool3 beta.kubernetes.io/arch:amd64 beta.kubernetes.io/instance-type:Standard_E8s_v3 beta.kubernetes.io/os:linux failure-domain.beta.kubernetes.io/region:centralindia failure-domain.beta.kubernetes.io/zone:0 kubernetes.azure.com/agentpool:nodepool3 kubernetes.azure.com/cluster:MC_staging_staging-np-pune-aks_centralindia kubernetes.azure.com/mode:user kubernetes.azure.com/node-image-version:AKSUbuntu-1804gen2containerd-2021.09.06 kubernetes.azure.com/role:agent kubernetes.azure.com/storageprofile:managed kubernetes.azure.com/storagetier:Premium_LRS kubernetes.io/arch:amd64 kubernetes.io/hostname:aks-nodepool3-27401777-vmss000000 kubernetes.io/os:linux kubernetes.io/role:agent node-role.kubernetes.io/agent: node.kubernetes.io/instance-type:Standard_E8s_v3 poollabel:ancillary2 poolname:nodepool3e8 providerID:azure:///subscriptions/de50a670-dd24-4abd-afa8-e0bb87e589a3/resourceGroups/mc_staging_staging-np-pune-aks_centralindia/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool3-27401777-vmss/virtualMachines/0 storageprofile:managed storagetier:Premium_LRS topology.kubernetes.io/region:centralindia topology.kubernetes.io/zone:0] accelerator nvidia}
I1124 04:33:07.107930       1 azureprovider.go:908] [Warning] no pricing data found for centralindia,Standard_E8s_v3,ondemand: &{map[agentpool:nodepool1 beta.kubernetes.io/arch:amd64 beta.kubernetes.io/instance-type:Standard_E8s_v3 beta.kubernetes.io/os:linux failure-domain.beta.kubernetes.io/region:centralindia failure-domain.beta.kubernetes.io/zone:0 kubernetes.azure.com/cluster:MC_staging_staging-np-pune-aks_centralindia kubernetes.azure.com/mode:system kubernetes.azure.com/node-image-version:AKSUbuntu-1804gen2containerd-2021.07.03 kubernetes.azure.com/os-sku:Ubuntu kubernetes.azure.com/role:agent kubernetes.io/arch:amd64 kubernetes.io/hostname:aks-nodepool1-27401777-vmss000001 kubernetes.io/os:linux kubernetes.io/role:agent node-role.kubernetes.io/agent: node.kubernetes.io/instance-type:Standard_E8s_v3 poollabel:ancillary2 poolname:nodepool1 providerID:azure:///subscriptions/de50a670-dd24-4abd-afa8-e0bb87e589a3/resourceGroups/mc_staging_staging-np-pune-aks_centralindia/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-27401777-vmss/virtualMachines/1 topology.kubernetes.io/region:centralindia topology.kubernetes.io/zone:0] accelerator nvidia}
I1124 04:33:07.107956       1 azureprovider.go:908] [Warning] no pricing data found for centralindia,Standard_E8s_v3,ondemand: &{map[agentpool:nodepool1 beta.kubernetes.io/arch:amd64 beta.kubernetes.io/instance-type:Standard_E8s_v3 beta.kubernetes.io/os:linux failure-domain.beta.kubernetes.io/region:centralindia failure-domain.beta.kubernetes.io/zone:0 kubernetes.azure.com/cluster:MC_staging_staging-np-pune-aks_centralindia kubernetes.azure.com/mode:system kubernetes.azure.com/node-image-version:AKSUbuntu-1804gen2containerd-2021.07.03 kubernetes.azure.com/os-sku:Ubuntu kubernetes.azure.com/role:agent kubernetes.io/arch:amd64 kubernetes.io/hostname:aks-nodepool1-27401777-vmss000002 kubernetes.io/os:linux kubernetes.io/role:agent node-role.kubernetes.io/agent: node.kubernetes.io/instance-type:Standard_E8s_v3 poollabel:ancillary2 poolname:nodepool1 providerID:azure:///subscriptions/de50a670-dd24-4abd-afa8-e0bb87e589a3/resourceGroups/mc_staging_staging-np-pune-aks_centralindia/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-27401777-vmss/virtualMachines/2 topology.kubernetes.io/region:centralindia topology.kubernetes.io/zone:0] accelerator nvidia}
I1124 04:33:07.108747       1 azureprovider.go:908] [Warning] no pricing data found for centralindia,Standard_E8s_v3,ondemand: &{map[agentpool:nodepool1 beta.kubernetes.io/arch:amd64 beta.kubernetes.io/instance-type:Standard_E8s_v3 beta.kubernetes.io/os:linux failure-domain.beta.kubernetes.io/region:centralindia failure-domain.beta.kubernetes.io/zone:0 kubernetes.azure.com/cluster:MC_staging_staging-np-pune-aks_centralindia kubernetes.azure.com/mode:system kubernetes.azure.com/node-image-version:AKSUbuntu-1804gen2containerd-2021.07.03 kubernetes.azure.com/os-sku:Ubuntu kubernetes.azure.com/role:agent kubernetes.io/arch:amd64 kubernetes.io/hostname:aks-nodepool1-27401777-vmss000001 kubernetes.io/os:linux kubernetes.io/role:agent node-role.kubernetes.io/agent: node.kubernetes.io/instance-type:Standard_E8s_v3 poollabel:ancillary2 poolname:nodepool1 providerID:azure:///subscriptions/de50a670-dd24-4abd-afa8-e0bb87e589a3/resourceGroups/mc_staging_staging-np-pune-aks_centralindia/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-27401777-vmss/virtualMachines/1 topology.kubernetes.io/region:centralindia topology.kubernetes.io/zone:0] accelerator nvidia}
I1124 04:33:07.108795       1 azureprovider.go:908] [Warning] no pricing data found for centralindia,Standard_E8s_v3,ondemand: &{map[agentpool:nodepool1 beta.kubernetes.io/arch:amd64 beta.kubernetes.io/instance-type:Standard_E8s_v3 beta.kubernetes.io/os:linux failure-domain.beta.kubernetes.io/region:centralindia failure-domain.beta.kubernetes.io/zone:0 kubernetes.azure.com/cluster:MC_staging_staging-np-pune-aks_centralindia kubernetes.azure.com/mode:system kubernetes.azure.com/node-image-version:AKSUbuntu-1804gen2containerd-2021.07.03 kubernetes.azure.com/os-sku:Ubuntu kubernetes.azure.com/role:agent kubernetes.io/arch:amd64 kubernetes.io/hostname:aks-nodepool1-27401777-vmss000002 kubernetes.io/os:linux kubernetes.io/role:agent node-role.kubernetes.io/agent: node.kubernetes.io/instance-type:Standard_E8s_v3 poollabel:ancillary2 poolname:nodepool1 providerID:azure:///subscriptions/de50a670-dd24-4abd-afa8-e0bb87e589a3/resourceGroups/mc_staging_staging-np-pune-aks_centralindia/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-27401777-vmss/virtualMachines/2 topology.kubernetes.io/region:centralindia topology.kubernetes.io/zone:0] accelerator nvidia}
I1124 04:33:07.108829       1 azureprovider.go:908] [Warning] no pricing data found for centralindia,Standard_E8s_v3,ondemand: &{map[agentpool:nodepool3 beta.kubernetes.io/arch:amd64 beta.kubernetes.io/instance-type:Standard_E8s_v3 beta.kubernetes.io/os:linux failure-domain.beta.kubernetes.io/region:centralindia failure-domain.beta.kubernetes.io/zone:0 kubernetes.azure.com/agentpool:nodepool3 kubernetes.azure.com/cluster:MC_staging_staging-np-pune-aks_centralindia kubernetes.azure.com/mode:user kubernetes.azure.com/node-image-version:AKSUbuntu-1804gen2containerd-2021.09.06 kubernetes.azure.com/role:agent kubernetes.azure.com/storageprofile:managed kubernetes.azure.com/storagetier:Premium_LRS kubernetes.io/arch:amd64 kubernetes.io/hostname:aks-nodepool3-27401777-vmss000000 kubernetes.io/os:linux kubernetes.io/role:agent node-role.kubernetes.io/agent: node.kubernetes.io/instance-type:Standard_E8s_v3 poollabel:ancillary2 poolname:nodepool3e8 providerID:azure:///subscriptions/de50a670-dd24-4abd-afa8-e0bb87e589a3/resourceGroups/mc_staging_staging-np-pune-aks_centralindia/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool3-27401777-vmss/virtualMachines/0 storageprofile:managed storagetier:Premium_LRS topology.kubernetes.io/region:centralindia topology.kubernetes.io/zone:0] accelerator nvidia}

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-frontend` and paste the output here:

172.29.36.57 - - [24/Nov/2021:04:14:57 +0000] "GET /api/prometheusQuery?query=node_total_hourly_cost*730&req=205105 HTTP/1.1" 200 63 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.190"
172.29.36.154 - - [24/Nov/2021:04:14:57 +0000] "GET /api/ HTTP/1.1" 200 1186 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.98"
172.29.36.57 - - [24/Nov/2021:04:14:57 +0000] "GET /api/helmValues HTTP/1.1" 200 6322 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.190"
172.29.36.154 - - [24/Nov/2021:04:14:57 +0000] "GET /api/prometheusQuery?query=avg(up)%20by%20(component%2C%20job%2C%20kubernetes_namespace%2Ckubernetes_node)&req=323136 HTTP/1.1" 200 453 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.98"
172.29.36.57 - - [24/Nov/2021:04:14:57 +0000] "GET /model/getApiConfig?req=157222 HTTP/1.1" 200 530 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.190"
172.29.36.57 - - [24/Nov/2021:04:14:57 +0000] "GET /api/podLogs?namespace=kubecost&selector=app.kubernetes.io/name=thanos&since=12h HTTP/1.1" 200 0 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.190"
172.29.36.57 - - [24/Nov/2021:04:14:57 +0000] "GET /api/prometheusQuery?query=sum(up)&req=51695 HTTP/1.1" 200 106 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.190"
172.29.36.154 - - [24/Nov/2021:04:14:57 +0000] "GET /api/podLogs?namespace=kubecost&selector=app=prometheus&since=24h HTTP/1.1" 200 0 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.98"
172.29.36.57 - - [24/Nov/2021:04:14:57 +0000] "GET /api/prometheusQuery?query=sum(sum_over_time(kube_pod_container_resource_requests%7Bresource%3D%22memory%22%2C%20unit%3D%22byte%22%7D%5B10m%5D))&req=970873 HTTP/1.1" 200 116 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.190"
172.29.36.154 - - [24/Nov/2021:04:14:57 +0000] "GET /api/prometheusQuery?query=sum(node_cpu_seconds_total)&req=189439 HTTP/1.1" 200 116 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.98"
172.29.36.57 - - [24/Nov/2021:04:14:57 +0000] "GET /api/prometheusQuery?query=sum(sum_over_time(container_cpu_usage_seconds_total%5B10m%5D))&req=764272 HTTP/1.1" 200 121 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.190"
172.29.36.57 - - [24/Nov/2021:04:14:57 +0000] "GET /api/prometheusQuery?query=avg_over_time(kubecost_savings_memory_allocation_bytes%5B10m%5D)&req=319055 HTTP/1.1" 200 63 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.190"
172.29.36.154 - - [24/Nov/2021:04:14:57 +0000] "GET /api/prometheusQuery?query=sum(sum_over_time(node_cpu_hourly_cost%5B10m%5D))&req=445143 HTTP/1.1" 200 63 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.98"
172.29.36.57 - - [24/Nov/2021:04:14:57 +0000] "GET /api/prometheusQuery?query=sum(avg_over_time(kube_persistentvolume_capacity_bytes%5B10m%5D))&req=924528 HTTP/1.1" 200 116 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.190"
172.29.36.57 - - [24/Nov/2021:04:14:57 +0000] "GET /api/prometheusQuery?query=sum(sum_over_time(container_cpu_usage_seconds_total%5B10m%5D))&req=464389 HTTP/1.1" 200 121 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.190"
172.29.36.154 - - [24/Nov/2021:04:14:57 +0000] "GET /api/thanosQuery?query=sum(count%20by%20(name%2C%20cluster_id)(%7B__name__%3D~%22.%2B%22%7D%20offset%203h))%20by%20(cluster_id)&req=602466 HTTP/1.1" 200 45 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.98"
172.29.36.57 - - [24/Nov/2021:04:14:57 +0000] "GET /api/thanosQuery?query=topk(25%2C%20count%20by%20(name%2C%20job%2C%20cluster_id)(%7B__name__%3D~%22.%2B%22%7D%20offset%203h))&req=692290 HTTP/1.1" 200 45 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.190"
172.29.36.57 - - [24/Nov/2021:04:14:57 +0000] "GET /api/thanosQuery?query=avg(up)%20by%20(component%2C%20job%2C%20kubernetes_namespace)&req=390034 HTTP/1.1" 200 45 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.190"
172.29.36.154 - - [24/Nov/2021:04:14:57 +0000] "GET /api/podLogs?namespace=kubecost&selector=app=cost-analyzer&since=24h HTTP/1.1" 200 477229 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.98"
172.29.36.57 - - [24/Nov/2021:04:14:58 +0000] "GET /api/prometheusQuery?query=sum(count%20by%20(name)(%7B__name__%3D~%22.%2B%22%7D))&req=573281 HTTP/1.1" 200 109 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.190"
172.29.36.154 - - [24/Nov/2021:04:14:58 +0000] "GET /api/prometheusQuery?query=topk(25%2C%20count%20by%20(name%2C%20job)(%7B__name__%3D~%22.%2B%22%7D))&req=481509 HTTP/1.1" 200 633 "http://kubecost.staging-pn-np.xx-internal.x.com/settings.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "172.29.36.4"

gz#1078

**Comment by kbrwn** [comment]
@mpsanj Didn't you already post this in our slack in #general? Can you reply there with the requested information instead? This is not a bug but rather an issue with your deployment that we can solve as a support request.

**Comment by mpsanj** [comment]
@kbrwn sorry my bad I thought i had to open a issue, will do. Thanks
