### ISSUE TITLE
YAML Key-duplication

### ISSUE THREAD

**Issue by lkhomenk** [kubecost/cost-analyzer-helm-chart#1150]
**Describe the bug**
YAML Key duplication in https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-network-costs-service-template.yaml#L12 conflicts with `app` label from commonLabels.
Helm itself can handle key-duplication but latest versions on [flux with kustomize v4](https://github.com/fluxcd/flux2/issues/1522). This is the only duplicated key in whole chart
`app: cost-analyzer` label is not needed in `cost-analyzer-network-costs-service` as PodMonitor uses another value
```
map[string]interface {}(nil): yaml: unmarshal errors:
mapping key "app" already defined
```

**To Reproduce**
1. Run yamllint against helm manifests of templates/cost-analyzer-network-costs-service-template.yaml
2. grep key-duplication

Or deploy chart via flux 1.23

gz#1084

**Comment by kbrwn** [comment]
@lkhomenk Thanks for the report. Helm is the supported tool to deploy kubecost. We hope to maintain compatibility with other tools such as flux/kustomize etc but this may not always be the case as new versions of these other tools come out and have breaking changes. As helm can handle key-duplications without error this is unlikely to be a priority to fix right away. We are happy to review any PRs if you are up for the challenge.
