### ISSUE TITLE
Configurable port for tcp-server and tcp-model

### ISSUE THREAD

**Issue by kbrwn** [kubecost/cost-analyzer-helm-chart#1151]
**What problem are you trying to solve?**
Users should be able to configure the service ports.

**Describe the solution you'd like**
Allow for these values to be configurable in the cost-analyzer values.yaml file.

**Describe alternatives you've considered**

Editing the service after deployment (this breaks healthchecks unfortunately)

**How would users interact with this feature?**

`--set` or parameters in the values.yaml
<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1093'>Zendesk ticket #1093</a>)<br>gz#1093</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-51) by [Unito](https://www.unito.io)

**Comment by kbrwn** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-service-template.yaml#L29-L33

**Comment by AjayTripathy** [comment]
We found another workaround for the user here, so seems lower priority but would love someone to pick it up as a good way to get experience with the helm chart!

**Comment by AjayTripathy** [comment]
Hi @vgazzola apologies for the late response, most of the team was at a conference. The workaround here was just to manually edit the chart, and hardcode, so a configurable PR would be much accepted here.
