### ISSUE TITLE
Need to be able to load kubecostToken from a secret

### ISSUE THREAD

**Issue by chaosunsfx** [kubecost/cost-analyzer-helm-chart#1154]
**What problem are you trying to solve?**
kubecostToken seems only be provided in values YAML file as plain text, based on [the way it is used](https://github.com/kubecost/cost-analyzer-helm-chart/blob/release-1.88.1/cost-analyzer/templates/cost-analyzer-config-map-template.yaml#L27). This would raise concerns as we have certain security standards to comply to.

**Describe the solution you'd like**
Support the loading of kubecostToken from a secret, which is either mounted as a file or exported as an environment variable in container.

**Describe alternatives you've considered**
N/A

**How would users interact with this feature?**
We will create a Kubernetes Secret which holds the token, and mount it either as a file or an environment variable in pod.

gz#1108

**Comment by dwbrown2** [comment]
Thanks for the issue, @chaosunsfx! This is actually an optional field for tracking trial status. You can actually immediately remove if you have any privacy concerns. Hope this helps.

**Comment by chaosunsfx** [comment]
Thanks @dwbrown2
