### ISSUE TITLE
Kubecost metrics duplication on latest version

### ISSUE THREAD

**Issue by etsyamitra** [kubecost/cost-analyzer-helm-chart#1155]
**Describe the bug**
We have found kubecost instance creating separate metrics in some cases instead of leveraging the vanilla kube state metrics.
This spooked our monitoring infra and could also potentially spike the metrics storage space.

Would be curious if there is any new feature in latest version which needs this duplication and,
if it would be possible to keep this optional.

**To Reproduce**
- Upgrade kubecost to latest version (v1.88.0)
- monitoring our prometheus for any specific model.
<img width="1413" alt="Screen Shot 2021-12-03 at 9 48 46 AM" src="https://user-images.githubusercontent.com/75339656/144649171-36b0d2dc-6b8b-4f18-a66d-01a37f4110b6.png">

Note: we have configured kubecost to use the existing prometheus instance, but started observing this issue since upgrade from v1.78.0 to v1.88.0

**Expected behavior**
Based on understanding of the reason of duplication, would be more ideal to reuse the existing metrics.

gz#1112

**Comment by kbrwn** [comment]
@etsyamitra this is behavior is well documented please review: https://guide.kubecost.com/hc/en-us/articles/4408095797911-Kube-State-Metrics-KSM-Emission

You likely want to disable ksm metric emission by the kubecost pod.

**Comment by kbrwn** [comment]
hi @etsyamitra I am going to close this issue. Please re-open if you have any further questions in regards to this topic or email support@kubecost.com.
