### ISSUE TITLE
Provide general purpose event markers in UI

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1158]
**What problem are you trying to solve?**
At times, certain events trigger increases or decreases in cost or other metrics.  Currently, there is no way to timestamp/annotate/identify these in the UI

**Describe the solution you'd like**
A way to add a marker (timestamp, description, etc.) and have them display in views and reports to capture significant events to add context to cost changes.

**Describe alternatives you've considered**
Currently, we just keep this in our head, but as we roll this out to more and more users, it would be beneficial for everyone to have the information readily visible in the UI.

**How would users interact with this feature?**
As a start, creating them via yaml would be fine, but ultimately it would be valuable to have them created from the UI.  I would expect them to be persisted in Prometheus and, where applicable, Thanos as simply another piece of timestamped data.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-54) by [Unito](https://www.unito.io)

**Comment by dsmith-amg** [comment]
Annotations is a definite value feature for us that would extend our use of the platform immeasurably.

**Comment by dwbrown2** [comment]
Really interesting idea! Are there specific events/annotations that would be most impactful to see?

**Comment by dwbrown2** [comment]
Totally agree there are many different directions that can go. Was trying to get a sense for highest priority events if there are specific ones of interest. Another potential approach is to monitor k8s events and add as annotations.

**Comment by kirbsauce** [comment]
Understood.  I think another use is to simply identify events that take place outside of k8s.  For example, an indicator that says "removed x number of abandoned workloads", to explain a reduction in overall cost in the charts.  It answers the question "Why did costs go down here?"
