### ISSUE TITLE
Provide way to list unallocated assets

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1165]
**What problem are you trying to solve?**
I would like to be able review assets that are "unallocated".

**Describe the solution you'd like**
I would like to be able to drill down into the unallocated assets line item.

**Describe alternatives you've considered**
Have considered a script which leverages the APIs.

**How would users interact with this feature?**
By being able to click down into the unallocated assets line item.

**Comment by kaelanspatel** [comment]
This has been tracked (but not actually tackled) for a little while [here](https://github.com/kubecost/cost-model/issues/876).

**Comment by kirbsauce** [comment]
Thanks @kaelanspatel!  I'll go ahead and close this and track https://github.com/kubecost/cost-model/issues/876.
