### ISSUE TITLE
Add labels to savings recommendation logic

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1172]
**What problem are you trying to solve?**
Manage a large number of savings recommendations

**Describe the solution you'd like**
I would like the savings recommendation logic to consider labels such that I can identify workloads as "ignore", "under review" (action taken on a previous recommendation), etc.  Some would simply remove a workload from savings consideration, where others could be used for sorting and filtering.

**Describe alternatives you've considered**
Via the API

**How would users interact with this feature?**
Users would be responsible for setting the labels and the UI would provide the ability to sort/filter recommendations based on the labels.

A workflow might be:

1. Review savings recommendations.
1. Assign a developer a set of workloads to review.
1. Label these workloads as "under review".

At the time of the next review, those labeled workloads would either be filtered out or sorted further down the list.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-55) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
This would be pretty straight forward to accomplish with k8s labels and then more robust filtering logic. Any input on the benefits of tracking state in Kubecost vs in Kubernetes directly?

**Comment by kirbsauce** [comment]
I think the intent is to do just that...change the k8s label and provide necessary filtering/sorting. @AjayTripathy , is that your understanding too?

**Comment by AjayTripathy** [comment]
The intention is to label the pod from within k8s, of course. But as always we should consider a default label to use and perhaps make this configurable-- if the label is configurable, it would need to be tracked from within kubecost.

**Comment by patrick-tavares** [comment]
This topic has come up again in conversations with potential customers though they are more interested not in excluding resources from recommendation considerations but rather specifying only those to be included in recommendations by specific labels. I would like to request that we broaden the scope of this RFE to enable inclusion and/or exclusion label conditions and have the ability to manage those filtering conditions from the UI

**Comment by kwombach12** [comment]
@patrick-tavares we will be adding the ability to archive or dismiss savings card in 104, in future releases, we will be adding more granularity to the dismissing ability
