### ISSUE TITLE
Uncaught error when certain filters passes to request sizing

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#1177]
**Describe the bug**
Adding an unexpected filter value causes the request-sizing page to break. 

**To Reproduce**
1. Go to the request sizing page
2. Add `app=prometheus` as a Label filter
3. Page hands and error is visible

![image](https://user-images.githubusercontent.com/298359/146190918-c37b6a92-8fac-40cd-a581-28e6a23f8cde.png)

**Expected behavior**
Page doesn't crash. 

Secondary suggestion: we may want to provide filter hints, e.g. `app:prometheus`, because it was not obvious what accepted values were possible.

**Comment by nealormsbee** [comment]
Issue is addressed here: https://github.com/kubecost/cost-analyzer-frontend/pull/460
