### ISSUE TITLE
Default chart value for Thanos setup doesn't match the port name referenced in Thanos sidecar's service template

### ISSUE THREAD

**Issue by tohjustin** [kubecost/cost-analyzer-helm-chart#1187]
**Describe the bug**

- Default chart value for Thanos setup uses `sidecar-http` as the port name for the sidecar container's HTTP endpoint (see https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.89.0-rc.2/cost-analyzer/values-thanos.yaml#L51) 
- Thanos sidecar's service template uses `http` as the target port (see https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.89.0-rc.2/cost-analyzer/charts/thanos/templates/sidecar-service.yaml#L54)
- Since both configs aren't using a matching port names, the service isn't exposing the Thanos sidecar container's `/metrics` endpoint properly & Prometheus isn't able to scrape the Thanos sidecar metrics.

**Expected behavior**

Replacing the port name in https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.89.0-rc.2/cost-analyzer/values-thanos.yaml#L51 from `sidecar-http` to `http` fixes the issue.

**Comment by kbrwn** [comment]
Hi @tohjustin thanks for this report as well. The fix is included in PR  #1189.
