### ISSUE TITLE
Incorrect path expression for service labels used in Thanos sidecar's service template

### ISSUE THREAD

**Issue by tohjustin** [kubecost/cost-analyzer-helm-chart#1188]
**Describe the bug**

Incorrect path expression for service labels used in Thanos sidecar's service template (see https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.89.0-rc.2/cost-analyzer/charts/thanos/templates/sidecar-service.yaml#L46)

**Expected behavior**

Path expression should be `{{ with .Values.sidecar.http.service.labels }}` instead of `{{ with .Values.store.http.service.labels }}`.

**Comment by kbrwn** [comment]
Thanks for the report @tohjustin. I have submitted a PR to fix this issue.
