### ISSUE TITLE
[FR] Network Costs DaemonSet UpdateStrategy configuration

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-analyzer-helm-chart#1195]
**What problem are you trying to solve?**

In clusters with a very high number of nodes the rollout of the NetworkCosts daemonset is very slow and slows down the package upgrade substantially.

**Describe the solution you'd like**

The simplest solution would be to let the `updateStrategy` be defined at the chart level.

To date, they are statically defined. https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-network-costs-template.yaml#L10-L11

**Describe alternatives you've considered**

None

**How would users interact with this feature?**

Users can decide which `updateStrategy` is best suited to their setup. 

gz#1204

**Comment by kbrwn** [comment]
@pierluigilenoci thanks for this suggestion. We will investigate further.

**Comment by dwbrown2** [comment]
Note PR out for this!
