### ISSUE TITLE
Ability to disable emitting `*_labels` metrics

### ISSUE THREAD

**Issue by mhulscher** [kubecost/cost-analyzer-helm-chart#1200]
**What problem are you trying to solve?**

We run kubecost with our own installation of prometheus and thanos. We strictly label only namespaces with cost allocation metadata. We don't label controllers, pods, or anything else.

**Describe the solution you'd like**
I would like to be able to configure kubecost to stop emitting prometheus metrics of `*_labels` for resources that are not namespaces. This will decrease the sprawl of timeseries.

**Describe alternatives you've considered**
N/A

**How would users interact with this feature?**
Some configuration in the helm-chart's values.yaml would be my preference.

**Comment by AjayTripathy** [comment]
Fine grained control of kubecost metrics emitted makes sense to me.

**Comment by AjayTripathy** [comment]
Just as a note @kaelanspatel has been working on this...designs for configs expected next week!

**Comment by kaelanspatel** [comment]
Currently my thought process is for there to be a field under kubecostProductConfigs like:
```
metricsConfigs:
    disabledMetrics:
      - kube_node_labels
      - kube_pod_labels
      etc.
```
This will give users fine-grained control over metrics emitted without bloating values.yaml with flags.

**Comment by dwbrown2** [comment]
I imagine this could break the UI in hard to understand ways, depending on
what metrics are removed. Let us know if you need help thinking through the
different implications.

**Comment by AjayTripathy** [comment]
I suggest we disable nothing by default and let users disable them if they end up being duplicated?

**Comment by kaelanspatel** [comment]
Seems this closed automatically. 

Any metric can now be disabled by configuration in the helm chart:
```
kubecostProductConfigs:
  ...
  metricsConfigs:
    disabledMetrics:
      - <metric-to-be-disabled>
      - <metric-to-be-disabled>
      etc.
```

This has been implemented and will likely be available in the next few releases.
