### ISSUE TITLE
 Split shared ALB external cost with Kubecost across multiple namespaces

### ISSUE THREAD

**Issue by pengchen98** [kubecost/cost-analyzer-helm-chart#1203]
**What problem are you trying to solve?**
With ALB v2 (load balancer controller) promoted  in AWS EKS, services teams can share one load balancer among multiple ingresses to save costs by leveraging target group annotation. This feature brings a lot of business values but at same time it posts challenge that calculating kubecost external LB cost based on  namespace tag alone is no longer working if multiple services from different namespaces share same LB. 

**Describe the solution you'd like**
I would expect Kubecost support an array of values on the tags to split LB costs among service deployments in different namespaces.

gz#1230

**Comment by AjayTripathy** [comment]
Hi @pengchen98 , thanks for this feedback. You should already not need to tag loadbalancers to allocate them to kubernetes services-- we should be able to pick up their ID automatically from the kubernetes API and reconcile their costs with the AWS bill. If you look at /assets.html > Kubernetes > Loadbalancers with an AWS integration you should see the fully loaded cost picked up from the AWS cost and usage report then split among pods which use the loadbalancer in the loadbalancer allocation column.

**Comment by AjayTripathy** [comment]
All that being said, I do think there is value in splitting Cloud Assets into shared resources per kubernetes dimension, for resources other than loadbalancers-- it's just that LBs are unique in that we generally should be capable of autodetecting them.

**Comment by kbrwn** [comment]
@pengchen98 did the default allocation model built in for LB work for your ALB?

**Comment by kbrwn** [comment]
@pengchen98 I am going to close this issue. Sorry if having you create it was time consuming. I was mistaken about how kubecost would allocate for ALB.  Please feel free to re-open or email us at support@kubecost.com if your notice that your ALB is not properly allocated as expected.
