### ISSUE TITLE
UI Enhancement: Ability to send a savings recommendation to an external target

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1204]
**What problem are you trying to solve?**
I would like an easy way to send a savings recommendation to JIRA for ticket creation.

**Describe the solution you'd like**
Ideally, KC integrated directly with JIRA, but a more broadly usable solution would be to deliver the recommendation data to a webhook.  Obviously some sort of button or option on a menu to "Share".

**Describe alternatives you've considered**
Leveraging the API, but it's rather manual with no "Share" button.

**How would users interact with this feature?**
Define a webhook to be used for sharing of sizing recommendations in the config.yaml or settings.html

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-58) by [Unito](https://www.unito.io)

**Comment by srpomeroy** [comment]
Would be great if this was like a cost allocation alert in that it could be sent to different channels (email, slack, webhook) and have the ability to filter on resources and/or alert on thresholds.

**Comment by dwbrown2** [comment]
Awesome request! I see two potential features:

* Summary savings report
* Detailed savings insights

The concern I have is that the one or both of these are two noisy, e.g. I keep getting the same recommendation that doesn't apply to me for some reason. 

Thoughts on that framework / risk?

**Comment by AdamStack18** [comment]
Had the same idea as Sean. 

We could add this as an option in alerts.  Don't see any risk here as it could work the same as email or slack notifications. 

Also, love Kirby's share button idea.  If a stakeholder is looking at a filtered view this would make it easy to turn an insight into an action item.
