### ISSUE TITLE
Add percentage column in Cost Allocation page

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1215]
Filing on behalf of a customer:

**What problem are you trying to solve?**
Looking for a quick and easy way to see percentage of total cost that each row accounts for next to costs in Cost Allocation

**Describe the solution you'd like**
An additional column in the Cost Allocation page

**Describe alternatives you've considered**
Currently we export then create a percentage column in a spreadsheet

**How would users interact with this feature?**
view it directly in the Cost Allocation page

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-60) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
Would another potential solution be a tooltip with this information, or adding it to the info panel on the bar graph? Just trying to explore different options...

**Comment by kirbsauce** [comment]
Yes, I think either of those options would be good...maybe both?  (I think there are circumstances where the bars and line items represent different aggregations?).

**Comment by nealormsbee** [comment]
^ Typically those differences occur when the user visualizes cost *over time* in the bar graph. Each bar might contain cost data per-day, but the table always expresses cost data over the entire queried window.

Tossing in one other idea: we could add that info to each table row without making it a separate column. The Total Cost column could be displayed as something like `$395.86 (31.64%)`

That said, the table is pretty wide already in some circumstances. Tooltip may be the way to go.

**Comment by kirbsauce** [comment]
thanks @nealormsbee , that does make a lot of sense.  Tooltips for the win!
