### ISSUE TITLE
New details page missing efficiency info

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#1217]
Hi, I'm seeing a bug with efficiency on the inspect page with the new RC build from today. You can view here by clicking thanos-store. I see this on the allocation page:

![image](https://user-images.githubusercontent.com/298359/151459186-9dff3a70-07f6-4bc4-89f4-dd355f216793.png)

And this on the inspect page:
![image](https://user-images.githubusercontent.com/298359/151459222-bdd673c2-1469-4d4a-a3dd-07ad32506cbf.png)

**Comment by wolfeaustin** [comment]
Should be take care of with this PR https://github.com/kubecost/cost-analyzer-frontend/pull/472
