### ISSUE TITLE
[FR] Allow the Chart to create extra manifest 

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-analyzer-helm-chart#1218]
**What problem are you trying to solve?**
Sometimes, accessory to the installation there may be manifest to be installed (for example a SecretProviderClass).

**Describe the solution you'd like**
 It would be nice to be able to do this directly via the Chart using the approach that ArgoCD also uses.

Ref: https://github.com/argoproj/argo-helm/blob/cf57a71a154a1a8a19f5f9d3980d60eb3efd80c8/charts/argo-cd/values.yaml#L62-L87

**Describe alternatives you've considered**
I don't think there are alternatives.

gz#1301

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-61) by [Unito](https://www.unito.io)

**Comment by kbrwn** [comment]
@pierluigilenoci This is a great idea. Thank you for the request. We will work on a plan to implement something similar in our chart.

**Comment by pierluigilenoci** [comment]
![hopes-and-dreams-barney-hopes](https://github.com/kubecost/cost-analyzer-helm-chart/assets/36044817/60f356cb-4cdb-4ab2-8f0a-91a20660c0b5)

**Comment by jessegoodier** [comment]
did you see this?  https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L1270

**Comment by chipzoller** [comment]
Closing as completed. The Kubecost chart has a provision for deploying extra objects.
