### ISSUE TITLE
"Logout" button w/redirect

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1224]
**What problem are you trying to solve?**
The ability for our users to logout/sign out of the UI and be redirected to a configurable url.

**Describe the solution you'd like**
A logout button which would clear the session and redirect the user to a configurable URL

**Describe alternatives you've considered**
none

**How would users interact with this feature?**
User would click the logout button and be redirected to a configurable url.

related to https://github.com/kubecost/cost-analyzer-helm-chart/issues/1223

**Comment by kaelanspatel** [comment]
This has been implemented with the linked PR.
