### ISSUE TITLE
Standardize on all resources in cost-analyzer/templates/ having cost-analyzer.commonLabels

### ISSUE THREAD

**Issue by pzimno** [kubecost/cost-analyzer-helm-chart#1227]
**What problem are you trying to solve?**

We're in the middle of evaluating Kubecost enterprise and are trying to script converting the helm template into our internal  Argo/Kustomize format which requires each service to be in its own directory. To do this we utilize the `helm.sh/chart` and `chart` keys in the resource labels. 

These seem to be generated by the `{{ include "cost-analyzer.commonLabels" . | nindent 4 }}` helper function but are missing from a lot of the resources in cost-analyzer/templates/

**Describe the solution you'd like**
Is there a reason `{{ include "cost-analyzer.commonLabels" . | nindent 4 }}`  is not included in all resources in the cost-analyzer chart? If not can they be standardized to have them? 

**Describe alternatives you've considered**
Any other alternative that allows us to differentiate these services when running a `helm template` 

**How would users interact with this feature?**

Users will be able to identify workloads following labeling best practices. 

gz#1321

**Comment by kbrwn** [comment]
@pzimno thanks for this feature request. I agree that labels should be standardized and our chart/subcharts should support the latest `helm.sh/chart` label. At this time you can add additional labels to many of the k8s resources with an `additionalLabels: {}` in the values.yaml file.  [Example](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L134). There is also [.Values.kubecostDeployment.labels](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L10).

**Comment by pzimno** [comment]
@kbrwn Appreciate the quick response. Would your solution work for files like https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-psp.template.yaml#L6?

**Comment by kbrwn** [comment]
@pzimno No I don't think that resource can be labeled by the chart as does not appear that the PSP template has the needed function.

**Comment by pzimno** [comment]
Got it, I was wondering if I was missing a way it would apply since I haven't worked with Helm for a bit. I created https://github.com/kubecost/cost-analyzer-helm-chart/pull/1230

**Comment by kbrwn** [comment]
@pzimno thanks for the commit! We will work on getting it reviewed.

**Comment by kbrwn** [comment]
@pzimno thanks so much for your contribution! Closing this issue since #1230 is merged!
