### ISSUE TITLE
Settings page should show a version for both the Client and Server

### ISSUE THREAD

**Issue by nealormsbee** [kubecost/cost-analyzer-helm-chart#1231]
**What problem are you trying to solve?**
Using the UI of one Kubecost to visit the Settings page of a different Kubecost shows me the version info for the first Kubecost.

**Describe the solution you'd like**
Everything else on the settings page describes the cluster that's been selected for viewing. The version info should also show that cluster's version, at a minimum. Ideally, there would be separate concepts for client-version and server-version, both of which could be displayed in settings.

**Describe alternatives you've considered**
I have considered no alternatives

**How would users interact with this feature?**
They would go to the settings page and view version info.

With thanks and credit to balonik for noting that our settings page only shows client version info.

gz#1322<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1322'>Zendesk ticket #1322</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-63) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
+1 on my end, interesting think about this in the context of hosted too

cc @mbolt35

**Comment by nealormsbee** [comment]
We actually do this in the product now, an have for some time! Closing the issue.
