### ISSUE TITLE
Pass AWS_CLUSTER_ID environment variable, or pass arbitrary environment variables

### ISSUE THREAD

**Issue by davidfluck-kong** [kubecost/cost-analyzer-helm-chart#1235]
**What problem are you trying to solve?**
I would like to set the `AWS_CLUSTER_ID` environment variable in my values file, but from what I can tell, the Helm chart doesn't provide a config option for it specifically, and the Helm chart doesn't let you pass through arbitrary environment variables. Kubecost logs frequently complain about `AWS_CLUSTER_ID` not being set, and I would like to set it. I've checked a few times, and I'm fairly certain there isn't a way to do this, but I could be wrong.

**Describe the solution you'd like**
I would like either the ability to specify the `AWS_CLUSTER_ID` specifically via the values file, as with other environment variables, or the ability to pass through arbitrary extra environment variables via the values file.

**Describe alternatives you've considered**
I believe that this is the only reasonable solution.

**How would users interact with this feature?**
Users would configure the AWS cluster ID via a specific values file config option, or arbitrary extra environment variables via an `env` dictionary, which would be merged with the other environment variables in the Helm chart. For example:

```
{{- range $key, $value := .Values.env }}
- name: {{ $key }}
  value: {{ quote $value }}
{{- end }}
```

Let me know if you need any more information. Thank you!

gz#1342

**Comment by davidfluck-kong** [comment]
Additionally, I'm more than happy to submit a pull request if this is accepted as a feature request.

**Comment by kbrwn** [comment]
@davidfluck-kong I think this is a great feature request. Let me ask an engineer to review just to check if there is a reason this has not been implemented already.

**Comment by kbrwn** [comment]
@davidfluck-kong This env var is likely to be removed in the future. If you set a cluster name in the chart the error warning related to this env var in the log should go away: https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L747

**Comment by davidfluck-kong** [comment]
Ah, gotcha. I'm sorry, I don't know how I missed that. Sounds good, thank you.

**Comment by nealormsbee** [comment]
@kbrwn should we consider this resolved and close?

I could also see turning this into discussion around env-var setting from the Helm values, if that's of interest.

**Comment by kbrwn** [comment]
@nealormsbee Thanks for the reminder. Closing this out.
