### ISSUE TITLE
Remove `kubernetes-service-endpoints-slow`

### ISSUE THREAD

**Issue by kbrwn** [kubecost/cost-analyzer-helm-chart#1244]
`kubernetes-service-endpoints-slow` is unused by kubecost and needs to be removed.

https://github.com/kubecost/cost-analyzer-helm-chart/blob/28f351e47509acc4f20f0904cf8bca11f3c81c59/cost-analyzer/charts/prometheus/values.yaml#L1277<br><br><i>(created from <a href='https://kubecost.zendesk.com/agent/tickets/1372'>Zendesk ticket #1372</a>)<br> gz#1372</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-67) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
@AjayTripathy do we know where this is deprecated? I'm still seeing in the Prom community chart: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L1621

**Comment by AjayTripathy** [comment]
Oh, this was just a note that _our_ chart no longer relies on it (ie, we have deprecated its use in kubecost)

**Comment by gouglhupf** [comment]
We just installed Kubecost in our clusters and Prometheus is ingesting more data then needed.

As of now the Prometheus job `kubernetes-service-endpoints-slow` is still present in the [config](https://github.com/kubecost/cost-analyzer-helm-chart/blob/bdc8521c75a575c27e9a57a5316735640c738b23/cost-analyzer/charts/prometheus/values.yaml#L1334). If useful I can create PR removing it.

Are the jobs `prometheus-pushgateway` and `kubernetes-services` not in use too?

**Comment by AjayTripathy** [comment]
@gouglhupf a PR removing endpoints-slow and disabling prometheus-pushgateway makes sense.

I believe we use kubernetes-services though.
