### ISSUE TITLE
Support Service Account annotation for access for ETL S3 Backup feature

### ISSUE THREAD

**Issue by kbrwn** [kubecost/cost-analyzer-helm-chart#1250]
**What problem are you trying to solve?**
A thanos formatted secret must be used to utilize the [ETL S3 Backup](https://guide.kubecost.com/hc/en-us/articles/4407601815191-ETL-S3-Backup) feature. Some users don't want to specify a secret/access key.

**Describe the solution you'd like**

Support for pod/service account annotations. 

**Describe alternatives you've considered**

None.

**How would users interact with this feature?**

Applying policy to pods or SA resources in the kubernetes cluster. 

gz#1381

**Comment by AjayTripathy** [comment]
@mbolt35 I think this was already supported but want to double check with you.

**Comment by mbolt35** [comment]
We implement an identical bucket storage to Thanos via the minio client. The thanos docs state:

### Credentials
By default Thanos will try to retrieve credentials from the following sources:

* From config file if BOTH `access_key` and `secret_key` are present.
* From the standard AWS environment variable - `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`
* From `~/.aws/credentials`
* IAM credentials retrieved from an instance profile.
> NOTE: Getting access key from config file and secret key from other method (and vice versa) is not supported.

It seems that if S3 access has been configured for Thanos via the annotation method, then so can our bucket storage.

**Comment by kbrwn** [comment]
Re-opened because this functionality did not work as expected. Some notes from associated zd ticket: 

`KUBECOST_CONFIG_BUCKET` had to be set for S3 ETL storage to be enabled, but I didn't see it being set in the cost-analyzer deployment:

https://github.com/kubecost/cost-model/blob/master/pkg/config/configmanager.go#L61

https://github.com/kubecost/cost-model/blob/master/pkg/config/configmanager.go#L29-L31

https://github.com/kubecost/cost-model/blob/master/pkg/cmd/agent/agent.go#L142-L145

https://github.com/kubecost/cost-model/blob/fb51264ede8c399ffbe93dd8bd3bbc4eef854272/pkg/env/costmodelenv.go#L81

`KUBECOST_CONFIG_BUCKET` needs to be set but the Helm chart is setting `ETL_BUCKET_CONFIG`

**Comment by mbolt35** [comment]
> Re-opened because this functionality did not work as expected. Some notes from associated zd ticket: 
> 
> 
> 
> `KUBECOST_CONFIG_BUCKET` had to be set for S3 ETL storage to be enabled, but I didn't see it being set in the cost-analyzer deployment:
> 
> 
> 
> https://github.com/kubecost/cost-model/blob/master/pkg/config/configmanager.go#L61
> 
> 
> 
> https://github.com/kubecost/cost-model/blob/master/pkg/config/configmanager.go#L29-L31
> 
> 
> 
> https://github.com/kubecost/cost-model/blob/master/pkg/cmd/agent/agent.go#L142-L145
> 
> 
> 
> https://github.com/kubecost/cost-model/blob/fb51264ede8c399ffbe93dd8bd3bbc4eef854272/pkg/env/costmodelenv.go#L81
> 
> 
> 
> `KUBECOST_CONFIG_BUCKET` needs to be set but the Helm chart is setting `ETL_BUCKET_CONFIG`

None of the above is accurate. There was a small pass-through config that dropped the flag (looks like a fudged merge). Fix was added here: https://github.com/kubecost/kubecost-cost-model/pull/670

**Comment by dwbrown2** [comment]
Am I correct that this will be resolved in 1.91?

**Comment by AjayTripathy** [comment]
@mbolt35 I believe so but can you confirm and add the "next release" tag to this if so?

**Comment by kirbsauce** [comment]
Wouldn't "next release" be 1.92?

**Comment by mbolt35** [comment]
This is already fixed

**Comment by kbrwn** [comment]
`aws_sdk_auth: true` causing yaml parsing error preventing service account auth. Potentially need to update minio library.

**Comment by mbolt35** [comment]
After some further reading, it _may_ be possible that the existing version will work provided they remove the `access_key` and `secret_key` entries from the config file. 

This code is in our open source: 
https://github.com/kubecost/cost-model/blob/cb99ad914f080f06538205dafd7e5349c6ab1f4d/pkg/storage/s3storage.go#L193-L211

I believe the line: 
```
wrapCredentialsProvider(&credentials.IAM{
	Client: &http.Client{
		Transport: http.DefaultTransport,
	},
}),
```
will account for the service account IAM policies. We may want to ask them to try removing `access_key` and `secret_key` first. We'll plan to update anyways to get up to the thanos spec for the configuration.

**Comment by AdamStack18** [comment]
@kbrwn Can we close this issue? My understanding is that https://github.com/kubecost/cost-model/pull/1092 closed this out.

**Comment by kbrwn** [comment]
If @mbolt35 believes his PR fixed this issue sure.

**Comment by mbolt35** [comment]
@AdamStack18 Yes, this fix is merged.
