### ISSUE TITLE
Ingress template file bug

### ISSUE THREAD

**Issue by chrism417** [kubecost/cost-analyzer-helm-chart#1251]
In the cost-analyzer-ingress-template.yaml file, line 8 has:

{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}

but it should be:

{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}

Changing it to the correct value allows the ingress to be created with the correct spec.

gz#1390

**Comment by kaelanspatel** [comment]
Hi @chrism417.

Can you expand a little on the issue(s) this causes? This was a change made because `networking.k8s.io/v1` does not have the Ingress type for all K8s versions.

**Comment by chrism417** [comment]
Hello,
Interesting. We are running kubernetes version 1.22.2 and above and `Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress"` returns the deprecated ingress spec.

**Comment by kbrwn** [comment]
@kaelanspatel @mbolt35 I agree with @chrism417 that `networking.k8s.io/v1/Ingress` is not valid for ingress in v1.22. We need to follow: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

adding high priority

**Comment by kbrwn** [comment]
@chrism417 can you confirm the version of kubectl that is in use? The .Capabilities.APIVersions.Has feature of the chart makes use of the kubectl client and a mismatch could be an issue here.

**Comment by chrism417** [comment]
`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by AjayTripathy** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/pull/1267 is expected to solve this issue, and is expected in our next release.
