### ISSUE TITLE
Expose metrics about kubecost for prometheus

### ISSUE THREAD

**Issue by kbrwn** [kubecost/cost-analyzer-helm-chart#1252]
To allow users to better monitor kubecost with prometheus kubecost should expose metrics about the health/actions of kubecost. For example:

• Metrics on incoming requests

• Metrics on outbound requests to cloud providers 

• Metrics on queries to Prometheus

gz#1362</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-68) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
+1, I imagine this would be pretty straightforward to implement. Design areas worth discussion IMO:

* naming conventions -- are there known examples in other application? I know Prom itself exposes some...
* details on specific events we would track -- @kbrwn let us know if you have any more specific in mind here

To play devil's advocate a little too, we've seen that most teams aren't using AlertManager... do we know what would be used to monitor this?

**Comment by MrColeC** [comment]
This is related to [#264](https://github.com/kubecost/cost-model/issues/264) - right?

**Comment by AjayTripathy** [comment]
Yes-- we're still in the design phases here so we'll consolidate this soon!

**Comment by AdamStack18** [comment]
@kbrwn @dwbrown2 Can we close this issue and #264?  If not do we have a list of additional items to include in v1.95?

**Comment by dwbrown2** [comment]
Would love to get input from users that requested and see if there are more metrics of interest!

**Comment by MrColeC** [comment]
As shared in https://github.com/kubecost/opencost/issues/264

We are interested in Kubecost specific metrics such as:
- histogram metric for frontend response times and request
- histogram metric for API response times and request
- histogram metric for etl build times
- histogram metric for etl file sizes
- gauge metric for # of green etl days
- gauge metric for # of NON-green etl days

I understand some (perhaps most?) of that was added in 1.94 which was just released and we are about to roll out. I will need to review what was done there to frame any ask for additional.

That being said, the intent is:
1. Metrics that help us know Kubecost is working well **inside** (It's ETL is healthy, its routine tasks are functional, it can access data to ingest ok and things are operating normally)
2. Metrics related to user actions (they are able to use Kubecost, it is working well for them; basically traditional RED metrics)

**Comment by AdamStack18** [comment]
@MrColeC Thanks for the response.  I will review your list against the build on Monday. 

CC: @dwbrown2

**Comment by AdamStack18** [comment]
@MrColeC This issue is still on my radar. Will update soon.

**Comment by kirbsauce** [comment]
Here is another use case where we could alert -> https://kubecost.slack.com/archives/C02DNV35W21/p1660314823459869?thread_ts=1659979361.961269&cid=C02DNV35W21

(alert on abnormal ETL file size, for those who don't have permissions to see this particular slack.)

**Comment by raids** [comment]
> * gauge metric for # of green etl days
> * gauge metric for # of NON-green etl days

these metrics would be immensely useful for us too. We would want PrometheusRules to power alerts for when ETL processes fail.

**Comment by Adam-Stack-PM** [comment]
@raids, Thanks for this idea. Will review with the team.

**Comment by AjayTripathy** [comment]
Seems groupable with #1152 . @Adam-Stack-PM can you get those together and tracked under monitoring tasks?

**Comment by AjayTripathy** [comment]
And #1695 as well.
