### ISSUE TITLE
Kubecost-deployment: accessMode of PVC isn't customizable, but user is able to set number of replicas

### ISSUE THREAD

**Issue by behofer** [kubecost/cost-analyzer-helm-chart#1254]
## Summary
User is able to set replica count for kubecost deployment in values.yaml. This leads to conflicts with accessMode of PVC which is hard-coded "ReadWriteOnce". This isn't supposed to be working for most storage classes.

## User impact
Setting replica count to a number > 1 leads to only one working replica of kubecost deployment when using default PVC.

## Possible solutions
* Get it automated by using corresponding accessMode in PVC
* Make accessMode customizable in values
* If replicas > 1 isn't supported at all in free tier, this should be made clear for the user or kubecostDeployment.replicas should be removed.

gz#1404

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-69) by [Unito](https://www.unito.io)

**Comment by ivankube** [comment]
@behofer There is a comment in [values.yaml](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L597):

`# Kubecost Deployment Configuration`
`# Used for HA mode in Business & Enterprise tier`

What would be the better comment in your opinion?

**Comment by behofer** [comment]
Yes, I've seen that comment ... The better way would be to either remove the value completely or to add accessMode paramter (or set accessMode accordingly if the user changes number of replicas). For me as a user it's not a good way to have paramters which lead to some non-working pods; t first glance, that's a bug in chart design.
If you intend to leave the comment, I'd rather have something like: "Usage of HA mode is not supported by this chart!". That would be more clear IMHO.

**Comment by dwbrown2** [comment]
@behofer we actually have many config options in the helm chart that aren't relevant when a particular feature isn't enabled. I don't see anything wrong with that pattern. 

Would love to see what we can support for different `accessModes` that are new in 1.22. https://kubernetes.io/blog/2021/09/13/read-write-once-pod-access-mode-alpha/

@michaelmdresser would this be out of scope of rotation this week?

**Comment by michaelmdresser** [comment]
> would this be out of scope of rotation this week?

I'm swamped this week with higher-priority support work. I think it normally would be a good candidate for the support rotation, though!

**Comment by dwbrown2** [comment]
@AjayTripathy to review before next week's sprint
