### ISSUE TITLE
Allow set fqdn in nginx config (kubecostFrontend)

### ISSUE THREAD

**Issue by skillcoder** [kubecost/cost-analyzer-helm-chart#1271]
**What problem are you trying to solve?**
Our cluster coredns do not support following domains
`app.namespace`
It can support only fqdn (app.namespace.svc.cluster.local) or just namespace level, eg `app`
For example i want to set grafana upstream host to `kubecost-grafana.kubecost.svc.cluster.local`, but currently I can't.
The same with cost-model and server, I can't set it to `localhost:9003` and `localhost:9001` accordingly.
Related code:
https://github.com/kubecost/cost-analyzer-helm-chart/blob/aefe69f814ef722cffd02b34eacae2c090248277/cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml#L48-L72

**Describe the solution you'd like**
Add some new values to the values.yaml file to set this fqdn in cost-analyzer-frontend-config-map-template.yaml for:
* upstream api 
* upstream model
* upstream grafana
* upstream clustercontroller
Just use this values if they set (server value with port) instead trying to build them from different parts.

**Describe alternatives you've considered**
Right now I use **VERY PAINFUL** workaround by completely replacing configmap `nginx-conf` and reload `kubecost-cost-analyzer` pod.

**How would users interact with this feature?**
Just set this value under `kubecostFrontend` in local helm values.yaml file.

gz#1437

**Comment by AjayTripathy** [comment]
Hi @skillcoder thank you for filing this issue. This seems reasonable-- we'll get it triaged and looked at soon!

**Comment by dwbrown2** [comment]
@skillcoder thanks to @biancaburtoiu we now have a PR outstanding! does this look like it meet the needs you have? any feedback on the progress so far?

**Comment by evgenii-denisov** [comment]
@biancaburtoiu Thank you for PR. I have added few comments.
