### ISSUE TITLE
awsstore deployment doesnt work.

### ISSUE THREAD

**Issue by wesleyorama-grindr** [kubecost/cost-analyzer-helm-chart#1273]
**Describe the bug**
"awsstore" in cost-analyzer helm chart values file doesnt represent all required fields.

**To Reproduce**
1. Attempt to deploy helm chart with awsstore / useAwsStore set to true
2. Note deployment doesn't complete / hangs or fails with `The Deployment "kubecost-cost-analyzer-awsstore" is invalid: spec.template.spec.containers[0].image: Required value` depending on your tooling. 

**Expected behavior**
the awsstore deployment deploys successfully. 

**Screenshots**

**Collect logs (please complete the following information):**

I have already resolved the problem and cannot get this Information without breaking it again. 

gz#1439

**Comment by wesleyorama-grindr** [comment]
See PR above for the fix I implemented locally.

**Comment by kbrwn** [comment]
@wesleyorama-grindr Thank you for this bug report and commit! We will review asap.

**Comment by kbrwn** [comment]
Hello @wesleyorama-grindr I have updated the documentation to more accurately reflect the steps to complete an AWS Marketplace Install of kubecost: https://github.com/kubecost/docs/blob/main/aws-marketplace-install.md 

You can find this doc and many others on guide.kubecost.com as well: https://guide.kubecost.com/hc/en-us/articles/4407596808087

**Comment by wesleyorama-grindr** [comment]
@kbrwn Thanks, I will close this PR and issue.
