### ISSUE TITLE
Add the ability to define a default report

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1285]
**What problem are you trying to solve?**
Curate the cost allocation view so that users are presented with a predefined view when they access the UI.

**Describe the solution you'd like**
Right now the first saved report acts as the default. To change the default saved report, you need to delete all the reports prior to it so that it becomes the first. I'd like to see the ability to change the first/default report.

**Describe alternatives you've considered**
n/a

**How would users interact with this feature?**
Select the default report from the saved reports view.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-73) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
This makes sense to me. @nealormsbee thoughts?

**Comment by nealormsbee** [comment]
Agree this is a very sensible ask.

**Comment by dwbrown2** [comment]
Yup, or maybe support both?

**Comment by anoop2811** [comment]
In addition each user may need a different default view, so having the default view as a user level information would be something we are interested in

**Comment by dwbrown2** [comment]
@anoop2811 completely agree. just curious, do you currently use SAML with Kubecost? 

Just trying to determine if that should be stored locally (i.e. browser local storage) or on Kubecost backend (i.e. using account mapping)

**Comment by anoop2811** [comment]
@dwbrown2 , thanks and yes we use SAML with kubecost.

**Comment by clekas-fff** [comment]
Would love the ability to set this. As it is, we ended up with a default being the report created by the first team to save one and even if we were to define a different default before anyone else could define one, we don't have a way to change it without deleting all of our other reports (as I understand it, at least).
