### ISSUE TITLE
Add support for Norwegian Krone (NOK)

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1296]
What problem are you trying to solve?
My cloud provider(Azure) invoices me in Norwegian Krone (NOK), I would like to be able to view the cost in Kubecost with the same currency symbol.

Describe the solution you'd like
The ability to select NOK as a supported currency.

Describe alternatives you've considered
none

How would users interact with this feature?
Set via UI or helm values.

**Comment by dwbrown2** [comment]
Should be available in current release as a result of https://github.com/kubecost/cost-analyzer-frontend/pull/467!

**Comment by srpomeroy** [comment]
Would still need to be added to the settings drop down in the UI.

Don't we also use currency code when getting Azure and GCP ondemand rates?

**Comment by dwbrown2** [comment]
I see it available here: http://nightly.kubecost.io:9090/settings.html Anywhere that it's missing in the UI?

**Comment by srpomeroy** [comment]
@dwbrown2 I think you may be looking at DKK. This issue is for NOK support.

**Comment by dwbrown2** [comment]
Doh, huge mistake on my end. My apologies. 

@AjayTripathy would this be a good potential first issue for Bianca while she works on building the backend? Reference PR in comment above.

**Comment by dwbrown2** [comment]
@srpomeroy does getting scheduled next week work for your timing? let us know if it's urgent.
