### ISSUE TITLE
alertmanager.persistentVolume.enabled=false and pushgateway.persistentVolume.enabled=false are not working

### ISSUE THREAD

**Issue by gknepper** [kubecost/cost-analyzer-helm-chart#130]
**Describe the bug**

alertmanager.persistentVolume.enabled=false and pushgateway.persistentVolume.enabled=false are not working

**To Reproduce**

I'm deploying the app and I still see the the this volumes pending indicating the directive is not being respected. 

**Expected behavior**

Don't create the volumes like the variables persistentVolume.enabled=false and prometheus.server.persistentVolume.enabled=false

**Comment by dwbrown2** [comment]
Thanks for reporting this, @gknepper! We are able to reproduce and are exploring a fix now.

**Comment by gknepper** [comment]
Just letting you know. I updated to version 1.46.5 and the issue persists. Thanks.

**Comment by dwbrown2** [comment]
Thanks for bumping this. We're actively testing this today. We expect to have in our build tonight.

**Comment by dwbrown2** [comment]
Turns out this is an issue in our Prometheus subchart dependancy. We're investigating what is would take to resolve. Sorry taking a bit longer than expected.

Potential immediate workarounds: 1) disable alertmanager/pushgateway outright with helm options 2) manually delete these PVs

**Comment by AjayTripathy** [comment]
Hi, I'm unable to reproduce as of 1.46.6. 

```
Ajays-MacBook-Pro-2:cost-analyzer atripathy$ git diff
diff --git a/cost-analyzer/values.yaml b/cost-analyzer/values.yaml
index 6d95e17..8135adb 100755
--- a/cost-analyzer/values.yaml
+++ b/cost-analyzer/values.yaml
@@ -143,10 +143,10 @@ prometheus:
       enabled: true
   alertmanager:
     persistentVolume:
-      enabled: true
+      enabled: false
   pushgateway:
     persistentVolume:
-      enabled: true
+      enabled: false
   serverFiles:
     prometheus.yml:
         remote_write:
```

installing with this yields 
```
 kubectl get pv

NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                 STORAGECLASS   REASON   AGE
pvc-2200a87b-ebcb-11e9-bc0d-42010a8000ed   8Gi        RWO            Delete           Bound    default/jenkins                       standard                17d
pvc-bb11125e-f9da-11e9-96e9-42010a80005f   32Gi       RWO            Delete           Bound    kubecost/kubecost-prometheus-server   standard                13m
pvc-bb118e9b-f9da-11e9-96e9-42010a80005f   1Gi        RWO            Delete           Bound    kubecost/kubecost-cost-analyzer       standard                13m
```

Could you perhaps provide a little more context on how this occurred? Is the issue that once volumes have been created and you upgrade with different values, the PVs are retained? If so, I would recommend just manually deleting them.

**Comment by gknepper** [comment]
Hi there,

I'm installing every time from scratch to test. I just installed the version 1.46.6 and the volumes are still being created:

I'm using this variables:
	prometheus.server.persistentVolume.enabled=false
	alertmanager.persistentVolume.enabled=false
	pushgateway.persistentVolume.enabled=false
	persistentVolume.enabled=false
	kubecostToken="Z2FicmllbEBsbnguY29tLmJyxm343yadf98" 

I'm using rancher 2.x

**Comment by dwbrown2** [comment]
@AjayTripathy you are doing my suggested workaround option 1. I've also recreated this on 1.46.6. It's a subchart issue. Let's discuss tomorrow.

**Comment by gknepper** [comment]
Hi There, I tried to delete the PVs manually but rancher didn't allow me that because the cost-analyzer-prometheus-alertmanager and cost-analyzer-prometheus-pushgateway are waiting for them.

**Comment by dwbrown2** [comment]
Confirmed that setting `prometheus.alertmanager.persistentVolume.enabled` addresses this. @gknepper is this still an outstanding issue for you?

**Comment by gknepper** [comment]
Hello @dwbrown2, I moved cost-analyzer to another cluster sometime ago and everything looks to work fine. BTW, now I'm using a persistent volume. I don't have a place to test the variable, sorry. Thanks.

**Comment by dwbrown2** [comment]
Thanks for the feedback, @gknepper! I was able to confirm on a cluster, so I'll mark this as closed. Reach out if we can get you anything else.
