### ISSUE TITLE
Typo in network costs role template

### ISSUE THREAD

**Issue by andy-cowley** [kubecost/cost-analyzer-helm-chart#1301]
https://github.com/kubecost/cost-analyzer-helm-chart/blob/8798fd26db93205122f5895d9e485088060f897f/cost-analyzer/templates/network-costs-role.template.yaml#L9

See this line `lables > labels`

gz#1483

**Comment by mbolt35** [comment]
Fixed in https://github.com/kubecost/cost-analyzer-helm-chart/pull/1300
