### ISSUE TITLE
[FR] More attention / testing during releases

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-analyzer-helm-chart#1304]
**What problem are you trying to solve?**

This is not a real FR but a request.
Can you please pay more attention to the releases of the Helm Chart, especially the changes made to the Network Policies?

In the last few releases, there have been two rather gross errors that broke the chart:
- 1.90.0 https://github.com/kubecost/cost-analyzer-helm-chart/issues/1236
- 1.91.0 https://github.com/kubecost/cost-analyzer-helm-chart/issues/1301

I want to add that there is a lot of time between reporting the issue, its correction, and the release of a new correct chart.
7 days have passed between version 1.90.0 and 1.90.1. 
I hope 1.19.1 will be released as soon as possible.

**Describe the solution you'd like**

I would like extended chart tests to be done because it is clear that these two issues are the result of a lack of tests.

I would like that, when an issue is opened for an error that breaks the chart, it will be corrected immediately and a fix release made as soon as possible.

**Describe alternatives you've considered**

No alternative

**How would users interact with this feature?**

Great joy in using the chart

gz#1489

**Comment by mbolt35** [comment]
With respect to testing, it's not possible for us to test every permutation of helm argument accepted in our helm chart. We have integration tests that run every day and we're continuing to expand our coverage of these tests. However, adding a new option to our helm chart increases the number of outcomes exponentially, so there will unfortunately never exist complete coverage, and there will exist certain issues that sneak by. Apologies for the two issues you've run into lately with the upgrade, I can assure you we're doing our best to stay on top of this. 

Our release schedule is set on what we feel is best for our team and our customers. If you're unsatisfied with the duration between releases, we do cut nightly builds that you're more than welcome to use: 
```
$ helm repo add kubecost-nightly https://kubecost.github.io/nightly-helm-chart
$ helm repo update
$ helm upgrade kubecost -n kubecost kubecost-nightly/cost-analyzer
```

**Comment by pierluigilenoci** [comment]
@mbolt35 I can understand the difficulties but here we are talking about two particularly striking cases.

In the first case, it is a `space` that made it impossible to install the network policies completely.
Therefore a rather serious case and therefore a rather evident lack of a test.
Ref: https://github.com/kubecost/cost-analyzer-helm-chart/pull/1237/files

In the second case, it is a `typo` in the YAML which makes it equally impossible to create network policies.
This also shows that there is not even a single test on NPs.
Ref: https://github.com/kubecost/cost-analyzer-helm-chart/pull/1300/files

I'm not talking about the release schedule which is certainly linked to software development.
I'm talking about emergency releases to be done to correct only and exclusively the problems that make the software unusable (or in this case the chart). 
Creating a branch with just the fix and make release is a matter of minutes.

I am sorry to note once again that, despite the "talk a lot about community", here the interest of the "community of those who pay" is made above all.

I would like to add that we (or rather my company) would have liked to become part of the community of those who pay.
As we have told you several times.
Once all the issues we had raised had been resolved.
Some have still been awaiting resolution for a year now.

**Comment by AjayTripathy** [comment]
Hi @pierluigilenoci . Thank you for this feedback. 

First of all, I want to share some context on #1301 and I'm sorry you encountered it. We do integration test the deployment of network-costs through the chart. In this particular case the network-costs pod was broken only if Pod Security Policies were enabled from the network-costs pod, which was not integration tested. PSPs are deprecated-- I don't disagree that in a perfect world we'd have integration tests that deployed kubecost with them, but we don't use them in our own testing environments today, though I'm happy to add them.

Second of all, I just updated v1.91.0 with this fix, so you should be able to just helm upgrade and have this work now. Going through a full patch release takes some time since image versions need to be bumped.

That being said, I'm going to close this issue out in favor of actionable testing items like https://github.com/kubecost/cost-analyzer-helm-chart/issues/1307 that I just filed.

**Comment by pierluigilenoci** [comment]
@AjayTripathy thanks so much for everything.

Thanks for solving the problem. 
But above all for your constant and continuous availability.
It is always a pleasure to interact with you. 👍🏻
