### ISSUE TITLE
Limit node recommendations to available nodes 

### ISSUE THREAD

**Issue by kbrwn** [kubecost/cost-analyzer-helm-chart#1316]
**What problem are you trying to solve?**

Cluster sizing recommends nodes to users that may not be available to managed k8s options such as EKS.

**Describe the solution you'd like**

Cluster sizing should limit node suggestions based on cluster type. 

**Describe alternatives you've considered**

There are no alternatives. This feature is not useful if suggesting nodes that cannot be deployed. 

**How would users interact with this feature?**

/cluster-sizing.html page

 gz#1516</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-75) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
Have an example or AWS docs that you can share? 

I do believe we today look at look at provider, split by arch type, and then bin pack.

**Comment by kbrwn** [comment]
See the associated ticket (#1516) to see a suggestion of a node that is not available to an EKS

**Comment by srpomeroy** [comment]
THis should probably be associated with https://github.com/kubecost/cost-analyzer-helm-chart/issues/1117

**Comment by srpomeroy** [comment]
And [#985](https://github.com/kubecost/cost-model/issues/985)

**Comment by kbrwn** [comment]
@srpomeroy thank you @kirbsauce let's bring this up in the issue planning meeting later today. I'm fairly certain that v1.91 is suggesting ARM instances when set to x86 which would be a regression.

**Comment by srpomeroy** [comment]
> I'm fairly certain that v1.91 is suggesting ARM instances when set to x86 which would be a regression.

Can confirm I've seen this behavior as well.

**Comment by Adam-Stack-PM** [comment]
@biancaburtoiu, Wondering if you've had time to look at this bug or did SPA overshadowed it?

**Comment by biancaburtoiu** [comment]
Didn't have the time unfortunately! Also needing more context here on how to determine instance type eligibility for a given cluster. @Adam-Stack-PM

**Comment by Adam-Stack-PM** [comment]
@srpomeroy With Kyle gone, would you be willing to help track down the additional context needed for this issue?

**Comment by srpomeroy** [comment]
> @srpomeroy With Kyle gone, would you be willing to help track down the additional context needed for this issue?

I can certainly try @Adam-Stack-PM!
