### ISSUE TITLE
Don't trigger daily repair on rebuild of hourly

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1318]

**Comment by AdamStack18** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/issues/1317

**Comment by AdamStack18** [comment]
@kirbsauce Closing this out. https://github.com/kubecost/cost-analyzer-helm-chart/issues/1317 should have fixed the issue. Reopen it if needed.
