### ISSUE TITLE
Cluster Sizing Recommendations providing incorrect instance types for cloud provider

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1320]
**Describe the bug**
Multi-cloud deployment. Primary on AWS. Looking at cluster sizing recommendations. Regardless of what cluster I am looking at Kubecost is recommending AWS instance sizes.

**To Reproduce**
1. Deploy Kubecost to clusters across at least two different clouds and federate with Thanos.
2. View cluster sizing recommendations for the secondary cluster
3. Verify if instance types are for primary or secondary cluster

**Expected behavior**
Instance type recommendations should be for appropriate cloud the cluster is running on.

**Screenshots**
kc-demo-prod = AWS
kc-demo-stage = GCP
kc-demo-dev = Azure 
![image](https://user-images.githubusercontent.com/15660532/158870933-b002cfa0-8d2d-4429-b8ce-fc17f6f3855e.png)
![image](https://user-images.githubusercontent.com/15660532/158870947-5babc6bc-4cfe-43da-8f96-466c3d8890d0.png)

**Collect logs (please complete the following information):**

 - Run `helm ls` and paste the output here:
NAME    	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART               	APP VERSION
kubecost	kubecost 	9       	2022-03-16 23:14:34.079864 -0400 EDT	deployed	cost-analyzer-1.91.2	1.91.2

**Comment by dwbrown2** [comment]
@nealormsbee would this be a fit for current support rotation or need to be traiged?

**Comment by nealormsbee** [comment]
I can take a look, but I suspect this issue has deep roots. At cluster startup we create a Provider object for that cluster, and then proceed to use that for everything provider-related (like asking what node types are available). We'd want instead to create a new Provider for a given cluster on every request-sizing query. I don't know exactly how much lift that is, but it's likely a lot.

@nikovacevic or @mbolt35 may know more or be better able to articulate.

**Comment by dwbrown2** [comment]
Sounds like waiting is best. I also feel like we have a potential cluster of issues we could address on cluster right-sizing. @michaelmdresser want to get this on your radar as tech lead in this area.

**Comment by Sean-Holcomb** [comment]
Deep roots indeed, I will see what can be done here.

**Comment by dwbrown2** [comment]
@Sean-Holcomb able to make any progress?

**Comment by biancaburtoiu** [comment]
I picked this up - Strongly believe we need to sort this out before doing any further developments on the cluster sizing page. Just put a PR up...
