### ISSUE TITLE
Deploy sigv4 sidecar for Thanos queries

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1321]
Ideally, would like to have top-level “values” for the AMP workspace that would create a sigv4 sidecar for Thanos queries and set the remote_write values for primary and secondary clusters. As a workaround.  This would eliminate the need to run a sigv4 proxy as a workaround.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-76) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
@kirbsauce thanks for reporting. any change you can share what problem this is solving or why running a sigv4 proxy is needed? I thought thanos supported a `signature_version2: false` flag.

**Comment by kirbsauce** [comment]
@AjayTripathy can confirm, but I believe sigv4 is needed to make remote-write API calls to AMP...https://aws.amazon.com/blogs/opensource/prometheus-2-26-0-adds-aws-signature-version-4-support/

**Comment by AjayTripathy** [comment]
The sigv4 proxy is needed for _reads_ against AMP. I believe remote write to AMP is already supported internally within prometheus.

**Comment by kirbsauce** [comment]
thanks @AjayTripathy !
