### ISSUE TITLE
Workload Savings Multi-cloud **From D2IQ**

### ISSUE THREAD

**Issue by bruced2iq** [kubecost/cost-analyzer-helm-chart#1325]
**What problem are you trying to solve?**
I would like to be able to deploy workloads to different environments based on cost savings

**Describe the solution you'd like**
I would like to see a report for a workload and instead of just telling me to right size the instance to save x dollars, I would be able to see that if I deployed this workload on GCP instead of AWS I would save x dollars.

**Describe alternatives you've considered**
Only way is deploying workloads to multiple clouds and doing the comparison manually.

**How would users interact with this feature?**
Very frequently

gz#1564

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-78) by [Unito](https://www.unito.io)

**Comment by ivankube** [comment]
Thanks for sending in this feature request! We can’t always add new features that are requested, but we do keep track of each one. This may be something we look into later on down the line

**Comment by AjayTripathy** [comment]
Hey @bruced2iq ! This seems like a great idea. I think it wraps up nicely with the idea of "workload estimates" where we use our API to estimate costs based on requests before a workload is deployed. So you can see the cost of deploying a workload cleanly on different instance types, like n1-standard-1, t1-small, etc.

**Comment by dwbrown2** [comment]
+1, definitely in favor of exploring further soon. We've had a number of users already do this with our APIs. 

@bruced2iq would love to run some product ideas by you soon if interested!
