### ISSUE TITLE
New allocations of shared resources

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#1329]
**What problem are you trying to solve?**
There's a growing collection of use cases that direct us towards new and different allocations of shared costs. Here are a handful of examples: 

* During full-cluster upgrades, some services don’t handle node transfers very well. Users ask to “park” certain nodes during upgrades to keep Kafka and other problematic apps up as much as possible. During this period, shared costs should not be allocated to the workloads running on these parked nodes.
* Teams have tainted node pools or scale sets for certain applications in their cluster. This could be for security or other isolation reasons. Tenants on these workloads may receive a different portion of shared/idle costs. 

**Describe the solution you'd like**
It would be nice to allow users this ability to set these custom rules. It feels complex enough that a UI would be valuable but API may work too. 

**Describe alternatives you've considered**
A number of teams take our APIs and do custom distribution of shared, idle, etc.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-80) by [Unito](https://www.unito.io)

**Comment by mmurph3** [comment]
We have another customer looking for this request. On prem. Example use case:

For production clusters - multiply shared cost by 2
For dev clusters - multiply shared cost by 3
