### ISSUE TITLE
AWS costs

### ISSUE THREAD

**Issue by lax-m** [kubecost/cost-analyzer-helm-chart#134]
I have created the cost analyser service and able to access the web page now. There are some widgets which show loading icon especially the cost widget. Where should I add my aws keys to get the cost info .

<img width="711" alt="Screenshot 2019-10-21 at 12 37 00 PM" src="https://user-images.githubusercontent.com/56817161/67183654-a1e72180-f3ff-11e9-9cee-60a7556879fe.png">

**Comment by dwbrown2** [comment]
Hi @lax-m, happy to help. Can you share any errors available in your developer console? Also, can you confirm what version you are running (available in Settings)?

**Comment by lax-m** [comment]
I don't see any errors. All other widgets load. but the Cost section keeps showing loading symbol which I have attached in the above comment. 
I am using this tar https://github.com/kubecost/cost-analyzer/blob/gh-pages/cost-analyzer-1.46.5.tgz

**Comment by dwbrown2** [comment]
Hm, what platform are you on? There should be either a request that is failing / not returning or an error in the developer console. 

You can also look at pod logs directly with a command like this: `kubectl logs kubecost-cost-analyzer-<pod-extension> -n kubecost -c cost-model`

**Comment by dwbrown2** [comment]
@lax-m, are you still stuck here? Let me know if we can help.

**Comment by dwbrown2** [comment]
@lax-m is this issue still outstanding?

**Comment by dwbrown2** [comment]
Closing because this issue was resolved!
