### ISSUE TITLE
"Zero case" workload rightsizing should have consistent efficiencies and non-zero sizing recommendations

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1343]
version 1.92.0 rc-0

**Describe the bug**
Savings, over-provisioned workloads...

* Rightsizing recommendations are 0.
* Efficiency #s are inconsistent.
* Seeing recommendations with zero savings.

**Expected behavior**

1. I would expect these corner cases to at least have consistent efficiencies and non-zero sizing recommendations
1. I would expect that when the savings are zero I wouldn't be concerned with rightsizing them, rather I would address these in abandoned workloads.

**Screenshots**
![image](https://user-images.githubusercontent.com/46360304/161155753-2bfe7475-734e-47c8-84f8-c28179838468.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-81) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
@kirbsauce any chance you have a repro case here? I suspect this is happening in the back API in certain scenarios, e.g. when we have little to no data points. 

cc @michaelmdresser who is in this part of the code base this week

**Comment by kirbsauce** [comment]
Sure @dwbrown2 , all you need to do is go to the request-sizing.html page on dogfood 1.92 RC
and sort Efficiency from lowest to highest.

**Comment by dwbrown2** [comment]
@michaelmdresser is this something you'd want to investigate?

**Comment by dwbrown2** [comment]
@michaelmdresser do you understand what is causing this issue?

**Comment by michaelmdresser** [comment]
Not exactly. The current request sizing API logic is extremely entangled and sorting out an issue like this is high-effort low-reward. More consistent logic would result from pursuing the API schema v2 and I suspect writing the entirety of API v2 would take less time than untangling the behavior described in this ticket.

**Comment by dwbrown2** [comment]
Ok, if you feel reasonably confident this isn't a quick win then we let's discuss time estimate for rewrite and decide if it should be a part of v1.94.

**Comment by Adam-Stack-PM** [comment]
@michaelmdresser, Any chance this item will be fixed with your current work in progress?

**Comment by michaelmdresser** [comment]
The new API in https://github.com/kubecost/kubecost-cost-model/pull/923 should address most of these concerns, but that PR doesn't close this issue because there is still frontend work required to get data from the new API in front of users.
