### ISSUE TITLE
Allow using ENV vars to set Prometheus external_labels cluster IDs in Federated Clusters

### ISSUE THREAD

**Issue by pzimno** [kubecost/cost-analyzer-helm-chart#1348]
**What problem are you trying to solve?**
We utilize Kubecost enterprise for the federated cluster view. We prefer our agents use a common/constant values file for manifest generation. This means setting `clusterName=` in a pricing-configs config map and `CLUSTER_ID=` in the cluster-id configmap. This prevents us from having to generate separate Helm templates for agents. 

Unfortunately the Kubecost comments above the `prometheus.server.clusterIDConfigmap` variable state:
>  NOTE: This does not affect the external_labels set in prometheus config.

Federated cluster documentation then [states](https://github.com/kubecost/cost-analyzer-helm-chart/blob/release-v1.91.1/cost-analyzer/values.yaml#L412):
> Ensure you provide a unique identifier for prometheus.server.global.external_labels.cluster_id to have additional clusters be visible in the Kubecost product, e.g. cluster-two.

Meaning we would have to generate a helm template with a separate values file for each federated cluster.

**Describe the solution you'd like**
Currently our workaround is turning on the [prometheus expand-external-labels](https://prometheus.io/docs/prometheus/latest/feature_flags/#expand-environment-variables-in-external-labels) flag so we can set `prometheus.global.external_labels.cluster_id` to `${CLUSTER_ID}`.

In the main values file under `prometheus.server` we then add:

```
env:
  - name: CLUSTER_ID
    valueFrom:
      configMapKeyRef:
        name: cluster-id
        key: CLUSTER_ID
```

This solves the issue mentioned by this comment
> NOTE: This does not affect the external_labels set in prometheus config.

It would be great to have this configurable with a helm chart value. 

**Describe alternatives you've considered**
We attempted to have a values file per each agent but this added in complexity and went against KISS/DRY principles.
If there is an alternative I missed that works instead of this workaround I would love to hear it too. 

**How would users interact with this feature?**

This could be default behavior when setting `clusterIDConfigmap` or an extra var. 

gz#1614

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-82) by [Unito](https://www.unito.io)

**Comment by keithhand** [comment]
Hi @pzimno, I could be incorrect here, so I'm going to tag @AjayTripathy, who will be able to confirm. I believe, though, that if you set up the `clusterIDConfigmap`, you shouldn't need additional modifications to the `external_labels` because Kubecost should be using this value rather than the value from Prometheus. The `external_labels` field is getting hard-coded in the values.yaml, so you will still get the `cluster-one` value, but I don't think that should affect your installation.

**Comment by AjayTripathy** [comment]
Hey @keithhand I do still think you need to supply different values to each helm chart-- you can't do this with just clusterIDConfigmap. That being said we can look to add this feature.
