### ISSUE TITLE
Remove thanos and grafana ingress in the bundled charts 

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#1349]
The old ingresses have been disabled and it is beyond the scope of this chart to run an ingress for thanos or grafana-- those are accessible via service addresses.

**Comment by dwbrown2** [comment]
Is it fair to call this low priority?

**Comment by Adam-Stack-PM** [comment]
Closing based on linked issues and priority status. Re-open if needed.
