### ISSUE TITLE
RBAC: Users are still able to authenticate after admin and readonly groups are enabled.

### ISSUE THREAD

**Issue by alonsogalvan** [kubecost/cost-analyzer-helm-chart#1350]
**Describe the bug**
When implementing SAML integration for user management and RBAC, both default groups, admin and readonly, are enabled. We expect that all user sessions without the respective assertionValues should not be able to access the UI.

**To Reproduce**
1. Set the following values in the values  yaml file:  

  rbac:
    enabled: true
    groups:
      - name: admin
        enabled: true # if admin is disabled, all SAML users will be able to make configuration changes to the kubecost frontend
        assertionName: "userType" # a SAML Assertion, one of whose elements has a value that matches on of the values in assertionValues
        assertionValues:
          - "admin"
          - "superusers"
      - name: readonly
        enabled: true # if readonly is disabled, all users authorized on SAML will default to readonly
        assertionName:  "userType"
        assertionvalues:
          - "readonly"
2. Install the chart.
3. See behavior when accessing the Kubecost UI.

**Expected behavior**
The expected behavior is to deny access to all users without the assertion values on their session.

**Screenshots**

**Collect logs (please complete the following information):**

 Please reach out for logs.

gz#1617

gz#1600<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1600'>Zendesk ticket #1600</a>)</i>

**Comment by dwbrown2** [comment]
@alonsogalvan just wanted to follow up here. did you mean to close? anything we can help with on this issue?

**Comment by kirbsauce** [comment]
Thanks for the followup, @dwbrown2 .  @keithhand and I worked with @alonsogalvan earlier today and agreed to close this once we made it past the hurdle.  Details in the linked ticket.

**Comment by dwbrown2** [comment]
Reading this ticket it feels like we could benefit from a diagnostic endpoint to help users understand what RBAC roles are currently being applied. @AjayTripathy what do you think?
