### ISSUE TITLE
Redirect loop when not passing SAML assertion values

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1351]
**Describe the bug**
After enabling both [RBAC SAML groups](https://github.com/kubecost/cost-analyzer-helm-chart/blob/c98f4856bc96d50c5a8a775547ac8ce539e7037b/cost-analyzer/values.yaml#L162-L175), if no SAML assertion value gets provided in the response, the application will continuously loop trying to authenticate.

**To Reproduce**
1. Enable SAML and RBAC user roles, don't pass any role assertion values via the SAML provider
2. Attempt to sign in
3. Hit redirect loop

**Expected behavior**
An "Access denied" page or possibly an error screen that indicates the application received no assertion value.

**Comment by dwbrown2** [comment]
Thanks, @keithhand! Assigning to @AjayTripathy for review.

**Comment by jessegoodier** [comment]
FYI, another customer reported the issue on April 26th.

**Comment by dwbrown2** [comment]
@teevans thoughts on this from the FE's perspective? I agree that a simple/standardized Access Denied page that links to our docs would make sense.

**Comment by AdamStack18** [comment]
@teevans added to Front-End Team board. Please remove it if that's not the correct place for this issue to live.

**Comment by teevans** [comment]
We actually have an unauthorized page already that I migrated to React last week. Should be able to use that!

Assigning to @nealormsbee since he's got some bandwidth.

**Comment by dwbrown2** [comment]
Also, could be totally wrong but I think @kaelanspatel is working on something related on the BE...

**Comment by AjayTripathy** [comment]
Hmm, maybe https://github.com/kubecost/cost-analyzer-frontend/blob/8b52a5f9304cacecd403d12f30bd6c4e303b54c4/static/vendor/helper.js#L1975

causes a redirect loop somehow? @kaelanspatel is investigating since I thought this was primarily a backend issue

**Comment by nealormsbee** [comment]
Assigning to @kaelanspatel since you're investigating. Just assign back to me if you need to throw it back!

**Comment by teevans** [comment]
@kaelanspatel - Did you already merge this fix in?

**Comment by kaelanspatel** [comment]
Yeah it should be in the release branch w/ https://github.com/kubecost/cost-analyzer-helm-chart/pull/1456. Will close this unless there are further concerns.
