### ISSUE TITLE
Add support for Swedish Kronor (SEK)

### ISSUE THREAD

**Issue by jonerer** [kubecost/cost-analyzer-helm-chart#1352]
What problem are you trying to solve?
My cloud provider(AWS) invoices me in Swedish Kronor (SEK), I would like to be able to view the cost in Kubecost with the same currency symbol.

Describe the solution you'd like
The ability to select SEK as a supported currency.

Describe alternatives you've considered
none

How would users interact with this feature?
Set via UI or helm values.

**Comment by dwbrown2** [comment]
@teevans might be a good quick one for next week!

**Comment by teevans** [comment]
@jonerer - This has been merged in, and should make it out with our next release! You should be able to select SEK via Helm values, or through the UI! Thanks so much for the feedback!
