### ISSUE TITLE
Only readonly permissions when no SAML RBAC groups are enabled

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1355]
**Describe the bug**
The user is unable to do various tasks when `saml.rbac.enabled = true`, but no groups are enabled. The user defaults with both `admin` and `readonly` groups, but the permissions seem based only on the `readonly` group. Saving and Un-saving reports were recognized as the first problem, though I think any task limited with the `readonly` RBAC group will behave this way.

**To Reproduce**
1. Enable SAML and RBAC with both `admin` and `readonly` groups disabled
2. Error out when saving or un-saving reports

**Expected behavior**
If a user has both RBAC groups `readonly` and `admin`, the `admin` permission set should take precedence over the `readonly` permissions.

**Comment by dwbrown2** [comment]
> If a user has both RBAC groups readonly and admin, the admin permission set should take precedence over the readonly permissions.

Totally see your point and think this is well put. But could this also be dangerous? i.e. someone intentionally adds a user to a read-only group and they overlook that they are also admin?

cc @AjayTripathy for his input!

**Comment by keithhand** [comment]
There is room for discussion, for sure. I thought having a "readonly admin" seems unintended, as that would be a readonly user and nothing admin about it. Perhaps a solution could be to change the role description to just "read" to be more descriptive of the permissions applied when attached.

**Comment by AjayTripathy** [comment]
I think that users should always take the least permissions of any group they're assigned for security reasons. That's why the group is called "readonly" -- a user in it can only read regardless of other groups, but open to further discussion

**Comment by dwbrown2** [comment]
@AjayTripathy is this one getting addressed with current work?

**Comment by AjayTripathy** [comment]
I think that this is already wai
