### ISSUE TITLE
Support Custom Google Analytics

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1358]
We would like to be able to enable google analytics on our kubecost deployments. To do this, we need to be able to add a tag right after the head tag on each page of kubecost. Is adding tags to the webpage code something that we could get support for? I am specifically referencing the “Add the global site tag directly to your web pages” section in the “Set up data collection (for websites)” section on this google analytics help page https://support.google.com/analytics/answer/9304153?hl=en&ref_topic=9303319#zippy=%2Cadd-the-global-site-tag-directly-to-your-web-pages

(created from [Zendesk ticket #1633](https://kubecost.zendesk.com/agent/tickets/1633))
gz#1633

**Comment by kirbsauce** [comment]
We actually already optionally support GA today. So I think we would just need to support passing a custom tracking ID via a helm flag. Would that work in this case? We can move this to a public issue if that's easier for user input.

@dwbrown2

**Comment by dwbrown2** [comment]
@teevans and I to start reviewing this week! currently expected for next release, v1.93

**Comment by kirbsauce** [comment]
FYI @AdamStack18

**Comment by dwbrown2** [comment]
> Note: this will provide basic frontend analytics, e.g. page views, time on page, etc. 

@teevans let us know if we can get someone to add in a BE endpoint with a helm chart flag. That will hopefully keep you moving really fast on FE!

**Comment by teevans** [comment]
Let me see what I can come up with tomorrow for this. This is a bigger lift because of the SPA disconnect. But, we're gonna knock it out.
