### ISSUE TITLE
Change content-type for webhooks

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#136]
We are currently sending `application/x-www-form-urlencoded;charset=UTF-8`. We should instead be sending `application/json`. This is most relevant for non-Slack webhooks.

**Comment by dwbrown2** [comment]
Ping... I suspect this would be easy to support?

**Comment by kirbsauce** [comment]
A look at the code indicates that this has been addressed.  Link to code shared offline.  Please close if satisfied with my evidence.
