### ISSUE TITLE
Release note for v1.92.0 is available but no chart for this version

### ISSUE THREAD

**Issue by ndctrb** [kubecost/cost-analyzer-helm-chart#1364]
**Describe the bug**
Release note for v1.92.0 is available but no chart for this version

**To Reproduce**
there's no chart 1.92.0 when using helm search repo kubecost -l

**Expected behavior**

**Screenshots**

**Collect logs (please complete the following information):**

 - Run `helm ls` and paste the output here:

 - If the pod is stuck in init, run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-init` and paste output here:

 - If a page is broken or not loading, open your javascript developer console and paste the ouput here:

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-server` and paste the output here:

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-model` and paste the output here:

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-frontend` and paste the output here:

gz#1649

**Comment by AjayTripathy** [comment]
Hi @ndctrb sorry for the delay. v1.92.0 is now avaialbel on the helm repository.
