### ISSUE TITLE
Support annotation filtering in the UI

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#1366]
**What problem are you trying to solve?**
We currently only support filtering by annotation optionally, and via the API. We should allow that in the UI as well.

**Describe the solution you'd like**
Filtering by annotations is supported in the UI

**Describe alternatives you've considered**
You can currently already use the API to do annotation filtering, but we would want to do this via the UI

**How would users interact with this feature?**
Via a filtering dropdown section for "annotations", but it should be greyed out if annotations are not being emitted.

gz#1658<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1658'>Zendesk ticket #1658</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-86) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
+1, what would the user experience be if annotations are disabled? Do we have a good way to determine if these are enabled or disabled from frontend?

**Comment by AjayTripathy** [comment]
Noted in the request that we should grey it out to show it's an option that's unenabled. I don't think we have a good way to tell if they're enabled from the frontend but it shouldn't be particularly hard.

**Comment by AdamStack18** [comment]
@teevans It could be a good project for Anna to test using the new design system and create a prototype for this feature.

**Comment by keithhand** [comment]
Had some more interest in this feature. Is there any update on when this might be usable?

**Comment by dwbrown2** [comment]
@Annalillie know you had a couple early mocks here. Have interest in revisiting during 1.99? I believe this should be quick on the eng side.

**Comment by Annalillie** [comment]
I'm interested and invested. I'll do some research into this and come up with some concepts! @dwbrown2
