### ISSUE TITLE
Ability to Inspect Shared Costs

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1367]
**What problem are you trying to solve?**
I am sharing a number of different costs within my clusters and I need to be able to see the composition of my shared costs. Shared can contain costs from fixed overhead, tenancy costs, namespaces, and labels. And those costs can be split evenly or proportionally based on spend.

**Describe the solution you'd like**
Just as external and network have the `Inspect...` options when aggregating by Namespaces in the Cost Allocation view, it would be great to have an `Inspect Shared Costs` option. Upon selecting it, it would show shared costs broken down by overhead, tenancy costs, shared namespaces, shared labels, and external costs.

![image](https://user-images.githubusercontent.com/15660532/163255293-853eae14-8194-48d0-88d1-0f5af8b81059.png)

**Describe alternatives you've considered**
None

**How would users interact with this feature?**
Using the `...` menu in front of the Namespace name, have an option to `Inspect Shared Costs`.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-87) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
+1, I think this is a good candidate for 1.94 IMO

**Comment by teevans** [comment]
For whatever mystical reason I thought there was already an API breakdown for this - @nikovacevic 1.94 may be out of question, but is there a way we could get an endpoint for this for 1.95?

**Comment by nikovacevic** [comment]
I'm happy to look into it and write up a design doc this week. Not going to make 1.94. We could try for 1.95.

As far as whether a new API is required or not, that will depend on what exactly we want to show, which is not entirely clear from this ticket description. In a general sense, we want to see "where costs came from" to end up in the shared cost column?

If so, a few questions:

1. Do we want to see shared costs _for an allocation_ as well? Like, considering the screenshot, _for kubecost namespace_ we want to see "what went into the shared cost column" for that row?
2. That set of information will be of a non-uniform schema (i.e. a mix of allocation data, scalar cost values, and tenancy costs). Do we want to just see `name` and `cost`? Are there other fields we'd want to see?
3. In the case of allocations, there will be ambiguity about aggregation. (e.g. you can share namespace kubecost and label app:cost-analyzer, which have overlapping allocation rows.) Do we want to just see "shared allocation data" as a single category? Or is the idea to see costs _associated by name with the "thing" you're trying to share_?

As a simplest possible example, you can imagine inspecting _global_ shared costs for a window, and just seeing three line items:
- Overhead... $
- Tenancy... $
- Allocation... $

**Comment by nikovacevic** [comment]
@teevans that would be my recommendation, but again -- the devil is in the details

@dwbrown2 you can do that, but again -- if you also share labels, and those labels overlap with each other, or with a shared namespace, you're not going to be able to get the number to line up without doing some very tedious math-y filtering.

**Comment by nikovacevic** [comment]
Might be worth pointing out:  if you're not worried about getting the column value to match the new page's value, then this is relatively easy without a new API.

e.g.
1. Shared cost for row R is C; you click on that
2. Navigate to page where it shows shared costs like: shared overhead c1, shared namespace A = c2, shared label B = c3, ...
3. You sum c1 + c2 + ... + cN and sometimes that will equal C, but sometimes it won't

**Comment by keithhand** [comment]
Bumping this as I recently had this issue brought up as a desired feature. We could do something similar to the cloud asset breakdown section on the Advanced report page. If we implement something like that for shared assets, I think that would get users the information they needed. Another option is possibly adding shared costs as a section on the `/details` page.

**Comment by teevans** [comment]
CC: @nealormsbee

**Comment by wamak9** [comment]
+1 and P0. @dwbrown2

**Comment by teevans** [comment]
Moving to 1.101 Prioritization.

**Comment by wamak9** [comment]
is this still part of v1.101  ?
@teevans  @dwbrown2

**Comment by dwbrown2** [comment]
We designed a solution here during 101 and are moving to implementation now. Please let us know if you have any questions.

**Comment by wamak9** [comment]
Is this still part of 1.101?, I don't see anything being listed with 1.101.2 release?

**Comment by kwombach12** [comment]
We designed a solution for this during the 1.101 release, it has not yet been implemented yet but we are pushing to have this built in the next release!

**Comment by wamak9** [comment]
@kwombach12  @dwbrown2  -- I see the 1.102 is released and there is still no word on this ticket ?
This is requested by every single user who is looking at the cost for his namespace and wants to know what is it user being billed for under the shared cost.

I am assuming we won't be seeing anything until next release which could be May mid week ?

**Comment by dwbrown2** [comment]
Definitely see the need, @wamak9. We're doing this as a major overall of advanced reporting. I believe @kwombach12 already shared but we plan to have a prototype available soon that we can share.

**Comment by wamak9** [comment]
do we have any ETA on this ? I see there is one more version got released and still no sign of this feature request.

**Comment by kwombach12** [comment]
@wamak9 we have started the implementation for this! It will be delivered in v1.104

**Comment by mmurph3** [comment]
Great work on getting this into v1.104. Can we look at adding idle costs as well?

cc @kwombach12

**Comment by srpomeroy** [comment]
@mmurph3 Let's raise a separate FR for inspecting idle costs to prioritize and track them appropriately.

**Comment by teevans** [comment]
Closing this!
