### ISSUE TITLE
Add a warning to the free version when selecting a > 15 day date range on the cost allocation page 

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#1368]
**What problem are you trying to solve?**
When using the free version which is limited to 15 days of data retention the "Assets" page displays a warning (see image) a date range > 15 days is selected. No warning is displayed on the "Cost Allocation" page when selecting a date range > 15 days. This can lead to confusion as it is unclear that the "Cost Allocation" charts are based on 15 days of data despite selecting a > 15 day date range.

"Assets" page displaying warning:
<img width="1389" alt="Screen Shot 2022-04-13 at 5 30 22 PM" src="https://user-images.githubusercontent.com/17748044/163277675-d71d6591-17dd-49f6-8572-e1fc60f30b65.png">

"Cost Allocation" page on the same install showing no warning with a 90 day range:
<img width="1104" alt="Screen Shot 2022-04-13 at 6 03 04 PM" src="https://user-images.githubusercontent.com/17748044/163277838-4723238e-7679-4ff2-a632-0380ddd84f65.png">

**Describe the solution you'd like**
Display the same warning on the "Cost Allocation" page when selecting a date range > 15 days.

**Comment by dwbrown2** [comment]
Thanks for reporting, Jason! I believe this is a regression if you're reviewing Bianca so you may be able to quickly grep for this string.

**Comment by biancaburtoiu** [comment]
Here it seems the frontend isn't able to capture and render the warning message returned by the allocation summary endpoint; I'm looking into a neat way to parse the API response! @dwbrown2 @jcharcalla
