### ISSUE TITLE
Support OIDC authentication for Kubecost

### ISSUE THREAD

**Issue by ErnestG4** [kubecost/cost-analyzer-helm-chart#1371]
**What problem are you trying to solve?**
Users would like Kubecost to support OIDC auth. 

**Describe the solution you'd like**
Support OIDC authentication with Oauth2 authorization. 

**Describe alternatives you've considered**
Currently, Kubecost only supports SAML auth. 

**How would users interact with this feature?**
Similar to how SAML is currently configured, but with a flag for OIDC and fields for the relevant configuration options.

**Comment by marinoborges** [comment]
cool, OIDC is our desirable SSO protocol so it would be good to have that option on Kubecost. Thanks!

**Comment by dwbrown2** [comment]
+1, we've had this request a number of times. Can we see about tracking for 1.94 @AdamStack18?

Is there any more guidance or docs on preferred path for integrating OIDC?

cc @AjayTripathy @keithhand

**Comment by srpomeroy** [comment]
@Adam-Stack-PM Sounds like this issue may have been fixed.
@kaelanspatel @biancaburtoiu I believe you may have the most context, can this be closed?

**Comment by biancaburtoiu** [comment]
Yes, @kaelanspatel introduced OIDC support a good couple of months ago!

**Comment by abdennour** [comment]
any guide how to integrate Kubecost enterprise with OIDC or even specifically Keycloak ?  thru the official helm chart

**Comment by srpomeroy** [comment]
> any guide how to integrate Kubecost enterprise with OIDC or even specifically Keycloak ? thru the official helm chart

Yes. https://github.com/kubecost/docs/blob/c5ecd850f0751def941bd538891aad90c4a5a77d/user-management-oidc.md
