### ISSUE TITLE
Add Helm linting/templating to PRs on this repo

### ISSUE THREAD

**Issue by michaelmdresser** [kubecost/cost-analyzer-helm-chart#1378]
We should add Helm linting via GH Actions as a PR check on this repo. At its simplest, this could involve just running Helm's built-in `lint` and `template` commands. It would help us catch issues like this: https://github.com/kubecost/cost-analyzer-helm-chart/pull/1377

This is a good first issue for a new hire.

**Comment by dwbrown2** [comment]
I think this would be impactful! @dramich any interest or experience here on your side? Feels like it could be a good one to explore next week if you do have interest. Just wanted to share because I overheard you might be looking soon.

**Comment by dramich** [comment]
@dwbrown2 Yes to both, this is also required in order to implement https://github.com/kubecost/cost-analyzer-helm-chart/issues/1362 which is currently tied to me

**Comment by dwbrown2** [comment]
Nice! Feel free to run with it. Seems like it doesn't have to be this week if you do have other stuff you're focused on! 

cc @AdamStack18 for tracking relative to releases
