### ISSUE TITLE
No default value for ETL_CLOUD_USAGE_ENABLED variable

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1382]
**Describe the bug**
When no value gets provided to the values.yaml file, no value gets assigned to the `ETL_CLOUD_USAGE_ENABLED` environment variable in the `cost-analyzer-deployment-template.yaml`. Based on [this doc](https://github.com/kubecost/docs/blob/6290d5818c9a78f92d088fc6d18c06385f82c1e2/cloud-integration.md#cloud-integration-configurations), this value should get set to true.

**To Reproduce**
```cmd
helm template kubecost kubecost/cost-analyzer | grep ETL_CLOUD_USAGE_ENABLED -A1`
            - name : ETL_CLOUD_USAGE_ENABLED
            - name: CLOUD_ASSETS_EXCLUDE_PROVIDER_ID
```

**Expected behavior**
```cmd
helm template kubecost kubecost/cost-analyzer | grep ETL_CLOUD_USAGE_ENABLED -A1`
            - name : ETL_CLOUD_USAGE_ENABLED
              value: "true"
```

gz#1713

**Comment by dwbrown2** [comment]
@keithhand did you notice an impact to application functionality as a result?

cc @AdamStack18 to track for this release

**Comment by keithhand** [comment]
@dwbrown2, I didn't notice app functionality impacted, though I didn't extensively test. The doc mentions that specific endpoints get enabled with that variable, so it might be good to check if they are still available with a default install.

**Comment by Sean-Holcomb** [comment]
There should be no impact because the env variable also defaults to true when it is pulled into the app
