### ISSUE TITLE
/orphaned-resources.html returns error on null values

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#1383]
**Describe the bug**
opening /orphaned-resources.html
returns:
Failed to load resources
Check that you have a valid service key and the cost analyzer API is running, then refresh

There are no other errors in the logs regarding this that I can find. 

**To Reproduce**
1. Go to '/orphaned-resources.html'
2. See error

**Expected behavior**
No error message

**Screenshots**
<https://files.slack.com/files-pri/TE6RTBNET-F03C7KDB83G/image.png>

**Collect logs (please complete the following information):**

N/A

**Comment by dwbrown2** [comment]
Thanks for sharing, @jessegoodier! Any chance there was an error message in the JR console?

cc @AdamStack18 to add v1.93 release tracking

**Comment by nealormsbee** [comment]
^ Jesse and I looked at this together. The console says "Unexpected end of JSON input..."

Reason being that the API is providing a totally empty response, rather than e.g. `[]` or `{}`, so it fails to parse.
