### ISSUE TITLE
consider pod limits on nodes when suggesting sizing changes to the cluster

### ISSUE THREAD

**Issue by thejohncostanzo** [kubecost/cost-analyzer-helm-chart#1384]
**What problem are you trying to solve?**
I have a cluster with many many pods that each require a small amount of resources. As a result they don't typically use all the cpu/memory on any node provided by AWS. Kubecost suggests downsizing my provisioned nodes (in size and/or count) to better match the compute usage, but it doesn't take into account the fact that the nodes also have limits on the number of pods they are allowed to have (typically due to limits on the network interface). e.g. I may be running ~160 different pods which could be scheduled on at least 3 2xlarge instance types (each can hold 58 pods for a total of 174), however kubecost insists i could get away with only 2 instances of a 2xlarge (which is incorrect and means this entire cost saving feature provides no value to me).

**Describe the solution you'd like**
Kubecost needs to take into account how many pods are allowed to be scheduled to nodes (and how many pods are on the cluster) to make appropriate recommendations.

gz#1705

gz#1696<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1696'>Zendesk ticket #1696</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-88) by [Unito](https://www.unito.io)

**Comment by kirbsauce** [comment]
Thanks for the submission, @thejohncostanzo !  cc'ing in @michaelmdresser and @AdamStack18 for visibility!

**Comment by dwbrown2** [comment]
Actually adding @biancaburtoiu because we've recently been discussing exactly this! +1 from me.
