### ISSUE TITLE
Cannot Add Annotations to Services

### ISSUE THREAD

**Issue by rlees85** [kubecost/cost-analyzer-helm-chart#1395]
**What problem are you trying to solve?**
There is no way to add custom annotations to the services created by the Kubecost Helm chart. This prevents existing cluster services and tools from working with the services Kubecost creates. A specific example is Prometheus set up in a custom way that may require additional annotations in order to pick up and scrape the services.

**Describe the solution you'd like**
A way to set custom annotations on service objects.

**Describe alternatives you've considered**
The only alternative is for everyone to run Prometheus in the way that Kubecost expects which is a non starter. Also other tools/services that rely on annotations will never be able to work - again a non starter.

**How would users interact with this feature?**
By defining the extra annotations as a map in Helm values.

gz#1737<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1737'>Zendesk ticket #1737</a>)</i>

**Comment by AjayTripathy** [comment]
Thanks for this report and the follow-on PR @rlees85 ! I'm generally supportive and can pick up this review.
