### ISSUE TITLE
Kubecost recommending ARM (x2gd.2xlarge) instead of x86

### ISSUE THREAD

**Issue by chicagozer** [kubecost/cost-analyzer-helm-chart#1397]
**Describe the bug**
Kubecost is recommending an ARM based processor, x2gd.2xlarge, even though I chose x86.

**To Reproduce**
Choose x86 on an AWS based cluster.

**Expected behavior**
x86 Recommendations.

**Screenshots**
<img width="866" alt="Screen Shot 2022-05-01 at 7 25 25 PM" src="https://user-images.githubusercontent.com/906190/166161488-fedbb959-e13e-4c8e-a89e-fe14bc624134.png">

gz#1753<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1753'>Zendesk ticket #1753</a>)</i>

**Comment by dwbrown2** [comment]
@biancaburtoiu would you be able to take a look given your recent work here?

**Comment by chicagozer** [comment]
@biancaburtoiu appreciate you looking at this...what was the resolution?

**Comment by biancaburtoiu** [comment]
Hi @chicagozer! Thanks for raising this - there was an issue in the way we were distinguishing between AWS x86 and ARM instances. It should be fixed in the following release!
