### ISSUE TITLE
Wrong link for the "request sizing"

### ISSUE THREAD

**Issue by RomanDvorsky** [kubecost/cost-analyzer-helm-chart#1399]
**Describe the bug**
When you drill down thru labels the "request sizing" button shows wrong (no) data.

**To Reproduce**
1. Go to 'Cost Allocation'
2. Aggregate by some label - team in our case
3. drill down to given team
4. Click "request sizing" button
5. No data are shown - error is shown :) "Failed to load request sizing recommendations
Invalid label filter. Label filters must be of the form key:value"

The button contains this link: "http://localhost:9090/request-sizing.html?filters=label:team%3Ateam=frontendframework"
instead of: "http://localhost:9090/request-sizing.html?filters=label%3Ateam%253Afrontendframework"

**Expected behavior**
Show filtered containers.

**Screenshots**
![image](https://user-images.githubusercontent.com/36188474/166458511-871ca61d-f808-4c9b-b6b9-109265a41198.png)
![image](https://user-images.githubusercontent.com/36188474/166458524-c833a9dc-2216-4407-b612-4982da5a4994.png)

gz#1759<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1759'>Zendesk ticket #1759</a>)</i>

**Comment by AjayTripathy** [comment]
Triaging to @biancaburtoiu since @kaelanspatel is working on something else I believe.

**Comment by dwbrown2** [comment]
cc @wolfeaustin since he's our expert here

cc @AdamStack18 for release tracking

**Comment by RomanDvorsky** [comment]
Hi, I have installed the latest version: "v1.93.0-rc.0" and I have to say it is not fixed!
![image](https://user-images.githubusercontent.com/36188474/166945105-b3c2c103-694a-4750-bd46-a81af2a89af6.png)
the error message is gone however it does not filter properly.

Wrong link now: https://kubecost-we-test.services.ori/request-sizing.html?filters=team%3Aacquisition  (label is missing here)
correct link: https://kubecost-we-test.services.ori/request-sizing.html?filters=label%3Ateam%253Aacquisition

**Comment by biancaburtoiu** [comment]
Hello @RomanDvorsky, sorry for the confusion! The fix isn't available in this release candidate, we expect to have it either in a following release candidate or in the final release.

**Comment by RomanDvorsky** [comment]
so just to tell that version 1.93.2 does not fix the issue either:
![image](https://user-images.githubusercontent.com/36188474/170240395-a6bd3643-9658-41f9-9ab8-9a27162528dc.png)
there should be `team:frontend...` not `team=frontendf...`

**Comment by biancaburtoiu** [comment]
Hi @RomanDvorsky, thanks for your patience! This is an issue in the way we're handling certain label types, we're looking to fix it ASAP.

To bypass the error and reach the correct page, start in the Cost Allocation page and aggregate by `Label:team` (i.e. write down "team" into the Label Name textbox, to obtain the filter as in the screenshot below) instead of using the predefined property `Team`. Then, if you drill down into your desired team, the Request Sizing link should point to the correct page. 

![image](https://user-images.githubusercontent.com/22826352/171440715-77709080-b392-4039-9bd9-7f7d3f1a5e70.png)

**Comment by RomanDvorsky** [comment]
Hi,

the version 1.94.0 did fix the issue however there is still one little thing. See attached image - the numbers shown in the overview are total cluster numbers not the team overview numbers...

![image](https://user-images.githubusercontent.com/36188474/172647507-562498bb-a1a5-4055-b4d6-1ebe6327de36.png)

**Comment by AdamStack18** [comment]
@RomanDvorsky Thanks for calling this out. @biancaburtoiu, Could you look into this?

**Comment by biancaburtoiu** [comment]
@AdamStack18 was able to reproduce, will have to reopen this as this is indeed not the expected behaviour. cc @wolfeaustin
