### ISSUE TITLE
UI/UX for Collecting Data message on new deployments

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1405]
**What problem are you trying to solve?**
When deploying kubecost the UI says something to the extent of "Kubecost is collecting data. Check back in 5 minutes." When using the federated architecture this is more like 3 hours due to the delay of Thanos shipping chunks to object storage.

**Describe the solution you'd like**
Would like to see the collecting data message reflect that it could take up to 'n' hours if federating data from multiple clusters.

**Describe alternatives you've considered**
None.

**How would users interact with this feature?**
Passively.

**Comment by dwbrown2** [comment]
Thanks, Sean!

@teevans and I just discussed this clean install experience yesterday. Let's review for 1.94 if that sounds good!

**Comment by teevans** [comment]
This has made it into the 1.94 release as part of the overview page upgrades.
