### ISSUE TITLE
Provide an option to display label value only in graphs

### ISSUE THREAD

**Issue by ivankube** [kubecost/cost-analyzer-helm-chart#1407]
**What problem are you trying to solve?**
Currently both label key and values is displayed. When key is long, value is not visible.

**Describe the solution you'd like**
Provide an option to display label values only. 

**Describe alternatives you've considered**
Change graphs labels from diagonal to horizontal or vertical. 

**How would users interact with this feature?**
Users will have an option of displaying both labels' keys and values or only labels values.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-94) by [Unito](https://www.unito.io)

**Comment by michaelmdresser** [comment]
Here's a visual example:

<img width="527" alt="image" src="https://user-images.githubusercontent.com/17585786/167132682-1d11712c-6e63-4185-832d-f0008b3f824e.png">

The highlighted `app=` string is what this feature request wants to be able to toggle. Note how it makes it more difficult to read longer strings on the graph, like `app=cost-anal...` because they get truncated.

**Comment by dwbrown2** [comment]
The full value is shown on hover though right... does that not help a lot in this situation?

Really long strong will still be truncated no matter what we do here..

**Comment by ivankube** [comment]
Response from the user: "Indeed there is a "hovering" function available but it requires you to go through all the graph columns to find the one you are after"

More infö with label examples in ticket #1768.

**Comment by AdamStack18** [comment]
I've seen this challenge solved by adding a color key. There could be a toggle to hide it or reveal it.

![Dashboards-Charts-From-Reports-Chart](https://user-images.githubusercontent.com/102822297/167953826-ec6fa28e-c94d-4255-88f9-9c0e0f78a568.jpeg)
![drill-down-by](https://user-images.githubusercontent.com/102822297/167953836-34fae989-9919-41ce-84a3-504ced388889.png)
.
