### ISSUE TITLE
Allow wildcards in Budget alert filters

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#1410]
**What problem are you trying to solve?**
When configuring a "budget alert" using a wildcard `*` in the filter no alerts are sent (Note that test alerts are sent). Wildcards are documented as working for "Recurring" alert filters so this change will bring consistency to alert configuration. The following example screen shot shows a scenario where the namespace filter is set to `kube*` with the expected result to send alerts for the "kube-system" and "kubecost" namespaces.

![](https://user-images.githubusercontent.com/17748044/167193077-9fe1273f-3234-40c3-8ce4-323b679aaec2.png)

**Describe the solution you'd like**
Allow wildcards `*` in filters when configuring budget alerts.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-95) by [Unito](https://www.unito.io)

**Comment by mbolt35** [comment]
Just wanted to provide an update. It took me a bit of time to track down exactly what was going on here: Our `filter` property does support a single `*` character to represent "all," but as for actual prefix/suffix wildcards, this isn't currently supported. We do currently support a comma delimited list. ie: `kubecost,kube-system,kube-configuration`

This is definitely something we can look into supporting.
