### ISSUE TITLE
Grafana Sidecar generating many log entires due to missing value

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1412]
**Describe the bug**
When enabling the datasources feature of the Grafana sidecar, the logs fill up with an invalid literal error.

**To Reproduce**
1. Enable the datasources feature of the Grafana Sidecar: https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L666
2. Observe logs

**Expected behavior**
SIdecar should run without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/15660532/167440468-f562dd18-6b1b-45ec-ace6-886bd884e081.png)

**Collect logs (please complete the following information):**
v1.92

![image](https://user-images.githubusercontent.com/15660532/167440720-220925d8-a5b3-454c-9643-9dd718f90477.png)

**Comment by AdamStack18** [comment]
@srpomeroy  Can this issue be closed? Or are additional PRs needed? 

PR #1413

**Comment by srpomeroy** [comment]
We're good @AdamStack18 !
