### ISSUE TITLE
Support a single AWS AMP for Primary and Secondary Kubecost

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#1420]
**What problem are you trying to solve?**
There is an interest in using a single AWS AMP (Amazon Managed Service for Prometheus) to replace Prometheus on Primary and Secondary (or multiple secondaries) kubecosts in a federated install. From what I understand this will require limiting the Prom queries to the relevant cluster. It will also require updates to the [documentation](https://guide.kubecost.com/hc/en-us/articles/4409859798679-Amazon-Managed-Service-for-Prometheus).

**Describe the solution you'd like**
Support a single AMP from multiple secondaries.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-96) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
Can you share the detailed use case and/or reason why this is important?

**Comment by AjayTripathy** [comment]
From a maintenance perspective, it's not ideal to maintain a bunch of prometheuses _and_ AMP. This is probably the fastest approach for doing that, but perhaps an alternative we should consider is that _no_ secondary clusters require a database, instead scraping and maintaining a buffer of OpenTelemetry data from the kubelets themselves. That's probably a significantly larger project, though.

**Comment by dontmint** [comment]
In my case, I use 1 single Prometheus server for 10 clusters. This reduces the cost of our infrastructure and makes it easy to maintain for us. I think this is doable, we just need to have 1 more option to customize queries to match the customized metrics. This will help Kubecost fit into more environments.

**Comment by dwbrown2** [comment]
@dontmint can you share more about the "customized metrics"? Is this just you have a custom field for `cluster_id` if so this  should already be support. Disclaimer: I do believe the version of multi-cluster is on a paid Kubecost plan though.

**Comment by dontmint** [comment]
Hi @dwbrown2 , thank you for your reply.

I use this [GPU share scheduler](https://github.com/AliyunContainerService/gpushare-scheduler-extender) to deploy apps that use a fraction of GPU. This tool doesn't have metrics like [Cadvisor](https://github.com/google/cadvisor) or [DCGM exporter](https://github.com/NVIDIA/dcgm-exporter). So I have to write my own metrics, these are only for internal use but I can show you some of them below:

```
# HELP aliyun_com_gpushare_memory_allocated How much memory was allocated for a pod, memory unit .
# TYPE aliyun_com_gpushare_memory_allocated gauge
aliyun_com_gpushare_memory_allocated{gpu_device_id="GPU 0",kubernetes_node_ip="127.0.0.1",kubernetes_node_name="localhost",kubernetes_pod_name="pod_name",kubernetes_pod_namespace="namespace"} 2
```

Therefore, a lot of resources were excluded in the Kubecost report page and I don't know how to modify the default query for GPU like this.

**Comment by dontmint** [comment]
> 

Yes, It was scraped manually in an external Prometheus instance, then I config Kubecost to query from that instance and followed this [document](https://guide.kubecost.com/hc/en-us/articles/4407595941015-Custom-Prometheus) as well.

**Comment by AjayTripathy** [comment]
We don't today support pulling custom metrics into our ui but it's an interesting thought. Could you possibly rewrite the names of your internal gpu collector to match how kubecost collects gpu metrics?
