### ISSUE TITLE
Business Tier Warning shows 15 days instead of 30

### ISSUE THREAD

**Issue by sellers** [kubecost/cost-analyzer-helm-chart#1424]
**Describe the bug**
Version 1.91 did not warn you when you went beyond 30 days (and would often show more than 30 days) 
Version 1.93 shows a warning, but says the data is beyond 15 days and is not available but I believe it should say 30 days as business allows for more than 15 days worth of data.   This is likely related to a recent enhancement. 

**To Reproduce**
1. Go to any report
2. Click on 'Date Range'
3. See error that states 15 days instead of the limit based on your tier

**Expected behavior**
That the warning would show what limits are in place for your license versus the generic free version limit 

**Screenshots**
Version 1.91  90 days
<img width="1362" alt="Screen Shot 2022-05-16 at 2 06 32 PM" src="https://user-images.githubusercontent.com/6163830/168664724-4e2412fa-178a-4c31-9584-6b5a34d96246.png">

Version 1.93 90 days
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/6163830/168665048-70876273-16b2-4af4-927d-61cc5c4dc0f1.png">

Tier
<img width="166" alt="image" src="https://user-images.githubusercontent.com/6163830/168665131-3bfc46d4-6761-4a87-8372-c2ef13c4a8b9.png">

gz#1820<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1820'>Zendesk ticket #1820</a>)</i>

**Comment by sellers** [comment]
See also issue #1368

**Comment by keithhand** [comment]
Thanks for pointing this out to us! Cc @teevans so that we can dig into this.

**Comment by teevans** [comment]
@nealormsbee would you want to pick this up?

**Comment by nealormsbee** [comment]
Yep, should be a quick adjustment. Self-assigning.

**Comment by nealormsbee** [comment]
Just checking @sellers:

On business tier, you can still query between 15 and 30 days of data without issue, right? The issue is that when you exceed 30 days, the warning shown says "15 days", which is inaccurate.
