### ISSUE TITLE
Helm upgrade fails with Kubernetes v1.22

### ISSUE THREAD

**Issue by sg09** [kubecost/cost-analyzer-helm-chart#1425]
When trying to install cluster controller with EKS 1.22 (v1.22.6-eks-7d68063), helm upgrade fails with the below error

`helm upgrade kubecost kubecost/cost-analyzer --namespace kubecost  --set clusterController.enabled=true
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"`

Already Kubecost is running in EKS with helm chart..  Followed this link, https://guide.kubecost.com/hc/en-us/articles/4407595938327, created secret and during the next step to deploy, getting the above error. Help suggest how can I do this with the existing setup up and running?

gz#1824<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1824'>Zendesk ticket #1824</a>)</i>

**Comment by AjayTripathy** [comment]
Looks like this has moved to apiextensions.k8s.io/v1 so our chart needs an upgrade to successfully install the cluster controller for automated turndown.

**Comment by AjayTripathy** [comment]
Assigning to @wolfeaustin the support eng on rotation

**Comment by sg09** [comment]
Appreciate any interim solutions till the fix is in place to unblock us

**Comment by AjayTripathy** [comment]
Hi @sg09 you could just clone "master" of cost-analyzer-helm-chart and replace this line: https://github.com/kubecost/cost-analyzer-helm-chart/blob/d72ca06f3b58fedaf6505ce05f7bbe3197768efb/cost-analyzer/templates/kubecost-cluster-controller-template.yaml#L250 with ` apiextensions.k8s.io/v1` or deploy the helm chart without .Values.clusterController.enabled .

**Comment by dwbrown2** [comment]
@mbolt35 potential quick fix next week?

**Comment by AjayTripathy** [comment]
Think Austin (support rotation) should have a PR soon!

**Comment by michaelmdresser** [comment]
@wolfeaustin is this issue resolved, now that #1429 is merged?

**Comment by wolfeaustin** [comment]
@michaelmdresser yep! I'll go ahead and close.
