### ISSUE TITLE
1.93.1 - 'Aggregate By' section - Duplicate labels allowed / Handling of capitals in labels  

### ISSUE THREAD

**Issue by kc-adawson** [kubecost/cost-analyzer-helm-chart#1434]
**Describe the bug**

here's what I have found in 1.93. I have an active label on my workloads - "app" with a lower case A.

1. If I add just plain "app" to my +Label field on the "Aggregate By" tab, it works fine.

2.  If you add a tag with a capital letter (eg "App"), it gets added to the "Aggregate By" section showing as lower case, but it does not show any lower case "app" labels within the report.

3. The "Aggregate By" UI allows you to add multiple duplicates of the same labels (in this case I added multiple lower case "app" labels). When you click on one, it turns them all on and off at the same time.

**To Reproduce**
1. Go to 'Cost Allocation -> Click on the "Aggregate By" modal. 
2. Type in "app" (lower case) into the +Label field
3. Verify it works
4. Add another +Label for "App" - (capital A)
5. It shows up in the modal as a lowercase "app" but does not show any data.
6. Add another +Label "app"
7. The platform creates a duplicate of the label and turns all duplicates on/off in unison

**Expected behavior**

I would expect that adding +Label "app" and +Label "App" should show with their proper capitalizations. I also would expect that exact duplicates ("app" and "app") would be blocked.

It would be good if users could combine multiple filters - If I wanted to add "app", present a checkbox to include any capitalization (App, APP, apP, etc). Maybe this could be something that could be set proactively in the Settings / Label section under a custom label grouping

**Screenshots**

https://user-images.githubusercontent.com/101200254/169887965-88ba7e48-b96d-4097-a784-d914fda3a32d.mp4

**Comment by dwbrown2** [comment]
Great catch and detailed report! I was able to repro on my end. 

cc @AdamStack18 @teevans
