### ISSUE TITLE
Add drill down options for Advanced Reporting

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1435]
**What problem are you trying to solve?**
Previously, you could drill down categories like external costs with a link from the cost allocation page. With the move of external costs to Advanced reporting, this is no longer an option.

**Describe the solution you'd like**
A similar "drill down" option from the allocation reports on the advanced reporting screen.

**How would users interact with this feature?**
![image](https://user-images.githubusercontent.com/43491549/170084691-b02cd733-f912-49d7-b0b2-c973687a72d8.png)

gz#1848<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1848'>Zendesk ticket #1848</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-98) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
@keithhand we do now have the ability to aggregate external cost by any dimension in Advanced Reports, e.g. service, account, provider, etc. Anything you feel is missing there?

**Comment by dwbrown2** [comment]
@wolfeaustin and I discussed yesterday! Investigating now, thanks again for sharing.

**Comment by AdamStack18** [comment]
@teevans @wolfeaustin 
 
In the sprint meeting it was discussed having Austin pick up some Advanced report’ enhancement items. Is this a good candidate?  If not, could you assign a priority to help prioritize future report work?
 
1. Must Do
2. Nice to have 
3. Filler work
