### ISSUE TITLE
Advanced reporting "Data Source Grouping" doesn't appear to work properly

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1440]
**Describe the bug**
Unexpected results happen when using the new advanced reporting feature and customizing the "Asset Label" field in the Data Source Grouping section. For instance, if you already have a team aggregation based on `label:kubernetes_label_team`, that will work fine. But when you update this value to a different value and then reset it to the original `label:kubernetes_label_team`, the table will no longer show the mapped results. It also appears to affect if you have labels set (for instance, a label of `team` within your AWS CUR) and try to map the values based on this custom value, as nothing gets mapped.

**To Reproduce**
1. Create an advanced report
2. Customize the field `Asset Label`
3. Don't get the results expected

**Expected behavior**
Label mappings based on custom options within the advanced report work as expected.

gz#1848<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1848'>Zendesk ticket #1848</a>)</i>

**Comment by dwbrown2** [comment]
Thanks for the detailed report, @keithhand!

@wolfeaustin want to review and touch base on current Advanced Reports work tomorrow?

**Comment by wolfeaustin** [comment]
@dwbrown2 that sounds great!

**Comment by AdamStack18** [comment]
@wolfeaustin @dwbrown2  Did any action items come out of your meeting?  This was flagged as an important customer issue.  Adding to bug list for work in v1.95.
