### ISSUE TITLE
Prometheus/Thanos upgrade in

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#1443]
**What problem are you trying to solve?**
Upgrade prometheus and thanos in the base chart. 

**Describe the solution you'd like**
Prometheus and thanos move to the latest stable versions

**Describe alternatives you've considered**
We have to keep up with upgrades, no alternatives. We could wait for the RC but stable versions are preferred

**How would users interact with this feature?**
No impact

**Comment by dwbrown2** [comment]
cc @AdamStack18

**Comment by dramich** [comment]
This should also include the dependencies like `node-exporter`, the current version we are using was released on `Jun 4, 2019`

**Comment by Adam-Stack-PM** [comment]
@AjayTripathy Would you like to push tomorrow to get this into v1.95 or should we roll it into v1.96?

**Comment by sundeepghuman** [comment]
Ajay and are meeting tomorrow morning to go over this bug and plan to
submit it before EOD.

**Comment by sundeepghuman** [comment]
Skipping Thanos upgrade as later versions are relatively new, and no current known security vulnerabilities: https://github.com/kubecost/integration-ci-cd/runs/7147125236

**Comment by sundeepghuman** [comment]
Choosing Prometheus version v.2.35.0 as it picks up go v1.18 and known vulnerabilities are related to go binary

https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md#2350--2022-04-21
nightly scan results: https://github.com/kubecost/integration-ci-cd/runs/7147125058

**Comment by sundeepghuman** [comment]
> This should also include the dependencies like `node-exporter`, the current version we are using was released on `Jun 4, 2019`

@dramich Node exporter is showing no known vulnerabilities: https://github.com/kubecost/integration-ci-cd/runs/7147124874

Will file separate ticket to address update in subsequent release.

**Comment by dwbrown2** [comment]
@sundeepghuman these are always tricky upgrades IMO. historically, it's been fairly straightforward to test for 90% of cases but long-tail has been hard for us.

**Comment by dramich** [comment]
I agree with @dwbrown2 . I think doing this piecemeal is also going to cause issues, despite us having our own charts we should be following upstream with what versions are being packaged together so we know they have been tested together and don't accidentally walk into a breaking change.

**Comment by AjayTripathy** [comment]
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L503 Looks like the community chart is running that version for node-exporter. Maybe let's try that one?

**Comment by AjayTripathy** [comment]
We can test carefully as well, but none of the 0.X.X changes to 1.X.X Breaking Changes should affect us:
```
The netdev collector CLI argument --collector.netdev.ignored-devices was renamed to --collector.netdev.device-blacklist in order to conform with the systemd collector. https://github.com/prometheus/node_exporter/pull/1279
    The label named state on node_systemd_service_restart_total metrics was changed to name to better describe the metric. https://github.com/prometheus/node_exporter/pull/1393
    Refactoring of the mdadm collector changes several metrics
        node_md_disks_active is removed
        node_md_disks now has a state label for "failed", "spare", "active" disks.
        node_md_is_active is replaced by node_md_state with a state set of "active", "inactive", "recovering", "resync".
    Additional label mountaddr added to NFS device metrics to distinguish mounts from the same URL, but different IP addresses. https://github.com/prometheus/node_exporter/pull/1417
    Metrics node_cpu_scaling_frequency_min_hrts and node_cpu_scaling_frequency_max_hrts of the cpufreq collector were renamed to node_cpu_scaling_frequency_min_hertz and node_cpu_scaling_frequency_max_hertz. https://github.com/prometheus/node_exporter/issues/1510
    Collectors that are enabled, but are unable to find data to collect, now return 0 for node_scrape_collector_success.
    ```

**Comment by sundeepghuman** [comment]
@dramich will include in the same PR for this release.
