### ISSUE TITLE
Add ability to define usage calculation method for rightsizing recommendations

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1451]
**What problem are you trying to solve?**
Workload rightsizing uses an average over the defined window, which doesn't account for workloads which tend to spike.

**Describe the solution you'd like**
The ability to define methods other than average, such as "max" or "P95" or "Px"

**Describe alternatives you've considered**
Using the API to define tighter windows so average reflects more of the spike.

**How would users interact with this feature?**
Via the UI or the API with an additional setting. (API setting would be optional, where default method is still average to preserve backwards compatibility)

**Comment by kirbsauce** [comment]
Well, that certainly is there in black and white.  Sorry for the churn and I'll propagate this to others to avoid further confusion.  Closing...

**Comment by dwbrown2** [comment]
No problem, let me know if that's more we can do in product. 

Also, we are looking at a custom profile option!
