### ISSUE TITLE
savings report for clusters missing from kubecost (unmanaged)

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#1452]
**What problem are you trying to solve?**

A potential savings report: allow users to see which clusters are running in the cloud providers, but are not being monitored by kubecost.

**Describe the solution you'd like**

-total savings card: based on industry averages and total assuming these are all abandoned clusters?
-list of clusters with cost per month with related details: days not in kubecost, (is it possible to find who created it?), region, node count, tags
-graph of cost over time of unmanaged clusters
-ability to create an alert based on unmanaged clusters for x days

**Describe alternatives you've considered**

N/A

**How would users interact with this feature?**

-savings card
-alerts

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-99) by [Unito](https://www.unito.io)

**Comment by srpomeroy** [comment]
Would be nice to include what AWS Account, Azure Subscription, GCP Project the cluster is running in.
And potentially what cloud tags are attached to it to help identify the responsible party.

**Comment by teevans** [comment]
I think this could be the tip of the iceberg for this type of functionality. I could see us implementing something in the future that would allow them to click on a cluster and select "Add to Kubecost" - Foods for thought.

**Comment by AjayTripathy** [comment]
That would be a dramatic departure from our permissions model but may be possible with the right permissions!

**Comment by jessegoodier** [comment]
@Adam-Stack-PM 
There's still a ton of value in this one, just bumping this up for visibility.

**Comment by AjayTripathy** [comment]
Agree, this should be rolled into an "unmonitored clusters tracking" feature.

**Comment by jessegoodier** [comment]
added in 1.102
