### ISSUE TITLE
Send links to reports or images of reports instead of just text information

### ISSUE THREAD

**Issue by artemlive** [kubecost/cost-analyzer-helm-chart#1460]
**What problem are you trying to solve?**
It's inconvenient to get Kubecost's reports in text format only. It would be great if there was a way to send a preview of the report with a link to the actual report. 

**Describe the solution you'd like**
It would be great if Kubecost could send the report preview like an image with the link to the actual report.

For example, CloudHealth has such a feature. They send you a report preview with a link to the actual report. 
![](https://user-images.githubusercontent.com/3328394/172137163-3be5e2d1-4eb8-483f-821f-333a38e0dd23.png)

It's much more convenient to see the picture of the report instead of the text information only. Sometimes you don't even need to go to UI to recognize that there is a problem with costs if you have such kind of preview. 

gz#1917<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1917'>Zendesk ticket #1917</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-100) by [Unito](https://www.unito.io)

**Comment by artemlive** [comment]
Hey @keithhand. Yes, you are right, that's what we need 👍

**Comment by AdamStack18** [comment]
@wolfeaustin @teevans Great feedback here for Advanced Reports.

**Comment by dwbrown2** [comment]
@artemlive you should be able to accomplish this today with recurring reports + a linkback url:

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/298359/172757085-4b3384ce-cb67-4057-be79-ceaa729e03a4.png">

We'll be adding more here soon so would love to hear your feedback!

**Comment by mmurph3** [comment]
Why does the customer need this? (List the business requirements here)
This is a handy feature for increasing observability. For example, we can configure daily reports sent to leads of different teams with the related resources, and they can observe their cost usage without directly interacting with Kubecost. It is much better than current Kubecost's reporting system. It only sends the text data without graphs, and you can't track your daily cost usage. If there is a spike in cost usage, you can observe it on charts and find out what kind of service began to consume costs.

**Comment by dwbrown2** [comment]
Exploring this now for 1.99 release! cc @teevans

**Comment by mmurph3** [comment]
@teevans @kwombach12 any updates here on if/when we can get graphs in addition to the tables in our pdf's when exporting alerts/reporting  via email, web hook, etc?

**Comment by kwombach12** [comment]
@mmurph3 this is something thats definitely in our roadmap! It hasn't been assigned to a specific release yet, but it is certainly on our radar
