### ISSUE TITLE
Add the ability to see the actual report while alert testing

### ISSUE THREAD

**Issue by artemlive** [kubecost/cost-analyzer-helm-chart#1461]
**What problem are you trying to solve?**
I was trying to debug the recurring report on the alert page and I was surprised that there was no way to send the 
actual report for test/debug approaches. 
<img width="1526" alt="Screenshot 2022-06-06 at 10 55 07" src="https://user-images.githubusercontent.com/3328394/172129710-63c2918b-3918-449e-80df-e5f72817db78.png">
When I press the test button it sends me only the message with the report parameters:
> "This is a test message from a Kubecost alert with the following properties:
> 	Type: recurringUpdate
> 	Window: 7d
> 	Aggregation: namespace
> 	Filter: *"

I waited a week and Kubecost sent me a message with a report and then I was surprised again because the formatting has been broken.

> [Kubecost Weekly Update]
> Below is the Kubecost weekly summary for your cumulative spend by Namespace. The summary is from 2022-05-30 to 2022-06-06. Visit your installation of the Kubecost [app](https://kubecost.example/allocations.html) to learn more.
>  Clustername: devops
>  Cost and Efficiency by Namespace
> \`\`\`    namepsace-a                                  $0.29     1%
>     __unmounted__                              $0.01     0%
>     namespace-b                          $0.34     2%
>     namespace-c                                   $0.63     2%
>     namespace-d                    $0.00     0%
>     namespace-X                       $3.39     4%

I guess it had to be within a code block \`\`\` but it sent me the actual \`\`\` symbols and I couldn't get it before I got the actual report. 
So now I have to wait one more week to take a look at the new version of the report. 

**Describe the solution you'd like**
It would be great if there was a button to send the actual report instead of just test message with the report's parameters. 

gz#1918<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1918'>Zendesk ticket #1918</a>)</i>

**Comment by dwbrown2** [comment]
+1, this is definitely something we want to support! We'll aim to include an update in our next release.

**Comment by Adam-Stack-PM** [comment]
Closing. I believe this is solved by attaching PDFs to the recurring reports in v1.99. 

@dwbrown2, Please re-open if you would like to take this further. Could see value in giving users the option to attach a PDF or a CSV down the road.
