### ISSUE TITLE
Add Kubecost PVC metrics to Diagnostics Page

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1472]
**What problem are you trying to solve?**
It would be useful to have a warning appear if the PVC with backing ETL data (`pvc/kubecost-cost-analyzer`) is approaching its storage capacity. 

**Describe the solution you'd like**
A way within the application to notice if the storage is approaching its capacity 

**Describe alternatives you've considered**
Exec into the pod manually to check the disk status

**How would users interact with this feature?**
Status on /diagnostics.html and a possible error on the home page if the storage is approaching its capacity.
![image](https://user-images.githubusercontent.com/43491549/172957563-cbf2a247-ba79-40be-a161-53f383301e1a.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-102) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
Totally agree, if I remember correctly cadvisor dropped this metric and the kubelet now exposes. We'd likely would need to ingest an entirely new data source. 

cc @AjayTripathy

**Comment by AjayTripathy** [comment]
Why not just poll our own filesystem and emit the metric ourself? That seems like a way simpler approach and more accurate than cadvisor, yeah?

**Comment by dwbrown2** [comment]
That sounds good to me if no concerns on your side, even if 1.96. 

Can we get all PVC usage metrics though? Have others will be valuable too.

**Comment by AjayTripathy** [comment]
That feels much harder, let's not scope creep this.

**Comment by AdamStack18** [comment]
@AjayTripathy, Who is the right person to work on this? 

Down the road could be a good candidate to add to our notification event list.

**Comment by DKeeling01** [comment]
Hello all - 

Just checking in to get a status update on this issue - customer is asking for a timeline

**Comment by AjayTripathy** [comment]
This depends on #1713 once that lands we should be in good shape to look at this in v1.99 (our post-kubecon release)

**Comment by wamak9** [comment]
@AjayTripathy , @keithhand , @DKeeling01, @Adam-Stack-PM   -- can we visiting this?
v1.99 did release and I don't think this got enough traction.

**Comment by teevans** [comment]
@nikovacevic @nealormsbee  - Perhaps another small win?

**Comment by nealormsbee** [comment]
Appears to be! Adding a note to the diagnostics page is super easy. I imagine the endpoint for this would be as well.

Putting this in the Frontend-Team project so it doesn't fall off my radar.

**Comment by MrJW27** [comment]
Hi @nealormsbee was this completed by the frontend team?

**Comment by wamak9** [comment]
is this till on track for v1.101 ?
@dwbrown2 @Adam-Stack-PM

**Comment by Adam-Stack-PM** [comment]
@wamak9 , Thanks for the ping on this item.  @kwombach12 could you jump in here as you have the most roadmap context.

**Comment by nealormsbee** [comment]
>Hi @nealormsbee was this completed by the frontend team?

@MrJW27 it was not. I think we'll still need to write both the API endpoint and the UI for surfacing the notification.

**Comment by teevans** [comment]
@nealormsbee - Are we tracking this one in Jira?

**Comment by teevans** [comment]
@wamak9 - We've opened the first PR on this issue today - We should be able to get this into the next release!

**Comment by nikovacevic** [comment]
This should be closed after the front end work goes in.
