### ISSUE TITLE
Add color indicators to efficiency card on overview screen

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1477]
**What problem are you trying to solve?**
The green text for Efficiency percentage on the overview page can be confusing.
![image](https://user-images.githubusercontent.com/15660532/173400267-5088099b-3b9b-438d-b99f-20989ebeea78.png)

**Describe the solution you'd like**
Would be great if the color of the value changed in accordance with some thresholds.
For example:
0-40% = red
41-65% = yellow
66% - 85% = green
85%+ = yellow

**Describe alternatives you've considered**
none

**How would users interact with this feature?**
Thresholds defined in settings.html

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-105) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
I think what we had before (very similar to this) worked pretty well! Is newer version static / always green?

I would vote we make it dynamic but wait on bring this configuration to settings for a potential part 2.
