### ISSUE TITLE
Add trend indictors to overview cards

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1478]
**What problem are you trying to solve?**
Quick visual indicator to identify trends with high-level cost data

**Describe the solution you'd like**
Would like to see something like a simple arrow and maybe percentage indicator of change from the previous window to the current
![image](https://user-images.githubusercontent.com/15660532/173400690-78f608e4-77dd-46ec-b274-5cffca390723.png)

**Describe alternatives you've considered**
None

**How would users interact with this feature?**
Visual indicator on overview cards

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-106) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
A big +1 here, I might even propose going further and present something like:

<img width="295" alt="image" src="https://user-images.githubusercontent.com/298359/173483335-ac364100-61ab-4925-9171-d212011ea1d3.png">

Thoughts on the frontend @teevans?

I'm guessing this would have a much bigger impact on the backend, thoughts @AjayTripathy?

**Comment by teevans** [comment]
I'm all about it - if we pull in previous window data from the Frontend we effectively double our memory overhead on those set of requests though. I'd be curious if there would be a good way for us to query this on the backend.

**Comment by Adam-Stack-PM** [comment]
@jjarrett21, Are you aiming to get this into v1.96?

**Comment by dwbrown2** [comment]
@jjarrett21 have the APIs you need or anything we can help you with?
