### ISSUE TITLE
Allow users to create the service account

### ISSUE THREAD

**Issue by gopisaba** [kubecost/cost-analyzer-helm-chart#148]
**What problem are you trying to solve?**
The kubecost need s3 access to read the spot data feed. 
I can't use the [EKS IAM service account mapping](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) to get s3 access instead I have to give s3 access to all the worker nodes. The downside is, all the pods running on the nodes will have access to the s3 bucket.

**Describe the solution you'd like**
Allow user to create their own service account with right IAM Role ARN annotations to get s3 access. 

**Describe alternatives you've considered**
Give s3 access to all the worker nodes

**How would users interact with this feature?**

I already raised a [PR](https://github.com/kubecost/cost-analyzer-helm-chart/pull/145) for this

**Comment by dwbrown2** [comment]
Closing now that PR has been merged, let me know if there is more to do here though. Thanks again for this contribution!
