### ISSUE TITLE
add variable for scrape_timeout in prom servicemonitor

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#1482]
**What problem are you trying to solve?**

Customer request to add a helm variable for scrape_timeout in prom servicemonitor:
https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.94.3/cost-analyzer/templates/cost-analyzer-servicemonitor-template.yaml#L17

**Describe the solution you'd like**

Simple value for setting scrape timeout via helm

**Describe alternatives you've considered**

Prometheus was timing out on kubecost_container_cpu_usage_irate 
adjusting the scape_timeout manually solved the issue.

**How would users interact with this feature?**

add something like:
.Values.serviceMonitor.scape_timeout
to that line

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-107) by [Unito](https://www.unito.io)

**Comment by Pluggi** [comment]
Having a value for `interval` would also be nice to have.
