### ISSUE TITLE
cost analyzer gradually eat up memory

### ISSUE THREAD

**Issue by peijianju-sonrai** [kubecost/cost-analyzer-helm-chart#1483]
**Describe the bug**

Dear kubecost,

`kubecost-cost-analyzer` pod is crashlooping due to OOM in our cluster.  We have bumped the `cost model` memory limit 3 times this month. From 5G to 8G, then to 10G, now it is 13G. 

Is there is way that we can trace/diagnose what is eating so many memory?

**To Reproduce**
N/A

**Expected behavior**
We expect the the memory consumption is steady or less frequently bumping requirement. 

**Screenshots**
N/A

**Collect logs (please complete the following information):**

 - Run `helm ls` and paste the output here:
```
❯ helm ls
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART               	APP VERSION
kubecost	kubecost 	29      	2022-06-13 17:18:21.790499035 +0000 UTC	deployed	cost-analyzer-1.91.2	1.91.2
```

 - If the pod is stuck in init, run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-init` and paste output here:
N/A

 - If a page is broken or not loading, open your javascript developer console and paste the ouput here:
N/A

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-server` and paste the output here:
N/A

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-model` and paste the output here:
We lost the logs since we bump the memory and the pod is now running. I will upload the log when the crashlooping happens again

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-frontend` and paste the output here:
N/A

gz#1983<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1983'>Zendesk ticket #1983</a>)</i>

**Comment by jcharcalla** [comment]
@peijianju-sonrai Thank you for reporting this.

What version of Kubecost are you currently running? Additionally how many node/pods are in your cluster and are you integrating with a cloud provider for external costs?

**Comment by peijianju-sonrai** [comment]
@jcharcalla thank you for the responses.

Our kubecost image is at `gcr.io/kubecost1/cost-model:prod-1.91.2` 
As right now, we have 32 worker nodes, we are using AWS EKS serivce, so it may auto scale as needed.

And thank you for the guide, we will try to upgrade and see if that works. Thank you

**Comment by jcharcalla** [comment]
@peijianju-sonrai Were you able to reduce the memory consumption after upgrading and reviewing the guide?

**Comment by peijianju-sonrai** [comment]
Hi @jcharcalla , thank you for the feedback, it looks good for now. We will still observe it for a while. Please feel free to close this ticket. thanks again

**Comment by jcharcalla** [comment]
Thank you for the update! Marking this as closed now.

**Comment by lesh366** [comment]
Hey @jcharcalla 
I think it's still being reproduced...
we are running on eks and using version 1.105.1 

![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/26593417/fff9ced6-df27-4cbc-b444-21e24dcf84b8)
