### ISSUE TITLE
Pricing Endpoint is set statically

### ISSUE THREAD

**Issue by Marmalade2** [kubecost/cost-analyzer-helm-chart#1484]
**What problem are you trying to solve?**

Currently, I have confirmed that kubecost works normally with the default helm chart in the closed network, but it is difficult to calculate the exact cost because the price policy of each node is applied differently by region.
I think it would be better to set the value dynamically than to set it statically within the code.
I know that some complicated requirements are charged, but I hope that this kind of setting can be modified to be set even in the free tier.

**Describe the solution you'd like**

When use kubecost in a closed network, I hope can modify the endpoint so that you can synchronize the cloud pricing data.

**Describe alternatives you've considered**

I would like to set the currently statically set endpoint value as the default value and control it through environment variables.

**How would users interact with this feature?**
Users will be able to set the value by changing the chart values or k8s spec.

gz#1989<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1989'>Zendesk ticket #1989</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-108) by [Unito](https://www.unito.io)

**Comment by jcharcalla** [comment]
@Marmalade2 Thank you for your feature request. Can you tell me which Cloud provider you are using?

**Comment by Marmalade2** [comment]
@jcharcalla Thanks for reply. I use AWS, but it seems another cloud provider(ex. azure, GCP) is also configured statically.
