### ISSUE TITLE
Network Costs detected as disabled in details.html

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1485]
**Describe the bug**
Network Costs is enabled. The daemon set is running properly and I see network costs in cost allocation but when I view the details.html page for a resource that has network costs, the network costs card says "Network Traffic allocation not configured."

**To Reproduce**
1. Deploy Kubecost with network costs enabled
2. In UI, under Cost Allocation, aggregate by Namespace
3. Click on the details link for a specific namespace
4. Observe the network cost widget

If I inspect the browser console, I see the following call returns no data: `sort_desc(sum(increase(kubecost_pod_network_egress_bytes_total{service!="", namespace="${resourceName}"}[7d])) by (service))`

If I modify the query and remove the `service!=""` filter, I get data back.

**Expected behavior**
See metrics for network costs.

**Screenshots**
<img width="446" alt="image" src="https://user-images.githubusercontent.com/15660532/173722002-1311595c-a095-4c58-b725-4fd4bf1fa99c.png">

**Collect logs (please complete the following information):**

 - Run `helm ls` and paste the output here:
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART               	APP VERSION
kubecost	kubecost 	12      	2022-06-13 17:32:35.433585985 +0000 UTC	deployed	cost-analyzer-1.94.2	1.94.2

 - If a page is broken or not loading, open your javascript developer console and paste the ouput here:
The following call returns 0 results: `query=sort_desc(sum(increase(kubecost_pod_network_egress_bytes_total%7Bservice!=%22%22,%20namespace=%22kubecost%22%7D%5B7d%5D))%20by%20(service))%20`
Response: {"status":"success","data":{"resultType":"vector","result":[]}}

But this one returns something: `query=avg(kubecost_network_internet_egress_cost)`
Response: {"status":"success","data":{"resultType":"vector","result":[{"metric":{},"value":[1655259724,"0.12"]}]}}

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-model` and paste the output here:
2022-06-15T02:22:04.178192473Z INF http: named cookie not present
2022-06-15T02:22:04.178229096Z INF [JWT Groups] No Cookie set
2022-06-15T02:22:04.179029592Z INF ETL: QuerySummaryAllocation([2022-06-14T22:22:04+0000, 2022-06-15T02:22:04+0000), [namespace]) from AggregatedStore[1h] 753.08µs [query 473.689µs] [idle/tenancy 28.347µs] [external 1.079µs] [aggregate 249.417µs] [accumulate 326ns] [stop 222ns]
2022-06-15T02:22:04.222940414Z INF ETL: Asset: QueryAsset([2022-06-08T02:22:04+0000, 2022-06-15T02:22:04+0000), [service]) from ETLStore[1d] 43.843963ms [query 916.875µs] [cloud 32.648748ms] [aggregate 9.929556ms] [accumulate 348.553µs] [stop 231ns]
2022-06-15T02:22:04.263746413Z INF http: named cookie not present
2022-06-15T02:22:04.263785143Z INF [JWT Groups] No Cookie set
 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-frontend` and paste the output here:
192.168.13.201 - - [15/Jun/2022:02:22:03 +0000] "GET /details.html?name=kubecost&type=namespace HTTP/1.1" 200 385 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/allocations.html?title=Cumulative+cost+for+last+7+days+by+namespace&window=7d&agg=namespace&chartDisplay=series&idle=shareByNode&rate=cumulative&filters=W10%3D" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:03 +0000] "GET /body.0c6bce9c.css HTTP/1.1" 200 8294 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:03 +0000] "GET /app.c1ac2fc3.js HTTP/1.1" 304 0 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:03 +0000] "GET /model/clusterInfo HTTP/1.1" 200 370 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:03 +0000] "GET /KFOmCnqEu92Fr1Mu4mxK.fc5bb7d7.woff2 HTTP/1.1" 200 15736 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/body.0c6bce9c.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:04 +0000] "GET /KFOlCnqEu92Fr1MmWUlfBBc4.d89c9e5f.woff2 HTTP/1.1" 200 15816 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/body.0c6bce9c.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:04 +0000] "GET /model/clusters?req=1655259723899 HTTP/1.1" 200 41 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:04 +0000] "GET /KFOlCnqEu92Fr1MmEU9fBBc4.2bf8a2a2.woff2 HTTP/1.1" 200 15872 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/body.0c6bce9c.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:04 +0000] "GET /model/getConfigs?req=1655259723900 HTTP/1.1" 200 1310 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:04 +0000] "GET /model/getApiConfig?req=1655259723900 HTTP/1.1" 200 636 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:04 +0000] "GET /model/getProductKey?&req=1655259724001 HTTP/1.1" 200 129 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:04 +0000] "GET /model/allocation/summary?aggregate=namespace&window=4h&accumulate=false HTTP/1.1" 200 2067 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:04 +0000] "GET /model/prometheusQuery?query=avg(kubecost_network_internet_egress_cost) HTTP/1.1" 200 104 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:04 +0000] "GET /model/prometheusQuery?query=sort_desc(sum(increase(kubecost_pod_network_egress_bytes_total%7Bservice!=%22%22,%20namespace=%22kubecost%22%7D%5B7d%5D))%20by%20(service))%20 HTTP/1.1" 200 63 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:04 +0000] "GET /model/assets?window=7d&aggregate=service&accumulate=true HTTP/1.1" 200 1856 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:04 +0000] "GET /model/alerts?req=591923 HTTP/1.1" 200 875 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:04 +0000] "GET /model/allocation/summary?aggregate=namespace&window=7d&accumulate=true&shareTenancyCosts=true&filterPods=&filterControllers=&filterNamespaces=kubecost&filterClusters=&shareNamespaces=kube-system&shareLabels=%3A&shareCost=0&shareSplit=weighted HTTP/1.1" 200 1011 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:04 +0000] "GET /model/allocation/summary?aggregate=namespace&window=7d&accumulate=false&shareTenancyCosts=true&filterPods=&filterControllers=&filterNamespaces=kubecost&filterClusters=&shareNamespaces=kube-system&shareLabels=%3A&shareCost=0&shareSplit=weighted HTTP/1.1" 200 1459 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:04 +0000] "GET /model/allocation/summary?aggregate=controller&window=7d&accumulate=true&shareTenancyCosts=true&filterPods=&filterControllers=&filterNamespaces=kubecost&filterClusters=&shareNamespaces=kube-system&shareLabels=%3A&shareCost=0&shareSplit=weighted HTTP/1.1" 200 1380 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:04 +0000] "GET /model/getConfigs HTTP/1.1" 200 1310 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:04 +0000] "GET /model/assets?window=7d&aggregate=service&accumulate=true&filterLabels=kubernetes_namespace%3Akubecost HTTP/1.1" 200 829 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:04 +0000] "GET /favicon.ico HTTP/1.1" 200 1859 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"
192.168.13.201 - - [15/Jun/2022:02:22:04 +0000] "GET /model/savings/requestSizing?window=2d&filterNamespaces=kubecost&req=1655259724356 HTTP/1.1" 200 6267 "http://k8s-kubecost-kubecost-07c8b6cfbf-1068492450.us-west-2.elb.amazonaws.com/details.html?name=kubecost&type=namespace" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36" "104.246.60.255"

**Comment by mbolt35** [comment]
@srpomeroy What's the version of the network-costs image?

**Comment by srpomeroy** [comment]
@mbolt35 `gcr.io/kubecost1/kubecost-network-costs:v16.0`

**Comment by mbolt35** [comment]
@srpomeroy Ok, cool. That version does support the service tags, but they're all disabled by default, which is likely why there isn't any data showing up. Looks like we just need to change the wording on that particular page... or specifically run different metrics which do include data.

**Comment by jcharcalla** [comment]
I can confirm the promql behind this does work when you set one of these [values](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L567-L576) (Ex: `networkCosts.config.services.amazon-web-services=true` ). It's certainly not documented that way, and I'm also not sure if that requires the cloud provider integration to be enabled.

**Comment by mbolt35** [comment]
@jcharcalla The added service detection does not require cloud provider integration, as it uses the publicly available endpoint APIs from the providers. 

Where is this documented for the frontend features? I do think this is a frontend specific issue. 

@dwbrown2 @wolfeaustin Thoughts?

**Comment by jessegoodier** [comment]
Would it be possible to add 
Internet Egress	
Cross Zone	
Cross Region
Total net

to this card?
Happy to file a new issue if it needs to be seperate.
	
![image](https://user-images.githubusercontent.com/31039225/175101591-77e2df05-7d18-46c5-856e-19cf3871ffaf.png)

**Comment by wolfeaustin** [comment]
> @jcharcalla The added service detection does not require cloud provider integration, as it uses the publicly available endpoint APIs from the providers.
> 
> Where is this documented for the frontend features? I do think this is a frontend specific issue.
> 
> @dwbrown2 @wolfeaustin Thoughts?

I've got some details/Inspect documentation that I need to push up. I'll get this added.

**Comment by nealormsbee** [comment]
Adding this to the FE-Team project and assigning @wolfeaustin. @jessegoodier if you don't mind creating a separate `enhancement` issue for putting more detail into that card, I think it makes sense to track that separately from this ticket.

**Comment by srpomeroy** [comment]
Docs incoming... https://github.com/kubecost/docs/pull/327

**Comment by nealormsbee** [comment]
Hey @srpomeroy !

As of v1.99, the messaging on the card is improved. We now differentiate between:

- Network daemon not enabled
- No service-level network data
- No data for this namespace
- Data available

Is that sufficient to close this issue, or is there more we should do? It seems like a few things wound up combined here (showing x-zone / x-region breakdowns, product documentation), and I'm not sure if those are required to close this issue, or tracked elsewhere, etc.

**Comment by srpomeroy** [comment]
Yes! The new logic/messaging is much clearer. Thanks!
