### ISSUE TITLE
Add the ability for a customer to modify their ngnix config

### ISSUE THREAD

**Issue by zorrobyte** [kubecost/cost-analyzer-helm-chart#1487]
**Related to case 1932**

**What problem are you trying to solve?**
"I don’t know if this was supposed to have been fixed in 1.94.0, but I still can’t get any output from the `Cluster Sizing Recommendations` page.. it just spins and eventually times out."

The issue is that NGNIX is timing out before the backend can satisfy the request.

**Describe the solution you'd like**
AjayTripathy seemed to have been working on an NGNIX config PR where a customer could modify their config and it persists.

**Describe alternatives you've considered**
We could resolve the underlying issue of the page render taking more than 180 seconds to complete

**How would users interact with this feature?**
A user exposed NGNIX file that isn't re-generated when Kubecost is upgraded, alternatively, user configurable timeouts in the helm chart:
https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml#L161

gz#1998<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1998'>Zendesk ticket #1998</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-109) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
routing to @AjayTripathy

**Comment by zorrobyte** [comment]
@jcharcalla is working on case https://kubecost.zendesk.com/agent/tickets/1691 which could benefit from the enhancement

**Comment by dwbrown2** [comment]
This page definitely shouldn't take 180 seconds too load... not saying we want to support different NGINX configs as well, but will defer to @teevans and @AjayTripathy on that part.

**Comment by AjayTripathy** [comment]
I agree 180s seems long. @zorrobyte can you add the following info to this issue while we try to repro this on our scale test cluster?

* What version of kubecost?
* Roughly how many nodes are running
* Roughly how many pods are running
* what cloud provider(s) is this running in?

And is this the related ticket for speed? https://github.com/kubecost/opencost/issues/1164

**Comment by zorrobyte** [comment]
> I agree 180s seems long. @zorrobyte can you add the following info to this issue while we try to repro this on our scale test cluster?
> 
> * What version of kubecost?
> * Roughly how many nodes are running
> * Roughly how many pods are running
> * what cloud provider(s) is this running in?
> 
> And is this the related ticket for pageload speed? [kubecost/opencost#1164](https://github.com/kubecost/opencost/issues/1164)

1.94.1
GCP
~400 nodes
~8500 pods

Yes, this is related to https://github.com/kubecost/opencost/issues/1164 - but differs as user-configurable NGNIX config could be a workaround to get it working while we focus on deeper stack enhancements

**Comment by AjayTripathy** [comment]
cc @biancaburtoiu -- want to try simulating this as well as dropping the time range from using the hourly etl to using the daily?

**Comment by zorrobyte** [comment]
Smartnews is running into this as well, we had a call with them last night and the backend is timing out:
https://kubecost.zendesk.com/agent/tickets/1972

Their AWS load balancer timeout was getting triggered first, now they are getting hit with NGNIX timeouts

Here's the endpoint:
```https://kubecost.smartnews.net/model/savings/requestSizing?algorithm=max-headroom&window=2d&targetCPUUtilization=0.65&targetRAMUtilization=0.65&req=1656376063002```

They were asking about Thanos caching, I recommended Redis to them for testing, but it may not directly resolve this issue as I believe it's ETL that is queried, correct, @keithhand ?
