### ISSUE TITLE
Can I add a banner with company logo to my kubecost dashboard

### ISSUE THREAD

**Issue by pubudumilan111** [kubecost/cost-analyzer-helm-chart#1490]
Linked to Zendesk issue 

gz#2006<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2006'>Zendesk ticket #2006</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-110) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
@pubudumilan111 would love to see what we can potentially support here. Can you share more about what you'd be looking for and what's driving the use case you have in mind?
