### ISSUE TITLE
add efficiency over time to graphs

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#1492]
**What problem are you trying to solve?**

A significant  benefit of kubecost is visibility into container request efficiency. 

Tracking efficiency over time in graphs will allow users to estimate the savings created by the use of kubecost and drive ROI.

**Describe the solution you'd like**

Potentially a 2nd y axis with efficiency %
Could also/alternatively be another option in the chart type settings selector.

Note that this could be well over 100%, though it is not common in my experience. Probably best to check the min/max of the range before rendering scale, and cap it at "200%." 

<img width="877" alt="eff-over-time" src="https://user-images.githubusercontent.com/31039225/174635794-1a2b9027-4ccb-4174-8fe3-1eb8fb4a7c04.png">

<img width="1060" alt="details html png" src="https://user-images.githubusercontent.com/31039225/175071668-1982e4be-6e46-465f-9c4e-66d7af0e7312.png">

**Describe alternatives you've considered**

N/A

**How would users interact with this feature?**

Ideally this would be exposed via an API endpoint, prom metric and via all appropriate graphs.

**Comment by michaelmdresser** [comment]
Love the diagram!

Just to add, we could pick workload efficiency, which is capped at 100% because it is `usage / max(request, usage)`. That avoids > 100% or < 0% problems.

I see a big opportunity here to add a visualization like this to the request sizing page, where efficiency is the most natural existing datapoint to visualize.

**Comment by dwbrown2** [comment]
100% in favor of displaying efficiency over time in Allocation + Overview! 

In this example chart, would we show avg efficiency? That's interesting but I could also see it being nice to view efficiency by each individual namespace, etc. Might be a good spot to get input from @teevans and Anna!

**Comment by jessegoodier** [comment]
I was assuming we'd show the efficiency in the totals line, which would change based on filters. Though we should certainly consider whatever would be the most consistent.

**Comment by teevans** [comment]
Scheduled some time next week for us to go over!

**Comment by jessegoodier** [comment]
Nice work @Annalillie
