### ISSUE TITLE
Update depricated kubernetes APIs

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#1493]
**Describe the bug**
Kubecost is using Kubernetes APIs which have been deprecated in v1.22, this is causing excess logging which could lead to costs increases. Specific examples presented by customers using GKE are [CertificateSigningRequest](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#certificatesigningrequest-v122) `certificates.k8s.io/v1beta1` which has been migrated to `certificates.k8s.io/v1` and [ClusterRole / ClusterRoleBinding](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#rbac-resources-v122)  `rbac.authorization.k8s.io/v1beta1` migrated to `rbac.authorization.k8s.io/v1`. Additional details with screenshots are available in Zendesk ticket #2012. 

The complete list of deprecations are here: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22 

To prepare for k8s v1.25, the [PodSecurityPolicy](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125) from the `policy/v1beta1` API will be removed.

**To Reproduce**
1. Install Kubecost in a 1.22 cluster
2. Install a tool like [Kube-no-trouble](https://github.com/doitintl/kube-no-trouble)
3. run `kubent`

```
./kubent 
1:12PM INF >>> Kube No Trouble `kubent` <<<
1:12PM INF version 0.5.1 (git sha a762ff3c6b5622650b86dc982652843cc2bd123c)
1:12PM INF Initializing collectors and retrieving data
1:12PM INF Target K8s version is 1.22.9-eks-a64ea69
1:12PM INF Retrieved 63 resources from collector name=Cluster
1:12PM INF Retrieved 0 resources from collector name="Helm v2"
1:12PM INF Retrieved 62 resources from collector name="Helm v3"
1:12PM INF Loaded ruleset name=custom.rego.tmpl
1:12PM INF Loaded ruleset name=deprecated-1-16.rego
1:12PM INF Loaded ruleset name=deprecated-1-22.rego
1:12PM INF Loaded ruleset name=deprecated-1-25.rego
__________________________________________________________________________________________
>>> Deprecated APIs removed in 1.22 <<<
------------------------------------------------------------------------------------------
KIND                           NAMESPACE     NAME                   API_VERSION                            REPLACE_WITH (SINCE)
MutatingWebhookConfiguration   <undefined>   pod-identity-webhook   admissionregistration.k8s.io/v1beta1   admissionregistration.k8s.io/v1 (1.16.0)
__________________________________________________________________________________________
>>> Deprecated APIs removed in 1.25 <<<
------------------------------------------------------------------------------------------
KIND                NAMESPACE     NAME                         API_VERSION      REPLACE_WITH (SINCE)
PodSecurityPolicy   <undefined>   eks.privileged               policy/v1beta1   <removed> (1.21.0)
PodSecurityPolicy   kubecost      kubecost-cost-analyzer-psp   policy/v1beta1   <removed> (1.21.0)
PodSecurityPolicy   kubecost      kubecost-grafana             policy/v1beta1   <removed> (1.21.0)
```

**Expected behavior**
New API's are used.

gz#2012<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2012'>Zendesk ticket #2012</a>)</i>

**Comment by AdamStack18** [comment]
@jcharcalla We are looking into this issue and will post an update soon.

**Comment by AjayTripathy** [comment]
PSPs have no upgrade path (totally deprecated) so no point doing anything there since they're optional. The primary things that look like they need upgrade are.

ClusterRole rbac.io.authorization/v1beta -> v1 in prometheus server
ClusterRoleBinding  rbac.io.authorization/v1beta - -> v1 in ksm

**Comment by AjayTripathy** [comment]
This looks like an issue with a user running an older version, since we peeked at the authorizations and found none of them to be using v1beta1. I'll chat w/ customer and follow back up.

**Comment by ledouxpl** [comment]
A related issue is that Kubecost uses `kube-state-metrics` 1.9.8 in its helm chart. The version as well as the container arguments are not configurable. This old version may hit deprecated apis such as ingresses and certificatesigningrequests.

Unless I am mistaken, there is no way through the helm chart's values to change the image used for kube-state-metrics or opt-out of ingress and certificate signing requests by omitting the corresponding `--collector` container arguments.

This makes kube-state-metrics hit the deprecated API and will therefore generated deprecation warnings in GKE.

**Comment by Adam-Stack-PM** [comment]
@ledouxpl, Our engineering is looking into this and will respond soon. Thanks for the additional info.

**Comment by dwbrown2** [comment]
@AjayTripathy can you please shared any updates? 

@ledouxpl created https://github.com/kubecost/cost-analyzer-helm-chart/issues/1547 to review further!

**Comment by dwbrown2** [comment]
Also, @ledouxpl are none of these config options helpful? https://github.com/kubecost/cost-analyzer-helm-chart/tree/develop/cost-analyzer/charts/prometheus/charts/kube-state-metrics

**Comment by ledouxpl** [comment]
@dwbrown2 Setting `collectors.ingresses` to `false` would work. However if Kubecost needs those metrics, it is a bummer that to fix deprecated calls you have to opt-out of one of Kubecost feature. 

Getting around this issue is not that hard, but I just feel that the default Kubecost helm chart should use a `kube-state-metrics` image which _plays nice_ with Kubernetes 1.22+. Or maybe introduce a compatibility matrix? Just my two cents.

**Comment by dwbrown2** [comment]
@ledouxpl that shouldn't be a required metric or have impact on Kubecost functionality  

@kirbsauce would you be able to share the set of required metrics today and comment on version support?

cc @AjayTripathy

**Comment by jcharcalla** [comment]
From the [bring your own Prometheus documentation](https://guide.kubecost.com/hc/en-us/articles/4407595941015-Custom-Prometheus#dependency-requirements ).
```
Kubecost requires the following minimum versions:
    kube-state-metrics - v1.6.0+ (May 19)
    ...
```

And below is the list of the KSM metrics that are both consumed and emitted by the Kubecost from the [User Metrics](https://guide.kubecost.com/hc/en-us/articles/4425134686743-User-Metrics#kube-state-metrics) page. These can also be found on the [KSM Emissions](https://guide.kubecost.com/hc/en-us/articles/4408095797911-Kube-State-Metrics-KSM-Emission#replicated-ksm-metrics) page. Let me know if this helps or if you need more info!

<html><head></head><body><h3 id="kube-state-metrics">Kube-State-Metrics<a class="link-anchor" href="https://guide.kubecost.com/hc/en-us/articles/4425134686743-User-Metrics#kube-state-metrics"></a></h3>

<p>The following KSM metrics are both consumed and emitted by the Kubecost installation. The <code>cost-model</code> replicates all of these metrics such that a KSM installation is not actually required. Read more <a href="https://guide.kubecost.com/hc/en-us/articles/4408095797911">here</a>.</p>

Metric | Description
-- | --
kube_deployment_spec_replicas | Number of pods specified for a Deployment
kube_deployment_status_replicas_available | Number of pods currently available for a Deployment
kube_job_status_failed | The number of pods which reached Phase Failed and the reason for failure
kube_namespace_annotations | Kubernetes annotations converted to Prometheus labels
kube_namespace_labels | Kubernetes labels converted to Prometheus labels
kube_node_labels | Kubernetes labels converted to Prometheus labels
kube_node_status_allocatable | The allocatable for different resources of a node that are available for scheduling
kube_node_status_allocatable_cpu_cores | Total allocatable cpu cores of the node (Depecated in ksm 2.0.0)
kube_node_status_allocatable_memory_bytes | Total allocatable memory bytes of the node (Depecated in ksm 2.0.0)
kube_node_status_capacity | The capacity for different resources of a node
kube_node_status_capacity_cpu_cores | Total cpu cores available on the the node (Depecated in ksm 2.0.0)
kube_node_status_capacity_memory_bytes | Total memory available on the node (bytes) (Depecated in ksm 2.0.0)
kube_node_status_condition | The condition of a cluster node
kube_persistentvolume_capacity_bytes | Total capacity of a persistent volume (bytes)
kube_persistentvolume_status_phase | Status of a persistent volume (Bound
kube_persistentvolumeclaim_info | Information about persistent volume claim
kube_persistentvolumeclaim_resource_requests_storage_bytes | The capacity of storage requested by the persistent volume claim
kube_pod_annotations | Kubernetes annotations converted to Prometheus labels
kube_pod_container_resource_limits | The number of requested limit resource by a container
kube_pod_container_resource_limits_cpu_cores | Limit on CPU cores that can be used by the container. (Depecated in ksm 2.0.0)
kube_pod_container_resource_limits_memory_bytes | Limit on the amount of memory that can be used by the container. (Depecated in ksm 2.0.0)
kube_pod_container_resource_requests | The number of requested request resource by a container
kube_pod_container_status_restarts_total | The number of container restarts per container
kube_pod_container_status_running | Describes whether the container is currently in running state
kube_pod_container_status_terminated_reason | Describes the reason the container is currently in terminated state
kube_pod_labels | Kubernetes labels converted to Prometheus labels
kube_pod_owner | Information about the Pod’s owner
kube_pod_status_phase | The pods current phase (Pending
kube_replicaset_owner | Information about the ReplicaSet’s owner

**Comment by romankydybets** [comment]
Warning policy/v1beta1 usage PR
#1599

**Comment by Adam-Stack-PM** [comment]
@romankydybets, Thanks the PR!

**Comment by allemp** [comment]
I've been having the same problem as 

> A related issue is that Kubecost uses `kube-state-metrics` 1.9.8 in its helm chart. The version as well as the container arguments are not configurable. This old version may hit deprecated apis such as ingresses and certificatesigningrequests.


The error looked like

```
reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1beta1.CertificateSigningRequest: the server could not find the requested resource
```

I tried disabling ingresses collector, but it kept spamming errors for certificatesigningrequests. Disabling those as well in the kubecost values.yaml fixed the log error spam:

```yaml
prometheus:
  kube-state-metrics:
    collectors:
      ingresses: false
        certificatesigningrequests: false
```

I'm not that great with helm and it took me a while to figure out how to work with helm subcharts so for anyone googling the issue I've added the exact error and the workaround I've used.

**Comment by zorrobyte** [comment]
@Adam-Stack-PM I have another customer blocked, unable to update their clusters due to KSM depreciation. They'd rather not create a snowflake KubeCost configuration, as currently, we'd have to disable KSM via the Prometheus sub-chart: https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/charts/prometheus/values.yaml#L391

Could we add a variable in the primary helm chart values to disable/remove KSM so it's easier for customers to configure?

**Comment by AjayTripathy** [comment]
There is a value to disable KSM from the top level, it's simply .Values.prometheus.kube-state-metrics.disabled . Subchart variables are specifiable from their parents.

**Comment by zorrobyte** [comment]
> .Values.prometheus.kube-state-metrics.disabled

Excellent, thanks! I've notified the customer and shared with the team!

**Comment by dwbrown2** [comment]
@zorrobyte @AjayTripathy were we able to answer @allemp's question here? https://github.com/kubecost/cost-analyzer-helm-chart/issues/1493#issuecomment-1212037352

**Comment by Adam-Stack-PM** [comment]
@dwbrown2, If you identify an issue we have missed, please add the needs-triage label.  

This will put the issue into the engineering support rotation triage workflow that has a 24hr SLA

@jjarrett21, Please reach out to via slack to Ross and confirm this customer has gotten a response or will get help today.   This bug also needs to be prioritized and categorized into a sub-category.

**Comment by zorrobyte** [comment]
> @zorrobyte @AjayTripathy were we able to answer @allemp's question here? [#1493 (comment)](https://github.com/kubecost/cost-analyzer-helm-chart/issues/1493#issuecomment-1212037352)

Should be good! Just waiting for a response in this GH issue

**Comment by goshlanguage** [comment]
It looks like (as indicated in GKE) `cost-analyzer` `v1.99.0` still tries to reach deprecated APIs. 
Is there some way of preventing these calls to outdated?

The following output is from GKE after installing the latest version of `cost-analyzer` with the following settings:

```
helm install kubecost kubecost/cost-analyzer \
   --version 1.99.0 \
   --set prometheus.kube-state-metrics.collectors.ingresses=false \
   --set prometheus.kube-state-metrics.collectors.certificatesigningrequests=false
```

## Deprecated APIs called

| API | User agent | Total calls (last 30 days) | Last called |
| - | - | - | - |
|/apis/certificates.k8s.io/v1beta1/certificatesigningrequests | kube-state-metrics/v1.9.8 (linux/amd64) kube-state-metrics/	| 2600782	| December 15, 2022 at 5:27:00 PM UTC-5 |
|/apis/extensions/v1beta1/ingresses | kube-state-metrics/v1.9.8 (linux/amd64) kube-state-metrics/ | 2600774 | December 15, 2022 at 5:28:00 PM UTC-5 |

**Comment by AjayTripathy** [comment]
Hi @goshlanguage does this actually block the install? This probably needs to get rolled into a general ksmv2 upgrade since it's ksm that's accessing-- just trying to get a sense for priority. We do already support byo-ksmv2 natively but agree we should get this done in the helm chart.

**Comment by goshlanguage** [comment]
@AjayTripathy It's not so much that it blocks the install (I do have issues with that but that's out of scope), but that auditing tools and the like flag it such as GKE portal. While it's innocuous really, kubecost can toggle what apis it's trying to reference and probably should.

I'd love to help make that possible, but I don't know where to start

**Comment by goshlanguage** [comment]
Actually, apologies, I think I have an idea from your message, many thanks!

**Comment by teevans** [comment]
Closing for now since I believe we've corrected this with KSM adjustments.

**Comment by thomasvn** [comment]
To follow up on this discussion, I was able to validate that installing Kubecost with the following configuration resolved the issue.

```
helm install kubecost kubecost/cost-analyzer \
   --set prometheus.kube-state-metrics.collectors.ingresses=false \
   --set prometheus.kube-state-metrics.collectors.certificatesigningrequests=false
```

KSM was configured to stop making requests to the API server at the following endpoints: `/apis/extensions/v1beta1/ingresses`, `/apis/certificates.k8s.io/v1beta1/certificatesigningrequests`.

**Comment by andrewhharmon** [comment]
Im having a similar problem on k8s 1.27. My logs are spammed with 
```
Failed to list *v1beta1.CronJob: the server could not find the requested resource                                                                                                                   
Failed to list *v1beta1.PodDisruptionBudget: the server could not find the requested resource                                                                                                                 
Failed to list *v2beta1.HorizontalPodAutoscaler: the server could not find the requested resource
```

I guess i can turn off those collectors as indicated above? Or is there a better solution? just want to verify I'm shouldn't be upgrading to a newer version or something.

**Comment by thomasvn** [comment]
@andrewhharmon Thanks for bringing this up! Yes turning off the respective collectors would be the best solution here.
