### ISSUE TITLE
Grafana "Pod cost & utilization metrics" dashboard has missing graph points

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1494]
**Describe the bug**
On the "Pod cost & utilization metrics" dashboard, the "CPU Usage vs Requested" graph is only showing usage data. It looks like the query used for requests is:

```avg(kube_pod_container_resource_requests{resource="cpu", unit="core", namespace=~"$namespace", pod=~"$pod", container=~"$container", container!="POD"}) by (container)```

versus if you remove the `container=~"$container"`, the following query works:

```avg(kube_pod_container_resource_requests{resource="cpu", unit="core", namespace=~"$namespace", pod=~"$pod", container!="POD"}) by (container)```

**To Reproduce**
1. Go to `<kubecost-url>/grafana/d/at-cost-analysis-pod/pod-cost-and-utilization-metrics?orgId=1&from=1655784863828&to=1655957663828&var-namespace=kube-system&var-pod=kube-proxy-drc67&var-cluster=&var-datasource=Prometheus&editPanel=94&tab=query`
2. Update the "B" query by removing `container=~"$container"`
3. Begin to see data on the graph

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/43491549/175086883-105ed6d3-577c-4b89-b52d-9e8ea0b0c7a8.png)

After:
![image](https://user-images.githubusercontent.com/43491549/175086771-08c81d47-e7ba-4221-b555-8fb8a4bfd074.png)

**Comment by keithhand** [comment]
This appears to get set [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/pod-utilization.json#L277)

**Comment by dwbrown2** [comment]
Nice find, @keithhand! Thanks for reporting too. Want to open a PR or would be better for someone else to pick up?
