### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by jvendetti** [kubecost/cost-analyzer-helm-chart#1495]
Testing for kirbsauce

gz#2027<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2027'>Zendesk ticket #2027</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-111) by [Unito](https://www.unito.io)

**Comment by kirbsauce** [comment]
testing sync, removing needs triage
