### ISSUE TITLE
hide context switcher by default

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#1498]
**What problem are you trying to solve?**

Hide the context switcher on the bottom left of the UI unless it is specifically enabled in helm.

Users are often confused when trying to do multi-cluster. A large percentage of users want multi-cluster single-pane-of-glass and not a bookmark to another kubecost environment. 

**Describe the solution you'd like**

remove this based on helm value:
![](https://user-images.githubusercontent.com/31039225/175563598-24543edf-1390-4380-b7f1-7d9a8c646b50.png)

**Describe alternatives you've considered**

Documentation has been updated, but not all users will read the docs.

**How would users interact with this feature?**

helm value

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-112) by [Unito](https://www.unito.io)

**Comment by teevans** [comment]
cc: @dwbrown2 @AjayTripathy @mbolt35

**Comment by dwbrown2** [comment]
Not opposed, but how would we make this feature easily discoverable for those that do want to add a new context? Maybe a clear option in Settings? 

In my view, we at a minimum want people to know they have (multiple) options for adding additional clusters.

**Comment by jessegoodier** [comment]
I understand we don't want to remove value and hide it more than necessary. 

With the new overview page, if you have a single cluster, it points to: https://github.com/kubecost/docs/blob/main/multi-cluster.md

Perhaps bullet 2 (on that doc) needs to be expanded, and we will need to update that page + the cluster-switcher.md when we "fix" this.

**Comment by dwbrown2** [comment]
+1, I think there's two things here: 1) make the current docs as helpful as possible and then 2) refine this product experience. I propose we tackle 1 quickly while think through 2. Thoughts?

**Comment by Adam-Stack-PM** [comment]
### **Action Items:**  For quick reference (credit Webb)

1)) Make the current docs as helpful as possible and then 
2) Refine this product experience.

Order of Action 
We tackle 1 quickly. Then we think through and design the right product experience.

**Comment by DKeeling01** [comment]
Hello all - 

Just checking in for a status/timeline on this request - I have a customer who is asking for the ability to disable switch context in the UI. They are also having an issue with customers being confused with what the functionality is supposed to be.

Thanks!

Danielle

**Comment by DKeeling01** [comment]
Hi all - 

Just checking in once again - I have another customer who this time is asking for the switch context feature to include OAuth2 so they can integrate multiple contexts  in different  Azure subscriptions. Any thoughts?

Thanks!

Danielle

**Comment by AjayTripathy** [comment]
@DKeeling01 what's the current behavior when oauth2 is enabled? We don't allow adding the context to the list of switchable contexts?

**Comment by AjayTripathy** [comment]
@DKeeling01 ping?

**Comment by DKeeling01** [comment]
@AjayTripathy - when they enabled OAuth2 and try to switch contexts the page doesn't load. It's my understanding that happens because context switch only allows basic auth thus causing the handshake to fail. However, OAuth2 is required in Azure so basic auth is not an option

**Comment by jessegoodier** [comment]
possibly related to https://github.com/kubecost/cost-analyzer-helm-chart/issues/1929
and
https://github.com/kubecost/cost-analyzer-helm-chart/issues/2063

**Comment by jessegoodier** [comment]
Just another example:
I had a customer that had used two different browsers and one was on a different context. 
He couldn't understand why costs kept changing based on the browser he used. 

We deleted the cookies and all was fixed. Customer felt it was confusing, and he had wasted time.

**Comment by kwombach12** [comment]
@dwbrown2 what are your thoughts on moving the context switcher to settings so its a bit more hidden?

**Comment by dwbrown2** [comment]
A number of big discussions around packaging going on here... Let's follow up soon!

**Comment by jessegoodier** [comment]
@dwbrown2 would you support a helm value such as:

```yaml
kubecostProductConfigs:
  contextSwitcherEnabled: false
```

This could be used by multi-cluster customers that have users who are confused about the UI element?

**Comment by dwbrown2** [comment]
This has been completed as of ~v1.103
