### ISSUE TITLE
Aggregation API returns 500 with large offset

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#150]
When an `offset` greater than currently available data window is passed, we return the following:

```
{"code":500,"data":null,"message":"Error: Internal Server Error"}
```

We should probably just return empty data in this case, or at least a more helpful error?

**Comment by nikovacevic** [comment]
This error is being returned from the cost model, not the aggregation API:
```
Error parsing normalization values: Normalization data is empty, kube-state-metrics or node-exporter may not be running
```
Aggregation API is simply passing it through. I'll talk with @AjayTripathy about how best to handle this. I'd be hesitant to do this, but we could just check for the substring "Normalization data is empty" in the error string and return `200` with `data: []` in that case, but that might suppress some real errors.
