### ISSUE TITLE
add support for microsoft teams webhooks (ms-teams)

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#1500]
**What problem are you trying to solve?**

A few customers have requested for ms teams webhook support for alerts.

(servicenow comes up occasionally as well)

**Describe the solution you'd like**

Allow MS teams webhooks in alerts.

**Describe alternatives you've considered**

They have tried the MS teams URL in current slack box, but it did not work.

**How would users interact with this feature?**

Add option on /alerts.html

**Comment by jessegoodier** [comment]
FYI, I asked the customer for more detail (kroll) and am waiting for more information.

**Comment by dwbrown2** [comment]
@jessegoodier let us know if you hear more, we're prioritizing for next release now

@teevans I tried this on the frontend with a generic ms teams webhook, e.g. `https://m365x234234.webhook.office.com/`

And we overwrote with `https://hooks.slack.com/services/XXXXXXXXXXX/XXXXXXXXXXX/XXXXXXXXX` on the frontend display so there's a chance we're not storing this correctly.

**Comment by teevans** [comment]
Yeah, that experience is going to change this month. If we can ensure the backend is sending properly formatted webhooks to teams, we can build a nice experience around choosing which platform you want to send to. I assume the payload that we send to slack won't match what we send to teams.

**Comment by jessegoodier** [comment]
A customer got MS Teams to work using "power automate"

https://powerautomate.microsoft.com/en-us/

we can close this issue unless we want to change the wording here: 
![image](https://user-images.githubusercontent.com/31039225/180269819-3e3cc412-d4cd-409d-b8ff-1c4800ba2992.png)

**Comment by AjayTripathy** [comment]
Can we add documentation for how powerautomate works so it doesn't get lost, then close this issue linking that documentation?

**Comment by teevans** [comment]
^^ Let's do that, but let's also update the copy on the page, and provide a help link to this new documentation.

**Comment by srpomeroy** [comment]
FWIW, Microsoft Power Automate is separate from Microsoft Teams and not necessarily included in M/O365 licensing.

**Comment by dwbrown2** [comment]
Would it make sense to see how we can support teams too? Another path would be to at adding a more generic PagerDuty integration.

**Comment by teevans** [comment]
I'm assuming they're using the power-automate feature to take the slack formatted webhook and port it to a teams notification. I would argue that if there is a way for us to build multiple different variations of webhooks for different platforms, we should. Including a generic 'Webhook' that has a simple payload that any of their middleware tools like powerapps can parse.

**Comment by mmurph3** [comment]
We have another customer who is interested in this feature and for it to be available by default under alerts. That's 2 customers in the past week (1 will be intercepting the slack webhook as a workaround).

**Comment by sylus** [comment]
I know we at Statistics Canada would be interested in this feature as well :)
