### ISSUE TITLE
add details to 

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#1502]
**What problem are you trying to solve?**

Add details to the 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**How would users interact with this feature?**

![node right sizing](https://user-images.githubusercontent.com/31039225/176166469-0134aa60-72ad-44cb-9f93-7580f9597a54.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-113) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
Agree this would be a nice addition! I'm somewhat torn between a smaller preview (e.g. assets) vs much more detail (e.g. inspect page). Have a specific set of use cases in mind at this point?

**Comment by jessegoodier** [comment]
stale issue, mitigated by cluster overview page
