### ISSUE TITLE
add details to "Managed underutilized nodes"

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#1503]
Customer request: 

Note: Do we have plans to make this work for multi-cluster?

**What problem are you trying to solve?**

Better understand the potential savings on the "Managed underutilized nodes" page.

**Describe the solution you'd like**

Add more details to the action.html?a=unusednodes

Suggestions: cost/month, Cluster Name, node type, region

**Describe alternatives you've considered**

Cost/Month would be useful. 
The other details are in the tags when you click the node, but for large cluster, this doesn't scale.

**How would users interact with this feature?**

![node right sizing](https://user-images.githubusercontent.com/31039225/176166469-0134aa60-72ad-44cb-9f93-7580f9597a54.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-114) by [Unito](https://www.unito.io)

**Comment by AdamStack18** [comment]
@jessegoodier Grate idea. Marketed as a cost savings product enhancement for tracking.

**Comment by dwbrown2** [comment]
+1 we definitely want to make this multi-cluster. Proposal is we do it next release.

cc @teevans and @nealormsbee because they are doing a rewrite in React now.
