### ISSUE TITLE
Allow customizing the list of installed Grafana dashboards and remove Prometheus Benchmark dashboard

### ISSUE THREAD

**Issue by zerodayyy** [kubecost/cost-analyzer-helm-chart#1508]
**What problem are you trying to solve?**
I noticed a "Prometheus Benchmark - 2.17.x" dashboard in my Grafana, which didn't work properly since I'm not using Prometheus shipped with Kubecost. The resource in question is `grafana-dashboard-prometheus-metrics-template.yaml`, which deploys a dashboard via `prom-benchmark-dashboard` ConfigMap.

Furthermore, the dashboards that provide no cost information (e.g. "Attached Disk Metrics", "Node Utilization Metrics") only make sense when built-in Prometheus is used, however otherwise they provide duplicate information already available in dashboards created by `kubernetes-mixin` in prom-operator (I'm pretty confident to say this is the common way of using Prometheus on k8s).

**Describe the solution you'd like**
I'd prefer the Helm chart to not provide this dashboard as this dashboard is not related to cost-analyzer itself, and rather is a debugging add-on.

If it can't be removed, it would make sense if it is only installed when build-in Prometheus is enabled (i.e. when `global.prometheus.enabled` is `true`).

Regarding other dashboards, I think there should be an option to enable each dashboard individually or at least by group (i.e. cost metrics, utilization metrics, prometheus benchmark etc.)

**Describe alternatives you've considered**
At the moment , the only approach that works for me is disabling cost-analyzer dashboards altogether.

**How would users interact with this feature?**
Helm values would look something like:

```yaml
grafana:
  sidecar:
    dashboards:
      enabled: true
      dashboards:
        - cluster-metrics
        - cluster-utilization
        - label-cost-utilization
```

Chart users would then be able to override the dashboard list, enabling only needed ones.

gz#2070<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2070'>Zendesk ticket #2070</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-115) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
I really like the structure/syntax proposed. Have you seen this pattern supported successfully in other projects?

The primary complication that I see creating a smooth handoff experience from the Kubecost FE. Today, we have the ability to inform users when Grafana is/isn't enabled globally but that model would need to change when individual dashboards may be missing.

**Comment by zerodayyy** [comment]
up

**Comment by chipzoller** [comment]
@jessegoodier, what are your thoughts on making this template conditional based on whether the built-in Prometheus is deployed? The ConfigMap template is [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/grafana-dashboard-prometheus-metrics-template.yaml).

**Comment by jessegoodier** [comment]
> @jessegoodier, what are your thoughts on making this template conditional based on whether the built-in Prometheus is deployed? The ConfigMap template is [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/grafana-dashboard-prometheus-metrics-template.yaml).

Works for me. Happy to review any pull request.
Though I'm not sure what our position is on including Grafana in our future releases.
