### ISSUE TITLE
Add "Editor" role option to values.yaml

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#1511]
**What problem are you trying to solve?**
Would like to leverage new Editor role for all KC end users, much like "read-only", and avoid an RBAC integration.

**Describe the solution you'd like**
A setting in the values.yaml file similar to "read-only", but for "editor"

**Describe alternatives you've considered**
An RBAC integration, but would like to avoid this lift just to set "editor" functionality for all users

**How would users interact with this feature?**
as a setting in the values.yaml file

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-116) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
Interesting idea! Feedback on the technical difficulty of this @AjayTripathy?

Should we change this pattern and move to a "default-role: reader|admin|editor"
