### ISSUE TITLE
Update node-exporter

### ISSUE THREAD

**Issue by sundeepghuman** [kubecost/cost-analyzer-helm-chart#1512]
**What problem are you trying to solve?**
The version of node-exporter we are using was released on Jun 4, 2019 as pointed out by @dramich in #1443 . We should keep up to date with our dependencies.

**Describe the solution you'd like**
Update node-exporter versions to a more recent stable version

**Describe alternatives you've considered**
Do nothing - doesn't seem like best practice to use a 3 year old release. It's possible that Trivy is not revealing all known vulnerabilities or this may cause later breakages due to lack of feature parity down the road.

**How would users interact with this feature?**
N/A

gz#2081<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2081'>Zendesk ticket #2081</a>)</i>

**Comment by dwbrown2** [comment]
Crazy idea: when testing an upgrade, we could potentially run our current version of node-exporter as well as new version on a number of nodes. Then look at diff on `/metrics` endpoint. 

Ways this could impact product: 1) core metrics are removed 2) metrics are renamed 3) resource consumption increase (due to new metrics or otherwise)

**Comment by sundeepghuman** [comment]
@dwbrown2 that's a great idea. We probably want to instrument this as part of the generic rollout process across entire clusters. As part of the review of our testing and rollout processes, I can make sure to include scoping out instrumenting our own "Canary Analysis System." Ideally we would push new builds to canaries (some small portion of prod clusters, i.e. 10%) where it would bake for several days and then automate A/B diffing for the new build versus the old build, although to start we could have this be a manual comparison. After a couple days of traffic, if the comparison checks out, we would push the build to the rest of the clusters. I need to understand the architecture a bit more here to recommend the best process, whether that is using replicases (standard) or different namespaces and more of a A/B load test comparison. For our hosted solution, canarying is definitely something we should implement.
