### ISSUE TITLE
Enabling metrics-exporter causes Multi-Attach error on pod init

### ISSUE THREAD

**Issue by baldey-nz** [kubecost/cost-analyzer-helm-chart#1514]
**Describe the bug**
Enabling the metrics-exporter in the helm chart creates a volume multi-attach error when the metrics pod is created on a different node to the cost-analyzer pod. One of the pods gets stuck in init:0/1 status

**To Reproduce**

deploy the cost-analyzer helm chart with the following option enabled:

_kubecostMetrics:
  exporter:
    enabled: true
    port: 9005_

**Expected behavior**
That the pods both start. It looks to me that perhaps an affinity rule is needed here if both the pods are running and the PVC is shared? This might not be a bug (might be that i just havent found the correct docs) if the intention here is that if you enable the metrics exporter pod on then you need to disable the cost-analyzer pod? Or possibly use a different storageClass with something like volumeBindingMode: WaitForFirstConsumer?

**Collect logs (please complete the following information):**

 - Run `helm ls` and paste the output here:

`helm ls -n kubecost

NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART               	APP VERSION

kubecost	kubecost 	19      	2022-07-04 21:16:33.213006522 +0000 UTC	deployed	cost-analyzer-1.94.3	1.94.3`

 - If the pod is stuck in init, run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-init` and paste output here:

```
kubecost-cost-analyzer-6796bff4bd-nqdft       0/3     Init:0/1   0
Warning  FailedAttachVolume  14m                    attachdetach-controller  Multi-Attach error for volume "pvc-659ad362-0f95-44c0-8890-b0126645a655" Volume is already used by pod(s) kubecost-metrics-669884f68d-2djzb
```

gz#2090<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2090'>Zendesk ticket #2090</a>)</i>

**Comment by keithhand** [comment]
Hello @baldey-nz, generally, users will use this pod as an alternative to emitting Kubecost metrics without having to deploy the cost-analyzer pod. It sounds like you still intend on deploying the cost-analyzer pod, so I am curious as to what your end goal is so that I might be able to find the best solution for you.

**Comment by baldey-nz** [comment]
Thanks for coming back to me. i think you have just answered my question in your response. Its designed to either run one or the other and thats fine it wasnt clear to me from the comments in the helm chart or the docs i could find. closing this one, thanks again
