### ISSUE TITLE
Expecting Annotation aggregation and filter value along with existing dropdown values

### ISSUE THREAD

**Issue by jainasanthoshkmr** [kubecost/cost-analyzer-helm-chart#1519]
**What problem are you trying to solve?**
I would like to create an alert by aggregating annotations applied on k8s namespace.

**Describe the solution you'd like**
Provide additional drop down value to choose annotations as like as existing value Label.

**Describe alternatives you've considered**
![image](https://user-images.githubusercontent.com/79314049/177537714-5e744338-5361-4281-9c06-7276b7adc16d.png)

**How would users interact with this feature?**
For generating and schedule alerts based on owners of namespaces.

gz#2109<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2109'>Zendesk ticket #2109</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-117) by [Unito](https://www.unito.io)

**Comment by keithhand** [comment]
Hello @jainasanthoshkmr this sounds like a great feature request! Let me tag @Adam-Stack-PM from our product team so that we can get some eyes on this.

**Comment by Adam-Stack-PM** [comment]
@jainasanthoshkmr, Great idea. Will add this to our feature backlog and review with the team.
