### ISSUE TITLE
totalcost number is not matching (cpucost + ramcost + gpucost + pvcost + networkcost + loadbalancercost )

### ISSUE THREAD

**Issue by peijianju-sonrai** [kubecost/cost-analyzer-helm-chart#1521]
**Describe the bug**
Hi, I am exporting kubecost cost's data using `/model/allocation` endpoint. And comparing the result to AWS cost explorer. 
But I found that 
totalcost number I get is not matching `(cpucost + ramcost + gpucost + pvcost + networkcost + loadbalancercost)`

Further investigation, I notice these metrics
- cpuCostAdjustment
- gpuCostAdjustment
- networkCostAdjustment
- pvCostAdjustment
- ramCostAdjustment
- loadBalancerCostAdjustment

1. What are these adjustment costs? Where does them come from?
2. When comparing the result to AWS cost explorer, should I consider those adjustment costs?
3. We have a saving plan with AWS, can kubecost reveal that in the result

Thank you

**To Reproduce**
1. `kubectl port-forward svc/kubecost-cost-analyzer 9090:9090`
2. `curl http://localhost:9090/model/allocation \
  -d window=2022-06-29T00:00:00Z,2022-06-29T23:59:59Z \
  -d aggregate=namespace \
  -G`

Thank you

**Expected behavior**

**Screenshots**

**Collect logs (please complete the following information):**

 - Run `helm ls` and paste the output here:
```
❯ helm ls
Enter MFA code for arn:aws:iam::418471569463:mfa/peijian.ju:
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART               	APP VERSION
kubecost	kubecost 	30      	2022-06-17 14:18:29.601486693 +0000 UTC	deployed	cost-analyzer-1.94.3	1.94.3
```

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-server` and paste the output here:
N/A

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-model` and paste the output here:
N/A

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-frontend` and paste the output here:
N/A

gz#2119<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2119'>Zendesk ticket #2119</a>)</i>

**Comment by keithhand** [comment]
Hello @peijianju-sonrai, you will likely have a better chance to match pricing using the Assets screen directly; here is a link to a document that describes how you should be able to compare those prices: https://guide.kubecost.com/hc/en-us/articles/4407596809111-AWS-Node-Price-Reconciliation-Methodology. The adjustments that you see in the application should change made to your costs based on your cost and usage report, which would include savings plan discounts. Does this help clear things up?

**Comment by nealormsbee** [comment]
@peijianju-sonrai does that API do what you need? If so, I'll close this ticket and consider the problem resolved ^_^

**Comment by peijianju-sonrai** [comment]
> @peijianju-sonrai does that API do what you need? If so, I'll close this ticket and consider the problem resolved ^_^

@nealormsbee  thank you, please feel free to close this
