### ISSUE TITLE
Something about Cost Allocation

### ISSUE THREAD

**Issue by hyj-github** [kubecost/cost-analyzer-helm-chart#1525]
**What problem are you trying to solve?**
I use Kubecost to calculate the cost of the K8S cluster。The K8S cluster is AWS EKS。
The following picture shows the items related to costs displayed by "Cost allocation". What are the meanings of each item? What factors are associated with the cost value? For example, the LB in the screenshot below.

![image](https://user-images.githubusercontent.com/54680729/177675736-4cc1f58d-db35-4306-bdc6-b4b202feda77.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-120) by [Unito](https://www.unito.io)

**Comment by kirbsauce** [comment]
Hi @hyj-github , sorry for the delayed response.  LB stands for loadbalancers, and other zero columns normally fill in when you integrate with your cloud provider.  (This gives us access to those resources outside of kubernetes.). While GPU is a k8s resource, it looks like you're not using those.  As for __idle__, those are the costs of the node/cluster resources that are available but not yet allocated to workloads.

Let's start with this, and please let me know if you have any followup questions.

**Comment by kirbsauce** [comment]
@hyj-github , here is a bit more detailed information. Agree that it's slightly outdated as related to the UI, but the method of calculation hasn't changed.

**Comment by hyj-github** [comment]
> @hyj-github , here is a bit more detailed information. Agree that it's slightly outdated as related to the UI, but the method of calculation hasn't changed.
Where are the detailed information?

**Comment by kirbsauce** [comment]
Apologies, @hyj-github , my mistake...
https://guide.kubecost.com/hc/en-us/articles/4407601807383-Kubernetes-Cost-Allocation#cost-metrics-1

**Comment by hyj-github** [comment]
> Apologies, @hyj-github , my mistake... https://guide.kubecost.com/hc/en-us/articles/4407601807383-Kubernetes-Cost-Allocation#cost-metrics-1

I cannot access this website. Is there any relevant introduction in other places? Such as github

**Comment by dwbrown2** [comment]
@hyj-github can you share why you're unable to access that page at guide.kubecost.com?

Here's the corresponding page on GH: https://github.com/kubecost/docs/blob/main/cost-allocation.md

**Comment by hyj-github** [comment]
> @hyj-github can you share why you're unable to access that page at guide.kubecost.com?
> 
> Here's the corresponding page on GH: https://github.com/kubecost/docs/blob/main/cost-allocation.md

This page is too general, can you be more detailed and explain how the figures are calculated.In addition, foreign websites cannot be accessed in China.

**Comment by dwbrown2** [comment]
These calculations are based on the OpenCost spec: https://github.com/kubecost/opencost/tree/develop/spec
