### ISSUE TITLE
Azure cost export changed format & missing pricing data

### ISSUE THREAD

**Issue by andreb89** [kubecost/cost-analyzer-helm-chart#1526]
Hi,
it seems like during May/start of June Azure changed the format of their exported cost reports, that we had configured for usage with AKS and Kubecost (out-of-cluster costs). We have been using this setup/configuration for over a year and it worked. But since May/June the out-of-cluster costs were very strange and sadly only today I had time to check everything and then noticed the difference in the exported cost reports.

The old columns of the cost export CSV is as follows:
```
Name der Abteilung (DepartmentName),Name des Kontos (AccountName),ID des Kontobesitzers (AccountOwnerId),Abonnement-GUID (SubscriptionGuid),Name des Abonnements (SubscriptionName),Ressourcengruppe (ResourceGroup),Ressourcenstandort (ResourceLocation),UsageDateTime (UsageDateTime),ProductName (ProductName),Kategorie der Verbrauchseinheit (MeterCategory),MeterSubcategory (MeterSubcategory),ID der Verbrauchseinheit (MeterId),Name der Verbrauchseinheit (MeterName),Region der Verbrauchseinheit (MeterRegion),Maßeinheit (UnitOfMeasure),UsageQuantity (UsageQuantity),Ressourcensatz (ResourceRate),PreTaxCost (PreTaxCost),Kostenstelle (CostCenter),Genutzter Dienst (ConsumedService),ResourceType (ResourceType),InstanceId (InstanceId),Tags (Tags),OfferId (OfferId),Zusätzliche Informationen (AdditionalInfo),Dienstinformation 1 (ServiceInfo1),Dienstinformation 2 (ServiceInfo2)
```

The new columns:
```
invoiceId,previousInvoiceId,billingAccountId,billingAccountName,billingProfileId,billingProfileName,invoiceSectionId,invoiceSectionName,resellerName,resellerMpnId,costCenter,billingPeriodEndDate,billingPeriodStartDate,servicePeriodEndDate,servicePeriodStartDate,date,serviceFamily,productOrderId,productOrderName,consumedService,meterId,meterName,meterCategory,meterSubCategory,meterRegion,ProductId,product,subscriptionId,subscriptionName,publisherType,publisherId,publisherName,resourceGroupName,InstanceName,resourceLocation,Location,effectivePrice,quantity,unitOfMeasure,chargeType,billingCurrency,pricingCurrency,costInBillingCurrency,costInPricingCurrency,costInUsd,paygCostInBillingCurrency,paygCostInUsd,exchangeRatePricingToBilling,exchangeRateDate,isAzureCreditEligible,serviceInfo1,serviceInfo2,additionalInfo,tags,payGPrice,frequency,term,reservationId,reservationName,unitPrice
```

Since then we also found in the cost-model container log warnings regarding missing pricing data for vms:
```
no pricing data found for ,,ondemand: &{map[agentpool:nodexyz beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.azure.com/agentpool:nodexyz kubernetes.azure.com/cluster:MC_staging-xyz-infra-group_staging-xyz-aks_westeurope kubernetes.azure.com/mode:user kubernetes.azure.com/node-image-version:AKSUbuntu-1804containerd-2022.04.13 kubernetes.azure.com/role:agent kubernetes.azure.com/storageprofile:managed kubernetes.azure.com/storagetier:Standard_LRS kubernetes.io/arch:amd64 kubernetes.io/hostname:aks-nodexyz-23568084-vmss00000j kubernetes.io/os:linux kubernetes.io/role:agent node-role.kubernetes.io/agent: owner:zuse providerID: storageprofile:managed storagetier:Standard_LRS topology.disk.csi.azure.com/zone:westeurope-2 topology.kubernetes.io/zone:westeurope-2] accelerator nvidia}
```

As well as warnings in the cost-model logs for missing fields:
```
CostModel.ComputeAllocation: Node CPU cost query result missing field: 'instance_type' field does not exist in data result vector
CostModel.ComputeAllocation: Node CPU cost query result missing field: 'instance_type' field does not exist in data result vector
CostModel.ComputeAllocation: Node RAM cost query result missing field: 'instance_type' field does not exist in data result vector
CostModel.ComputeAllocation: Node RAM cost query result missing field: 'instance_type' field does not exist in data result vector
CostModel.ComputeAllocation: Node GPU cost query result missing field: 'instance_type' field does not exist in data result vector
CostModel.ComputeAllocation: Node GPU cost query result missing field: 'instance_type' field does not exist in data result vector
CostModel.ComputeAllocation: Node spot  query result for missing node: cluster-one/aks-nodexyz-23568084-vmss00000j
```
And another warning:
`CostModel: failed to find node for cluster-one/aks-nodexyz-23568084-vmss00000j`

For further testing, I also completely uninstalled Kubecost and removed the storage with the cache. But even after doing a complete fresh installation, rebuilding costs from scratch, the problems are the same and the warnings in the logs occur again.

I hope someone can take a look and give me some feedback.

gz#2127<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2127'>Zendesk ticket #2127</a>)</i>

**Comment by keithhand** [comment]
Hi @andreb89, let me look and see if I can find anything that might have changed. It would be good to confirm that the cost export type you have configured is `Daily export of month-to-date costs`; Is that accurate?

**Comment by andreb89** [comment]
Hi @keithhand thanks for the fast response.
Yes `Daily export of month-to-date costs` is configured in the Azure cost export. Just to be sure, I tried recreating the cost export through the Azure Portal and also via AZ CLI, but the exports of both have the same new structure in the CSV now.

**Comment by marco-giovannini-73team** [comment]
Not sure if might be related but in my Kubecost recently installed in Azure I see the cost calculation is wrong. The cost for recent data (last 2 days) are ok but older data are incorrect. I suspect is related to reconciliation  with cost exporter data. Repairing the ETL bring the data to correct value after after a while the are wrong again.

I was able to validating running the ETL repair I got good calculation I trigger the reconcialiation again with https://xxxxxxx.eastus.cloudapp.azure.com/kubecost/model/etl/asset/reconciliation/run?commit=true and my calculation got messed up again.

After I run ETL repair
https://files.slack.com/files-pri/TE6RTBNET-F03P6G21ACR/screenshot_2022-07-08_at_15.25.47.png

After reconciliation run 
https://files.slack.com/files-pri/TE6RTBNET-F03NWCMG5LL/screenshot_2022-07-08_at_15.49.56.png

**Comment by marco-giovannini-73team** [comment]
My cost exporter has the  following fields

InvoiceSectionName,
AccountName,
AccountOwnerId,
SubscriptionId,
SubscriptionName,
ResourceGroup,
esourceLocation,
Date,
ProductName,
MeterCategory,
MeterSubCategory,
MeterId,MeterName,
MeterRegion,
UnitOfMeasure,
Quantity,
EffectivePrice,
CostInBillingCurrency,
CostCenter,
ConsumedService,
ResourceId,
Tags,
OfferId,
AdditionalInfo,
ServiceInfo1,
ServiceInfo2,
ResourceName,
ReservationId,
ReservationName,
UnitPrice,
ProductOrderId,
ProductOrderName,
Term,PublisherType,
PublisherName,
ChargeType,
Frequency,
PricingModel,
AvailabilityZone,
BillingAccountId,
BillingAccountName,
BillingCurrencyCode,
BillingPeriodStartDate,
BillingPeriodEndDate,
BillingProfileId,
BillingProfileName,
InvoiceSectionId,
IsAzureCreditEligible,
PartNumber,
PayGPrice,
PlanName,
ServiceFamily,
CostAllocationRuleName,
benefitId,
benefitName

and this the job exporter
![Screenshot 2022-07-08 at 16 06 38](https://user-images.githubusercontent.com/95924236/178008442-5588097e-392a-4453-8366-8b1db06a0cf8.png)

**Comment by keithhand** [comment]
Hi @andreb89, can I have you check the cloud integration section diagnostics page and see if there is any information provided there? 
![image](https://user-images.githubusercontent.com/43491549/178075673-e0745304-7c06-4844-aaf4-9e8a49715f5e.png). It would also be helpful to know if you are seeing any adjustments being applied when you visit your Asset reports.

**Comment by andreb89** [comment]
Hi @keithhand 
yes, it shows the information for the Azure cloud integration and also the latest sync status:
![image](https://user-images.githubusercontent.com/78923723/178200290-499ca567-19fd-4f88-8ea7-a0057125f59f.png)

In the Assets page, it shows no adjustments at all (only €0.00), which is strange, since in the past it definitely showed prices being adjusted. But nothing anymore.

**Comment by keithhand** [comment]
Hey @andreb89, thanks for the additional information. Let me pass this along to the engineering team to look into what we have now, and if there is anything else we can get from you, we will reach out. Thanks!

**Comment by Sean-Holcomb** [comment]
@andreb89 can you verify that that the column "InstanceId (InstanceId)" was replaced with "InstanceName". 
Additionally can you check that the date format hasn't changed in the CSV for me?

**Comment by Sean-Holcomb** [comment]
@andreb89 In terms of your second issue. It appears that your nodes are missing the labels `topology.kubernetes.io/region and `beta.kubernetes.io/instance-type` or `node.kubernetes.io/instance-type` can you check if this is the case, and if so is there anything particular about your aks set up that you think might affect this.

**Comment by Sean-Holcomb** [comment]
@andreb89 thank you for the response. I believe I have the solution for billing data ingestion. I will keep looking at the second issue.

**Comment by andreb89** [comment]
@Sean-Holcomb 
Hi, can you give an update here, please?

**Comment by Sean-Holcomb** [comment]
The updated format export is in v1.96 were you able to confirm the fix there?

In terms of the other issue, did the fix to the other issue change it at all.
If not can you run the following query and give me the result?
`/model/assets?window=7d&accumulate=false&filterCategories=Storage&includeCloud=false`

**Comment by andreb89** [comment]
ah, I did not see that the fix was in v1.96
I haven't updated yet, but will try to do so today or tomorrow latest. Then I will give you an update.

**Comment by andreb89** [comment]
@Sean-Holcomb 
So I was finally able to update our Kubecost instance from v1.94.3 to v1.96.0, which really should be tested again, since initially when I upgraded with the v1.94.3 helm configuration values, then the cloud integration did not work. Only when I also manually created the cloud-integration secret, the feature worked. So now I have a Kubecost deployed with 3 different secrets, that all basically contain the same Azure connection information (service-key, azure-storage-config and cloud-integration). Not sure, if this is intended.

But back to the actual issue here, the out-of-cluster Azure costs look overall better now. At least I can see costs in the Assets page, that make sense now:

![image](https://user-images.githubusercontent.com/78923723/189079812-2492248f-93dc-471f-8859-8ea0f33d4e78.png)

Until now (I installed it yesterday), there is also no strange node/cloud storage categorization. So in general, I guess the fix works.

But checking the log of the cost-model container, I still have a lot of error messages, as follows:

- `CloudUsage[]: Build[wlvsX]: QueryCloudUsage error: Configure Azure Storage Failed azure storage config not found`

=> even though it is configured and a secret for it exists as well, the same configuration worked for v1.94.3, the cost exports from the storage can also still be read, not sure what this really means

A collection of error messages from the log, which repeat over time:
```
- could not get account tags for provider []: GetAccountTagsByAccount unimplemented for Azure.
- WRN: ClusterNodes: CPU mode data missing node
- CostModel.ComputeAllocation: PVC info query result missing field: 'storageclass' field does not exist in data result vector
- ClusterLoadBalancers: LB cost data missing ingress_ip
- CostModel.ComputeAllocation: Node CPU cost query result missing field: 'instance_type' field does not exist in data result vector
- CostModel.ComputeAllocation: Node RAM cost query result missing field: 'instance_type' field does not exist in data result vector
- CostModel.ComputeAllocation: Node GPU cost query result missing field: 'instance_type' field does not exist in data result vector
- CostModel.ComputeAllocation: PV bytes result for missing PV: %!s(<nil>)
- CostModel: failed to find node for dev/aks-default-xyz-vmss000123
- Allocation: ComputeAllocation: raw allocation data missing for dev/akswin10000g7/kube-system/csi-azuredisk-node-win-58j8k/azuredisk
- RequestSizing: failed to calculate scaled CPU savings for container aznodecopy: cost per resource hour cannot be <= 0
- RequestSizing: failed to calculate scaled CPU savings for container __unmounted__: cost per resource hour cannot be <= 0
- ETL: ComputeAssets: clusterManagementQuery: Prometheus communication error: 400 (Bad Request) URL: 'http://prometheus.dev-monitor:9090/api/v1/query?query=sum_over_time%28%28avg%28kubecost_cluster_management_cost%29+by+%28cluster_id%29%29%5B0m%3A1m%5D%29+%2A+0.016667&time=1662559280', Request Headers: 'map[]', Headers: '{ Date: [ Wed, 07 Sep 2022 14:01:20 GMT ], Content-Type: [ application/json ] }', Body: '{"status":"error","errorType":"bad_data","error":"invalid parameter \"query\": 1:71: parse error: duration must be greater than 0"}' Query: 'sum_over_time((avg(kubecost_cluster_management_cost) by (cluster_id))[0m:1m]) * 0.016667': retrying
```

**Comment by Sean-Holcomb** [comment]
`CloudUsage[]` logs with this signature are indicative of the failed set ups with service-key and azure-storage-config. Since you have multi-cloud integration the data coming in is correct. In terms of why your other configurations are failing I would need to see your helm values to help diagnose the issue.

**Comment by rossfisherkc** [comment]
Will close this issue for now due to staleness, please don't hesitate to re-open or reach out for help in the future!
