### ISSUE TITLE
Exluded resources from recurring alert if spend threshold is not exceeded

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1535]
**What problem are you trying to solve?**
Limit noise in recurring alerts to resources above a spend threshold.

**Describe the solution you'd like**
The ability to define a spend threshold for a recurring alert.
Example: Customer doesn't care about a namespace consuming $0.95 / day

**Describe alternatives you've considered**

**How would users interact with this feature?**
It would function identical to the efficiency alert option of specifying a spend threshold. UI, Helm, and API

gz#2142<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2142'>Zendesk ticket #2142</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-121) by [Unito](https://www.unito.io)

**Comment by nealormsbee** [comment]
Sounds like a sensible feature to me. Adding to the FE team project backlog.

Out of scope for this ticket, but it might be cool to expand general Allocation/Asset filters to permit "exclude items with totalCost < $X".
