### ISSUE TITLE
Manage underutilized nodes Grafana link goes nowhere

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1536]
**Describe the bug**
When viewing the "Manage Underutilized Nodes" savings report, you can view additional details about the nodes by selecting a node. In the modal that pops up, there is an option to "view metrics dashboard". This should route to a Grafana dashboard but instead opens a new window/tab to the current page.

**To Reproduce**
1. Go to Savings > Manage underutilized nodes
2. Select a node
3. Select "View metrics dashboard"

**Expected behavior**
Should open the node dashboard in Grafana

**Screenshots**
![image](https://user-images.githubusercontent.com/15660532/178203615-dee55f06-a4d5-452e-b349-c5ec3dee9492.png)

gz#2143<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2143'>Zendesk ticket #2143</a>)</i>

**Comment by dwbrown2** [comment]
Thanks for reporting, @srpomeroy! Know what build/version this is on?

cc @Adam-Stack-PM

**Comment by nealormsbee** [comment]
I'm unable to reproduce on `v1.94.3`. @srpomeroy if you happen to have a live link or version info that would be a big help! Otherwise I'll plan to browse the code for anything that looks like it might cause this.

**Comment by srpomeroy** [comment]
I will get some additional details from the customer and report back!

**Comment by nealormsbee** [comment]
Thank you! In the meantime, it looks like this will happen if the client is unable to retrieve the configured Grafana URL from the backend, or if it is simply still waiting for a response. We create the link `target="_blank" href=""`, and then ask the server for the Grafana URL, and apply it to the link after-the-fact.

**Comment by nealormsbee** [comment]
Any update on this one @srpomeroy ?

**Comment by srpomeroy** [comment]
I was unable to solicit any additional feedback. We can close.
