### ISSUE TITLE
Duplicated resources with custom Prometheus

### ISSUE THREAD

**Issue by headyj** [kubecost/cost-analyzer-helm-chart#1537]
**Describe the bug**
It seems that some resources are duplicated, due to the original kubernetes-service-endpoints being also parsed by kubecost:

`kube_pod_container_resource_limits{exported_namespace="my-namespace", job="kubernetes-service-endpoints", namespace="prometheus", pod="my-nginx-55dcdfbb6d-42hf4", resource="cpu", service="prometheus-kube-state-metrics", uid="6200aefa-c378-4ba0-bbdc-2bdb703c4432", unit="core"} 0.5`

`kube_pod_container_resource_limits{job="kubecost", namespace="my-namespace", pod="my-namespace-nginx-55dcdfbb6d-42hf4", resource="cpu", uid="6200aefa-c378-4ba0-bbdc-2bdb703c4432", unit="core"} 0.5
`

the result is that almost all resources are duplicated in "prometheus" namespace

**To Reproduce**

1. Install kubecost
2. Use custom prometheus: https://guide.kubecost.com/hc/en-us/articles/4407595941015-Custom-Prometheus
3. Both "kubernetes-service-endpoints" kube_pod_container_resource_limits and "kubecost" one are used (as well as others)

**Expected behavior**
resources should not be duplicated

**Screenshots**

**Collect logs (please complete the following information):**

Kubecost v1.95.0-rc.1

No helpful information on the logs, seems to be an issue with the filter used by kubecost itself?

gz#2144<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2144'>Zendesk ticket #2144</a>)</i>

**Comment by kirbsauce** [comment]
Thanks for reporting, @headyj.  We'll dig into this right away.

**Comment by jcharcalla** [comment]
@headyj Are you seeing duplicated resources within the Kubecost UI or just in your external Prometheus metrics?

Also, are you running an additional Kube-state-metrics pod outside of Kubecost? Here is [documentation](https://guide.kubecost.com/hc/en-us/articles/4408095797911-Kube-State-Metrics-KSM-Emission#dealing-with-duplicate-metrics-when-a-non-kubecost-ksm-is-present-in-the-cluster) for handling duplicate metrics which occur with more than one KSM deployment.

**Comment by akramwaseem** [comment]
@jcharcalla  -- Based on the documentation link provided above

`
Run a separate Prometheus for Kubecost alone (the default installation behavior of Kubecost) and disable the scraping of Kubecost’s metrics in your other Prometheus configurations.
`
I am running separate Prom for kubecost and there is other Prom which is also running. can you update the documentation where I can either completely disable scraping metrics for the whole kubecost namespace or just the KSM and kubecost Prom ?

I know everyone has a different requirement but having something to start with might help. 

This is what I am trying to do :

```yaml

- job_name: kubecost-metric-drop
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace]
    action: drop
    regex: kubecost

```

**Comment by AjayTripathy** [comment]
That drop information looks correct but must be added to the scraping job on your own Prometheus, not as a separate job, since you're asking the existing job to drop metrics from the kubecost namespace @akramwaseem

**Comment by AjayTripathy** [comment]
@headyj to reduce duplication, if you're using ksmv2 you can set this to true. https://github.com/kubecost/cost-analyzer-helm-chart/blob/6ee0c8bb58664767a6b6efe0123d85e586f568f2/cost-analyzer/values.yaml#L227

**Comment by headyj** [comment]
I was finally able to solve this issue by setting `honor_labels` to `true` on our **internal** prometheus, for `kubernetes-service-endpoints` job (to replace `exported_namespace` key by `namespace`

**Comment by akramwaseem** [comment]
@headyj  -- can you share the job. if possible.
Did you add it as a Job or Added it during the Prometheus deployment ?

**Comment by headyj** [comment]
No I did not add a job (except the kubecost one, as explained on the documentation: https://guide.kubecost.com/hc/en-us/articles/4407595941015-Custom-Prometheus), I just added the `honor_labels: true` to the existing kubernetes-service-endpoints job: 

```
- job_name: 'kubernetes-service-endpoints'
    scrape_interval: 15s
    honor_labels: true
```
because otherwise I was getting namespaces as "exported_namespaces", which caused the duplications

**Comment by Adam-Stack-PM** [comment]
@headyj Closing this out based on your above comment.   

If you need additional help, please open a support ticket [here](https://guide.kubecost.com/hc/en-us/requests/new), and a support engineer will jump on it.

@akramwaseem, also please reach out if we can help.
