### ISSUE TITLE
Support label configuration in filters

### ISSUE THREAD

**Issue by zdenekvicar** [kubecost/cost-analyzer-helm-chart#1539]
**What problem are you trying to solve?**
Kubecost currently provides very nice way of connecting custom labels with those pre-defined in Kubecost. We are using `Team` label connection by providing our custom value `reporting_team` into values.yaml `kubecostProductConfigs.labelMappingConfigs.team_label`.
This works very nice on `allocations.html` page where we can aggregate by this just by selecting `Team`. However we miss this functionality on filters, where I still have to write a custom filter `label=reporting_team:{team}`.

**Describe the solution you'd like**
I would like to be able to select `Team` (and possibly other pre-defined Kubecost labels) the same way as they are available in `allocations.html` with aggregate by function.

**Describe alternatives you've considered**
n/a

**How would users interact with this feature?**
Right now the UI allows users to select filters they want to apply (namespace, label, ...) ... there would be a new filter added called `team` that would be matched with value from custom label. Custom label key could be taken from `kubecostProductConfigs.labelMappingConfigs.team_label` because this possibility is already there.

gz#2153<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2153'>Zendesk ticket #2153</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-122) by [Unito](https://www.unito.io)

**Comment by michaelmdresser** [comment]
Hi @zdenekvicar, I think we already support this functionality in our API, but not on the frontend. If you're an API user, you should be able to pass a parameter like this: `filterTeams={team}`.

However, as you've seen, we aren't currently exposing that as an option on the frontend. Thanks for the report/feature request, this may be a pretty straightforward addition once we get it prioritized. I'm sure @Adam-Stack-PM can keep you posted here.
