### ISSUE TITLE
Save custom savings.html views for later use

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1540]
**What problem are you trying to solve?**
There are ways to save the views for both Allocation and Asset reports so that you can review them later with the same filters applied. I want this same functionality within the savings pages; the most useful would be the filters when selecting container request sizing. 

**Describe the solution you'd like**
The ability to save pre-determined filters on the savings pages.

**Describe alternatives you've considered**
Currently, the filters get applied via the URL, so you can create a report and then bookmark/share the link. 

**How would users interact with this feature?**
Similar to how the reports page works currently.

gz#2149<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2149'>Zendesk ticket #2149</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-123) by [Unito](https://www.unito.io)

**Comment by nealormsbee** [comment]
Thanks Keith!

@teevans I'm putting this on the Backlog of the Front-End Team project so it can be considered for a future release. Let me know if you want to see a different kind of process here.
