### ISSUE TITLE
Review use of kube-state-metrics

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#1547]
**What problem are you trying to solve?**
Kube-state-metrics will become optional in our application yet we ship with it on by default. We should decide how this should be used in our application as there have been requests for upgrading + more configuration https://github.com/kubecost/cost-analyzer-helm-chart/issues/1493#issuecomment-1175121269

**Describe the solution you'd like**
I'm inclined to say that we should move this to off by default, and provide minimal configuration in our application. If users, want more we should place nicely with other ksms. 

**Describe alternatives you've considered**
A fully configurable ksm in the kubecost helm chart.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-125) by [Unito](https://www.unito.io)

**Comment by kirbsauce** [comment]
@dwbrown2 , just to clarify, SOME version of KSM is required, no?  There is some confusion based on "Kube-state-metrics is now optional in our application".  Users are referencing this issue asking if they can disable KSM.

**Comment by AjayTripathy** [comment]
I would call the optionality in alpha state and note that it is not recommended for production (yet). In particular, downtime in kubecost becomes a lot more relevant than when ksm runs, because pod uptime tracking moves from ksm to kubecost.
