### ISSUE TITLE
it is not clear how to enable grafana for summary dashboard

### ISSUE THREAD

**Issue by romankydybets** [kubecost/cost-analyzer-helm-chart#1562]
Hi team,
It is not clear what should be configured for using this feature
<img width="1338" alt="Screenshot 2022-07-15 at 15 56 36" src="https://user-images.githubusercontent.com/27759761/179228052-11975e5b-1fe4-4c0f-993f-5fdbb6a2ca0d.png">

i am using grafana which was provided by your team,
and it is accessible 

gz#2192<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2192'>Zendesk ticket #2192</a>)</i>

**Comment by dwbrown2** [comment]
Thanks for reporting, @Kydybets! We just noticed this issue last night on the latest release and are now investigating. 

Note: dupe of private issue https://github.com/kubecost/cost-analyzer-frontend/issues/903

**Comment by keithhand** [comment]
Hey @romankydybets, the latest release (v1.96.0) should have a fix for this issue. Can you upgrade and test if it resolves this for you?

**Comment by romankydybets** [comment]
@keithhand 
thank you for update
right now it is forwarding to grafana,
but for some reason I start facing the issue `origin not allowed` for each view and even when I try to login
this is example of response from one of the view
```
Object
status:403
statusText:""
data:Object
message:"origin not allowed
"
error:""
response:"origin not allowed
"
config:Object
url:"api/ds/query"
method:"POST"
data:Object
requestId:"Q102"
retry:0
headers:Object
hideFromInspector:false
message:"origin not allowed
"
```

**Comment by keithhand** [comment]
@romankydybets, what is the ingress controller you are using? I would be curious to see if access/error logs might indicate what is happening to deny the request.

**Comment by romankydybets** [comment]
@keithhand  nginx ingress controller of the helm chart version "4.1.1"

**Comment by keithhand** [comment]
@romankydybets, do you notice any logs from the nginx ingress controller that relate to this? https://kubernetes.github.io/ingress-nginx/troubleshooting/#check-the-ingress-controller-logs

**Comment by keithhand** [comment]
@romankydybets, are you using an external Grafana or the Grafana bundled with Kubecost?

**Comment by romankydybets** [comment]
@keithhand  sorry for the late response, 
I just test on version 1.96.0, and everything works perfect,

I am using bundled Grafana and Prometheus, 
Unfortunately for Prometheus, not yet find the way add target without breaking  existing metrics related to k8s
