### ISSUE TITLE
Summary numbers for Efficiency and Savings are unclear

### ISSUE THREAD

**Issue by kc-adawson** [kubecost/cost-analyzer-helm-chart#1563]
**What problem are you trying to solve?**

Had multiple calls this week that have called out our Savings numbers not adding up/ overall efficiency score not being clear. People are genuinely curious why these numbers seem to not add up.

On https://demo.kubecost.xyz/, we say there is a 3.5% efficiency score, but we also show that the idle over 14 days has been $112 dollars out of ~175. The prospect asked why it said 3% if that would make it more like ~35%, and its not totally clear what the calculations are to get 3% efficiency.

![](https://user-images.githubusercontent.com/101200254/179293981-6cecac0f-7399-4496-b9a0-be07f9191422.png)

On the Savings page, the lower recommendation numbers don't add up to the top number.

![](https://user-images.githubusercontent.com/101200254/179294023-f07b3299-7bc7-4969-867e-55397a3ea988.png)

**Describe the solution you'd like**
It would be great if we had some kind of "How are we getting this number?" type of tool tips that explain the reason why it may not add up and what the numbers behind it are, or for it to add up properly on some of the main high level module pages (like the Savings Page)

**Describe alternatives you've considered**
Alternative is to leave it how it is and rely on the customer taking our word for it.

**How would users interact with this feature?**
As they do today.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-127) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
Re: overview -- I believe @nealormsbee is looking at this now. Summary is that cost efficiency exposed both workload idle + cluster idle. I see a really opportunity for us to have more "learn more" tooltips that deep link to relevant docs, e.g. the OpenCost spec. I say that because these are complex topics...

Re: savings -- is the tooltip in the top card helpful at all? 

cc @Annalillie as FYI

**Comment by Annalillie** [comment]
@dwbrown2 I agree. I think a "learn more" that link to docs will help users really understand how we are calculating these numbers. A quick "Efficiency is determined by calculating X and X. Learn more." I see Neal may be on this now. If this continues to be a UX issue after his coding magic, I'd love to brainstorm alternative ways to present this information to users so they aren't inherently having to rely on a tooltip here.

**Comment by dwbrown2** [comment]
I dit it! Kinda random example, but I think Google flights does this in a pretty slick way...

<img width="440" alt="image" src="https://user-images.githubusercontent.com/298359/179312948-8ddb90c5-3f2d-4f83-adcf-0d5c2c13e829.png">

**Comment by Annalillie** [comment]
Thats a great example, exactly like that. A brief overview with the option to read more in-depth in desired.

**Comment by kc-adawson** [comment]
> Re: savings -- is the tooltip in the top card helpful at all?

<img width="1059" alt="2022-07-16_08-46-31" src="https://user-images.githubusercontent.com/101200254/179355469-c36012c4-20cd-4877-8cbf-46c58394e2d7.png">

The tool tip makes sense that the total is "probability adjusted", but first impression to most is the Savings sub-report numbers on the bottom cards would add up to the total summary card up top. If you look at the top 4 savings blocks alone, they add up to over $120+ in savings, vs the $730 displayed up top.

I think a simple adjustment that could be good is change the top green savings number to be the total sum of all the sub-savings reports, and maybe provide an "probability adjusted savings" as a secondary number. If we did that in this screenshot scenerio, it would show more savings which is consistent with the sub-reports below.

I think the fact that its not consistent is the issue, it causes people to become skeptical about the underlying numbers, even when everything is how it is for specific reasons.

**Comment by kc-adawson** [comment]
CC @jessegoodier and I worked on a rough mock up on layout ideas - If we broke out the savings by category, it could make the overall report clearer. 

<img width="1447" alt="2022-07-18_10-26-08" src="https://user-images.githubusercontent.com/101200254/179534140-05b022cf-65d0-498b-aa0d-f39a44d06cea.png">

**Comment by Adam-Stack-PM** [comment]
Hi @kc-adawson and @jessegoodier 

Here is a link to a document our design consoltant is using to update the savings UX.  

Based on the scope of our engagement want to keep the scope tight.  

However, if you could add any future ideas or context at the bottom, that would be very helpful.  

https://docs.google.com/document/d/1_Vadch2sTTbeTWjE2a_b7XfBr3AHhpXoTB3kSTr_gE8/edit#heading=h.48eulx5rs2l

**Comment by AjayTripathy** [comment]
Here are my thoughts:
* I think it's pretty clear from the feedback and tickets that "probability adjusted savings" shouldn't be way up at the top. Those numbers aren't summable, so my opinion is we should stop summing them if it's causing confusion.
* Idle and efficiency are separate concepts, so let's just stop pages from mixing them...

**Comment by dwbrown2** [comment]
A big part of these numbers not adding up is because we attach a savings value to optimizations like removing abandoned pods and right-sizing applications. These indirectly allow for savings, because teams can then right-sizing infrastructure, but don't directly lead to savings. 

I have ideas on how we can better present, but would love to hear your input!

**Comment by Adam-Stack-PM** [comment]
I would be hesitant to lose the total savings. It is clear and tangible for a business user.  This point of view was inspired by Mat Wilcox related to a feature gate idea I had.

Webb, to ensure I understand correctly to get the full savings, the user must first act on the initial recommendations like "right-sizing applications".  Then these unlock additional savings opportunities like right-sizing infrastructure? 

If this is the case could see a fun and very engaging UI that shows the estimated 2nd step savings but have it locked with a hover state.   It could be subtle, like a locked icon in a table view.

**Comment by kc-adawson** [comment]
Hey team, following up on this since i've heard it brought up a few times again in the last week. Users are getting tripped up by the "estimated monthly savings" number at the top not matching the sub-report 'save up to' totals on the savings page. Its not clear to users why it would be a different number up top, and can cause distrust in the product. 

Would it make sense to replace the "Estimated Monthly Savings" (aka Probability Adjusted) summary total with just a sum of all the "Save Up To" reports below? We could label it as 'Save Up To $X". 

<img width="1212" alt="2022-12-13_09-39-52" src="https://user-images.githubusercontent.com/101200254/207364547-224f616c-347e-47ac-985a-786991ad2f41.png">

**Comment by AjayTripathy** [comment]
@nealormsbee is it relatively easy to have this estimated number just equal the sum of all numbers on this page?

**Comment by dwbrown2** [comment]
This is exactly what we had previously and it leads to a whole host of problems, e.g. double counting. An an example, right-sizing an application doesn't actually drive savings. Instead it creates room for other opportunities, i.e. right-sizing underlying infra.

**Comment by AjayTripathy** [comment]
Ok, I do think this remains important to think through or explain more clearly since I hear this fairly often. Any other thoughts on how to make this clearer?

**Comment by nealormsbee** [comment]
Maybe an overly-simple idea: Could we pull the text that's in the tooltip *out* of the tooltip, and onto the main page? Then have *more* detailed info in the tooltip?

Something like

```
-------------------------------------------------------------------------------------------------------------------------
                                   <h1>Possible Savings $3,141.59</h1>
 <p>Estimated savings are probability-adjusted and include both Kubernetes and external cloud insights</p><info-icon />
-------------------------------------------------------------------------------------------------------------------------
```

Hovering on the info icon shows tooltip text:

```
Savings strategies often overlap. For example, workload savings cannot be realized from both right-sizing the workload, and deleting it (if it is considered abandoned). Total savings is revised downward (probability-adjusted) to account for the fact that multiple strategies may claim the same savings.
```

IMO probability-adjusting the total downward is correct, so that we don't inflate total savings projections when multiple strategies try to squeeze the juice from the same orange. We just need to figure out how to make it more obvious that's happening. We could even put a full explanation of the downward-revision outside the tooltip, although that feels excessive to me.

**Comment by Annalillie** [comment]
@nealormsbee i like this idea of having a brief description present on the page with the tooltip pointing to more detailed information.

**Comment by nealormsbee** [comment]
@Adam-Stack-PM do you think we should consider this for a v1.100 improvement? Seems like a piece of longstanding confusion that we can try to resolve for users.

@dwbrown2 what do you think of the proposal above? Is there another direction you think we should take this?

**Comment by Adam-Stack-PM** [comment]
@nealormsbee Would be great to push and improve the user experience in v1.100. If @dwbrown2, is ok with the proposed solution or can help us build on it lets go for it.

**Comment by Adam-Stack-PM** [comment]
@dwbrown2, @kwombach12, Friendly Ping. Wanted to get this issue back on your radar when you have time.

**Comment by jessegoodier** [comment]
Good thread from today on efficiency: https://kubecost.slack.com/archives/G01MN4R06MB/p1674166793088819

The tooltip for the total on /savings is not working on nightly currently

Should savings number from overview match the savings banner? http://nightly.kubecost.io:9090/overview

**Comment by dwbrown2** [comment]
@kwombach12 you ok to take a pass then we can review later this week?

**Comment by kc-adawson** [comment]
Closing issue -I think this has been addressed/there are more relevant discussions outside of this thread.
