### ISSUE TITLE
Settings durable storage debug section always asks for upgrade

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1564]
**Describe the bug**
The durable storage section of the settings page displays "Product upgrade required to enable long-term metric retention." when on an enterprise version with Thanos running.

**To Reproduce**
1. Deploy Enterprise Kubecost with Thanos
2. View [`/settings`](http://a33fe579340b346b6a7badbaa503699d-79357105.us-east-2.elb.amazonaws.com:9090/settings)
3. See error

**Expected behavior**
Durable storage debug information is shown when enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/43491549/179636569-77c98741-e0d1-4221-a72f-2acd59c4f06f.png)

gz#2133<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2133'>Zendesk ticket #2133</a>)</i>

**Comment by dwbrown2** [comment]
cc @teevans looks like this is statically set

I believe we need to decide on the exact flag where this is shown as enabled/disable? i.e. is this when you have a bucket key attached, show successful writes, or something else. @mbolt35 might have ideas

**Comment by teevans** [comment]
@wolfeaustin - Do you have any context on this? It looks like it's checking if thanos is enabled, but I'm not sure what the actual logic behind it is.

**Comment by wolfeaustin** [comment]
@teevans yea it looks like there isn't any existing logic around this. I'll put something together to remedy.

**Comment by teevans** [comment]
I would think it would be if they have durable storage enabled.

**Comment by Adam-Stack-PM** [comment]
Added the v1.96 label for the bug. Please update if you have other plans.

**Comment by teevans** [comment]
@wolfeaustin - Can you knock this out?
