### ISSUE TITLE
Option to ignore last 2 days if CUR enabled

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1566]
**What problem are you trying to solve?**
Because enabling a cost & usage report will result in discrepancies for the last 48 hours (time it takes to post CUR data), I would like an option to disable non-reconciled data so that it doesn't show up in my UI.

**Describe the solution you'd like**
An option to ignore dates that have not yet been reconciled against my CUR.

**Describe alternatives you've considered**
Manually adjusting the window of a report to ignore dates

**How would users interact with this feature?**
An application setting for "ignore_non_cur_dates" or possibly a API/report specific setting

gz#2216<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2216'>Zendesk ticket #2216</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-128) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
Thanks for sharing Keith! Have a sense for what pages this most applies to? Would custom date ranges be a good way to tackle?

**Comment by keithhand** [comment]
This would primarily be for Asset and Allocation reports. A custom date range would work, but because we need to set an actual date, there's not a way to customize reports with a window such as "last seven days minus today and yesterday."

**Comment by AjayTripathy** [comment]
I think we could quickly build that as a dropdown and then have the user save that dropdown as their default report? Don't think we need to add additional configuration.
