### ISSUE TITLE
Cost treemap UI bug

### ISSUE THREAD

**Issue by RomanDvorsky** [kubecost/cost-analyzer-helm-chart#1571]
**Describe the bug**
Unable to see cost efficiency and costs on the graph - the menu get hidden.

**To Reproduce**

1. have multiple small namespaces
1. Show cost treemap graph
1. Try to show costs for the bottom namespaces

**Expected behavior**
Shown menu position will be changed depending on the position the control so it is always visible, bottom controls will have menu on the top, right control will have it on the left...

**Screenshots**
![image](https://user-images.githubusercontent.com/36188474/180140708-cea3cfdd-176f-4e95-8607-8193c7e0086c.png)

**Collect logs (please complete the following information):**
no logs needed - kubecost version is 1.95.0

gz#2230<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2230'>Zendesk ticket #2230</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-130) by [Unito](https://www.unito.io)

**Comment by Adam-Stack-PM** [comment]
@RomanDvorsky Thanks for this bug and clear explanation.  We are working on a big frontend update and will get this on our roadmap. 

@teevans  This could be a good candidate to fix as we migrate to the new design system.
