### ISSUE TITLE
Ability to 'exclude' certain namespaces (kube-system) in Request Rightsizing

### ISSUE THREAD

**Issue by kc-adawson** [kubecost/cost-analyzer-helm-chart#1573]
**What problem are you trying to solve?**
On a GKE cluster, the Kube-system namesapce can not be resized. Within the Kubecost rightsizing section, many of my top savings are kube-system, which are counted in Savings but can not actually be re-sized.

![](https://user-images.githubusercontent.com/101200254/180258801-36c2dcbc-a6f4-4164-afd0-49539bff059e.png)

**Describe the solution you'd like**
Ability to "exclude" or filter out namespaces from the Request Sizing recommendations, specifically the kube-system namespace which can not be resized.

**Describe alternatives you've considered**
You can filter to specific namespaces one by one to remove kube-system, but it would be nice to see only the groupings you care about, and filter out ones that can not be resized due to provider or business-related constraints

**How would users interact with this feature?**
In the existing filter on the Request Sizing page, allow an "!=" operator. Or, a checkbox that says "remove Kube-system containers"  if we want to contain it to only one excluded namespaces.

![](https://user-images.githubusercontent.com/101200254/180260546-c99eb8a2-5eac-4137-9c32-c09d3d6a2358.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-132) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
Definitely see the need for this! @michaelmdresser would we be close now with new filters implementation?

**Comment by michaelmdresser** [comment]
Yes, we're close. The request sizing API will have to be updates to accept the new filters (should be straightforward) and then the frontend will have to be updated (similar to https://github.com/kubecost/cost-analyzer-frontend/issues/925).

**Comment by michaelmdresser** [comment]
Request sizing API V2 supports both V1 and V2 Allocation filters. Documentation PR explaining: https://github.com/kubecost/docs/pull/324

Now we just need frontend updates to request sizing. See https://github.com/kubecost/cost-analyzer-frontend/issues/1018. Another issue may be warranted to change the special "filter" control window that we use to make V2 filters. That aligns with https://github.com/kubecost/cost-analyzer-frontend/issues/925 as I noted before.

**Comment by kc-adawson** [comment]
This now works! Closing issue.
