### ISSUE TITLE
Unknown storage class

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#1575]
**Describe the bug**
When drilling into "Disk" assets the storage class is always displayed as "Unknown". This appears to happen with volumes from all cloud providers and I have reproduced it using Kubecost `1.95.0`. This bug report is in reference to Zendesk ticket [2191].(https://kubecost.zendesk.com/agent/tickets/2191)

Screenshot showing "Unknown" Storage class.
<img width="1279" alt="Screen Shot 2022-07-20 at 3 50 36 PM" src="https://user-images.githubusercontent.com/17748044/180307656-e9696a77-9974-4e40-99c7-b51db1f6677b.png">

When looking at the har dump there does not appear to be any "Storage Class" returned in the assets query for the volume selected. 
<img width="1409" alt="Screen Shot 2022-07-21 at 4 20 22 PM" src="https://user-images.githubusercontent.com/17748044/180308545-16af7f1e-24bf-46f7-9f95-5bfa1fc0dea8.png">

**To Reproduce**
1. Go to the 'Assets' page on the [test cluster](http://a33fe579340b346b6a7badbaa503699d-79357105.us-east-2.elb.amazonaws.com:9090/assets?agg=type&context=W10%3D).
2. Aggregate by 'type'.
3. Drill into 'Disk'
4. Click on any of the disks/volumes to bring up the details page and note the 'Storage Class' field will report "Unknown"

**Expected behavior**
Display a storage class if known.

**Collect logs (please complete the following information):**
Har file:
[Unknown_Storage_class.har.zip](https://github.com/kubecost/cost-analyzer-helm-chart/files/9162597/Unknown_Storage_class.har.zip)

**Comment by AjayTripathy** [comment]
Hey @jcharcalla thanks for this! I don't think this is necessarily on the FE folks; the api doesn't return this data so it should probably be assigned to @sundeepghuman for further traige.

**Comment by Adam-Stack-PM** [comment]
@AjayTripathy, While on support rotation, could you take the first pass at assigning this bug a priority p0,1,2)?

**Comment by avrodrigues5** [comment]
Closing this issue as v1.97 forth has storage class information in Disk drilldown. 
![Screen Shot 2022-09-19 at 4 18 32 PM](https://user-images.githubusercontent.com/11470561/191135663-6935adf4-924c-49a4-89ba-6ef964c75499.png)
![Screen Shot 2022-09-19 at 4 18 36 PM](https://user-images.githubusercontent.com/11470561/191135666-eb7cad1a-15d4-42b6-845f-3f973be72a91.png)
