### ISSUE TITLE
Left over Cloud provider after removal from the cloud-integration.json

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#1576]
**Describe the bug**
A customer has removed a GCP entry from the `cloud-integration.json` used for [multi-cloud integrations](https://guide.kubecost.com/hc/en-us/articles/4407595968919-Setting-Up-Cloud-Integrations) and after doing so the "Cloud Integrations" section of the "diagnostics" page now shows a generic GCP "Cloud Provider" in its place. They are currently running version `1.95.0`. 

A Har dump of the page shows the generic GCP "Cloud Provider" as `cloud: {"": {cloudConnectionStatus: "Missing Configuration", providerType: "GCP",…},…}`.

In addition to the Har file, we have verified that the item is not configured in `/var/configs/gcp.json` or `/var/cloud-integration/cloud-integration.json`.  These additional details can be found in Zendesk ticket [2181](https://kubecost.zendesk.com/agent/tickets/2181)

**To Reproduce**
1. Define multiple cloud providers in the `cloud-integration.json` file.
2. After a few hours remove one from the `cloud-integration.json` file.
3. See error

**Expected behavior**
After removal the only the existing integrations are listed.

**Screenshots**

"Cloud Provider" on the diagnostics page. Note that it says it was synchronized with the others.
<img width="1003" alt="Screenshot 2022-07-19 at 15 39 41" src="https://user-images.githubusercontent.com/17748044/180313278-0f3c6ccf-6695-4632-8d06-5c753093c37e.png">

From the HAR dump, the "Missing Configuration" behind the "Cloud Provider" shown. 
<img width="1336" alt="Screen Shot 2022-07-21 at 4 55 29 PM" src="https://user-images.githubusercontent.com/17748044/180313735-254d6afc-7e54-4e61-9b22-701651db4e30.png">

**Collect logs (please complete the following information):**
Additional Logs, Har files, and more can be found in Zendesk ticket [2181](https://kubecost.zendesk.com/agent/tickets/2181)

**Comment by jcharcalla** [comment]
If there is an additional location I should check for left over configuration details let me know.

**Comment by teevans** [comment]
@Sean-Holcomb - I believe this is something we've talked about. Didn't I commit to removing the blank ones from the FE?

**Comment by Adam-Stack-PM** [comment]
Lets try and get a priority set for this (p01,2,3).

**Comment by Sean-Holcomb** [comment]
Yes you did, I am not sure when a regression would have happened

**Comment by teevans** [comment]
@Sean-Holcomb  - Looks like AWS and GCP both have different values for those attributes. GCP returns "", while AWS returns "_" - So I'll need to account for both. PR opening soon.
