### ISSUE TITLE
External costs column shown on the details page, and does not match the "Cloud Costs" tile.

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#1577]
**Describe the bug**
After [1.94.0](https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.94.0) where the release notes state "Removed External Costs column from the totals row", should the "External" column still be displayed on the details page? It appears to alway show $0.00 even when the "Cloud Costs" tile shows a dollar amount or when `&external=true` is added to the URL.

**To Reproduce**
1. Go to our [test cluster](http://a33fe579340b346b6a7badbaa503699d-79357105.us-east-2.elb.amazonaws.com:9090/details?name=kubecost&type=namespace)
2. Go to the "cost allocation" page
3. Aggregate by namespace and drill into one to find the details page.

**Expected behavior**
It's not clear to me what the expected behavior is on this.

**Screenshots**
External column on the details page:
<img width="1412" alt="Screen Shot 2022-07-21 at 5 15 05 PM" src="https://user-images.githubusercontent.com/17748044/180317706-ff352d4a-50ef-45ef-9366-72f326d64cda.png">

Cloud costs tile from the same page showing a dollar amount that does not match the $0.00 in the External column.
<img width="402" alt="Screen Shot 2022-07-21 at 5 26 07 PM" src="https://user-images.githubusercontent.com/17748044/180318018-f645b1a1-3c51-4698-a752-3d198f55595c.png">

**Comment by Adam-Stack-PM** [comment]
@jcharcalla Thanks for reporting this.  Side note, I unassigned Thomas. We are trying to use that field for when items have been scheduled. 

@teevans Could you get this reviewed and assign it a priority for an upcoming release (p0,1,2)?

**Comment by teevans** [comment]
@wolfeaustin - Can you take a look at this and see what's going on here?

**Comment by Adam-Stack-PM** [comment]
@wolfeaustin, Any update on this item? Your making great progress on open items. Thanks for the hard work.

**Comment by wolfeaustin** [comment]
@Adam-Stack-PM [this](https://github.com/kubecost/cost-analyzer-frontend/pull/964) should take care of it
