### ISSUE TITLE
Make LB estimates per-provider and more accurate pre-reconciliation

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#1578]
**Describe the bug**
When drilling into the cost allocation details page, the estimated costs for AWS load balancers prior to CUR reconciliation are inflated ($2 vs $0.60). This was seen in `1.95.0`.

**To Reproduce**

1. Go to the [test cluster](http://a33fe579340b346b6a7badbaa503699d-79357105.us-east-2.elb.amazonaws.com:9090/details?name=kubecost&type=namespace)
1. Click on the "cost allocation" page and drill into the details page of a namespace with a load balancer.
1. See error

**Expected behavior**
Better estimates.

**Screenshots**
Load balancer cost of $2.34 on the 19th vs an average of $0.60 on prior days after reconciliation.
![](https://user-images.githubusercontent.com/17748044/180321365-3a895d91-c623-4ef3-9ad2-cde19e025099.png)

Load balancer shown in blue.
![](https://user-images.githubusercontent.com/17748044/180321377-52666978-b09c-4ba7-87b0-ab17a5b44d1a.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-133) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
This is not a frontend bug, also note the estimates are off for AWS.

**Comment by dwbrown2** [comment]
@AjayTripathy can you share recommended next steps?

**Comment by Adam-Stack-PM** [comment]
@AjayTripathy When you identify the next steps, could you also label this issue with (P0,1, or 2)?

**Comment by AjayTripathy** [comment]
Next steps would be to come up with an algorithm to refine estimates for AWS and Azure on the CUR. Perhaps a small task for v1.97?

**Comment by Adam-Stack-PM** [comment]
@jcharcalla, have added this to the list of items we are considering for v1.97.

**Comment by jcharcalla** [comment]
I have a customer seeing a similar issue with network costs on GCP.

Is it related to this issue or should I file an additional GH issue?
 
![Screen Shot 2022-09-29 at 11 28 31 AM](https://user-images.githubusercontent.com/17748044/193078587-6d3924fc-0711-42f3-ac5a-34f5be7ca7f7.png)

**Comment by AjayTripathy** [comment]
1. I think our LB estimates are just based on GCP pricing or something and we need to do estimates on a per provider basis.
2. Subnet classification has to happen to get more accurate network pices in GCP. https://github.com/kubecost/cost-analyzer-helm-chart/issues/1720#issuecomment-1281655132
