### ISSUE TITLE
Strange numbers from reconciliation on Azure

### ISSUE THREAD

**Issue by Sean-Holcomb** [kubecost/cost-analyzer-helm-chart#1579]
User reports:
Not sure if might be related but in my Kubecost recently installed in Azure I see the cost calculation is wrong. The cost for recent data (last 2 days) are ok but older data are incorrect. I suspect is related to reconciliation with cost exporter data. Repairing the ETL bring the data to correct value after after a while the are wrong again.

I was able to validating running the ETL repair I got good calculation I trigger the reconcialiation again with https://xxxxxxx.eastus.cloudapp.azure.com/kubecost/model/etl/asset/reconciliation/run?commit=true and my calculation got messed up again.

After I run ETL repair
https://files.slack.com/files-pri/TE6RTBNET-F03P6G21ACR/screenshot_2022-07-08_at_15.25.47.png

After reconciliation run
https://files.slack.com/files-pri/TE6RTBNET-F03NWCMG5LL/screenshot_2022-07-08_at_15.49.56.png

gz#2233<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2233'>Zendesk ticket #2233</a>)</i>

**Comment by Sean-Holcomb** [comment]
@marco-giovannini-73team I have created a new issue for you because I don't think what you are seeing is related to the issue you originally commented on. I agree that your issue is likely related to reconciliation. What kind of adjustment numbers are you seeing for on the Asset page. Can you find the resources in Azure's cost explorer and ensure that the number are not being correctly adjusted?

**Comment by sundeepghuman** [comment]
@Sean-Holcomb can you get the additional information from the original reporter here so we can get this fixed in v1.97

**Comment by marco-giovannini-73team** [comment]
This issue was related to the misconfiguration of the currency between Kubecost and cost export. Kubecost was using US dollars but cost export is in INR.

**Comment by Sean-Holcomb** [comment]
Thank you Marco, glad it worked out for you!
