### ISSUE TITLE
Find and update any recommendations that conflict with #1581 update 

### ISSUE THREAD

**Issue by Adam-Stack-PM** [kubecost/cost-analyzer-helm-chart#1582]
We should ideally find any recommendations that conflict with this throughout our docs. Items changed in PR (review PR after merged to ensure additional changes where made)

Default values for Kubecost Helm chart
FOR THE EASIEST UPGRADE PATH, DO NOT COPY THIS FILE AS YOUR OWN values.yaml.
ONLY SET THE VALUES YOU WANT TO OVERRIDE IN YOUR values.yaml.
Source: https://github.com/kubecost/cost-analyzer-helm-chart/pull/1581

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-136) by [Unito](https://www.unito.io)

**Comment by bstuder99** [comment]
Can you be more specific about what we should be looking for in the docs and how we issue corrections? I see about 20 articles that mention a values.yaml, but what else is required to warrant a correction? Does that warning we've added to the Cost Analyzer Helm Chart need to be duplicated on every page?

**Comment by dwbrown2** [comment]
Definitely want to get eng input here, but IMO any time we say to "copy values.yaml" or duplicate our full values.yaml it can lead to upgrade issues later. I'd call this P2, don't mean to create a firedrill
