### ISSUE TITLE
Add the option to filter by non-standard aggregation types

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1583]
**What problem are you trying to solve?**
Within the Allocation report, if you would like to filter by certain aggregation types that are based on labels (Product, Team, Owner, etc.), you have to choose to filter based on the label, rather than the aggregation.

**Describe the solution you'd like**
A way to select "Filter by product:cost-analyzer"

Describe alternatives you've considered**
If you know how the aggregation type is formed, you can specify that label to filter on. For example, "Filter by label app:cost-analyzer"

**How would users interact with this feature?**
Added "Filter" options within the report setting menu

gz#2235<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2235'>Zendesk ticket #2235</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-137) by [Unito](https://www.unito.io)

**Comment by clekas-fff** [comment]
This would be great. It would make sense for the group by options and the filter options to match since it's a pretty common use case to group by something, then filter to only it and remove the grouping to drill down.

**Comment by Adam-Stack-PM** [comment]
@keithhand Thanks for this idea.  Also, thank you @clekas-fff for the additional feedback.  We have this categorized and will consider it for an up coming release.
