### ISSUE TITLE
Add support for Azure in the Orphaned Resources savings report

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1585]
**What problem are you trying to solve?**
Identify disks and IP addresses in Microsoft Azure that are not currently attached.

**Describe the solution you'd like**
Azure support on the Orphaned Resources savings page.

**Describe alternatives you've considered**
I manually identify resources via the Azure API, CLI, or UI.

**How would users interact with this feature?**
Disks and IP addresses would be populated on the savings page.

gz#2238<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2238'>Zendesk ticket #2238</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-138) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
+1, would just need to see if the same APIs exist. I'm guessing they do.
