### ISSUE TITLE
Fine-grained contractual discount specification

### ISSUE THREAD

**Issue by clekas-fff** [kubecost/cost-analyzer-helm-chart#1590]
**What problem are you trying to solve?**
Negotiated discounts often apply to more than just compute, but they apply at different rates.

**Describe the solution you'd like**
It would be useful to be able to specify different discounts for different types of resources (e.g. on-demand compute, RIs, CSPs, spot instances, networking, S3).

**Describe alternatives you've considered**
Without this, the effects of these discounts need to be mentally computed and applied.

**How would users interact with this feature?**
Settings menu - specify one time.

gz#2244<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2244'>Zendesk ticket #2244</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-140) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
@clekas-fff this should be supported with our bill reconciliation feature once you integrate with a cloud provider!

**Comment by clekas-fff** [comment]
@dwbrown2 That's an awesome feature, but unfortunately it doesn't address the situation of negotiated discounts that show up as a credit at the end of the month (a credit which can even appear on another account's bill).

**Comment by dwbrown2** [comment]
@clekas-fff it actually should account for end of month adjustments, do you have a specific scenario you're encountering that you need help with?

**Comment by clekas-fff** [comment]
@dwbrown2 We get end of month adjustments in the form of a non-itemized rebate that:
- isn't broken down by account
- isn't broken down by service
- appears on a bill that we don't ingest

For those reasons, I don't think that Kubecost's bill ingest functionality will be able to correct for these other negotiated discounts.

**Comment by AjayTripathy** [comment]
The non-itemized rebate is a little tricky to handle but I think this is a cool idea to add to our "Advanced Reports" feature. cc-ing @teevans and @wolfeaustin for visibility-- what do you all think of applying constants or user-defined transformations in Advanced reports?

@clekas-fff while our frontend team explores that, maybe there is also something we can do to handle a non-itemized rebate automatically. Do you happen to know how AWS codes it for you in the CUR?

**Comment by clekas-fff** [comment]
@AjayTripathy I've just learned that AWS has something called a billing policy that actually might achieve what we need it. It sounds like it lets us hard-code some discounts, which it applies when generating the CUR.

**Comment by clekas-fff** [comment]
The billing policy worked for the EC2 pricing, but not for:
- S3
- Data transfer out
- intr-regional data transfer
- EBS? I can't really tell from reading the line entry in kubecost if the negotiated discount here is getting applied

**Comment by AjayTripathy** [comment]
Thanks for that feedback @clekas-fff . It sounds like there are transformations we potentially want to apply on our side to data returned by Athena/Prometheus. cc @teevans -- sounds like a good feature for advanced reports?

**Comment by dwbrown2** [comment]
How is this currently showing up in the CUR for these others services? A credit that isn't associated with any other service?

**Comment by clekas-fff** [comment]
We used to get a credit not associated with any other services, but now we
see notes (-XX.XX%) in the title of the line-item pricing in the AWS bill.
It looks like with this bill version we do get the discounts coming in
through the CUR, though that isn't shown to us directly in kubecost like
the SP and RI discounts are. It looks like our network discounts might not
be coming in, but we're working through some issue there, so that could
also be a red herring.

**Comment by mbolt35** [comment]
Thanks for the excellent feature idea. We'll have  @Adam-Stack-PM add it to our roadmap ideas list. It looks like you have a support issue in Zendesk already if you need further support.

**Comment by chipzoller** [comment]
Stale. Closing.
