### ISSUE TITLE
test alert not sending email to recipient 

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1592]
**Describe the bug**
Email not being sent when creating an alert to recipient specified. 

**To Reproduce**
1. Navigate to Alerts > + CREATE ALERT
2. set Cost Threshold to any number (e.g. 1)
3. Under add recipient, add your email and click button "TEST ALERT"

**Expected behavior**
I expect it to send me an email.

**Additional Info**
I can confirm this feature worked in version 1.93 (back on may 25th). I was using the free version of kubecost.

**Comment by mbolt35** [comment]
@mmurph3 Not sure if this is related, but make sure you hit enter after specifying your email address:

![image](https://user-images.githubusercontent.com/334480/181365927-2731f977-1de3-4214-9a4e-a633ebd3b090.png)

This is something I didn't do originally, and was seeing the following:
![image](https://user-images.githubusercontent.com/334480/181366380-8ebd0ab4-363b-496f-be04-bd656e26f5ac.png)

If that wasn't the issue, definitely check spam filters as well, as I believe we've added some newer formatting that may be tripping up email services.

**Comment by Adam-Stack-PM** [comment]
@teevans Bolts comment relates to a small UI issue that has come up a few times. May be worth looking at.

**Comment by dwbrown2** [comment]
+1 on Adam's and Bolt's comment. @Annalillie has a great UX suggestion here!

**Comment by Annalillie** [comment]
Thanks for tagging me @dwbrown2, I remember reading this in another issue. In regards to @mbolt35 and @Adam-Stack-PM comment, this is definitely a UX problem. A physical action would be great here to eliminate addresses not being saved, such as an "add" icon. I also think notifying users to check spam could work as microcopy if alerts are being sent there. I'll brainstorm a few different flows for this and shoot it you guys way for feedback.

**Comment by Annalillie** [comment]
Yes! Thanks for that reminder. I'll run with this flow for the time being.

**Comment by mmurph3** [comment]
@mbolt35 it works - It was a user error. I didn't hit enter after entering the email. Should I close this out?

**Comment by Adam-Stack-PM** [comment]
Thanks @Annalillie, Let me know if you need any feedback on the designs but also feel free to run with it. 

@mmurph3, Thanks for opening this issue and pointing out a place we can elevate our UI. Great find!!
