### ISSUE TITLE
Kubecost not showing recommendation based on max usage

### ISSUE THREAD

**Issue by ankit-kumar-7** [kubecost/cost-analyzer-helm-chart#1594]
**Describe the bug**
Kubecost request sizing giving recommendations based on current usage and not the max usage. 

**Expected behavior**
The recommendation should be based on max usage which is 1.047 in case of cpu as shown in third image.

**Screenshots**

![](https://user-images.githubusercontent.com/97100327/181444515-eeefbdaf-d04d-4484-ae9d-d5834340844e.png)
This image shows the usage and recommendation for all pods.

![](https://user-images.githubusercontent.com/97100327/181444887-f7216e92-3404-4f24-8b2a-bb6fa0f3758c.png)
This image shows usage and recommendation for the application.

![](https://user-images.githubusercontent.com/97100327/181447143-f0d00a0e-fb3b-46e9-b39f-c298cff46a4c.png)
This image shows the grafana report for one of the pods with max cpu usage: 1.047

gz#2265<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2265'>Zendesk ticket #2265</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-141) by [Unito](https://www.unito.io)

**Comment by keithhand** [comment]
Hi @ankit-kumar-7, I'm not sure what is causing this, but it looks like it might be a bug to me. I noticed that it appears we are targeting the same pod for max usage (`...-rt7kg`). I am curious if the other pods within the Kubecost and Grafana dashboards match values. Could you check some of these to see if we notice a similar discrepancy or if they are consistent? I will also ping someone from our engineering team to look and see if they have a quick explanation.

**Comment by Adam-Stack-PM** [comment]
@keithhand, ,Were  you and Austin able to get this issue resolved? If so could we close it? Or do we have more work to do on it?

**Comment by keithhand** [comment]
We noticed that the [Grafana section](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/pod-utilization.json#L264) looks like it might be using a different window than the [request sizing query](https://github.com/kubecost/cost-analyzer-frontend/blob/1a2f31db431990fe774028fb6e2117d75680e0c9/src/pages/RequestSizing/queries.ts), but we weren't able to confirm much past that. @ankit-kumar-7, were you able to check any of the other pods to see if there was a similar discrepancy or if this was a single point where the query was failing?

**Comment by ankit-kumar-7** [comment]
Hi @keithhand I checked the same for other pods as well and they are also showing similar discrepancy. There is a huge difference between usage shown in kubecost from the max usage indicated by grafana. Here's another example
<img width="1274" alt="Screenshot 2022-08-08 at 10 34 52 AM" src="https://user-images.githubusercontent.com/97100327/183343639-7a2643ee-d83b-4256-b6c4-1f7ae4fdb31f.png">


<img width="1710" alt="Screenshot 2022-08-08 at 10 35 17 AM" src="https://user-images.githubusercontent.com/97100327/183343686-b75023ec-ab22-40fb-9167-b881841e4a19.png">


Also this data is for the same window(last 7 days) for both

**Comment by dwbrown2** [comment]
@ankit-kumar-7 do you believe that you're seeing this on just CPU usage? And is this the exact Grafana/Prom query you're viewing? Just wanted to make sure this hasn't been modified...

```
avg (rate (container_cpu_usage_seconds_total{namespace=~"$namespace", pod_name="$pod", container_name!="POD",container_name!=""}[10m])) by (container_name)
```

Also, what profile are you using in request-sizing view? 

<img width="497" alt="image" src="https://user-images.githubusercontent.com/298359/183755153-efa9af02-d5ea-47c6-9c3f-888dc7ca1e33.png">

**Comment by AjayTripathy** [comment]
Hi @ankit-kumar-7 I noticed in this issue https://github.com/kubecost/cost-analyzer-helm-chart/issues/1612#issuecomment-1208947819 that you are running an older version of kubecost-- mind upgrading to v1.95.1 and taking another look?

**Comment by ankit-kumar-7** [comment]
On upgrading to 1.95.1, the link to grafana dashboard broke. Its showing grafana is disabled while in the deployment it's enabled. The cpu usage and recommendation shown is still much less compared to max usage.

**Comment by keithhand** [comment]
Relooking at this, I noticed those two sections I posted earlier, the [Grafana section](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/pod-utilization.json#L264) and the [Kubecost section](https://github.com/kubecost/cost-analyzer-frontend/blob/1a2f31db431990fe774028fb6e2117d75680e0c9/src/pages/RequestSizing/queries.ts), it looks like the Kubecost frontend is checking for `sum(quantile_over_time)` vs the Grafana dashboard is basing numbers based on `avg`. Could this possibly cause the discrepancy? Tagging @kaelanspatel as the engineer on rotation.

**Comment by kaelanspatel** [comment]
Form a cursory look over it doesn't seem like the Kubecost request sizing FE does that prometheus query. That Grafana query looks like it's consistent with the one Kubecost uses to get pod CPU usage.

@ankit-kumar-7 for the dashboard link being disabled, are you using bundled Grafana? i.e. is grafana enabled or disabled in your helm configs?

**Comment by ankit-kumar-7** [comment]
@keithhand @kaelanspatel apologies for leaving the above comment unattended. Has there been any update on this. Currently we are using v1.100.0 and the issue still persists(i.e it is showing recommendations based on average usage instead of max usage over a period of time).

**Comment by kwombach12** [comment]
@ankit-kumar-7 We have fixed this issue with this PR - https://github.com/opencost/opencost/pull/1813. If you upgrade to 1.102, it should be resolved!
