### ISSUE TITLE
Support AWS Assume Role when ingesting multiple AWS bills

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1596]
**What problem are you trying to solve?**
My organization has many different AWS payer accounts, and I would like Kubecost to ingest the bill from all of them using [IAM Roles for Service Accounts (IRSA)](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html). Today this appears only to be possible using IAM Users.

**Describe the solution you'd like**
The ability to set an AWS Role ARN for each bill source to have Kubecost assume the relevant IAM Role based on the billing source.

**Describe alternatives you've considered**
We've considered replicating CUR S3 buckets to a single bucket, and having Athena target that single combined bucket.
https://catalog.us-east-1.prod.workshops.aws/workshops/fd889151-38aa-4fe2-a29d-d5fa557197bb/en-US/prerequisites-multipayer

**How would users interact with this feature?**
Currently, Kubecost requires setting `.Values.kubecostProductConfigs.masterPayerARN` to the ARN of the IAM Role in the payer account to assume. With the support of multi-cloud via cloud integrations, [the addition of a masterPayerARN property to the AWS object](https://guide.kubecost.com/hc/en-us/articles/4407595968919#aws-1) would match what Kubecost is doing for IAM User.

IAM User:

```json
{
    "serviceKeyName": "<ACCESS_KEY_ID>",
    "serviceKeySecret":"<ACCESS_KEY_SECRET>",
    "athenaBucketName": "<ATHENA_BUCKET_NAME>",
    "athenaRegion": "<ATHENA_REGION>",
    "athenaDatabase": "<ATHENA_DATABASE>",
    "athenaTable": "<ATHENA_TABLE>",
    "projectID": "<ATHENA_PROJECT_ID>"
}
```

IAM Role:

```json
{
    "masterPayerARN": "<MASTER_PAYER_ARN>",
    "athenaBucketName": "<ATHENA_BUCKET_NAME>",
    "athenaRegion": "<ATHENA_REGION>",
    "athenaDatabase": "<ATHENA_DATABASE>",
    "athenaTable": "<ATHENA_TABLE>",
    "projectID": "<ATHENA_PROJECT_ID>"
}
```

gz#2269<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2269'>Zendesk ticket #2269</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-143) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
@Sean-Holcomb does this seem straightforward?

**Comment by Sean-Holcomb** [comment]
AFAIK this is more of a docs issue, multi-cloud can take in master-payers for each of its [aws configs ](https://github.com/opencost/opencost/blob/2850bc8f33f8ba6dd49aa9d1d2348d93a1535b2c/pkg/cloud/awsprovider.go#L429) and it is handled [here](https://github.com/opencost/opencost/blob/2850bc8f33f8ba6dd49aa9d1d2348d93a1535b2c/pkg/cloud/awsprovider.go#L433)

**Comment by srpomeroy** [comment]
@Sean-Holcomb are you saying what I am suggesting is already supported?

**Comment by Sean-Holcomb** [comment]
I am pretty sure they still need 
```
"serviceKeyName": "<ACCESS_KEY_ID>",
"serviceKeySecret":"<ACCESS_KEY_SECRET>",
```
It sounds like they are wanting to do multi-pod annotation verification, which I don't think is supported.

**Comment by srpomeroy** [comment]
Hopefully it will work without having an IAM user specified. In theory you would just need the role in the account where the primary is running to be trusted by all the roles in the different payer accounts. 

I’ll make some time next week to treat it out.

**Comment by Hronom** [comment]
Is this supported?

**Comment by srpomeroy** [comment]
I am trying to remember if I tested it or what the outcome was. It should be possible to use the `MasterPayerARN` property so long as the proper IAM trusts are in place across accounts.

**Comment by AjayTripathy** [comment]
This should be supported now, yes. Please feel free to reopen if it is not.
