### ISSUE TITLE
namespaces with no <0.01 units of CPU and MEMORY show no cost in cost allocation UI

### ISSUE THREAD

**Issue by praveenkumar0566** [kubecost/cost-analyzer-helm-chart#1607]
**Describe the bug**
Namespaces with no resource requests and limits defined for both CPU and MEMORY show 0$ in the cost allocation report even if the workload is running in the pod.
![image](https://user-images.githubusercontent.com/102574445/183144077-2bb5768b-cf1d-4f15-8f0c-723823b9a98f.png)

And If we redeploy the pod by defining resource requests and limits for CPU and RAM values appear in the cost allocation namespace section.
![image](https://user-images.githubusercontent.com/102574445/183144350-c78748da-139d-4662-bed6-108f29662265.png)

**To Reproduce**
Steps to reproduce the behavior: Add a namespace to the cluster and deploy some sort of workload without resource requests or limits defined.

1. Go to the 'cost allocation page' 
1. Click on 'filters with namespace' 
1. See error check the added namespace CPU and RAM values. it shows 0$

**Expected behavior**
The namespace should show the CPU and RAM of the running workload even if the reserves are not set.

gz#2321<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2321'>Zendesk ticket #2321</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-147) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
This doesn't seem likely. It's more likely that the backing cadvisor metrics are not making it back into kubecost. Can you look at the diagnostics page to ensure cadvisor metrics are being scraped?

**Comment by AjayTripathy** [comment]
I suppose another point is that if usage is low, you might have $0.004 over a small time window causing a round to zero-- you may check the backing API for more preceision.

**Comment by kirbsauce** [comment]
@praveenkumar0566 , let's run another test.  Let's deploy two workloads w/out requests or limits and let it bake for two days and make sure the UI has a 7 day window.  If we still see 0's, let's redeploy just one with requests and observe the results.  this should ensure we're allowing things to accumulate a reportable cost, in the event their resource utilization is low.

**Comment by AjayTripathy** [comment]
Checking the API also seems reasonable. That should have ~6 figures of precision and you can also check if usage is registered

**Comment by kirbsauce** [comment]
love that idea.  it also gives us something to have users try.  one could also just drill down into the details too, I suppose.

**Comment by AjayTripathy** [comment]
Were you able to check the API on your end @praveenkumar0566 ?

**Comment by praveenkumar0566** [comment]
Apologies @AjayTripathy  i didn't update here. Yes i have ran the API i can see the namespace with limits and i didn't see the values for the namespace with no limits.
I have deployed a namespace without requests yesterday (my time) so i will verify today again.
Will keep updated.

**Comment by praveenkumar0566** [comment]
I verified again today that the cost allocation for CPU and RAM are displaying for the namespace with the workload for the one in which requests are not defined. Yesterday it was zero so I think it takes time to accumulate to display with very low utilization I checked both from UI and via API
**Below is the pod with requests not defined.**
![image](https://user-images.githubusercontent.com/102574445/183653542-f35d2190-89a4-4503-934a-1d3fc1261c54.png)

API

    "redis":{
            "name":"redis",
            "properties":{
               "cluster":"cluster-one",
               "node":"ip-10-0-28-142.us-west-1.compute.internal",
               "container":"leader",
               "controller":"redis-leader",
               }
            },
            "window":{
               "start":"2022-08-09T00:00:00Z",
               "end":"2022-08-10T00:00:00Z"
            },
            "start":"2022-08-09T00:00:00Z",
            "end":"2022-08-09T12:57:00Z",
            "minutes":777.000000,
            **"cpuCost":0.040943,**
            **"ramCost":0.005353,**

**Below is the pod with requesters defined.**
![image](https://user-images.githubusercontent.com/102574445/183653706-cd810782-8208-45ee-8533-94a47f872097.png)

"nginx-ingress":{
            "name":"nginx-ingress",
            "properties":{
               "cluster":"cluster-one",
               "node":"ip-10-0-24-78.us-west-1.compute.internal",
               "container":"nginx-nginx-ingress",
               "controller":"nginx-nginx-ingress",
               "controllerKind":"deployment",
               "namespace":"nginx-ingress",
               "pod":"nginx-nginx-ingress-b79f57db7-thm7f",
                 .
            "cpuCores":0.100000,
            **"cpuCost":0.075879,**
            **"ramCost":0.012699,**

I believe it's not a bug but it takes time to accumulate the cost if the usage is too low.

**Comment by AjayTripathy** [comment]
Sounds like this can be closed then... @Annalillie any ideas on improving the UX here so that it's more clear that we have data albeit very small for these views?

**Comment by Annalillie** [comment]
@AjayTripathy if I'm reading the comments Praveen made correctly, it seems as though we have data for these views. However, this data is pretty small and takes a while to display. In that case, a "pending" status could be useful here in place of the value. If a value is, let's say $0.004, we could also have a generic value in place that describes the cost for this view is under $0.01. Maybe something like { v $0.01 }

**Comment by AjayTripathy** [comment]
Yep, you're reading it correctly. Pending or < 0.01 both sound good.

**Comment by Annalillie** [comment]
Awesome! I think the number value is best here. Even though pending would work, it doesn't offer any up front information like the number value does which I believe is more useful to users.

<img width="1041" alt="Screen Shot 2022-08-09 at 2 26 09 PM" src="https://user-images.githubusercontent.com/89574007/183764914-3ef5a4d3-d7ed-4c78-802f-b2e1d4eda57e.png">

<img width="1125" alt="Screen Shot 2022-08-09 at 2 23 51 PM" src="https://user-images.githubusercontent.com/89574007/183764972-71dfa8b2-c621-45a1-9ced-ca33fef1073f.png">

**Comment by AjayTripathy** [comment]
I like the first option. @teevans for final call here and triage.

**Comment by dwbrown2** [comment]
I also like the first option! Would this just be used to differentiate between say 0.000001 and 0.0? Or would either of you also picture it being used in other scenarios, e.g. specifically on startup like Praveen originally reported? I feel like the former handles all cases I can picture but just wanted to see.

**Comment by AjayTripathy** [comment]
I beleive this has been addressed in the UI
