### ISSUE TITLE
Allow users to export saved reports/alerts created via the UI

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1608]
**What problem are you trying to solve?**
If a user creates an alert or report in the UI, it would be nice to have a way to export that report into a YAML format to add to their values.yaml so the alert/report can be recreated every deployment.

**Describe the solution you'd like**
A button for saved reports/alerts to 'export YAML'
 

**Describe alternatives you've considered**
Users today can configure the report in the UI and then manually input them into the correct [values.yaml format](https://guide.kubecost.com/hc/en-us/articles/4407595977879-Saved-Reports#example-helm-values-yaml-saved-reports-section).

**How would users interact with this feature?**
![image](https://user-images.githubusercontent.com/43491549/183159891-9138bd3f-bfbe-44ba-8bd2-8e32fd775367.png)
![image](https://user-images.githubusercontent.com/43491549/183160282-479d8ff5-87d6-404c-8328-6b992b28010b.png)

gz#2133<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2133'>Zendesk ticket #2133</a>)</i>

**Comment by akramwaseem** [comment]
+1

**Comment by akramwaseem** [comment]
+1

**Comment by wamak9** [comment]
so, current process is to update the YAML file for both alert and reports and then deploy and see if the alert is working as expected or if the report is as we need it.
If its not, update the yaml again and redeploy the chart and go on until we get to a point on what we need.

This goes on for both reports and alerts. Having a import as yaml gives more insights into how the report looks and alerts look and we can play around with the configuration and then import and add it yaml.

Let me know what other feedback you need.

@keithhand

**Comment by Adam-Stack-PM** [comment]
@akramwaseem, Thanks for the followup and helping build on the idea.

**Comment by akramwaseem** [comment]
Can we get some traction on this ?

**Comment by dwbrown2** [comment]
To be reviewed as part of 1.99 release where we'll look at a number of alerts/reports features!

**Comment by Adam-Stack-PM** [comment]
Likely to miss v1.99. Feel we should prioritize this issue early in v1.100.

**Comment by wamak9** [comment]
Would be nice if we can prioritize this for next version release.

**Comment by teevans** [comment]
This seems like a quick win - I'll see if I can knock it out this week.

**Comment by teevans** [comment]
Assigning to @aligon to see if can knock this out
