### ISSUE TITLE
Unable to send test alerts on GCP

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#161]
```
I1203 14:49:28.500611       1 router.go:238] Error returned to client: metadata: GCE metadata "instance/attributes/cluster-name" not defined
```

**Comment by dwbrown2** [comment]
User is running self managed kubernetes cluster with cloud provider as gce. 
K8s Version : v1.14.0
Kubecost version : Running Kubecost v1.48.0

**Comment by AjayTripathy** [comment]
This is fixed, as we now check for the instance attribute "cluster-name" existing. https://github.com/kubecost/cost-model/commit/0cd7790c65460b0efdabd3270c4a28ecff0a512f
