### ISSUE TITLE
Anomaly in cost savings report

### ISSUE THREAD

**Issue by ankit-kumar-7** [kubecost/cost-analyzer-helm-chart#1612]
**Describe the bug**
We have jobs running everyday for whhich the cost allocation shows very less total cost incurred for a day but the savings report show high value based on cpu and ram request.

**Expected behavior**
The savings report should show data based on usage.
for one day cost showing : $0.24
For 30 days (considering similar usage): 0.24*30 = $7.2
Then how is savings report showing $371.85/mo

**Screenshots**
<img width="1441" alt="Screenshot 2022-08-08 at 3 04 20 PM" src="https://user-images.githubusercontent.com/97100327/183387728-2c2e1ef5-988e-4002-bdf1-b9a8559a4d4a.png">
Cost allocation for one day.

<img width="1447" alt="Screenshot 2022-08-08 at 3 04 54 PM" src="https://user-images.githubusercontent.com/97100327/183388005-12609190-2ec5-4a97-93fc-304fe69b90b5.png">
Savings report for the same

**Note:**
1.  Filters applied for both: **namespace=prod, label=project:qua-job-apiauto**
2. CPU usage in savings report does not indicate max usage - separate issue - [link](https://github.com/kubecost/cost-analyzer-helm-chart/issues/1594)

gz#2327<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2327'>Zendesk ticket #2327</a>)</i>

**Comment by jcharcalla** [comment]
@ankit-kumar-7  Thank you for reporting this issue.

Can you tell me what version of Kubecost you are running?

**Comment by ankit-kumar-7** [comment]
I am running **Kubecost v1.89.1**

**Comment by AjayTripathy** [comment]
Thanks @ankit-kumar-7 , mind upgrading to v1.95.1 and taking a look again? Lots has changed since that version on accuracy/anomaly detection.

**Comment by jcharcalla** [comment]
@ankit-kumar-7 Were you able to test this after upgrading?

**Comment by ankit-kumar-7** [comment]
On upgrading to kubecost 1.95.1 this issue was resolved. Thanks @AjayTripathy @jcharcalla

**Comment by dwbrown2** [comment]
Great to hear, @ankit-kumar-7! Anything else we can help you with?
