### ISSUE TITLE
Set thanos store to recreate instead of update

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1613]
**Describe the bug**
kubecost-thanos-store pod hangs when editing deployment definition to change the update strategy. 

**To Reproduce**
1. Edit kubecost-thanos-store deplyoment and make a change to the update strategy. Change it to 'Recreate' 
2. Run:
kubectl get pods -n kubecost
4. See that the second kubecost-thanos-store pod is created and old pod is stuck in 'terminating' state. 

**Expected behavior**
We expect the pod to terminate cleanly and a new pod to deploy.

**Proposed Solution**

Change the default update strategy type setting from Rolling to Recreate:
{{ with .Values.store.deploymentMatchLabels }}{{ toYaml . | indent 6 }}{{ end }}
{{ with .Values.store.deploymentStrategy }}
  strategy: {{ toYaml . | nindent 4 }}
{{ end }}

Reference: https://github.com/kubecost/cost-analyzer-helm-chart/blob/fb9a9ab67e4ed0a1ed9c5ec0a19b9f392dbb1ea1/cost-analyzer/charts/thanos/templates/store-deployment.yaml#L25-L32

**Comment by keithhand** [comment]
I updated this in the past to support a custom strategy in this [PR](https://github.com/kubecost/cost-analyzer-helm-chart/issues/1328) based on this [ZD request](https://kubecost.zendesk.com/agent/tickets/1576). If we would like to default to Recreate, we only need to tweak the sub-charts values.yaml, see [this PR](https://github.com/kubecost/cost-analyzer-helm-chart/pull/1614).

**Comment by Adam-Stack-PM** [comment]
@Sean-Holcomb Could you add a priority status to this bug?
