### ISSUE TITLE
Full Aggregation of Costs by Controller

### ISSUE THREAD

**Issue by cazter** [kubecost/cost-analyzer-helm-chart#1621]
**What problem are you trying to solve?**
Need a complete sum total of costs associated with a StatefulSet.

**Describe the solution you'd like**
Cost Allocations page drill-down to K8S controllers currently only includes some portion of costs (CPU and Memory) for controllers. We'd like this to include all associated costs--network and storage.

**Describe alternatives you've considered**
N/A

**How would users interact with this feature?**
This would allow us to track our customer resource usage cost in order to fairly pass those costs on-to customers.

gz#2356<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2356'>Zendesk ticket #2356</a>)</i>

**Comment by zorrobyte** [comment]
Nice meeting with you, Brent!

Thank you for submitting this enhancement request; I'll follow up in the support case! (ZD #2196)

**Comment by Sean-Holcomb** [comment]
@cazter can I get a little more detail on what you want to accomplish here. It seems to me that what you are looking for is on the Allocation page rather than the Asset page. On the Allocation page you can aggregate by controller and get a break down like this
![Screen Shot 2022-08-10 at 4 58 23 PM](https://user-images.githubusercontent.com/12225425/184042903-38c397eb-41fa-4494-a349-3c7b954c4842.png)

**Comment by cazter** [comment]
@Sean-Holcomb Here's an example. The below screenshot is from Assets > Disk.
![disks](https://user-images.githubusercontent.com/6201176/184148081-f9ee35f0-8920-47da-9f2b-1b6d15b3cc43.png)

That PVC disk is attached to this controller's pod. The below screenshot is from Cost Allocation > Namespace (Controller):
![controller](https://user-images.githubusercontent.com/6201176/184148302-dca2f421-a93f-4755-98e6-3688fb1fdc73.png)

Cost allocation is not properly accounting for the full costs of the resources associated with the controllers.

**Comment by Sean-Holcomb** [comment]
@cazter thank you for the details that makes the issue much clearer. I have relabeled this issue as a bug and given it a category and priority. It will be considered for an upcoming release.

**Comment by AjayTripathy** [comment]
Hey all, we're digging in here now and the plan is to get it into an upcoming release. We'll let you know if additional debugging info is needed.

**Comment by AjayTripathy** [comment]
@cazter any chance we could get a dump of your data we can mount on our test instances to speed up our repro and make sure we're reproing the right thing? The etl-download.sh script generates a tarball we can use to view data on our own clusters: https://github.com/kubecost/etl-backup

**Comment by cazter** [comment]
@AjayTripathy Sure. I'll drop the data in your slack on #customer-grow.

**Comment by Adam-Stack-PM** [comment]
@AjayTripathy, When you have time could you confirm you have the information you need?  Want to make sure this issue does not slip through the cracks.
