### ISSUE TITLE
Add UI Report Aspects for Budget / Budget Alerts

### ISSUE THREAD

**Issue by kc-adawson** [kubecost/cost-analyzer-helm-chart#1622]
**What problem are you trying to solve?**
We offer Allocation and Asset Budget Alerts to be created within the "Alerts" module. There is no current way to visualize or tracki these budgets in the Front End/UI.

**Describe the solution you'd like**
A UI element could be created when Budget Alerts are created, showing what is defined in the alert (Kubecost over Last 7 Days - Budget vs Spend), Or, create a way to view and track budgets for K8s and Cloud Assets within the respective UI (Cost Allocation/Assets), or on its own page. 

**Describe alternatives you've considered**
Keep budgets to Alerts only and develop Budget reporting later in the product roadmap.

**How would users interact with this feature?**
Via the Front End and via API

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-149) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
@teevans any thoughts here?

**Comment by dwbrown2** [comment]
+1, we used to display part of this in the namespace details page. I see at least three potential options: 1) display more info on the alerts 2) provide insights on the inspect page or 3) create a new budgets (& policies) page. 

One UI aspect to consider is that we could potentially have multiple/many budgets set per namespace.

**Comment by billups32** [comment]
This came up recently @dwbrown2 for a Budget filter or stand alone report that shows Budget vs Actual.

**Comment by teevans** [comment]
@billups32 - We're actually going to be prioritizing some budget work over the next few releases. Will update when I have more information!

**Comment by kc-adawson** [comment]
Closing issue- this is now working in the platform.
