### ISSUE TITLE
Parameterize namespace values using Values.yaml file

### ISSUE THREAD

**Issue by linhlam-kc** [kubecost/cost-analyzer-helm-chart#1629]
**What problem are you trying to solve?**
- Customer and partner report that many of our deployment templates does not have the namespace explicitly specified in the metadata. It generates issue when deploying Kubecost using their in-house deployment tool or Gitops tool like ArgoCD which has no option to omit namespace value. The template that does not have the namespace specified will be deploy into 'default' namespace.

**Describe the solution you'd like**
 - Update all of our resources templates in all of the helm charts and subcharts in consistent format with namespace is explicitly specified. Customer can specify the namespace to deploy Kubecost via a Values file

- Example logic:
```
{{- if .Values.namespaceOverride -}}
{{- .Values.namespaceOverride -}}
{{- else -}}
{{- .Release.Namespace -}}
{{- end -}}
```
**Describe alternatives you've considered**
- Rendering Helm charts to template file and overriding namespace value in post-operation using Kubect:
- Example:
```
helm template | kubectl create --namespace foo -f -
```
 **How would users interact with this feature?**
Customers can either deploy Kubecost using Helm with the `--namespace` flag or set it in values.yaml file when deploy Kubecost via their Gitops tool.

**Related issue**
https://github.com/kubecost/cost-analyzer-helm-chart/issues/1527

**Comment by Adam-Stack-PM** [comment]
@linhlam-kc Thanks for this idea. To help move this forward, do you see any downsides to your proposed solution? 

Assuming we went with the current approach for a specific reason (not saying it was a good or bad) but always helpful knowing the other side of a change.

**Comment by linhlam-kc** [comment]
@Adam-Stack-PM From my local testing, I have not seen the downside of the proposed solution compare to the current approach yet.

**Comment by linhlam-kc** [comment]
Closing the issue as it was resolved with the PR https://github.com/kubecost/cost-analyzer-helm-chart/pull/1924
