### ISSUE TITLE
AWS cross zone traffic doesn't seem right

### ISSUE THREAD

**Issue by zorrobyte** [kubecost/cost-analyzer-helm-chart#1630]
**Describe the bug**
Customer has their network config setup like this:

```config
destinations: 
direct-classification: 
- region: apne1 
zone: apne1-az1 
ips: 
- 10.0.104.0/22 
... 
- region: apne1 
zone: apne1-az2 
ips: 
- 10.0.128.0/22 
...
```

This is traffic within a zone:
![image](https://user-images.githubusercontent.com/7257172/184022775-1d32466f-637a-401d-8be0-bf73d668b502.png)

And outside a zone:
![image](https://user-images.githubusercontent.com/7257172/184022804-b425973b-52bf-4602-85c5-59fe351adb1a.png)

In-zone traffic should be much, much more than cross-zone traffic. (The conclusion can be verified via AWS VPC flow logs)

The Cost and Usage report has been configured for AWS.

I spoke with AjayTripathy about this awhile back and the answer was that these costs are estimates and as such, may not be exactly correct. The sentiment here is that they seem to be very incorrect.

ZD case 2190

gz#2361<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2361'>Zendesk ticket #2361</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-150) by [Unito](https://www.unito.io)

**Comment by Adam-Stack-PM** [comment]
@zorrobyte Thanks for this issue. We have the bug categorized and prioritized. Will review for an up coming release.

**Comment by dwbrown2** [comment]
I know we've tested this fairly closely. Are we confident this isn't a potential configuration issue?

**Comment by zorrobyte** [comment]
> I know we've tested this fairly closely. Are we confident this isn't a potential configuration issue?

I've been working with Simon on this case since July 14th or so. I can ask them to chime in here!

**Comment by simonwu-sn** [comment]
How can I verify if it's configuration issue. As @zorrobyte says, we follow the online documentation and define the zone info with CIDR.
destinations: 
direct-classification: 
- region: apne1 
zone: apne1-az1 
ips: 
- 10.0.104.0/22 
... 
- region: apne1 
zone: apne1-az2 
ips: 
- 10.0.128.0/22 
...

**Comment by Adam-Stack-PM** [comment]
@simonwu-sn, Sorry for the delay here.  I will get this on supports radar Monday morning.

**Comment by dwbrown2** [comment]
The config pasted looks like it has indention off, but that might just be auto formatting. If the configuration fails to load, we do log it, but we revert to a default configuration (which would definitely be missing any custom classifications):

```
// Load/Parse Configuration File, Fallback to Default if failure
    networkConfig, err := network.NewNetworkConfigFromFile("/network-costs/config/config.yaml")
    if err != nil {
        klog.V(1).Infof("Config file failed to load, falling back to default: %s", err.Error())

        networkConfig = network.DefaultNetworkConfig()
    }
```

You can restart a single `network-costs` pod and watch the logs at startup and look for the log above.
