### ISSUE TITLE
Auto populate filters under Savings > Right Size your Container Requests

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1634]
**What problem are you trying to solve?**
Specifying filters is tedious and manual in this view. Involves knowing the values you're searching for more specifically and involves some copying and pasting.

**Describe the solution you'd like**
Ability to search for specified filter value with an auto-complete function instead of having to copy and paste the value(s) for the specified filter in the text box.
![](https://user-images.githubusercontent.com/36980248/184214689-84e3eb7c-063c-4efe-bd5e-60c1c26369e7.png)

**Describe alternatives you've considered**
Doing this from the cost allocation pane by aggregating the data.

**How would users interact with this feature?**
Users would be able to easily add a filter for the label, namespace, service, etc they're looking for in large cluster(s)/workloads instead of having to specify this more specifically in the text box next to the filters drop down.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-151) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
I believe autocomplete is very straightforward with certain fields, e.g. namespace, but then is much harder for others, e.g. labels. 

As an alternative but also potentially complementary: what do you think about making this another form a saved reports, i.e. a saved report for different views of Savings/Optimization Insights?

**Comment by kc-adawson** [comment]
What if you were able to create custom groups in Settings where you could define all the subgroups and what their labels are. These subgroups could then auto-populate the different filter views with pre-loaded data.

For example: 

Group- Environment
---
Subgroups:
Prod (Label: Prod) (50% of cost)
Dev (Label:Dev or Name Contains Dev) (25% of cost)
Test (Label:Test or Name Contains Test (15% of cost)
Unallocated (10% of cost)

Kubecost could auto-populate filters based on these pre-loaded groups. Similar to the Department/Owner/Team/Product group functionally today, but with ability to manipulate the sub groups / combine groups / add additional label logic to groups.

**Comment by akramwaseem** [comment]
+1 -- This can be integrated into  https://github.com/kubecost/cost-analyzer-helm-chart/issues/1670

Auto populating the field with namespaces /cluster / service  seems like a good option.

**Comment by dwbrown2** [comment]
@kc-adawson like the idea, but feels a bit more like reporting functionality than core Settings functionality to me. You see it closer tied to Settings?

cc @michaelmdresser since he's working on related functionality w/r/t filters

**Comment by jessegoodier** [comment]
We have a couple of big requests for easier filtering for some large-scale POCs. I'll share a recent recording internally, but the summary is that the UI is not intuitive when there are many items. Top requests are for allocation and request-sizing pages.

Suggestions have been autocomplete, "sticky filters," and drop downs.

cc: @kwombach12

**Comment by kwombach12** [comment]
@jessegoodier Thanks for the heads up. This is a high priority feature we are picking up in 1.102

**Comment by wamak9** [comment]
@kwombach12  --  bump.
@jessegoodier

**Comment by wamak9** [comment]
bump

**Comment by wamak9** [comment]
bump

**Comment by kwombach12** [comment]
We added autopopulating filters to budgets page in 103 and hope to expand that functionality soon!

**Comment by MrJW27** [comment]
@wamak9 - Have you tested this?

**Comment by wamak9** [comment]
@MrJW27  -- yes, I did they work as expected. Waiting on bringing this to other  things.
