### ISSUE TITLE
Increase the Requested rows of Asset data > 75000 and to an amount that will NOT crash browser

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1635]
**What problem are you trying to solve?**
This is working as intended. Per our internal conversations, this should be able to be increased.

To reproduce this:
Navigate to Asset View, hit aggregate by "type" and then click "cloud" under the results under the graph.
This error generates (specific to environment amount of unaggregated asset data):

```
Requested 134775 rows of Asset Data which exceeds the limit of 75000.
To reduce the amount of data returned, try changing resolution of Entire Window or adding filters. Learn more.
```

**Describe the solution you'd like**
Increase the allowed number of rows requested. Large enough that it won't crash the browser.

**Describe alternatives you've considered**
Reduce the amount of data returned, try changing resolution of Entire Window or adding filters

**How would users interact with this feature?**
Perform the above action in the UI and not receive a warning to make adjustments on the client if it meets a threshold higher than 75,000 rows.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-152) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
I definitely think we can bump this limit. tentative proposal is to check on multi-cloud where unaggregated this number is closer to 200k and see if we can get there.

**Comment by mmurph3** [comment]
We have a few customers experiencing this. Do we have an update on what we can bump the limit to and when this will be added?

`Requested 1843940 rows of Asset data which exceeds the limit of 75000.`

**Comment by dwbrown2** [comment]
@Adam-Stack-PM can we review again as part of 1.100? This should be a quick change it just requires scale testing. 

@mmurph3 is there an example request they are making of the application?  

@AjayTripathy @nealormsbee any further input?

**Comment by Adam-Stack-PM** [comment]
Tracked. Would propose we jump on this item early in the release cycle and start testing week 1. This would give us time to work out any scaling roadblocks.

**Comment by nealormsbee** [comment]
>any further input?

I'd vote to create an Assets View API response as we've done with Allocation and Cloud.

**Comment by mmurph3** [comment]
Aggregate Assets by label is one aggregation that causes this.

**Comment by AjayTripathy** [comment]
We're changing Assets -> Cloud Assets but yes we have a view api on our list-- @nikovacevic to confirm?

**Comment by nikovacevic** [comment]
Yep, just added it to the release doc.

BTW this is also likely a FE bug that is easy to solve. Why are we going straight from Type to Item? Shouldn't we go Type -> Service -> Item for type Cloud? cc @nealormsbee

**Comment by nealormsbee** [comment]
Makes sense to me. I'll open an issue for that on the FE repo.

**Comment by srpomeroy** [comment]
@Adam-Stack-PM Did this make it into 1.100?

**Comment by teevans** [comment]
@srpomeroy - No it didn't

**Comment by dwbrown2** [comment]
@kwombach12 is reviewing as part of long-running queries work for 1.101

**Comment by AjayTripathy** [comment]
Doesn't this become a lot less necessary as we move to the new Cloud API? 75000 kubernetes-only assets is a huge number.

**Comment by teevans** [comment]
I believe that's correct ^^

**Comment by AjayTripathy** [comment]
My proposal is we focus on the new APIs then in 101, since we want to thoroughly vet them for scale and accuracy!

**Comment by mmurph3** [comment]
@AjayTripathy @teevans Now that we have the cloud cost api, will this issue be solved? Can we solve this issue?

**Comment by teevans** [comment]
@mmurph3 - That's correct sir.

**Comment by chipzoller** [comment]
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.
