### ISSUE TITLE
Label query shouldn't transform results to contain underscores

### ISSUE THREAD

**Issue by williamscs** [kubecost/cost-analyzer-helm-chart#1636]
**What problem are you trying to solve?**
It's confusing when I query for allocations related to a label that contains a dash in it "-" and it is returned from the API with underscores "_". 

![image](https://user-images.githubusercontent.com/1476137/184397927-cbd0bdc3-f20b-4cd2-b2bc-3f13818ea62c.png)

**Describe the solution you'd like**
For the API to return the exact value queried.

gz#2389<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2389'>Zendesk ticket #2389</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-153) by [Unito](https://www.unito.io)

**Comment by keithhand** [comment]
Hello @williamscs, the limitation here is due to a limit within Prometheus for how we can save labels: https://guide.kubecost.com/hc/en-us/articles/4407595916823-Allocation-API#allocation-schema-version-1-76.

> Note: Prometheus only supports underscores (_) in label names. Dashes (-) and dots (.), while supported by Kubernetes, will be translated to underscores by Prometheus. This may cause the merging of labels, which could result in aggregated costs being charged to a single label.
