### ISSUE TITLE
Generate PDF with more data and possibly a graph when sending alerts via email 

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1641]
**What problem are you trying to solve?**
Provide more information, including visual when an alert is generated and sent to email so it is more easily interpreted by various teams within an org.

**Describe the solution you'd like**
When an alert is generated, send an attached pdf to the recipient that includes more information.  Example: a recurring update alert of the cumulative costs breakdown by namespace including the other values like CPU/RAM etc. Including a graph, similar to the reports view.

![](https://user-images.githubusercontent.com/36980248/184898073-a9aed25a-e680-4193-aaaf-c1f1e3deeefb.png)

**Describe alternatives you've considered**
Generating a report and sending it off manually

**How would users interact with this feature?**
Users would create an alert with defined threshold

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-155) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
+1, @jjarrett21 have you or anyone on the team used an PDF generator packages before? That feels like the only missing piece that I see. 

@mmurph3 where do you see most value here, 1) attaching more data to email directly or 2) displaying it in visually appealing way?

**Comment by mmurph3** [comment]
I think a graph in addition to the real values is quite good as graphs are more appealing than values, but a distribution of the costs (CPU, RAM, out-of-the cluster costs etc.) would make the alert more "complete". As you can see in the attachment you have the cost and efficiency value. It lacks the distribution of the cost. Having this information included makes the alert more "eligible/complete/valuable".
It would be fine if it could be included as HTML and/or PDF output
<img width="533" alt="pic" src="https://user-images.githubusercontent.com/36980248/185465897-d1bf7d16-a777-4eec-8d53-20dbba9e2be0.png">
t

**Comment by jessegoodier** [comment]
IHAC ask today for basically this too. They want an alert (aka "scheduled report") with the /details page on a namespace
use case is giving details to users without them logging into kubecost UI.

Happy to add another ER (for /details), but just echoing that this is being asked for by other customers.

**Comment by akramwaseem** [comment]
+1
