### ISSUE TITLE
Support overriding name on cost-analyzer service name

### ISSUE THREAD

**Issue by 1uf3** [kubecost/cost-analyzer-helm-chart#1645]
What problem are you trying to solve?
On the cost-analyzer service, overriding name is not an option. It appears supported on other psp templates so could it be added here?
i hate deployed service name `cost-analyzer-cost-analyzer`. i want to change. for instance`kubecost-cost-analyzer`

Describe the solution you'd like
Override the name of cost-analyzer service name https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-service-template.yaml#L7

Describe alternatives you've considered
Do nothing, Probably not great for support for old users.

How would users interact with this feature?
Should be seamless-- can inherit names as other psps do.

gz#2436<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2436'>Zendesk ticket #2436</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-156) by [Unito](https://www.unito.io)

**Comment by lufeee** [comment]
can i make PR to solve this issue?

**Comment by dwbrown2** [comment]
Seems like a great idea to me if you can @lufeee but I'm less familiar with this part of the code base. Any considerations on your end @AjayTripathy @michaelmdresser?

**Comment by Adam-Stack-PM** [comment]
@lufeee Adding the needs follow up label to get this on the engineering teams radar.  Would expect a followup within 24 hours.
