### ISSUE TITLE
Container Request Recommendation Request entity too large

### ISSUE THREAD

**Issue by jyepesr1** [kubecost/cost-analyzer-helm-chart#1646]
**Describe the bug**
When I try to run the commands described here https://github.com/kubecost/docs/blob/main/api-request-recommendation-apply.md to check the plan to be applied for the cluster resources I get a 413, Request entity too large.

**To Reproduce**

1. Run the following command

```
 curl -XGET 'https://<my kubecost hostname>/model/savings/requestSizing' \
 -d 'window=2d' \
 |
 curl -H "Content-Type: application/json" \
     -XPOST \
     --data-binary @- \
     'https://<my kubecost hostname>/cluster/requestsizer/plan'
```

1. See error

```
<HTML>
   <head><title>413 Request Entity Too Large</title></head>
   <body>
      <center><h1>413 Request Entity Too Large</h1></center>
      <hr><center>nginx/1.23.1</center>
   </body>
</html>
```

**Expected behavior**
I can get the info from the `requestSizing` endpoint, but I got the error since the data is very large.

gz#2442<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2442'>Zendesk ticket #2442</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-157) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
@michaelmdresser is also actively working on request sizing APIs for next release! would that impact?

**Comment by nikovacevic** [comment]
@dwbrown2 Yes, that would definitely impact -- but still possible to have nginx choke on a large payload, I'd imagine. Larger file uploads would definitely help. We can also consider composing these two features on the back-end (as opposed to yielding one result, then immediately uploading it back to _another_ API call.)

**Comment by michaelmdresser** [comment]
There are two upload steps when applying our request sizing recommendations. Based on the request information from @jjarrett21 (thanks for the excellent detail!!) this user seems to be having problems with the first step, which is uploading a recommendation API response to receive a plan; i.e., the recommendation API response is too large to upload. It is possible to have problems with the second step as well, which we could solve by doing a combined plan+apply on the backend.

The recommendation API response size [1] will be vastly improved by [2]. To get the benefits on file upload size here and resolve this issue, the request sizing plan APIs (and frontend) will have to be updated to use the v2 request sizing API.

The planning API is called with a recommendation API response [3] (this is an upload) and a plan [4] is received. Then, that plan is reuploaded to apply the recommendation [5]. Niko is absolutely correct that this situation can be improved by combining the "plan" and "apply" steps on the backend.

The stopgap measure here is to increase the upload limit.

[1] Size problems outlined in an issue https://github.com/kubecost/kubecost-cost-model/issues/585
[2] https://github.com/kubecost/kubecost-cost-model/pull/923
[3] https://github.com/kubecost/cluster-controller/blob/f8ef426ae3576b3738ac3f876ce9ea2b68869c16/pkg/requestsizer/requestsizer.go#L117-L130
[4] https://github.com/kubecost/cluster-controller/blob/develop/pkg/requestsizer/requestsizer.go#L20-L50
[5] https://github.com/kubecost/cluster-controller/blob/f8ef426ae3576b3738ac3f876ce9ea2b68869c16/pkg/requestsizer/requestsizer.go#L397-L406
