### ISSUE TITLE
Develop branch installs outdated images by default

### ISSUE THREAD

**Issue by michaelmdresser** [kubecost/cost-analyzer-helm-chart#1653]
## Repro
See the following template commands of the `develop` branch:

By default:

```
helm template kubecost ./cost-analyzer \
  --namespace kubecost --create-namespace --set prometheus.server.global.external_labels.cluster_id=CLUSTER_NAME \
  | yq '..|.image? | select(.)' | sort -u

gcr.io/kubecost1/cost-model:prod-1.92.0
gcr.io/kubecost1/frontend:prod-1.92.0
```

Can be fixed by setting `imageVersion` (or other methods, like the relevant `...fullImageName`)

```
helm template kubecost ./cost-analyzer --set imageVersion=prod-1.96.0 \
  --namespace kubecost --create-namespace --set prometheus.server.global.external_labels.cluster_id=CLUSTER_NAME \
  | yq '..|.image? | select(.)' | sort -u


gcr.io/kubecost1/cost-model:prod-1.96.0
gcr.io/kubecost1/frontend:prod-1.96.0
```

Huge thanks to jessegoodier for identifying the issue and providing the above repro commands.

## Why it matters
While developing on the Helm chart, it is natural to assume that the latest image will be used. Unexpected behavior could occur if a Helm chart change or addition expects a more recent version of the `cost-model` or `frontend` containers to be running.

This is currently not the case because our release automation only bumps the version on Release Branches and not `develop`. 

## Possible fixes
* Augment the release process to version bump `develop` for prod releases.
* Change the `develop` branch to have a version string like "dev" that causes the latest nightly images to be pulled or the latest prod images (requires [1]). (similar to [2])
* Open to suggestions!

> I don't think merging `master` or a Release Branch back into `develop` is a good strategy. I think we should maintain the independence of our Release Branches as much as possible (see [3]).

[1] https://github.com/kubecost/release-scripts/issues/21
[2] https://github.com/kubecost/cost-analyzer-frontend/pull/1007
[3] https://github.com/kubecost/release-scripts/issues/25

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-159) by [Unito](https://www.unito.io)

**Comment by michaelmdresser** [comment]
For clarity: this does _not_ affect production releases of Kubecost because our release automation correctly handles version bumping.

**Comment by mbolt35** [comment]
If we're incrementing the version #s for the release build, why are they not being merged back into develop?

**Comment by michaelmdresser** [comment]
Releases per repo _are_ tagged. See e.g. https://github.com/kubecost/cost-analyzer-helm-chart/tags

Dev branch not having an incremented version is a problem, which is why this issue is open and is what I'm hoping we can address! See also https://github.com/kubecost/cost-analyzer-frontend/pull/1007.

My personal opinion is that merging a release branch back into `develop` is not the right choice because once a release "begins" (release branch is created) that code should exist independently and only be modified by cherry picks, enabling developers to make non-release changes on `develop` without worrying about potential merge conflicts that occur as a result of code drift between a release branch and `develop`. If this isn't quite clear, I can put together a diagram.

I've offered up some ideas for how we can approach this problem and I welcome others, including merging back into `develop` if others agree -- I just don't want to make that choice because its the first one we think of.

>  Look at the README for https://github.com/researchgate/gradle-release

The gradle-release workflow seems very similar to what we do right now, including maintaining release branches separately from working branches. I could be missing something.

> find/replace version increment

At the end of the day, version information is strings in files -- we can always employ more robust methods for updating those strings, like `jq` for `package.json` and `yq` for the Helm version. I don't believe the fragility of our current method is the same as the underlying need to version bump files.
