### ISSUE TITLE
Add cluster identifier to cluster health alerts

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1655]
**What problem are you trying to solve?**
If you set up a single webhook for multiple cluster health alerts, it becomes hard to identify which alert belongs to which cluster. 

**Describe the solution you'd like**
Include the cluster id in the cluster health alerts

**Describe alternatives you've considered**
Configure multiple slack webhooks for each cluster

**How would users interact with this feature?**
Configure alert, see id

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-160) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
+1, adding to group of alerts features that will be triaged for an upcoming release!

**Comment by nealormsbee** [comment]
This item came up in a call today. I think this would be a backend thing, right? If we want to take action, let's get it into tracking and assigned to someone.

CC @nikovacevic @teevans

**Comment by nikovacevic** [comment]
I put this on my team's project (https://github.com/orgs/kubecost/projects/23/views/3) as "To Do" but unassigned. I'll have Nick or Steven jump on it next time they're free, but feel free to assign it to someone else first if it jumps in priority.

cc @teevans @AjayTripathy

**Comment by AjayTripathy** [comment]
I don't see it on the tracker @nikovacevic did I miss something?

**Comment by nikovacevic** [comment]
It's in the backlog: https://github.com/orgs/kubecost/projects/23/views/6

Do we want to prioritize it?

**Comment by AjayTripathy** [comment]
Not for 1.99-- maybe 1.100
