### ISSUE TITLE
Inaccurate Reporting on No Master Replicas in Cluster Health Page

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1659]
**Describe the bug**
The health report shows Cluster does not have replicated masters. This is for a hosted master set up in AKS with auto-scaling enabled. This doesn't seem accurate. The nodes have agent roles:

```
% kubectl get nodes
NAME                                STATUS   ROLES   AGE   VERSION
aks-agentpool-38945443-vmss000000   Ready    agent   44d   v1.22.6
aks-agentpool-38945443-vmss000001   Ready    agent   44d   v1.22.6
aks-agentpool-38945443-vmss000002   Ready    agent   44d   v1.22.6
```

**To Reproduce**

1. Go to Health tab
1. Click on Cluster Does Not Have replicated masters
1. See feedback:

![](https://user-images.githubusercontent.com/36980248/186523579-7848bdea-1a05-4342-b742-edb2a860b8c1.png)

**Expected behavior**
Not report this if using AKS hosted master set up with auto-scaling enabled.

* Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-model` and paste the output here:
* Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-frontend` and paste the output here:

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-163) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
Great point, this recommendation needs to be reviewed for all managed offerings. Do we know for sure how AKS manages the control plane? 

I believe GKE requires a regional cluster for replication, more [here](https://jayendrapatil.com/google-kubernetes-engine-gke/).

**Comment by Adam-Stack-PM** [comment]
@kaelanspatel When you have time could you add the sub category here?
