### ISSUE TITLE
Times displayed on the allocation and asset reports don't match bar data

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1666]
**Describe the bug**
It looks like the times for the bars data itself is based on local time, and will update if I change my timezone on my local machine. However, the axis details always display UTC. From what I can tell it's configured for the [bar here](https://github.com/kubecost/cost-analyzer-frontend/blob/develop/src/pages/Assets/AssetChart/RangeChart.tsx#L143-L149) and the [axis here](https://github.com/kubecost/cost-analyzer-frontend/blob/develop/src/pages/Assets/AssetChart/RangeChart.tsx#L72-L83).

**To Reproduce**

1. Go to an allocation or asset report
1. Change the date range to "Yesterday"
1. Hover a bar, and see local time, whereas the bar axis data is UTC

**Expected behavior**
Consistency with the displayed data. Maybe a way to toggle between displaying the UTC or local value.

**Screenshots**
![image](https://user-images.githubusercontent.com/43491549/186790984-c9842e63-0050-4068-80b2-2692f4c7a19e.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-165) by [Unito](https://www.unito.io)

**Comment by zorrobyte** [comment]
Hey @keithhand 

Looks like utcOffset has been depreciated, see:
https://github.com/kubecost/cost-analyzer-helm-chart/pull/1081
