### ISSUE TITLE
Add way to filter for missing labels

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1671]
**What problem are you trying to solve?**
When trying to label assets for OOC matching, it can be challenging to verify I have all my external assets labeled.

**Describe the solution you'd like**
It would be helpful to have a way to filter for all assets missing that label within the UI.

**Describe alternatives you've considered**
Manually filtering JSON results received from the API

**How would users interact with this feature?**
Currently, you can aggregate by a filter, and it will create a line item with "No label:<label-name>". I think this could be a good way for users to select that line to bring them to a list of all the assets missing that label.
![image](https://user-images.githubusercontent.com/43491549/186998500-03ab6a86-e7ad-4585-b578-457c7297906e.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-169) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
This feels like a no brainer based on my understanding! 

@keithhand would an example query be something like `service=s3` and `owner_label=""` or a functional equivalent? 

@michaelmdresser any work on filters apply here?

**Comment by michaelmdresser** [comment]
We haven't yet scheduled work for implementing v2 filters for Assets, so probably not here.

This is a good feature request for filters in general, though! I've heard a similar request on the Allocation side with a similar motivation: finding K8s workloads that don't adhere to a labeling scheme.
