### ISSUE TITLE
arm images on public ECR

### ISSUE THREAD

**Issue by aliusmiles** [kubecost/cost-analyzer-helm-chart#1672]
I've tried to install Kubecost as per [aws instructions](https://aws.amazon.com/blogs/containers/aws-and-kubecost-collaborate-to-deliver-cost-monitoring-for-eks-customers/), but sadly there are no arm images available on public ecr repo, even though arm is present on gcr repos. Would be nice to have arm on ecr too, as I'm surely not the only one trying to achieve fully-arm'ed EKS cluster :)

But please correct me if I'm wrong: I can simply use gcr images with ecr helm chart or even use chart from this github repo? The only thing that matters is eks values file, correct? Because I was under impression that following aws specific install instructions would result in some extra "eks only" functionality for Kubecost, but ecr seems to be just a mirror of gcr?

**Comment by dwbrown2** [comment]
Great request, @aliusmiles! Happy to look at posting these. 

@linhlam-kc would this just be mirroring as an initial step or more than that?

**Comment by linhlam-kc** [comment]
@dwbrown2 Hi Webb, we have required images to support ARM platform. I'm doing further testing to ensure they will work well with ECR public registry. I will update this issue soon once the changes are ready for testing.

**Comment by linhlam-kc** [comment]
Public ECR registries is updated to support multi-arch (amd64.arm64) images.
Customer can deploy Kubecost on Amazon EKS cluster with ARM-based worker nodes with the following command:

```
helm upgrade -i kubecost \
oci://public.ecr.aws/kubecost/cost-analyzer --version 1.96.0 \
--namespace kubecost --create-namespace \
-f https://raw.githubusercontent.com/linhlam-kc/cost-analyzer-helm-chart/aws-eks/cost-analyzer/values-eks-cost-monitoring.yaml \
--set prometheus.configmapReload.prometheus.image.repository=jimmidyson/configmap-reload
```

On the Amazon EKS cluster with mixed worker nodes type, this parameter can be used to schedule Kubecost deployment on ARM-based worker nodes:

```
--set nodeSelector."beta\\.kubernetes\\.io/arch"=arm64
```

Kubecost public documentation is going to be updated soon.

**Comment by dwbrown2** [comment]
Wow, thanks so much for this @linhlam-kc! 

@aliusmiles does this get you everything you need?  

@linhlam-kc see a good way to point users from blog post back here?

**Comment by aliusmiles** [comment]
Awesome, many thanks!

**Comment by linhlam-kc** [comment]
Public doc is updated. Closing this issue.
