### ISSUE TITLE
Better support for value global.additionalLabels

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1674]
**What problem are you trying to solve?**
I am trying to apply labels to every resource deployed by Kubecost.

**Describe the solution you'd like**
The `.Values.global.additionalLabels` section would indicate that it would apply labels to everything. However, that doesn't seem to be the case in practice. For example, both the node exporter and network costs daemon sets aren't updated, nor are the kubecost-prometheus-server, kubecost-grafana, or kubecost-cost-analyzer deployments.

**Describe alternatives you've considered**
Labeling each resource in the corresponding block for that feature. I.e. `.Values.kubecostDeployment.labels`

**How would users interact with this feature?**
`.Values.global.additionalLabels`

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-171) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
I like this feature request! @mbolt35 any challenges that you see or helm patterns that would point you in another direction?

**Comment by mbolt35** [comment]
I agree with this, but execution may be a bit more of a challenge (although I'm guessing this is fairly common practice on a lot of larger charts, so surely there's a clean solution we can derive from somewhere). 

We definitely want to avoid the "duplicate labels" issues that are possible when you allow settings labels from different sources. Then, we'll need to establish some level of priority (which label should "win" when there are multiple defined). As long as there is consistency, I think we should be able to template this.
