### ISSUE TITLE
Error finding abandoned workloads: json: Unsupported value: +Inf

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#1676]
This was seen in a customer install of Kubecost v1.96.0

**Describe the bug**

When viewing the Abandoned workloads page an error "Failed to load abandoned pods" is displayed. The browser developer tools console it is shown that the cause is `Error finding abandoned workloads: json: Unsupported value: +Inf`

This is a federated/Thanos backed install. I can get more information from the customer if needed.

Screenshot:
![Screen Shot 2022-08-31 at 10 15 42 AM](https://user-images.githubusercontent.com/17748044/187780476-4d737b1b-a627-4cba-8779-ab76d3309f1d.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-172) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
Never seen this before. @mbolt35 any ideas on this one?

**Comment by dwbrown2** [comment]
@jcharcalla anything obviously unusual about this cluster/deployment or able to repro?

**Comment by mbolt35** [comment]
I've got this on my list of tickets to look into - This looks like a backend issue, but it's not clear where the `+Inf` comes from given the current context.

**Comment by ivankube** [comment]
Another user is hitting the same error in 1.97.0

**Comment by AjayTripathy** [comment]
@ivankube I think I might have actually fixed this swapping the if/else case. Let's check in on this after 1.98 is released.
