### ISSUE TITLE
Unable to find "container_fs_usage_bytes" and/or "container_fs_limit_bytes" metrics

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#1677]
This was seen in a customer install of Kubecost v1.96.0

**Describe the bug**
When viewing the "Cluster Savings > Low Disk Utilization" page nothing is displayed. The browser developer console shows and error of `Warning: Unable to find "container_fs_usage_bytes" and/or "container_fs_limit_bytes" metrics`.

This is a federated/Thanos backed install and we verified the metrics are present in Thanos. Looking at the browser developer network tab I can see that there are two Prometheus queries involved in this page.

```
prometheusQuery?query=sum(container_fs_usage_bytes{id="/"}) by (instance)
prometheusQuery?query=sum(container_fs_limit_bytes…22tmpfs",id="/"}) by (instance)
```

As you can see both of these queries are [instant vectors](https://prometheus.io/docs/prometheus/latest/querying/basics/#instant-vector-selectors), and thus we believe this issue may be due to the 3 hour offset from the use of Thanos. I think this issue could potentially be resolved by adding a [offset modifier](https://prometheus.io/docs/prometheus/latest/querying/basics/#offset-modifier) in the query.

Screenshot:
![Screen Shot 2022-08-31 at 10 16 54 AM](https://user-images.githubusercontent.com/17748044/187786537-2842125d-65ff-4e38-8f59-a19e9f4457c0.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-173) by [Unito](https://www.unito.io)

**Comment by mbolt35** [comment]
@jcharcalla They're hitting `prometheus` though, the endpoint is `prometheusQuery` -- we actually have a separate endpoint for `thanosQuery`. 

The console logs from the frontend page shows the response was a 500. I think the "unable to find metric" log is misleading, as it will log that message under any failure circumstance. 

On the backend, we're just forwarding along the query body, so we only fail with a 500 if the prometheus service is unable or times out. Missing metrics would return empty data, not a 500. 

While the frontend could likely handle this scenario a bit better, I don't think this is a bug. We should add better error reporting to this page though.

**Comment by dwbrown2** [comment]
@mbolt35 investigated further and I believe there's something going on in the frontend!
