### ISSUE TITLE
Allow for shared resources to be distributed proportionality

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#168]
By default, in cluster resources are distributed evenly. A number of users have requested them be distributed proportionately to a tenants consumption of other resources. 

Technically this should be straightforward but let's determine the right API parameters.

**Comment by AjayTripathy** [comment]
Sounds good to me. I think the main question is whether we want the default to be shared evenly vs. proportionally or if we should support both even and proportionate or just one.

**Comment by dwbrown2** [comment]
Feature released in v1.49.4. Requires passing `sharedSplit=weighted` to aggregatedCostModel API. Shared expenses are weighted based on the resource costs of the individual pods in a particular aggregation.

**Comment by joerocklin** [comment]
I'm hitting a strange condition whereby if I have `allocateIdle=true` and `sharedSplit=weighted`, the shared costs go negative. I can provide more details of the queries/responses via email if needed.

**Comment by dwbrown2** [comment]
Thanks for reporting, Joe! Investigating now.

**Comment by dwbrown2** [comment]
@AjayTripathy, I was able to successfully reproduce with this request:

```
/aggregatedCostModel?window=1d&aggregation=namespace&allocateIdle=true&sharedNamespaces=kube-system&sharedSplit=weighted
```

Thanks again for reporting, Joe! We will get a fix ready and will share updates here.

**Comment by dwbrown2** [comment]
@joerocklin, we were able to find a scenario where the idleCoefficient was able to cause this problem. We have a fix being reviewed now, and are also updating our test suite. As of now, we expect this to be resolved in our next release! Will follow with further updates soon.

**Comment by dwbrown2** [comment]
@joerocklin fix complete and additional test added in v1.50.2! Please let me know if we can get you anything else here. Sorry again for not catching this particular issue at initial release.

**Comment by dwbrown2** [comment]
Joe, ready to mark this done after about a week of testing. Let me know if we can get you anything else first though!

**Comment by joerocklin** [comment]
It seems to be working in the API. Another piece I can think of related to this is in the GUI. Since we can now display shared costs there, it would be good to have a way to select the model used for display.

**Comment by dwbrown2** [comment]
We're on it!

**Comment by dwbrown2** [comment]
Joe, we've made the decision to make this the default in our frontend, so no additional configuration will be needed on your end. Implementation is done and is expected to be in our next release. Let me know if you have any questions!

**Comment by dwbrown2** [comment]
Joe, this final piece should now be complete as of our release last Friday. Let me know if we can get you anything else!

**Comment by joerocklin** [comment]
Looks good!

**Comment by dwbrown2** [comment]
Great, marking this as closed but feel free to reopen this or a new issue if you have any questions!
