### ISSUE TITLE
Azure Out of Cluster Costs only displaying for 1st of the month

### ISSUE THREAD

**Issue by calasto123** [kubecost/cost-analyzer-helm-chart#1681]
**Describe the bug**  
After following this guide: https://guide.kubecost.com/hc/en-us/articles/4407595936023-Adding-Azure-Out-of-Cluster-Cluster-Costs-into-Kubecost

We only recieve out of cluster data for what appears to be first day of the month, even though there are reports present for 2nd, 3rd and 4th of September.

![KubecostIssue](https://user-images.githubusercontent.com/99887832/188457827-c9730c4e-c388-482d-81a6-776d210b494a.PNG)

Azure is creating a Daily month-to-date export as requested in the documentation, but Kubecost does not appear to be handling it correctly.

**To Reproduce**  
1. Follow this guide: https://guide.kubecost.com/hc/en-us/articles/4407595936023-Adding-Azure-Out-of-Cluster-Cluster-Costs-into-Kubecost
2. Allow a few days of report generation
3. See that data is only displayed for 1st day

**Expected behavior**  

- Costs for each day should be displayed, not all bundled into the 1st day of the month

**Comment by dwbrown2** [comment]
Can't say I've ever seen this. 

@AjayTripathy @michaelmdresser @Adam-Stack-PM can you triage? should this go to Kubecost Support Eng?

**Comment by AjayTripathy** [comment]
Hi @calasto123 I've never seen this before. Is it possible that the report only was accessible for 1 day and then we lost access? What does it say about current access to the Azure integration at the /diagnostics view?

**Comment by Adam-Stack-PM** [comment]
@wolfeaustin, Could you look into this related to your v1.97 testing?

**Comment by calasto123** [comment]
> Hi @calasto123 I've never seen this before. Is it possible that the report only was accessible for 1 day and then we lost access? What does it say about current access to the Azure integration at the /diagnostics view?

It did appear to be displaying the metrics for one of the items in the report but not the others.

Strangely enough now there is a weeks worth of data it is displaying absolutely fine.

I'm not sure if it was a case of the azure report that was just skipping a few days. But it looks to be all resolved from my perspective.
