### ISSUE TITLE
Better Digital Ocean pricing support

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1684]
**What problem are you trying to solve?**
For customers on DO clusters, there are custom configuration options for pricing. However, it would be helpful to pull pricing API information in the same way we do AWS, GCP, and Azure.

**Describe the solution you'd like**
Add support for pulling pricing information from Digital Ocean APIs.

**Describe alternatives you've considered**
Add custom prices to a CSV or generic prices like "$CPU/hr."

**How would users interact with this feature?**
Install Kubecost on DigitalOcean and have accurate pricing.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-174) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
Thanks for this request, @keithhand! What do you think about opening a corresponding issue in the OpenCost repo as I think this is where most of the initial work will be. 

We actually recently connect with the Digital Ocean team given that a handful of users have requested this. Here's some more information based on what we've learned. Would love to see if someone in the community is interested in collaborating on this. 


https://docs.digitalocean.com/reference/api/api-reference/#tag/Sizes

```
~ doctl compute size list
Slug Description Memory VCPUs Disk Price Monthly Price Hourly
s-1vcpu-512mb-10gb Basic 512 1 10 4.00 0.005950
s-1vcpu-1gb Basic 1024 1 25 6.00 0.008930
s-1vcpu-1gb-amd Basic AMD 1024 1 25 7.00 0.010420
s-1vcpu-1gb-intel Basic Intel 1024 1 25 7.00 0.010420
s-1vcpu-2gb Basic 2048 1 50 12.00 0.017860
s-1vcpu-2gb-amd Basic AMD 2048 1 50 14.00 0.020830
s-1vcpu-2gb-intel Basic Intel 2048 1 50 14.00 0.020830
s-2vcpu-2gb Legacy Basic 2048 2 60 18.00 0.026790
s-2vcpu-2gb-amd Basic AMD 2048 2 60 21.00 0.031250
s-2vcpu-2gb-intel Basic Intel 2048 2 60 21.00 0.031250
s-2vcpu-4gb Basic 4096 2 80 24.00 0.035710
s-2vcpu-4gb-amd Basic AMD 4096 2 80 28.00 0.041670
s-2vcpu-4gb-intel Basic Intel 4096 2 80 28.00 0.041670
c-2 CPU-Optimized 4096 2 25 42.00 0.062500
c2-2vcpu-4gb CPU-Optimized 2x SSD 4096 2 50 47.00 0.069940
s-4vcpu-8gb Basic 8192 4 160 48.00 0.071430
s-4vcpu-8gb-amd Basic AMD 8192 4 160 56.00 0.083330
s-4vcpu-8gb-intel Basic Intel 8192 4 160 56.00 0.083330
g-2vcpu-8gb General Purpose 8192 2 25 63.00 0.093750
```

- Storage: DO has just one type of block storage volume (storageclass: do-block-storage). This is priced at 10 cents/GB/month.
- Load balancer: DO has just 1 type of LB priced at $12/month. Users can choose to scale LB horizontally by choosing a size count. That is configured through an [annotation in the service definition](https://docs.digitalocean.com/products/kubernetes/how-to/configure-load-balancers/#size-unit).
- Any discount is customer specific. No spot instances etc. So it is actually very simple.
- Customers get a pool of network bandwidth (eg. 1TB) for a certain droplet (eg. $40/month droplet). Generally few customers exceeding their free bandwidth pool.

**Comment by darkpixel** [comment]
I just tested on DigitalOcean and get lots of errors from various parts of the app because it doesn't appear to know the costs of running on DO, so I believe this is still relevant.

**Comment by chipzoller** [comment]
This issue is already present in OpenCost (https://github.com/opencost/opencost/issues/1396) so closing as this isn't a Helm chart bug or feature.
