### ISSUE TITLE
Bug: Read only users can still access the diagnostics page and perform operations (v1.98)

### ISSUE THREAD

**Issue by rossfisherkc** [kubecost/cost-analyzer-helm-chart#1694]
Customer concern:
```
So, I am looking at the readonly RBAC and seems like users with readonly can still view the diagnostics page and then click on it and actually repair the ETLs.
 
I don’t think Users with readonly should not have access to any of the settings page at all.
 
By the way I am using RBAC default readonly without any filters.
```

This seems related to the TODOs in this issue that may have not yet been implemented:
https://github.com/kubecost/cost-analyzer-helm-chart/issues/1164
cc @AjayTripathy @kaelanspatel

**Comment by nikovacevic** [comment]
I'll follow up later this week, to find out if there's anything not WAI here. Sounds like the user might simply disagree with us about what "readonly" should mean, and which views that should grant access to. Can revisit with @dwbrown2 and @AjayTripathy from a product perspective after the behavior is verified to be correct.

**Comment by rossfisherkc** [comment]
Just my opinion here from the DBA world, but if a readonly account is created for PostgreSQL, Redis, MongoDB, etc; such user shouldn't be able to perform potentially disruptive operations. I'd never imagine granting a read only user to perform a compact on a PSQL deployment, for example.

**Comment by dwbrown2** [comment]
I agree, repairing ETLs seems like it would not be a readonly action to me. 

I believe viewing Settings can provide helpful context to read-only users, e.g. what are pricing assumptions. Would be interested to hear if there are other perspectives here!

**Comment by nikovacevic** [comment]
Well, I can confirm that ETL rebuild/repair is not protected by any auth mechanisms. Either today or tomorrow, I'll try to put out a PR fixing those.

To be clear, this would be:
* Disabling the Diagnostics page for readonly
* Making the scary ETL endpoints admin-only

Likely going to want help from @AjayTripathy or @kaelanspatel as I do not have any experience testing SAML auth stuff, and I'd prefer to not reinvent the wheel here. I'm sure someone's set something up for that.

**Comment by nikovacevic** [comment]
FYI did not get to this today, but will revisit next week

**Comment by akramwaseem** [comment]
@nikovacevic -- Is there an update on this ?
Isn't this a security risk with Read Only users having access to ETL with  performing repairs ?

**Comment by dwbrown2** [comment]
@akramwaseem this is in process this week

@michaelmdresser can you add Steven's GH? I'm not sure what his handle is.

**Comment by michaelmdresser** [comment]
I believe its @saweber!

**Comment by kaelanspatel** [comment]
We ideally want to block rebuild and repair for all pipelines (Allocation, Asset, Cloudusage etc.), though some of these are not tied to the diagnostics page.

**Comment by akramwaseem** [comment]
@saweber  -- Cant we just grayout the diagnostic button for Read only users ?
So they dont even get to view the page ? That would make it much easier and better approach ?
What do you think ?

**Comment by dwbrown2** [comment]
@akramwaseem why would you want to disable the diagnostics page entirely vs making this particular action on the diagnostics page not accessible?

**Comment by dwbrown2** [comment]
@akramwaseem we have a number of teams where read-only users want to be able to view Prometheus status, ETL status, cloud integration status, etc. Are there situations where that would be problematic for you?

**Comment by akramwaseem** [comment]
I think I am fine with view access.

**Comment by AjayTripathy** [comment]
Closing in favor of bugs on our end to help the UI
