### ISSUE TITLE
Extend alerting to include KubeCost errors

### ISSUE THREAD

**Issue by rossfisherkc** [kubecost/cost-analyzer-helm-chart#1695]
Case #2590

Customer experienced a Thanos Error 500: parse error: bad number or duration syntax which led to Thanos being unable to ingest secondary data. This led to the customer loosing data from their secondary cluster for a few days, until they realized the issue and reinstalled KubeCost.

This seems related to https://github.com/opencost/opencost/issues/1291 as a bug fix went out in 1.96, the secondary could have been on 1.95 (we cannot be certain as it's running 1.96 since the reinstall, which resolved the issue).

The ask is to enhance our alerting to include platform and ingest issues so customers can take immediate action, instead of learning they have data loss and breakage days later that cannot be resolved. Thankfully, this was on a test cluster, it would have been a disaster, per the customer, if it were to have occurred in production.

The customer will provide more information and use case in this issue shortly, sharing it with them now!

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-176) by [Unito](https://www.unito.io)

**Comment by akramwaseem** [comment]
+1, this is kind of we needed it yesterday kind of alert.
