### ISSUE TITLE
Generate cost Estimate report based on custom CPU/RAM inputs 

### ISSUE THREAD

**Issue by akramwaseem** [kubecost/cost-analyzer-helm-chart#1696]
**What problem are you trying to solve?**
I am using 2 CPU  2GB RAM per pod with 3 pods , And it is costing me around $500 a month.
I want to increase 2 CPU to 4 CPU and 2 GB RAM to 6GB RAM but before I do that, I want to calculate the cost increase for these changes for 3 pods or I want to deploy 5 pods or 10 pods  for a week or month.

**Describe the solution you'd like**
We need a new section under Savings with tile "Cost Estimate Requests"(There might be a better name ).
With the historical data kubecost have and prize data kubecost have, should be able to generate a report with the estimates.

**Describe alternatives you've considered**
There is no option in kubecost to see this kind of report, apart from doing some calculations based on generated kubecost allocation report and get the prize for RAM and CPU and crunching some numbers with rough estimates.

**How would users interact with this feature?**
Useful for teams to estimate cost increase if in case they need to upgrade pods with more memory and cpu.
Useful to estimate cost for an application, in case they want to upgrade the deployment for more performance but want to estimate cost increase.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-177) by [Unito](https://www.unito.io)

**Comment by Adam-Stack-PM** [comment]
@akramwaseem  Thanks for this idea. 

@dwbrown2, I would love your opinion on this item. 

I like it because I see two sides to cost optimization.  

> 1)  Savings: Looking backward to identify future saving opportunities.
> 2) Budgeting: Forward Looking:  I have x dollars to spend. How best can I spend this money, and/or should I increase my budget? 

I feel both are very important and I would vote that this idea falls into budgeting.

**Comment by akramwaseem** [comment]
bump

**Comment by akramwaseem** [comment]
bump+

**Comment by dwbrown2** [comment]
Absolutely see the value in this. The complexity that I see calculating these costs before the pods are deployed is that cost can be usage driven, i.e. you may be requesting 2 cpus but using 12 and that will drive costs. 

Once the pods are deployed, Kubecost has the ability to estimate monthly costs in the Allocation view within several hours.

**Comment by wamak9** [comment]
> Absolutely see the value in this. The complexity that I see calculating these costs before the pods are deployed is that cost can be usage driven, i.e. you may be requesting 2 cpus but using 12 and that will drive costs.
> 
> Once the pods are deployed, Kubecost has the ability to estimate monthly costs in the Allocation view within several hours.

so, there are few things here to consider
Every K8s deployment is different, but in our case, we use both limit and request feature, some others might just use request feature. This means we know how much our request and limit is for pod to use.

1. so, we can take these two inputs and then generate cost model with existing Nodepool(Since Kubecost already have the node cost data available)
2. We can just take request input and generate cost model with existing Nodepool (Since Kubecost already have the node cost data available) Throw in a warning that current prediction is based on only requested CPU, if limit is applied prediction might be different.
3. Ability to export the prediction report as a format.

For V2,

all the above with nodes(VM SKUs) which are not part of kubecost existing cost model but since kubecost has ability to read SKU cost data from cloud providers, can generate a predictive cost model which doesn't need to be %100 accurate.

Let me know if this makes sense, happy to jump on call for more details.

**Comment by AjayTripathy** [comment]
@michaelmdresser has started up a "predictions" API that we expect in v1.100!

**Comment by dwbrown2** [comment]
Excited for your feedback on this initial launch!

**Comment by wamak9** [comment]
@dwbrown2  -- Isnt this feature supposed to have a UI?
Or am I missing something here ?

**Comment by teevans** [comment]
@akramwaseem - Our first pass at this leverages our kubectl cost plugin! Take a look [here](https://github.com/kubecost/kubectl-cost) and let us know what you think!

**Comment by wamak9** [comment]
@teevans -- I did look at the doc and I appreciate you guys working on the feature.
I was hoping for an UI, where PMs and Managers can interact. 
Do you have an ETA on the UI part ?

**Comment by teevans** [comment]
@akramwaseem - We don't currently have anything planned for this release. However, @dwbrown2 and @kwombach12 are likely cooking something up! I'll let them comment on when something like this might be coming.

**Comment by dwbrown2** [comment]
Yep, @akramwaseem UI coming soon! Would love to get your input on the data + format we are exposing currently. Is there anything else you're looking to see?

**Comment by kwombach12** [comment]
@akramwaseem We are planning to add a UI for our predict API in v1.102 - kubecost/features-bugs#97 ! Closing this issue for now since the API is live.
