### ISSUE TITLE
Need better labels for Cost Allocation and Need drilldown support for Multi Aggregation feature

### ISSUE THREAD

**Issue by wamak9** [kubecost/cost-analyzer-helm-chart#1708]
**What problem are you trying to solve?**

1) Cost Allocation Tab needs  more labels, so viewing pods with clusters makes it more readable
2) Also multi aggregation doesn't let you drilldown to the pod level when any of the two aggregations are selected.

**Describe the solution you'd like**
1) by default it is being aggregated by Name which gives me list of all the namespaces but I have 15 clusters with the same namespace, how do I know what cluster i that pod belongs to which is being displayed.
Cost Allocation Tab needs to display Cluster label along with the Name and CPU and soon so that if I am looking at a POD, I need to know what cluster that pod and cost belong to.
2_ I cannot drilldown to pod level like how many containers are running in a pod and how much am I paying
If 3 aggregations are selected such as namespace , cluster, deployment, I still cannot drilldown further to see how many pods am I running and what am I paying for each pod or container.

**Describe alternatives you've considered**
1) I can get the cluster context every time and filter it but its not handy when I want to do this for 15 clusters , 15 times.
if I do by POD, UI will freeze even when its back, I don't know cluster pod belongs to

**How would users interact with this feature?**

1) Cost Allocation Tab needs to display Cluster label along with the Name and CPU and soon so that if I am looking at a POD, I need to know what cluster that pod and cost belong to.
2) If 3 aggregations are selected such as namespace , cluster, deployment, I still cannot drilldown further to see how many pods am I running and what am I paying for each pod or container.

Final goal is to someone(maybe users who are not developers / devops guys) who looks at the Kubecost doesn't need to filter based on each cluster to get the cost data this is helpful for organizations with more clusters.

1) Cost Allocation Cluster label:

![cost!UNITO-UNDERSCORE!allocation](https://user-images.githubusercontent.com/15903405/191599779-a9b0326a-beb4-4b18-9f94-72e76bf22ed5.png)

2) Multi Aggregation Drilldown Image:

![kubecsot!UNITO-UNDERSCORE!multi](https://user-images.githubusercontent.com/15903405/191598394-ddd69dd0-5f6d-4df5-be12-211f38a594ca.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-181) by [Unito](https://www.unito.io)

**Comment by biancaburtoiu** [comment]
hello @akramwaseem, thank you for sharing this request!

While we currently don't support drilldown when selecting multiple aggregations (and I will raise a feature request for that), I'm spotting a few potential solutions to some of the issues you've raised:
- Aggregate by `cluster`, as well as `cluster & namespace`, `cluster & namespace & pod`, `pod & container` to clearly see which clusters the resources belong to, as well as costs at container level
- Filter queries by `cluster`,`namespace`,`deployment` to limit outputs to the desired granularity

I hope these will be helpful - please let us know if you have other questions!

**Comment by akramwaseem** [comment]
@biancaburtoiu -- I did try those and I had a session with the kubecost team. We still might need the drilldowns.

**Comment by MrJW27** [comment]
Hi @biancaburtoiu - The customer would still need the drilldowns, is it possible to review this and add to the roadmap?

**Comment by teevans** [comment]
@nealormsbee - What are your thoughts on the lift here?

**Comment by nealormsbee** [comment]
I think the lift for multi-aggregation drilldown is not too large. What we did for Assets is:

- Establish a directed graph of aggregations, to know where each drilldown "leads", e.g. `namespace -> controller`.
- For multi-aggregation, we apply *all* of the rows aggregations as filters, and go to the most fine-grained point in the graph that any of the aggregations points to.

And I think that implementation likely holds up here. The challenging thing would be if granularity isn't a well-defined concept for Allocation. We'd just have to make some decisions about rules for where we're drilling to next.

**Comment by teevans** [comment]
@nealormsbee - Ok - I think we can probably push this to 1.101 if that works. I'd call this a P2 for 100, if we can get to it great, but let's plan on attacking as a P1 for 101.

**Comment by MrJW27** [comment]
Hi @teevans - I wanted to confirm if this was resolved in V1.101? Thanks!

**Comment by kwombach12** [comment]
@MrJW27 I dont believe it will be resolved in 1.101 - @teevans correct me if im wrong.

**Comment by wamak9** [comment]
@kwombach12  -- bump and any update ?
@teevans

**Comment by nealormsbee** [comment]
Hi @wamak9,

I've just opened a PR to add multi-aggregation drilldown to Cost Allocation to the product. It should be available in 1.102. If it fails QA and cannot be resolved before the release, I'll update here. Otherwise, you can expect this feature in the next release.
