### ISSUE TITLE
Improved request sizing information

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1712]
**Problem are you trying to solve?**
The only error displayed is "Container may be underprovisioned"; however, this can sometimes be confusing in the case where one resource is underprovisioned, but another is overprovisioned. 

**Describe the solution you'd like**
A more precise explanation for the request sizing recommendations

![](https://user-images.githubusercontent.com/43491549/192395918-b11b3574-5c1e-43b5-ab9d-69fbe36fc9d5.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-183) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
Seems like a simple UI fix... I know @nealormsbee something for you to triage?
