### ISSUE TITLE
Savings - Underutilized Savings Plans and Reserved Instances

### ISSUE THREAD

**Issue by mattray** [kubecost/cost-analyzer-helm-chart#1715]
There is currently no visibility into Savings Plans or purchased Reserved Instances in the Savings tab. As a user with these attached to my account, I would like visibility into whether or not these are being consumed properly because they contribute to the entire build.

This is a feature request on behalf of a customer.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-185) by [Unito](https://www.unito.io)

**Comment by Adam-Stack-PM** [comment]
@dwbrown2 would love your thoughts here.  

Also may be interesting to help customer's transition workloads to saving plans and predictable workloads to reserved instances when relevant

**Comment by dwbrown2** [comment]
Excited to see more support here beyond our basic insights today. @mattray have any more context on what you feel would be most valuable?
