### ISSUE TITLE
Inflated Network costs estimates before GCP reconciliation

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#1720]
**Describe the bug**
When drilling into the cost allocation details page, the estimated costs for GCP networking prior to the detailed billing report reconciliation are inflated.

It has been mentioned that using [direct classification ](https://github.com/kubecost/cost-analyzer-helm-chart/blob/4fa9493251ad904ff28487632808c26bbc5a40ff/cost-analyzer/values.yaml#L607-L614) may help with the estimates in this scenario.

**To Reproduce**
This was seen in a customer install running v1.96.0, it is similar to this existing GH issue: https://github.com/kubecost/cost-analyzer-helm-chart/issues/1578

**Expected behavior**
Better estimates.

**Screenshot**
![193078587-6d3924fc-0711-42f3-ac5a-34f5be7ca7f7](https://user-images.githubusercontent.com/17748044/193340579-0dea2ce0-ab01-4f4a-b495-b301495d070b.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-187) by [Unito](https://www.unito.io)

**Comment by mbolt35** [comment]
We should look into how their scrape is setup as well. How "inflated" is it? 2x or more?

**Comment by dwbrown2** [comment]
@jcharcalla any updates on your end?

**Comment by dwbrown2** [comment]
@jcharcalla friendly ping on this, any updated information?

**Comment by AjayTripathy** [comment]
This is going to be a tough one to estimate correctly without carefully modifying the CIDR blocks for what traffic happens where. This may relate more closely to @jessegoodier filing an issue for an option to just disable estimates until reconciliation has run. (https://github.com/kubecost/cost-analyzer-helm-chart/issues/1744)

**Comment by kirbsauce** [comment]
@jcharcalla had some issue with notifications and will be updating this asap.

**Comment by jcharcalla** [comment]
Notifications are working now! I'll follow up with the customer.

**Comment by jcharcalla** [comment]
@mbolt35 For the scrape config this customer is using Victoria Metrics, not the standard Prometheus. Are there any specifics of the config you would like me to ask about?
I'm currently waiting on a reply as to how "inflated" the costs are.

For tacking purposes... this was from ZD ticket [2725](https://kubecost.zendesk.com/agent/tickets/2725)

**Comment by mbolt35** [comment]
@jcharcalla Sounds like a pretty custom setup. Prometheus operator? Can you get their helm values?
