### ISSUE TITLE
Getting AWS pricing data in air-gapped environments

### ISSUE THREAD

**Issue by tohjustin** [kubecost/cost-analyzer-helm-chart#1722]
**Describe the bug**  
When deploying Kubecost in a regular EKS cluster provisioned in a VPC that doesn't have an internet gateway (i.e. essentially an air-gapped cluster, cluster nodes doesn't have internet access), Kubecost fails to get AWS pricing data from the AWS Pricing API.

Deployment Environment
- EKS v1.22
- Kubecost v1.97.0

**To Reproduce**  
1. Provision EKS cluster in VPC that w/o internet gateway.
2. Install Kubecost on the cluster.
3. Inspect `cost-model` container logs to see error message shared.

**Expected behavior**  
Kubecost should provide a solution for us to load AWS pricing data ourselves.

**Screenshots**  
N/A

**Collect logs**

```
$ kubectl logs deploy/kubecost-cost-analyzer -n kubecost -c cost-model
...
2022-09-27T03:35:54.804730549Z ERR Bogus fetch of "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/ap-southeast-1/index.json": Get "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/ap-southeast-1/index.json": dial tcp 13.33.33.29:443: i/o timeout
2022-09-27T03:35:54.80482237Z INF Failed to download pricing data: Get "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/ap-southeast-1/index.json": dial tcp 13.33.33.29:443: i/o timeout
```

**Comment by AjayTripathy** [comment]
Hi @tohjustin thank you for the feedback. Today, you can use a custom pricing CSV (https://docs.google.com/document/d/1GgSOl_W_zchO8Yc66H4o5D37Sj46FZTWx0oU64Tq-RM/edit) to specify node or node class types. 

If that's not feasible, we could explore doing this via a JSON file we can place on the container (or possibly in s3) since it is quite large. Would one of those options work for you?

**Comment by AjayTripathy** [comment]
That sounds like a potentially quick fix. Would you need authentication around that file or could we just assume the file is at a URL  as a static endpoint @tohjustin ?

**Comment by tohjustin** [comment]
We don't need any authentication around that file, probably just specifying the S3 bucket + path to the pricing data JSON file would work for us.

---

Just spoke with Matt Ray & Jeremy Walker earlier today, we could also work with the existing [custom pricing CSV](https://docs.google.com/document/d/1GgSOl_W_zchO8Yc66H4o5D37Sj46FZTWx0oU64Tq-RM/edit) solution shared above. But we were wondering whether:

1. Is Kubecost able to reconcile RI discounts using this approach (prices of EC2 nodes in our air-gapped EKS clusters fetched from this custom pricing CSV)?
1. Does the engineering team have any scripts available to convert AWS pricing data from its API into the custom CSV format that Kubecost uses.

**Comment by AjayTripathy** [comment]
1. No-- I'm not sure reconciliation is compatible with the CSV today.
2. We don't. 

Given this, let's focus on delivering a simple URL to read the JSON from. I'd estimate we can deliver this in v1.99.

**Comment by tohjustin** [comment]
@AjayTripathy Would we eventually have RI savings reconciliation to be compatible with the CSV approach? Cause we would still be purchasing RIs for our air-gapped cluster nodes & ideally want the costs reported by Kubecost to account for the discounts too 🤔

**Comment by AjayTripathy** [comment]
Hey @tohjustin sorry for the late response. I think that's a very reasonable feature request though it isn't supported today. It's probably easiest and the least "sticker shock" (where reconciliation drifts heavily from the actual cost) if we do as suggested and drop a JSON file to read from for airgapped clusters.

**Comment by tohjustin** [comment]
@AjayTripathy @Adam-Stack-PM I've discussed with my team & seems like the fix mentioned in https://github.com/kubecost/cost-analyzer-helm-chart/issues/1722#issuecomment-1274542965 wouldn't be useful for us if the RI savings aren't reconciled.

Instead of the proposed fixed above, would it be possible to just allow the AWS Pricing API endpoint to be configurable via some Helm Chart value or Environment value for the cost-model server? (we're okay with provisioning a proxy to provide kubecost on our air-gapped cluster access to the AWS pricing API) Seems like this approach might require lower effort on your team's end & the RI savings should be reconciled as usual.

**Comment by AjayTripathy** [comment]
That makes sense to me. Is that preferred over dropping the whole API as a JSON object into the pod?

**Comment by tohjustin** [comment]
Hi @AjayTripathy, this would be much preferred over dropping the whole API as a JSON object into the pod - implementing a proxy for the pricing API on our end is a tradeoff would like to take as we prefer reconciliation to be supported since day one. 😅

**Comment by AjayTripathy** [comment]
@tohjustin PTAL at https://github.com/opencost/opencost/pull/1505 and lmk if that fits your needs!

**Comment by tohjustin** [comment]
@AjayTripathy Sorry for the late reply, was out of office for the past 2 weeks.... Yes, the PR looks good & should work for our use-case 🙏🏼
