### ISSUE TITLE
Support more configurations for Advanced Reports feature

### ISSUE THREAD

**Issue by tohjustin** [kubecost/cost-analyzer-helm-chart#1723]
**What problem are you trying to solve?**
The current functionality of the **Advanced Reports** feature isn’t able to fully replace what we used to have on our `/allocations` page back in & we’re not sure why the External Costs column was removed from the table on that page in `v1.94.0` before a proper replacement is available.

**Describe the solution you'd like**
We would like to see the following filter/options

* Hide idle cost
* Hide unallocated cost
* Allow selection of date ranges instead of fix windows (24h, 48h, 7d, 30d) — similar to the date range picker in the `/allocation` & `/assets` pages
* Allow table rows to be sorted by column values

**Describe alternatives you've considered**
No clear alternatives other than using an older version of Kubecost (before `v1.94.0`).

**How would users interact with this feature?**
Users will be able to create advanced reports to see the exact same set of data they could see back in the old `/allocation` page (before `v1.94.0`).

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-188) by [Unito](https://www.unito.io)

**Comment by mattray** [comment]
Related: 
https://github.com/kubecost/cost-analyzer-frontend/issues/1125
https://github.com/kubecost/cost-analyzer-frontend/issues/1126

**Comment by AjayTripathy** [comment]
Hi @tohjustin thanks for the feedback. @Adam-Stack-PM can we get this grouped with the other advanced reports feedback and prioritized for v1.99?

**Comment by teevans** [comment]
Hey @tohjustin - We'll actually be bringing the external column to a new advanced reports experience in 1.99 next week. I'd love to get some feedback on what you think of it when it releases!
