### ISSUE TITLE
1.96 fails to show 1.97+ upgrade available on settings page.

### ISSUE THREAD

**Issue by ErnestG4** [kubecost/cost-analyzer-helm-chart#1724]
Thanks for your interest in Kubecost!  To ensure you get the help you need, please follow these guidelines:

- If you have questions about product functionality/usage or need assistance with product installation/configuration, please email support@kubecost.com, where our support engineering team will be happy to help!
- If you have a reproducible bug or a feature request, you're in the right place.  Please include the information requested below.

---
# For reproducible bugs, please provide the following

**Describe the bug**  
Navigating to the settings page of Kubecost v1.96.x should show that an upgrade to 1.97.x is available. However, it does not. 

**To Reproduce**  
1. Run Kubecost v1.96.x
2. Navigate to the version info on the settings page
3. Observe the absence of the `upgrade available` text.

**Expected behavior**  
If a GitHub release for a version > the current version exists, then the settings page should render an `upgrade available` text.

**More Info**
Demonstrated in customer environment running Kubecost v1.96.0. 
Reproduced in a test environment running Kubecost v1.96.0 on 10/3/22.

**Comment by dwbrown2** [comment]
cc @AjayTripathy

**Comment by AjayTripathy** [comment]
I think this may have had to do with the build proces son v1.97. Let's make sure we get this fixed in v1.98

**Comment by Adam-Stack-PM** [comment]
@dwbrown2, @AjayTripathy  After researching, Kaelan and I think this item got dropped when the settings page got converted.  Marking it P0 for v1.99 for the FE team.

**Comment by AjayTripathy** [comment]
While this isn't on the /settings page, this is at least working again on the /diagnostics page for 1.96+

**Comment by wamak9** [comment]
@nealormsbee  -- I am not sure, if it's going to take time for update to show up,but I still don't see the 1.99 available notification on the diagnostic page.
I see 1.99 released yesterday.

![image](https://user-images.githubusercontent.com/15903405/207737541-4341d9e4-1c1b-4b94-9d0d-882d915e8f9a.png)



![image](https://user-images.githubusercontent.com/15903405/207737295-5279f640-75d3-4f76-8969-132d0be5f8d1.png)

**Comment by nealormsbee** [comment]
Hi @akramwaseem 👋 

This bug exists in versions 1.96, 1.97, and 1.98. This issue was closed because the banner has been added to the Settings page in the version 1.99 release. This means that if you upgrade to v1.99, you will see the upgrade banner when v1.100 is released.

We have *not* patched those earlier versions (96, 97, 98) to show the upgrade banner, and don't plan to do so, as we typically only update older versions for critical items.

I hope this is clear! If you have any additional questions or comments I'm happy to discuss.

**Comment by wamak9** [comment]
@nealormsbee  -- makes sense, thanks for the clarification.
