### ISSUE TITLE
Savings Plan Feature

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1731]
**What problem are you trying to solve?**
It's difficult to identify and stay on top of opportunities for adjustments on savings plan in aws console.

**Describe the solution you'd like**
Kubecost to be able to provide recommendations on saving plan summary https://us-east-1.console.aws.amazon.com/cost-management/home?region=us-east-2#/savings-plans/overview. Like what we have for reserved instances but for Savings Plan.

**Describe alternatives you've considered**
Right size cluster savings page but it's more focused on rightsizing workloads/instances and not Savings Plan centric.

**How would users interact with this feature?**
Savings plan in aws console is based on commitment to spend a particular dollar amount per hour over a specific period. Having a page in the savings page sort of like we do for Reserve instances so we can identify potential ways to save on compute resources and ec2 instances based on usage vs dollar amount allocated per hour would be helpful. Using data collected over time to provide feedback.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-189) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
Seems like a major focus in v1.99, wdyt @dwbrown2 ?
