### ISSUE TITLE
Single click to rebuild all ETL 

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#1732]
**What problem are you trying to solve?**

We run into issues with users needing to rebuild various etl stores and it is difficult for users to find the commands to kick off the rebuilds. 

In my experience, there is little harm in running these when there is "bad data"

**Describe the solution you'd like**

a single click to kick off:
/model/etl/asset/rebuild?commit=true
/model/etl/allocation/rebuild?commit=true
/model/etl/cloudUsage/rebuild?commit=true

Note: I don't know what the best practice is in terms of order or if they can run concurrently.
Ideally the UI would have a status for progress (start/end time) and completion pass/fail

**Describe alternatives you've considered**
NA

**How would users interact with this feature?**
button on /diagnostics
![image](https://user-images.githubusercontent.com/31039225/194574306-7487ce6a-c19c-45b9-8ca6-d37fb50354bc.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-190) by [Unito](https://www.unito.io)

**Comment by Adam-Stack-PM** [comment]
@jessegoodier , Have added this to the ETL backlog idea list https://github.com/orgs/kubecost/projects/13/views/2

Do you see any downside if this requires two clicks? 

Wondering if we should have a confirmation step that warns users this may take a few hours, and if there is only a day or two of bad data, they may want to rebuild the individual hour/day.

**Comment by jessegoodier** [comment]
> @jessegoodier , Have added this to the ETL backlog idea list https://github.com/orgs/kubecost/projects/13/views/2
> 
> Do you see any downside if this requires two clicks?
> 
> Wondering if we should have a confirmation step that warns users this may take a few hours, and if there is only a day or two of bad data, they may want to rebuild the individual hour/day.

most of the value would be to get links into the UI. 
Open to whatever is the best practice.

**Comment by DKeeling01** [comment]
@AjayTripathy 

Had a customer inquire about a similar feature, but with the following changes:

- auto detect the corrupt/missing stores
- automatically kick off the rebuild
- doesn't need to rebuild all of the stores, just the ones that are corrupt/missing (unless they are all not functional)

**Comment by AjayTripathy** [comment]
This feels like a bigger project we can look to take in in v1.100, along with alerts etc. when ETL is missing data. I guess a button could work, but it's sort of a button that brings down the app until the rebuild is complete so we'd need to be really careful.
