### ISSUE TITLE
Forecasting in Savings page

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1734]
**What problem are you trying to solve?**
It's not possible to project costs from UI if new tenants/customers are added (scaled deployments, nodes, etc).

**Describe the solution you'd like**
Add a "Forecasting" sub page under Savings page that allows user to input values such as increased/decreased number of replicas for a given deployment/workload, adding specific number of nodes and node type with specific existing workloads and provide output of projected costs for workloads under new namespace for example.

**Describe alternatives you've considered**
From my understanding, customers currently use CI/CD pipelines to achieve this with our API's https://guide.kubecost.com/hc/en-us/articles/9176161195799-Container-Request-Right-Sizing-Recommendation-API-v2-#api-examples

**How would users interact with this feature?**
When customer onboards new tenants/customers they would be able to project how much it'd cost them to run their workloads in their clusters based on existing data. They would add number of tenants/customer and define the workload within a new namespace.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-191) by [Unito](https://www.unito.io)

**Comment by tonytauller** [comment]
Please look at this example https://spot.io/resources/azure-pricing/azure-cost-management-4-ways-to-optimize-azure-costs/

**Comment by dwbrown2** [comment]
@mmurph3 @tonytauller any feedback on daily/monthly projected rate in the allocation view? https://guide.kubecost.com/hc/en-us/articles/4407601807383#cost-metric-1

This would account for a deployment scale up, new namespace, etc etc.

**Comment by AjayTripathy** [comment]
I totally think request size * projected rate is a great start. Over time, I think we will potentially want to account for stuff like taints/tolerations, savings plans, RIs, spot, etc.

Increasingly, it seems like people want forecasting tools on their own pages, which I support.
