### ISSUE TITLE
Percentage of Budget Attainment Alert

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1736]
**What problem are you trying to solve?**
Get notified before budget overrun.

**Describe the solution you'd like**
Define thresholds to trigger a budget alert.
Example: When total cost is 90% of budget threshold.

**Describe alternatives you've considered**
None

**How would users interact with this feature?**
When creating the budget alert, have an additional field that allows setting the budget percentage notification threshold. If left blank, use the existing behavior of notifying when the budget is exceeded.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-192) by [Unito](https://www.unito.io)

**Comment by srpomeroy** [comment]
Some additional feedback based on recent conversations.

Customer would like to have multiple notification paths based on budget.
Example: Notify when 50%, 90%, etc of budget

**Comment by teevans** [comment]
Does this need to be configurable? Or can we set some sensible defaults like your aforementioned 50, 75, 90?

**Comment by AjayTripathy** [comment]
I think sensible defaults seem right to me.

**Comment by srpomeroy** [comment]
> I think sensible defaults seem right to me.

Agreed

**Comment by dwbrown2** [comment]
Would propose like request sizing.. defaults but with ability to override?

**Comment by teevans** [comment]
CC @nealormsbee for visibility.

**Comment by nealormsbee** [comment]
I'm game to pick this up along with the addition of a Savings-based alert this release.

**Comment by nealormsbee** [comment]
This one totally fell by the wayside, sorry y'all. Labeling for v1.101 proposal.

**Comment by dwbrown2** [comment]
@nealormsbee I've been tracking, this is getting revisited at part of new predict APIs!

**Comment by srpomeroy** [comment]
This is now a feature in the product!
