### ISSUE TITLE
Show total cost for an object(s) by week, day month, etc. (e.g. Monthly granularity)

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1737]
**What problem are you trying to solve?**

**Describe the solution you'd like**
The ability to aggregate by specified object(s) in cost allocation page/asset page and get total cost by week, month, year.

**Describe alternatives you've considered**
Cost over time & monthly rate settings in UI when aggregating by object(s).

**How would users interact with this feature?**
Build reports showing the monthly cost per cluster for x months So user can see costs for any cluster for the past 6 months to show whether the cost of the cluster is going up or down.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-193) by [Unito](https://www.unito.io)

**Comment by derekhawkesworth** [comment]
This is a good feature available in AWS Cost explorer and really helps seeing trends over the resources.

**Comment by Adam-Stack-PM** [comment]
CC: @dwbrown2 interesting idea here.

**Comment by dwbrown2** [comment]
+1, what step sizes seem most valuable? daily, weekly, and monthly?

**Comment by derekhawkesworth** [comment]
Yes daily/weekly/monthly seems good, hourly can be useful but not as important as the others.

**Comment by mmurph3** [comment]
We have another customer whose stakeholders are also interested in this feature. Support tix #3006.

**Comment by jessegoodier** [comment]
quote from a customer:
```
Some of the reporting aspects that are very important to leadership require having weekly, monthly, and yearly type reports. If I can’t generate those kinds of reports, I’m going to need to look into another solution.
```

This was specifically for a chargeback advanced report.

**Comment by ErnestG4** [comment]
This has come up recently for several of my customers as well. 
The ultimate goal is to be able to tell a story with the data, such as "we made foo/bar/baz changes, and as you can see this is the cost trend for these clusters/namespaces/projects over this set of time". 
Yearly is its own challenge (data has to be backed up over that time period and pulled back in to generate an intensive report), but week-over-week and month-over-month are just as valuable. 

One important note is that while it is currently possible to manually create these views by exporting monthly cost aggregations from the UI and importing them into a spreadsheet, these do not include associated out-of-cluster costs. Including out-of-cluster costs via advanced reporting only allows for viewing the last 30 days of data.

**Comment by mmurph3** [comment]
@kwombach12 we also have several customers wanting this feature. Here's more context:

**Cloud Cost Report**

- Year
- Month
- Team ([<redacted>.<redacted>.kubernetes.io/team](http://<redacted>.<redacted>.kubernetes.io/team))
- Owner ([<redacted>.<redacted>.kubernetes.io/owner](http://<redacted>.<redacted>.kubernetes.io/owner))
- Environment ([<redacted>.<redacted>.kubernetes.io/environment](http://<redacted>.<redacted>.kubernetes.io/environment))
- Cost Center ([<redacted>.<redacted>.kubernetes.io/centercode](http://<redacted>.<redacted>.kubernetes.io/centercode))
- Product  ([<redacted>.<redacted>.kubernetes.io/product](http://<redacted>.<redacted>.kubernetes.io/product))
- Total Cost (Based on team aggregation & idle costs shared by cluster)

**Comment by dwbrown2** [comment]
@kwombach12 @nikovacevic @nealormsbee wouldn't this be picked up in current `step_size` feature for 1.101?

**Comment by kwombach12** [comment]
@mmurph3 thanks for flagging this. We are actually targeting adding weekly and monthly step sizes in this current release (1.101). Can you elaborate more on the context? Not sure I am getting the desired takeaway from those bullets.

Yearly step sizes (assuming the user wants to see data from several years) would take storing a tremendous amount of data. We are working in the current release toward creating a better UX for larger/more data, but multi-year reports will likely be out of scope.

cc: @dwbrown2

**Comment by kwombach12** [comment]
> @kwombach12 @nikovacevic @nealormsbee wouldn't this be picked up in current `step_size` feature for 1.101?

@dwbrown2 you beat my comment by mere seconds... yes it is scoped as a 1.101 feature

**Comment by nikovacevic** [comment]
We're going to get as far as we can for that "long running queries" epic, but we do not anticipate completing the full experience listed for that PRD in 101. We're hustling just to get a basic prototype out. So we can hopefully squeeze in a weekly and monthly granularity (i.e. accumulateBy week, month) but we will not have a weekly and monthly ETL, so it'll still be driven by daily data.

Let me know if anyone here has questions about that. Sean H is working his butt off to get the basics for us, and excited to be able to offer more "long-running query" features in the future.

**Comment by mmurph3** [comment]
do we have an eta on when we'll be able to do monthly comparisons (monthly etls) in the allocations page and other pages? I have a long list of enterprise customers wanting this. Thanks.

cc @kwombach12

**Comment by kwombach12** [comment]
@mmurph3 I have this as a proposal for our 1.106 release.

**Comment by chipzoller** [comment]
I believe this is now complete. Closing.
