### ISSUE TITLE
Add option to disable SAML port

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1739]
**What problem are you trying to solve?**
When SAML is enabled, [port 9004 gets opened](https://github.com/kubecost/cost-analyzer-helm-chart/blob/ca8e9952df26179fedd6ad00a72278c9d4d16b70/cost-analyzer/templates/cost-analyzer-service-template.yaml#L62-L66) for an additional way to access the API, some users might not want this option to be there.

**Describe the solution you'd like**
An option to disable this port from being opened.

**Describe alternatives you've considered**
Manually modify the service created by the helm chart. However, this would still leave a user open to the ability of someone with cluster access to create a service to link to this port, so it might also need to be closed within the application.

**How would users interact with this feature?**
`.Values.saml.port.enabled=false`

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-194) by [Unito](https://www.unito.io)

**Comment by clekas-fff** [comment]
It would be great to be able to have health metrics available here so that engineers can support the operations of Kubecost, but to not have any cost/usage data available since that is needed by a separate group and contains sensitive information.

**Comment by dwbrown2** [comment]
Thank you both!

@keithhand this internal port access can be limited by a network policy to all user or only those with namespace access. That's what we've seen done previously to block exposure. Are there scenarios where that's not a viable solution? 

@clekas-fff do you mean Kubecost application health metrics available at this port or something else?

**Comment by AjayTripathy** [comment]
@keithhand if you can access the namespace you can essentially access the data by exec-ing into the pod so tend to agree with @dwbrown2 here that this needs to happen at the k8s rbac level. 

@clekas-fff -- you can view /etl/status at this endpoint but more coming soon!
