### ISSUE TITLE
Endpoint not returning json: prometheusRecoringRules

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#174]
Result: "Method not allowed"
Response code: 200

**Comment by dwbrown2** [comment]
@immusk I was able to confirm that this would cause the behavior you were experiencing. I have a frontend fix to limit the impact but we are now investigating how this could happen on the backend.

**Comment by immusk** [comment]
after adding back the rules to Prometheus and by hitting this end point
`api/prometheusQuery?query=cluster:cpu_usage:rate5m`

I am getting this response, which I guess a success result.

`{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"cluster:cpu_usage:rate5m"},"value":[1576223817.088,"10.146747859436617"]}]}}`

But I am still seeing that particular dashboard is not loading and seeing that "Method not allowed" 

`api/prometheusRecordingRules`
this query is giving that "Method not allowed exception"

**Comment by dwbrown2** [comment]
Fix completed on the frontend! It will be available in the next release. 

This appears to be happening on the backend because your Prometheus is sending an expected response to this: `http://<your-prometheus-endpoint>/api/v1/rules`

Can you visit that endpoint and see what result you are getting? You should be getting a 200 with json that has `status=success`

**Comment by immusk** [comment]
@dwbrown2 

Yes, I have a got a lengthy json by hitting this `http://<your-prometheus-endpoint>/api/v1/rules` end point with a`"status":"success"` message

Can you please let me know, when the release will happen.

**Comment by dwbrown2** [comment]
@immusk, release expected tomorrow as of now!

**Comment by dwbrown2** [comment]
@immusk, this fix is now available in v1.49.3. can you confirm that this is resolved for you?

**Comment by dwbrown2** [comment]
@immusk, this fix is now available in v1.49.3. can you confirm that this is resolved for you?

**Comment by immusk** [comment]
@dwbrown2 I can confirm that this issue is fixed now. all dashboards are loading now. 👏

**Comment by dwbrown2** [comment]
Glad to hear! Please feel free to reopen if you need too for any reason.
