### ISSUE TITLE
More implicit scraping of required Prometheus metrics

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1742]
**What problem are you trying to solve?**
If you deploy Kubecost to a cluster that has many services with the Prometheus annotation `prometheus.io/scrape: true`, our bundled Prometheus will attempt to auto-scrape these endpoints, potentially leading to false positives on the diagnostics page for "Prometheus endpoints"

**Describe the solution you'd like**
More implicit scraping of our metrics and removing the reliance on the default `prometheus.io/scrape` annotation

**Describe alternatives you've considered**
Ignore false positives, remove scraping from existing services (not possible with infrastructure)

**How would users interact with this feature?**
Install Kubecost with bundled Prometheus, and it doesn't scrape existing Prometheus metric endpoints.

**Comment by thomasvn** [comment]
More specifically, this issue occurs for the [`kubernetes-service-endpoints` scrapeconfig](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/charts/prometheus/values.yaml#L1278). Prometheus will scrape all service endpoints available, and it may error out attempting to scrape API servers or monitoring stacks that require authentication.

As a potential solution, we can add to the [Kubernetes service discovery config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config) to include `__meta_kubernetes_namespace: kubecost` or (`__meta_kubernetes_endpoints_name: kubecost-prometheus-node-exporter` and `kubecost-kube-state-metrics`) to filter for only the targets Kubecost cares about.

**Comment by AjayTripathy** [comment]
I support this and like the proposed solution @thomasvn , this feel like something you can pick up for v1.99? adding the label and cc-ing @Adam-Stack-PM

**Comment by thomasvn** [comment]
Thanks for the feedback @dwbrown2 and @AjayTripathy! Yep this is something I can work on for v1.99!

**Comment by akramwaseem** [comment]
+1, This is something we need as well. This is causing lot of duplicates on metrics as well and adding our own custom config or scrape config seems more resource intensive and have to maintain in the long run.

**Comment by dwbrown2** [comment]
@thomasvn still think you'll have capacity to pick for 1.99?

One other thought: if we use `__meta_kubernetes_endpoints_name` filter we should think about network costs deamonset as well I believe. Not sure if there are others, but Nvidia's GPU utilization exporter may be one.

**Comment by thomasvn** [comment]
@dwbrown2 Thanks for keeping me on this! I'll commit to getting a first-draft PR done by next Friday (Nov 18). 

Also, thanks for that reminder! So in summary, we want to whitelist by this label `__meta_kubernetes_endpoints_name` for the following [service endpoints](https://github.com/kubecost/docs/blob/main/user-metrics.md):
* kubecost-prometheus-node-exporter
* kubecost-kube-state-metrics
* kubecost network costs daemonset
* kubecost gpu utilization exporter

**Comment by dwbrown2** [comment]
That seems right to me! Thanks, Thomas. 

@AjayTripathy @kaelanspatel may know more about these last two endpoint names

**Comment by mbolt35** [comment]
Just want to highlight that this broke cloud-agent and the metrics-exporter configurations of kubecost that leveraged prometheus.scrape: true annotations. All that had to be done is a quick search in our helm chart.
