### ISSUE TITLE
IPv6 support for network costs

### ISSUE THREAD

**Issue by mKeRix** [kubecost/cost-analyzer-helm-chart#1743]
**What problem are you trying to solve?**
I would like to use the network cost allocation on an IPv6 EKS cluster to receive granular insights into the network costs that our applications generate.

**Describe the solution you'd like**
A seamless detection of IPv6 clusters would be best, but a toggle in the Helm chart is also fine. The network-costs tool would also need to understand the IPv4 addresses that are silently mapped to pods in an otherwise IPv6-only cluster to do proper matching of all traffic.

In our case, we use Cilium on top of aws-cni, although I believe that this has no special implications for how the network cost allocation works.

**Describe alternatives you've considered**
Amazon just released a [blog post](https://aws.amazon.com/de/blogs/containers/getting-visibility-into-your-amazon-eks-cross-az-pod-to-pod-network-bytes/) about building something in this direction using Athena.

I've also tried using the existing network costs feature of Kubecost, but it does not seem to work for this setup (please correct me if I'm wrong). The logs only report IPv4 routes and `kubecost_pod_network_egress_bytes_total` is not exposed (scraping is successful, I also checked the metrics endpoints directly).

**How would users interact with this feature?**
The same way they would now - via the Kubecost dashboard.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-195) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
@mbolt35 I thought we supported ipv6 routes in the network costs pods... that not the case?

**Comment by mbolt35** [comment]
We support ipv6 routes. @mKeRix Is there a reason you think this isn't the case?

**Comment by mKeRix** [comment]
My believe is based on the `kubecost_pod_network_egress_bytes_total` metric not being reported by the network cost container, as well as the following reported log output:

```
I1025 16:57:39.940799       1 networktraffic.go:200] Removed 0 expired entries.
I1025 17:04:39.940809       1 networktrafficlogger.go:85] ------------
I1025 17:04:39.957956       1 netroutes.go:61] +----------------------- Routing Table -----------------------------
I1025 17:04:39.957977       1 netroutes.go:63] | Destination: 172.16.64.0, Route: 0.0.0.0
I1025 17:04:39.957982       1 netroutes.go:63] | Destination: 169.254.172.4, Route: 0.0.0.0
I1025 17:04:39.957985       1 netroutes.go:63] | Destination: 169.254.172.6, Route: 0.0.0.0
I1025 17:04:39.957988       1 netroutes.go:63] | Destination: 169.254.172.7, Route: 0.0.0.0
I1025 17:04:39.957992       1 netroutes.go:63] | Destination: 169.254.172.8, Route: 0.0.0.0
I1025 17:04:39.957994       1 netroutes.go:63] | Destination: 169.254.172.12, Route: 0.0.0.0
I1025 17:04:39.957997       1 netroutes.go:63] | Destination: 169.254.172.15, Route: 0.0.0.0
I1025 17:04:39.958000       1 netroutes.go:63] | Destination: 0.0.0.0, Route: 172.16.64.1
I1025 17:04:39.958003       1 netroutes.go:63] | Destination: 169.254.172.9, Route: 0.0.0.0
I1025 17:04:39.958023       1 netroutes.go:63] | Destination: 169.254.172.10, Route: 0.0.0.0
I1025 17:04:39.958027       1 netroutes.go:63] | Destination: 169.254.172.13, Route: 0.0.0.0
I1025 17:04:39.958031       1 netroutes.go:65] +-------------------------------------------------------------------
I1025 17:04:44.949197       1 conntrackwatcher.go:134] ConntrackWatcher parsed 252 conntrack entries in 4ms
I1025 17:10:39.941509       1 networktraffic.go:200] Removed 0 expired entries.
```

As suggested, I went onto the node directly to check conntrack there. Since the OS is Bottlerocket, I ran the following commands:

```
enter-admin-container
sheltie
conntrack -E
```

The output included IPv6 addresses, such as:

```
 [UPDATE] udp      17 30 src=2a05:d014:785:503:c356::1e dst=2a05:d014:785:504:a0d7:: sport=46216 dport=53 src=2a05:d014:785:504:a0d7:: dst=2a05:d014:785:503:c356::1e sport=53 dport=46216
 [UPDATE] udp      17 30 src=2a05:d014:785:503:c356::1e dst=2a05:d014:785:504:a0d7:: sport=34098 dport=53 src=2a05:d014:785:504:a0d7:: dst=2a05:d014:785:503:c356::1e sport=53 dport=34098
    [NEW] udp      17 30 src=2a05:d014:785:503:c356::1e dst=2a05:d014:785:504:a0d7:: sport=36324 dport=53 [UNREPLIED] src=2a05:d014:785:504:a0d7:: dst=2a05:d014:785:503:c356::1e sport=53 dport=36324
```

Is there anything else I could check?

**Comment by Adam-Stack-PM** [comment]
@mKeRi, Apologies for the slow reply. 

We had a few people out the last few weeks. I am getting this back on the Engineers radar.   

@ajay, could you help me route this to the right person?

**Comment by ajaykumarmandapati** [comment]
Hey is there a reason this was closed off? this is still an issue for us. Could we re-open this and try to debug further?
@Adam-Stack-PM
