### ISSUE TITLE
Add redirect link after SAML login

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1748]
**What problem are you trying to solve?**
If a user is directed to an instance deployed with SAML using a specific link (such as a report), I would like to be routed to the link after successful login. Currently, the user gets routed back to `/overview` every time.

**Describe the solution you'd like**
Route users to the link that initially opened after successful login.

**Describe alternatives you've considered**
After the user logs in, they can re-select the link to access the page desired.

**How would users interact with this feature?**
The user gets redirected after a successful login

**Comment by dwbrown2** [comment]
+1, seems like a no brainer to me. @AjayTripathy have a sense for difficulty?

**Comment by AjayTripathy** [comment]
Doesn't seem too hard. Tagging as a candidate for v1.99 cc @Adam-Stack-PM

**Comment by nimish22** [comment]
+1, This is a feature multiple users in our organization have requested. Thank you.

**Comment by Adam-Stack-PM** [comment]
Adding this to the v1.100 proposal list.

**Comment by teevans** [comment]
@kaelanspatel - Could I bother you to look at the difficulty level required to implement? It looks like we have some customer needs to implement this quickly.

**Comment by kaelanspatel** [comment]
Should be quite simple. Are we thinking a config in the HC?

Edit: Ah, sorry, we want to redirect to the page originally navigated to. Let me look into it.

**Comment by dwbrown2** [comment]
@Adam-Stack-PM let's prioritize for 1.00 if we can!

**Comment by Adam-Stack-PM** [comment]
Marking P1. Meaning we will do our best to get it in but will not delay the release for it.

**Comment by teevans** [comment]
If possible I'd like to upgrade this to P0 - We've got several companies that are requesting this directly so they're able to share reports easier with other users around the company.

**Comment by AjayTripathy** [comment]
https://stackoverflow.com/questions/24601188/how-do-i-redirect-back-to-the-originally-requested-url-after-authentication-with

Tells you how to communicate from tenant -> SAML provider -> tenant via the RelayState which the SAML provider is obligated to send back.

**Comment by Adam-Stack-PM** [comment]
@teevans Do you want to push to get this in next week or bump it up the list for v1.101?

**Comment by teevans** [comment]
Looks like @kaelanspatel already merged this in! Closing.
