### ISSUE TITLE
Allocation API fails when aggregating on annotations with a JSON string value

### ISSUE THREAD

**Issue by Atinlay** [kubecost/cost-analyzer-helm-chart#1750]
**Describe the bug**

From another pod in kubernetes, when calling the allocation endpoint with the JSON format and with an aggregation on an annotation, e.g. `http://localhost:9090/model/allocation?format=json&aggregate=annotation%3Aad.datadoghq.com%2Ftags`, where the value of the annotation is a JSON string, e.g. `'{"key": "value"}'`, I receive an error. The workaround is to call the API with the csv format, then the key of the aggregation is the JSON string.

**To Reproduce**

1. Create a deployment / pod with an annotation, e.g. `ad.datadoghq.com/tags: '{"key": "value"}'`
1. Deploy the kubecost-analyzer
1. Call allocation endpoint with an aggregation of that particular annotation: `curl http://localhost:9090/model/allocation?format=json&aggregate=annotation%3Aad.datadoghq.com%2Ftags`
1. Returns 500 server error

**Expected behavior**

Calling the allocation endpoint with json format and with an aggregation on an annotation will return a JSON string.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-199) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
Hi @Atinlay thanks for this report. Assigning to @Adam-Stack-PM  for triage, seems like a good candidate for v1.99

**Comment by Adam-Stack-PM** [comment]
@Atinlay, This is not going to make v1.99. However, it is on our radar for an upcoming release, and we will keep you updated on the progress.

**Comment by saweber** [comment]
Hello @Atinlay ! This issue has been resolved and will be released in v1.101.
