### ISSUE TITLE
Ability to drill into "No Account" Asset in assets page 

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1751]
**What problem are you trying to solve?**
It's currently not possible to drill down into No Account asset when aggregating by Account in assets page.
![](https://user-images.githubusercontent.com/36980248/197046929-ad8a3140-8386-4389-9f89-523462688502.png)

**Describe the solution you'd like**
Capability to drill down to see what resources aren't tied to an account whether it'd because the account id is missing or something else.

**Describe alternatives you've considered**
Multi-aggregating by account and service to try and find nodes that don't have accounts associated with them

**How would users interact with this feature?**
click on "No Account" and see assets with no account tied to them from kubecost perspective

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-200) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
@nikovacevic would this go away all together with new Asset store?

**Comment by AjayTripathy** [comment]
I don't think it will. In general we have created != filters in order to support this usecase and think we should follow through.

**Comment by dwbrown2** [comment]
I don't disagree, but do we know why something has no account this scenario?

@nealormsbee Looks like new filters UI doesn't support the use of != yet. That right? That would help us investigate my previous question.

**Comment by nealormsbee** [comment]
@dwbrown2 it's true; we have not migrated the frontend's logic to use the new filters API, so we don't support things like `!=`.

In addition to `!=`, I don't *think* we have a good way, with the old filters API, to ask for items where a given field is `null` or `""`. Passing e.g. `?filterAccounts=`, the filter is simply ignored. Something like `Account != *` or `!Account` in the new syntax will likely do what we want (I need to catch up on the docs for that API).

This would be why we don't currently support drilldown for the `No Account` row -- there wasn't a good way to ask for the data until recently. Agree with Ajay that we should prioritize switching the FE to the new filter API now that we have it.

I don't know what causes some assets to have no associated "Account" field ¯\_(ツ)_/¯

**Comment by dwbrown2** [comment]
Would it make sense to pick this up when @nikovacevic and @Sean-Holcomb have their new API?

**Comment by nikovacevic** [comment]
So, first thing is -- this is almost certainly your Kubernetes spend. I don't think we attribute Account to nodes, disks, etc. Yo ucan see this clearly on my cluster e.g. http://kubecost.nikovacevic.io/assets?agg=account&context=W10%3D

So one thing is figure out how to do that.

Then, in terms of "!=" filters, we can totally implement those. But today they only exist for Allocation API. So we'd start with implementing for Assets, and then we'd need to do the design and UI work to bring them through.

**Comment by nikovacevic** [comment]
And to address your point directly, @dwbrown2... if my hypothesis is correct, then our API won't necessarily solve this, but splitting the views into "Kubernetes Assets" and "Cloud Costs" will make it very clear what's happening.

**Comment by AjayTripathy** [comment]
> I don't disagree, but do we know why something has no account this scenario?

We are not entirely certain, but per @Sean-Holcomb if you don't place your account in helm configs for a multicloud setup, we aren't able to pull the account through. Not sure if there's another solution to that issue-- care to elaborate there Sean?
