### ISSUE TITLE
Compare efficiency between two date ranges

### ISSUE THREAD

**Issue by thomasvn** [kubecost/cost-analyzer-helm-chart#1755]
### What problem are you trying to solve?
I'd like to compare Kubecost's efficiency metric between two different date ranges. For example, what was our average efficiency for the "App1" namespace in Q3 of 2022 versus Q3 of 2021?

### Describe alternatives you've considered
One existing solution is Kubecost's existing chart to show "Efficiency over time". This is helpful in understanding how efficiency changes day-to-day over the course of a single date range. However you cannot compare two distinct date ranges.

![](https://user-images.githubusercontent.com/11251627/197586143-ad592d84-881b-4de7-ae65-e26a1b409814.png)

An alternative way to solve this problem is to open up two browser windows showing the Kubecost UI. One window showing the first date range. The second window showing the second date range.

### How would users interact with this feature?
With the selection of an option, users will be get a quick overview of how they're performing month-over-month, quarter-over-quarter, or year-over-year.

### Describe the solution you'd like
Unsure how this can be easily implemented. The more ambitious implementation would be the ability to select two separate date ranges in the "Date Range" dropdown menu.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-202) by [Unito](https://www.unito.io)

**Comment by ErnestG4** [comment]
Added this feature request to the tracking project. 

I have received this request from multiple enterprise customers.

**Comment by MrJW27** [comment]
@Adam-Stack-PM  or @teevans - Do we have any updates on this FR? Thanks!

**Comment by kwombach12** [comment]
@MrJW27 I dont believe we have picked up this FR yet, but I have this as a high impact FR for 1.102 - will push hard to get this into next release

**Comment by thomasvn** [comment]
Another existing workaround which is available in v1.100+, is the following number on the furthest right column of the Allocations page. I believe this number compares the total cost of this date range, with the equivalent number of days prior (e.g. the last 30 days versus the previous set of last 30 days).

![Screenshot 2023-02-22 at 9 10 00 AM](https://user-images.githubusercontent.com/11251627/220704272-943e628d-5007-4c07-8288-ae9569e38dd8.png)

**Comment by wamak9** [comment]
@Adam-Stack-PM  @kwombach12 -- I guess, This did not make it as well to 1.102

Can we update timelines so that I can provide proper feedback to users who are asking for this feature please?

**Comment by dwbrown2** [comment]
@wamak9 have you explored the new step sizes feature we just added? It actually does allow you to visualize efficiency changes week-over-week.

**Comment by wamak9** [comment]
@dwbrown2  -- I dont think we are on the same page. i dont see a use case for us to do week by week.
We want to compare month to a month.

**Comment by dwbrown2** [comment]
@wamak9 let's get on the same page then. I'm asking you if this feature is directionally useful to you in it's general implementation. We have added this for weekly first and then will bring it to other time windows assuming its current form is useful.

**Comment by wamak9** [comment]
@dwbrown2  -- I like the week or week. It is useful for us in some scenarios.
To compare the efficiency for some products.
Thanks for working on this and yeah, I will be waiting for the Month-Month.

**Comment by dwbrown2** [comment]
Great to hear, @wamak9! Working to prioritize month-to-month for you now :) Hoping it will make 104 release but will share updates.

**Comment by mmurph3** [comment]
@kwombach12 is this going to make it into v104? Are we going to have monthly etls?

**Comment by kwombach12** [comment]
@mmurph3 unfortunately, monthly etls is a heavy lift and wont make 104.

**Comment by wamak9** [comment]
bump

**Comment by wamak9** [comment]
bump @kwombach12  @dwbrown2

**Comment by chipzoller** [comment]
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.
