### ISSUE TITLE
Allow "Unmounted PVs" costs in allocation view to be aggregated by namespaces

### ISSUE THREAD

**Issue by tohjustin** [kubecost/cost-analyzer-helm-chart#1759]
**What problem are you trying to solve?**

* If a PV is dynamically provisioned by a PVC in Namespace A
* The PV isn’t mounted by any pods in Namespace A
* Kubecost allocates the cost of such unmounted PVs under a cluster-wide group called “Unmounted PV” on the /allocations page

In order to implement proper PV cost chargebacks on our tenants, we need to be able to aggregate such cost by namespace (i.e. Namespace `A`) regardless of whether PVs dynamically created by their PVCs are mounted by any pods or not.

**Describe the solution you'd like**

Allow "Unmounted PVs" costs in allocation view to be aggregated by namespaces.

* Statically provisioned PVs: Aggregate into cluster-wide “Unmounted PV”
* Dynamically provisioned PVs: Aggregate into namespaced “Unmounted PV”

**Describe alternatives you've considered**

N/A

**How would users interact with this feature?**

When viewing cost allocations filtered by namespace(s), user can see a "Unmounted PV" row in the table if the PV(s) dynamically provisioned by the PVC(s) in the namespace(s) are not being mounted by any containers within the workspace.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-203) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
I think this needs some investigation since we don't necessarily have the data of who provisioned a PV, just that the PV exists and hasn't been mounted. That being said I am going to add it to the v1.99 proposal, though it needs some scoping.

**Comment by Adam-Stack-PM** [comment]
@kaelanspatel, Does https://github.com/opencost/opencost/pull/1477 close this issue, or is there more work to be done?
