### ISSUE TITLE
What does 'SummaryAllocation: detected invalid sharing coefficient' mean?

### ISSUE THREAD

**Issue by mikementzmaersk** [kubecost/cost-analyzer-helm-chart#1760]
Really like the product !
Just a quick query, we are seeing this warning message and would like a hint as to what it might mean?

WRN SummaryAllocation: detected invalid sharing coefficient for CLUSTER1//rook-ceph/csi-cephfsplugin-wbks4/driver-registrar: 0

I wondered if the two slashes after cluster_id were anything or not - just looked odd..

**Comment by AjayTripathy** [comment]
Mike, thanks so much for the feedback. I believe this means we weren't able to compute a coefficient for the total cluster costs, possibly because kubecost was installed recently and we're missing historical data.

@nikovacevic  am I on the right track? can you help clarify what this means?

**Comment by nikovacevic** [comment]
@AjayTripathy is correct that we weren't able to compute a coefficient -- but it appears to actually be much simpler than that. The `0` at the end of the log indicates that the cost of the container was $0.00, and we log if the coefficient is not `> 0.0`. (The coefficient is `container cost / cluster cost`` or `container cost / node cost`.) We should just disable the log for coeffs == 0.0.

**Comment by AjayTripathy** [comment]
Great find!!

**Comment by nikovacevic** [comment]
Tackling this now.
