### ISSUE TITLE
Ensure that label aggregation properties are populated in final aggregation items

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1765]
**What problem are you trying to solve?**
When viewing a report based on labels, if you select more than one aggregation type, the label can be dropped from the `properties` section of the API response. This will happen if the second aggregation type doesn't include the same label, even if the aggregation might match. 

**Describe the solution you'd like**
If you have a report based on an aggregate label, that label should be propagated to all associated line items.

**Describe alternatives you've considered**
Use single aggregation types so as to not run into conflicts. Another option is to infer the label based on the values in the report.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-204) by [Unito](https://www.unito.io)

**Comment by Adam-Stack-PM** [comment]
@keithhand, I Want to make sure im clear. Does this relate to when you view a saved report or when you use the allocation view regardless if you have the view/report

**Comment by AjayTripathy** [comment]
This happens regardless.
