### ISSUE TITLE
/spot 500 error: error performing cluster sizing for spot-ready workload

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#1779]
500 error on 

```
error performing cluster sizing for spot-ready workload distribution: WorkloadDistribution's clusterID cluster-one does not match a calculated monthly cluster rate
```

link to HAR: <https://kubecost.slack.com/files/U0325HCDR17/F0499RDB9B6/spot_instances_500.har>

**To Reproduce**

I have not reproduced this error. This is for the same customer in the issue here: https://github.com/kubecost/cost-analyzer-helm-chart/issues/1761

Essentially, Kubecost is not running on all clusters that are in the aggregated Prometheus metrics (cortex). 
Though I'm not sure if that is the root cause.

1. Go to 'savings>spot>'
1. 500 error

Happy to get logs as needed.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-205) by [Unito](https://www.unito.io)

**Comment by biancaburtoiu** [comment]
@jessegoodier thanks for your patience here!

As part of the spot cluster sizing API call (`/savings/spotChecklistClusterSizing`) we run an asset query (aggregated by cluster) to obtain the cost of all nodes in the cluster in the given time window. We then use this value to derive an estimated monthly cost. 

The error returned here indicates that no nodes were found for `cluster-one` in the query results. 

The query should have the following parameters: `window: 1d, step: 24h, accumulate: true, aggregateBy: cluster, filterTypes: node`. Would the customer be able to reproduce this so we could have a look at the outputs?

**Comment by jessegoodier** [comment]
customer ran:
```
/model/savings/spotChecklistClusterSizing?accumulate=true&filterTypes=node&window=1d&aggregateBy=cluster
```
result:
```
spot-ready workload distribution not available for local cluster ID cluster-one
```

**Comment by jessegoodier** [comment]
sorry for my delay!

**Comment by biancaburtoiu** [comment]
I realise I was unclear in the previous comment in the sense that the query params I described were meant to be used for an `/assets` call and not for a `/spotChecklistClusterSizing` call. Could we try to get the following query outputs from the customer to have a look over the raw asset data, to see if we can find any results corresponding to the `cluster-one` cluster?

- `/model/assets?accumulate=true&filterTypes=node&window=1d&aggregateBy=cluster`

The second error here is along the same lines as the one pointed out a couple of days ago - out of all _allocations_ queried, there wasn't any with `allocation.Properties.Cluster = cluster-one`. Could we have a look at the asset data first and identify the error starting from there?
