### ISSUE TITLE
Build Reports/Send Alerts and Export capability with data from each sub page under Savings page.

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1783]
**What problem are you trying to solve?**
Reporting, exporting and sending capabilities in each of the sub pages under savings page.

**Describe the solution you'd like**
Same functionality available in cost allocation, assets and alerts page but for savings page.

**Describe alternatives you've considered**
Giving kubecost access to various teams/people wanting to see savings page and recommendations.

**How would users interact with this feature?**

Configure alerts to be sent with data available in savings page
Build and save reports from data in the savings page.
This would be ideal for presentations and for sending data to targeted teams/individuals. It would limit the need to configure user access which in turn reduces overhead.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-207) by [Unito](https://www.unito.io)

**Comment by kc-creynold** [comment]
this came up on a customer call the other day as a needed feature

**Comment by dwbrown2** [comment]
Starting to dig into reports/alerts in 1.99 and I suspect will be ready to focus here in the following release. 

Any detailed use cases or specific personas that either of you have heard?

**Comment by rossfisherkc** [comment]
I have a customer on ZD 3095 planning on chiming in their case case here; I offered to pass it along if they couldn't for some reason. Will update once I hear something

**Comment by amitkc1** [comment]
Use case and Persona:

**Comment by amitkc1** [comment]
**Use case and Persona:**
On a high level, the use case is to provide savings report and savings alerts similar to what's available for Allocation and Assets.  For clarification, I am also attaching some screenshots. 
![Screen Shot 2022-12-04 at 3 43 02 PM](https://user-images.githubusercontent.com/2672595/205524733-845055c5-87c7-46ed-8021-ce056a2f8280.png)

![Screen Shot 2022-12-04 at 3 43 13 PM](https://user-images.githubusercontent.com/2672595/205524552-a0a80468-2a55-47eb-ac92-ea4107b5c9d5.png)

The persona for each of the savings types can vary. Here is my take on the personas who can use these reports/alerts:
1. Right size container requests - **Application owner** based on Namespace and cluster
2. Abandoned Workloads - **Application owner** based on Namespace, cluster
3. Resize local disks, Reserve instances ,  Unclaimed volumes, unassigned resource, identify workloads ready for spot instances, resize your persistent volumes - **Administrator/ Provisioner** of the cluster


Here are a couple of scenarios where these alerts/reports could help:
1. Send an alert when savings after right sizing container requests could go up by certain "Cost threshold". Allow filtering 
   by namespace and cluster both.
2. The same is applicable for abandoned workloads. 
    *  Send a report to the application owner and/or administrator on a regular cadence about abandoned workloads.
     * When the abandoned workloads have gone up by certain threshold, send an alert.

**Comment by rossfisherkc** [comment]
cc @dwbrown2 ^

**Comment by AjayTripathy** [comment]
Seems reasonable, tagging for a 1.100 proposal

**Comment by nealormsbee** [comment]
This seems like a useful extension of the Alerts we have today. I don't think we have anything scoped for v1.100 as of now.

I don't foresee having bandwidth for big coverage here this release, but maybe we can start with one savings view and start planning out the rest?

**Comment by teevans** [comment]
^^ Let's give that a shot

**Comment by mmurph3** [comment]
@teevans I'm thinking this would be good to have under the 'Reports' page. Perhaps add the option under actions where the user could set email addresses/s3 bucket endpoints/webhook and the interval at which to send a saved report in pdf or csv format? pdf export and email address would be top priority. We have an enterprise customer who would like to automate prebuilt reports and send them out at preset intervals.

**Comment by mmurph3** [comment]
Hi Team, we have more customers looking for this feature to build reports from savings page and ability to send alerts automatically on preset/predefined intervals.

**Comment by kwombach12** [comment]
@mmurph3 this feature makes a lot of sense to me. I will push for this to be included in the next release and see if we have the bandwidth to potentially squeeze this into this current release.

cc: @dwbrown2

**Comment by mmurph3** [comment]
@kwombach12 thanks! Here is more context and an example one of our customers would like to see for savings report, along with automation to send report every 30 days for example.

**Cloud Cost Savings Report**
- Year
- Month
- Team ([<redacted>.<redacted>..kubernetes.io/team](http://<redacted>.<redacted>..kubernetes.io/team))
- Owner ([<redacted>.<redacted>.kubernetes.io/owner](http://<redacted>.<redacted>..kubernetes.io/owner))
- Environment ([<redacted>.<redacted>..kubernetes.io/environment](http://<redacted>.<redacted>.kubernetes.io/environment))
- Cost Center ([<redacted>.<redacted>.kubernetes.io/<redacted>](http://<redacted>.<redacted>.kubernetes.io/<redacted>))
- Product  ([<redacted>.<redacted>.kubernetes.io/product](http://<redacted>.<redacted>.kubernetes.io/product))
- Total Possible Savings

**Comment by keithhand** [comment]
A little additional context from what I have heard from customers regarding the "pre-built reports". There are current alerts that have some of this data, though the formatting is significantly different than if you were to look at the data directly in the application. For example, a recurring update alert and an allocation report display a lot of similar data, but the recurring update won't have all the details an allocation report will have. Ideally, users are looking for a way that we could utilize the "Download as PDF" button in a more "cron"-like format to send those downloaded PDFs directly via alerts.

**Comment by kwombach12** [comment]
@keithhand @mmurph3 We are picking up this work in 1.102 so I wanted to make sure I am clear on what the asks are in this issue. Please feel free to correct me, but I am seeing a couple distinct asks here:

1. Create a new report type, "Savings Report" for each/any of the savings cards
2. Enable Allocation, Asset, Cloud Cost, & Savings Reports to be sent as .pdfs with a configurable cadence.

Is there anything you would add to these 2 enhancements? Is there anything else I'm missing?

**Comment by mmurph3** [comment]
@kwombach12 :

1. I think it'd be beneficial here to allow users the option to build a savings report summary from sub pages of their choosing. It's important here to respect custom setting such as filters applied in the Right-size your container requests page, duration in abandoned workloads, custom container right sizing profiles and any other setting set in each sub page set by the user that's not default. The report(s) would also be exportable to pdf. 
2. Yes, we have several customers who'd like to send built reports with a configurable cadence - allocation, advanced reporting, cloud cost/assets being highest priority. Savings would be a huge plus. 
Example:
a) Every week, month, custom interval - send a report of last 7, 30days, custom to the following email addresses set . <-- Some/most users will want the data in the reports reconciled with the bill from the cloud provider for accuracy. We could add an option "Data Reconciled?" yes/no. If yes, +/-3 days (not sure what makes the most sense) of the specified window. Users that select no will most likely not be pulling in a bill from the cloud provider or they're on prem.


Let me know if you'd like more info from customers or want to brainstorm what this would look like.

**Comment by mmurph3** [comment]
We have another enterprise customer who would like report sent on a regular cadence (auto). 2 customers would like the ability to send to s3 buckets due to security requirements and internal processes.

**Comment by mmurph3** [comment]
@kwombach12 are we going to have ability to export pdf & csv in abandoned workloads page in v1.103?

**Comment by kwombach12** [comment]
@mmurph3 we are going to try to squeeze in .csv export for that page.

**Comment by mmurph3** [comment]
@kwombach12 are we going to see the ability to send reports on a set cadence in v1.103? I recall us discussing that the alerts functionality was going to be moving to reporting and that 'last 30days' was also going to be added so users can send some sort of report on a set cadence greater than the 7 days currently available in alerts.

**Comment by kwombach12** [comment]
@mmurph3 Unfortunately, we didnt have capacity to pick this up in 103

**Comment by mmurph3** [comment]
@kwombach12 did this make it in v1.104?

**Comment by chipzoller** [comment]
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.
