### ISSUE TITLE
Reintroduce `gpuRequestAverage` and `gpuUsageAverage` to the Allocation API Schema

### ISSUE THREAD

**Issue by thomasvn** [kubecost/cost-analyzer-helm-chart#1787]
### What problem are you trying to solve?
Currently when calling the Allocation API (example below), we are only returned `gpuCount`, `gpuHours`, `gpuCost`, and `gpuCostAdjustment`.

To get a better understanding of how the GPUs are actually used, it would be nice to add `gpuRequestAverage` and `gpuUsageAverage` to the Allocation API Schema (similar to how `cpuCoreRequestAverage` and `cpuCoreUsageAverage` exist in the schema)

```
/model/allocation?window=yesterday&accumulate=true&shareIdle=true&reconcile=true&idleByNode=true&aggregate=node
```

### Background
This feature was previously introduced in [PR #944](https://github.com/opencost/opencost/pull/944), however it needed to be rolled back in [PR #965](https://github.com/opencost/opencost/pull/965).

Given that Kubecost now has a backwards-compatible ETL [PR #624](https://github.com/kubecost/kubecost-cost-model/pull/624), this new Allocation Schema can be re-introduced.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-209) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
Just as a note, those aren't standalone; they require deploying a metric collector to run that isn't straightforward. I'm happy to bring those back, just know that getting the relevant exporters running on clusters can be a challenge. I think we can look to bring this back in an alpha state though for v1.99 and provide a guide for spinning up the gpu usage exporters. @kaelanspatel thoughts?

**Comment by kaelanspatel** [comment]
Agree for reintroduce, would be nice to support. 

Like Ajay says, this was initially designed to use the `DCGM_FI_DEV_GPU_UTIL` metric from the Nvidia DCGM. Old setup document [here](https://docs.google.com/document/d/1fsbV55wTbpfWy4m9_FVETqHgtTMahfUa2w5MzV9gngc/edit). If we find some time, we might want to look at other metrics and/or the state of the DCGM, the `DCGM_FI_DEV_GPU_UTIL` metric was moved to off by default in the DCGM and I wonder if there's been an alternative since for a raw usage number.

**Comment by AjayTripathy** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/pull/1805 FYI when we reintroduce. Need to scrape the DCGM exporter by default for ease of setup.

**Comment by Howlla** [comment]
Is DCGM enabled by default now?

**Comment by thomasvn** [comment]
@Howlla Feature to scrape & process DCGM metrics not currently available

**Comment by worr** [comment]
Howdy! Are there any plans to reintroduce this feature in the near future? It's something I know we'd find quite useful.

**Comment by chipzoller** [comment]
This is planned in https://github.com/opencost/opencost/pull/2731. Closing this issue as it is not Helm specific.
