### ISSUE TITLE
Lower memory consumption of network-cost daemonset

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1790]
**What problem are you trying to solve?**
A lot of network traffic is being monitored and the driving force of costs within org. It's not cost effective to run the network-cost daemonset because it's ~2,000 euros/week to run this. It is need however to identify spend and inefficiencies accurately among different teams. 

**Describe the solution you'd like**
Lower memory consumption by only mapping to destination instead of the full pod object. Trim down functions.

**Describe alternatives you've considered**
1. Deploy network-cost daemonset without CUR.
2. Network-cost daemonset reconciling with the CUR.
3. Setting CPU limits.

We need lower memory consumption. We understand the option of setting CPU limits but this is not a solution since our concern is with the memory. Memory is what's being taxed. 

We have a shared ingress controller we run. The egress costs goes back to ingress. The nodes where that run on is where we see the hotspot. Push ~100mb to 200mb of traffic a min. That traffic goes to other pods internally. There might be 90 pods running on that node, but 1/90 pods is responsible for network traffic. This is one reason why we need the network-cost daemonset

heapdump screenshots attached.
<img width="1190" alt="Screenshot 2022-11-03 at 2 23 40 PM" src="https://user-images.githubusercontent.com/36980248/200333327-3bc2a184-7d9b-4941-b3a4-80f115708f2b.png">
<img width="1211" alt="Screenshot 2022-11-03 at 2 24 30 PM" src="https://user-images.githubusercontent.com/3698024
<img width="1219" alt="Screenshot 2022-11-03 at 2 25 34 PM" src="https://user-images.githubusercontent.com/36980248/200333354-8b231c09-4a49-4641-a2ad-023dc890ee10.png">
<img width="1071" alt="Screenshot 2022-11-03 at 2 22 16 PM" src="https://user-images.githubusercontent.com/36980248/200333355-4cac460d-6779-409f-b487-0393944be3b8.png">
8/200333328-86375703-70dd-4259-bd16-c04254eb27a4.png">

**Comment by mmurph3** [comment]
<img width="1211" alt="Screenshot 2022-11-03 at 2 24 30 PM" src="https://user-images.githubusercontent.com/36980248/200339078-e8eac3e5-c6bb-45eb-8b73-9d5711cea2d8.png">

**Comment by AjayTripathy** [comment]
Hey @mmurph3 we have an image with substantial improvements available here: [gcr.io/kubecost1/kubecost-network-costs:testhostnodenetworkmap2](http://gcr.io/kubecost1/kubecost-network-costs:testhostnodenetworkmap2)

Pushing to make it default in 1.99  but the user can swap out with the test image to see if there's an improvement.

**Comment by mmurph3** [comment]
@AjayTripathy thanks ! We've received great feedback on this from various customers. Waiting on original customer to test. I'll close this for now.
