### ISSUE TITLE
Divide sharedOverhead/sharedNamespaces/sharedLabels proportionally

### ISSUE THREAD

**Issue by myrthebil** [kubecost/cost-analyzer-helm-chart#1791]
**What problem are you trying to solve?**
We would like to divide sharedOverhead/sharedNamespaces/sharedLabels proportionally over our aggregation by owner. This way our larger fish owners can carry some weight for the smaller fish in our pond.

**Describe the solution you'd like**
We are looking for a way for the costs defined in sharedOverhead to be divided proportionally over our aggregation by owner. If the owner has a large number of allocations, we'd like to see the sharedOverhead/sharedNamespaces/sharedLabels divided proportionally. 

**Describe alternatives you've considered**
For now, we are trying think of a way to spread the costs in an xls sheet, looking up the number of allocations per owner and then dividing it proportionally.

**How would users interact with this feature?**
A user would fill in the amount in sharedOverhead and select the method to divide - [ split equally | divide proportionally | other.. ]

**Comment by AjayTripathy** [comment]
@myrthebil have you taken a look at the https://github.com/kubecost/docs/blob/main/allocation.md#querying shareSplit option here? Does that help at all?

**Comment by myrthebil** [comment]
@AjayTripathy thanks, we can definitely use this in the development of our workaround.

**Comment by teevans** [comment]
@myrthebil - Closing for now, let us know if there is anything else we can help you with!
