### ISSUE TITLE
Azure duplicated out of cluster costs

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1797]
**Describe the bug**

After enabling an out-of-cluster report on an Azure cluster, it seems some objects are being duplicated and not reconciled with the correct Kubernetes resources within the cluster. The specific objects that were noticed to be a problem seem to be related to Load Balancers.

**To Reproduce**

1. Enable Azure OOC
1. Check the Assets report for "microsoft.network" and "Microsoft.Network"
1. Notice what appears to be a duplicated line item

**Expected behavior**

A single line item that is reconciled back with the "Kubernetes" line item

**Screenshots**

![image](https://user-images.githubusercontent.com/43491549/200918640-377f0419-3cf1-43a7-ae16-d749e3a77cf2.png)
![image](https://user-images.githubusercontent.com/43491549/200919106-74754c85-332d-4d5d-a057-500ffb41d911.png)
![image](https://user-images.githubusercontent.com/43491549/200919261-fbe0e270-5d59-4c35-9af2-7331815560ba.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-210) by [Unito](https://www.unito.io)

**Comment by cr-benchmarkcorp** [comment]
Thank you Keith.   It's less of a 'duplication' issue than it is a 'correlation' issue.   Azure bills two different ways for the same object.   Therefore, the cost model is different for the same object, but they should be correlated together, imo.   Beyond that, these things belong to a Managed Kubernetes deployment (AKS in this case), and should therefore ALSO be correlated against "Kubernetes" in KubeCost.    

Organizations (of any size) need to understand TCO of Kubernetes (Managed or on-prem), therefore holistic correlation is absolutely necessary...in the Cloud, or on-prem, and any provider.

In this case Azure, AKS.

**Comment by AjayTripathy** [comment]
Thanks for this report! To confirm, this isn't an accuracy issue but an issue of where the data is displayed? We're reworking some of these pages and can take a look after that redesign. 

Just as a note, afaik there's no way to directly correlate the exact LB in the AKS cost and usage report with how the LB is tagged/labeled in Kubernetes (@Sean-Holcomb to confirm).
