### ISSUE TITLE
Simplifying Custom Prom Install

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#1798]
This step, as part of using a custom Prom, has always seemed unnecessary to me. Could we not just tell Prom to scrape Kubecost in our service via annotation? We could have this enabled by default but easily turned on by a single flag.

Seems like this would greatly simplify the setup because most teams wouldn't have to touch their Prom configs. 

![](https://user-images.githubusercontent.com/298359/200920401-b31a3801-62cc-42b5-bab4-feb884b429bf.png)

Source: https://guide.kubecost.com/hc/en-us/articles/4407595941015-Custom-Prometheus

Thoughts thomasvn @jessegoodier?

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-211) by [Unito](https://www.unito.io)

**Comment by mbolt35** [comment]
We have no way of knowing what the custom prom setup is like. We can't just expect that it can automatically scrape our data, right?

Our instructions are definitely necessary for someone without service discovery configured, and if they have service discovery configured, our instructions provide a reasonable guide to the configuration options to set. 

I believe we have all the necessary options in helm to deploy operator components for cost-model as well. I'm not sure what other options we have.

**Comment by dwbrown2** [comment]
What's preventing us from doing just what `kube-state-metrics` does? https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/charts/prometheus/charts/kube-state-metrics/templates/service.yaml#L17

My understanding is that the vast majority of teams use service discovery for ksm and it works well.

**Comment by mbolt35** [comment]
It doesn't seem like much of an issue to say: "Here's the instructions on how you would manually add Kubecost to your scrape configs", and let whoever is managing the custom prometheus determine the appropriate action for adding it. This just feels like a case where we're giving instructions to support the non-service discovery user at a minimum. IMO, it's much worse to just leave off this information and expect that things will work automatically on a custom setup. 

Now, if you're saying that we don't even have a way of enabling prometheus service discovery options on our service, then yeah, we should definitely add that.

**Comment by dwbrown2** [comment]
> Now, if you're saying that we don't even have a way of enabling prometheus service discovery options on our service, then yeah, we should definitely add that.

I think that's what I'm saying haha, if we do it's not at all documented as part of this setup!

**Comment by mbolt35** [comment]
We support this when you deploy kubecost as a separate metrics exporter! https://github.com/kubecost/cost-analyzer-helm-chart/blob/23f6d28743f5a9c110899f293e22df680a497e2e/cost-analyzer/templates/kubecost-metrics-service-template.yaml#L16-L19

**Comment by mbolt35** [comment]
@dwbrown2 There may be some deeper complexity here that I'm misremembering, but I definitely agree we should have a flag that can enable this. We do it for network-costs as well as the cost-model as a metrics exporter.

**Comment by jessegoodier** [comment]
For those that run prometheus that supports service monitors (most?), I think this works today:
```
helm upgrade --install kubecost --repo https://kubecost.github.io/cost-analyzer/ cost-analyzer \
  --set global.prometheus.enabled=false \
  --set serviceMonitor.enabled=true
```

For the others, we just need what @mbolt35 has above with the scrape annotations.

It would just take a little templating to add the annotations to the cost-analyzer pod.

**Comment by dwbrown2** [comment]
Good call out, Jesse. Thoughts on quickly adding Bolt's suggestion on adding to our service plus documenting both paths in this resource above? I think either would be significantly easier than asking teams to directly edit their scrape configs.

**Comment by AjayTripathy** [comment]
Adding a little additional helm templating sounds plausible and I support this, just want to ask the question if our existing global.podAnnotations field + strong documentation wouldn't cover this rather than making a code change?

https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L48

would support doing this either way but bias towards writing less code/adding less flags when possible.
