### ISSUE TITLE
Cluster Health Monitoring is not allowing to modify of the threshold

### ISSUE THREAD

**Issue by praveenkumar0566** [kubecost/cost-analyzer-helm-chart#1802]
# For reproducible bugs, please provide the following

**Describe the bug**  

Cluster Health Monitoring is not allowing to modify of the existing values of "**_Health change threshold_**" and "**_Window_**"

![image](https://user-images.githubusercontent.com/102574445/201350172-621a24ba-e25a-4dd4-984e-db6d8efe20f7.png)

The above error occurs on hitting the test button after modifying the existing values of the Health change threshold and Window in the Monitor Cluster Health window

**To Reproduce**  
Steps to reproduce the behaviour:
1. Go to 'Alert '
2. Click on 'Monitor Cluster Health'
3.  modify "**_Health change threshold_**" and "**_Window_**" in Monitor Cluster Health window -> click _**save**_ -> click "**_Test Alert_**"

**Expected behavior**  
Monitor Cluster Health should allow modifying the existing  values of the **Health change threshold** and  **Window** 

**Screenshots**  
![image](https://user-images.githubusercontent.com/102574445/201349985-ea770b70-fccb-46c4-a775-83723cc6be52.png)

**Comment by dwbrown2** [comment]
Thanks for sharing, @praveenkumar0566! Can you share what version you're running?

cc @Adam-Stack-PM to track as a potential 1.99 bug fix

**Comment by praveenkumar0566** [comment]
I see this bug in 1.96, 1.97 and in 1.98, Maybe it was hidden since the previous versions :)

**Comment by nealormsbee** [comment]
I'll try to pick this tomorrow. Context if someone else needs to take it:

It looks like we're setting "threshold" as a string instead of a number when it's user-modified, and not converting it before sending to the server. We just need to convert the threshold value to a number for the request JSON payload.

**Comment by nealormsbee** [comment]
A PR fixing this issue is now open. The bug should be resolved in our v1.99 release! Thanks for the report @praveenkumar0566
