### ISSUE TITLE
Modify OIDC setup to support AzureAD

### ISSUE THREAD

**Issue by biancaburtoiu** [kubecost/cost-analyzer-helm-chart#1808]
**What problem are you trying to solve?**
It is currently not possible to configure our current OIDC implementation under the AzureAD provider. The `authURL` configuration under AzureAD requires a unique `nonce` among the request parameters for every login request ([see AzureAD docs](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc)). At the moment, the `authURL` is a configurable parameter in the Kubecost Helm chart `.values.oidc.authURL` and, once set, it can't be manipulated further.

**Describe the solution you'd like**
Introduce a boolean `isAzureAD` flag in the Helm chart OIDC settings (default false), which, when activated, can intercept the authURL and append a randomly-generated string as the required nonce. See the AzureAD docs for any further work to be done here; it is recommended to parse the nonce claim within the returned ID token and compare it against the previously generated nonce before granting user access to the application.

**Describe alternatives you've considered**
Using a static nonce is not recommendable for security reasons.

**How would users interact with this feature?**
Users interested in integrating with AzureAD OIDC would set `isAzureAD=true` in the OIDC Helm chart configs.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-213) by [Unito](https://www.unito.io)

**Comment by biancaburtoiu** [comment]
cc @jessegoodier @kaelanspatel

**Comment by AjayTripathy** [comment]
Is there any harm in just always adding the nonce? That way we can skip additional configuration? Aren't nonces in all specs?

https://openid.net/specs/openid-connect-core-1_0.html#NonceNotes
