### ISSUE TITLE
Broken URI for keyinstructions section

### ISSUE THREAD

**Issue by michemoche** [kubecost/cost-analyzer-helm-chart#1809]
Hello,
In the last version, you fixed the broken URI redirection for some links when you have kubecost deployed in a subpath (like /kubecost/[...])

But I've found another one 

when you go to settings > Cloud Cost Settings > Update 
it redirects you to /keyinstructions instead of /kubecost/keyinstructions

adding the subpath manually works fine

**Comment by AjayTripathy** [comment]
@nealormsbee  seems like a quick fix?

**Comment by nealormsbee** [comment]
Quick indeed! Thank you for the report @michemoche. A PR to resolve this issue is submitted, and it will be fixed in v1.99.

**Comment by michemoche** [comment]
awesome, thanks guys ! :)
