### ISSUE TITLE
Slack URL should be masked in Monitor Cluster Health

### ISSUE THREAD

**Issue by praveenkumar0566** [kubecost/cost-analyzer-helm-chart#1813]
**What problem are you trying to solve?**
When we try to edit "Monitor Cluster Health" configurations, one can see the Slack webhook URL as plaintext. 

<img width="736" alt="Screenshot 2022-11-21 at 5 59 31 PM" src="https://user-images.githubusercontent.com/102574445/203056651-6f36d88d-d06a-42d0-9468-d460ff4a2bf2.png">

**Describe the solution you'd like**
Like SLACK URL is masked in **Monitor Kubecost Health**, The URL should also get masked for **Monitor Cluster Health**

**Describe alternatives you've considered**
We can adopt a solution to pick the URL from a secret from HELM, like https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L198

**How would users interact with this feature?**
This feature is requested for fixing the security leak.

**Comment by AjayTripathy** [comment]
@teevans sounds like this is a quick one that we want to knock out for v1.99 . @Adam-Stack-PM can you add to the buglist?

**Comment by dwbrown2** [comment]
@praveenkumar0566 does it not obfuscate once saved? can you share what version you're running?

**Comment by praveenkumar0566** [comment]
@dwbrown2  Yes, this doesn't get obfuscated after saving, Observed in 1.96,1.97 and 1.98

**Comment by teevans** [comment]
@jjarrett21 - Can you jump on this?

My idea is this: When there is a token, change the placeholder to "Token hidden" - Verbiage up for debate there

When there is not a token, make the placeholder "https://hook.slack.com/xxxxxxxxxx/xxxxxxxxxx" 

Make sense?

**Comment by jjarrett21** [comment]
![Screen Shot 2022-11-29 at 2 12 00 PM](https://user-images.githubusercontent.com/14066631/204638034-13202b01-df43-4016-8413-2403e5050186.png)
![Screen Shot 2022-11-29 at 2 11 51 PM](https://user-images.githubusercontent.com/14066631/204638039-9b9f5f7d-62c8-4532-ae53-f032f3c852b5.png)
 What doe we think about something like this instead has the placeholder but treats the field like a password? @teevans

**Comment by teevans** [comment]
I think that works for now. Let's a get a PR going. I want to re-visit this experience in the near future though.

**Comment by jjarrett21** [comment]
I can do the other thing with some regex or with some yup magic so I'll swap this and get a PR up.

**Comment by Adam-Stack-PM** [comment]
Closing based on connected PR.
