### ISSUE TITLE
GKE cluster management free tier credit not reflected in Kubecost (with GKE Integration Enabled) 

### ISSUE THREAD

**Issue by kc-adawson** [kubecost/cost-analyzer-helm-chart#1818]
- - -
# For reproducible bugs, please provide the following
**Describe the bug**

Kubecost on GKE Cluster does not reflect Free Zonal Cluster Management Fee, with cloud integration enabled.

**To Reproduce**

1. On an account with a single GKE 'zonal' cluster, install Kubecost on the cluster.
1. After cost metrics are collecting and GCP Billing is integrated, go to "Assets".
1. There will be a "Cluster Management" charge showing in Kubecost, a charge that is shown as credited in the GCP Billing.

**Expected behavior**

Expected behavior would be that "Cluster Management" would show credits within Kubecost when there are matching credits in the GCP console.

**Screenshots**

Kubecost shows Cluster Management as an uncredited charge:

![](https://user-images.githubusercontent.com/101200254/203372723-643cc83e-a6f7-4cc3-bb91-fd54c0d3afc4.png)

The console shows the Cluster Management fee as a credited charge:

![](https://user-images.githubusercontent.com/101200254/203372776-cfcafb98-a0f9-44d1-b72a-98a16284ab7e.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-216) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
I think this is likely because we draw "cluster management" as an "in cluster" cost where I think it really should not be anymore. @nikovacevic this is changing for the new Cloud Assets pipeline, correct?

**Comment by nikovacevic** [comment]
I don't believe @Sean-Holcomb and I have finalized where Cluster Management fees are going to fall in the new Cloud Costs work. (I think it makes slightly more sense for it to NOT be considered in-cluster, but that creates some friction with the spec.) If it's not considered in-cluster, then this should be solved by faithfully reflecting the CUR data.
