### ISSUE TITLE
Grafana not working in certain Thanos deployments

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#182]
Grafana dashboards are reporting `Templating Init Failed`. After initial investigation, we suspect this is related to the Thanos sidecar being deployed.

**Comment by AjayTripathy** [comment]
Potential issue: zone information hardcoded at https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/templates/grafana-datasource-template.yaml#L23 . We should swap this to the service address without .svc.cluster.local

**Comment by dwbrown2** [comment]
Confirmed that this was caused by Prometheus being not available
