### ISSUE TITLE
Timestamp is not available in csv report generated by kubecost

### ISSUE THREAD

**Issue by azizzoaib786** [kubecost/cost-analyzer-helm-chart#1822]
**What problem are you trying to solve?**
When generating the report from kubecost UI, it generates the perfect csv but somehow timestamp is missing.

**Describe the solution you'd like**
Date/Timestamp column in the csv report.

Sample report without any timestamp/date column aggregated by namespace.

```
Name,CPU,GPU,RAM,PV,Network,LoadBalancer,External,Shared,Efficiency,Total
"newrelic",24.43,0,8.87,0.06,0,0,0,6.38,0.1674310134533946,39.74
"pos",6.4,0,2.06,0,0,0,0,1.61,0.10360300115565402,10.07
"platform-backend",4.8,0,1.04,0,0,0,0,1.12,0.07903842643945132,6.96
"customer-care",4.37,0,1.05,0,0,0,0,1.03,0.10888320931553017,6.45
"observability",3.51,0,0.66,0.18,0,0,0,0.83,0.1427050327334455,5.18
```

Is there any possibility of providing adding this column by default in the report?

**Comment by dwbrown2** [comment]
@azizzoaib786 would this be beginning end of report time window for the entire report or something else?

@teevans @nealormsbee, if it's the former, we just added this functionality to new PDR reports so I'm guessing quick?

**Comment by azizzoaib786** [comment]
@dwbrown2 may be the duration time window? for example duration start & duration end? similar to what we have in the json output when you use the kubecost api.

Or end of report time will make sense if the cost is cumulative. What do you think?

**Comment by teevans** [comment]
Hey @azizzoaib786 - We'll knock this out for 1.99!

**Comment by nealormsbee** [comment]
One implementation question here. For reports with N rows, do we just print the same timestamp N times in its column? The time is like a piece of metadata for the whole report, but I don't think CSVs accommodate that kind of thing.

**Comment by AjayTripathy** [comment]
Think it's fine to just reprint the timestamp

**Comment by dwbrown2** [comment]
If it's metadata for the entire report, I personally would just put it in a sub title or footer. Repeating also seems acceptable though.

**Comment by dwbrown2** [comment]
Closed with a PR expected to be in 1.99!

**Comment by azizzoaib786** [comment]
@dwbrown2 is it already done? I saw that 1.99 is released so this feature is already integrated?

**Comment by teevans** [comment]
@azizzoaib786 - Yes! This is live in V1.99!

**Comment by azizzoaib786** [comment]
@teevans But I don't see the 1.99.0 docker image out in ECR
https://gallery.ecr.aws/kubecost/cost-analyzer

Do you know when it will be available for use?

**Comment by teevans** [comment]
@azizzoaib786 - Sorry about that - That release is a little behind our current channel. 

@linhlam-kc should be able to give more details, but I believe he is OOO right now. As soon as he's back we'll have an update!

**Comment by dwbrown2** [comment]
FYI, these images will typically be published concurrent with release. We currently have a teammate that manages that is experiencing a major illness. We hope to get him back soon.

**Comment by linhlam-kc** [comment]
Hi all, v1.99 images and helm charts are now available on the ECR public gallery.
