### ISSUE TITLE
"values-eks-cost-monitoring.yaml" should be updated accordingly for newer kubecost version 1.98

### ISSUE THREAD

**Issue by smartbenson1** [kubecost/cost-analyzer-helm-chart#1832]
**What problem are you trying to solve?**
The value for the following file in the chart is not updated to 1.98
https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values-eks-cost-monitoring.yaml

**Describe the solution you'd like**
The docker image version for kubecost should be updated to 1.98

**Comment by thomasvn** [comment]
@linhlam-kc I recommend removing the [`.Values.imageVersion`](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.98/cost-analyzer/values-eks-cost-monitoring.yaml#L36) altogether. If you do so, the template will default to ` - image: {{ .Values.kubecostModel.image }}:prod-{{ $.Chart.AppVersion }}` as shown [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.98/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L307-L319).

This way, you won't need to manually update the `imageVersion` for each Kubecost release.

**Comment by linhlam-kc** [comment]
> @linhlam-kc I recommend removing the [`.Values.imageVersion`](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.98/cost-analyzer/values-eks-cost-monitoring.yaml#L36) altogether. If you do so, the template will default to ` - image: {{ .Values.kubecostModel.image }}:prod-{{ $.Chart.AppVersion }}` as shown [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.98/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L307-L319).
> 
> This way, you won't need to manually update the `imageVersion` for each Kubecost release.

Thank you @thomasvn . I created a PR to fix it at https://github.com/kubecost/cost-analyzer-helm-chart/pull/1867 . That flag was enabled initially to address few early issue of the integration.

**Comment by AjayTripathy** [comment]
I went ahead and merged this for you @linhlam-kc
