### ISSUE TITLE
Multiple filters, NOT just namespace when creating alerts

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1834]
**What problem are you trying to solve?**
It's limiting not being able to use multiple filters when creating alerts and defining thresholds, etc.

**Describe the solution you'd like**
Ability to use multiple filters (labels) in the UI when creating alerts. For example, filtering by cluster and product and NOT just namespace. 
![](https://user-images.githubusercontent.com/36980248/205692577-35edfb50-4bb9-4665-9572-585905f77a32.png)

**How would users interact with this feature?**
Add multiple filters (labels) under Filter text box in Alerts when creating thresholds.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-219) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
cc @nealormsbee know the limitation here today? i believe the backing APIs support.

**Comment by nealormsbee** [comment]
Yes and no.
Yes, in that the alerts utilize ETL queries, which support these other filters.
No, in that the Alerts section of the API code expects filters to be a comma-delimited list of namespaces, and saves/handles them with this expectation.

So in addition to a UI update, we'd need to:

- Change the public-facing `/alerts` api
- Migrate existing user's alerts to a schema that supports more complex filtering

I think we should do it! I just want to characterize the effort involved accurately.

**Comment by Adam-Stack-PM** [comment]
@nealormsbee, Are you thinking we should push to get this into v1.99 or push to a future release?

**Comment by nealormsbee** [comment]
Most definitely a future release.

**Comment by AjayTripathy** [comment]
As a habit can we tag stuff as v.(n+1 release)-proposal when we need to push?

**Comment by nealormsbee** [comment]
Works for me!

**Comment by Adam-Stack-PM** [comment]
> As a habit can we tag stuff as v.(n+1 release)-proposal when we need to push?

@AjayTripathy, great suggestion!

**Comment by rafal-skurka** [comment]
any chance of implementing it soon? It would be great to get a similar filter like in reports.
