### ISSUE TITLE
AWS Resource tags in s3 CUR integration have s."resourceTags/user:Name prefix

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1835]
**Describe the bug**  
AWS Resource tags in Assets page show a s."resourceTags/user:Name prefix. This is with custom CUR [1] setup (manually pulling/uploading CUR files to an s3 bucket) and this string is present, s."resourceTags/user:, at the beginning of all tags on AWS resources. Example: s."resourceTags/user:kubernetes_namespace=<namespace>. Checked on the AWS side, the tag is set as kuberenetes_namespace=<namespace>. See kubecost instance [2] with a working s3 csv-cur integration for issue.

**To Reproduce**  
1. Go to Assets Page
2. Aggregate by service, see tags
3. See 

**Expected behavior**  
Tags should not have s."resourceTags/user: prefix

**Screenshots**  
<img width="1572" alt="image" src="https://user-images.githubusercontent.com/36980248/205750931-5bc372a9-d4b4-40fa-aa94-d1d3daee46b0.png">

[1] https://docs.google.com/document/d/1ONphj866XBXZWRvmZbAgFwy35joECht7NS3TnjJA-yc/edit#heading=h.ob1hyrtb9yfj
[2] http://sso.papasmurph.kubecost.xyz/assets?agg=service

**Comment by mmurph3** [comment]
https://github.com/kubecost/kubecost-cost-model/blob/develop/pkg/provider/awscurfetcher.go

**Comment by AjayTripathy** [comment]
This looks like a really quick fix, stripping out the prefix "resourceTags:user/". I think it can make it into v1.99.

**Comment by nikovacevic** [comment]
Looks to me like this line: https://github.com/kubecost/kubecost-cost-model/blob/develop/pkg/provider/awscurfetcher.go#L331 is trying to `TrimPrefix(tagColumnName, "resourceTags/user:")` but should be `TrimPrefix(tagColumnName, "s:\"resourceTags/user:")`.

That said, it looks like @Sean-Holcomb specifically changed it from that to what it is now here: https://github.com/kubecost/kubecost-cost-model/commit/62cd8cfb0873c0d4a5a0e6cda73574794315fbd6

Anything you can share on this @Sean-Holcomb ?

**Comment by Sean-Holcomb** [comment]
Yeah looks like I was fixing the label column matching but broke the label clean-up

**Comment by nikovacevic** [comment]
Is this quick to test? If so, can someone share how to do that, and I can set up someone on the team to make that 1-liner change and verify that it works? (Or I can make a quick change and hand off for testing?)

**Comment by AjayTripathy** [comment]
I think @mmurph3 volunteered to take an image and deploy to his cluster, then rebuild Cloud Assets, right? :)

**Comment by Adam-Stack-PM** [comment]
@AjayTripathy, Would you call this P1 or P0?

**Comment by nikovacevic** [comment]
It's done: https://github.com/kubecost/kubecost-cost-model/pull/1103

Just need to merge and cherry-pick.

**Comment by nikovacevic** [comment]
And cherry pick is open here: https://github.com/kubecost/kubecost-cost-model/pull/1104
