### ISSUE TITLE
When using `aggregate` with the Allocation API, it does not always list the full set of properties

### ISSUE THREAD

**Issue by thomasvn** [kubecost/cost-analyzer-helm-chart#1839]
## What problem are you trying to solve?
When using the `/model/allocation` API and using an aggregation such as `aggregate=label:app`, some of my line items are missing the “properties.namespace” value (example below).

```bash
$ curl -G http://my.kubecost.com/model/allocation \
  -d window=2022-12-01T00:00:00Z,2022-12-02T00:00:00Z \
  -d aggregate=label:app \
  -d shareIdle=false > kubecost.json

# Shortened example result
$ cat kubecost.json
{
    "code": 200,
    "data": [
        {
            "app=cost-analyzer": {
                "name": "app=cost-analyzer",
                "properties": {
                    "cluster": "cluster-one",
                    "node": "ip-xxx-xxx-xx-xx.us-west-1.compute.internal",
                    "controller": "kubecost-cost-analyzer",
                    "controllerKind": "deployment",
                    "namespace": "kubecost",
                    "pod": "kubecost-cost-analyzer-7d85bbf798-gvkld",
                    "providerID": "i-xxxxxxxxxxxxxxxxx"
                },
                ...
            },
            "app=hello-world": {
                "name": "app=hello-world",
                "properties": {
                    "controllerKind": "deployment"
                },
                "window": {
                    "start": "2022-10-01T00:00:00Z",
                    "end": "2022-10-02T00:00:00Z"
                },
                ...
            }
        }
    ]
}
```

I suspect this is an issue because when aggregating on `label:app`, one of the line items `app=hello-world` may be deployed to multiple namespaces. If that is the case, Kubecost will have multiple conflicting values available for "properties.namespace", and will therefore omit "properties.namespace" altogether.

We can verify this by running the query again without `-d aggregate=label:app`, and verifying all of the “properties.namespace” values exist.

## Describe the solution you'd like
If there are multiple clashing properties when performing an aggregation, I would like the kubecost-cost-model to list all available "properties" instead of omitting them.

## Describe alternatives you've considered
We can hypothetically work around this issue by doing the following:

```bash
# 1) No aggregation. View the properties of each workload (deployment/daemonset/statefulset) as its own line item
curl -G http://my.kubecost.com/model/allocation \
  -d window=2022-12-01T00:00:00Z,2022-12-02T00:00:00Z \
  -d shareIdle=false > kubecost.noaggregation.json

# 2) Aggregation
curl -G http://my.kubecost.com/model/allocation \
  -d window=2022-12-01T00:00:00Z,2022-12-02T00:00:00Z \
  -d aggregate=label:app \
  -d shareIdle=false > kubecost.json

# 3) Run a custom script to reconcile all properties available in "kubecost.noaggregation.json" with "kubecost.json"
./reconcile-properties.sh
```

## How would users interact with this feature?
When using an aggregation on the `/model/allocation` API, users would have a more verbose list of properties for each line item.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-220) by [Unito](https://www.unito.io)

**Comment by thomasvn** [comment]
Additionally, here is a [doc](https://docs.google.com/document/d/1NN8ZeWd541S-sRyDQfwc1uTjA17YdBbR5LcqFOcJIog/) describing how to reproduce the issue in my environment.

**Comment by AjayTripathy** [comment]
Hey @thomasvn as discussed, it's not clear what to do when properties conflict. We've had this feature request before and can continue to discuss or talk about adding a flag to ensure all properties propagate even on conflicts, but the best workaround is to simply aggregate on the properties you'd like to propagate.

**Comment by thomasvn** [comment]
@AjayTripathy Thanks for the clarification! I agree that the simplest workaround to this Feature Request is to perform a multi-aggregation on `/model/allocation`. This is better than my original suggested workaround.

```
curl -G http://my.kubecost.com/model/allocation \
  -d window=2022-12-01T00:00:00Z,2022-12-02T00:00:00Z \
  -d aggregate=namespace,label:app \
  -d shareIdle=false > kubecost.json
```

**Comment by AjayTripathy** [comment]
Can we make sure this gets documented in an FAQ somewhere , maybe in the API docs, and we can look to perhaps add a flag that supports unioning disparate properties together in an upcoming release.

**Comment by thomasvn** [comment]
@AjayTripathy Merged a docs PR to add this to the FAQ! Also, a multi-aggregation example already exists on the API docs as shown [here](https://docs.kubecost.com/apis/apis/allocation#query-examples).
