### ISSUE TITLE
AWS Cloud Integration “No Athena Bucket Configured”

### ISSUE THREAD

**Issue by thomasvn** [kubecost/cost-analyzer-helm-chart#1840]
## Describe the bug
When setting up AWS Cloud Integration via the user interface, the UI displays “No Athena Bucket Configured” despite having properly set up the Cloud Integration.

![](https://user-images.githubusercontent.com/11251627/206060276-e18ebec9-e79d-4699-ad55-b7988c625bb1.png)

However, when setting up AWS Cloud Integration via the Helm values, there are no errors.

## To Reproduce
1. Ensure you are starting with configs that are known to work (i.e. configs that have been tested via Helm values as well)
1. Go to [http://my.kubecost.com/settings](http://my.kubecost.com/settings)
1. Cloud Cost Settings -> External Cloud Cost Configuration (AWS) -> Update -> Enter your AWS Cloud Integration configs here
1. Hit the following endpoint to start the CloudUsage pipeline: http://my.kubecost.com/model/etl/cloudUsage/rebuild?commit=true
1. Hit the following endpoint to start the Reconciliation pipeline: http://my.kubecost.com/model/etl/asset/reconciliation/run?commit=true
1. Verify that you can see out-of-cluster costs and adjustments in the “/assets” view.
1. Go to http://my.kubecost.com/diagnostics and check whether the “No Athena Bucket configured” diagnostic is red

## Expected behavior
The “No Athena Bucket configured” diagnostic should have a green check mark.

## Screenshots
Screenshot verifying that my Cloud Integration was successfully set up:

![](https://user-images.githubusercontent.com/11251627/206060613-235eabc2-553f-4260-9d40-4b9d1e86365e.png)

Screenshot verifying that the CloudUsage and Reconciliation pipelines both successfully ran:

![](https://user-images.githubusercontent.com/11251627/206060643-a23f59a4-bb38-46b3-a2bc-9669119f2641.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-221) by [Unito](https://www.unito.io)

**Comment by thomasvn** [comment]
Additionally, here is a [doc](https://docs.google.com/document/d/1pPZegY7vhbP8JMTXW0PtI-YFPjrFXfYZvuGozx-l8Ck/) describing how to access my environment to test the issue.

**Comment by Adam-Stack-PM** [comment]
A note on this issue from a conversation with Ajay.

> "Most people set this up via helm config, so I don't think this is p1 for 1.99, but it feels like we should commit to this for v1.100"

Pushing to v1.100.
