### ISSUE TITLE
Add options for 30, 60, 90 days to Date Range drop down when creating Alert (retroactively and proactively).

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1842]
**What problem are you trying to solve?**
Having a quick and efficient option in the drop down query items month/past 30 days, 60days, 90 days in addition to the alert existing custom date range function.

**Describe the solution you'd like**
Ability to use the drop down to query for predefined # of days. 30, 60, 90. 30 being most desirable. Ability to do this retroactively and for the frequency at which to run these queries moving forward (future queries).
![](https://user-images.githubusercontent.com/36980248/206298939-2afe4c24-485c-4a2f-a27b-11737f03965c.png)

**Describe alternatives you've considered**
Setting the custom date range - but this only allows 7 days max.

**How would users interact with this feature?**

Users will go to Alerts page and create an alert and choose a predefine date range of 30days, 60 days, 90 days and get alerted on past events and a second option for setting query frequencies in the future.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-223) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
Seems reasonable, just as a note you should be able to add these via configmap. But tagging as a proposal for v1.100

**Comment by dwbrown2** [comment]
+1 @teevans @nealormsbee, can we start using one consistent FE window module across all of these use cases? Think this same scenario applies to multiple savings pages, and more.

**Comment by nealormsbee** [comment]
We do have a reusable Window selection component that would be easy to swap in here! Although it uses MUI components and we need to assemble one for our custom UI kit.

I'm a little fuzzy on my memory of Alerts implementation. I want to say we custom-limited this to 7d because that was the max range supported at the time. But that's probably not the case now.

Big +1 to standardizing window selection across pretty much everything.

**Comment by Jose-Matsuda** [comment]
@AjayTripathy could you direct me towards some documentation that shows me how to do this (as in adding the extra date ranges to the UI)? I've looked through the documentation and issues but haven't really seen anything 😔 .

**Comment by srpomeroy** [comment]
Any chance we can target this for v1.102?

**Comment by teevans** [comment]
Tagging @kwombach12 / @dwbrown2 for priority!

**Comment by dwbrown2** [comment]
I would say P1/2, but should be quick now that we have the reusable component?

**Comment by teevans** [comment]
Assuming backend supports the longer windows, yes! - @Sean-Holcomb / @michaelmdresser - Can I bother one of you two to chime in on if the alerts API supports a longer than 7D window?

**Comment by michaelmdresser** [comment]
> chime in on if the alerts API supports a longer than 7D window?

The window parameter of an alert config appears to be fully variable [1]. The only thing I can see that would prevent a longer alert from functioning is a lack of data (not running long enough or not enough retention) or _maybe_ performance of such a long query; rule of thumb would be if you can load the window on the FE, you can set it as an alert window.

https://github.com/kubecost/kubecost-cost-model/blob/8f3834d53c0b4d1d33099aeb04006c7ee57b4dd0/pkg/alerts/alertconfigs.go#L36

**Comment by srpomeroy** [comment]
@kwombach12 Any plans to support an alert window greater than 7 days (via UI) in 1.105/1.106?

**Comment by kwombach12** [comment]
@srpomeroy It likely wont be delivered in 105/106. We now have the ability to auto send saved reports which can have any window. Are there specific alerts which you'd like to see these new windows for?

**Comment by srpomeroy** [comment]
Allocation Spend Change and Allocation Efficiency

**Comment by kwombach12** [comment]
@srpomeroy ok. I'm not sure if this will fit in 105, but I will add as a proposal for 106

**Comment by nealormsbee** [comment]
Added an issue to the 106 Epic in Jira: https://kubecost.atlassian.net/browse/FRONTEND-300

@kwombach12 you can close it as a dupe if you made one already.

**Comment by chipzoller** [comment]
Closing, appears complete.
