### ISSUE TITLE
efficiency missing on request sizing v2

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#1843]
**Describe the bug**  

Pods without deployment/ds/rs do not have efficiency calculations. We have some large customers that deploy these pods via ci/cd jobs and would like to track the efficiency.

**To Reproduce**  
http://nightly.kubecost.io:9090/request-sizing (enable v2)

**Expected behavior**  

% Calculation on table.

**Screenshots**  

![image](https://user-images.githubusercontent.com/31039225/206299675-5d5a15a3-b969-4315-a429-9c93ce8235c3.png)

@michaelmdresser and I have discussed this already.

**Comment by michaelmdresser** [comment]
I think this may have something to do with the API's [special handling of uncontrolled pods](https://github.com/kubecost/kubecost-cost-model/blob/develop/pkg/savings/requestsizing/v2/helpers.go#L73-L80) interacting with [aggregation](https://github.com/kubecost/kubecost-cost-model/blob/develop/pkg/savings/requestsizing/v2/requestsizing.go#L502)/joining logic used for [appending efficiency info to the recommendations](https://github.com/kubecost/kubecost-cost-model/blob/develop/pkg/savings/requestsizing/v2/requestsizing.go#L309).

Can investigate later, but don't have time this week unless determined priority for v1.99 (@Adam-Stack-PM)

**Comment by AjayTripathy** [comment]
@michaelmdresser this definitely seems like a priority to me for v1.99, since it will block people from using request sizing v2 entirely

**Comment by dwbrown2** [comment]
Tend to agree! Would call P1 in my view. 

cc @Adam-Stack-PM

**Comment by michaelmdresser** [comment]
On it

**Comment by michaelmdresser** [comment]
Being cherry picked into the v1.99 release: https://github.com/kubecost/kubecost-cost-model/pull/1119
