### ISSUE TITLE
Kubecost Integration with Tableau Analytics Platform

### ISSUE THREAD

**Issue by DKeeling01** [kubecost/cost-analyzer-helm-chart#1848]
**What problem are you trying to solve?**
Users are looking for ways to ingest Kubecost data in new and interesting ways. One recent request the ability to integrate Kubecost metrics with the Tableau Analytics Platform to provide a single pane of glass for cost analysis data

**Describe the solution you'd like**
Create integration of Kubecost with Tableau using one (or more) of the following connectors/methods:

Web Data Connector
Analytics Extensions API
Dashboard Extensions API
Connector SDK

More info here:

https://www.tableau.com/developer/tools

**Describe alternatives you've considered**
NA - Specific request to meet customer needs

**How would users interact with this feature?**

Tableau Desktop
Tableau Cloud
Tableau Mobile

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-224) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
Thanks @DKeeling01  for the suggestion. We want to instrument more connectors for the API but meanwhile, this can be instrumented with our API, right?
