### ISSUE TITLE
Region selection for price calculation

### ISSUE THREAD

**Issue by ricardojdsilva87** [kubecost/cost-analyzer-helm-chart#186]
Hello everyone,
My question is if it's possible to configure different region for price calculation via the helm chart/another?

On the cost-analyzer pod logs I can see the following messages:
I1223 10:32:07.637701       1 awsprovider.go:540] starting download of "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.json", which is quite large ...
I1223 10:32:07.680652       1 awsprovider.go:546] Finished downloading "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.json"

That means that the us-east-1 region is configured by default as it seems. Is there any place I can change that?
Thanks

**Comment by dwbrown2** [comment]
Hi @ricardojdsilva87, thanks for reaching out. Can you share more on what you are looking to accomplish with this? Note that this json file actually has pricing data for all AWS regions.

**Comment by ricardojdsilva87** [comment]
Hi @dwbrown2, the idea was to have specific costs for each region since there are small differences.
Didn't knew that the json file had the prices for every region, probably was misled only by the URL of the download, thought it was used based on the region configured.
Thanks for the help
