### ISSUE TITLE
Cloud Costs API alpha release

### ISSUE THREAD

**Issue by nikovacevic** [kubecost/cost-analyzer-helm-chart#1868]
In v1.99, Kubecost is releasing an alpha version of a new Cloud Costs API and pipeline, which will be available only on AWS at first. We anticipate the Cloud Costs will provide rich new experience for cloud cost-and-usage data, and lower memory usage than existing Kubecost features. In the future, it will also support GCP and Azure integration.

If you are on AWS and would like to try the alpha release of the new API, please reach out.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-225) by [Unito](https://www.unito.io)

**Comment by bajaj6** [comment]
We are installing kubecost on EKS via the AWS EKS add-on.
Wondering how is this API helpful to me.

**Comment by Adam-Stack-PM** [comment]
@AjayTripathy, Would you be able to jump in and help @bajaj6?

**Comment by AjayTripathy** [comment]
This is a more scalable version of our existing cloud costs API. If your CUR is relatively small (less than 1GB / day in exported data) it's recommended to stick with the existing API until this is out of alpha.

**Comment by udidn** [comment]
Quick question on the last correspondence:
When you say "stick with the existing API", do you refer to the Assets API?

**Comment by dwbrown2** [comment]
Yep, in particular the API described here: https://docs.kubecost.com/using-kubecost/getting-started/assets

**Comment by udidn** [comment]
Thanks. Another question:

Currently, the [Assets API](https://docs.kubecost.com/apis/apis/assets-api) has no `step` input, as opposed to the [Allocation on-demand query API](https://docs.kubecost.com/apis/apis/allocation#querying-on-demand-experimental), which has a `step` input.

Will the new Cloud Costs API include a `step` input?

**Comment by AjayTripathy** [comment]
No-- step sizes will be predefined since we don't have much control over granularity in the cloud providers.

**Comment by abdennour** [comment]
This feature will released at v1.99.0

**Comment by teevans** [comment]
@abdennour - This will be an ongoing work in progress over the next few releases!
