### ISSUE TITLE
Narrow down options on filters for Abandoned Workloads as the user selects them

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1877]
**What problem are you trying to solve?**
When using the filters on the `/abandoned-workloads` page, sorting through multiple clusters with unique namespace names can be challenging. Using the [demo site](http://demo.kubecost.io/abandoned-workloads) as an example, if you select the `kc-demo-aws-1` cluster, the only namespace available is `kubecost`; however, you can see all the options from the other cluster in the dropdown. 
![](https://user-images.githubusercontent.com/43491549/207714639-a09b635d-22bd-41a5-a1ae-bd3de9d6a295.png)

**Describe the solution you'd like**
I would like to have the filters narrow down possible options as I make selections.

**Describe alternatives you've considered**
Sort through the list manually, which might not be easy for large clusters.

**How would users interact with this feature?**
After selecting each option, the remaining filters should be updated with only relevant selections.
![](https://user-images.githubusercontent.com/43491549/207715421-fffb1628-f8f9-4893-890f-6764d9bfaf75.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-226) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
@nealormsbee seems like you could do this on the frontend by making a tree of filters? What do you think degree of difficulty is here?

**Comment by nealormsbee** [comment]
Disclaimer that I've spent basically no time in this page's code, but this seems ~medium-simple.

Guessing the filter option lists are determined by looking at the values for all available items...we'd just filter those items based on current selections, and use that filtered list to determine options for unset filters.

Only tricky part is that you could then change an already-set filter to something incompatible with other set filters, if that makes sense. In that case we'd probably just unset the others.

**Comment by dwbrown2** [comment]
Thanks, Keith. I think this goal of having dynamic filters generally applies to many places in application, e.g. assets + allocation. Thoughts, @nealormsbee?

**Comment by teevans** [comment]
@nealormsbee - If we take this on, let's be very methodical about how we approach this. My suggestion is a well tested service that would allow us to build these lists fairly dynamically. I think Burke may have some insight on building a capability like this well that we can reuse.
