### ISSUE TITLE
1.99.0 image is not available on ECR

### ISSUE THREAD

**Issue by azizzoaib786** [kubecost/cost-analyzer-helm-chart#1880]
I can see that new release v1.99.0 is out but the docker image is still not reflected at below ECR.
https://gallery.ecr.aws/kubecost/cost-analyzer

Any timelines when it will be released with the v1.99.0 tag?

**Comment by roee-landesman** [comment]
Relates: https://github.com/kubecost/cost-analyzer-helm-chart/issues/1878#issuecomment-1352314870. TL;DR - coming soon :)

**Comment by teevans** [comment]
@azizzoaib786 - Sorry for the delay, we're working on getting an image uploaded soon! Our usual team member that handles this is out sick right now. I'll reply here when we have an updated timeline!

**Comment by azizzoaib786** [comment]
Thanks @teevans

**Comment by linhlam-kc** [comment]
1.99.0 images and helm charts are now available on ECR public gallery.
