### ISSUE TITLE
Helm values for "labelMappingConfigs.external_label" do not set Custom Data Mappings in Advanced Reports

### ISSUE THREAD

**Issue by kc-adawson** [kubecost/cost-analyzer-helm-chart#1882]
Thanks for your interest in Kubecost!  To ensure you get the help you need, please follow these guidelines:

**Describe the bug**  
In 1.99 Advanced Reporting, there is the option to set the labelMapping to use existing external tags. The Helm values for these external tag mappings are not making it into the Advanced Reporting label map settings.

LabelMappingConfig Helm values:
<img width="710" alt="2022-12-15_17-14-57" src="https://user-images.githubusercontent.com/101200254/207979399-15e696ee-3bdc-4968-89f5-dffe2d77853c.png">

With those values enabled, Kubeost does not overwrite the defaults of "kubernetes_label_*" in Advanced Reports. It still shows the default.
<img width="478" alt="2022-12-15_17-28-40" src="https://user-images.githubusercontent.com/101200254/207981874-0ffaa8f2-126d-4100-819b-81b458e3b8af.png">

If I manually update the mapping to to "label:owner", it works as intended:
<img width="933" alt="2022-12-15_17-38-55" src="https://user-images.githubusercontent.com/101200254/207982193-a0bb4672-e689-437b-8378-877f6224b0ba.png">

**To Reproduce**  

1. Add labelMappingConfig values to an existing Kubecost with cloud integration
2. Go to Advanced Reporting at look at the Custom Data Mapping
3. Verify that the Custom Data Mapping did not change to reflect the labelMappingConfig values.

**Expected behavior**  
The Custom Data Mapping section should align with the corrosponding `labelMappingConfig.external` in the helm values

**Comment by Adam-Stack-PM** [comment]
@wolfeaustin When you have time would be great if you could help triage this issue. Wondering if it is a FE or BE issue? 

@kc-adawson, Could you help me understand how many users this could be affecting and the importance from your perspective?

**Comment by kc-adawson** [comment]
Hi @Adam-Stack-PM , its not urgent/blocking right now because the user can set it manually via the UI drop down. I think allowing Users to set external mappings via those Helm values makes sense to fix eventually, as the values are already there in the helm file.

**Comment by Adam-Stack-PM** [comment]
@kc-adawson, Thanks for the info. Adding it to v1.101 proposal list. v1.100 is jam packed

**Comment by AjayTripathy** [comment]
This feels both very easy (like an hour or two of work to fetch the right labels out of the config) and like a high visibility bug. I strongly feel we should scope work, especially bugs before we decide whether or not they'll make a release.  Inconsistency between the helm value/not correctly using the helm value in favor of the frontend is really frustrating for users because FE changes always have the potential to revert. cc @nealormsbee -- is this not really easy?

**Comment by nealormsbee** [comment]
Should be pretty straightforward -- we have the custom label data available in the FE, setting up the AR page to use it as a default when present should be simple. I can pick this one up in the space between now and 1.100.

**Comment by nealormsbee** [comment]
Just opened a v1.100 PR that should resolve this. Thanks for the report Andrew!
