### ISSUE TITLE
Add shared costs to /allocation/compute

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1884]
**What problem are you trying to solve?**
You can't reference shared costs when using the `/allocation/compute` endpoint. This makes it impossible to use this endpoint in all the same ways you can use the `/allocation` endpoint.

**Describe the solution you'd like**
The ability to use the same sharing logic in both the `/allocation` and `/allocation/compute` endpoint.

**Describe alternatives you've considered**
Use `/allocation`; however, if users need the ability to query on-demand, this isn't doable.

**How would users interact with this feature?**
Using the same [query parameters](https://docs.kubecost.com/apis/apis/allocation#querying) used in `/allocation`.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-228) by [Unito](https://www.unito.io)

**Comment by teevans** [comment]
@nikovacevic - Is this trivial?

**Comment by nikovacevic** [comment]
In short, no. Frankly, I don't want anyone using the `/allocation/compute` endpoint. What is the context @keithhand?

**Comment by nikovacevic** [comment]
And can you be more specific about which shared costs we need? e.g. shared tenancy is practically impossible, but shared overhead is trivial, and shared namespaces/labels are somewhere in between.

**Comment by AjayTripathy** [comment]
> In short, no. Frankly, I don't want anyone using the `/allocation/compute` endpoint.

There are two usecases here @nikovacevic 
1. Some people want to calculate increased resolutions over certain windows
2. There's currently no other way to access data outside the ETL window.

I think we can live without case 1 but we will need a way to figure out case 2 / build ETLs for days in the past in some sort of job architecture if we want to remove /allocation/compute. That make sense?

**Comment by nikovacevic** [comment]
That makes sense, but the challenge here is that sharing tenancy cost, e.g., will require a hard dep on an Asset Compute endpoint, which doesn't exist. So again... some of this is easy, and some of it will require much more work, and ideally open sourcing some code that is not today open source.
