### ISSUE TITLE
Match the sorting done in the UI in the generated CSV

### ISSUE THREAD

**Issue by myrthebil** [kubecost/cost-analyzer-helm-chart#1886]
**What problem are you trying to solve?**
The columns in our csv are sorted by the Total amount, not by the column we sorted by in the UI.

**Describe the solution you'd like**
When we download the csv of a report result, we would like to see the same sorting applied to the columns as we see in the UI.

**Describe alternatives you've considered**
Sorting by hand, which feels like a duplicate action, because we already sorted in the UI.

**How would users interact with this feature?**
They would follow the same interaction flow as the current behaviour, only the generated csv would have the correct sorting applied.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-29) by [Unito](https://www.unito.io)

**Comment by teevans** [comment]
@myrthebil - Thanks for the request! Let me get with the team and we'll circle back!

**Comment by dwbrown2** [comment]
I think of most people exporting csv to a spreadsheet application which makes this pretty simple... @myrthebil do you have a different workflow?

**Comment by myrthebil** [comment]
@dwbrown2 this is indeed our solution, though it would be nice to not have to execute the sorting twice - once in the UI and then again in a spreadsheet application.

**Comment by teevans** [comment]
@dwbrown2 - is this something we want to look at for 101?

**Comment by dwbrown2** [comment]
@myrthebil sounds lower priority given there's a workaround but let me know if you feel differently. Would be something that we'd look at in a future release.
