### ISSUE TITLE
Use a more user-friendly identifier for Cloud Costs Breakdown on Overview

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1887]
**What problem are you trying to solve?**
When viewing the Cloud Costs Breakdown - Account section in the new UI, the line items are based on an ID, sometimes making it hard to determine which account is which.

**Describe the solution you'd like**
Changing the item information displayed to be something more user-friendly. I'm not sure if there is a better value to reference for AWS, but both GCP and Azure have easier-to-read names (project id and subscription name, respectively).

**Describe alternatives you've considered**
Reference the accounts based on the ID displayed in the cloud console.

**How would users interact with this feature?**
Viewing the Overview page

Before:
![](https://user-images.githubusercontent.com/43491549/208976401-6e92b9ec-7819-401e-aeb4-28d744d502fb.png)

After:
![](https://user-images.githubusercontent.com/43491549/208976572-384a4321-dc78-41ba-8d11-a413042a11e4.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-28) by [Unito](https://www.unito.io)

**Comment by geborgeson** [comment]
👍

**Comment by teevans** [comment]
This would be nice - @nealormsbee - Do we have this data available to map through?

**Comment by nealormsbee** [comment]
I don't think we have data to map account numbers directly to some other, friendlier alias. Using GCP as an example, there's not a 1-1 mapping between Account and Project (at least the way we model them). Here's a table aggregated by `provider/account/project`, taken from `multi.test`:

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/981904/210413092-0e73e25f-6ec4-4a92-b2b4-fdc53f46c271.png">

You'll see the same account number holds multiple projects.

What we *can* do is aggregate this table by Project, or by Account/Project, to help make these rows friendlier.

**Comment by nealormsbee** [comment]
Marking this as linked to https://github.com/kubecost/cost-analyzer-frontend/issues/1474 so that we can close both issues together.

**Comment by kwombach12** [comment]
I think this would be a signification improvement to our user experience. Will add it to our v1.101 proposals

**Comment by MikeFindsThings** [comment]
Has there been any movement on this?

**Comment by kwombach12** [comment]
@MikeFindsThings Not yet. I will see if this is something we can squeeze in 106

**Comment by MikeFindsThings** [comment]
@kwombach12 how's this looking for 106? Had a user ask about it today.

**Comment by kwombach12** [comment]
@MikeFindsThings I should have a better idea as to whether we have capacity for this in 106 next week!

**Comment by MikeFindsThings** [comment]
@kwombach12 , bump 🙃

**Comment by kwombach12** [comment]
@MikeFindsThings Unfortunately, it seems we dont have capacity for this in 106 as it is a larger feature request and our focus for 106 is on polish/bugs

**Comment by chipzoller** [comment]
Closing, appears complete.
