### ISSUE TITLE
Add PDF Export to /details page

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1892]
**What problem are you trying to solve?**
I want to export [a details page](https://demo.kubecost.xyz/details?name=kubecost&type=namespace) to a PDF for sharing, similar to what has been added to the Allocation reports, here: https://github.com/kubecost/kubecost-cost-model/pull/1068.

**Describe the solution you'd like**
A "Download PDF" button on the /details page with a formatted PDF with all relevant information.

**Describe alternatives you've considered**
Print the entire screen, though this includes things like the navbar. Another solution would be to create each set of information necessary in an allocation report and download individual PDFs.

**How would users interact with this feature?**
![](https://user-images.githubusercontent.com/43491549/210659084-14138542-f6bb-4571-bbf9-530b00e2c66a.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-27) by [Unito](https://www.unito.io)

**Comment by wamak9** [comment]
+1

**Comment by teevans** [comment]
@dwbrown2, @kaiwombacher - Priority here?

**Comment by kwombach12** [comment]
I think this is a good proposal for v1.101.

**Comment by wamak9** [comment]
Is this added to v1.101 ??
@kwombach12  @teevans  @keithhand
