### ISSUE TITLE
secret exposure trough HELM_VALUES environment variable 

### ISSUE THREAD

**Issue by stefan-kiss** [kubecost/cost-analyzer-helm-chart#1893]
**Problem**

kubecost-cost-analyzer deployment has a field named HELM_VALUES

https://github.com/kubecost/cost-analyzer-helm-chart/blob/e53c15ba0ca45d0d2df92611f7d5cd535a8478e2/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L455

this field apparently contains the full helm values provided 

the values MAY contain secrets (and usually they do) while some values in the values file allow secret references to be passed others do not. regardless of that, the general expectancy from helm users is not to have the full value file exposed as hardcoded environment variable in the deployment's configuration

https://github.com/kubecost/cost-analyzer-helm-chart/blob/e53c15ba0ca45d0d2df92611f7d5cd535a8478e2/cost-analyzer/values.yaml#L33

**Expected behavior**

any kind of secrets or data that contain potential secrets should be stored in kubernetes as a secret. the technique is already employed by other parts of the chart so it's fairly easy to implement. inside the pod, it's still visible as an environment variable so no functionality is affected.

example: 

https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L540

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-26) by [Unito](https://www.unito.io)

**Comment by teevans** [comment]
@AjayTripathy - This is an interesting point, and one that I run into with hosted right now. Want to pow wow and see what we can come up with?

**Comment by teevans** [comment]
Also, @stefan-kiss - Thanks for opening this up. We'll take a look internally and see what we can do!

**Comment by srpomeroy** [comment]
In the meantime, this ENV can be disabled by setting [`reporting.valuesReporting` to `false`](https://github.com/kubecost/cost-analyzer-helm-chart/blob/b6b2ad0145041f7bd2d85fb6b121c507bfde35d0/cost-analyzer/values.yaml#L731)

**Comment by teevans** [comment]
@AjayTripathy - Friendly ping

**Comment by AjayTripathy** [comment]
Hey @teevans sorry for the late response. In hosted I think we should be using the secret, but this is maintained in the helm chart for backwards compatibility, as a quick way to test the secrets out when configuring, and as a parallel path with adding the secret from the frontend. Feels like the solution here is to not set any secrets as helm values rather than filter them from the HELM VALUES variable?
