### ISSUE TITLE
What's the usage of kubecostToken? is it must to be set while installing kubecost helm charts?

### ISSUE THREAD

**Issue by anemptyair** [kubecost/cost-analyzer-helm-chart#1895]
What's the usage of kubecostToken? is it must to be set while installing kubecost helm charts?

**Comment by teevans** [comment]
@anemptyair - We use that for a license key! More information around how that works can be found near the top of this page!

https://docs.kubecost.com/install-and-configure/install

Going to go ahead and close this issue for now, please feel free to re-open if there is anything else we need to look at.

**Comment by thomasvn** [comment]
Hi @anemptyair !

`.Values.kubecostToken` is primarily used to manage trial access and is provided to you when visiting http://kubecost.com/install (as documented [here](https://docs.kubecost.com/install-and-configure/advanced-configuration/add-key)).

This is different from `.Values.kubecostProductConfigs.productKey` which is used to apply a Business/Enterprise license (as found [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.99/cost-analyzer/values.yaml#L915-L919)).

**Comment by thomasvn** [comment]
@anemptyair Just checking in, did that help to answer your question?
