### ISSUE TITLE
Suppport for managed identities for cost exports configuration

### ISSUE THREAD

**Issue by passionInfinite** [kubecost/cost-analyzer-helm-chart#1899]
**What problem are you trying to solve?**
Currently, the configuration uses storage account access token while setting up the azure cost exports storage account access. This creates a problem of sharing access tokens within the large enterprise setup where there are multiple satellite clusters in the federated setup.

**Describe the solution you'd like**
Instead of using storage account access token, do we have a support for managed identities for the cost exports configuration? This will help us to scale in large enterprise environment and will be managing access securely without sharing the access tokens.

**Describe alternatives you've considered**
Maybe system assigned managed identities but the draw back with this approach is the managed identities resources will grow with the number of satellite cluster and it will be tuff for us to change the role accesses later on.

**How would users interact with this feature?**
In an enterprise setup, mothership (federated instance) will be using only managed identity entry to access those cost exports easily similarly on the satellite clusters (app teams) who want to join the federated cluster and want to export there cost exports they will be able to use the user assigned managed identity to connect to the storage account blob.

**Note: Thanos configuration supports the managed identities by following the thanos official config documentation.**

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-24) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
@kaelanspatel do we support these? If not maybe it's quick to knock out?

**Comment by kaelanspatel** [comment]
I'm guessing this is dependent on the library (or rather library derived code) we use for the connections [here](https://github.com/opencost/opencost/tree/develop/pkg/storage), which I admit I'm not too familiar with. Let me take a look.

**Comment by passionInfinite** [comment]
@kaelanspatel Thank you for response. I believe you are looking into the thanos configuration support while I am talking about support for `managed identity` for reading the cost exports (cloud billing) configuration that we do. For example:

```
{
    "azure": [
        {
            "azureSubscriptionID": "AZ_cloud_integration_subscriptionId",
            "azureStorageAccount": "AZ_cloud_integration_azureStorageAccount",
            "azureStorageAccessKey": "AZ_cloud_integration_azureStorageAccessKey", // instead of access key can we have managed identity support?
            "azureStorageContainer": "AZ_cloud_integration_azureStorageContainer",
            "azureContainerPath": "",
            "azureCloud": "public/gov"
        }
    ]
}
```

**Comment by thomasvn** [comment]
@passionInfinite I believe some degree of Managed Service Identity is supported, but currently the `azureStorageAccount` and `azureStorageAccessKey` are still required. As shown [here](https://github.com/opencost/opencost/blob/v1.99/pkg/storage/azurestorage.go#L118-L148).

**Comment by passionInfinite** [comment]
I need to try out with the managed identity part, if it supports then maybe we won't require `azureStorageAccessKey` and what exactly the key name shall I pass to this Azure object? `azureUserAssignedID` ?

**Comment by thomasvn** [comment]
@mbolt35 Are you able to comment on how to configure Managed Service Identity shown as `MSIResource` [here](https://github.com/opencost/opencost/blob/v1.99/pkg/storage/azurestorage.go#L118-L148)? Specifically when configuring [Azure Cost Export Integration](https://docs.kubecost.com/install-and-configure/install/cloud-integration/azure-out-of-cluster)?

**Comment by AjayTripathy** [comment]
I think @Sean-Holcomb might know best actually.

**Comment by Sean-Holcomb** [comment]
We do not support this currently, but it should be easier to add once CloudCost is live.

@passionInfinite in the mean time is there are reason that need the billing integration set up on the satellite clusters? That data doesn't get stored in Thanos. So you could just connect the Primary cluster to billing exports of accounts with federated clusters

**Comment by passionInfinite** [comment]
@Sean-Holcomb Thank you for the reply. Yes we are not setting up the billing integration on the satellite cluster. It will be only on the primary cluster but due to some policies we need to rotate the credentials so if we can have Identities support one less thing to worry about.

**Comment by teevans** [comment]
@Adam-Stack-PM / @kwombach12 can we get this planned for 102? Perhaps a stretch for 101.

**Comment by kwombach12** [comment]
@teevans yes, will add to 102.

**Comment by srpomeroy** [comment]
@kwombach12 Did this make 102? Plans for 103+?

**Comment by kwombach12** [comment]
It didnt make 102, but we are going to shoot for 103!

**Comment by justbert** [comment]
I'm assuming it hasn't made it into 103, 104, or 105. Is it still planned? We'd also be looking to use this feature to reduce our operational burden with credential rotation.

**Comment by kwombach12** [comment]
@justbert unfortunately, we haven't been able to add support for this yet, but it is still on our roadmap and something we hope to add soon!

**Comment by chipzoller** [comment]
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.

**Comment by srpomeroy** [comment]
Azure Workload Identities for the cloud integration is now supported.
https://docs.kubecost.com/install-and-configure/install/cloud-integration/azure-out-of-cluster/azure-workload-identity
