### ISSUE TITLE
Incorrect context addition breaks the federated kubecost instance as well

### ISSUE THREAD

**Issue by passionInfinite** [kubecost/cost-analyzer-helm-chart#1900]
Thanks for your interest in Kubecost!  To ensure you get the help you need, please follow these guidelines:

* If you have questions about product functionality/usage or need assistance with product installation/configuration, please email support@kubecost.com, where our support engineering team will be happy to help!
* If you have a reproducible bug or a feature request, you're in the right place.  Please include the information requested below.

- - -
# For reproducible bugs, please provide the following
**Describe the bug**

While adding the wrong context url to the kubecost instance it shows as inaccessible kubecost context in the manage contexts page (this is good) but there are two problems that occurs due to wrongly adding the context.

1. We cannot remove the wrongly added context from the frontend.
1. If the wrongly added context is selected from the "Select Context" model it shows api not found but then we cannot go back to the actual context anyway. The only option left is clearing storage account and cookies to reset the kubecost context state.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to manage context page.
1. Add wrong url to the manage context page.
1. It should show the new context in the Context Unavailable section.
1. Now there are two breaking points:

*   "Select Context" modal shows the unavailable context as well as it is selectable.
* If you select that context, it breaks the whole UI with either "white screen" or "api not found" depending on the wrong context url that was added. 

**Expected behaviour**

I would recommend to not add the unavailable contexts at all to the configurations.

**Screenshots**

![](https://user-images.githubusercontent.com/16861318/211594505-ec0ec90b-e82e-4a73-a054-ba111939c21e.png)
![](https://user-images.githubusercontent.com/16861318/211594512-a4f34224-a6fa-4fab-a1c2-a231e04c0368.png)
![](https://user-images.githubusercontent.com/16861318/211597318-9553ba35-9186-4754-ba86-501e9689b020.png)

This is white screen image when the url is completely incorrect:

## ![](https://user-images.githubusercontent.com/16861318/211594517-5c2e0445-3e05-48d9-bbbf-ed58f4754a10.png)
This is api not found when the url is partially incorrect:
![](https://user-images.githubusercontent.com/16861318/211596296-87b7504b-aaf1-467d-8428-d37e0cbcabd0.png)
![](https://user-images.githubusercontent.com/16861318/211596304-f95dd566-71cb-4aa8-9325-3f7d2d2339f3.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-23) by [Unito](https://www.unito.io)

**Comment by teevans** [comment]
@passionInfinite - Thank you for reporting! We've actually corrected this issue in the new user interface that is launching next release!

**Comment by Adam-Stack-PM** [comment]
@passionInfinite, Thanks for reporting this. Closing as this was fixed in v1.100. Please reopen if needed.
