### ISSUE TITLE
AWS CUR Athena queries should make use of partitions

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1902]
**What problem are you trying to solve?**
I have CUR history in AWS Athena going back many years, and I would like to lower my Athena costs.

**Describe the solution you'd like**
Today when Kubecost queries Athena, it ignores the partitions in place, which means the query scans all historical data before returning the results. By making use of the partitions, kubecost can minimize the data it scans which should lead to lower costs.

Below examples are from a demo environment with minimal data.

Before partition:
![image](https://user-images.githubusercontent.com/15660532/212370059-538c44f4-1e00-4dad-9ce2-b26912b175d3.png)
![image](https://user-images.githubusercontent.com/15660532/212367727-27b4cfbd-1263-41d2-a501-92857ee043df.png)

After with partition using year and date:
![image](https://user-images.githubusercontent.com/15660532/212369825-4e15747d-20e4-4d1f-8c4f-ba16a5f15d0f.png)
![image](https://user-images.githubusercontent.com/15660532/212368639-65c22c11-6e6b-408e-8215-9fc32aad81dd.png)

After with partition using year:
![image](https://user-images.githubusercontent.com/15660532/212369980-9c026343-f67c-4e75-be47-e907a6cf6a68.png)
![image](https://user-images.githubusercontent.com/15660532/212368987-456abc3a-b5e3-4d35-b285-9d5069392f81.png)

**Describe alternatives you've considered**
None

**How would users interact with this feature?**
No change would be required from the user's perspective unless there was a need to enable/disable partitioning when querying.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-22) by [Unito](https://www.unito.io)

**Comment by teevans** [comment]
This is interesting - does Athena automatically build partitions around dates, or is this something the user would have to configure?

**Comment by srpomeroy** [comment]
All CURs with Athena integration are partitioned by default.

Here is an example of the SQL command used to create a table as provided by AWS.
![image](https://user-images.githubusercontent.com/15660532/212957888-3c76c95a-2356-4927-b935-27d6cb2d2a06.png)

**Comment by teevans** [comment]
@nikovacevic  / @Sean-Holcomb could we look into this for v1.101?

**Comment by Sean-Holcomb** [comment]
@teevans this is definitely something we can do for the compute and agg queries and it lowers Athena costs and compute time, and will be easier very soon. We won't be able to use it for the TopN query because the partitions don't work on sub-queries which we are using there.

**Comment by AjayTripathy** [comment]
seems fine since topN is configurable and can be made small with a LIMIT right?

**Comment by Sean-Holcomb** [comment]
This has been addressed in https://github.com/opencost/opencost/pull/2154
