### ISSUE TITLE
Owner / Team filters on assets

### ISSUE THREAD

**Issue by speedfl** [kubecost/cost-analyzer-helm-chart#1905]
**What problem are you trying to solve?**
Owner / Team / Product filters not available on assets (such as PVC)

**Describe the solution you'd like**
Assets are part of the team / owner / Product cost. It could be nice to add the filters

**Describe alternatives you've considered**
N/A

**How would users interact with this feature?**
N/A

**Comment by thomasvn** [comment]
@speedfl Thanks for the feature request!

Currently, you can only aggregate/filter by Kubernetes constructs (e.g. Namespace, Deployment, Cluster) on the "/allocations" view. And on the "/assets" view you can aggregate/filter by cloud provider constructs (e.g. ProviderID, Account, Service).

I believe the [Owner / Team / Product labels](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.99/cost-analyzer/values.yaml#L876-L882) are considered Kubernetes constructs. Tagging product team for further input!

**Comment by speedfl** [comment]
Hi @thomasvn 

I am not sure to fully understand

Owner team and product are kubernetes constructs.
I was able to add them as filtre in the "/allocations"

However PVC requests imply disks creation (we can by the way see the storage class associated). 
It is essential to correlate disk costs with the team/owner/project who requested it (that's why we are adding labels to PVC)

What is your suggestion ?

**Comment by thomasvn** [comment]
@speedfl Ah, I think I understand now.

For example, when a PV is created and is given the label `team: dev1` you would like to be able to trace the PV's cost back to its team?

To address this, I believe we either:

* add PVs to the "/allocations" view, or
* add capability to the "/assets" view to aggregate/filter by kubernetes constructs (e.g. Namespace, Deployment, Label, Owner, Team, Product) as you initially discussed

cc @Adam-Stack-PM

**Comment by thomasvn** [comment]
@speedfl As a correction to what I said earlier, you *can* see PVs in the allocation view. Let me know if this satisfies your desired use case!

Here is a screenshot when aggregating by namespace then drilling into the Kubecost namespace:

![PV-Overview](https://user-images.githubusercontent.com/11251627/212981854-e556cae0-3198-4dd3-8ba1-6fd35b8b83ac.png)

Here is a screenshot when drilling all the way down to the pod:

![PV-Pod](https://user-images.githubusercontent.com/11251627/212981918-231b75e5-ecfe-4193-bdaa-3829331631e1.png)

**Comment by speedfl** [comment]
That's perfect thanks a lot :)
