### ISSUE TITLE
NetworkCost API vs UI

### ISSUE THREAD

**Issue by fgiannetti** [kubecost/cost-analyzer-helm-chart#1907]
Hello all!
I have a question related to the field 'networkCost' of the allocation API response.
This field has a value of '0' on every response json received from the Kubecost API

But looking the Kubecost UI, there is a non zero value in the 'Network' column in the same time window:
<img width="684" alt="Screen Shot 2023-01-17 at 10 52 42" src="https://user-images.githubusercontent.com/272366/212916473-4f26a593-26eb-4242-ab08-96cfb1185f4a.png">

I thought that I should enable some property on Kubecost installation, but the difference of values happens in the same installation 

Any idea why this difference between API and UI for network cost? A similar situation happens with 'sharedCost'

Thank you in advance!!

**Comment by thomasvn** [comment]
@fgiannetti Thanks for reaching out! I believe this question would be best handled by one of our dedicated support engineers. Would you mind logging a ticket with support@kubecost.com?

It would also help to include a link to this Github issue and also a [bug report](https://docs.kubecost.com/troubleshooting/bug-report)! Please note that all communication will be handled via that ticket moving forward to ensure privacy of your data as we work to resolve the issue.
