### ISSUE TITLE
Aggregating multiple vendor cost capability, like Datadog, or Confluent Cloud

### ISSUE THREAD

**Issue by danielpsf** [kubecost/cost-analyzer-helm-chart#1919]
**What problem are you trying to solve?**
As a Platform Person, I'd like to provide my company a full 360 view of their total cost, including external vendors, when they provide APIs to query such data so that I can charge back a team, or a department and understand if a given service is worth their money.

**Describe the solution you'd like**
1) Out of the box:

> Integration with [Datadog Metric Usage APIs](https://docs.datadoghq.com/api/latest/usage-metering/) or [Confluent Metrics APIs](https://docs.confluent.io/cloud/current/monitoring/metrics-api.html) and use their known and custom pricing (_configurable through the Helm values file_) in order to show as another column in the Advanced Report's page with a configurable naming, or in case the integration is made for Datadog specifically, use a column called Datadog.
> The solution is a bit tricky, but using Datadog Tags and Confluent Cloud topics and partitions it can be done, as long as there is a mapping functionality that can aggregate back to the service.
> 

1. Develop a plugin capability that can allow the community to develop their own plugins to collect and display another kind of costs withing Kubecost

**Describe alternatives you've considered**
It is on our roadmap to create a Datadog custom dashboard regarding how many logs, tracing, RUM sessions and etc a given service is using and use a custom [function](https://docs.datadoghq.com/dashboards/functions/) to process how much it is costing, then display it on the Service's page using [backstage.io](https://roadie.io/backstage/plugins/datadog/).

**How would users interact with this feature?**
Through Advanced Reporting, the users could see if a given service is costing too much in K8S, in the Cloud (with the out-of-the-cluster cost), or with vendors, such as Datadog or others.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-16) by [Unito](https://www.unito.io)

**Comment by teevans** [comment]
@dwbrown2 - This is interesting - Want to weigh in?

**Comment by dwbrown2** [comment]
@danielpsf thanks for sharing this! this is something we've recently started actively discussing in [OpenCost community meetings](https://calendar.google.com/calendar/u/0/embed?src=c_c0f7q56e5eeod3j89bb320fvjg@group.calendar.google.com&ctz=America/Los_Angeles). would you be interested in joining that to give further input?

cc @kwombach12

**Comment by danielpsf** [comment]
Sure, I'll be at the one on the 23rd of March. 😉

**Comment by AjayTripathy** [comment]
Hey @danielpsf , want to take a look at this doc we're starting to look at this idea, which we're calling "Custom External Metrics"? https://docs.google.com/document/d/1m-QqRRlL17xBLa3U0YBjpeuJjzG7Asdh-EZg9WhUu2o/edit

**Comment by dwbrown2** [comment]
This is now planned for OpenCost! More context here: https://www.opencost.io/blog/cloud-costs
