### ISSUE TITLE
New ETL repair endpoint which will sequentially run all ETL pipelines

### ISSUE THREAD

**Issue by thomasvn** [kubecost/cost-analyzer-helm-chart#1922]
## What problem are you trying to solve?
In disaster recovery scenarios, I need to manually run the following ETL repair pipelines. And the pipelines must be run sequentially, waiting for one repair pipeline to finish before running the next repair pipeline since they build off one another.

```
/model/etl/asset/repair
/model/etl/allocation/repair
/model/etl/cloudUsage/repair
/model/etl/asset/reconciliation/repair
```

Instead of monitoring logs and manually triggering each repair pipeline myself, I would like for a new endpoint which will run all ETL pipelines sequentially.

This is particularly helpful in cases where I am only able to repair small windows to limit the resource consumption of the repair pipeline.

## Describe the solution you'd like
```bash
# New API endpoint
# Runs the Asset, Allocation, CloudUsage, and Reconciliation pipelines for the specified window
/model/etl/repair
```

## Describe alternatives you've considered
A potential alternative, would be to develop a script which runs repairs then polls the cost-analyzer pod’s logs. Upon seeing completion of a repair pipeline, run the next repair pipeline.

## How would users interact with this feature?
User would make HTTP requests to `/model/etl/repair` API.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-13) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
Seems like a win to me, @nikovacevic wdyt? Any possible gotchas eg if the pipeline goes down in the middle of the run?

**Comment by nikovacevic** [comment]
First thing to note is that reconciliation is the only one that necessitates ordering -- the other three can be run all at once. I am not opposed to making a single endpoint. Let's attempt this in v1.101. Should be < 1 week of work.

**Comment by nikovacevic** [comment]
As you point out, the biggest problem is just keeping a log of what happened and allowing access to the results so that we can be assured that it all went well, or know when/how it failed.

**Comment by thomasvn** [comment]
@nikovacevic Thanks for clarifying that these ETL pipelines don't require ordering (with the exception of Reconciliation which builds upon Asset ETL)!

In order for the Reconciliation pipeline to understand when the Asset ETL has completed, would it be appropriate to simply check the filesystem to see when the expected ETLStores were last created/modified? (I guess this does assume that `ETL_FILE_STORE_ENABLED=true`)

**Comment by nikovacevic** [comment]
@thomasvn you can use the status endpoint to check that! http://nightly.kubecost.io:9090/model/etl/status

Does that address your question, or am I misunderstanding?

**Comment by thomasvn** [comment]
@nikovacevic Yep that answers the question! So Reconciliation pipeline can poll the `/model/etl/status` endpoint to wait for the `/model/etl/asset/repair` to complete.

**Comment by nikovacevic** [comment]
Yes, that's right -- and we can still build the `/model/etl/rebuild` endpoint to do exactly that.

**Comment by thomasvn** [comment]
@nikovacevic @AjayTripathy I'd like to take a stab at this!
