### ISSUE TITLE
Refresh sometimes 404s when using Contour/Envoy

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1923]
**Describe the bug**

When deploying using Contour/Envoy as the backing ingress controller with wildcard certificates, the application can sometimes issue a request in a way that Contour/Envoy doesn't accept, resulting in a generic 404 error. This seems to be related to how Contour/Envoy handles existing connections and the fact that we moved to a SPA in v1.95 (the problem didn't occur in v1.89, so I believe that is the version it would have stopped working, but I haven't confirmed). 

GitHub issues regarding this problem:

1. Initial finding - https://github.com/projectcontour/contour/issues/2468
1. Contour issue - https://github.com/projectcontour/contour/issues/1493
1. Underlying Envoy bug - https://github.com/envoyproxy/envoy/issues/6767

I'm curious if there is any workaround we could do on the front-end to better help with this.

**To Reproduce**

1. Deploy Kubecost with Contour v1.4+ as the backing ingress
1. Use a wildcard certificate for TLS
1. Consistently refresh the page until the requests swaps servers, leading to the invalid certificate/404

**Expected behavior**

Consistent refresh always returns results

**Screenshots**

![](https://user-images.githubusercontent.com/43491549/214669165-3403f953-736f-4016-9703-aec57e412c74.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-12) by [Unito](https://www.unito.io)

**Comment by thomasvn** [comment]
Related to [ZD #3281](https://kubecost.zendesk.com/agent/tickets/3281)
