### ISSUE TITLE
Add Dex integration via oidc rbac policies 

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1927]
**What problem are you trying to solve?**
Unable to apply rbac policies via oidc used by a third party proxy IDP (Dex)

**Describe the solution you'd like**
A way to integrate kubecost with Dex via oidc, using rbac policies Dex manages from their upstream provider. There are the two categories Dex supports with oidc:

1. Apps that request OpenID Connect ID tokens to authenticate users.
Used for authenticating an end user.
Must be web based.
1. Apps that consume ID tokens from other apps.
Needs to verify that a client is acting on behalf of a user.

Kubecost I believe falls under category one. It looks like you can configure apps to use oidc with dex: https://dexidp.io/docs/using-dex/#configuring-your-app

**Describe alternatives you've considered**
saml 2.0 but I believe this would not work since the SSO is using oidc. Looks like saml is the only thing that's supported with rbac in kubecost. It is also being deprecated in Dex.

https://github.com/kubecost/kubecost-cost-model/blob/1cb7bffbaa9a8a4ae5c0d22cf41ca5fcdd547626/pkg/cmd/costmodel/costmodel.go#L221-L232

**How would users interact with this feature?**
Configure in values.yaml oidc rbac policies generated and used by Dex (authentication proxy).

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-11) by [Unito](https://www.unito.io)

**Comment by jcstryker** [comment]
Hey +1 on this feature, we would love to be able to integrate the KubeCost UI with an existing Dex instance.

With that integration, the ability to specify admin and read-only permission scopes based on id token group claims would be very useful as well.

**Comment by teevans** [comment]
Ping to @dwbrown2 and @kwombach12 for Product prioritization

**Comment by AjayTripathy** [comment]
@kaelanspatel or @biancaburtoiu  would know best about if we support oidc + rbac in kubecost. My intuition is that if not it's not hard to add but let me know!

**Comment by kaelanspatel** [comment]
Hey all, @nickcurie and I actually implemented this for the last Hackathon (alongside some roll permissions customization endpoints).

It probably could be tested more thoroughly, and needs to be decoupled from the hacky role customization, but it totally exists. I'll take a pass over it and make sure it's  still working, but should be able to get it in once it's cleaned up a little.

**Comment by mmurph3** [comment]
@kaelanspatel awesome. More context on how customer uses this:

Their requirement:
Summary: Have kubecost integrate with their SSO (oidc - pingID) and have the ability to assign certain AD groups to be read-only and admin users.

1. PingID is behind all of this https://www.pingidentity.com/en/platform/capabilities/single-sign-on.html
2. It's being abstracted using dex within kubernetes.
3. Each of their clusters has a local dex instance that is a proxy for oidc (pingID) and dex will connect to pingID.
4. Dex itself is running its own identity provider and will assign its own tokens so dex would then essentially be the primary target for integrating oidc.

**Comment by AjayTripathy** [comment]
@teevans since this sounds mostly done maybe we can get some time from @kaelanspatel to knock this out in v1.101?

**Comment by teevans** [comment]
Shouldn't be a problem!

**Comment by AjayTripathy** [comment]
Believe this got done!
