### ISSUE TITLE
Option to hide specific savings options

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1929]
**What problem are you trying to solve?**
Some available savings options might not be plausible depending on the user's architecture. This can lead to significant savings numbers that might never be achievable.

**Describe the solution you'd like**
A way to hide specific panels on the savings page.

**Describe alternatives you've considered**
Ignore the panels that aren't used

**How would users interact with this feature?**
Helm configuration to set specific panels as disabled. Maybe something similar to:

```yaml
disableSavings:
  cluster-sizing: true
  orphaned-resources: true
```

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-10) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
Thanks for reporting, @keithhand! Can you share example you've seen where this is true?

**Comment by keithhand** [comment]
Sure! Any of the panels on this page are what I am talking about. The "orphaned-resources" panel was the targeted one, but the same idea would apply to all of them.
<img width="1450" alt="image" src="https://user-images.githubusercontent.com/43491549/215225814-af0bf371-3ccd-4302-b5ab-8c73c724f32d.png">

**Comment by wamak9** [comment]
+1 , P1

**Comment by teevans** [comment]
I'll mark this with a product-triage for now - We can prioritize for 101 if need be!

**Comment by dwbrown2** [comment]
I'm interested to learn more about specifics around where this doesn't apply? i.e. is it just a simple as they don't want to delete these resources?

**Comment by keithhand** [comment]
I believe that's the case. From what I understand, there is a situation where a developer would deploy Kubecost and hand it off to a management team. When the management team asks about the orphaned resources, there is nothing they can do because of architectural constraints. So they want the information to reflect only savings for changes they can make.

**Comment by dwbrown2** [comment]
That's helpful! We have a new guided savings experience in design. One concept related to that mode is the potential to archive / mark insights as not relevant. I feel like that pattern may be more appropriate here. Let me know if others feel differently. 

@kwombach12 @Annalillie

**Comment by Annalillie** [comment]
I agree, having the option to hide insights that aren't relevant to the user would be very useful here. Guided savings aim to streamline the savings experience, so I think this is a great place for it to live. Along with the other guided features, this will add to the users ability to focus on the savings that are relevant to their unique situations.

**Comment by Annalillie** [comment]
Here are some mocks for variation. One for customizing savings insights within the guided savings experience as well as one for the savings main page. Users would have the ability to toggle the insights they find relevant.
![image](https://user-images.githubusercontent.com/89574007/216153928-2ff62d98-fd53-438e-85f6-06af44d4078b.png)
![image](https://user-images.githubusercontent.com/89574007/216154907-8624479c-5d0a-43b9-abd2-b9ad850bee88.png)

**Comment by wamak9** [comment]
@Annalillie  -- Can this be Admin only ? Only Admin can enable disable ?

**Comment by Annalillie** [comment]
From a UI/UX perspective this could be achieved, however @dwbrown2 @kwombach12 would be able to give better insight to this proposal.

**Comment by dwbrown2** [comment]
Thanks for this, Anna! My intuition is that we may want to drill deeper and enable hiding/archiving specific recommendations... i.e. does a user not want to see ANY orphaned resources suggestions or are some of the suggestions actually active resources and therefore these insights should be snoozed or archived. 

+1 on make this Admin or Write only.

**Comment by wamak9** [comment]
@dwbrown2  -- bump
@keithhand , @Adam-Stack-PM

**Comment by Adam-Stack-PM** [comment]
@wamak9 Thanks for the the bump.  @kwombach12, As you are building out roadmaps wanted to get this on your radar for prioritization and consideration.

**Comment by dwbrown2** [comment]
We're exploring a number of different approaches at this time!

**Comment by wamak9** [comment]
is there an ETA on this ? @dwbrown2

**Comment by wamak9** [comment]
bump +1

**Comment by wamak9** [comment]
But that is basically the whole idle cost for the cluster.
I am not sure why that cannot is distributed ?
________________________________
From: Waseem ***@***.***>
Sent: Wednesday, April 5, 2023 5:26:52 PM
To: kubecost/cost-analyzer-helm-chart ***@***.***>
Cc: Waseem Mohammed ***@***.***>; Your activity ***@***.***>
Subject: [EXTERNAL] Re: [kubecost/cost-analyzer-helm-chart] Option to hide specific savings options (Issue #1929)

bump +1 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread. Message ID: <kubecost/cost-analyzer-helm-chart/issues/1929/1498236817@ github. com> ‍ ‍ ‍ ‍ ‍
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

bump +1

**Comment by dwbrown2** [comment]
@wamak9 we have a product design doc in the works. We'll have it finalized in the next several weeks. Would you want to give input?!

**Comment by wamak9** [comment]
yeah sure.  bump

**Comment by dwbrown2** [comment]
@kwombach12 can share more, this is now starting implementation this release

**Comment by kwombach12** [comment]
@dwbrown2 is correct! We will be adding the ability to hide/archive specific savings cards in 104. In future releases, we will enhance this further to provide the ability to hide specific savings recommendations.

**Comment by chipzoller** [comment]
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.
