### ISSUE TITLE
Add "proportion of cluster" information to Allocation report

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1930]
**What problem are you trying to solve?**
Some chargeback models are based on the proportion of total cluster cost that any single aggregation use. This proportion is displayed when you view the "Proportional Costs" chart; however, if there are more than ten items, the rest of the items get categorized under "other," and you can't see the proportional cost of each item. 

![](https://user-images.githubusercontent.com/43491549/215223537-6b1597d8-9163-4b98-97cf-dec076047189.png)

**Describe the solution you'd like**
I want a visual display of any line item's proportional costs on an allocation report.

**Describe alternatives you've considered**
Manually calculate the proportion based on the cluster's total costs and each line's total costs.

**How would users interact with this feature?**
View the new column on the allocation report, or allow users to bypass the 10-item limit on the graph displayed (I feel like this way could get noisy)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-9) by [Unito](https://www.unito.io)

**Comment by wamak9** [comment]
+1

**Comment by kwombach12** [comment]
I think the 'semi-circle' visualization of proportional costs really limits us from showing more items (I also find it hard to read). Perhaps a different visualization of proportional costs could be effective here. Im thinking something like this: 
<img width="845" alt="Screenshot 2023-01-30 at 11 55 35 AM" src="https://user-images.githubusercontent.com/86785820/215542668-fd2c17a8-ad0f-4e47-8948-f86da9622f31.png">
@Annalillie Do you mind doing a quick mock-up of what this could look like with a bunch of items?

**Comment by Annalillie** [comment]
Most definitely! I'll love to work on hashing this ux out. I'll update with mocks when they're ready.

**Comment by Annalillie** [comment]
There's a prototype [here](https://www.figma.com/proto/iNuogIfNVYxOaQpvrUtjD9/New-Design-System-Pages?page-id=19%3A57&node-id=2279%3A30082&viewport=-1359%2C684%2C0.15&scaling=scale-down-width&starting-point-node-id=2279%3A30082). I'd love some feedback or thoughts :) 
![image](https://user-images.githubusercontent.com/89574007/216146395-6d780a8c-e147-49b3-ab20-f02c6289c797.png)
![image](https://user-images.githubusercontent.com/89574007/216147321-9f1b88f0-e1ae-48c6-9c94-63d092e7c3ed.png)

**Comment by wamak9** [comment]
@Annalillie  -- This looks good. But can we fit everything here?
@kwombach12  -- Can we add an export functionality here with the option to export proportional cost onto a excel sheet ?
Or maybe can we display proportional cost in the below column details.

**Comment by Annalillie** [comment]
Thank you @akramwaseem. With this chart, we can expand vertically. @keithhand proposed having the option to bypass the 10 item limit. This could trigger the charts expansion to show more items. There's also the option to interact with/click into the "other" tile and view the items placed there. I agree that too many items on the screen will begin to feel cluttered. This wouldn't be as significant if it's presented as an action that can be selected/deselected according to the users needs.

**Comment by keithhand** [comment]
Another option that might be work looking at is adding the column to the report output. This sounds good to me because it doesn't introduce any more clutter with the graphic and gives the user a way to use features like export to CSV. 
![image](https://user-images.githubusercontent.com/43491549/216229373-9b396394-1240-47ef-9690-93764acc323b.png)

**Comment by kwombach12** [comment]
@keithhand I will add that to our feature backlog. For me, its low priority given that users should be able to calculate the proportional cost quite easily today by dividing the Total Cost for an item by the overall Total Cost.

**Comment by teevans** [comment]
A thought here too - this would be pretty quick to add to the csv output I believe...so if we *needed* it in quick, that would be a way to solve it...but loading a csv into excel and doing your own formula may yield more tailored results anyhow.

**Comment by wamak9** [comment]
> @keithhand I will add that to our feature backlog. For me, its low priority given that users should be able to calculate the proportional cost quite easily today by dividing the Total Cost for an item by the overall Total Cost.

I think it's more complicated than that. image having 15 shared namespaces and multiple clusters with just shared namespaces. 
and running 20 K8s cluster and then calculating the proportional cost across all the 20 K8s clusters.

If that is something achievable and doesn't need lot of manual intervention on user side, it is worth looking into it.
maybe generate a CSV and then user can do whatever they want with the CSV.

Current CSV format is not at all in readable format for most of the users. it's hard to figure out the proportional cost for everything with all the over complicated details listed on the CSV.

**Comment by wamak9** [comment]
@kwombach12  -- any update on this? Can we at least add something to the CSV file when exporting?

**Comment by AjayTripathy** [comment]
Hey @wamak9 , I started this ticket https://github.com/opencost/opencost/issues/1731 to look at adding proportional cost to  the API spec. would that sort of API change satisfy your needs here? I'd imagine we'd bring to the frontend shortly after.

**Comment by wamak9** [comment]
We dont use APIs at the moment and have no plans yet. I would appreciate if this can come to frontend.

**Comment by wamak9** [comment]
bump

**Comment by chipzoller** [comment]
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.
