### ISSUE TITLE
RBAC support for cloud costs & savings

### ISSUE THREAD

**Issue by kwombach12** [kubecost/cost-analyzer-helm-chart#1932]
**What problem are you trying to solve?**
Provide the ability to hide Cloud Costs & Possible savings

Breakout from Issue https://github.com/kubecost/cost-analyzer-helm-chart/issues/1574

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-8) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
@kwombach12 know this is still being discussed. Worth moving to feature repo?
