### ISSUE TITLE
Error getting node pricing. Error: Warning: no pricing data found

### ISSUE THREAD

**Issue by AndreOrlovE** [kubecost/cost-analyzer-helm-chart#1933]
**Describe the bug**  
We are using GKE, once we installed kubecost with helm we have a negative price for __idle__.
According to the link https://docs.kubecost.com/install-and-configure/install/custom-prom#negative-idle-reported
we have checked
```
kubectl exec -i -t -n kubecost \
  $(kubectl get pod --namespace kubecost|grep analyzer -m1 |awk '{print $1}') \
  -c cost-analyzer-frontend -- \
  curl "http://localhost:9003/prometheusQuery?query=node_total_hourly_cost"
```
output:
`{"status":"success","data":{"resultType":"vector","result":[]}}`

logs show:
`k logs kubecost-cost-analyzer-85865b7fd-6svvr -f`
```
Error getting node pricing. Error: Warning: no pricing data found for &{map[
beta.kubernetes.io/arch:amd64 
beta.kubernetes.io/instance-type:e2-highmem-8 
beta.kubernetes.io/os:linux 
cloud.google.com/gke-boot-disk:pd-balanced 
cloud.google.com/gke-container-runtime:containerd 
cloud.google.com/gke-cpu-scaling-level:8 
cloud.google.com/gke-logging-variant:DEFAULT 
cloud.google.com/gke-max-pods-per-node:110 
cloud.google.com/gke-nodepool:nap-e2-highmem
cloud.google.com/gke-os-distribution:cos 
cloud.google.com/machine-family:e2 
failure-domain.beta.kubernetes.io/region:us-central1 
failure-domain.beta.kubernetes.io/zone:us-central1-a 
kubernetes.io/arch:amd64 
kubernetes.io/hostname:gke-ltx-nap-e2-highmem
kubernetes.io/os:linux 
node.kubernetes.io/instance-type:e2-highmem-8 
topology.kubernetes.io/region:us-central1 
topology.kubernetes.io/zone:us-central1-a]}
```

**To Reproduce** 
helm upgrade --install kubecost kubecost/cost-analyzer --namespace kubecost --set kubecostToken="token" -f values.yaml
values.yaml
```
prometheus:
  nodeExporter:
    enabled: false
  serviceAccounts:
    nodeExporter:
      create: false
  kubeStateMetrics:
    enabled: false
```
kubecost          deployed	cost-analyzer-1.99.0          	1.99.0

**Expected behavior**  
__idle__ price should not be negative in the report

**Comment by thomasvn** [comment]
@AndreOrlovE Thanks for reporting! Just checking, but in your `values.yaml` you are disabling nodeExporter because you already have one running with your own Prometheus instance? And you are disabling kubeStateMetrics because you are already running it in your cluster?

**Comment by AndreOrlovE** [comment]
@thomasvn hi, yes, we already have these instances deployed in our cluster

**Comment by thomasvn** [comment]
@AndreOrlovE According to the troubleshooting command you provided above:

```bash
$ kubectl exec -i -t -n kubecost \
  $(kubectl get pod --namespace kubecost|grep analyzer -m1 |awk '{print $1}') \
  -c cost-analyzer-frontend -- \
  curl "http://localhost:9003/prometheusQuery?query=node_total_hourly_cost"

{"status":"success","data":{"resultType":"vector","result":[]}}
```

The result is an empty vector. This indicates that your Prometheus instance likely isn't scraping Kubecost for its metrics.

I believe this issue would be best handled by one of our dedicated support engineers. Would you mind logging a ticket with support@kubecost.com? Be sure to include a link to this GitHub issue so you don’t have to document your issue twice! Please note that all communication will be handled via that ticket moving forward to ensure privacy of your data as we work to resolve the issue.

**Comment by AndreOrlovE** [comment]
@thomasvn , sure, I'll create a ticket with [support@kubecost.com](mailto:support@kubecost.com), thank you

**Comment by kirbsauce** [comment]
Hi @AndreOrlovE , closing this out as we're working the issue in Zendesk.
