### ISSUE TITLE
Add filter of cluster selected from overview page and allow user to drill down into namespace to get overview of workloads for chosen cluster in overview page

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1940]
**What problem are you trying to solve?**
When drilling down from overview page -> clusters: cluster breakdown -> clicking on cluster then clicking the namespace (not the white space) it brings up overview of all the workloads across all clusters with the same namespace [1]. This confused one our customers on a working session. We had to redirect customer to click the whitespace next to the namespace in order to see the overview of the workloads for the cluster they clicked on in the overview page (previous page). Additionally, it does not give the same overview as clicking directly on the namespace.
![Feb-01-2023 13-14-27](https://user-images.githubusercontent.com/36980248/216128069-1d5d3319-6104-41d2-959b-1eabb34b06dd.gif)

**Describe the solution you'd like**
When clicking on a cluster from the overview page and drilling down into the namespace by clicking directly on the namespace, provide an overview of the namespace specific to the cluster chosen from the overview page (previous page). This will allow for a smoother UX experience. Having to click on the white space is not intuitive. 

**Describe alternatives you've considered**
clicking white space next to namespace to drill down to workloads for cluster chosen in overview page.

**How would users interact with this feature?**

Click directly on the namespace link and see overview of workloads for the specific cluster.

[1] https://multi.test.kubecost.io/details?name=scale&type=namespace

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-6) by [Unito](https://www.unito.io)

**Comment by kwombach12** [comment]
This should be resolved in 1.101. When a user clicks on a cluster on the overview page, they will be taken to a new, 'cluster inspect' page. Within that page, they will see the most expensive namespaces for that cluster, and when they click on that table, they will be taken to the allocations page, aggregated by namespace, and filtered by the given cluster. 

@mmurph3 Excited to get your feedback on this new UX when we publish the RC for testing!

cc: @dwbrown2
