### ISSUE TITLE
AWS Cost Explorer Includes Enterprise Discounts For Amortized Cost

### ISSUE THREAD

**Issue by Sean-Holcomb** [kubecost/cost-analyzer-helm-chart#1944]
This issue was discovered while working with a customer to identify the source of a discrepancy between costs in Kubecost CloudUsage on the Assets page and the AWS Cost Explorer. Kubecost costs aggregated by service were exceeding those shown in the Cost Explorer by ~25%. When drilling into the AmazonRDS service specifically we found if we removed our filter for Usage line items
`(line_item_line_item_type = 'Usage' OR line_item_line_item_type = 'DiscountedUsage' OR line_item_line_item_type = 'SavingsPlanCoveredUsage')` the cost number began to match  CE Amortized Cost . When we inverted that filter we found that items that were making our query match CE Amortized Cost were for Enterprise Discounts.  The [Cost Explorer documentation](https://docs.aws.amazon.com/cost-management/latest/userguide/ce-exploring-data.html) implies that Amortized Cost is pre-discount and Net Amortized Cost is post-discount. If it is correct for these line items to be included in non-net cost fields it would be helpful to have a more clear description of what is included in net vs non-net, in addition to what kind of discounts trigger the addition of the net columns to the CUR.

**Describe the solution you'd like**

I would like to reach out to AWS and try to either get an update on the documentation or confirmation of a bug

On our end we have two options:

1. Update our Athena Queries to allow for line_item_line_item_type = 'EdpDiscount'
1. The new Cloud Cost page which will be replacing CloudUsage on the Asset page has support for Net Amortized Costs. The presence of the the Enterprise discount implies that the net cost columns will be available in the CUR. With those columns in use it would make more sense for users to try and match their service aggregated costs in Kubecost against Net Amortized Cost in the Cost Explorer, where this issue would likely not arise. Even if we have access to Net Amortized Cost it is still desirable for Amortized Cost to be correct, so one of the above solutions may still be required.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-5) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
Can this now be closed based on https://github.com/kubecost/kubecost-cost-model/pull/1210 ?

Or should we leave it open until we get feedback?

**Comment by Sean-Holcomb** [comment]
Changes are available in Nightly only right now and did not go into release. We could close for now, I don't think anything else needs to be done unless the customer has an issue, in which case we could reopen.

**Comment by nikovacevic** [comment]
Closing based on previous comment and lack of activity.
