### ISSUE TITLE
Allocation page window / results look off near start of cluster's data

### ISSUE THREAD

**Issue by nikovacevic** [kubecost/cost-analyzer-helm-chart#1950]
Version: v1.100-rc.0
Environment: http://eks.dev1.niko.kubecost.xyz:9090/

### Description
Something looks off between the window and the results for the Allocation page when the window spans the period of earliest data. A few things seem to be the case:

### Window component timezone
The `window` selector is not using UTC, but the underlying data is. So you can get data from the (apparently) wrong date range. E.g. when I select (Jan 1 - Jan 31) the underlying request is made for:

http://eks.dev1.niko.kubecost.xyz:9090/model/allocation/view?aggregate=namespace&window=2023-01-01T07%3A00%3A00Z%2C2023-01-18T07%3A00%3A00Z&accumulate=false&shareIdle=false&idle=true&idleByNode=false&shareTenancyCosts=false&shareNamespaces=&shareCost=NaN&shareSplit=weighted&chartType=2&costMetric=1&startIndex=0&maxResults=0&req=1675391960238?req=1675391960238

Notice that there is a local timezone in there, not UTC, and so you get this information, which seems to make no sense:

![Screenshot from 2023-02-02 19-38-59](https://user-images.githubusercontent.com/8070055/216500924-6761bbb8-501d-4d0e-a419-08f216aa24f6.png)

The correct request (noting the window) would be:

http://eks.dev1.niko.kubecost.xyz:9090/model/allocation/view?aggregate=namespace&window=2023-01-01T00%3A00%3A00Z%2C2023-01-18T00%3A00%3A00Z&accumulate=false&shareIdle=false&idle=true&idleByNode=false&shareTenancyCosts=false&shareNamespaces=&shareCost=NaN&shareSplit=weighted&chartType=2&costMetric=1&startIndex=0&maxResults=0&req=1675391960238?req=1675391960238

### Allocation View API does not return "empty" data

The other issue seems to be a backend one. (Or perhaps it's a valid product decision? But seems weird to me.) That is:  we seem to no longer return empty data. So for the over-time visualization, you can request 60d or 90d and only see the same data. It used to be that you'd see 60 or 90 days, but many would be empty.

![Screenshot from 2023-02-02 19-35-51](https://user-images.githubusercontent.com/8070055/216501199-a3b51869-da51-4468-9e22-a08615c7051e.png)
![Screenshot from 2023-02-02 19-36-02](https://user-images.githubusercontent.com/8070055/216501202-57e97deb-8c39-4f77-ba02-1dc1ac0b0938.png)
![Screenshot from 2023-02-02 19-36-13](https://user-images.githubusercontent.com/8070055/216501204-154f04d0-d404-455b-84e9-3520f3e57ca5.png)

In the old system, this would look like:

![Screenshot from 2023-02-02 19-52-48](https://user-images.githubusercontent.com/8070055/216501357-f8397b10-2286-47b5-ab90-e05fcb393b00.png)

This seems to be an API thing -- the UI is just rendering what it receives. The API is only sending back the non-empty data for that viz.

**Comment by nikovacevic** [comment]
@Adam-Stack-PM @kwombach12 this feels borderline P0 to me for v1.100. What do you think?

**Comment by nikovacevic** [comment]
@avrodrigues5 would be a good person to talk to about this API.

**Comment by dwbrown2** [comment]
@kwombach12 for product input!

**Comment by Adam-Stack-PM** [comment]
Marked p0 for visibility.  Feel free to adjust as we learn more.

**Comment by avrodrigues5** [comment]
Since we are supporting UTC, first part of the bug might just fall under Front end purview to make the request with only UTC timezone like we have done in the past(old UI), that would solve the immediate bug. 

With that said I am going to triage why we get weird result and try to make sense of it for the local timezone request.

As Niko mentioned, Second part is definitely only backend to return empty data. If Product aka Kai wants empty data to be rendered on FE if request timeline exceeds length of kubecost collecting data I will make that change.

**Comment by kwombach12** [comment]
I agree that the first part is a p0 bug... in terms of the second part - I think the old design (where we show empty data) makes more me sense to me. There pros & cons to both approaches IMO, but I think some users will forget that they only setup kubecost say 52 days ago, so when they flip to last 60 days, they would be confused as to why they arent seeing all 60 and when they flip to 90 days after, they would again be confused as to why their data isn't updating.

**Comment by Adam-Stack-PM** [comment]
@nealormsbee, who should we get the first part of the bug routed too?

**Comment by nikovacevic** [comment]
@avrodrigues5 do you think it'd be quick to just add the extra empty data sets? It's only for the "over-time" graph data, right? The table and totals should not need to change.

**Comment by avrodrigues5** [comment]
The underlying data is stored/transffered in proto3 and proto3 are designed to drop empty data, so i have to think through this problem a little. I'll see what i can do and get back with the solution. 

The table and totals wont change i'll ensure that.

**Comment by nikovacevic** [comment]
Argh, that's annoying. Sorry, Alan. That proto3 work has really turned into a curse.

**Comment by aligon** [comment]
I *think* the way the UI is currently setup, the user's are picking the custom window in their local time (at least from their perspective) which we then convert to UTC to send to the backend. So that is causing the non-zero hours in the timestamp.


If the window needs to fall on UTC boundaries we could indicate to the users that the date they are picking is in UTC not local time. Depending on their technical level that could be confusing though.

**Comment by nikovacevic** [comment]
Yeah, the way it's always worked has just been that selecting "January 1 2023" in the UI converts to "2023-01-01T00:00:00Z" (i.e. UTC) in the request. The underlying data is in UTC, so we're looking for parity between date-picker and data, not date-picker and locale. Is that helpful?

**Comment by nikovacevic** [comment]
With relative durations (e.g. 6h, 10d) it's irrelevant. But for RFC-3339 format, it does matter.

**Comment by aligon** [comment]
We can do that!

Should we add a note about the dates being in UTC? Or is it too subtle for it to really become an issue?

**Comment by kwombach12** [comment]
@aligon I think thats something we can leave in our docs... not sure where'd we'd put it in the product unless you have an idea on how to subtly put it in

**Comment by aligon** [comment]
I was thinking maybe just a "dates are in UTC" beneath the the inputs, but depending on technical level that might just confuse things more.

**Comment by kwombach12** [comment]
yea I think it may add to the confusion. let's leave it in the docs for now

**Comment by avrodrigues5** [comment]
Just to notify stakeholders Backend fix went in via 
https://github.com/kubecost/kubecost-cost-model/pull/1199 - Develop branch
https://github.com/kubecost/kubecost-cost-model/pull/1200 -> pick for v1.100

**Comment by teevans** [comment]
Closing
