### ISSUE TITLE
Tiles on details page display only primary Kubecost metrics

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1954]
**Describe the bug**

The information on the cards displayed at the bottom of `/details` is pulled directly from Prometheus using the `prometheusQuery` endpoint. On federated systems, this is causing issues where we aren't getting all of the data expected from a particular namespace because the information is stored in Thanos, not Prometheus. When we load the `/details` page on the primary, the `prometheusQuery` response is empty, however, changing the query to `thanosQuery` provides us with the results we would expect to fill out that data. 

**To Reproduce**

1. Deploy a federated system with the secondaries enabling the network costs daemonset
1. Go to a `/details` page of a namespace you expect network costs to be emitting from the secondary
1. See "Network Traffic allocation not configured"

**Expected behavior**

The details page has details from all clusters, not just the primary.

**Screenshots**

![image](https://user-images.githubusercontent.com/43491549/216718379-b0c01c33-f501-4c2d-8f88-13f8daa8e41f.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-2) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
Hm, I thought we had deprecated all prom queries on the FE? cc @nealormsbee ?

**Comment by nealormsbee** [comment]
Nope. We use ETL data on the `/network` page because it now has x-zone, x-region, but this card wants to break down network costs by cloud service, which we don't have in ETL.

Also just to note, this is a screencap of the old Details view network card, which is going away soon. We're more likely to find issues like this with parts of the deprecated Classic UI.

I don't think we're getting cloud services in ETL's network data any time soon. We can update the card to use `prometheusQuery` or `thanosQuery` as appropriate.

**Comment by mmurph3** [comment]
Do we have an update on this?

**Comment by nealormsbee** [comment]
No progress yet @mmurph3.

@keithhand do you mind if I change the title of this issue to state that it's about the network tile, specifically?

We can update the tile to use Thanos when we detect that it's available, but we'd still show this message when the main Kubecost cluster isn't running the network daemonset. We check with the primary cluster to see if that daemonset is running, and if it isn't we show this error, even in the presence of network data. That behavior is consistent with what's been there historically....I don't know why it was originally set up that way. I'm all for changing it.

Going to label this as a proposed update for 1.102.

**Comment by mmurph3** [comment]
@nealormsbee looks like this may need to be considered for v1.103. Is that correct?

**Comment by nealormsbee** [comment]
That is correct. I should revise my statement above ^
We've definitely removed all prom queries from the network page now. We still show a "network traffic not configured" message if the primary cluster doesn't have the daemonset enabled and I *think* we should be okay to change that? We'll just report network data if it's there, and it would be nice to show per-cluster which clusters don't have the network pods running.
