### ISSUE TITLE
Updating kubecost causes data loss

### ISSUE THREAD

**Issue by hyj-github** [kubecost/cost-analyzer-helm-chart#1956]
**Problem**
I used the helm command below to upgrade kubecost from 1.73 to 1.96.0.Because the disk capacity has been expanded, the disk size is specified as the disk size.
**helm upgrade  kubecost kubecost/cost-analyzer -n kubecost --version 1.96.0 --set prometheus.server.persistentVolume.size=40Gi**

After the update was successful, it was found that the previous data could not be queried, and the disk size of kubecost-prometheus-server was reduced from 29 GB to 15 GB, and the data before Prometheus was lost. But the pvc was not rebuilt after destruction. Is there a problem with the upgrade operation?

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-1) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
Between v1.73 and 1.96, Kubecost's ETL data would need to be rebuilt. This should be rebuilt up to the default amount of data stored in Prometheus (15 days). Data beyond this would be lost in an upgrade.

**Comment by hyj-github** [comment]
Hi, I lost all the data before the upgrade and did not keep the data for 15 days.
In addition, I have upgraded kubecost 1.87 to 1.96 without data loss. The command is "helm upgrade kubecost kubecost/cost-analyzer -n kubecost --version 1.96.0".  Whether the above configuration to set the disk size will cause data loss.

**Comment by thomasvn** [comment]
@hyj-github Did you lose Kubecost's ETL data? Or did you lose Prometheus's metrics?

For the cluster you increased the PV size for, could you check for the presence of Prometheus's metrics? You can follow [this guide](https://docs.kubecost.com/troubleshooting/prometheus) to access the Prometheus frontend, then query for `node_cpu_hourly_cost`.

**Comment by hyj-github** [comment]
@thomasvn  I queried the Prometheus that came with kubecost and found data for this indicator.Does it mean that the data is not actually missing? If not, why can't I find it on the kubecost page?

**Comment by thomasvn** [comment]
@hyj-github You may need to repair the Kubecost ETLs. Visit the [diagnostics page](https://docs.kubecost.com/troubleshooting/diagnostics#kubecost-etl-pipeline-metrics) to check the health of these ETL files, and repair as needed.

**Comment by hyj-github** [comment]
> @hyj-github You may need to repair the Kubecost ETLs. Visit the [diagnostics page](https://docs.kubecost.com/troubleshooting/diagnostics#kubecost-etl-pipeline-metrics) to check the health of these ETL files, and repair as needed.

I see the ETL Cache in the diagnostic view as follows:
![etl-status](https://user-images.githubusercontent.com/54680729/217695097-a4158c64-589d-4540-8e24-535ef0cb06ff.PNG)

After you click "REPAIR", "Invalid ETL Data Stored" is displayed. Moreover, no data can be queried on the "Cost Allocation" page.

What can I do to recover the data?

**Comment by thomasvn** [comment]
@hyj-github Thanks for sharing a screenshot of that error message. 

* Are you noticing your `kubecost-prometheus-server` pod restarting or getting OOM Killed? If so, could we increase increase resources, and adjust the Prometheus configs based on [this tuning guide](https://docs.kubecost.com/general/resource-consumption)?
* Are you able to port-forward to the Prometheus frontend, then perform the same query displayed in the error message?

**Comment by hyj-github** [comment]
> * Are you noticing your `kubecost-prometheus-server` pod restarting or getting OOM Killed? If so, could we increase increase resources, and adjust the Prometheus configs based on [this tuning guide](https://docs.kubecost.com/general/resource-consumption)?
**I solved the OOM problem by expanding the capacity.  When this error occurs, how do you fix the data?**


> * Are you able to port-forward to the Prometheus frontend, then perform the same query displayed in the error message?
**I queried "node_cpu_hourly_cost" on the Prometheus console and found the data shown below.(On January 26th)
 But I can't get any data from the Kubecost console.**

![Prometheus结果](https://user-images.githubusercontent.com/54680729/218036468-a455c4e4-1c78-4dac-abca-81a0d23babd6.PNG)

**Comment by thomasvn** [comment]
@hyj-github Could you try the query which was shown in your error message?

```
avg(avg_over_time(kube_pod_container_resource_requests{resource="memory", unit="byte", container!="", container!="POD", node!=""}[1h])) by (container, pod, namespace, node, cluster_id)
```

Additionally, a list of queries Kubecost performs to compute cost allocations [here](https://github.com/opencost/opencost/blob/v1.100/pkg/costmodel/allocation.go#L19).

**Comment by hyj-github** [comment]
> @hyj-github Could you try the query which was shown in your error message?
> 
> ```
> avg(avg_over_time(kube_pod_container_resource_requests{resource="memory", unit="byte", container!="", container!="POD", node!=""}[1h])) by (container, pod, namespace, node, cluster_id)
> ```
> 
> Additionally, a list of queries Kubecost performs to compute cost allocations [here](https://github.com/opencost/opencost/blob/v1.100/pkg/costmodel/allocation.go#L19).

I can query this metric on prometheus.What does it say?

**Comment by thomasvn** [comment]
@hyj-github That query displayed each container's average [`spec.resource.requests`](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits) over time. And is one of the queries used to repair ETLs, but failed (as shown in the above screenshot).

Is it still failing when you attempt to repair ETLs? If you are getting the same Prometheus error, can you verify that prometheus-server has not been restarted? And can you confirm that the network connection between kubecost-cost-analyzer and prometheus-server is stable?

**Comment by hyj-github** [comment]
> @hyj-github That query displayed each container's average [`spec.resource.requests`](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits) over time. And is one of the queries used to repair ETLs, but failed (as shown in the above screenshot).
> 
> Is it still failing when you attempt to repair ETLs? If you are getting the same Prometheus error, can you verify that prometheus-server has not been restarted? And can you confirm that the network connection between kubecost-cost-analyzer and prometheus-server is stable?

When I clicked "repaired", the following information was displayed.
**"Invalid ETL Data Stored"**

prometheus-server may have been restarted at the repair date.

**Comment by thomasvn** [comment]
@hyj-github Can we test to see if repairing your ETLs via [these `curl` commands](https://docs.kubecost.com/troubleshooting/etl-repair) will work? I'd highly recommend setting a small `window` parameter to try to ensure Prometheus does not restart due to OOM.
