### ISSUE TITLE
Expose GPU Efficiency

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1961]
**What problem are you trying to solve?**
My teams are beginning to use GPUs and would like to understand how effectively they are being used.

**Describe the solution you'd like**
Consider GPU in measuring efficiency or expose it separately.

**Describe alternatives you've considered**
Direct queries to Prometheus

**How would users interact with this feature?**
Column in Cost Allocation, details view, request sizing, and of course the API.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-247) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
Hey @srpomeroy what Prometheus metric being used to measure gpu utilization here?

**Comment by dwbrown2** [comment]
Any more info we can share on this one?

**Comment by AjayTripathy** [comment]
Not sure... @srpomeroy any idea what kind of GPUs etc the user is using?
