### ISSUE TITLE
Support Kubecost Label Aliases in filters

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1962]
**What problem are you trying to solve?**
I have several long, complicated labels I like to aggregate and filter my cost and resource data by. I use the built-in Kubecost aliases to make it easier for my end users to work with the labels. But when they need to filter, they must manually provide the long, complicated labels.

**Describe the solution you'd like**
I'd like to see the filters in all views support the built-in label aliases.

**Describe alternatives you've considered**
Manually providing the label keys.

**How would users interact with this feature?**
Filter drop-down in allocation, container rightsizing, and via API.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-248) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
Seems reasonable and pretty straightforward, thoughts @kwombach12 ?

**Comment by kwombach12** [comment]
Totally supportive of this enhancement. Would love to pick this up in the next release!

**Comment by kwombach12** [comment]
@srpomeroy Just to make sure I understand the proposal... we would like to add the filters available to a drop down? For example, when a user click 'service' they would see the services available for filtering in a dropdown?
<img width="431" alt="Screenshot 2023-02-14 at 9 42 59 AM" src="https://user-images.githubusercontent.com/86785820/218770846-75107ae3-e91d-447b-90f2-b513f3f6e60f.png">

**Comment by kc-adawson** [comment]
Related notes/discussion on this issue - https://github.com/kubecost/cost-analyzer-helm-chart/pull/1925. Would love to see something like this available in UI/API - FiltersV2 - 'filter=product:"linux"' 

<img width="1440" alt="2023-02-16_09-28-17" src="https://user-images.githubusercontent.com/101200254/219452302-486a2356-9957-4865-8b69-44c1ea9f0dfc.png">

**Comment by srpomeroy** [comment]
> @srpomeroy Just to make sure I understand the proposal... we would like to add the filters available to a drop down? For example, when a user click 'service' they would see the services available for filtering in a dropdown?
> <img alt="Screenshot 2023-02-14 at 9 42 59 AM" width="431" src="https://user-images.githubusercontent.com/86785820/218770846-75107ae3-e91d-447b-90f2-b513f3f6e60f.png">

That auto-suggest would be a great additional feature request.

I was specifically suggesting just adding our built in label aliases that we aggregate by as additional filters.

**Comment by kwombach12** [comment]
@srpomeroy AH thank you for the clarification! I'm very supportive of this feature. Will prioritize for 1.102

**Comment by kc-adawson** [comment]
@kwombach12 It would be great to have the auto-populating filter dropdowns as well - We do this already kind of within the old ui abandoned workloads report. Having to type the whole name correctly when filtering can be a pain.

http://acdc9ca48678c4e938348860722a922f-1516114798.us-east-2.elb.amazonaws.com:9090/abandoned-workloads

![Kapture 2023-02-16 at 12 39 55](https://user-images.githubusercontent.com/101200254/219458164-fe32e1ea-5d37-4b02-abef-0189377a6a96.gif)

**Comment by kwombach12** [comment]
@kc-adawson totally agree! Have that planned for 1.102 as well!

**Comment by srpomeroy** [comment]
@kwombach12 Are we still planning to implement?

**Comment by kwombach12** [comment]
@srpomeroy yes - we definitely want to implement this. When we took at look at this feature in 102, it required more work than expected

**Comment by chipzoller** [comment]
I think this is now complete. Closing.
