### ISSUE TITLE
Support Custom Label Aliases

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#1963]
**What problem are you trying to solve?**
I need to aggregate my costs based on several different label keys that don't necessarily fit into the built-in aliases of Owner, Team, Department, Product, or Environment.

**Describe the solution you'd like**
I want to be able to define custom label aliases or change the names of the built-in ones.

**Describe alternatives you've considered**

1. Using the existing aliases even though they don't correlate to my labels.
1. Aggregate by label(s) manually and save report.

**How would users interact with this feature?**
Set in UI or helm.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-249) by [Unito](https://www.unito.io)

**Comment by thomasvn** [comment]
@srpomeroy Another existing workaround would be to aggregate by the label name right? For example: `aggregate=label:app`.

**Comment by srpomeroy** [comment]
Indeed @thomasvn. Which also leads to some UX issues. I'll update it. Thanks!

**Comment by srpomeroy** [comment]
The customer in question would like to be able to aggregate multiple complex labels.

**Comment by AjayTripathy** [comment]
Seems like one for @kwombach12 to peek at

**Comment by kwombach12** [comment]
@srpomeroy Can you elaborate on the UX issues that come from aggregating by `label:example_label_name`? Not sure I understand the feature request here

**Comment by srpomeroy** [comment]
> @srpomeroy Can you elaborate on the UX issues that come from aggregating by `label:example_label_name`? Not sure I understand the feature request here

The user working with the data would need to know the label key to provide, and they would need to offer it without error. This is simple for something like `app` but more complex for something like `company.domain.com/complex_label-key`. Especially when there are multiple complex labels to aggregate by.

**Comment by srpomeroy** [comment]
Relates to [#1016](https://github.com/kubecost/cost-analyzer-frontend/issues/1016)

**Comment by jessegoodier** [comment]
+1 from another customer today: `customer` and `sub-product`
+1 from another customer yesterday: `project`

**Comment by teevans** [comment]
@kwombach12 / @dwbrown2 - Friendly product ping here.

**Comment by kwombach12** [comment]
@teevans I was hoping to add this for 1.102 but it seems we didnt have the capacity... if you can find some extra capacity to pick this up for us I would be fully supportive!

**Comment by dwbrown2** [comment]
Thanks for reporting. Saved reports was aimed at partially solving this... i.e. aggregate by any custom label set and then name a report. Does this meet needs here? Any feedback on where it's missing?

**Comment by srpomeroy** [comment]
Saved reports are a good stop-gap that works well for allocations. Though it does get complex if you have many labels to aggregate and also filter by. You'd need a lengthy list of saved reports which would be difficult to manage.

We also don't currently have saved reports in savings. If you wanted to filter/aggregate container right-sizing by labels, you are doing it manually each time.

**Comment by kc-adawson** [comment]
Hearing this from more and more users - Looking for the exact same functionality we have right now but with the ability to have a custom name for the label group. 

Also if there was a way to combine multiple labels/annotations/node labels together in these custom groups it would be awesome. Right now it works only if an asset meets every tag specified in the group, not in a "Check for TagA, IfNot Check TagB, IfNot Check Tag C" type of setup. That may need a separate discussion.

**Comment by jessegoodier** [comment]
to simplify this- most of the value is having these aliases in the UI. 

the concern is that teams with many people using kubecost don't know what a saved report is or the exact text they need to type in for the aggregation/filter.

Regarding the potential that this be `UI only`: a developer pulling from the API can create a query with the actual labels (no custom mapping). IMO, the developer natively understands this type of syntax needed to make a query.

A proposal (not pushing the actual solution) is to just have this in the front end.

example custom alias helm value:

```
kubecostProductConfigs:
  cloudIntegrationSecret: cloud-integration
  clusterName: federated-primary
  labelMappingConfigs:
    enabled: true
    custom_alias1_name=my-cost-center
    custom_alias1_label=label:company.com/cost-center
```

and the UI would look like:

![image](https://user-images.githubusercontent.com/31039225/231868416-c4f094be-2f5c-4197-a725-e45337cbb88e.png)
![image](https://user-images.githubusercontent.com/31039225/231868584-75997174-0b82-4f2b-b06f-7683e4df1e52.png)
![image](https://user-images.githubusercontent.com/31039225/231868724-4c60e94f-2699-4016-b48a-0124d674c7a9.png)
![image](https://user-images.githubusercontent.com/31039225/231868904-c1d39794-50fe-40d9-94e6-2819b6340a22.png)


@srpomeroy any edits here?

**Comment by kwombach12** [comment]
@nealormsbee can you comment on the feasibility of the proposal above? If workable, that would help us prioritize in 104

**Comment by nealormsbee** [comment]
Hey @kwombach12 , sorry for the delay here. The core of the idea isn't too cumbersome. It gets a little more complicated when we think about "what label mappings should apply where?". I think we might want 3 copies of Jesse's helm chart example: one for allocations, one for assets, and one for cloud costs. And then we have to make sure that we present the options as available and map them correctly for any place in the app that those calls are made.

I would ballpark about a week.

**Comment by jessegoodier** [comment]
@nealormsbee thanks for that update, made me think a bit more on how this would be used. 

For the use case where the user wanted a label for "my-cost-center" - I would think this would be global in kubecost in order to prevent confusion. 

For the use case of mapping cloudCosts to allocations: I think you all have work being done in 1.104 and I don't know how that would impact this: 
The current Advanced Report UI allows for custom mappings on both sides, so just including the new custom labelMappingConfigs on the "Aggregate" side would keep it simple (see screenshot).

All that said, this is just sharing some current thoughts, you all are the experts here.

![image](https://user-images.githubusercontent.com/31039225/236525718-9e3caf7d-7dd9-4a7e-8934-0760b0c92d87.png)

**Comment by mmurph3** [comment]
@kwombach12 we have another customer waiting on this feature. I'll add it to the FR report.

**Comment by mou** [comment]
Our company also very interested in implementation of this FR

**Comment by kwombach12** [comment]
The feature is very high on our priority list. We will try to have something here in the next few releases

**Comment by mou** [comment]
@kwombach12, it is awesome. Thank you for sharing this.

**Comment by chipzoller** [comment]
I believe this is now complete. Closing.
