### ISSUE TITLE
Removing negative `__idle__`

### ISSUE THREAD

**Issue by thomasvn** [kubecost/cost-analyzer-helm-chart#1965]
## What problem are you trying to solve?

I’m proposing for the Kubecost Allocation APIs to stop returning negative `__idle__`. It can be difficult to interpret, and skews the graphs when displayed on the frontend.

**Details:**
Given that idle is defined as follows:

> *idle_cost = sum(node_cost) - (cpu_allocation_cost + ram_allocation_cost + gpu_allocation_cost)*

where

> *allocation = max(request, usage)*

I always see negative idle if (1) I am entirely missing node metrics such as `node_total_hourly_cost`, or if (2) I am intermittently missing node metrics (i.e. I have one or fewer datapoints for `node_total_hourly_cost` every hour).

## Describe the solution you'd like

I would like for Kubecost to extrapolate existing node metrics if available. Or if node metrics are unavailable, I would like for Kubecost to assume that I am 100% allocated and that there are no idle costs. An additional warning about missing node costs may also be helpful.

## Describe alternatives you've considered

Alternatively, Kubecost can provide more frontend tooltips & documentation to help users understand what negative `__idle__` means, and how to fix it.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-251) by [Unito](https://www.unito.io)

**Comment by kwombach12** [comment]
@thomasvn Thanks for logging this issue, I think its important that we tackle this. In terms of the solution - extrapolating the node metrics feels dangerous... My concern is that it could be complicated to explain how we are extrapolating in the product, and if we are off, users would lose trust in our data.

I would propose we follow your second solution in this scenario and assume that users are 100% allocated and show $0 for __idle__. This should absolutely be accompanied by a warning about missing node costs.
