### ISSUE TITLE
PV attached to workload(s) reporting inaccurate costs (lower) in Allocation page compared to Azure Cost Analysis & Asset Page

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1966]
Thanks for your interest in Kubecost!  To ensure you get the help you need, please follow these guidelines:

- If you have questions about product functionality/usage or need assistance with product installation/configuration, please email support@kubecost.com, where our support engineering team will be happy to help!
- If you have a reproducible bug or a feature request, you're in the right place.  Please include the information requested below.

---
# For reproducible bugs, please provide the following

**Describe the bug**  
PV (attached to a deployment) cost in the allocation page  does not match what is shown in asset and cost analysis (azure) page. The cost of the PV in the asset page DOES match what's in cost analysis (Azure) billing console. The impact here is that a user cannot effectively tie the true cost of the PV attached to the kubernetes deployment back to the namespace which it is running under because it does not match what the Azure billing console and assets page report for the PV. Example: We have a customer showing ~$10 for the last 30 days for a PV  in the azure billing console but in the kubecost UI it's showing ~$1.16 in the overview and allocations page for the same PV attached to the deployment. 

**To Reproduce**  
1. Choose a custom date (1 day)
2. Drill down into kubecost namespace in the allocations page. 
3. Drill down into workload and check the cost for PV the kubecost-thanos-store deployment (customer's comparing a different deployment).
4. Compare this cost in the allocation page for one day in the assets page and azure billing console for the same PV.

**Expected behavior**  
I expect to see the cost match from the billing console -> assets page -> deployment

**Screenshots**  
1. We see the cost here is $0.32 for the PV attached to kubecost-thanos-store
 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/36980248/217843986-08660b57-5352-425b-a757-d937ab5da94e.png">

2. Here we see the Volume that's attached to the workload:

```
% k describe pvc store-data-volume -n kubecost
Name:          store-data-volume
Namespace:     kubecost
StorageClass:  default
Status:        Bound
Volume:        pvc-b6ebde3e-3e89-4ccd-be23-abbf48aceb8f **<---- Volume attached to deployment**
Labels:        app.kubernetes.io/managed-by=Helm
Annotations:   meta.helm.sh/release-name: kubecost
               meta.helm.sh/release-namespace: kubecost
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
               volume.kubernetes.io/selected-node: aks-agentpool-38945443-vmss000000
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      100Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       kubecost-thanos-store-5464fff689-5rltw
Events:        <none>

```
3. Search for this PV in the assets page under kubernetes -> disk in kubecost for the same day. Here we see the cost is $.02 higher:
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/36980248/217850434-1c79fe13-3244-4118-af90-df70e4747e54.png">

4. Search in the Azure cost analysis console for the same PV for the same day. Here we see the cost does match what it's in the assets page but DOES not match what's in the allocations page for the same PV that's attached to deployment:

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/36980248/217851312-1b185e16-a1ed-4ad0-a557-1fb1915559b0.png">

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-252) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
It doesn't seem like the repro here matches what the customer is describing. Here it looks like we're 2/34 or 5% off, not $1.16 / $10. Can you possibly get an etl dump of the customer data to investigate further?
