### ISSUE TITLE
Azure external costs not working anymore

### ISSUE THREAD

**Issue by Mahagon** [kubecost/cost-analyzer-helm-chart#1967]
**Describe the bug**  
Kubecost (Chart version 1.99.0 and 1.100.0) suddenly stopped finding external costs of azure:

![image](https://user-images.githubusercontent.com/874007/217843572-a03ab7a6-e325-4b75-9844-affdc9fac5be.png)

kubecost is deployed 4 times and in all 4 subscriptions we got the same behavior.

**To Reproduce**  
I wish i knew :/

**Expected behavior**  
Pricing of the azure resources inside kubecost

**Screenshots**
Cloud Integration config seems valid
![Cloud integration](https://user-images.githubusercontent.com/874007/217809990-50d25454-b35c-45e9-8ead-7b90bff6fd12.png)

**Collect logs (please complete the following information):**
reoccurring log entries:

- WRN CostModel: failed to find node for cluster-one/aks-system-**************
- WRN could not fetch Azure node pricing for region germanywestcentral from cache (will use default westus2 instead): file /var/configs/azurenodeprices-germanywestcentral.json not found
- WRN AbandonedWorkloads: NaN NetworkReceiveBytes
- WRN ETL: Allocation: ComputeAllocation: raw allocation data missing for cluster-one/aks-user-******/namespace/podname
- WRN attempted to use nodeType [H16] with misconfigured HourlyPrice
- WRN attempted to use nodeType [D16as v4] with misconfigured HourlyPrice
- WRN attempted to use nodeType [D16a v4] with misconfigured HourlyPrice
- WRN attempted to use nodeType [NC12s v2] with misconfigured HourlyPrice
- WRN attempted to use nodeType [ND12s] with misconfigured HourlyPrice
- WRN attempted to use nodeType [NC12s v3] with misconfigured HourlyPrice
- WRN attempted to use nodeType [NV12s v3] with misconfigured HourlyPrice
- WRN attempted to use nodeType [NC12] with misconfigured HourlyPrice
- WRN attempted to use nodeType [NV12] with misconfigured HourlyPrice
- WRN attempted to use nodeType [NP10s] with misconfigured HourlyPrice
- WRN ETL: CloudUsage[subscriptionid/costexport]: Build[bUXAY]: CloudUsageSet is empty for [2022-11-09T00:00:00+0000, 2022-11-10T00:00:00+0000) and did not update.
- ERR ETL:  CloudUsage[subscriptionid/costexport]: Build[bUXAY]:  failed to load range from back up 2022-11-09 00:00:00 +0000 UTC - 2022-11-10 00:00:00 +0000 UTC: file does not exist
- could not get account tags for provider []: GetAccountTagsByAccount unimplemented for Azure.
- ETL: Asset[1d]: Reconciliation[]: Run[MnXux]: AssetSetRange is empty for [2023-02-05T00:00:00+0000, 2023-02-09T00:00:00+0000)
- **ERR ETL: Asset[1d]: Reconciliation[]: Run[MnXux]: error: Configure Azure Storage Failed azure storage config not found**
- **ERR ETL: CloudUsage[]: Run[mNldX]: QueryCloudUsage error for [2023-02-06T00:00:00+0000, 2023-02-10T00:00:00+0000): Configure Azure Storage Failed azure storage config not found**

** Cost Export **
![image](https://user-images.githubusercontent.com/874007/217846405-062f5180-2ac2-48a3-b5c0-8760041749dd.png)

The csv export is also still working:
`invoiceId,previousInvoiceId,billingAccountId,billingAccountName,billingProfileId,billingProfileName,invoiceSectionId,invoiceSectionName,resellerName,resellerMpnId,costCenter,billingPeriodEndDate,billingPeriodStartDate,servicePeriodEndDate,servicePeriodStartDate,date,serviceFamily,productOrderId,productOrderName,consumedService,meterId,meterName,meterCategory,meterSubCategory,meterRegion,ProductId,ProductName,SubscriptionId,subscriptionName,publisherType,publisherId,publisherName,resourceGroupName,ResourceId,resourceLocation,location,effectivePrice,quantity,unitOfMeasure,chargeType,billingCurrency,pricingCurrency,costInBillingCurrency,costInPricingCurrency,costInUsd,paygCostInBillingCurrency,paygCostInUsd,exchangeRatePricingToBilling,exchangeRateDate,isAzureCreditEligible,serviceInfo1,serviceInfo2,additionalInfo,tags,PayGPrice,frequency,term,reservationId,reservationName,pricingModel,unitPrice,costAllocationRuleName,benefitId,benefitName,provider`

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-253) by [Unito](https://www.unito.io)

**Comment by thomasvn** [comment]
@Mahagon Thanks for reporting, and for sharing screenshots & logs! I think the following error is most likely the cause:

> ERR ETL: CloudUsage[]: Run[mNldX]: QueryCloudUsage error for [2023-02-06T00:00:00+0000, 2023-02-10T00:00:00+0000): Configure Azure Storage Failed azure storage config not found*

Could you validate that your `cloud-integration.json` and its secret are still [configured properly](https://docs.kubecost.com/install-and-configure/install/cloud-integration/azure-out-of-cluster#step-2-provide-access-to-azure-storage-api)? I’d recommend checking the k8s secret, as well as the `/var/cloud-integration/cloud-integration.json` within the running container.

**Comment by Mahagon** [comment]
hi, thanks for the quick answer
it seems azure was at fault? unsure.
Without doing anything the data is coming in now...
