### ISSUE TITLE
OpenShift Network-Costs not working

### ISSUE THREAD

**Issue by metalbahamut** [kubecost/cost-analyzer-helm-chart#1968]
Hi,

**Describe the bug**  
We've installed Kubecost in Openshift 4.11 following the guide "https://docs.kubecost.com/install-and-configure/install/provider-installations/openshift-kubecost-install" but network-costs DaemonSet seems to not be working (no metrics in Prometheus).

Can you provide support? Maybe we have something wrong configured.

**To Reproduce**  
https://docs.kubecost.com/install-and-configure/install/provider-installations/openshift-kubecost-install

**Expected behavior**  
Network Costs.

**Screenshots**  
![image](https://user-images.githubusercontent.com/70911101/217883856-04a058d3-481c-479b-bfa8-7657aa3ff254.png)

**Collect logs (please complete the following information):**
I0209 16:41:27.184570 1 netroutes.go:61] +----------------------- Routing Table -----------------------------
I0209 16:41:27.184583 1 netroutes.go:63] | Destination: 10.217.192.144, Route: 0.0.0.0
I0209 16:41:27.184588 1 netroutes.go:63] | Destination: 168.63.129.16, Route: 10.217.192.145
I0209 16:41:27.184590 1 netroutes.go:63] | Destination: 169.254.169.254, Route: 10.217.192.145
I0209 16:41:27.184592 1 netroutes.go:63] | Destination: 172.30.0.0, Route: 0.0.0.0
I0209 16:41:27.184594 1 netroutes.go:63] | Destination: 0.0.0.0, Route: 10.217.192.145
I0209 16:41:27.184596 1 netroutes.go:63] | Destination: 10.128.0.0, Route: 0.0.0.0
I0209 16:41:27.184598 1 netroutes.go:65] +-------------------------------------------------------------------
I0209 16:42:16.661404 1 cachingnetworkmap.go:123] Removing Cached Pod: openshift-marketplace/redhat-operators-vrzn2
I0209 16:42:22.323511 1 networkendpoints.go:106] Error returned to client: Failed to load conntrack data from file and utility
I0209 16:42:55.914180 1 networkendpoints.go:106] Error returned to client: Failed to load conntrack data from file and utility
I0209 16:44:27.171626 1 networktraffic.go:200] Removed 0 expired entries.

\---

\# HELP kubecost_network_costs_parse_time kubecost_network_costs_parse_time total time in milliseconds it took to parse conntrack entries
\# TYPE kubecost_network_costs_parse_time gauge
kubecost_network_costs_parse_time 0
\# HELP kubecost_network_costs_parsed_entries kubecost_network_costs_parsed_entries total parsed conntrack entries
\# TYPE kubecost_network_costs_parsed_entries gauge
kubecost_network_costs_parsed_entries 0
\# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
\# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 20.95

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-254) by [Unito](https://www.unito.io)

**Comment by thomasvn** [comment]
@metalbahamut Thanks for reporting! When deploying the network-costs daemonset on OpenShift, are you setting [`hostNetwork: true`](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.100/cost-analyzer/templates/cost-analyzer-network-costs-template.yaml#L37)? Is the host you're running network-costs on allowing it to [use the underlying kernel module](https://docs.kubecost.com/install-and-configure/advanced-configuration/network-costs-configuration#kubernetes-network-traffic-metrics) for network data?

**Comment by metalbahamut** [comment]
Hi,

Yes, "hostNetwork: true" is set but I just realized that "privileged: true" was not (I don't know why. Now I can see the Prometheus metrics in network-costs DaemonSet but still nothing shown in the UI. We are running the free tier at moment (not sure if it's a pay feature).

Regards,

**Comment by thomasvn** [comment]
@metalbahamut Do you see costs on the "/network" page?

**Comment by metalbahamut** [comment]
Hi @thomasvn,
After all the weekend, now we can see some network metrics. It seems that if the cost is 0.00 then metrics don't appear in "Network Costs Breakdown" and due to it's an staging cluster, we have very little traffic.
Thanks for pointing me in the correct direction regarding privileged Pods :)
Regards,
