### ISSUE TITLE
allow custom minimum cpu and memory params for rightsizing v2

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#1974]
**What problem are you trying to solve?**
Customer requesting ability to set minimum cpu and memory recommendation using request sizing v2 api.

**Describe the solution you'd like**
Still TBD if customer wants this in UI. But they are using API for sure.
Can see potential for helm values, but also TBD.

**Describe alternatives you've considered**
NA

**How would users interact with this feature?**
API args.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-259) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
From thread offline:

```
these are currently hardcoded: https://github.com/kubecost/kubecost-cost-model/blob/2f37b267640d104580d443ecb9c2bdfcba326056/pkg/savings/requestsizing/v2/handlers.go#L103-L104
but could absolutely be turned into API params
```

**Comment by michaelmdresser** [comment]
PR linked to close this request.

**Comment by jessegoodier** [comment]
Customer confirmed that API is all they are asking for, though I can see a lot of benefit to UI config as well.

**Comment by michaelmdresser** [comment]
cc @nealormsbee adding a UI field for this is easy, but low priority right now. Could be a good onboarding task if you have anyone new coming on board soon.
