### ISSUE TITLE
Kubecost no longer supports BYO prometheus-node-exporter or kube-state-metrics

### ISSUE THREAD

**Issue by aaroniscode** [kubecost/cost-analyzer-helm-chart#1975]
**Describe the bug**  

With the introduction of PR #1805 customers are missing metrics when they have existing prometheus-node-exporter and kube-state-metrics and follow the [documentation](https://docs.kubecost.com/install-and-configure/install/custom-prom#disable-node-exporter-and-kube-state-metrics-recommended) which says:

### Disable node-exporter and kube-state-metrics (recommended)

If you have node-exporter and/or KSM running on your cluster, follow this step to disable the Kubecost included versions. Additional detail on [KSM requiments](/ksm-metrics.md).

> **Note**: In contrast to our recommendation above, we do recommend disabling the Kubecost's node-exporter and kube-state-metrics if you already have them running in your cluster.

  ```sh
  helm upgrade --install kubecost \
    --repo https://kubecost.github.io/cost-analyzer/ cost-analyzer \
    --namespace kubecost --create-namespace \
    --set prometheus.nodeExporter.enabled=false \
    --set prometheus.serviceAccounts.nodeExporter.create=false \
    --set prometheus.kubeStateMetrics.enabled=false
  ```

But when you follow the documentation above, kubecost's Prometheus won't scrape the existing prometheus-node-exporter and kube-state-metrics due to:

```
          - source_labels: [__meta_kubernetes_endpoints_name]
            action: keep
            regex: (kubecost-kube-state-metrics|kubecost-prometheus-node-exporter|kubecost-network-costs)
```

Code link [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/eb5010d956aae3a764a9f943c371b3f9e6cda850/cost-analyzer/charts/prometheus/values.yaml#L1287) Typically installs have names like `kube-state-metrics` and `prometheus-node-exporter`. Perhaps we want to add to `kube-state-metrics|prometheus-node-exporter` to the regex?  Like:

```
          - source_labels: [__meta_kubernetes_endpoints_name]
            action: keep
            regex: (kubecost-kube-state-metrics|kubecost-prometheus-node-exporter|kubecost-network-costs|kube-state-metrics|prometheus-node-exporter)
```

Note that the EKS optimized bundle of Kubecost doesn't include prometheus-node-exporter metrics because Node Exporter is disabled in the [EKS specific values file](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values-eks-cost-monitoring.yaml#L179).

**Expected behavior**  
Kubecost should scrape prometheus-node-exporter and kube-state-metrics when following the [documentation](https://docs.kubecost.com/install-and-configure/install/custom-prom#disable-node-exporter-and-kube-state-metrics-recommended) and trying to use existing prometheus-node-exporter and kube-state-metrics.

Happy to author a PR if the team agrees on the approach above or proposes something similar. Thanks.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-260) by [Unito](https://www.unito.io)

**Comment by thomasvn** [comment]
@aaroniscode Thanks for reporting! I agree that this is a bug, and I agree with your proposed solution. As a slight modification, what do you think about the following?

```yaml
# Removed kubecost-network-costs because it should have its own scrapeConfig
          - source_labels: [__meta_kubernetes_endpoints_name]
            action: keep
            regex: (.*kube-state-metrics|.*prometheus-node-exporter)
```

Are you interested in authoring the PR and testing via `helm template` and `helm install`?

cc @keithhand

**Comment by aaroniscode** [comment]
> Are you interested in authoring the PR and testing via helm template and helm install?

@thomasvn yes, I'll work on it this week

**Comment by aaroniscode** [comment]
@thomasvn Note I didn't remove `kubecost-network-costs` for 2 reasons:

1. The scrape job currently does some relabeling of those metrics in the `metric_relabel_configs` just a few lines below the change.
2.  You noted `kubecost-network-costs` should have its own scrapeConfig and I didn't see one and figured it would go in another PR. I'm not familiar enough with it to make a change.

If I'm wrong and it should still be removed, just let me know.

**Comment by thomasvn** [comment]
@aaroniscode The scrapeConfig for the `kubecost-network-costs` is in the [values.yaml](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.100/cost-analyzer/values.yaml#L482-L502). Therefore I think it's safe to remove it here!

**Comment by Danial968** [comment]
Hi, was wondering if the regex could be less strict for the node exporter. I don't see why there is a need for the "prometheus" to be prepended in front of the node-exporter. 

Could I suggest changing it from `.*prometheus-node-exporter` to `.*node-exporter` instead? 

```
          - source_labels: [__meta_kubernetes_endpoints_name]
            action: keep
            regex: (.*kube-state-metrics|.*node-exporter|kubecost-network-costs)
```

If it is ok I wouldn't mind raising a PR for it.

**Comment by kwombach12** [comment]
@teevans @cliffcolvin What do you guys think of this change? cc: @thomasvn

**Comment by thomasvn** [comment]
@Danial968 Yes that _should_ be ok! Could you write a PR for this change?

**Comment by chipzoller** [comment]
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.
