### ISSUE TITLE
Kubecost v1.100.0 fails to pick up the correct external label in advanced reporting

### ISSUE THREAD

**Issue by rj425** [kubecost/cost-analyzer-helm-chart#1977]
### Issue
Kubecost v1.100.0 is picking up the actual external label mapping (defined in values.yaml) in cloud breakdown advanced reporting section instead of the one that Kubecost itself converted the actual label into.
- Actual external label - `test:v1:costAllocation1`
- Kubecost converted label - `test_v1_cost_allocation1`
- Kubecost picks up `test:v1:costAllocation1` as the cloud breakdown mapping in advanced reporting.

### To Reproduce
1. We have defined the external labels mapping in our values.yaml like this:
```
labelMappingConfigs:
  enabled: true
  team_external_label: test:v1:costAllocation1
  namespace_external_label: test:v1:costAllocation2
  deployment_external_label: test:v1:costAllocation3
```
2. Kubecost is converting the external labels from `test:v1:costAllocation1` to `test_v1_cost_allocation1` as noticed in the assets page.  This converted label works fine for filtering and aggregrating.
3. In the advanced reporting section, when `Aggregate by` option is set to say team or namespace, cloud breakdown label is set to external label from values.yaml which shows external cost of 0.

### Expected behavior
Cloud breakdown option should be set to Kubecost converted external label for it to render the correct external cost.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-262) by [Unito](https://www.unito.io)

**Comment by dr460neye** [comment]
I face the same issue for v. 098 and 0.99

**Comment by AjayTripathy** [comment]
hmm.. cc @nealormsbee seems like a quick fix? Think this is just a conversion on the FE before sending data to the API or vice versa?

**Comment by nealormsbee** [comment]
Yep, this should be really straightforward to fix. We'll make sure it's working correctly in v1.101.

Thank you @rj425 for filing and @AjayTripathy for the flag!

**Comment by nealormsbee** [comment]
@nikovacevic @teevans any chance we can handle this on the server so the UI doesn't have to handle sanitizing labels for Prometheus? Just let me know.

**Comment by nikovacevic** [comment]
We need to spend some time understanding this better. May make v1.101, may make v1.102.

**Comment by nealormsbee** [comment]
Good deal. I had initially labeled this P0. Downgrading to P1 since there's a workaround of using sanitized labels in the KC config. Let's keep this in mind for 1.102 if it doesn't make 1.101.

**Comment by kc-adawson** [comment]
Received another request on fixing this ticket, adding another +1 here

**Comment by teevans** [comment]
My fear here is patching on the FE, then sending to the BE is going to cause problems for those who just use the API. Throwing in the Core backlog for 102. We should be able to get to this during bug week.

**Comment by AjayTripathy** [comment]
Makes sense guys, thank you.

**Comment by rj425** [comment]
Just updated our kubecost from from v1.101.2 to v1.102.0-rc.0 pre release. This issue still persists.
Is it because this pre-release does not have the fix yet?

**Comment by teevans** [comment]
@rj425 - that's correct. It's still in line to get fixed for 102 hopefully. We'll keep you posted!

**Comment by MrJW27** [comment]
@teevans - Can you provide eta on this? Thanks!

**Comment by teevans** [comment]
@MrJW27 - Apologies, this didn't make 102 - but I have it at the top of the list of items to be shipped in 103! Thank you for being patient with us!

**Comment by kwombach12** [comment]
@MrJW27 @rj425 @kc-adawson We are struggling to repro this issue. Can you provide us more context on your environment or perhaps a video recording of your issue?

**Comment by jessegoodier** [comment]
From some internally testing I did, this seems to work for me. 
Can you confirm this is still an issue @MrJW27 ? 

demo: https://jesse.test-1.kubecost.xyz/advanced-reporting?agg=deployment&cloudJoinLabel=label%3Acustom%3Alabel 
```yaml
kubecostProductConfigs:
  labelMappingConfigs:
    deployment_external_label: custom:label
    enabled: true
```
aws s3 tag:
```
Key | Value
custom:label | jesse

**Comment by rj425** [comment]
> @MrJW27 @rj425 @kc-adawson We are struggling to repro this issue. Can you provide us more context on your environment or perhaps a video recording of your issue?

@kwombach12 
I have messaged you the recording on slack.

**Comment by chipzoller** [comment]
Closing. Stale.
