### ISSUE TITLE
Harcoded namespace for Admission Controller

### ISSUE THREAD

**Issue by k7k0** [kubecost/cost-analyzer-helm-chart#1980]
**Describe the bug**  
When enabling `kubecostAdmissionController` resources uses the harcoded `kubecost` namespace value instead of `{{ .Release.Namespace }}` 

**To Reproduce**  
1. Install the helm chart setting a custom namespace `-n my-namespace` setting `kubecostAdmissionController.enabled: true` and `kubecostAdmissionController.readonly: true`
1. The [webhook server](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/kubecost-admission-controller-service-template.yaml#L7) and the [ValidatingWebhookConfiguration](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/kubecost-admission-controller-template.yaml#L23) uses the harcoded `kubecost` namespace

**Expected behavior**  
Resources should use custom `my-namespace`

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-265) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
Hey @k7k0 -- in this beta release of the kubecostAdmissionController we're only supporting deployment in the kubecost namespace for evaluation. We expect to have guidance on how to support more namespaces in upcoming releases.

The main issue here is that an SSL cert is required for admission controllers and those are minted on a per DNS level, and the DNS (ie webhook-server.kubecost.svc). Here's the design for supporting more namespaces in the coming v1.101 release: https://docs.google.com/document/d/1CV5d-2ky2xLLKLQJCQllbyfNHdgfe5wtoeQnyVH9un4/edit

and if you want to test this earlier I will follow up with a PR to support alternate namespaces soon!

**Comment by k7k0** [comment]
Thanks for the quick response, it would be nice to try it. Let me know, thanks

**Comment by AjayTripathy** [comment]
Hey @k7k0 this is merged and will be available with documentation in our v1.101 release scheduled for Friday!
