### ISSUE TITLE
Upgrade from v1.99 to v1.100 causes go.panic when hitting landing page

### ISSUE THREAD

**Issue by praveenkumar0566** [kubecost/cost-analyzer-helm-chart#1981]
**Describe the bug**  

When trying to upgrade to v1.100.0 , the landing page of UI is not displaying any cost metrics. 

IMAGE REMOVED

**To Reproduce**  
Upgrade to v1.100.0 

**Note**: The customer has a federated cluster set up using Thanos.   However, both kubecost pods takes over 10 minutes for the readiness probe to become healthy.

**Expected behavior**  
Upon successful upgrade, kubecost UI should show data.

**Screenshots**  
**More Background:**

The upgrade is done by updating the Chart dependency to cost-analyzer version from 1.99.0 to 1.100.0 of the ArgoCD Application.  Essentially what ArgoCD does is renders the helm chart, ie.., helm template... and applies the rendered manifests.
 
For this upgrade, the kubecost pod took a long time to pass readiness probe, I didn't time it but maybe 10 minutes.  Once healthy, the UI showed error retrieving data for all the components.  

**Collect logs (please complete the following information):**
**Panic error is seen**
```
2023-02-07T20:28:11.949822987Z INF Panic: runtime error: invalid memory address or nil pointer dereference
StackTrace: goroutine 7723 [running]:
github.com/opencost/opencost/pkg/errors.dispatch({0x2aa5ae0, 0x5209870}, 0x1)     /app/opencost/pkg/errors/panic.go:115 +0x4f github.com/opencost/opencost/pkg/errors.HandleHTTPPanic({0x3bb3de0, 0xc00507f290}, 0x7c?)     /app/opencost/pkg/errors/panic.go:108 +0x78 panic({0x2aa5ae0, 0x5209870})     /usr/local/go/src/runtime/panic.go:884 +0x213 github.com/opencost/opencost/pkg/kubecost.(*AssetSetRange).NewAccumulation(0xc002596780?)     /app/opencost/pkg/kubecost/asset.go:3252 +0x18 github.com/kubecost/kubecost-cost-model/pkg/etl.(*ETL).GetAssetsHandler.func2({0x3bb3de0, 0xc00507f290}, 0xc0007e7100, {0x3?, 0x0?, 0xc0016075a0?})     /app/kubecost-cost-model/pkg/etl/handlers.go:735 +0x90f github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc002426840, {0x3bb3de0, 0xc00507f290}, 0xc0007e7100)     /go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0x81c github.com/kubecost/kubecost-cost-model/pkg/product.WindowRestrictionMiddleware.func1({0x3bb3de0, 0xc00507f290}, 0xc0007e7100)     /app/kubecost-cost-model/pkg/product/productkeymiddleware.go:63 +0x486 net/http.HandlerFunc.ServeHTTP(0xc002388f00?, {0x3bb3de0?, 0xc00507f290?}, 0xc0010b4b00?)     /usr/local/go/src/net/http/server.go:2122 +0x2f github.com/kubecost/kubecost-cost-model/pkg/auth.AuthSAMLMiddleware.func1({0x3bb3de0, 0xc00507f290}, 0xc0007e7100)     /app/kubecost-cost-model/pkg/auth/samlauth.go:336 +0x7ea net/http.HandlerFunc.ServeHTTP(0x2c3dc40?, {0x3bb3de0?, 0xc00507f290?}, 0xc003f7a930?)     /usr/local/go/src/net/http/server.go:2122 +0x2f net/http.(*ServeMux).ServeHTTP(0x30?, {0x3bb3de0, 0xc00507f290}, 0xc0007e7100)     /usr/local/go/src/net/http/server.go:2500 +0x149 github.com/opencost/opencost/pkg/errors.PanicHandlerMiddleware.func1({0x3bb3de0?, 0xc00507f290?}, 0x493057?)     /app/opencost/pkg/errors/panic.go:76 +0x8f net/http.HandlerFunc.ServeHTTP(0x293de60?, {0x3bb3de0?, 0xc00507f290?}, 0x1?)     /usr/local/go/src/net/http/server.go:2122 +0x2f github.com/opencost/opencost/pkg/metrics.ResponseMetricMiddleware.func1({0x3bbf480?, 0xc001344c40}, 0xc0007e7100)     /app/opencost/pkg/metrics/httpmetricmiddleware.go:25 +0x124 net/http.HandlerFunc.ServeHTTP(0xc002984a80?, {0x3bbf480?, 0xc001344c40?}, 0xc0007e7100?)     /usr/local/go/src/net/http/server.go:2122 +0x2f github.com/rs/cors.(*Cors).Handler.func1({0x3bbf480, 0xc001344c40}, 0xc0007e7100)     /go/pkg/mod/github.com/rs/cors@v1.8.2/cors.go:231 +0x1c4 net/http.HandlerFunc.ServeHTTP(0xc002ae6f2c?, {0x3bbf480?, 0xc001344c40?}, 0x46d3ae?)     /usr/local/go/src/net/http/server.go:2122 +0x2f net/http.serverHandler.ServeHTTP({0xc00507f1d0?}, {0x3bbf480, 0xc001344c40}, 0xc0007e7100)     /usr/local/go/src/net/http/server.go:2936 +0x316 net/http.(*conn).serve(0xc00141cd80, {0x3bc0c40, 0xc0019a9ef0})     /usr/local/go/src/net/http/server.go:1995 +0x612 created by net/http.(*Server).Serve     /usr/local/go/src/net/http/server.go:3089 +0x5ed
```

I verified the logs, there are no suspected errors or warning related to this issue.

Will ping logs directly to chat if required, to avoid exposing any potentially sensitive information.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-266) by [Unito](https://www.unito.io)

**Comment by mbolt35** [comment]
Source of the panic looks to be: 
```
github.com/opencost/opencost/pkg/kubecost.(*AssetSetRange).NewAccumulation(0xc002596780?)
     /app/opencost/pkg/kubecost/asset.go:3252
```

**Comment by teevans** [comment]
@nikovacevic can we escalate this and get it triaged? It sounds like this could be a P0 that could require a patch

**Comment by nikovacevic** [comment]
On it

**Comment by kaelanspatel** [comment]
Fix is here, can cherry-pick once merged if needed. https://github.com/opencost/opencost/pull/1687

**Comment by rossfisherkc** [comment]
@teevans @kaelanspatel question around best practices for customers, should we ask them to cherry pick or will we be releasing a version bump? Can the customer just do a re-install by helm to pick this up?

**Comment by teevans** [comment]
@rossfisherkc - Good question. We don't have a release patch for this currently, so this would *in theory* roll into 1.102. Is this something we're seeing a lot of? We can patch if necessary.

**Comment by rossfisherkc** [comment]
@teevans I would recommend rolling out sooner than later if able, we are seeing case uptick and downgrades cc @kubecost/support-engineers

**Comment by teevans** [comment]
For all watching this, we're going to go ahead and release a patch version that will fix this issue. V1.100.2 should be available later today.

**Comment by nikovacevic** [comment]
Cherry pick here: https://github.com/opencost/opencost/pull/1689

**Comment by rossfisherkc** [comment]
Thanks @teevans - not to be "that guy" buuut, I don't yet see it on our releases page and have a customer or two wanting to upgrade ASAP. Is it safe to just pull the helm and do an upgrade as of this time?

**Comment by nealormsbee** [comment]
Hey, @rossfisherkc! Sorry about that -- I forgot that our patches don't automatically create new releases anymore.

We'll get those published today, but in the meantime you're totally good to

```bash
helm repo update
helm upgrade -i etc etc --devel
```

The `--devel` will get you 1.100.2-rc.0, which resolves the issue this ticket describes. We should have an `rc.1` coming out later today which will further reduce memory consumption when loading the Overview.
