### ISSUE TITLE
Azure Out of Cluster Costs didn't work

### ISSUE THREAD

**Issue by Malithkalhara** [kubecost/cost-analyzer-helm-chart#1988]
I'm try to integrate azure with kubcost. ATM all the reports are generated into azure storage account but I got below issue in the cost-anlyzer pod.

**Kubecost helm version : 1.100.1**

Please find the error log below.

> 2023-02-16T04:37:47.250640637Z INF Azure Storage: retrieving blob: /kubecost/xxxxx/kubecostexport_eb890b46-96db-429a-88ef-59a808676fb1.csv
2023-02-16T04:37:47.277227761Z ERR failed to parse usage date: '2023-02-13'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x22b14b4]
goroutine 365 [running]:
github.com/kubecost/kubecost-cost-model/pkg/provider.(*Azure).parseCSVForCloudAsset(0x0?, 0x1fb8200?, {0x0?, 0x0?, 0x0?}, {0x1fa46c5?, 0x7f2692b66bf8?, 0x0?}, {0xc001cf5680, 0x4, ...})
	/app/kubecost-cost-model/pkg/provider/azure.go:324 +0x214
github.com/kubecost/kubecost-cost-model/pkg/provider.(*Azure).csvToCloudAssets(0xc002a357a0, {0x3?, 0x0?, 0x0?}, {0x0?, 0xc002b1fc10?, 0x0?}, {0xc001cf5680, 0x4, 0x4}, ...)
	/app/kubecost-cost-model/pkg/provider/azure.go:293 +0x16c
github.com/kubecost/kubecost-cost-model/pkg/provider.(*Azure).QueryCloudUsage(0xc002a357a0, {0x30?, 0xc003296f38?, 0x0?}, {0x3?, 0x0?, 0x0?}, 0x458c91?, 0x3bc0bd0?)
	/app/kubecost-cost-model/pkg/provider/azure.go:266 +0x153
github.com/kubecost/kubecost-cost-model/pkg/cloudusage.(*ETLStore).run(0xc002a15d60, 0xc0024f68a0)
	/app/kubecost-cost-model/pkg/cloudusage/etlstore.go:723 +0xcc6
created by github.com/kubecost/kubecost-cost-model/pkg/cloudusage.(*ETLStore).Run
	/app/kubecost-cost-model/pkg/cloudusage/etlstore.go:443 +0x1cd

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-270) by [Unito](https://www.unito.io)

**Comment by thomasvn** [comment]
@Malithkalhara Thanks for reporting this. It seems Kubecost is unable to parse your Azure Cost Export. It may help to have some more context about the following:

- When setting up [Azure Cost Exports](https://docs.kubecost.com/install-and-configure/install/cloud-integration/azure-out-of-cluster), did you set "Daily export of month-to-date costs" and "Amortized cost (Usage and Purchases)" options while leaving off "File Partitioning"?
- Did you perform any post processing of the Azure Cost Export data?

Also, given that we will likely need to review your Azure Cost Export csv file to better validate the error, could you send an email to support@kubecost.com with this question? Be sure to include a link to this GitHub issue so you don’t have to document your issue twice! One of our dedicated support engineers will be able to help you with the matter. All communication will be handled via that ticket moving forward to ensure privacy of your data as we work to resolve the issue.

**Comment by Malithkalhara** [comment]
@thomasvn Sure I ll send the required details via email.

- When setting up [Azure Cost Exports](https://docs.kubecost.com/install-and-configure/install/cloud-integration/azure-out-of-cluster), did you set "Daily export of month-to-date costs" and "Amortized cost (Usage and Purchases)" options while leaving off "File Partitioning"? **--> Yes All are configured as your documentation.**
- Did you perform any post processing of the Azure Cost Export data? **--> No**

**Comment by Sean-Holcomb** [comment]
@Malithkalhara I have just merged a change that I think will address the issue you are experiencing. It will be in the [nightly build](https://docs.kubecost.com/architecture/release-process#nightly-releases) later this evening if you would like to give it a try. If you are able to give it a try, please let us know if you experience any more issues.
