### ISSUE TITLE
Improved error handling on Orphaned Resources savings page

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1989]
**What problem are you trying to solve?**
Specifically, when working with AWS (this might be relevant on other cloud providers, I haven't tested directly), the page fails to load when there are IAM errors on the orphaned resources page. It doesn't provide much information as to why. Generally, this is related to the node instance role not having proper account permissions. This might be due to not having permissions, but also when the active permission prevents access to an outside region, as a user reported a number displaying on the summary card but nothing on the primary page.

![image](https://user-images.githubusercontent.com/43491549/219493927-3b16bfcc-9f2a-47d7-9f68-facb7ca2e756.png)

![image](https://user-images.githubusercontent.com/43491549/219494038-4382d9f7-d535-456c-96cc-60f14a8b49bb.png)

**Describe the solution you'd like**
At the minimum, it would be nice to have a more apparent error that the issue with loading on this page is due to permission errors related to the IAM of the cluster. 

A more in-depth solution would be if there were a way that we could partially load the information that it appears we might be gathering from the summary card and display an error for "We couldn't gather information for regions: `us-west-2`. Check your IAM permissions and try again".

**Describe alternatives you've considered**
Configure IAM with these permissions across every region, or don't use this savings page.

**How would users interact with this feature?**
They would see an error message with details on the permission issue.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-271) by [Unito](https://www.unito.io)

**Comment by kwombach12** [comment]
Great call out @keithhand. My hope is that this is a quick win we can knock out in 1.102.

**Comment by b1gs3xy** [comment]
Hey team, thanks for calling this out & actioning the item. It would be great to implement least access principles here.
i.e. I don't want this single cluster KubeCost instance to have visibility of all regions.

**Comment by runtman** [comment]
What role is this even trying to get the permissions from?

I added `EC2: DescribeAddresses` to the node role for EKS and it still complains. I'm at a loss of what IAM user/role this is even trying to use?

**Comment by runtman** [comment]
I had the same issue, Eventually I managed to find the role in question via cloudtrail and fixed ithe `DescribeAddress` permission, now I get the same $0 figure and a nil pointer dereference error.

```
2023-02-17T14:28:44.181994597Z INF Panic: runtime error: invalid memory address or nil pointer dereference
StackTrace: goroutine 71149 [running]:
github.com/opencost/opencost/pkg/errors.dispatch({0x2aa5ae0, 0x5209870}, 0x1)
        /app/opencost/pkg/errors/panic.go:115 +0x4f
github.com/opencost/opencost/pkg/errors.HandleHTTPPanic({0x3bb3de0, 0xc0032cb680}, 0xc001ed7268?)
        /app/opencost/pkg/errors/panic.go:108 +0x78
panic({0x2aa5ae0, 0x5209870})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/opencost/opencost/pkg/cloud.(*AWS).findCostForDisk(0xc000fc4200, 0xc0048b5980)
        /app/opencost/pkg/cloud/awsprovider.go:1780 +0x9c
github.com/opencost/opencost/pkg/cloud.(*AWS).GetOrphanedResources(0x2c8be80?)
        /app/opencost/pkg/cloud/awsprovider.go:1701 +0x136
github.com/kubecost/kubecost-cost-model/pkg/cmd/costmodel.(*Accesses).OrphanedResourcesHandler(0xc0023befc0, {0x3bb3de0, 0xc0032cb680}, 0x10?, {0xc002cd5a40?, 0x0?, 0xc004f9e04d?})
        /app/kubecost-cost-model/pkg/cmd/costmodel/costmodel.go:1203 +0xd5
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0013192c0, {0x3bb3de0, 0xc0032cb680}, 0xc004e10200)
        /go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0x81c
github.com/kubecost/kubecost-cost-model/pkg/product.WindowRestrictionMiddleware.func1({0x3bb3de0, 0xc0032cb680}, 0xc004e10200)
        /app/kubecost-cost-model/pkg/product/productkeymiddleware.go:26 +0x4f6
net/http.HandlerFunc.ServeHTTP(0x2c3dc40?, {0x3bb3de0?, 0xc0032cb680?}, 0x46805a?)
        /usr/local/go/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0x30?, {0x3bb3de0, 0xc0032cb680}, 0xc004e10200)
        /usr/local/go/src/net/http/server.go:2500 +0x149
github.com/opencost/opencost/pkg/errors.PanicHandlerMiddleware.func1({0x3bb3de0?, 0xc0032cb680?}, 0x493057?)
        /app/opencost/pkg/errors/panic.go:76 +0x8f
net/http.HandlerFunc.ServeHTTP(0x10?, {0x3bb3de0?, 0xc0032cb680?}, 0x0?)
        /usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/opencost/opencost/pkg/metrics.ResponseMetricMiddleware.func1({0x3bbf480?, 0xc0032efb20}, 0xc004e10200)
        /app/opencost/pkg/metrics/httpmetricmiddleware.go:25 +0x124
net/http.HandlerFunc.ServeHTTP(0xc002ce4000?, {0x3bbf480?, 0xc0032efb20?}, 0xc004e10200?)
        /usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/rs/cors.(*Cors).Handler.func1({0x3bbf480, 0xc0032efb20}, 0xc004e10200)
        /go/pkg/mod/github.com/rs/cors@v1.8.2/cors.go:231 +0x1c4
net/http.HandlerFunc.ServeHTTP(0xc004f9e05f?, {0x3bbf480?, 0xc0032efb20?}, 0x46d3ae?)
        /usr/local/go/src/net/http/server.go:2122 +0x2f
net/http.serverHandler.ServeHTTP({0xc0032cb500?}, {0x3bbf480, 0xc0032efb20}, 0xc004e10200)
        /usr/local/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc0074a6b40, {0x3bc0c40, 0xc002cd07e0})
        /usr/local/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3089 +0x5ed
```

The reason we really want to see this feature is because on the dashboard it shows us savings of 1000 dollars and then we click the orphaned section, we get 0 dollars .

**Comment by dwbrown2** [comment]
@teevans @Adam-Stack-PM quick pickup for 101?

**Comment by teevans** [comment]
@Adam-Stack-PM - Can we get this added to the burn down list?

**Comment by Adam-Stack-PM** [comment]
@teevans, Can do.

**Comment by jjarrett21** [comment]
So showing the value from the card on the orphaned resource page is easy enough, I'm not sure if I'm able to show the region and give a more detailed error message like @keithhand suggested. Given the information I have I think that the value not being 0 will be a bit more graceful for the user if I'm wrong and I can grab region from a config I've overlooked pls let me know but, for now cc: this [PR](https://github.com/kubecost/cost-analyzer-frontend/pull/1722)

**Comment by runtman** [comment]
Have you got any information on my error? https://github.com/kubecost/cost-analyzer-helm-chart/issues/1989#issuecomment-1434730341

I only responded here because I was told to do so in slack.
