### ISSUE TITLE
Add 'Network Costs' button to 'Network Costs' tile on Overview Page of New UI

### ISSUE THREAD

**Issue by mclean0328** [kubecost/cost-analyzer-helm-chart#1993]
**What problem are you trying to solve?**
On the old UI on the Overview page, when you look at the 'Network Costs' tile, there is a 'Network Costs' button you can select to that brings you to another page where you can see all network costs broken down by namespace.  The new UI does not have this button and you must select one of the specific namespaces. This then brings you to a new page where you can see network costs only for that specific namespace.

**Describe the solution you'd like**
Add a button on the 'Network Costs' tile that will bring you to a new page where you can see a breakdown of all network costs by namespace.

**Describe alternatives you've considered**
The page to see all network costs by namespace does not necessarily have to be accessible from the 'Network Costs' tile, but it would be great to have it accessible from somewhere.

**How would users interact with this feature?**
Selecting a button to get to the report from the overview page.

<img width="714" alt="Old UI" src="https://user-images.githubusercontent.com/50640513/220377812-1752b476-6c17-4a1e-b203-2729fe3a4ce9.png">

<img width="703" alt="New UI" src="https://user-images.githubusercontent.com/50640513/220377953-878493f7-647d-4640-8529-8856236c39d2.png">

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-275) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
cc @kwombach12 for product input!

**Comment by dwbrown2** [comment]
You're right! cc @nealormsbee @Adam-Stack-PM for 1.101 tracking. Would propose this is P1

**Comment by kwombach12** [comment]
Yes! Lets bring this back in 1.101 if possible. @Annalillie can you please mock how this would look in the new UI?

**Comment by Annalillie** [comment]
@kwombach12 absolutely!

**Comment by Annalillie** [comment]
Here's a screenshot. @kwombach12 let me know your thoughts here.
![image](https://user-images.githubusercontent.com/89574007/220700638-fbc3edff-1ec2-4139-ba1c-764e33e1a294.png)

**Comment by kwombach12** [comment]
I like that!! Thanks @Annalillie. @Adam-Stack-PM @nealormsbee for 1.101 tracking.
