### ISSUE TITLE
AWS Discounts (Enterprise + Private Rate Card) missing on /Cloud and /Assets - v1.100.2

### ISSUE THREAD

**Issue by kc-adawson** [kubecost/cost-analyzer-helm-chart#1995]
**Describe the bug** 

 v1.100.2
 
Kubecost is not accounting for Enterprise or Private Rate Card discounts info from the CUR/Athena.

Looking at 1 days worth of data from the first week of February:

Kubecost /Cloud and /Assets page shows $394
AWS Cost Explorer Amortized Cost - $316.62 (where EDP is $28.18 & Private Rate Card is $49.20)
AWS Cost Explorer Net Amortized cost - $298

The Kubecost /Cloud and /Asset pages currently shows the Amortized Cost without the EDP + Private Rate Card discounts accounted for, causing Kubecost to show higher costs.

This information is within the CUR/Athena data, but not being processed into Kubecost when cloud-integration is enabled [Will update with specific column names]

**Comment by AjayTripathy** [comment]
Thanks @kc-adawson .. waiting on those column names then we can hand this over to eng for further examination.

**Comment by kc-adawson** [comment]
3 records with some dummy data and all columns.
Source: CUR Paraquet file

Actual column name of those EDP Discounts:
```
discount_private_rate_discount
discount_edp_discount
```

[cur-data.csv](https://github.com/kubecost/cost-analyzer-helm-chart/files/10807578/cur-data.csv)

Please note that the records in csv above might not have discount values. But they are present in cur data.

@AjayTripathy @linhlam-kc

**Comment by linhlam-kc** [comment]
Another column that needs to consider is `discount_total_discount` which is the sum of `discount_private_rate_discount` and `discount_edp_discount`

**Comment by AjayTripathy** [comment]
@Sean-Holcomb is this something you can work with? Need any more info?

**Comment by Sean-Holcomb** [comment]
I actually just need the value for `line_item_line_item_type` for the private rate discount items. For EDP discounts it was `EdpDiscount`

**Comment by Sean-Holcomb** [comment]
```
SELECT line_item_line_item_type,
sum(line_item_unblended_cost)
FROM $TABLE
WHERE YEAR = '2023' AND Month = '2'
AND line_item_usage_start_date = date '2023-02-$DAY' 
GROUP BY line_item_line_item_type
```
If they insert their table and the day in question and run this query they can hopefully identify the value I am looking for and match the $49.20

**Comment by kc-adawson** [comment]
@Sean-Holcomb 

In Dev bucket with Kubecost v1.100.2:
>>> df['line_item_line_item_type'].unique()
array(['Usage', 'DiscountedUsage', 'SavingsPlanCoveredUsage',
       'SavingsPlanNegation', 'Tax', 'RIFee'], dtype=object)
       
In Prod bucket with KubeCost v1.99:
>>> dev_df1['line_item_line_item_type'].unique()
array(['Usage', 'SavingsPlanCoveredUsage', 'SavingsPlanNegation', 'Tax'],
      dtype=object)

Here are some sums of those values from the Dev bucket:
>>> sum(dev_df1.loc[dev_df1['line_item_line_item_type'] == 'Usage']['line_item_unblended_cost'])
3824.172212563555
>>> sum(dev_df1.loc[dev_df1['line_item_line_item_type'] == 'SavingsPlanCoveredUsage']['line_item_unblended_cost'])
3733.9631755446158
>>> sum(dev_df1.loc[dev_df1['line_item_line_item_type'] == 'SavingsPlanNegation']['line_item_unblended_cost'])
-3733.963175544609
>>> sum(dev_df1.loc[dev_df1['line_item_line_item_type'] == 'Tax']['line_item_unblended_cost'])
3.7199999999999998

>>> dev_df2['line_item_line_item_type'].unique()
array(['PrivateRateDiscount'], dtype=object)
>>> sum(dev_df2.loc[dev_df2['line_item_line_item_type'] == 'PrivateRateDiscount']['line_item_unblended_cost'])
-660.147687862

>>> dev_df3['line_item_line_item_type'].unique()
array(['EdpDiscount'], dtype=object)
>>> sum(dev_df3.loc[dev_df3['line_item_line_item_type'] == 'EdpDiscount']['line_item_unblended_cost'])
-408.58678773768946

**Comment by Sean-Holcomb** [comment]
That is perfect, I opened this PR to address the issue
https://github.com/kubecost/kubecost-cost-model/pull/1251

**Comment by kc-adawson** [comment]
@Sean-Holcomb @AjayTripathy @linhlam-kc 

Testing on 1.101.0-RC.3

Looking back at historical cloud cost data after the update, we see the same incorrect daily costs for Feb 2nd. It looks like historical data was not updated.

Looking at the cost for 8th of March, after the new update.

Kubecost Cloud costs page - $169.37
Amortized Cost - $169.37 where EDP is $17.61 and Private rate card is $11.25.
Net Amortized cost - $160.06

Kubecost cost matches the amortized cost but does not match the net amortized cost. Is there any reason why that might be happening?

**Comment by AjayTripathy** [comment]
Hey @kc-adawson can you clarify where you're doing the cost matching? Is it on the /cloud page? can you share a screenshot?

**Comment by kc-adawson** [comment]
@AjayTripathy:

![Screenshot 2023-03-09 at 6 46 48 PM](https://user-images.githubusercontent.com/101200254/224121570-db051d5a-176e-43ab-ae3b-2c7e6c750796.png)
![Screenshot 2023-03-09 at 6 45 13 PM](https://user-images.githubusercontent.com/101200254/224121573-5914bc38-b3f1-4b1a-a84e-88f560c72b2c.png)

**Comment by AjayTripathy** [comment]
@Sean-Holcomb any chance you could take a look here?

**Comment by AjayTripathy** [comment]
@kc-adawson this is resolved w/ new build right? Can we close the loop here if so?

**Comment by kc-adawson** [comment]
Solved in new build, closing this out. Thank you @Sean-Holcomb !!
