### ISSUE TITLE
Health overviews do not consistently show namespaces

### ISSUE THREAD

**Issue by bbrala** [kubecost/cost-analyzer-helm-chart#1997]
Source: https://kubecost.slack.com/archives/CLFV60Y90/p1677145791772029

**Describe the bug**  

**To Reproduce**  
In the health overviews sometimes namespaces are mentioned in the list, but sometimes they arn't. This makes the lists kinda hard to   read.

For example this is hard to read:
![image](https://user-images.githubusercontent.com/3294970/221145059-ab5f8902-631d-4f1e-9cdf-24062e918488.png)

But this is pretty great:
![image](https://user-images.githubusercontent.com/3294970/221145110-adf8a47c-30fd-466a-aec9-2d9a5afd01ab.png)

**Expected behavior**  
Always show namespaces in all health checks.

**Screenshots**  
see above

**Collect logs (please complete the following information):**
Not applicable i think

**Comment by thomasvn** [comment]
Thanks for pointing this out @bbrala! I think this would be a good enhancement.

@teevans v1.101 or v1.102 proposal?

**Comment by teevans** [comment]
@thomasvn - I'll defer to @kwombach12 on prioritization here. It's a bit intensive to make changes to this page, and it may not make future releases.

**Comment by kwombach12** [comment]
I'll add as a proposal to v1.102. Dont think we have capacity to have this land for 1.101

**Comment by bbrala** [comment]
Aww. Is this something that I can contribute to or is this the closed part?

**Comment by teevans** [comment]
Hey @bbrala - Unfortunately this is our closed source portion. Otherwise I would certainly love the contribution!
