### ISSUE TITLE
Network Cost image - Change to semantic versioning

### ISSUE THREAD

**Issue by dr460neye** [kubecost/cost-analyzer-helm-chart#2001]
**What problem are you trying to solve?**
Tools like Dependabot or renovate ensure that software is up to date. To manage versions, semantic versioning is always a good option. Currently your network-cost image does not have semantic versioning in place.

**Describe the solution you'd like**
I would like that network-cost image changes from pattern vMAJOR.MINOR to MAJOR.MINOR.PATCH in the naming

**Describe alternatives you've considered**
None, currrently i need to manually patch all images

**How would users interact with this feature?**
Renovate can now scan and inform for this image way easier in a standartized way

**Comment by mbolt35** [comment]
@dr460neye Whole-heartedly agree here. This was a mistake where the initial versions were missing the leading major `0.` and there has since been a fear of overlapping image versions if/when we change this to semantic versioning. Any suggestions on how to best roll this out without creating future conflict with already deployed versions of the software?

**Comment by dr460neye** [comment]
hey @mbolt35 , i see two options, either stick to the current version as major ( 16.4.0) and change the way how you fix the things, or switch the image name. So next patch is 16.4.1 e.g.

In any way, i do not see any need to force-matching versions of images for the full deployment. In some cases there are even downsides.
What do you think?

**Comment by mbolt35** [comment]
> hey @mbolt35 , i see two options, either stick to the current version as major ( 16.4.0) and change the way how you fix the things, or switch the image name. So next patch is 16.4.1 e.g.
> 
> 
> 
> In any way, i do not see any need to force-matching versions of images for the full deployment. In some cases there are even downsides.
> 
> What do you think?
> 
> 
> 
> 

I actually checked historical versioning in our image repo, and there are exactly 0 instances of major.minor.build, so we're actually free to start the versioning correctly from here on out without risking conflict!
