### ISSUE TITLE
Multi Aggregation on the Alerts page

### ISSUE THREAD

**Issue by saiben10** [kubecost/cost-analyzer-helm-chart#2002]
I am getting alert report for the namespace cost allocation.
In that report i want to get the owner of that particular namespace also .
How can we get this which lavel should we use
![Uploading IMG_20230227_172923.jpg…]()

**Comment by thomasvn** [comment]
@saiben10 Would it help here to create your report using a Multi Aggregation? You can aggregate by "Namespace" then "Owner"

**Comment by saiben10** [comment]
Yes you got my point right in that report what I am getting i need the owner of that namespace also
Can you tell how to get that

**Comment by thomasvn** [comment]
@saiben10 When creating an Allocation Report, set "Multi Aggregation" to "Namespace" then "Owner". When you do so, it should look like this:

<img width="1000" alt="Allocation Report by Namespace and Owner" src="https://user-images.githubusercontent.com/11251627/221623381-e894eb88-d929-4ed5-a111-3fa1fe1c1823.png">

Above, we see that the "kubecost" namespace has the Owner "solutions@kubecost.com". The "acme-fitness" and "ingress-nginx" namespaces do not have owners and therefore show "unallocated".

**Comment by saiben10** [comment]
How can we get that as a alert report

**Comment by saiben10** [comment]
Did you got my doubt right

**Comment by saiben10** [comment]
Generally we will get report as a alert in mail in that report i need the owner of that each namespace

**Comment by saiben10** [comment]
Hy @thomasvn can you please look into it

**Comment by thomasvn** [comment]
@saiben10 Yes thanks for clarifying! I think I understand now.

Multi Aggregation is currently supported for the Reports page, but not the Alerts page. Example of the Alerts page below:

![Alerts Multi Aggregation](https://user-images.githubusercontent.com/11251627/221697629-aea73d9b-11ef-4594-8e5c-17ecfe08659e.png)

I'm going to adjust this issue to make it a feature request to add Multi Aggregation for the Alerts page.

@kwombach12 @Adam-Stack-PM v1.101 or v1.102 proposal?

**Comment by kwombach12** [comment]
Thanks @thomasvn the earliest we can pick this up is 1.102

**Comment by saiben10** [comment]
You are saying currently we don't have multi aggregation in alerts right

**Comment by thomasvn** [comment]
@saiben10 Correct

**Comment by saiben10** [comment]
In the report section can you tell how to get that i mean the owner of
namespace

**Comment by saiben10** [comment]
Can you share something like screenshot

**Comment by saiben10** [comment]
Can you please share me @thomasvn

**Comment by saiben10** [comment]
> @saiben10 When creating an Allocation Report, set "Multi Aggregation" to "Namespace" then "Owner". When you do so, it should look like this:
> 
> <img alt="Allocation Report by Namespace and Owner" width="1000" src="https://user-images.githubusercontent.com/11251627/221623381-e894eb88-d929-4ed5-a111-3fa1fe1c1823.png">
> 
> Above, we see that the "kubecost" namespace has the Owner "[solutions@kubecost.com](mailto:solutions@kubecost.com)". The "acme-fitness" and "ingress-nginx" namespaces do not have owners and therefore show "unallocated".

How did you get this 
Can you show inside filter

**Comment by thomasvn** [comment]
@saiben10 On Kubecost v1.100.2. Go to _Reports_ -> _Create a Report_ -> _Allocation Report_. Then select the following:

<img width="1582" alt="Multi Aggregation Annotated" src="https://user-images.githubusercontent.com/11251627/221935067-dee8b0c9-d1b7-446e-8c91-7c4f119364df.png">

**Comment by saiben10** [comment]
I am getting can I get this as a alert report

**Comment by rossfisherkc** [comment]
Howdy @saiben10 !

Note that alerting is a Business feature and while it's currently not locked down during the beta period, there will come a time where this feature will no longer be available, even unofficially. It seems we also have a handful of cases open with you about this specific topic across multiple channels. I'll reply back in the original case, but if you can keep in mind to only open and follow up on one case, it would greatly help our response time and ability to help out

**Comment by rossfisherkc** [comment]
Closed in favor of duplicate ZD case #3536

**Comment by thomasvn** [comment]
Thanks for helping to organize this @rossfisherkc! I'm going to re-open this Github Issue just so we can track the feature request to add Multi Aggregation to Alerts.

**Comment by saiben10** [comment]
Okay in business version do we get multi aggregation alerts then

**Comment by thomasvn** [comment]
Yes! Business License includes all features associated with [Reports and Alerts](https://docs.kubecost.com/install-and-configure/install#kubecost-features).

**Comment by rossfisherkc** [comment]
We should update this issue or close it out so it doesn't stagnate. I'm in favor of migrating it to a new issue with a more focused feature request for easier digestibility cc @thomasvn

**Comment by thomasvn** [comment]
@rossfisherkc Done!

**Comment by saiben10** [comment]
Hello

I have configured the alerts for kubecost for the group but I am not
receiving the alerts for the group.
Can you please tell how can I get alerts for the group mail.
Because I am getting same for individual mail.
