### ISSUE TITLE
AWS Reserved instances

### ISSUE THREAD

**Issue by dr460neye** [kubecost/cost-analyzer-helm-chart#2004]
**What problem are you trying to solve?**
When i preordered reserved instances, payments are provided in the past to cover these cost.
Afaiu, currently these cost are counted as 0, for in reality, these cost are distributed over the usage time.

**Describe the solution you'd like**
I would like to be able to note down my investments i did in the past, or let kubecost detect them automatically, so they get shared on the real instance costs.

**Describe alternatives you've considered**
Either let kubecost idenitfy it, or let the customer map these cost manually

**How would users interact with this feature?**
There could be a ui option, which shows the "prepaid" reserved instances, and get asked how to map them.

**Comment by AjayTripathy** [comment]
Hey @dr460neye the default is for this to be amortized, ie, these costs should be distributed over the lifetime of the node. Have you integrated your AWS cost and usage report with Kubecost yet?

**Comment by dr460neye** [comment]
AWS cost and usage report is enabled. But the instances got reserved a real long time ago. Not sure if this impact the report, or there is any other reason why the last 48h are always piling up cost.
For me this indicates that either one of the following applies:

- reserved instances not well transferred ( could be the case, but as no "raw vs discounted cost are shown its hard to identify )
- negotiated discount not fully correct ( could be the case, but as no "raw vs discounted cost are shown its hard to identify )
- ETL process has a high gap in time ( this i can exclude, as ETL runs each 3 h and the aws export every 2 )

For this reason i would suggest that the discount shows up in the "empty" credit section, which is normally used for AWS credits afaiu. So you always have the chance to see the "discounted" price vs. the normal one

**Comment by AjayTripathy** [comment]
@dr460neye we only fetch the AWS data on 48h intervals, since there can be up to a 48 delay in receiving data from AWS.
