### ISSUE TITLE
Link to Slack and GitHub are flip flopped in the Settings page in the UI

### ISSUE THREAD

**Issue by msdolbey** [kubecost/cost-analyzer-helm-chart#2006]
Thanks for your interest in Kubecost!  To ensure you get the help you need, please follow these guidelines:

- If you have questions about product functionality/usage or need assistance with product installation/configuration, please email support@kubecost.com, where our support engineering team will be happy to help!
- If you have a reproducible bug or a feature request, you're in the right place.  Please include the information requested below.

---
# For reproducible bugs, please provide the following

**Describe the bug**  
When you're in the Settings page of the UI
In the General area
At the top - there is this bit:

```
The new UI for Kubecost is now the default option. If you prefer our classic look, you can switch back using the toggle switch above. If you have any concerns or feedback about the new UI, don't hesitate to reach out to us on [Slack](https://github.com/kubecost/cost-analyzer-helm-chart/issues/new/choose) or [GitHub.](https://join.slack.com/t/kubecost/shared_invite/zt-1dz4a0bb4-InvSsHr9SQsT_D5PBle2rw)
```

The link for `Slack` is to the GitHub issues page, and the link to `GitHub` is to the slack.

**To Reproduce**  
1. Go to the Settings page in the UI
2. See error in the Slack and GitHub links.

**Expected behavior**  
The Slack link should go to https://join.slack.com/t/kubecost/shared_invite/zt-1dz4a0bb4-InvSsHr9SQsT_D5PBle2rw
The GitHub link should go to https://github.com/kubecost/cost-analyzer-helm-chart/issues/new/choose

**Screenshots**  
![Screen Shot 2023-02-28 at 2 17 53 PM](https://user-images.githubusercontent.com/5703649/221969604-080bb097-653e-44a8-a382-55548c26e331.png)

**Collect logs (please complete the following information):**
N/A - Just a UI link

**Comment by AjayTripathy** [comment]
Seems pretty straightforward @nealormsbee ?
