### ISSUE TITLE
directly link from allocations to request-sizing with filters

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#2008]
Just an idea here, perhaps there is a better idea already?

**What problem are you trying to solve?**
The allocation page does a great job finding large and inefficient aggregations. It is not intuitive to drill into `request-sizing` from here. Currently you need to click the detail page and find the request sizing link. 

**Describe the solution you'd like**
Having a method to directly go from the main allocation page to request-sizing would be much simpler than the current link from the detail page. Potential suggestion is to link from the efficiency %.

**Describe alternatives you've considered**
It is possible to  navigate via detail page, but very few find this.

**How would users interact with this feature?**
maybe: 

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/31039225/222034041-92a76974-9f30-4cb8-9640-af6812b19617.png">

**Comment by AjayTripathy** [comment]
This seems like a really good idea to me!

**Comment by jessegoodier** [comment]
added in 1.102
