### ISSUE TITLE
Either allow config via file or via ui

### ISSUE THREAD

**Issue by dr460neye** [kubecost/cost-analyzer-helm-chart#2009]
**What problem are you trying to solve?**
Currently you can configure everything  by either the UI or the helm chart.
This raises problems, as people can hijack the settings by overwriting it. Grafana e.g. offers a feature which disables ui configuration, when the file is provisioned via configmaps or other filesystem settings.

**Describe the solution you'd like**
If a configuration is provided via configmaps, disable the possibility to store settings in the UI.

**Describe alternatives you've considered**
Make transparent that you have manually overwritten a "configmap" values if the architecture does not allow different.

**How would users interact with this feature?**

When the setting appeared by the configmap, a config option for the UI should be greyed out and the api should raise failures.

**Comment by thomasvn** [comment]
@dr460neye I like the idea of a Helm config to disable config changes via the UI!

There is some degree of this functionality in [Kubecost's RBAC](https://docs.kubecost.com/install-and-configure/advanced-configuration/user-management). With RBAC, users in the `readonly` or `editor` groups cannot make any changes on the UI Settings page. Does this satisfy your use case?

**Comment by dr460neye** [comment]
As this is an enterprise only feature, and also lacking in the business subscription, i do not see this fitting the case.
In general i would more see a way of detecting if a config file is provided via the ui or via a mount as part of the cost-analyzer application itself.
The case is more simple, either you do infrastructure as code, or manual setup.
At the moment you can have a mixed way in your setup.

This should be a role independant feature and be more driven in relation to the iac vs manual configuration approach.

**Comment by thomasvn** [comment]
@kwombach12 @kaelanspatel Thoughts on a Helm config which would make the Settings page in the UI `readonly`?

**Comment by kwombach12** [comment]
This makes sense to me. I can add as a proposal for future releases

**Comment by AjayTripathy** [comment]
You can already use the readonly:true flag in the helm chart to do this. https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L854
