### ISSUE TITLE
Athena support for custom filters

### ISSUE THREAD

**Issue by dr460neye** [kubecost/cost-analyzer-helm-chart#2011]
**What problem are you trying to solve?**
One AWS account can have multiple independant kubernetes clusters. At the moment there are 2 problems due to a missing feature to filter for custom columns.

1. If you have a master payer account, you have the cost data of all environments
2. If you have multiple clean labeled clusters and aws ressources,  the suggestions are wrong, as infrastructure from cluster 2 is also taken into account.

**Describe the solution you'd like**
Add a filter for aws accountid to only get data imported you really need
Add a filter for remoned lines with custom labels e.g. environment and a set of supported values like: column=environment key!=playground if you only want to see you development eks

**Describe alternatives you've considered**
CUR of AWS does not support any kind of filtering or i could not find a way to do so

**How would users interact with this feature?**

Add a configuration file with the aws key which should be filtered
Add a configuration file with the columns you do not want to get imported into TTL by column based values. Also support "not set"

**Comment by thomasvn** [comment]
@dr460neye Thanks for the suggestion! This has been something I've been thinking about as well.

@kwombach12 @Sean-Holcomb Thoughts on the ability to filter on the CUR, so Kubecost is only reconciling against a subset of the CUR? Probably also need to think about the equivalent functionality for Azure & GCP.

**Comment by kwombach12** [comment]
Yea this makes sense to me. Would want to have this available for all 3 cloud providers before rolling it out

**Comment by Sean-Holcomb** [comment]
We can currently support Athena views, which can provide the filtering being discussed here. https://docs.aws.amazon.com/athena/latest/ug/create-view.html

In terms of parity there is a request for view support for BQ that is out right now https://github.com/kubecost/cost-analyzer-helm-chart/issues/1841#issuecomment-1424009511
Azure, and Alibaba I don't think will be able to support anything like this with the integrations that we are currently using.

In terms of ingestion filters on our side, this is certainly possible, but I would want the filter update to land first, In addition to Cloud Cost configuration and diagnostics fully fleshed out.

**Comment by stevesowerbutts** [comment]
I am also having the same issue described in problem 1. I have a master payer account and I would like to be able to filter the cost data by AWS account ID. This would be very helpful for me to track the costs of my individual environments.

Could you please let me know if there have been any updates with regards to this?
thanks

**Comment by kwombach12** [comment]
@stevesowerbutts our cloud costs page has a filter for account ID! Does that work for you use case?

**Comment by chipzoller** [comment]
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.
