### ISSUE TITLE
Add support for kubecost labels to kubecost deployments

### ISSUE THREAD

**Issue by dr460neye** [kubecost/cost-analyzer-helm-chart#2012]
**What problem are you trying to solve?**
Kind of funny, but kubecost is missing a simple predefinition of labels to add over adding pod labels everywhere ;) 

**Describe the solution you'd like**
Add a section to helper template with predefined labels, so teams do not have to come up with their own ones, and if they do, offer do place them everywhere with one setting.

**Describe alternatives you've considered**
Manual placement and reinventing the whole idea you heavily developed in the past with the kuebcost concept

**How would users interact with this feature?**
You either just write:
team_name: myteam

or add
team:
   key: kubecost.app/team
   value: myteam

**Comment by thomasvn** [comment]
Could you clarify the question @dr460neye ?

I believe Kubecost does apply labels to the [`cost-analyzer-deployment-template.yaml`](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.100/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L8-L9) using defaults from [`helpers.tpl`](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.100/cost-analyzer/templates/_helpers.tpl#L117-L126). Let me know if I'm misunderstanding!

**Comment by dr460neye** [comment]
You are missunderstanding :) I  speak about cost assignment labels.
Kubecost uses cost-assignment labels to assign cost to any service.
But there are no defaults predefined for kubecost stack itself.

**Comment by AjayTripathy** [comment]
http://demo.kubecost.io/allocations?agg=product

Hmm, we think of kubecost as a product and this should aggregate the costs to the kubecost "product" by default... is there more you'd like to see?
