### ISSUE TITLE
Advanced Reports: Add label to Cloud Breakdown aggregation type

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2023]
**What problem are you trying to solve?**
I would like to understand better what this value refers to under the "Cloud Breakdown" section of the Advanced Reports. 

![image](https://user-images.githubusercontent.com/43491549/222564077-89cffa6d-4df3-41a1-a782-38593cd703b8.png)

**Describe the solution you'd like**
Add some label to make it easier for users to understand that this is the current aggregation type selected

<img width="626" alt="image" src="https://user-images.githubusercontent.com/43491549/222564596-c792a24f-886b-4804-a492-4bd1e73d3f7f.png">

**Comment by dwbrown2** [comment]
cc @kwombach12

**Comment by kwombach12** [comment]
@keithhand totally agree this is confusing... I am actively working on revamping the advanced reports UX because I had that same confusion myself.
