### ISSUE TITLE
Improve network costs in Azure

### ISSUE THREAD

**Issue by ivankube** [kubecost/cost-analyzer-helm-chart#2024]
**Describe the bug** 
This issue was reported by a customer via [ZD #3314](https://kubecost.zendesk.com/agent/tickets/3314).

Network costs seem to be inaccurate when Kubecost is deployed in Azure. Egress traffic to Azure Services(e.g. Azure Storage) is recognized as Internet Egress in Kubecost and as a result network cost in Kubecost is much higher than Azure Cost Analysis shows.  

I believe we need to either include the most popular Azure Services subnets to the in-zone section of netwrokCost config or ideally fix reconciliation.

**To Reproduce**  
1. Deploy Kubecost on Azure, enable Azure cloud integration or use existing deployment: `az aks get-credentials --resource-group khandkcost --name khand-dev-1`
2. Compare Total Network Cost in Kubecost and Azure Cost Analysis
3. Observe the high discrepancy

**Expected behavior**  
Network cost in Kubecost and in Azure Cost Analysis is the same number.

**Screenshots**  
![Screenshot 2023-03-02 at 5 38 23 PM](https://user-images.githubusercontent.com/97049075/222576147-69f21eac-9918-48e8-92e9-60c18eb15483.png)
![Screenshot 2023-03-02 at 5 39 16 PM](https://user-images.githubusercontent.com/97049075/222576150-acc10f03-8448-47bc-854c-a781ba8d3d2e.png)
![Screenshot 2023-03-02 at 5 39 39 PM](https://user-images.githubusercontent.com/97049075/222576151-d4500677-0853-4bec-8b8c-075d77d2cd6f.png)
![Screenshot 2023-03-02 at 5 40 00 PM](https://user-images.githubusercontent.com/97049075/222576155-512a2151-5fce-46d3-b23c-9634a56c7f40.png)
![Screenshot 2023-03-02 at 11 00 12 AM](https://user-images.githubusercontent.com/97049075/222576156-0f4c8856-876a-4ad0-8dcb-8f18404aa86d.png)

**Comment by mbolt35** [comment]
Looks like reconciliation isn't working, and it's relying solely on default configuration network-costs pods.

**Comment by AjayTripathy** [comment]
Are there adjustments available on the Assets page?

**Comment by ivankube** [comment]
Adjustments are 0s on the Assets Page in my cluster. 
Total Assets cost is about the same as Azure reports:

![Screenshot 2023-03-02 at 6 38 16 PM](https://user-images.githubusercontent.com/97049075/222589629-b6d300f7-5cc8-4875-a882-e430e058c71f.png)


![Screenshot 2023-03-02 at 6 36 37 PM](https://user-images.githubusercontent.com/97049075/222589658-21aeed82-c084-436b-996e-38c86fd7071a.png)

Few more points:
1. Before I enabled closed integration, network cost in Kubecost was even higher:
![Screenshot 2023-03-01 at 4 52 23 PM](https://user-images.githubusercontent.com/97049075/222590477-b6b4a09c-4aee-4781-8d34-de3b6226d050.png)

2. Customer has adjustments in their Assets page but still network costs discrepancy is very high.

**Comment by AjayTripathy** [comment]
@Sean-Holcomb if Assets is showing a reasonable network cost and allocations is not, this seems like a bug in reconciliation. Can you take a look?

@ivankube can you post a public service address link to your cluster where you're seeing this repro? I would also expect to see adjustments in your cluster.

**Comment by AjayTripathy** [comment]
Also, fyi reconciliation does not work on days less than 48h old. @ivankube on customer data can we just look at one day greater than 48h in the past vs one day on the azure billing console?

**Comment by ivankube** [comment]
@AjayTripathy try http://ivan.kubecost.xyz or port forward `az aks get-credentials --resource-group khandkcost --name khand-dev-1`

Screenshots of Allocations and Azure cost analysis for the past month are posted in the [support ticket 3314](https://kubecost.zendesk.com/agent/tickets/3314). 

I'll ask them to send us Allocation, Assets and Azure screenshots for one day > 48h

**Comment by AjayTripathy** [comment]
Thanks Ivan. I'll make sure we look into this.

**Comment by AjayTripathy** [comment]
Let's get this tracked and assigned for fix-it week @Adam-Stack-PM -- I will work with another engineer when we get there.

**Comment by Adam-Stack-PM** [comment]
@AjayTripathy Sounds good.

**Comment by Sean-Holcomb** [comment]
Just opened a PR to fix this https://github.com/kubecost/kubecost-cost-model/pull/1327
