### ISSUE TITLE
Make kubecost-network-costs tags semver compatible

### ISSUE THREAD

**Issue by thomaschaaf** [kubecost/cost-analyzer-helm-chart#2026]
**What problem are you trying to solve?**
We are using https://github.com/xelalexv/dregsy to copy the images to our local docker registry. All your images use semver version names except kubecost-network-costs which is sadly not compatible with that tool. It would be great if you could use semver versioning.

**Describe the solution you'd like**
Please rename the version so that it is v16.3.0 instead of v16.3.

**Comment by AjayTripathy** [comment]
@mbolt35 we had some discussion about this... any objections to migrating network costs to semver?

**Comment by mbolt35** [comment]
@AjayTripathy I just have the minor concern of version overlap. This fiasco is my fault, the original Makefile had a regular semver and somehow I managed to truncate the leading `0.` during deployment, then stuck with it. 

So really, we should be on `0.16.X`
Also, I just looked in our image repo: When I look at the images we've cut in the past, none of them are semver, so it seems reasonable that we could start with `0.16.X` without hitting any overlap at all. 

It may be a bit confusing having some of the older images, but it would just put us on a better path going forward. Thoughts?

**Comment by AjayTripathy** [comment]
I think we can handle the confusion. Go ahead and start with 0.16.X IMO.

**Comment by mbolt35** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/pull/2032

**Comment by thomaschaaf** [comment]
Wow! Awesome thanks for tackling this!
