### ISSUE TITLE
Shared Tenancy Costs - Missing from Advanced Reporting + Typo in Settings

### ISSUE THREAD

**Issue by kc-adawson** [kubecost/cost-analyzer-helm-chart#2029]
**Describe the bug**  

There is a bug where the Shared Tenancy costs are not making it into Advanced Reporting when they are present in Allocation reports.

<img width="1227" alt="2023-03-06_07-23-08" src="https://user-images.githubusercontent.com/101200254/223109460-2dc07418-be32-4b37-95e9-5c59e09e44eb.png">

<img width="1221" alt="2023-03-06_07-28-46" src="https://user-images.githubusercontent.com/101200254/223110636-cfbdb26a-3d8c-46bb-b3a2-0c02da480236.png">

<img width="1411" alt="2023-03-06_06-52-09" src="https://user-images.githubusercontent.com/101200254/223109496-660d7f44-be5b-4538-9f12-4eba13bb8162.png">

In the settings, there is a typo in the word Tenancy:

<img width="657" alt="2023-03-06_07-22-09" src="https://user-images.githubusercontent.com/101200254/223109211-4bac00a2-1d4b-4318-979b-0a9aaed638d5.png">

**What problem are you trying to solve?**  
Create a consistent experience across all reporting modules.

**Describe the solution you'd like**  
Apply the same shared settings across all reports where applicable.

**Describe alternatives you've considered**  
None

**How would users interact with this feature?**
All reporting users.

**Comment by kwombach12** [comment]
@nealormsbee can you take a look at the lift for this one?

**Comment by kwombach12** [comment]
we should at least fix the typo

**Comment by AjayTripathy** [comment]
I think shared costs should be added to advanced reports... high priority if it can't make 101

**Comment by nealormsbee** [comment]
The linked PR will leverage the global "Share Tenancy Costs" setting in advanced reports. I imagine we'll also want a UI to override that value on a per-report basis...does that effect prioritization?
