### ISSUE TITLE
Helm Values Reporting Enhancement

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#2034]
**What problem are you trying to solve?**
Identify how Kubecost was configured based on passed helm values. Today we only report on values in sections that are `enabled`. A good example of the gap this creates is identifying a Prometheus FQDN when our bundled one is disabled. Because `global.prometheus.enabled` is set to `false`, helm values reporting does not capture the value of `global.prometheus.fqdn`.

https://github.com/kubecost/cost-analyzer-helm-chart/blob/8207a31e9d88a3739c3575ce6047bb5967e75c06/cost-analyzer/templates/_helpers.tpl#L183-L221

**Describe the solution you'd like**
Includes disabled branches as well as they may contain important configuration information that can be used for troubleshooting.

**Describe alternatives you've considered**
Having the end user run `helm get values kubecost` in their terminal with the proper kubenetes context.

**How would users interact with this feature?**
`/model/helmValues` endpoint as well as bug report.

**Comment by jessegoodier** [comment]
Biggest impact here is support and solutions. I spent an hour troubleshooting why the fqdn wasn't working, when in fact it was.

**Comment by dwbrown2** [comment]
@mbolt35 is this is helm limitation? i believe you were the one that originally started capturing these...

@teevans @nealormsbee @kwombach12 this also feels like a solid addition to diagnostics... wdyt?

**Comment by teevans** [comment]
Fully support. Bolt and I talked about this earlier actually.

**Comment by nealormsbee** [comment]
Makes a ton of sense to me.

**Comment by mbolt35** [comment]
We really may want to hold off. @dwbrown2 dug a deep rooted memory of a problem related to "all helm values." It may be worth it to take a glance at the git history to see if there are any hints as to why we went this route.

Originally, we were encoding the entire .Values and we had a few customers fail to upgrade/install. I don't remember the specific reasons for the failure (possibly a limitation of env var length?), but let's tread carefully here - certainly possible that it's a non issue now, but did want to specifically note that this broke users last time we tried.

**Comment by dwbrown2** [comment]
@mbolt35 If I remember correctly, I think this can 10x+  the size of this payload. That sound right?

**Comment by mbolt35** [comment]
> @mbolt35 If I remember correctly, I think this can 10x+  the size of this payload. That sound right? 

Yeah, it became massive (it already is).  Maybe we should write this to disk/configmap so we can avoid the attempt to cram this into a single env var?

I'm open to any approach here other than env var.
