### ISSUE TITLE
Add support for disabling HTTP2

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2036]
**What problem are you trying to solve?**
Some [users](https://github.com/kubecost/cost-analyzer-helm-chart/issues/1923) have run into installation issues when backed using Envoy proxy. This [seems like](https://github.com/envoyproxy/envoy/issues/6767) it is related to HTTP2 requests and there are some suggestions that users using Istio (built using Envoy) were able to bypass the issue by not using HTTP2 connections.

**Describe the solution you'd like**
A way for users to easily disable HTTP2 requests from the container.

**Describe alternatives you've considered**
Manually modify the Nginx configmap

**How would users interact with this feature?**
`.Values.kubecostFrontend.http2.enabled: false`

**Comment by AjayTripathy** [comment]
@jessegoodier as the networking/proxy expert, do you think this would be helpful? I'll admit this is a little beyond me.

**Comment by jessegoodier** [comment]
Do we even support http2?
NGINX may need TLS to support http2. Have they done that?


`curl --http2 -v http://nightly.kubecost.io:9090/`
```
*   Trying 34.69.101.254:9090...
* TCP_NODELAY set
* Connected to nightly.kubecost.io (34.69.101.254) port 9090 (#0)
> GET / HTTP/1.1
```
