### ISSUE TITLE
Proposing a new parameter `hourlyETL` to the Allocation API

### ISSUE THREAD

**Issue by thomasvn** [kubecost/cost-analyzer-helm-chart#2041]
## What problem are you trying to solve?
I want to be able to make requests to the Allocation API and be returned data from the Hourly ETLStore. Specifically, for an old date such as 1 month ago (`window=2023-02-14T00:00:00Z,2023-02-14T01:00:00Z`)

Currently, to do so would require I set `etlHourlyStoreDuration=720` to cover the last month, so that I can successfully run `curl -L 'http://localhost:9090/model/allocation?window=2023-02-14T00:00:00Z,2023-02-14T01:00:00Z'`

However, because the Allocation API always operates upon the most granular data possible, a configuration of `etlHourlyStoreDuration=720` is problematic when the frontend makes queries for Allocation ETL data over the last 7 days. It often results in OOM Kills to the kubecost-cost-analyzer-pod.

## Describe the solution you'd like
I would like for an additional parameter to the Allocation API `?hourlyETL=true`, which specifically requests a query to the hourly ETLStore regardless of what the `etlHourlyStoreDurationDays` configuration is.

By default, we can set `hourlyETL=false` when handling API requests. And the existing functionality with regards to `etlDailyStoreDurationDays` and `etlHourlyStoreDurationDays` would remain the same.

## Describe alternatives you've considered
An alternative is to increase `etlHourlyStoreDurationDays` to the desired amount, and refrain from using frontend views which would query for too many days worth of data.

## How would users interact with this feature?
A parameter in the Allocation API

**Comment by AjayTripathy** [comment]
Hey @thomasvn have you seen the /compute API as a temporary workaround? It supports changing granularities, though it will force a recompute of data. It's also likely to go away in federated.

@kaelanspatel , is hourly data federated? Would it be possible to only pull this data when requested going forward? https://docs.kubecost.com/apis/apis-overview/allocation#querying-on-demand-experimental

**Comment by thomasvn** [comment]
Agree that [`/model/allocation/compute`](https://docs.kubecost.com/apis/apis-overview/allocation#querying-on-demand-experimental) is a good workaround! Although using this endpoint is currently resource intensive when there exists a large amount of metrics.

**Comment by kaelanspatel** [comment]
>  is hourly data federated? Would it be possible to only pull this data when requested going forward?

Yes, hourly data is federated. It should be possible to query it as long as the data exists in the combined directory.

**Comment by AjayTripathy** [comment]
@kwombach12 proposing this as something to pick up when we return to federated support in 103

**Comment by kwombach12** [comment]
Ill add it to the list!
