### ISSUE TITLE
Add a check for an Athena bad state edge case to diagnostics on AWS

### ISSUE THREAD

**Issue by rossfisherkc** [kubecost/cost-analyzer-helm-chart#2047]
**What problem are you trying to solve?**
Supporting customer on ZD 3593. We spent quite a bit of time trying to figure out why their AWS cluster just up and disappeared from the UI. Repair requests failed with `CloudUsageSet is empty for (date) and did not update. ` We checked the S3 bucket, all seemed there and modification dates matched the last several days of missing data. Athena queries also looked fine and no errors. Diagnostics also looked fine.

Eventually, the customer discovered that the Athena partition needed to be repaired by trying to Preview Table on the kubecost_costs and Athena automagically running/suggesting a repair command:
![image](https://user-images.githubusercontent.com/113053906/224455716-5806b22f-e5bf-4406-8917-2f72992361e6.png)
![image](https://user-images.githubusercontent.com/113053906/224455723-70d0afd7-f157-45fa-9287-5a9ce886b21d.png)

**Describe the solution you'd like**
At the least, something in the diagnostics page that reports a bad state in Athena. Customer's AWS cluster just disappeared since 3/1/23 and they have been without data until Athena was repaired on 3/9/23.

While Athena is managed by AWS and the specific issue may be out of our direct scope, there's a pretty big negative experience with KubeCost if customer data just goes missing with no apparent, or easily discoverable cause.

At the most, some sort of auto-repair or repair button next to the Athena health failure in the diagnostics page would be nice. I'm not sure if our permissions we require for integration would cover that already, may not be worth it if we have to include a discrete setup step as this is the first time I've heard about the specific issue and could not find any other occurrences.

**Describe alternatives you've considered**
Customers should be able to setup a scheduled job in AWS Glue to autorun the Athena repair, but that incurs additional cost and performance impacts are unknown by dumbly spamming a repair command, it's also a messy user experience.

**How would users interact with this feature?**
As above

**Comment by AjayTripathy** [comment]
Thanks for filing this. Can we get this documented somewhere while we figure out a long term fix to automate? We already wrote an endpoint here that can do this: https://github.com/kubecost/kubecost-cost-model/blob/52f341877911c5230cc095d8878f7640b05ebf83/pkg/provider/awscurfetcher.go#L961

cc @Sean-Holcomb
