### ISSUE TITLE
chart not updated

### ISSUE THREAD

**Issue by llamahunter** [kubecost/cost-analyzer-helm-chart#2051]
the latest chart published is 1.00.2, but getting 'out of date' errors in the UI because latest version of software is 1.101.2

**Comment by teevans** [comment]
@llamahunter - Could you show us a screenshot of the top of your settings page that shows the version numbers of Kubecost?

**Comment by llamahunter** [comment]
![image](https://user-images.githubusercontent.com/843173/225451053-9f6484fb-6d81-415c-8ebf-eefb870d7700.png)

**Comment by llamahunter** [comment]
Hmm... I was looking at the checked in version of your helm chart, not the ones retrievable via the index.yaml.  Maybe you have published newer versions w/o checking in an update to your chart source code?

**Comment by llamahunter** [comment]
OK, I see, you don't update your charts in your default branch, only in release branches? And only sporadically update the default branch to match? A bit confusing.

**Comment by Adam-Stack-PM** [comment]
@kwombach12 Adding the install/upgrade label to  keep track of this issue incase we review the experience in the future.
