### ISSUE TITLE
Add Indonesian Rupiah (IDR) to Available Currencies in Settings

### ISSUE THREAD

**Issue by kc-adawson** [kubecost/cost-analyzer-helm-chart#2053]
Please add Indonesian Rupiah - IDR to the Currency menu in Kubecost Settings.

**Comment by dwbrown2** [comment]
+1, should be really quick

cc @nealormsbee in case you have reference PRs

**Comment by nealormsbee** [comment]
PR open here! https://github.com/kubecost/cost-analyzer-frontend/pull/1823
