### ISSUE TITLE
Abandoned Cluster

### ISSUE THREAD

**Issue by grinbvi** [kubecost/cost-analyzer-helm-chart#2054]
**What problem are you trying to solve?**
Cluster that have not sent or received a meaningful rate of traffic over a given duration may represent abandoned cluster

**Describe the solution you'd like**
After ensuring that a cluster  is abandoned, potential remedies include  deleting cluster  and notifying its owner.

**Describe alternatives you've considered**
None

**How would users interact with this feature?**
Traffic threshold (bytes/sec); Duration: 2,7,30 days. Analogous to Abandoned Workloads.

**Comment by dwbrown2** [comment]
Really interesting! Would you have the Kubecost agent installed on all of these clusters or would you need another data source?

**Comment by grinbvi** [comment]
Webb. I will leave the implementation for your team. Pls make sure there is no conflict with Security.

**Comment by grinbvi** [comment]
We have people who create the clusters (non-prod) and soon forget about them. But wondeful cloud providers (dealers) charge for the abondoned clusters anyway.

**Comment by dwbrown2** [comment]
Yep, just trying to get a sense if you install Kubecost on all of these clusters... is that the case?

@teevans think the new cluster list view could have interesting tie in with this!

**Comment by grinbvi** [comment]
It is preferable to install Kubecost on all clusters.

**Comment by dwbrown2** [comment]
Sg, would you want Kubecost to assist in the spin down of these clusters?

**Comment by grinbvi** [comment]
spin down?

**Comment by dwbrown2** [comment]
i.e. actually delete cluster resources, e.g. nodes, disks, etc

**Comment by grinbvi** [comment]
yes. but first notify the requiste team that the decommissioning process is initiated.

**Comment by dwbrown2** [comment]
Sounds good. Definitely fits with our vision for Kubecost Actions. Let us start discussing a design soon. Would you be open to giving input?

**Comment by grinbvi** [comment]
I am open.

**Comment by dwbrown2** [comment]
@grinbvi we're planning to implement this first at the namespace level and then expand! would that be useful in your situation?

**Comment by grinbvi** [comment]
Yes.

**Comment by ameijer** [comment]
Hello @grinbvi! I wanted to follow up on Webb's comments with a design for your review: https://docs.google.com/document/d/1ezy2LWiMyQQ4ZitQA6jMJQWXM1H0jFZkog8lrICfk7w/edit?usp=sharing. 

We're building this now. Your feedback is most welcome!

**Comment by grinbvi** [comment]
I do not have access to the above link

**Comment by ameijer** [comment]
[[EXTERNAL] Design Proposal Namespace Turndown.pdf](https://github.com/kubecost/cost-analyzer-helm-chart/files/11491770/EXTERNAL.Design.Proposal.Namespace.Turndown.pdf)

@grinbvi here's a PDF of the above link for you

**Comment by grinbvi** [comment]
Thanks, I'll check it out.

**Comment by chipzoller** [comment]
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.
