### ISSUE TITLE
productKey.enabled is not used cleanly

### ISSUE THREAD

**Issue by abdennour** [kubecost/cost-analyzer-helm-chart#2056]
Thanks for your interest in Kubecost!  To ensure you get the help you need, please follow these guidelines:

- If you have questions about product functionality/usage or need assistance with product installation/configuration, please email support@kubecost.com, where our support engineering team will be happy to help!
- If you have a reproducible bug or a feature request, you're in the right place.  Please include the information requested below.

---
# For reproducible bugs, please provide the following

**Describe the bug**  

**To Reproduce**  
3. See error

**Expected behavior**  

**Screenshots**  

**Collect logs (please complete the following information):**
- Run `helm ls` and paste the output here:
- If the pod is stuck in init, run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-init` and paste output here:
- If a page is broken or not loading, open your javascript developer console and paste the ouput here:
- Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-server` and paste the output here:
- Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-model` and paste the output here:
- Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-frontend` and paste the output here:

---
# For feature requests, please provide the following:

**What problem are you trying to solve?**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**How would users interact with this feature?**

**Comment by thomasvn** [comment]
Hi @abdennour! I see the template above, but it doesn't look to be filled out describing the issue.

I see that you've created a PR https://github.com/kubecost/cost-analyzer-helm-chart/pull/2057 too! Should we close this issue, then continue discussing on the PR?

**Comment by abdennour** [comment]
Because of time stress , we didn't fill in description. Please help to edit and fill description, or give to me and I will paste .. as per PR , it's clear.
Opening issue , then implement it in PR is a good practice . Opening  PR without issue reference is not good practice
