### ISSUE TITLE
Add secondary Kubecost versions alerts

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2059]
**What problem are you trying to solve?**
When managing a large set of clusters, ensuring that all versions of Kubecost maintain an up-to-date version can be challenging. 

**Describe the solution you'd like**
I would like for there to be secondary upgrade details added as a notification on the primary. Another solution might be to add the details of clusters with out-of-date Kubecost instances to the current [Kubecost Health alerts](https://docs.kubecost.com/using-kubecost/getting-started/alerts#type-monitor-kubecost-health).

**Describe alternatives you've considered**
I can manually monitor individual instances through a secondary UI (if deployed) or via CLI with a command like `helm list`.

**How would users interact with this feature?**
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/43491549/225466854-2b0a82ab-ff7c-4d14-951a-e554c2c0dce8.png">
And/Or [Kubecost Health Alerts](https://docs.kubecost.com/using-kubecost/getting-started/alerts#type-monitor-kubecost-health)

**Comment by kwombach12** [comment]
@keithhand Thanks for raising this. I will add to our feature backlog

**Comment by dwbrown2** [comment]
@kwombach12 do we now have this info, i.e. Kubecost (agent) version, on Cluster Inspect page?

@teevans could be a nice addition to a new Cluster List page if easily available?

**Comment by kwombach12** [comment]
We have the Kubernetes version of the cluster, but not the kubecost agent version. I agree it would be a nice addition to the page.

**Comment by wamak9** [comment]
This will avoid data loss for some clusters which are running way older version or kubecost and cannot upgrade to the last unless redeployed.

**Comment by AjayTripathy** [comment]
Hmm-- wouldn't expect any data loss unless new data is added, but fair enough for new fields/metrics being created.

**Comment by wamak9** [comment]
so, I was running 1.95 and I tried to move to 1.100 and I got the pod security policy error. basically this one https://docs.kubecost.com/troubleshooting/troubleshoot-install#issue-with-kubernetes-v1.25-helm-commands-fail-when-podsecuritypolicy-crd-is-missing-for-kubecost-gr

Turn out we upgraded the cluster to 1.25 like months ago and Prometheus was running so did kubestate metrics but not the cost analyzer. untill I moved it to 1.100  and then everything is working as expected and I lost the info for the last two months I dont see anything on the primary. I did had a session with the support team and there is no way to recover it.

Weird thing is cost analyzer is  in running state with 0/2 Running. That might be why we never got a alert as well.

so if you get a chance please pick it as soon as possible.
More helpfull for tenants with larger clusters
