### ISSUE TITLE
Add enterprise node limit alerts

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2060]
**What problem are you trying to solve?**
There isn't any indication today to let the user know their current Enterprise node limit, or if they are approaching that limit.

**Describe the solution you'd like**
A notification/alert so that when I start to approach my node limit, I know before it happens.

**Describe alternatives you've considered**
Checking the `/diagnostics` page and comparing with my known enterprise limit

**How would users interact with this feature?**
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/43491549/225482591-56f25ef8-01c8-447e-93a9-bf63dd40f710.png">
And/Or [Kubecost Health Alerts](https://docs.kubecost.com/using-kubecost/getting-started/alerts#type-monitor-kubecost-health)

**Comment by kwombach12** [comment]
@keithhand this is interesting to me - I was actually not aware that we had a gate setup based on number of nodes for enterprise users. Where does the max number of nodes value come from?

**Comment by teevans** [comment]
Yeah we don't track that inside of the application currently. We'd either need to bake that into the key management situation, or create an arbitrary field in the helm config that would display this.

**Comment by wamak9** [comment]
P0

**Comment by dwbrown2** [comment]
@wamak9 assuming by P0 you mean this is high priority for you as a user. Can you share more?

**Comment by wamak9** [comment]
maybe @keithhand  can add in more details here.  This is for the number of licenses we have and number of Nodes we use.
and based on the info I got if we go over the limit we get charged for the next tire and at the moment we dont have a way to monitor this apart from me looking at the kubecost page every week or so and see the node usage.

**Comment by wamak9** [comment]
bump

**Comment by chipzoller** [comment]
Kubecost no longer licenses by nodes so no longer relevant.
