### ISSUE TITLE
Add option to customize the default Allocate Idle type

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2061]
**What problem are you trying to solve?**
When using the "Allocate Idle Resources" option, some users want to default sharing by cluster, and others want to default sharing by node.

**Describe the solution you'd like**
The ability to change the type of default idle used.

**Describe alternatives you've considered**
Change the option per report.

**How would users interact with this feature?**
`kubecostProductConfigs.defaultIdleType: [cluster|node]`

**Comment by wamak9** [comment]
+1

**Comment by wamak9** [comment]
maybe we can add more options.
1. Specify based on clusters what the defaultIdleType is , could be sharebynode or sharebycluster.

if I have 15 clusters and i only needed 5 to be share by node then I should be able to specify that and other way around.

**Comment by chipzoller** [comment]
This is complete. Idle can be shared by cluster or by node.
