### ISSUE TITLE
Add total cluster count to Kubecost health alerts

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2062]
**What problem are you trying to solve?**
When I get [notified](https://docs.kubecost.com/using-kubecost/getting-started/alerts#type-monitor-kubecost-health) that clusters are added/removed from Kubecost, I would like to know the updated total number of clusters I have deployed to. This would help with users who have a lot of cluster names and might not notice an individual cluster get added/removed unintentionally.

**Describe the solution you'd like**
A "Total Clusters: x" alert.

**Describe alternatives you've considered**
Keep a close inventory of Cluster IDs monitored by Kubecost that are added/removed.

**How would users interact with this feature?**
See new information added to the existing "cluster added" and "cluster removed" alerts
```
Clusters Added: xxx
Clusters Removed: yyy, zzz
Total Clusters: 5 (Previous: 6)
```

**Comment by dwbrown2** [comment]
@AjayTripathy quick addition?

**Comment by wamak9** [comment]
This would be really nice feature, We lost 2 months of data for two clusters. This might help us figure out the missing clusters and fix them as soon as possible.

**Comment by dwbrown2** [comment]
@wamak9 can you share why the current health alert didn't help catch agents that stopped reporting data?

**Comment by wamak9** [comment]
we have 15 + clusters and when we get a alert saying new clusters are added, alert will list the names of all 15+ cluster(Not a number but names). so atleaset for me, I cannot remember all the names of the clusters and I cannot go over the list of names kubecsot alert published. 

If it being a number like total 15 added with names and a number and if I know yeah we  have 15 and when the alert triggers again and says 14 that means one cluster is missing for sure  but  gain I have to list them all and then compare and see who is missing and go debug.

if there is way if we can display name of the missing clusters and number count that would be really helpful.
If more details are needed, we can schedule a session.

**Comment by dwbrown2** [comment]
@wamak9 PR outstanding! Expected to be reviewed soon.
