### ISSUE TITLE
Support adding additional labels to ingress resources

### ISSUE THREAD

**Issue by mgtrrz** [kubecost/cost-analyzer-helm-chart#2070]
**What problem are you trying to solve?**
We would like to be able to add labels to the cost-analyzer ingress resources created by the helm chart. Labels on ingress objects allow our DNS controller to create records for us. There may be other ingress resources created by this helm chart that also don't have this option and would benefit users who wish to set additional labels.

**Describe the solution you'd like**
A new key titled `additionalLabels` in the top level `ingress` parameter that merges the [existing labels](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-ingress-template.yaml#L20-L21) for the cost-analyzer ingress object

**Describe alternatives you've considered**
n/a

**How would users interact with this feature?**
n/a

**Comment by thomasvn** [comment]
Hey @mgtrrz! This seems very do-able.

To clarify, are you looking to add labels just to the cost-analyzer ingress? Are you using any other ingresses for services such as Grafana, Prometheus, or Thanos?

**Comment by mgtrrz** [comment]
Hi @thomasvn! so far, just the cost-analyzer ingress. We're not using grafana/prometheus/thanos, though it might be a nice-to-have for anyone else who might need something similar

**Comment by thomasvn** [comment]
@mgtrrz Take a look at this PR https://github.com/kubecost/cost-analyzer-helm-chart/pull/2077 and let me know what you think!

**Comment by mgtrrz** [comment]
@thomasvn looks good! thanks for your contribution to this!
