### ISSUE TITLE
Pipeline to reconcile custom csv pricing (on prem) retroactively and on custom date ranges

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#2071]
**What problem are you trying to solve?**
There's no pipeline to reconcile and apply custom pricing retro actively. Kubecost only calculates custom csv pricing from date it's configured forward.

**Describe the solution you'd like**
A reconciliation pipeline to apply custom csv pricing for simple and advanced method retroactively. Additionally, having the ability to set multiple custom price values for monthly cpu, ram, etc in the simple pipeline AND values supported in the [custom csv](https://docs.kubecost.com/install-and-configure/advanced-configuration/csv-pricing#pricing-discounts) and apply them accordingly to **custom date** ranges. E.g. From 2/23/23 - 3/23/23, apply $90 cpu monthly cost and $30 monthly ram cost. For 3/24/23 - 4/24/23 apply $100 cpu/monthly and $50 ram/monthly cost for example cluster. Have kubecost then recalculate costs accordingly. 

**Describe alternatives you've considered**
N/A

**How would users interact with this feature?**
By default users would see the custom pricing take effect retroactively when custom cpu/ram/pv/gpu/node/etc pricing is set. In the settings page, Users would have the ability to set custom pricing for targeted custom date ranges. "The use case here is multiple stakeholders would see the results based on their needs." - Statement from customer.

**Comment by mmurph3** [comment]
*Having it visible in the UI to show how long the custom pricing is set for when setting a custom date range is important

**Comment by mmurph3** [comment]
Per our discussion - we have a commitment here from Product & Engineering. What's the timeframe? v1.103? Is it more realistic to say that we'll at least have reconciliation capabilities first or the whole feature released? This is a roadblock for an enterprise customer

cc @AjayTripathy @kwombach12

**Comment by AjayTripathy** [comment]
This has an engineer ( @CampfireRemnants ) assigned for 102 and I'm ready to help with design-- sounds like it's important for multiple customers. Let's set up some time to get started soon @CampfireRemnants !

**Comment by Sean-Holcomb** [comment]
@AjayTripathy this is v1.103 is it not?

**Comment by Sean-Holcomb** [comment]
The general ask of reconciliation from the CSV is clear but can I have some elaboration on the updated capabilities of the CSV? It sounds like we will need to change things for this feature request.
> Additionally, having the ability to set multiple custom price values for monthly cpu, ram, etc

Monthly is kind of a difficult here, is monthly a specific ask from the customer?
Resource breakdowns don't actually make sense here since this is going into assets where that information would be lost.

Can I get some bullet points for the key feature requests, ordered by importance if possible?

**Comment by AjayTripathy** [comment]
https://docs.google.com/document/d/10JgVDtLTIAQLarLmtQjFSMLxp3Q2VYsiKQrmHtXhU4A/edit?usp=sharing

Yes, let's try and put in scope for 103. I am not sure monthly is necessary but will find out more. I think setting a node price makes the most sense vs cpu/ram etc.

**Comment by mmurph3** [comment]
@kwombach12 @AjayTripathy any update on this? Thanks.

**Comment by kwombach12** [comment]
@teevans @Sean-Holcomb Didn't we deliver this in 103?

**Comment by mmurph3** [comment]
@teevans @Sean-Holcomb enterprise customer is asking the status of this on cadence call this morning. I don't see it in [release notes](https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.103.0).

**Comment by abdennour** [comment]
I am another enterprise customer. But I am already contributor here also. actually, we need this fix as well.

**Comment by mmurph3** [comment]
@kwombach12 @cliffcolvin @AjayTripathy it's unclear to us if this was added in v1.103. Any update here? I see the doc in this issue scoping it.

**Comment by kwombach12** [comment]
@mmurph3 looking back at the 103 docs it seems we did not deliver this feature.

**Comment by chipzoller** [comment]
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.
