### ISSUE TITLE
k8s.gcr.io registry

### ISSUE THREAD

**Issue by nmarangella** [kubecost/cost-analyzer-helm-chart#2082]
Should this be updated to registry.k8s.io before 4/3/23?
https://github.com/kubecost/cost-analyzer-helm-chart/blob/b04da589a5a8b469fe13f8b25cd21023601ecca9/kubecost.yaml#L20746
Reference:  https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/

**Comment by AjayTripathy** [comment]
Yes, seems reasonable. Let's get this manifest updated in 102.  cc @Adam-Stack-PM

**Comment by Adam-Stack-PM** [comment]
https://kubecost.atlassian.net/browse/BURNDOWN-47

**Comment by Adam-Stack-PM** [comment]
Based on the Jira ticket closing.
