### ISSUE TITLE
Manually Define 'Groups' within Kubecost UI/Reports

### ISSUE THREAD

**Issue by mclean0328** [kubecost/cost-analyzer-helm-chart#2085]
**What problem are you trying to solve?**
Without the use of tags/labels, I need to be able to save groups of resources (namespaces/deployments/services) into Kubecost define 'Groups'  that I can apply in reporting repeatedly without having to manually input each filter on the Advanced Reporting page.  When there are any tens-hundreds of different ways the data needs to consistently be viewed in Kubecost, manually entering in the filters for all the variations takes a long time.

**Describe the solution you'd like**
Introduction of manually defined Groups of resources in Kubecost for Advanced Reporting. A Group would consist of namespaces, deployments, services, etc. 

**Describe alternatives you've considered**
The alternative solution is to use the standard filtering in the Advanced reporting and to add the deployments, namespaces, services, etc. to the report every time.  

**How would users interact with this feature?**
In the Kubecost UI (either on the Settings page or Advanced Reporting page), there would be a section where you can define different saved Groups.  When using the Advanced Reporting, you would be able to apply the Group as a filter to filter down the report to just the resources defined in the Group.

**Comment by kwombach12** [comment]
We are working of designs a solutions for this in advanced reports! We hope to have some mocks to show you in the next couple weeks!
