### ISSUE TITLE
Custom Proportional Kubernetes and Out-Of-Cluster Resource Shared Costs

### ISSUE THREAD

**Issue by mclean0328** [kubecost/cost-analyzer-helm-chart#2086]
**What problem are you trying to solve?**
Some kubernetes resources and out of cluster services are utilized by other kubernetes resources more than others.  For example, one cluster, namespace, deployment will utilize  AWS S3 resourcing or a shared namespace more than another AWS cluster, namespace, deployment, etc. With this, I want to be able to define (ideally based on observed usage of the external resource, but manually if necessary) proportional shared costs for out of cluster resources. 

**Describe the solution you'd like**
I would like Kubecost to observe usage of cluster workloads and out of cluster resources by the kubernetes resources and provide a way to apply the proportional shared cost for that resource.  If this cannot be done automatically, define a way to manually associate X percentage of an out of cluster resource cost to a specific namespace, deployment, cluster.

**Describe alternatives you've considered**
Using standard Shared Costs method in Kubecost, but that applies the costs evenly.

**How would users interact with this feature?**
Ideally, Kubecost would be able to track use of specific proportional workloads or out of cluster services and apply cost of usage proportionally to deployment, namespace, cluster costs in Advanced reporting.  The out of cluster resources would still appear as their own line items in Kubecost Advanced Reporting, but only a proportion of the cost would be applied instead of the full cost.

If manual definitions are necessary, In Advanced Reporting, in the Filter section, there could be a new section that allows the user to input what percentage of cost they could apply for a specific out of cluster resource.  
<img width="456" alt="Screen Shot 2023-03-27 at 11 56 40 AM" src="https://user-images.githubusercontent.com/50640513/227996722-f455b130-43e6-4000-b83c-c1c7c29610c7.png">

Or a customer could provide a CSV with the custom proportional shared costs that can be referenced.

**Comment by srpomeroy** [comment]
Partially covered by #1580

**Comment by kwombach12** [comment]
Yea we dont have the ability to 'share' external costs - that would be covered by #1580 like @srpomeroy mentioned. I agree that a custom proportion of sharing is something that we should support. We are looking at that for advanced reports
