### ISSUE TITLE
Expose Cluster Health in REST API

### ISSUE THREAD

**Issue by mclean0328** [kubecost/cost-analyzer-helm-chart#2087]
**What problem are you trying to solve?**
I would like the Cluster Health information exposed in a new or existing Kubecost REST API endpoint

**Describe the solution you'd like**
Cluster Health Score [here](https://docs.kubecost.com/using-kubecost/getting-started/cluster-health-score) exposed at an existing REST endpoint or new endpoint such as /model/healthscore

**Describe alternatives you've considered**
Use the Kubecost UI

**How would users interact with this feature?**
Using the Kubecost REST APIs

**Comment by dwbrown2** [comment]
Thanks for reporting! We've got a big overhaul that we want to consider in a future release. There's probably going to multiple parts that will need some meaningful design work beforehand.
