### ISSUE TITLE
[bug] Keep image tag lowercase for nightly builds

### ISSUE THREAD

**Issue by abdennour** [kubecost/cost-analyzer-helm-chart#2088]
Hi, 

I am trying to use nightly build based on a recommendation from the enterprise support, until getting the fix in the stable release.
While trying the nightly
> gcr.io/kubecost1/cost-model-nightly:OC-440dfcb_KCM-1f53ee9

I am getting img err pull backoff.. 

```log
unknown desc = missing signature key
```

Actually, the same image was pulled from a new cluster ( k8s 1.24), while i am facing issue in a very old cluster (k8s 1.11)

After investigation, I found the docker runtime of the old cluster, does not support an image tag with capital case

Please try to modify the CI to tag the build with regular tag naming

**Comment by michaelmdresser** [comment]
Hi @abdennour, thanks for the report. I moved this to a better repository for tracking; `kubectl cost` has very little to do with our overall nightly release process. Someone should triage this issue soon!

@Adam-Stack-PM I'm not sure how our issue triage stuff works with an issue transferred from another repo, putting this on your radar just in case.

**Comment by thomasvn** [comment]
Hi @abdennour, I've opened a PR in our internal CI/CD repo. We'll get this fixed shortly!

**Comment by Adam-Stack-PM** [comment]
> 

Thanks @michaelmdresser

**Comment by AjayTripathy** [comment]
PR merged, this should be reflected in tonight's nightly!
