### ISSUE TITLE
Add information for normalized workload usage hours

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2089]
**What problem are you trying to solve?**
When working with cloud providers, discounts can sometimes be applied in ways that might cause the underlying allocation details to be less accurate. Suppose you have an EKS cluster on AWS with 2 nodes, both t3-mediums. If you were to have an EDP agreement with AWS that resulted in one of these nodes being 50% off, any workload running on the discounted node could result in a lower cost than a workload running on the full-price node because the allocation data is built on the underlying node cost that the workload ran on. 

A similar problem can appear when trying to compare raw assets if might be filtered by a specific label that could help to aggregate into a grouping like "team" or "project". One team might have EDP discounts applied to their nodes, while another doesn't; which leads to it being hard to manage and compare the actual "usage" of these resources. 

With regards to AWS, much of this information seems to be tracked in the CUR, as they provide a ["lineItem/NormalizationFactor"](https://docs.aws.amazon.com/cur/latest/userguide/Lineitem-columns.html#l-N) value, that you can get with a query like the following:

```
sum(case when lower(pricing_unit) in ('hours', 'hrs')
  and line_item_line_item_type != 'SavingsPlanNegation'
  and lower(line_item_product_code) in ('amazonec2', 'amazonrds')
  and regexp_like(line_item_usage_type, '.*[Box|Instance|Spot]Usage.*')
  then line_item_normalized_usage_amount
  else 0 end) as normalized_usage_hours
```

**Describe the solution you'd like**
I would like a "Normalized Usage" value that shows the user a value that is easily able to consistently be compared with another similar-type object, regardless of how discounts are applied at the cloud level. 

Once this value is assigned to a node, it would also be good to be able to attribute this value to Allocation workloads, so I can compare workloads as well, without worrying about which workload is associated with which node.

**Describe alternatives you've considered**
Manually obtain the normalization information from the CUR so that I can get "Normalized usage hours" for individual assets.

**How would users interact with this feature?**
![image](https://user-images.githubusercontent.com/43491549/228081670-b0839354-787c-435b-8241-03f265f3ea8c.png)
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/43491549/228083193-9bf241d8-ef38-49d3-9402-19abf330a54a.png">

**Comment by keithhand** [comment]
Some points that were added by the customer who initially noticed this (more details in the [Zendesk ticket](https://kubecost.zendesk.com/agent/tickets/3681)):

> [The ticet] makes reference to variable pricing (discounts) driven by an EDP. I understand those (Enterprise Discount Programs) as specifying standard discounts applied consistently across AWS accounts (enterprise). More likely drivers of variable cost that effect nearly all AWS customers are the (unpredictable) application of Saving Plans, Reserved Instances, and credits applied across accounts each month.

> The SQL snippet is something I wrote to be generalized across both EC2 and RDS. Not sure if that is going to confuse anyone. You could make more precise by changing to: `lower(line_items_product_code) = 'amazonec2'`

**Comment by AjayTripathy** [comment]
Seems like a reasonable idea. @Sean-Holcomb we should be preserving the discount field and by default using net cost in reconciliation, but maybe we can make that configurable?

**Comment by mmurph3** [comment]
Checking to see if we can get an update on this FR. Thanks!

**Comment by kwombach12** [comment]
@mmurph3 in 103 we are adding the ability to switch between net costs, net amortized costs, & list costs on the cloud costs page we will try to add this to allocations as well, but that may slip to next release.

**Comment by mmurph3** [comment]
@kwombach12 per customer (statement):
The point of that request is to see usage (in normalized hours) free of distortions caused by changes in price due variable RI & SP coverage or PPA

**Comment by kwombach12** [comment]
@mmurph3 I see. Thanks for additional context. We will try to prioritize this for future releases

**Comment by anoop2811** [comment]
@kwombach12 @mmurph3 : Has there been any progress on this? Do you have an ETA for this functionality?

**Comment by kwombach12** [comment]
@anoop2811 if you visit the cloud costs page, you should be able to set cost metric = 'list cost' which will show costs without any discounts applied. Does that work for your use case?

**Comment by premchandb** [comment]
@kwombach12 @mmurph3 Please note that our original request for this thread is to get the normalized view for usage and we are still not able to see it. While the cost attributes help in someway, but this is not our primary ask here

**Comment by mmurph3** [comment]
@premchandb can you confirm we're talking about this line item here from the bill as an option to toggle in the cloud costs page?

```
lineItem/NormalizedUsageAmount
The amount of usage that you incurred, in normalized units, for size-flexible RIs. The NormalizedUsageAmount is equal to UsageAmount multiplied by NormalizationFactor.
```

**Comment by chipzoller** [comment]
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.
