### ISSUE TITLE
Add ability to filter and aggregate by region and/or AZ.

### ISSUE THREAD

**Issue by ErnestG4** [kubecost/cost-analyzer-helm-chart#2091]
**What problem are you trying to solve?**
Give visibility to breakdown by region/AZ.

**Describe the solution you'd like**
Add region and/or AZ: filters, aggregation types, and perhaps a note on the pod drill down. 

**How would users interact with this feature?**
Allocations and Assets pages. Perhaps add AZ views to network costs panel in the future.

**Comment by dwbrown2** [comment]
Thanks, @ErnestG4! Let us review soon. Have a particular set of scenarios you've seen this be valuable in? 

Re: solution -- would asset/node label get what's needed here as a more general solution?
