### ISSUE TITLE
Update "File Backup" section of the Diagnostics page

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2095]
**What problem are you trying to solve?**
The "File Backup" section on the diagnostics page is [hard to interpret](https://github.com/kubecost/cost-analyzer-frontend/issues/943#issuecomment-1202419888) and could provide additional metadata information related to the backup process.

**Describe the solution you'd like**
Split up different "File Backup" diagnostic information into individual categories that are easier to explain, and provide a UI popup with metadata, similar to what you see with the Cloud Integration section (Last Run, Next Run, Refresh Rate).

**Describe alternatives you've considered**
Check the `/model/etl/config` API for specific details and check logs for various upload stats.

**How would users interact with this feature?**
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/43491549/228969300-2f8e5309-37be-40f4-a3e0-0abc885f0350.png">
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/43491549/228969979-96288900-0716-4504-bcdb-81b8476de923.png">

**Comment by wamak9** [comment]
+1

**Comment by dwbrown2** [comment]
+1, aiming to scope this during 103!
