### ISSUE TITLE
Add a quicker notification for when secondary clusters are added

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2096]
**What problem are you trying to solve?**
When adding secondary clusters, you must wait for the Thanos delay before confirming whether or not the data successfully connects to the primary, [reference](https://github.com/kubecost/docs/blob/main/long-term-storage.md#troubleshooting). 

**Describe the solution you'd like**
I want a way to see that a new cluster has been recognized from the primary without waiting for the secondary to start pushing data. 

**Describe alternatives you've considered**
You can view the logs of the secondary "thanos-sidecar" pod and confirm no errors are seen when authenticating with the bucket. 

**How would users interact with this feature?**
Currently, we have cluster alerts that might be useful to build this off by separating "secondary cluster added" and "ingesting secondary cluster metrics." Another option would be to have a notification/warning on the primary that a cluster is being read from durable storage, but metrics still need to be uploaded.
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/43491549/228966607-0034459b-62aa-4a50-928a-d96240b9baab.png">

**Comment by wamak9** [comment]
+1

**Comment by AjayTripathy** [comment]
I'm not sure the level of effort here. I think that we'd need to listen to logs from the Thanos services and emit errors or notifications.
