### ISSUE TITLE
 Broken SAML URL on 1.101.2 and 1.101.3

### ISSUE THREAD

**Issue by praveenkumar0566** [kubecost/cost-analyzer-helm-chart#2098]
# For reproducible bugs, please provide the following

**Describe the bug**  
upgrading to v1.101.2 from 1.99.0 has broken our SAML integration. Redirection from Okta UI to Kubecost is broken after authentication. We get redirection to https://kubecost.xxxxxxxx.**ioindex.html/** which doesn’t resolve to anything and it gets an error. 
Accessing Kubecost directly over correct URL works.

**To Reproduce**  
 Okta SAML setup

**Expected behavior**  
After authentication of SSO the URL should redirect to kubecost UI , But the issue is at the end of URL "index.html" is getting appended automaticaaly.

**Screenshots**  
Will be provided on direct chat.

**Collect logs (please complete the following information):**

**Please share the support case, if any**  
https://kubecost.zendesk.com/agent/tickets/3662

**What impact will this have on your ability to get value out of Kubecost?**
None.. Since currently the user is manually editing the URL to enter to kubecost UI

**Comment by AjayTripathy** [comment]
@kaelanspatel any ideas what's going on here?
