### ISSUE TITLE
getaddrinfo ENOTFOUND in alerts pods

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#210]
Reported on v1.50.3. The appears to be related to alerts being impacted when a different release name is passed. 

✗ kubectl get jobs
NAME                              COMPLETIONS   DURATION   AGE
cost-analyzer-checks-1580153400   1/1           20s        26m
cost-analyzer-checks-1580154000   1/1           21s        16m
cost-analyzer-checks-1580154600   1/1           36s        6m20s

Error: Error: getaddrinfo ENOTFOUND cost-analyzer.kubecost cost-analyzer.kubecost:9001
    at Object.dispatchError (/node/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:60:19)
    at Request.client.on.err (/node/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:674:20)
    at emitOne (events.js:121:20)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/node/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)

Reported by Stephany.

**Comment by dwbrown2** [comment]
Bolt, this looks like another place where not templating release name correctly

**Comment by mbolt35** [comment]
It actually looks like we're correctly supplying the address with namespace: https://github.com/kubecost/cost-analyzer-helm-chart/blob/7d3c45e7ba6e92f9c334000273fc47c504418eff/cost-analyzer/templates/cost-analyzer-checks-template.yaml#L33-L40

**Comment by mbolt35** [comment]
The `cost-analyzer.fullname` template contains the `{{ .Release.Name }}` but the error seems to indicate it's not used?

https://github.com/kubecost/cost-analyzer-helm-chart/blob/7d3c45e7ba6e92f9c334000273fc47c504418eff/cost-analyzer/templates/_helpers.tpl#L9-L25

**Comment by AjayTripathy** [comment]
Can confirm we're applying the release name appropriately. Do we have a version number with the error? I believe this is fixed.

**Comment by gknepper** [comment]
Updated to version 1.52.2 using helm chart and the issue still happening.

**Comment by dwbrown2** [comment]
@gknepper any chance you can share more? If you can send a [bug report](http://docs.kubecost.com/bug-report) to team@kubecost.com that would be really helpful.

Or just seeing a stack trace and what parameters you updated during install would help us reproduce.

**Comment by gknepper** [comment]
Hello @dwbrown2, sorry my delay. Basically the UI is not loading properly so I can't generate a bug report. The mail page stays on "Fetching clusters..." forever and in settings the Capture bug report button is not working. Let me know how can I help you other wise I'll reinstall kubecost from scratch. Thanks

**Comment by dwbrown2** [comment]
Hi @gknepper this particular issue is in the alerts pods and should not impact the core application. 
This sounds like something else. Could you capture any developer console errors and/or screenshots? Also, any logs in `cost-model` would be helpful. Example command: 

```
kubectl logs kubecost-cost-analyzer-7886544c47-tm98k -n kubecost -c cost-model
```

**Comment by dwbrown2** [comment]
Hi @gknepper this particular issue is in the alerts pods and should not impact the core application. 
This sounds like something else. Could you capture any developer console errors and/or screenshots? Also, any logs in `cost-model` would be helpful. Example command: 

```
kubectl logs kubecost-cost-analyzer-7886544c47-tm98k -n kubecost -c cost-model
```

**Comment by gknepper** [comment]
Home screen:

![image](https://user-images.githubusercontent.com/14863517/75271582-4a8ffe00-57b1-11ea-9d7f-ad9993c10ca4.png)

Settings (Capture bug report not working):

![image](https://user-images.githubusercontent.com/14863517/75271707-790dd900-57b1-11ea-9f1a-e4288f1b13b9.png)

Cost model:

I0225 17:31:39.235633 1 router.go:814] Starting cost-model (git commit "")
I0225 17:31:39.242611 1 router.go:841] Success: retrieved a prometheus config file from: http://cost-analyzer-prometheus-server.cost-analyzer
I0225 17:31:39.246313 1 router.go:847] Success: retrieved the 'up' query against prometheus at: http://cost-analyzer-prometheus-server.cost-analyzer
I0225 17:31:39.248009 1 clustercache.go:84] NAMESPACE: cost-analyzer
I0225 17:31:39.248439 1 reflector.go:122] Starting reflector *v1.Node (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248466 1 reflector.go:160] Listing and watching *v1.Node from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248486 1 reflector.go:122] Starting reflector *v1.Pod (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248499 1 reflector.go:122] Starting reflector *v1.StatefulSet (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248532 1 reflector.go:122] Starting reflector *v1.PersistentVolume (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248540 1 reflector.go:160] Listing and watching *v1.StatefulSet from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248545 1 reflector.go:160] Listing and watching *v1.PersistentVolume from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248563 1 reflector.go:122] Starting reflector *v1.Namespace (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248575 1 reflector.go:160] Listing and watching *v1.Namespace from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248657 1 reflector.go:122] Starting reflector *v1.Deployment (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248672 1 reflector.go:160] Listing and watching *v1.Deployment from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248438 1 reflector.go:122] Starting reflector *v1.ConfigMap (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.250054 1 reflector.go:160] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248523 1 reflector.go:160] Listing and watching *v1.Pod from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248437 1 reflector.go:122] Starting reflector *v1.StorageClass (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.250240 1 reflector.go:160] Listing and watching *v1.StorageClass from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248437 1 reflector.go:122] Starting reflector *v1.Service (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.250459 1 reflector.go:160] Listing and watching *v1.Service from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.448603 1 watchcontroller.go:183] Starting *v1.Node controller
I0225 17:31:39.448631 1 watchcontroller.go:183] Starting *v1.ConfigMap controller
I0225 17:31:39.448663 1 watchcontroller.go:183] Starting *v1.Pod controller
I0225 17:31:39.448666 1 watchcontroller.go:183] Starting *v1.Namespace controller
I0225 17:31:39.448673 1 watchcontroller.go:183] Starting *v1.Service controller
I0225 17:31:39.448680 1 watchcontroller.go:183] Starting *v1.StorageClass controller
I0225 17:31:39.448695 1 watchcontroller.go:183] Starting *v1.Deployment controller
I0225 17:31:39.448701 1 watchcontroller.go:183] Starting *v1.StatefulSet controller
I0225 17:31:39.448708 1 watchcontroller.go:183] Starting *v1.PersistentVolume controller
I0225 17:31:39.543172 1 provider.go:239] Unsupported provider, falling back to default
I0225 17:31:39.547184 1 router.go:882] No configs found at installtime, using existing configs: configmaps "pricing-configs" not found
I0225 17:31:39.565501 1 main.go:544] [Debug] aggregation: cache warming defaults: 2d:1m::::namespace::::weighted:false:false:true
I0225 17:31:40.270962 1 main.go:587] aggregation: warm cache: 2d
I0225 17:31:40.271037 1 main.go:544] [Debug] aggregation: cache warming defaults: 7d:1m::::namespace::::weighted:false:false:true
I0225 17:31:41.650059 1 costmodel.go:2687] [Profiler] 1.378897806s: costDataRange(163.000000h): Prom/k8s Queries:
- RAMAllocations took 1.039223724s
- CPUAllocations took 1.148957993s
- RAMUsage took 1.378720852s
I0225 17:31:41.903098 1 profiling.go:14] [Profiler] 1.63201576s: ComputeAggregateCostModel(duration=7d, offet=1m, field=namespace): compute cost data
I0225 17:31:41.944114 1 profiling.go:14] [Profiler] 1.673056839s: ComputeAggregateCostModel(duration=7d, offet=1m, field=namespace)
I0225 17:31:42.205471 1 main.go:603] aggregation: warm cache: 7d
I0225 17:31:42.205516 1 main.go:544] [Debug] aggregation: cache warming defaults: 1d:1m::::namespace::::weighted:false:false:true
I0225 17:31:42.659347 1 main.go:571] aggregation: warm cache: 1d
I0225 17:31:42.659403 1 main.go:544] [Debug] aggregation: cache warming defaults: 30d:1m::::namespace::::weighted:false:false:true
I0225 17:31:44.682944 1 costmodel.go:2687] [Profiler] 2.023401598s: costDataRange(697.000000h): Prom/k8s Queries:
- RAMRequests took 1.046420063s
- GPURequests took 1.103437283s
- CPURequests took 1.230254797s
- PodLabels took 1.266186702s
- CPUUsage took 1.299596976s
- RAMAllocations took 1.799332387s
- RAMUsage took 1.836783899s
- CPUAllocations took 2.023046375s
I0225 17:31:45.218190 1 profiling.go:14] [Profiler] 2.558746089s: ComputeAggregateCostModel(duration=30d, offet=1m, field=namespace): compute cost data
I0225 17:31:45.314820 1 profiling.go:14] [Profiler] 2.655400808s: ComputeAggregateCostModel(duration=30d, offet=1m, field=namespace)
I0225 17:31:47.417329 1 main.go:619] aggregation: warm cache: 30d

**Comment by dwbrown2** [comment]
Thanks, nothing looks concerning in backend logs. Something is going on with your frontend. I would assume it's related to a networking issue. Just looking at your UI, it looks like something may be blocking access to our external frontend dependancies. 

Can you share any errors in your developer console?

**Comment by gknepper** [comment]
@dwbrown2 

> kubectl logs cost-analyzer-656f669797-dbv2p -n cost-analyzer -c cost-model
I0225 17:31:39.235633       1 router.go:814] Starting cost-model (git commit "")
I0225 17:31:39.242611       1 router.go:841] Success: retrieved a prometheus config file from: http://cost-analyzer-prometheus-server.cost-analyzer
I0225 17:31:39.246313       1 router.go:847] Success: retrieved the 'up' query against prometheus at: http://cost-analyzer-prometheus-server.cost-analyzer
I0225 17:31:39.248009       1 clustercache.go:84] NAMESPACE: cost-analyzer
I0225 17:31:39.248439       1 reflector.go:122] Starting reflector *v1.Node (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248466       1 reflector.go:160] Listing and watching *v1.Node from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248486       1 reflector.go:122] Starting reflector *v1.Pod (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248499       1 reflector.go:122] Starting reflector *v1.StatefulSet (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248532       1 reflector.go:122] Starting reflector *v1.PersistentVolume (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248540       1 reflector.go:160] Listing and watching *v1.StatefulSet from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248545       1 reflector.go:160] Listing and watching *v1.PersistentVolume from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248563       1 reflector.go:122] Starting reflector *v1.Namespace (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248575       1 reflector.go:160] Listing and watching *v1.Namespace from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248657       1 reflector.go:122] Starting reflector *v1.Deployment (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248672       1 reflector.go:160] Listing and watching *v1.Deployment from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248438       1 reflector.go:122] Starting reflector *v1.ConfigMap (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.250054       1 reflector.go:160] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248523       1 reflector.go:160] Listing and watching *v1.Pod from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248437       1 reflector.go:122] Starting reflector *v1.StorageClass (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.250240       1 reflector.go:160] Listing and watching *v1.StorageClass from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.248437       1 reflector.go:122] Starting reflector *v1.Service (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.250459       1 reflector.go:160] Listing and watching *v1.Service from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:31:39.448603       1 watchcontroller.go:183] Starting *v1.Node controller
I0225 17:31:39.448631       1 watchcontroller.go:183] Starting *v1.ConfigMap controller
I0225 17:31:39.448663       1 watchcontroller.go:183] Starting *v1.Pod controller
I0225 17:31:39.448666       1 watchcontroller.go:183] Starting *v1.Namespace controller
I0225 17:31:39.448673       1 watchcontroller.go:183] Starting *v1.Service controller
I0225 17:31:39.448680       1 watchcontroller.go:183] Starting *v1.StorageClass controller
I0225 17:31:39.448695       1 watchcontroller.go:183] Starting *v1.Deployment controller
I0225 17:31:39.448701       1 watchcontroller.go:183] Starting *v1.StatefulSet controller
I0225 17:31:39.448708       1 watchcontroller.go:183] Starting *v1.PersistentVolume controller
I0225 17:31:39.543172       1 provider.go:239] Unsupported provider, falling back to default
I0225 17:31:39.547184       1 router.go:882] No configs found at installtime, using existing configs: configmaps "pricing-configs" not found
I0225 17:31:39.565501       1 main.go:544] [Debug] aggregation: cache warming defaults: 2d:1m::::namespace::::weighted:false:false:true
I0225 17:31:40.270962       1 main.go:587] aggregation: warm cache: 2d
I0225 17:31:40.271037       1 main.go:544] [Debug] aggregation: cache warming defaults: 7d:1m::::namespace::::weighted:false:false:true
I0225 17:31:41.650059       1 costmodel.go:2687] [Profiler] 1.378897806s: costDataRange(163.000000h): Prom/k8s Queries: 
 - RAMAllocations took 1.039223724s
 - CPUAllocations took 1.148957993s
 - RAMUsage took 1.378720852s
I0225 17:31:41.903098       1 profiling.go:14] [Profiler] 1.63201576s: ComputeAggregateCostModel(duration=7d, offet=1m, field=namespace): compute cost data
I0225 17:31:41.944114       1 profiling.go:14] [Profiler] 1.673056839s: ComputeAggregateCostModel(duration=7d, offet=1m, field=namespace)
I0225 17:31:42.205471       1 main.go:603] aggregation: warm cache: 7d
I0225 17:31:42.205516       1 main.go:544] [Debug] aggregation: cache warming defaults: 1d:1m::::namespace::::weighted:false:false:true
I0225 17:31:42.659347       1 main.go:571] aggregation: warm cache: 1d
I0225 17:31:42.659403       1 main.go:544] [Debug] aggregation: cache warming defaults: 30d:1m::::namespace::::weighted:false:false:true
I0225 17:31:44.682944       1 costmodel.go:2687] [Profiler] 2.023401598s: costDataRange(697.000000h): Prom/k8s Queries: 
 - RAMRequests took 1.046420063s
 - GPURequests took 1.103437283s
 - CPURequests took 1.230254797s
 - PodLabels took 1.266186702s
 - CPUUsage took 1.299596976s
 - RAMAllocations took 1.799332387s
 - RAMUsage took 1.836783899s
 - CPUAllocations took 2.023046375s
I0225 17:31:45.218190       1 profiling.go:14] [Profiler] 2.558746089s: ComputeAggregateCostModel(duration=30d, offet=1m, field=namespace): compute cost data
I0225 17:31:45.314820       1 profiling.go:14] [Profiler] 2.655400808s: ComputeAggregateCostModel(duration=30d, offet=1m, field=namespace)
I0225 17:31:47.417329       1 main.go:619] aggregation: warm cache: 30d
I0225 17:36:42.659599       1 main.go:544] [Debug] aggregation: cache warming defaults: 1d:1m::::namespace::::weighted:false:false:true
I0225 17:36:43.087405       1 main.go:571] aggregation: warm cache: 1d
W0225 17:37:43.398516       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.ConfigMap ended with: too old resource version: 778937493 (778938947)
I0225 17:37:44.398773       1 reflector.go:160] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:39:40.271232       1 main.go:544] [Debug] aggregation: cache warming defaults: 2d:1m::::namespace::::weighted:false:false:true
I0225 17:39:40.920846       1 main.go:587] aggregation: warm cache: 2d
I0225 17:41:43.087657       1 main.go:544] [Debug] aggregation: cache warming defaults: 1d:1m::::namespace::::weighted:false:false:true
I0225 17:41:43.513796       1 main.go:571] aggregation: warm cache: 1d
W0225 17:44:34.538780       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.ConfigMap ended with: too old resource version: 778939319 (778941021)
I0225 17:44:35.539038       1 reflector.go:160] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:46:43.514081       1 main.go:544] [Debug] aggregation: cache warming defaults: 1d:1m::::namespace::::weighted:false:false:true
I0225 17:46:43.975926       1 main.go:571] aggregation: warm cache: 1d
I0225 17:47:40.921111       1 main.go:544] [Debug] aggregation: cache warming defaults: 2d:1m::::namespace::::weighted:false:false:true
I0225 17:47:41.514340       1 main.go:587] aggregation: warm cache: 2d
I0225 17:49:42.205688       1 main.go:544] [Debug] aggregation: cache warming defaults: 7d:1m::::namespace::::weighted:false:false:true
I0225 17:49:43.535801       1 costmodel.go:2687] [Profiler] 1.329941284s: costDataRange(163.000000h): Prom/k8s Queries: 
 - RAMAllocations took 1.045627425s
 - CPUAllocations took 1.251074223s
 - RAMUsage took 1.329432811s
I0225 17:49:43.813825       1 profiling.go:14] [Profiler] 1.608058782s: ComputeAggregateCostModel(duration=7d, offet=1m, field=namespace): compute cost data
I0225 17:49:43.853883       1 profiling.go:14] [Profiler] 1.64816273s: ComputeAggregateCostModel(duration=7d, offet=1m, field=namespace)
I0225 17:49:44.111148       1 main.go:603] aggregation: warm cache: 7d
I0225 17:51:43.976211       1 main.go:544] [Debug] aggregation: cache warming defaults: 1d:1m::::namespace::::weighted:false:false:true
I0225 17:51:44.458446       1 main.go:571] aggregation: warm cache: 1d
W0225 17:52:43.676773       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.ConfigMap ended with: too old resource version: 778941398 (778943484)
I0225 17:52:44.677000       1 reflector.go:160] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 17:55:41.514649       1 main.go:544] [Debug] aggregation: cache warming defaults: 2d:1m::::namespace::::weighted:false:false:true
I0225 17:55:42.103212       1 main.go:587] aggregation: warm cache: 2d
I0225 17:56:44.458747       1 main.go:544] [Debug] aggregation: cache warming defaults: 1d:1m::::namespace::::weighted:false:false:true
I0225 17:56:44.819869       1 main.go:571] aggregation: warm cache: 1d
I0225 18:01:44.820116       1 main.go:544] [Debug] aggregation: cache warming defaults: 1d:1m::::namespace::::weighted:false:false:true
I0225 18:01:45.237029       1 main.go:571] aggregation: warm cache: 1d
W0225 18:02:28.814035       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.ConfigMap ended with: too old resource version: 778943856 (778946427)
I0225 18:02:29.814340       1 reflector.go:160] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 18:03:42.103459       1 main.go:544] [Debug] aggregation: cache warming defaults: 2d:1m::::namespace::::weighted:false:false:true
I0225 18:03:42.714878       1 main.go:587] aggregation: warm cache: 2d
I0225 18:06:45.237304       1 main.go:544] [Debug] aggregation: cache warming defaults: 1d:1m::::namespace::::weighted:false:false:true
I0225 18:06:45.660994       1 main.go:571] aggregation: warm cache: 1d
I0225 18:07:44.111439       1 main.go:544] [Debug] aggregation: cache warming defaults: 7d:1m::::namespace::::weighted:false:false:true
I0225 18:07:45.416947       1 costmodel.go:2687] [Profiler] 1.305278784s: costDataRange(163.000000h): Prom/k8s Queries: 
 - CPUAllocations took 1.132229739s
 - RAMAllocations took 1.167580228s
 - RAMUsage took 1.304947513s
I0225 18:07:45.662192       1 profiling.go:14] [Profiler] 1.550663588s: ComputeAggregateCostModel(duration=7d, offet=1m, field=namespace): compute cost data
I0225 18:07:45.703895       1 profiling.go:14] [Profiler] 1.592398062s: ComputeAggregateCostModel(duration=7d, offet=1m, field=namespace)
I0225 18:07:45.965866       1 main.go:603] aggregation: warm cache: 7d
W0225 18:11:35.946684       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.ConfigMap ended with: too old resource version: 778946809 (778949179)
I0225 18:11:36.947044       1 reflector.go:160] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 18:11:42.715275       1 main.go:544] [Debug] aggregation: cache warming defaults: 2d:1m::::namespace::::weighted:false:false:true
I0225 18:11:43.329539       1 main.go:587] aggregation: warm cache: 2d
I0225 18:11:45.661523       1 main.go:544] [Debug] aggregation: cache warming defaults: 1d:1m::::namespace::::weighted:false:false:true
I0225 18:11:46.023176       1 main.go:571] aggregation: warm cache: 1d
I0225 18:16:46.023431       1 main.go:544] [Debug] aggregation: cache warming defaults: 1d:1m::::namespace::::weighted:false:false:true
I0225 18:16:46.384599       1 main.go:571] aggregation: warm cache: 1d
W0225 18:17:29.091013       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.ConfigMap ended with: too old resource version: 778949556 (778951268)
I0225 18:17:30.091233       1 reflector.go:160] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 18:19:43.329891       1 main.go:544] [Debug] aggregation: cache warming defaults: 2d:1m::::namespace::::weighted:false:false:true
I0225 18:19:44.023170       1 main.go:587] aggregation: warm cache: 2d
I0225 18:21:46.384955       1 main.go:544] [Debug] aggregation: cache warming defaults: 1d:1m::::namespace::::weighted:false:false:true
I0225 18:21:46.816344       1 main.go:571] aggregation: warm cache: 1d
I0225 18:25:45.966203       1 main.go:544] [Debug] aggregation: cache warming defaults: 7d:1m::::namespace::::weighted:false:false:true
I0225 18:25:47.188239       1 costmodel.go:2687] [Profiler] 1.221859145s: costDataRange(163.000000h): Prom/k8s Queries: 
 - RAMAllocations took 1.078085571s
 - CPUAllocations took 1.158030399s
 - RAMUsage took 1.21657257s
I0225 18:25:47.435108       1 profiling.go:14] [Profiler] 1.468835655s: ComputeAggregateCostModel(duration=7d, offet=1m, field=namespace): compute cost data
I0225 18:25:47.474291       1 profiling.go:14] [Profiler] 1.5080515s: ComputeAggregateCostModel(duration=7d, offet=1m, field=namespace)
I0225 18:25:47.714256       1 main.go:603] aggregation: warm cache: 7d
I0225 18:26:46.816629       1 main.go:544] [Debug] aggregation: cache warming defaults: 1d:1m::::namespace::::weighted:false:false:true
I0225 18:26:47.171549       1 main.go:571] aggregation: warm cache: 1d
W0225 18:27:13.221882       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.ConfigMap ended with: too old resource version: 778951650 (778954209)
I0225 18:27:14.222135       1 reflector.go:160] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 18:27:44.023391       1 main.go:544] [Debug] aggregation: cache warming defaults: 2d:1m::::namespace::::weighted:false:false:true
I0225 18:27:44.682402       1 main.go:587] aggregation: warm cache: 2d
I0225 18:31:47.171875       1 main.go:544] [Debug] aggregation: cache warming defaults: 1d:1m::::namespace::::weighted:false:false:true
I0225 18:31:47.550097       1 main.go:571] aggregation: warm cache: 1d
W0225 18:33:21.355494       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.ConfigMap ended with: too old resource version: 778954585 (778956067)
I0225 18:33:22.355734       1 reflector.go:160] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 18:35:44.682709       1 main.go:544] [Debug] aggregation: cache warming defaults: 2d:1m::::namespace::::weighted:false:false:true
I0225 18:35:45.326170       1 main.go:587] aggregation: warm cache: 2d
I0225 18:36:47.550279       1 main.go:544] [Debug] aggregation: cache warming defaults: 1d:1m::::namespace::::weighted:false:false:true
I0225 18:36:47.957573       1 main.go:571] aggregation: warm cache: 1d
I0225 18:39:47.417676       1 main.go:544] [Debug] aggregation: cache warming defaults: 30d:1m::::namespace::::weighted:false:false:true
I0225 18:39:49.419424       1 costmodel.go:2687] [Profiler] 2.001378916s: costDataRange(697.000000h): Prom/k8s Queries: 
 - RAMRequests took 1.02712731s
 - CPURequests took 1.073723298s
 - GPURequests took 1.156567983s
 - CPUUsage took 1.252425348s
 - PodLabels took 1.255555632s
 - RAMUsage took 1.694939901s
 - RAMAllocations took 1.787103097s
 - CPUAllocations took 2.001194572s
I0225 18:39:49.884218       1 profiling.go:14] [Profiler] 2.466323282s: ComputeAggregateCostModel(duration=30d, offet=1m, field=namespace): compute cost data
I0225 18:39:49.981558       1 profiling.go:14] [Profiler] 2.563752014s: ComputeAggregateCostModel(duration=30d, offet=1m, field=namespace)
I0225 18:39:52.036010       1 main.go:619] aggregation: warm cache: 30d
W0225 18:40:03.494883       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.ConfigMap ended with: too old resource version: 778956440 (778958075)
I0225 18:40:04.495083       1 reflector.go:160] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 18:41:47.957926       1 main.go:544] [Debug] aggregation: cache warming defaults: 1d:1m::::namespace::::weighted:false:false:true
I0225 18:41:48.368641       1 main.go:571] aggregation: warm cache: 1d
I0225 18:43:45.326411       1 main.go:544] [Debug] aggregation: cache warming defaults: 2d:1m::::namespace::::weighted:false:false:true
I0225 18:43:45.972898       1 main.go:587] aggregation: warm cache: 2d
I0225 18:43:47.714567       1 main.go:544] [Debug] aggregation: cache warming defaults: 7d:1m::::namespace::::weighted:false:false:true
I0225 18:43:48.960520       1 costmodel.go:2687] [Profiler] 1.245714607s: costDataRange(163.000000h): Prom/k8s Queries: 
 - CPUAllocations took 1.084264951s
 - RAMUsage took 1.245124064s
I0225 18:43:49.214937       1 profiling.go:14] [Profiler] 1.500281609s: ComputeAggregateCostModel(duration=7d, offet=1m, field=namespace): compute cost data
I0225 18:43:49.255267       1 profiling.go:14] [Profiler] 1.540660649s: ComputeAggregateCostModel(duration=7d, offet=1m, field=namespace)
I0225 18:43:49.593083       1 main.go:603] aggregation: warm cache: 7d
W0225 18:45:23.628279       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.ConfigMap ended with: too old resource version: 778958445 (778959695)
I0225 18:45:24.628668       1 reflector.go:160] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I0225 18:46:48.369063       1 main.go:544] [Debug] aggregation: cache warming defaults: 1d:1m::::namespace::::weighted:false:false:true
I0225 18:46:48.727707       1 main.go:571] aggregation: warm cache: 1d
>

**Comment by dwbrown2** [comment]
Thanks, nothing looks concerning in backend logs. Something is going on with your frontend. I would assume it's related to a networking issue. Just looking at your UI, it looks like something may be blocking access to our external frontend dependancies.

Can you share any errors in your browser's developer console?

**Comment by gknepper** [comment]
@dwbrown2 

Just figured out the error. Kubecost needs internet access for some resources (css,icon,js,jquery) and I was running from a jumphost without internet access. In a browser with internet access everything works. 

Sorry and thanks.

**Comment by dwbrown2** [comment]
@gknepper does https://github.com/kubecost/cost-analyzer-helm-chart/issues/301 look good to you?!

**Comment by gknepper** [comment]
@dwbrown2 Yes thanks.
