### ISSUE TITLE
Add ability to add annotations to PVC's and VolumeClaimTemplate 

### ISSUE THREAD

**Issue by Yoni-shir** [kubecost/cost-analyzer-helm-chart#2102]
**What problem are you trying to solve?**
I have a specific use case, where I want to be able to pass annotations to PVC's and volumeClaimTemplate through values (We use [ebs-tagger](https://github.com/mtougeron/k8s-pvc-tagger) in our cluster to tag pvc's for cost, and it relies on annotations). 

**Describe the solution you'd like**
The solution should be fairly simple, just add an `annotations` value under `persistentVolume` (same hierarchy as `storageClass`).

**Describe alternatives you've considered**

**How would users interact with this feature?**

**Comment by noaramon** [comment]
+1

**Comment by thomasvn** [comment]
Hi @Yoni-shir! Just to make sure I understand, you're looking for a configuration option such as [`.Values.persistentVolume.annotations`](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.101/cost-analyzer/values.yaml#L492-L498)?

**Comment by Yoni-shir** [comment]
Hi @thomasvn, thanks for the reply
Yes, exactly

**Comment by thomasvn** [comment]
Hi @Yoni-shir! I've drafted a PR for this feature request: https://github.com/kubecost/cost-analyzer-helm-chart/pull/2140

Note, that my PR will only add labels & annotations to Kubecost's PVC (i.e. `pvc/kubecost-cost-analyzer`) and not the Prometheus or Thanos PVCs.
