### ISSUE TITLE
Hide __unallocated__ line item when aggregating by a label

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#2107]
**What problem are you trying to solve?**
When aggregating by a label, we see a line item in various pages that reads __unallocated__ and there are instances where we do not want tenants or other teams to see these unallocated costs

**Describe the solution you'd like**
Want an option to hide unallocated resources when doing aggregations

**Describe alternatives you've considered**
N/A

**How would users interact with this feature?**
Provide an option to hide unallocated line item in UI post aggregation under edit reports tab like. Sort of like we can do with hiding idle costs.

**Comment by dwbrown2** [comment]
@mmurph3 would a `!=__unallocated__` filter and then saved report do the trick?

**Comment by zhiyuanhe-indeed** [comment]
@dwbrown2 That does not work on my side. Not sure if I missed anything.

**Comment by kwombach12** [comment]
@zhiyuanhe-indeed Can you help us understand why filtering to entities not equal to **unallocated** doesn't work for your use case?

**Comment by zhiyuanhe-indeed** [comment]
@kwombach12 I mean I added the filter, but `__unallocated__` row still exist.

**Comment by zhiyuanhe-indeed** [comment]
Is there any syntax on how to write a correct filter?

**Comment by kwombach12** [comment]
@zhiyuanhe-indeed We don't have != filters available for the Allocations Page today unfortunately. I'm hoping that once we add that capability, you are able to 'hide' the unallocated row

**Comment by zhiyuanhe-indeed** [comment]
Ok, thank you!
