### ISSUE TITLE
Stop Installing KSM By Default

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#2108]
**What problem are you trying to solve?**
* For backwards compatibility, opencost emits all metrics it needs to be self-sufficient
* To lower metric volume, opencost also supports retrieving a large portion of its metrics from KSM + prometheus

**Describe the solution you'd like**
Both above points point to not installing KSM by default. Either you have it and we should integrate, or you don't and we emit metrics.

**Describe alternatives you've considered**
Do Nothing

**How would users interact with this feature?**
Should be seamless!

**Comment by dwbrown2** [comment]
Are there any potential downsides / negative impacts to moving this to off by default? 

cc @kwombach12 for operability input

**Comment by AjayTripathy** [comment]
I think that not running our container uptime stats in a separate pod means that when kubecost is down, we won't be able to collect data about pod runtimes, meaning we have a higher requirement for uptime.
