### ISSUE TITLE
Fix Azure virtual nodes cost

### ISSUE THREAD

**Issue by ivankube** [kubecost/cost-analyzer-helm-chart#2109]
**Describe the bug**  
[Azure virtual node](https://learn.microsoft.com/en-us/azure/aks/virtual-nodes) cost is incorrect. 

**Reported**

**To Reproduce**  
1. Create a new AKS cluster with enable virtual nodepools
2. Check virtual node cost in Kubecost
3. Check virtual node cost in Azure

*Test Cluster*
`az aks get-credentials --resource-group ivanresourcegroup --name Ivan`

**Expected behavior**  
Kubecost displays the correct cost for Azure virtual nodes

**Screenshots**  
![Screenshot 2023-04-04 at 2 10 32 PM](https://user-images.githubusercontent.com/97049075/229881736-0bca6353-b254-4f0b-866e-adbbc92c8da6.png)
![Screenshot 2023-04-04 at 2 14 16 PM](https://user-images.githubusercontent.com/97049075/229881737-3ab030d1-136b-4c85-96b0-d90a7311f154.png)

**Please share the support case, if any**  
https://kubecost.zendesk.com/agent/tickets/3702

**Comment by AjayTripathy** [comment]
Seems simple enough to detect virtual nodes based on label and change the resource counts. Let's get this in 103.

**Comment by jessegoodier** [comment]
Please let me know if you would like to test this when ready. I have a customer wanting this as well.

**Comment by kwombach12** [comment]
Created a Jira ticket for this issues for tracking: https://kubecost.atlassian.net/browse/ELV-31
