### ISSUE TITLE
Allocation Recurring Alert is not working with filtering by label 

### ISSUE THREAD

**Issue by ivankube** [kubecost/cost-analyzer-helm-chart#2112]
**Describe the bug**  
Allocation Recurring Alert is failing when user is aggregating and  filtering by label

**To Reproduce**  
1. Create a new Allocation Recurring Alert
2. Aggregate by label(e.g. team) and filter by label(e.g. team=kubecost)
3. Click Test Alert
4. Check your email or slack - no result.
5. Check Browser's console - 500

**Expected behavior**  
Alert is working 

**Screenshots**  
![Screenshot 2023-04-04 at 3 33 05 PM](https://user-images.githubusercontent.com/97049075/229900523-b5509163-a802-46bc-8897-3ae065aac8fa.png)

**Comment by kwombach12** [comment]
@teevans @nealormsbee can you please take a look at this? I'd call it very close to a p0

**Comment by nazzzzz** [comment]
For some additional context, I get this on old and new UI, and with a variety of expressions. For example, I've tried using `team:teamname`, `team=teamname`, and just plain `teamname` as the filter value and none work.

If the filter field is left blank, and I just aggregate on the team label, the alert fires without issue.

On the old UI it just silently fails, in the new UI an error is shown that tells me to check logs, but there's nothing that I can find in the logs that explains the error. For this testing, I used kubecost version 1.101.1

**Comment by nealormsbee** [comment]
Definitely looks like a bug in our Alerts. Making a copy of this in jira for internal tracking and will sync updates here. Thanks!

**Comment by teevans** [comment]
@nealormsbee - can you post the ticket number once it's created in jira?

**Comment by nealormsbee** [comment]
Sure! It's here: https://kubecost.atlassian.net/browse/CORE-169

**Comment by kirbsauce** [comment]
@kwombach12 will this make it into 1.103?

**Comment by kwombach12** [comment]
yes! I believe @michaelmdresser has merged his PR to resolve this

**Comment by michaelmdresser** [comment]
Yes, I can confirm that this fix will make it into v1.103.

**Comment by kirbsauce** [comment]
Thanks!
