### ISSUE TITLE
draft: new "commitment recommendations"

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#2114]
still a bit of a draft here, but don't want to lose sight of this.
@srpomeroy is co-author

**What problem are you trying to solve?**

1. more agnostic savings for committed node use

2. removal of node-exporter per: https://github.com/kubecost/cost-analyzer-helm-chart/issues/2116

**Describe the solution you'd like**
Ideas discussed (open to all suggestions):
New page to potentially replace reserved-instances with "commitment recommendations" ?

Instead of node-exporter, use a calculation of the sum of request-sizing resources used (at minimum) over some period of time. Though I'm paraphrasing what I heard. @AjayTripathy I believe you have some ideas here?

**Describe alternatives you've considered**
Potentially just remove reserve-instances page, which is single-cluster only?

**How would users interact with this feature?**
Ideally have some insights into the various savings plans and recommendations with tunable assumtions?

**Comment by dwbrown2** [comment]
@jessegoodier is the ultimate goal to be able to drop NE all together? Just trying to get a sense for your ultimate vision. If I remember correctly, we actually use NE to look at system/app CPU time on machines.

**Comment by AjayTripathy** [comment]
We don't really use that data in a ton of places across the app and pay a ton of resources on Prometheus and in support costs scraping and installing node exporter-- so I do think the goal is to drop this altogether.

**Comment by dwbrown2** [comment]
@AjayTripathy @bstuder99 I know you put together a doc on exactly where NE is used. Can you share?

**Comment by jessegoodier** [comment]
We have a setup with a proxy in front of prometheus. Using this, I had a quick look and the only metric I see used is `node_cpu_seconds_total`

I will leave it to the team to determine where that is used.

For reference, here's the list of metrics emitted by node-exporter:
```
group by(__name__) ({__name__!="", component="node-exporter"})
```

https://prom.kubecost.xyz/graph?g0.expr=group%20by(__name__)%20(%7B__name__!%3D%22%22%2C%20component%3D%22node-exporter%22%7D)&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h

**Comment by brstuder** [comment]
@dwbrown2 Not sure specifically what you mean, we don't have a central node exporter article, but it's mentioned mainly here:
https://docs.kubecost.com/install-and-configure/install/custom-prom#node-exporter-metric-labels
https://docs.kubecost.com/install-and-configure/advanced-configuration/resource-consumption#disable-or-stop-scraping-node-exporter

**Comment by srpomeroy** [comment]
FWIW, the linked issue describes where the NE metrics are used.
https://github.com/kubecost/cost-analyzer-helm-chart/issues/2116

Something else of note is the current reserved instances page only recommends nodes for the primary. Any new feature, enhancement, or replacement report should work across ALL clusters in a federated setup.

**Comment by chipzoller** [comment]
Not sure how relevant or desirable this still is so I'm closing here. Feel free to re-open but please transfer to [features-bugs](https://github.com/kubecost/features-bugs/) if done, or alternatively log an internal issue.
