### ISSUE TITLE
improve /overview page load time in large environments

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#2115]
**What problem are you trying to solve?**
Overview is the first impression users get of Kubecost. This page can take significant time to load in large environments.

**Describe the solution you'd like**
IMO, the page doesn't not need to be dynamic- a daily/hourly cache (with tool tips as needed) is preferable to the perception that Kubecost is slow.

Any solution to this page load time is welcome.

**Describe alternatives you've considered**
NA

**Comment by AjayTripathy** [comment]
Caching the savings response, especially totals and the top ten containers to optimize, seems very reasonable to me. @teevans let's carve some time out in 104 or maybe as a stretch 103 goal to sprint on overview and request-sizing performance again.

**Comment by teevans** [comment]
@allyleonce - Tagging for tracking, can you get a ticket for this going in Jira for 104 bug fixes?

**Comment by allyleonce** [comment]
https://kubecost.atlassian.net/browse/ELV-27
 
done @teevans

**Comment by mmurph3** [comment]
Opened another issue that's similar here in our private repo https://github.com/kubecost/cost-analyzer-frontend/issues/1921

**Comment by jessegoodier** [comment]
related to: https://github.com/kubecost/cost-analyzer-frontend/issues/1921 
?
