### ISSUE TITLE
node-exporter: What is it good for? 

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#2116]
Relates to #2114 

Prometheus node-exporter can consume a ton of resources in a cluster. It runs as a daemonset, and Prometheus needs to scrape each daemon to gather the relevant metrics. 

We've discussed in the past the value that node-exporter provides to Kubecost.
Do we clearly understand what features are directly impacted by the existence of the [node-exporter metrics](https://docs.kubecost.com/architecture/user-metrics#node-exporter) and what we lose by disabling node-exporter with our bundled Prometheus?

We know the reservation recommendations require the metrics. Can we source that information elsewhere?

We only see one reference to node-exporter metrics in KCM, and it's a test. And only a handful in the front-end and OpenCost code base. 

- `node_cpu_seconds_total`
  - https://github.com/kubecost/kubecost-cost-model/blob/4a3ca74182815c15a437e124d81bd7131294c1a5/pkg/alerts/format/format_test.go#L370-L377
  - https://github.com/opencost/opencost/blob/d121d54be42f74e8913ad34005033d47c73087e4/pkg/costmodel/cluster.go#L575
  - https://github.com/opencost/opencost/blob/d121d54be42f74e8913ad34005033d47c73087e4/pkg/costmodel/cluster.go#L895-L897
  - https://github.com/opencost/opencost/blob/d121d54be42f74e8913ad34005033d47c73087e4/pkg/prom/diagnostics.go#L69-L75
  - https://github.com/kubecost/cost-analyzer-frontend/blob/0204226ff8adb80cf490cb1ac6611cbe314e58eb/public/helper-network.js#L1845
  - https://github.com/kubecost/cost-analyzer-frontend/blob/0204226ff8adb80cf490cb1ac6611cbe314e58eb/public/helper-network.js#L1932
  - https://github.com/kubecost/cost-analyzer-frontend/blob/0204226ff8adb80cf490cb1ac6611cbe314e58eb/public/helper.js#L1848
  - https://github.com/kubecost/cost-analyzer-frontend/blob/0204226ff8adb80cf490cb1ac6611cbe314e58eb/public/helper.js#L1935
  - https://github.com/kubecost/cost-analyzer-frontend/blob/15aeaaa68211bac276b50d62d2af876870c743ef/src/pages/Actions/ReservedInstancesNew/ReservedInstances.tsx#L55
  - https://github.com/kubecost/cost-analyzer-frontend/blob/15aeaaa68211bac276b50d62d2af876870c743ef/src/pages/Settings/settingsHelpers.ts#L15
  - https://github.com/kubecost/cost-analyzer-frontend/blob/15aeaaa68211bac276b50d62d2af876870c743ef/src/pages/Settings/ThanosCheck.tsx#L41-L45
  - https://github.com/kubecost/cost-analyzer-frontend/blob/15aeaaa68211bac276b50d62d2af876870c743ef/src/vendor/helper.js#L1847
  - https://github.com/kubecost/cost-analyzer-frontend/blob/develop/src/vendor/helper.js#L1934

- `node_memory_MemTotal_bytes` & `node_memory_MemFree_bytes` & `node_memory_Cached_bytes` & `node_memory_Buffers_bytes`
  - https://github.com/kubecost/cost-analyzer-frontend/blob/0204226ff8adb80cf490cb1ac6611cbe314e58eb/public/queries.js#L819
  - https://github.com/kubecost/cost-analyzer-frontend/blob/15aeaaa68211bac276b50d62d2af876870c743ef/src/pages/Actions/ReservedInstances/api.ts#L75
  - https://github.com/kubecost/cost-analyzer-frontend/blob/15aeaaa68211bac276b50d62d2af876870c743ef/src/pages/Actions/ReservedInstances/api.ts#L179
  - https://github.com/kubecost/cost-analyzer-frontend/blob/develop/src/pages/Actions/ReservedInstancesNew/api.ts#L75
  - https://github.com/kubecost/cost-analyzer-frontend/blob/15aeaaa68211bac276b50d62d2af876870c743ef/src/pages/Actions/ReservedInstancesNew/api.ts#L166
  - https://github.com/kubecost/cost-analyzer-frontend/blob/15aeaaa68211bac276b50d62d2af876870c743ef/src/services/helper_dump.ts#L307-L308
  - https://github.com/kubecost/cost-analyzer-frontend/blob/15aeaaa68211bac276b50d62d2af876870c743ef/src/vendor/queries.js#L832

Is the cost of running node-exporter worth the value it provides? Can we safely replace the queries that rely on node-exporter today with some different logic that would allow us to disable node-exporter going forward?

**Comment by linhlam-kc** [comment]
For additional information, I disabled node-exporter in all recent integrations such as: all AWS integrations, OpenShift Helm chart and Operator, Digital Ocean, GCP Marketplace.

**Comment by srpomeroy** [comment]
The Solutions team typically disables node-exporter during POCs as well.

**Comment by chipzoller** [comment]
Node exporter is disabled by default and this issue is stale so closing.
