### ISSUE TITLE
Typos in report YAML export

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2122]
**Describe the bug**  
When selecting "Export YAML" from the reports page, the result has some typos that misconfigure the report.

| current        | desired       |
|----------------|---------------|
| `aggregatedBy` | `aggregateBy` |
| `cloundJoin`   | `cloudJoin`   |

**To Reproduce**  
1. Create a report
2. Select "Export YAML"

**Expected behavior**  
Valid YAML is output to copy/paste into values.yaml

**Screenshots**  
<img width="721" alt="image" src="https://user-images.githubusercontent.com/43491549/230161960-a810c75a-bad0-48f7-925e-957a6307bc2b.png">

**Please share the support case, if any**  
[ZD-3756](https://kubecost.zendesk.com/agent/tickets/3756)

**What impact will this have on your ability to get value out of Kubecost?**
Ability to export reports as YAML

**Comment by keithhand** [comment]
[I believe] the relevant frontend code is here: https://github.com/kubecost/cost-analyzer-frontend/blob/67fb890aca4b65f8983148d10ce973f6ef6b6d08/src/pages/ReportsNew/ReportExport.tsx#L81-L119

**Comment by AjayTripathy** [comment]
@nealormsbee can you help triage?

**Comment by nealormsbee** [comment]
PR here: https://github.com/kubecost/cost-analyzer-frontend/pull/1915

**Comment by nealormsbee** [comment]
Thanks for the flag @keithhand !
