### ISSUE TITLE
Update node count on diagnostics page to use 30d window

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#2123]
**What problem are you trying to solve?**
Gather the max and average node count for all connected clusters.

**Describe the solution you'd like**
[The diagnostic page currently shows max/average node count over a 7d window.](https://github.com/kubecost/kubecost-frontend/blob/96905991cdb9a13eff29ed2dc9f6c6fbba2cee91/apps/cost-analyzer-on-prem/src/services/diagnostics.ts#L273)
We want to use a 30d window to assist our licensing model better.

**Describe alternatives you've considered**
Manual queries against Prometheus data or ETL data via API.

**How would users interact with this feature?**
Kubecost UI > Settings > Diagnostics > "App Info" section

**Comment by chipzoller** [comment]
Closing, stale. Kubecost no longer licenses by nodes.
