### ISSUE TITLE
Label names on allocation aggregation

### ISSUE THREAD

**Issue by fgiannetti** [kubecost/cost-analyzer-helm-chart#2124]
Hello all!
When I was using Kubecost version 1.96.0, the response JSON of the allocation API showed the label names in the name of the object.
Example:
``` 
curl 'http://my-kubecost:9090/model/allocation?aggregate=label:service,label:environment,&window=2023-04-05T10:00:00Z,2023-04-05T11:00:00Z&shareTenancyCosts=false&accumulate=false&filterLabels=service:my-service,'
```

The resulting JSON:
```
{
    "code": 200,
    "data": [
        {
            "service=my-service/environment=prod": {
                "name": "service=my-service/environment=prod",
                "properties": {
                    ...
                    ...
```
Every object in the 'data' array, includes the label names in the key an the name _service=my-service/environment=prod_

Recently I upgrade my Kubecost to version 1.101.3 and the same request generates this response:
```
{
    "code": 200,
    "data": [
        {
            "my-service/prod": {
                "name": "my-service/prod",
                "properties": {
                    ...
                    ...
```

The key/names do not include the label names, just the values.

My question is: Is this a change corresponding to the new version api? (In which case the Allocation API should be updated)
Or can It be configured to maintain backwards compatibility?

Thank you in advance!!

**Comment by thomasvn** [comment]
Hi @fgiannetti! Thanks for pointing this out. I do believe that this was a result of a change made to the Allocation API. Is this something that you are able to build a workaround for? What's the level of impact to your existing code/automation?

@kwombach12, @Adam-Stack-PM . Do either of you know when this change may have been made. Or who may know the details? Specifically, this is the change in the Allocation API Results:

```
# v1.96
"name": "service=my-service/environment=prod"

# v1.101.3
"name": "my-service/prod"
```

**Comment by kwombach12** [comment]
Im not sure. @teevans is this something we did consciously?

**Comment by teevans** [comment]
Almost certainly. @michaelmdresser or @Sean-Holcomb do you have context on when this switch happened?

**Comment by fgiannetti** [comment]
Hey @thomasvn thank you very much for your answer.
I asked the question basically to find out if there is a specific setting for this in the new version and not to touch my code. 
I can make the workaround, that is not a issue, but I wanted to be sure if this change was a missconfiguration from my side ;)

**Comment by michaelmdresser** [comment]
@teevans IIRC some time in the past month or two there was a PR that changed this. I remember looking at it, but I don't remember who wrote it.

**Comment by Adam-Stack-PM** [comment]
@allyleonce for tracking.

**Comment by chipzoller** [comment]
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.
