### ISSUE TITLE
Wildcard v2 filters aren't working in the Request Sizing API

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2126]
**Describe the bug**  
I can't get wildcards to filter when using the Request Sizing API. I might be misconfiguring the filter, but after applying a wildcard, I get the following response from the API:

> Recommending requests from data: CPU algorithm set to max but no max data is available

I tried to change the algorithm to percentile for testing but got a similar issue.

> Recommending requests from data: CPU algorithm set to quantile but no quantile data is available

**To Reproduce**  
1. Go to [`/request-sizing`](https://demo.kubecost.xyz/request-sizing?filter=W10%3D)
2. [Filter](https://demo.kubecost.xyz/request-sizing?filter=W3sicHJvcGVydHkiOiJsYWJlbFthcHBdIiwidmFsdWUiOiJjb3N0KiIsImVxdWFsaXR5IjoiOiJ9XQ%3D%3D&window=7d&page=0&itemsPerPage=10&algorithmCPU=max&algorithmRAM=max&qCPU=0.95&qRAM=0.95&targetCPUUtilization=0.8&targetRAMUtilization=0.8&profile=custom) for a valid label using a wildcard
3. See the error in the [API request](https://demo.kubecost.xyz/request-sizing?filter=W3sicHJvcGVydHkiOiJsYWJlbFthcHBdIiwidmFsdWUiOiJjb3N0KiIsImVxdWFsaXR5IjoiOiJ9XQ%3D%3D&window=7d&page=0&itemsPerPage=10&algorithmCPU=max&algorithmRAM=max&qCPU=0.95&qRAM=0.95&targetCPUUtilization=0.8&targetRAMUtilization=0.8&profile=custom)

**Expected behavior**  
Values are filtered based on the wildcard label provided, similar to how the [allocation report](https://demo.kubecost.xyz/allocations?filters=W3sicHJvcGVydHkiOiJsYWJlbCIsInZhbHVlIjoiYXBwOmNvc3QqIn1d&agg=container) filters work (both should be v2, I believe).

**What impact will this have on your ability to get value out of Kubecost?**
The ability to filter for aggregates with all or no labels set. For example, if I want to query for all pods that don't have an `app` label, I would like to use the filter `label[app]!:*`.

**Comment by mmurph3** [comment]
Any update on this? 

cc @kwombach12

**Comment by kwombach12** [comment]
@michaelmdresser Do we support wildcard filters today and they are just missing from request sizing?

**Comment by srpomeroy** [comment]
Missing from docs as well if currently supported.
https://docs.kubecost.com/apis/apis-overview/filters-api

**Comment by michaelmdresser** [comment]
Wildcards are not currently supported in v2 filters. We're currently aiming to add that support in v1.105 of Kubecost.

**Comment by chipzoller** [comment]
Closing, appears resolved.
