### ISSUE TITLE
feature: add csv export to /request-sizing

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#2129]
sorry if this is a dupe, I did a quick search.

**What problem are you trying to solve?**
Add button to download CSV on request sizing page 

**Describe the solution you'd like**
similar to : https://github.com/kubecost/cost-analyzer-frontend/pull/1908

@jjarrett21 @nealormsbee nice work on that PR, you are my inspiration. 🥇 

**Describe alternatives you've considered**
Get json output from inspect on browser.

**How would users interact with this feature?**
button on /request-sizing

**Comment by jessegoodier** [comment]
I should add, this has been mentioned by a few customers- I just failed to log this previously.

**Comment by nealormsbee** [comment]
I don't think we have another ticket for this, and dupes are better than dropping things anyway 😄

**Comment by nealormsbee** [comment]
@kwombach12 I know we have an issue for CSV exporting orphaned-resources on the burndown for 103. Going to make a ticket for this one too.

**Comment by thomasvn** [comment]
@nealormsbee @kwombach12 Any updates on this one? Did it make it into v1.103?

**Comment by kwombach12** [comment]
It did not make 103, we will try to get this in 104

**Comment by KadiyalaPrasanti** [comment]
Hi Team,

We are using Enterprise version of KubeCost to charge back our tenants of our AKS clusters. It would be a critical feature for us to share the trend with App teams to help them with tuning the resources. Could you please prioritize and plan for the next release.

**Comment by kwombach12** [comment]
@KadiyalaPrasanti We are definitely looking at this for next release. Can you share a little more about your use case? I'd love to learn how you guys use the request right-sizing page to look at trends and do charge back. Is there something you get from this page that you don't get from the allocations page?

**Comment by jessegoodier** [comment]
This was added in 1.104!
