### ISSUE TITLE
Ability to create a Bin-Packing style report

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2131]
**What problem are you trying to solve?**
I am trying to create a report that measures the level of Node efficiency for a cluster based on workload usage ([bin packing](https://cloud.google.com/blog/products/containers-kubernetes/gke-best-practices-to-lessen-over-provisioning)). To do this, I can use the allocation report today and [aggregate by Node](https://demo.kubecost.xyz/allocations?filters=W10%3D&context=W10%3D&agg=node); however, this will include various other costs like Load Balancers and Disks. I want to be able to create a report in the UI that contains only the relevant information.

**Describe the solution you'd like**
I propose adding a new allocation API filter allowing you to filter for asset types to see only the workload allocation data associated with those assets.

**Describe alternatives you've considered**
Create a report using the allocation API and another data visualization tool containing only relevant pricing information.

**How would users interact with this feature?**
New filter type in the allocation API.

**Comment by kwombach12** [comment]
This is something we are looking to handle with a new version of advanced reports! We are prototyping this out in 103 and would love to get your feedback on it!
