### ISSUE TITLE
Saved Allocation report is not honoring step size

### ISSUE THREAD

**Issue by ivankube** [kubecost/cost-analyzer-helm-chart#2132]
**Describe the bug**  
Report does not have saved step size

**To Reproduce**  
1. Set Step Size to Daily on Allocation pate
2. Save the Report
3. Open Report and see that Step Size is Default

**Expected behavior**  
Report should have saved Step Size

**Screenshots**
Set Daily Step Size:  
<img width="1322" alt="Screenshot 2023-04-07 at 5 59 57 PM" src="https://user-images.githubusercontent.com/97049075/230684227-3c9ae00c-9c1d-4139-98ee-e275fedb635f.png">
Open Saved Report:
<img width="1322" alt="Screenshot 2023-04-07 at 6 00 28 PM" src="https://user-images.githubusercontent.com/97049075/230684286-23f877e8-042f-4223-a3ce-953c1e5f8262.png">

**Please share the support case, if any**  
https://kubecost.zendesk.com/agent/tickets/3819

**Reproduced**
[Report](https://demo.kubecost.xyz/allocations?title=Cumulative+cost+for+last+48h+by+namespace&window=48h&agg=namespace&idle=separate&rate=cumulative&chartDisplay=series&filters=W10%3D&sharedOverhead=0)

**Comment by kwombach12** [comment]
Thanks @ivankube we will fix this during 103. Here is a Jira ticket to track the progress: https://kubecost.atlassian.net/browse/EV-105

**Comment by ivankube** [comment]
@kwombach12 do we have an ETA for this issue?

**Comment by kwombach12** [comment]
@ivankube We will try to pick this up in 104.

**Comment by mmurph3** [comment]
@kwombach12 did this make v1.104?

**Comment by kwombach12** [comment]
Yes. Its should be resolved in 104

**Comment by chipzoller** [comment]
Closing, appears resolved.
