### ISSUE TITLE
UI issue adding AWS cloud integration: athenaDatabase must be a `object` type

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#2135]
**Describe the bug**  

Reported by a customer:
When adding a cloud integration from the UI:

```
athenaDatabase must be a `object` type, but the final value was: `null` (cast from the value `"athenacfn"`). If "null" is intended as an empty value be sure to mark the schema as `.nullable()`
```
![image](https://user-images.githubusercontent.com/31039225/231163260-2eb59d25-9ab4-4564-ad68-b76022dcc181.png)

**To Reproduce**  
1. Go to 'settings'
2. add aws cloud provider
3. See error

**Expected behavior**  
allow text input

**Comment by AjayTripathy** [comment]
@nealormsbee is this happening on the FE or BE? Looks like a react error?

**Comment by teevans** [comment]
Tagging @jjarrett21 - I believe he worked on this form

**Comment by zapr-16** [comment]
since this one is closed, what version will the fix be released on?

**Comment by kwombach12** [comment]
@zapr-16 this should be available in the 103 release going out this week! Please feel free to reopen and follow up with any issues!
