### ISSUE TITLE
Monitor -> Assets: failed to load asset data when Unaggregated

### ISSUE THREAD

**Issue by patrick-tavares** [kubecost/cost-analyzer-helm-chart#2137]
**Describe the bug**  
Kubecost UI is returning a "Failed to load asset data" error message when trying to view Assets with `aggregation` settings set to `Unaggregated`

**To Reproduce**  
1) Login to Kubecost UI.
2) Click `Monitor` and then `Assets` from the left nav menu.
3) Click the Aggregation settings button and choose `Unaggregated`
4) View error

**Expected behavior**  
Asset information should be displayed without any specific aggregation.

**Screenshots**  
![Screenshot from 2023-04-11 10-00-28](https://user-images.githubusercontent.com/30978122/231206918-766430b6-2d51-420d-9d58-d09341d14322.png)

![Screenshot from 2023-04-11 10-09-40](https://user-images.githubusercontent.com/30978122/231207346-543ed965-5b81-44b7-a707-32bcbd31176f.png)

**Collect logs (please complete the following information):**
![Screenshot from 2023-04-11 10-11-04](https://user-images.githubusercontent.com/30978122/231207670-d8e27b73-7dd9-4215-80ec-3ee752be9717.png)

**Comment by dwbrown2** [comment]
Thanks for reporting, @patrick-tavares! Have a build where this reproduced? I'm not seeing on nightly: http://nightly.kubecost.io:9090/assets?agg=unaggregated&context=W10%3D

I would call this P0/1 if it's happening often.

cc @allyleonce @kwombach12

**Comment by patrick-tavares** [comment]
@dwbrown2 : https://demo.kubecost.xyz/

I had pinged @mmurph3 about this yesterday but didn't get around to submitting the issue until today. It's possible he already addressed it in the last nightly.

**Comment by kwombach12** [comment]
hmmm this is strange, I am unable to repro this in any of my builds. @patrick-tavares is the xyz build running 1.102.1? @teevans Any thoughts on why this could be happening on this specific build?
