### ISSUE TITLE
Cloud Costs Line Items Showing as clickable links that do nothing

### ISSUE THREAD

**Issue by patrick-tavares** [kubecost/cost-analyzer-helm-chart#2139]
**Describe the bug**  
When navigating to _Monitor -> Cloud Costs_ from the left nav in the UI, the resulting cost line items appear as plain text initially. However, if you click on _Cloud Costs_ again, the line items are all turned into clickable links that don't do anything.

**To Reproduce**  
1. Login to the Kubecost UI
2. Click on _Monitor -> Cloud Costs_ from the left nav 
3. Notice the resulting line items are not clickable links
4. Click _Monitor -> Cloud Costs_ from the left nav again.
5. Notice the resulting line items become clickable links that do nothing when clicked.

**Expected behavior**  
Either the line items never become clickable links or they always are clickable links to views with more detail.

**Screenshots**  
![Screencast from 2023-04-11 13-09-22](https://user-images.githubusercontent.com/30978122/231253839-e90964d5-4d20-4d74-a497-91490c8a76a0.gif)

**Comment by kwombach12** [comment]
@patrick-tavares these will be clickable in 103!

**Comment by dwbrown2** [comment]
This is a strange experience though! Thanks for reporting.

@kwombach12 are we expecting nightly to have drilldown this week for @patrick-tavares to check out?

**Comment by kwombach12** [comment]
That is currently the plan, yes!
