### ISSUE TITLE
Enhance notifications with identifying information

### ISSUE THREAD

**Issue by ausmith** [kubecost/cost-analyzer-helm-chart#2141]
**What problem are you trying to solve?**
When receiving a notification from the Kubecost product, it lacks identifying information to aid in determining which instance is impacted. This is not necessary in environments with only a single Kubecost instance, but becomes useful information with more than one. Example output from one of these messages today:

> **[Kubecost Diagnostic] Prometheus Metrics Status**
> Kubecost relies on specific metrics collected by Prometheus to determine the cost of your cluster.
> The status of the metric diagnostics have changed:
> :x:  **Failing**
> **cAdvisor metrics available**
> _Determine if cAdvisor metrics are available during last 5 minutes._
> ```Query:   absent_over_time(container_cpu_usage_seconds_total[5m] )```
> :x:  **Failing**
> **Expected cAdvisor labels available**
> _Determine if expected cAdvisor labels are present during last 5 minutes._
> ```Query:   absent_over_time(container_cpu_usage_seconds_total{container!="",pod!=""}[5m] )```
> :x:  **Failing**
> **Node-exporter metrics available**
> _Determine if metrics from node-exporter are available during last 5 minutes._
> ```Query:   absent_over_time(node_cpu_seconds_total[5m] )```

**Describe the solution you'd like**
An indicator of what cluster this Kubecost instance is in (e.g. control plane domain) or endpoint it responds to (e.g. ingress domain) would be potentially helpful for tracking down which cluster sent this information. A link to the Kubecost instance as a call to action could also be useful, assuming the instance is operational.

**Describe alternatives you've considered**
Indicating just the namespace would be insufficient information if one has Kubecost instances deployed in multiple kube clusters under the same namespace.

**How would users interact with this feature?**
From Slack, MS Teams, Email, and anywhere else that is supported in the future for sending notifications.

**Comment by dwbrown2** [comment]
+1, @kwombach12 can you help prioritize?

**Comment by kwombach12** [comment]
Sure! @teevans is this something quick we can tackle during testing week?

**Comment by teevans** [comment]
Potentially - Will need @avrodrigues5 to weigh in. But let's get it on the burndown list and see what we can do.

**Comment by kwombach12** [comment]
Already there!

**Comment by nealormsbee** [comment]
This is a common-sense enhancement and would be super nice. The lift is nontrivial and this release is already hot. I would vote to consider this in 104. Thoughts @kwombach12 @dwbrown2 ?

**Comment by kwombach12** [comment]
@nealormsbee I agree on the value - good to hear its a quick lift. I'll leave it on the burndown so that we can pickup if we have additional bandwidth in 104

**Comment by nealormsbee** [comment]
:joy: _non-trivial_ lift. It's not huge but I wouldn't call it super quick either, just to be clear.

**Comment by kwombach12** [comment]
lol reading is hard - my bad.

**Comment by chipzoller** [comment]
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.
