### ISSUE TITLE
Cluster Inspect `Zone(s)` should be `Region`

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#2144]
**Describe the bug**  
When viewing the new [cluster inspect page](https://demo.kubecost.xyz/cluster-inspect?clusterId=kc-demo-prod&cloudId=kc-demo-prod), I noticed the `Zone(s):` field reflects the `Region` of my AWS EKS cluster.

**To Reproduce**  
1. Go to [Cluster Inspect](https://demo.kubecost.xyz/cluster-inspect?clusterId=kc-demo-prod&cloudId=kc-demo-prod)
2. Observe `Zone(s)` field displaying `us-west-2` instead of `us-west-2c,us-west-2d,us-west-2b`.

**Expected behavior**  
If the field is meant to be `Zone(s)`, then the value should be updated to reflect the actual zone(s) the nodes reside in.
If the field is meant to be `Region`, then the field name should be updated to the same.

Alternatively, consider this a feature request to show Region and Zone fields separately. 😛

Kubernetes has defined the following labels for [region](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesioregion) and [zone](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesioregion), respectively:
`topology.kubernetes.io/region`
`topology.kubernetes.io/zone`

The following examples were generated using the following command:
``` shell
kubectl get nodes -o custom-columns="NODE":".metadata.name","REGION":".metadata.labels.topology\.kubernetes\.io/region","ZONE":".metadata.labels.topology\.kubernetes\.io/zone"
```

AWS:
```
NODE                                           REGION      ZONE
ip-192-168-1-62.us-west-2.compute.internal     us-west-2   us-west-2b
ip-192-168-60-124.us-west-2.compute.internal   us-west-2   us-west-2c
ip-192-168-95-55.us-west-2.compute.internal    us-west-2   us-west-2d
```

Azure:
```
NODE                                REGION   ZONE
aks-agentpool-81479558-vmss000001   eastus   eastus-2
```

GCP:
```
NODE                                     REGION        ZONE
gke-kc-demo-stage-pool-2-70aa2479-k41y   us-central1   us-central1-c
gke-kc-demo-stage-pool-2-70aa2479-mfhe   us-central1   us-central1-c
```

**Screenshots**  
![image](https://user-images.githubusercontent.com/15660532/231635557-8c3f110d-9c30-4c5c-98c7-c7218ca57139.png)

**Please share the support case, if any**  
[Originally raised in Slack.](https://kubecost.slack.com/archives/G01MN4R06MB/p1678722517940519)

**What impact will this have on your ability to get value out of Kubecost?**
Not as much as something like a cost discrepancy, but still more than none.

**Comment by srpomeroy** [comment]
@kwombach12 Got room in 1.105/1.106? I'm hoping this is a simple change. I'm not sure if it's currently WAI.

**Comment by srpomeroy** [comment]
Also manifests in the assets view.
<img width="1144" alt="image" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/15660532/b716ce6c-cc3f-4c2d-aec9-8d12c96a0904">

**Comment by kwombach12** [comment]
@srpomeroy Thanks for logging this. The data presented is what I expected... The heading should be Region instead of Zone as you pointed out. I will file a ticket to update and it should be quick enough to resolve in 105

**Comment by srpomeroy** [comment]
This looks to be resolved in the cluster inspect view now.

It still reflects the zone in the assets view, though I wonder if that is WAI.
As it is unrelated to this issue, I am closing it as complete and will raise a separate one in JIRA.
