### ISSUE TITLE
Network Allocation details erroring out on large datasets

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2147]
**Describe the bug**  
When trying to view Network Allocation information, it will sometimes appear on the Overview page; however, when you try to drill into the details, you get a response that there is a "No network data" error. Upon investigating the user's HAR file of this page load, it looks like the allocation response is getting "chunked" but never "un-chunked," causing no data as far as the front end is concerned. They could directly make the same allocation queries that appear to be returning no results in the HAR, and when they did so in their browser, the response would load, albeit slowly. Reducing the query window or selecting a namespace with fewer overall allocation metrics resolves the issue and allows the page to load. We checked container usage/requests, and it doesn't seem like the container is running into any CPU limits that would indicate throttling, and the pod had no OOM restarts to show us hitting node RAM limits.

**To Reproduce**  
1. Go to the Overview page
2. Select the "Network Costs >" link in the "Network Costs Breakdown" section
3. Wait for the page to load and eventually see the error.

**Expected behavior**  
Scraped network data is shown on the details page, regardless of how large a query is made.

**Screenshots**  
![image](https://user-images.githubusercontent.com/43491549/231852485-88565b7a-d812-4b83-acaa-9d29d0015f23.png)
![image](https://user-images.githubusercontent.com/43491549/231854060-430d57d1-d229-479f-bd78-d4886d74d04a.png)

**Please share the support case, if any**  
More info (including HAR dump) in the [Zendesk Ticket](https://kubecost.zendesk.com/agent/tickets/3683)

**What impact will this have on your ability to get value out of Kubecost?**
The ability to use the Network Details page on any size cluster.

**Comment by kwombach12** [comment]
Thanks @keithhand Ill add this bug to our 103 burndown.

**Comment by keithhand** [comment]
@kwombach12, I'm not entirely sure if it's the network data itself or the raw allocation data. The query that seems to be returning the chunked data is: `/model/allocation?window=7d&aggregateBy=namespace%2Cpod&accumulate=true&shareIdle=true`

**Comment by mmurph3** [comment]
@kwombach12 any update on this? Do you or the team need more context?

**Comment by kwombach12** [comment]
I dont think we need more context - I think this is a pretty heavy bug that we are trying to knock off our burndown

**Comment by kwombach12** [comment]
I dont think we need more context - I think this is a pretty heavy bug that we are trying to knock off our burndown

**Comment by chipzoller** [comment]
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.
