### ISSUE TITLE
Frontend CSS bug

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#2148]
A customer has reported this CSS bug on the overview page in `v1.102` while using Chrome. I was not able to reproduce it on any test clusters, however in speaking with @wolfeaustin he asked that I submit a bug report.

**Screenshots**  

[overview-css.webm](https://user-images.githubusercontent.com/17748044/231880575-9da05413-e133-4390-82b1-c683af848dc7.webm)

**Comment by kwombach12** [comment]
I'll file a ticket for us to tackle this during testing week, but if we aren't able to repro, we wont know if we fix the issue

**Comment by kirbsauce** [comment]
not sure i'm stating the obvious, but when the tooltip appears it enables the horizontal scrollbar.

**Comment by kwombach12** [comment]
Yea our tooltips are expanding the screen width which I find irritating. We should be popping those tooltips off to the left instead of expanding the screen right which is why I consider this a bug.

**Comment by jcharcalla** [comment]
Tool tips go off the page when I try reproducing with Chrome... Probably still not the best solution either. Resizing could be a difference in browser/os.

<img width="1109" alt="Screenshot 2023-04-14 at 2 48 03 PM" src="https://user-images.githubusercontent.com/17748044/232131146-90aa0c65-de73-4009-912d-f4055aa60c7d.png">

**Comment by kwombach12** [comment]
Right - we should have the tooltip pop out to the left of the 'i' so that it doesnt run off the page or require resizing
