### ISSUE TITLE
Add Network Cost support for Alibaba Cloud

### ISSUE THREAD

**Issue by ivankube** [kubecost/cost-analyzer-helm-chart#2151]
**What problem are you trying to solve?**
We don't support Network Costs on Alibaba Cloud yet.

**Describe the solution you'd like**
Users will have an ability to add Network Costs on Alibaba Cloud

**How would users interact with this feature?**
https://docs.kubecost.com/install-and-configure/advanced-configuration/network-costs-configuration

**Comment by dwbrown2** [comment]
Can we clarify what happens if you currently install on Alibaba? I'm guessing the daemonset deploys but just provides estimates?

**Comment by ivankube** [comment]
Users can enable Network costs but they are 0s:

![1fva81lgdebxfa-image](https://user-images.githubusercontent.com/97049075/232105740-4df6cc59-bd73-422d-9814-4febb304aaef.png)

![1fva81lgde9039-image](https://user-images.githubusercontent.com/97049075/232105670-626fcc4c-769a-424d-b1ef-7f28ca7958ee.png)

**Comment by AjayTripathy** [comment]
That's somewhat surprising, is it possible we don't have access to the hostnetwork on this cluster? @avrodrigues5 do we still have an alibaba cluster where we can try this?

**Comment by avrodrigues5** [comment]
@AjayTripathy , yes Ajay we have one we can try this on!

**Comment by mbolt35** [comment]
@avrodrigues5 You can port-forward to any of the daemonset pods on port `3001` and hit the `/status` endpoint. You can also check `/metrics` to see if it's not emitting metrics.

**Comment by mbolt35** [comment]
This is not _that_ surprising, conntrack is sort of a legacy linux netfilter implementation that is slowly being phased out. Azure required us use a completely different approach to retrieving conntrack data. We do still have the syscall approach we can try if for some reason the `nf_conntrack` file and `conntrack -L` fail. There's also an iptable allow rule that some kernels require you enable to access conntrack data.

**Comment by mbolt35** [comment]
@AjayTripathy @dwbrown2 Just updating you guys, @avrodrigues5 and I investigated this on a live cluster and the network-costs pods are reporting metrics as expected, and prometheus is collecting them as expected. The issue was that opencost had $0 accross the board for the pricing of network costs:

https://github.com/opencost/opencost/blob/1d94c1be0da97ba17ae66652151a75c144da0268/pkg/cloud/aliyunprovider.go#L548-L554

Should be a relatively simple fix to at least configure the basic costs.

**Comment by dwbrown2** [comment]
Nice, is there a notion of adding a "default" price for these for other unknown providers or on-prem environments?

**Comment by avrodrigues5** [comment]
I believe custompricing has the code https://github.com/opencost/opencost/blob/develop/pkg/cloud/customprovider.go#L246-L268 so mostly it will show default pricing for an unknown provider. 

This is top priority after my feature work is complete this week. 

Side note: I will also edit this [doc](https://docs.google.com/document/d/1JVPCeQmvGU88aw0bJJjtTzdl5RhhOqT7FPs2szuHBkc/edit) to make sure next person adding new provider adds the default Network and LB pricing.

**Comment by avrodrigues5** [comment]
PR merged @ivankube! Closing the issue LMK otherwise
