### ISSUE TITLE
Add filterDeployments parameter to /model/allocation API endpoint

### ISSUE THREAD

**Issue by mclean0328** [kubecost/cost-analyzer-helm-chart#2155]
**What problem are you trying to solve?**
Using the /model/allocation endpoint, I would like to be able to pass a filterDeployments parameter with a specific Deployment name to receive a response with just information related to said Deployment.

**Describe the solution you'd like**
Add filterDeployments parameter to /model/allocation API endpoint.

**Describe alternatives you've considered**
N/A

**How would users interact with this feature?**
The /model/allocation REST API Endpoint

**Comment by kwombach12** [comment]
@nealormsbee @teevans is there a reason we dont have the ability to filter by deployments in allocations? Was it something we just missed?

**Comment by thomasvn** [comment]
@mclean0328 I believe the `filterControllers` parameter would work here:

```
/model/allocation?window=1d&filterControllers=kubecost-cost-analyzer
```

**Comment by mclean0328** [comment]
@thomasvn I believe you are right! Thank you for pointing this out!

**Comment by mclean0328** [comment]
@thomasvn I think the issue here is that filterControllers will filter over all controllers.  So if for example there is a deployment and a statefulset with the same name, they would get different controllers with the same name instead of just deployments with that name.

**Comment by thomasvn** [comment]
@mclean0328 Would this work?

```
/model/allocation?window=1d&filterControllerKinds=deployment&filterControllers=kubecost-cost-analyzer
```

**Comment by mclean0328** [comment]
Yes and that was already suggested.  The desire is to be able to filter to a specific deployment only using one parameter.

**Comment by nealormsbee** [comment]
```
/model/allocation?window=1d&filterControllers=deployment%3Akubecost-cost-analyzer
```

EDIT: @mclean0328 you can achieve what you're asking with the above. `filterControllers` supports a `<controllerKind>:<controllerName>` syntax. So you can specify a particular deployment with a single parameter. Does that help?

**Comment by chipzoller** [comment]
Closing, appears complete. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.
