### ISSUE TITLE
CrashLoopBackOff on ARM64 cluster

### ISSUE THREAD

**Issue by mmesnjak** [kubecost/cost-analyzer-helm-chart#2158]
I got an invite by mail and I tried deploying kubecost-cloud on my little free test cluster on the Oracle Cloud with the following command:
`helm upgrade --install kubecost-cloud \
--repo https://kubecost.github.io/cost-analyzer/ cost-analyzer \
--namespace kubecost-cloud --create-namespace \
-f https://raw.githubusercontent.com/kubecost/cost-analyzer-helm-chart/develop/cost-analyzer/values-cloud-agent.yaml  \
--set imageVersion="lunar-sandwich.v0.0.11" \
--set cloudAgentKey="<here goes the key>" \
--set cloudAgentClusterId="oracle-free-1" \
--set cloudReportingServer="collector.app.kubecost.com:31356" \
--set networkCosts.enabled=true`

It is a 2 ARM64 node instance kubernetes cluster, and I get `CrashLoopBackOff` for the `kubecost-cloud-cloud-agent` pod.

I am not sure how to debug what is the root cause for the error...

**Comment by kwombach12** [comment]
cc: @ausmith for triage. I have logged the bug: https://kubecost.atlassian.net/browse/CLOUD-179?search_id=8baefe5c-cd45-4c36-83e3-2eae9e906505

**Comment by teevans** [comment]
@mmesnjak - Apologies! We're currently building a multi-arch image right now, will have an update for you soon!

**Comment by teevans** [comment]
@mmesnjak - The ARM agent should now be available! Feel free to uninstall and re-install the agent!
