### ISSUE TITLE
/Overview Possible Savings does not match /Savings Summary

### ISSUE THREAD

**Issue by kc-adawson** [kubecost/cost-analyzer-helm-chart#2160]
**Describe the bug**  

The overview savings report number does not match with the summary from the savings report.

**To Reproduce**  

On /Overview, click View Report under Savings. Then compare the number to the savings summary.

**Expected behavior**  
The expected behavior would be consistency across these 2 summary numbers.

**Screenshots** 

![Kapture 2023-04-18 at 16 16 34](https://user-images.githubusercontent.com/101200254/232895606-045aa6af-43c5-4d90-812a-9d25aee42d72.gif)

**Comment by kwombach12** [comment]
@kc-adawson can you share where you are seeing this please? Which version are you running?

**Comment by kc-adawson** [comment]
HI, @kwombach12 apologies! Version 1.102.2 on https://demo.kubecost.xyz/overview - You can see the video in the GIF above, or just click that link and then click on "View Savings" on the overview and you'll see the mismatch.

**Comment by kwombach12** [comment]
Thanks @kc-adawson I will file a bug for the team to look at this. I would consider a P0 issue.
