### ISSUE TITLE
Improve Export to PDF - "Print" the report with graph and styling

### ISSUE THREAD

**Issue by kc-adawson** [kubecost/cost-analyzer-helm-chart#2161]
**What problem are you trying to solve?**

The latest reporting graphs in 1.102.2 look amazing, but when I export them to PDF I lose the nice formatting and graph.

![image](https://user-images.githubusercontent.com/101200254/232910076-0905188e-72dc-4845-9632-e8c53a957886.png)

Users can "Print" using their browser and get the full graph, but it would be really handy to be able to export the fully styled graph in the proper format, without the left-side navigation.

![image](https://user-images.githubusercontent.com/101200254/232910308-4e2b1783-5910-40f7-aa11-dff6aa81a401.png)

Is it possible to change the export to PDF so that it exports an exact copy of Kubecost including graph?

**Comment by kc-creynold** [comment]
if possible, add a legend or some type of color association between the aggregate and the colors on the bar chart

**Comment by kwombach12** [comment]
+1 I am a fan of adding the graphs to the .pdf reports we provide. I agree with @kc-creynold that to do so, would require a legend.
