### ISSUE TITLE
New Chart Type Request - Cost Over Time (Line Graph) 

### ISSUE THREAD

**Issue by kc-adawson** [kubecost/cost-analyzer-helm-chart#2162]
**What problem are you trying to solve?**
When looking at costs over time, sometimes costs fluctuate and are hard to track on a Stacked Bar graph. 

**Describe the solution you'd like**
Kubecost should offer a Cost Over Time - Line graph option, using the existing format we use for "Efficiency Over Time", which is a line graph over time precisely like I'm describing. 

**Describe alternatives you've considered**
Line graphs can be built in Grafana but this takes a lot of extra effort and should also be offered via the UI.

**How would users interact with this feature?**

![image](https://user-images.githubusercontent.com/101200254/233133812-2bf2aadf-1a46-408c-b302-21d09b55b6f6.png)

![image](https://user-images.githubusercontent.com/101200254/233133897-0399476f-fce2-4566-b0e0-926a92afdc8c.png)

**Comment by kwombach12** [comment]
@kc-adawson can you help me understand why the bar charts are challenging for you and what the advantages of a line chart would be? In the line chart you have proposed, there isn't a 'total' cost trend. If we add that, the scale of the chart will become overwhelmed by the total line.

**Comment by kc-adawson** [comment]
The goal at the heart of the request is the following: "It would be nice to see Cost Over Time - Line. Currently the idle swaps with another item throughout the period, so it’s harder to visualize the trend.". So maybe a line graph itself isn't the best solution, but some way to visualize trends clearly when things swap.

**Comment by kwombach12** [comment]
@kc-adawson I see. Would something like this make fulfill that objective? 
<img width="500" alt="Screenshot 2023-04-19 at 12 56 00 PM" src="https://user-images.githubusercontent.com/86785820/233146631-e559c4dd-04e7-4764-84f7-c22e7505334b.png">

**Comment by kc-adawson** [comment]
This is still stacked, after talking it out with the prospect they showed the following reason why the line option is valuable:

Cost Explorer offers Bar and Line options

<img width="762" alt="2023-04-21_14-21-16" src="https://user-images.githubusercontent.com/101200254/233723456-357d74d9-3678-4387-8c15-1aafde6f76e4.png">

We switch to line and see there is one large outlier line - This happens in our line graphs cost "Efficiency Over Time" sometimes.

You can "exclude" that one large line with an easy filter-

<img width="1015" alt="2023-04-21_14-21-39" src="https://user-images.githubusercontent.com/101200254/233723109-9943eb97-1eb1-414c-ac75-a155a3d9a180.png">

With the large item removed, you can see the trends over time easier: 

<img width="765" alt="2023-04-21_14-21-47" src="https://user-images.githubusercontent.com/101200254/233723734-2baa42d9-c0e7-4dae-967d-6479c7249449.png">

I know the easy filtering is not available, but we do have the exact line template already built in the Efficiency Over Time graph already. It would be nice if overall there were more customizable options. Like X Axis=Cost and Chart=Bar or X Axis=Efficiency Chart=Line

**Comment by kwombach12** [comment]
I think the stacked line graph gives great insights into trends overtime. When I look at this line graph,  Its hard for me to see any trend insights that wouldnt be delivered with a stacked line chart and I find it challenging to see most of the lines since they are 'smushed' together at the bottom. This 'smushing' problem would be even more challenging in our product where when total cost is a line. The y-axis would scale to meet the requirements set by total and the costs of individual items would be very hard to make out.

**Comment by kc-adawson** [comment]
Understood, this feedback was from a user. So I don't really have a counter point.

**Comment by chipzoller** [comment]
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.
