### ISSUE TITLE
Shared tenancy costs changing when drilling down in allocations page for views with released PVCs

### ISSUE THREAD

**Issue by JCBSLMN** [kubecost/cost-analyzer-helm-chart#2164]
Thanks for your interest in Kubecost!  To ensure you get the help you need, please follow these guidelines:

- If you have questions about product functionality/usage or need assistance with product installation/configuration, please email support@kubecost.com, where our support engineering team will be happy to help!
- If you have a reproducible bug or a feature request, you're in the right place.  Please include the information requested below.

---
# For reproducible bugs, please provide the following

**Describe the bug**  
When looking at the allocations page the total given for each namespace is different to the total that is given when a namespace is clicked on 

**To Reproduce**  
1. go to allocations page
2. pick a line item and take note of total
3. click on line item and compare the two totals

**Expected behavior**  
Allocations page and namespace page should provide same totals but they don't

**Screenshots**  
live items on allocations page:
![Screen Shot 2023-04-20 at 7 48 34 am](https://user-images.githubusercontent.com/48340936/233207589-b703e00c-7220-4cc6-97a3-cd1a3b31ea9a.png)

when clicking on namespace goji:
![Screen Shot 2023-04-20 at 7 49 15 am](https://user-images.githubusercontent.com/48340936/233207697-4600789a-c4d1-4993-8866-161e5c81347b.png)

costs don't add up to total that was shown on allocations page.

**Collect logs (please complete the following information):**
- Run `helm ls` and paste the output here:
![Screen Shot 2023-04-20 at 7 50 57 am](https://user-images.githubusercontent.com/48340936/233207941-70b09c61-3432-48c6-81a7-5115ef4aff77.png)

- If the pod is stuck in init, run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-init` and paste output here:
- If a page is broken or not loading, open your javascript developer console and paste the ouput here:
- Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-server` and paste the output here:
- Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-model` and paste the output here:
- Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-frontend` and paste the output here:

**Please share the support case, if any**  
This is most commonly a Zendesk ticket number or link.

**What impact will this have on your ability to get value out of Kubecost?**
Accurate costs are the entire reason we are using kubecost and if that isn't what it can provide then there isn't much value it keeping it running.

**Comment by AjayTripathy** [comment]
Hi @JCBSLMN when idle is not distributed at the top level, drilling down carries the idle cost share that the namespace holds onto the namespace page, resulting in higher totals. Can you try to hide idle or distribute idle costs by cluster, then drill down and compare the two views? You can do that with the selector in the top right that says "Edit"

**Comment by JCBSLMN** [comment]
So i've hidden idle cost on both the dashboard and the namespace page, still different figures:
![Screen Shot 2023-04-21 at 10 11 24 am](https://user-images.githubusercontent.com/48340936/233511723-f6a2d83e-073d-459e-826c-774b0a1421b5.png)
![Screen Shot 2023-04-21 at 10 11 46 am](https://user-images.githubusercontent.com/48340936/233511763-2560baf7-ddb7-4366-9da1-10ec674e5d40.png)

**Comment by AjayTripathy** [comment]
Hm, I haven't been able to repro this. Just to help us debug further could you:

1. Visit settings at <your-url>/settings, remove any shared namespaces and disable shared tenancy costs, then click save:
![image](https://user-images.githubusercontent.com/453512/233514948-da01d095-d361-4754-a1ae-46c3714c6d95.png)

2. If you're comfortable sharing a dump of your data, we can mount it on our side and step through this to see what's causing. You can email it to me directly at ajay@kubecost.com

https://github.com/kubecost/etl-backup

**Comment by JCBSLMN** [comment]
Looks like disabling shared tenancy costs did the trick, thanks for the help!

**Comment by AjayTripathy** [comment]
@JCBSLMN Thanks for that feedback. We are going to investigate  carefully why shared tenancy costs are not distributing properly for you. I suspect that it is because Uncontrolled Pods are not receiving a share of tenancy costs.

**Comment by AjayTripathy** [comment]
To further scope the bug, it is that PersistentVolumesClaimsthat are unmounted do not receive a share of Shared Namespace costs when drilling down. Or to put that conversely, when total costs are aggregate we incorrectly use the namespace cost plus unmounted PVCs in the namespace to compute the percentage of shared costs, and when drilling down, we correctly exclude unmounted PVs from the cost.

**Comment by JCBSLMN** [comment]
glad you figured it out!

**Comment by ameijer** [comment]
note - this has been fixed in https://github.com/kubecost/kubecost-cost-model/pull/1430 and will be present in the 103 release. 

@JCBSLMN, we went with the approach to distribute a proportion of shared costs to unmounted PVCs, the argument being that unmounted PVCs are still using management from the shared k8s resources (hosted masters, etc), and as such, should be responsible for a portion of the costs. The numbers should match now
