### ISSUE TITLE
Update images with CVEs

### ISSUE THREAD

**Issue by thomasvn** [kubecost/cost-analyzer-helm-chart#2166]
**Describe the bug**  
The following images have CVEs associated. Need to upgrade:

```txt
quay.io/prometheus/alertmanager:v0.23.0
prom/node-exporter:v1.3.0
prom/pushgateway:v1.4.2
grafana/grafana:9.4.3
curlimages/curl:latest
kiwigrid/k8s-sidecar:1.21.0
```

**To Reproduce**  
```bash
# Scan the image against a CVE database
trivy image quay.io/prometheus/alertmanager:v0.23.0
```

**Expected behavior**  
Update images to most recent versions to reduce CVEs.

**Comment by AjayTripathy** [comment]
These should be safe to upgrade without a ton of product impact. @thomasvn want to pick this up or assign to support engineers?
