### ISSUE TITLE
Addition of a Resource Usage report 

### ISSUE THREAD

**Issue by ochuko3d** [kubecost/cost-analyzer-helm-chart#2168]
Generating a report for the Pod Resource Usage in the cluster
Currently with kubecost we can generate a report that shows actual cpu and memory usage which is great but the report is in currency value, which helps the management more than the Infrastructure Engineer that need to right-size a ton of pods across various namespace and cluster. 

 A Report for CPU and Memory usage
Can a feature or report be added that generate the cpu and memory metrics, to enable users know the actual usage of their pods across namespaces and rightsize properly. The report should show the current pod usage and what was allocated to the pod(if a resource request value was added).

I really cant say. Of an alternative. 

Users should have a tab showing  the resource usage in addition to the cost value in the panels and be able to generate a report of this usage

**Comment by kwombach12** [comment]
@ochuko3d I believe our container right-sizing page has a lot of the functionality you're looking for. We will be adding more reporting capability to this page in the next couple releases!
<img width="2229" alt="Screenshot 2023-04-21 at 9 25 33 AM" src="https://user-images.githubusercontent.com/86785820/233647647-174e8ab9-f923-4e41-b190-d09b515f11c3.png">

**Comment by chipzoller** [comment]
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.
