### ISSUE TITLE
Error handling on `/nodes` page causing blank page

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#2170]
**Describe the bug**   
A user has reported [ZD: 3898](https://kubecost.zendesk.com/agent/tickets/3898) an issue with `v1.102.1` where a 404 error on the `/nodes` page causes the page to go blank. This is similar to this recent [PR 1928](https://github.com/kubecost/cost-analyzer-frontend/pull/1928) related to `/cluster-sizing`. It maybe worth checking other pages for similar error handling issues.

At this current time it's not clear what the underlying cause of the 404 error was, however @nealormsbee has asked me to "open a ticket to be more resilient to error responses in the UI on this page".

**Comment by nealormsbee** [comment]
Thanks @jcharcalla !

**Comment by kwombach12** [comment]
@nealormsbee do we have a corresponding jira ticket for this or should I make one?

**Comment by nealormsbee** [comment]
We do not have a corresponding Jira ticket yet.

**Comment by kwombach12** [comment]
@nealormsbee ticket raised - tried to incorporate the issue here as well as with cluster-sizing: https://kubecost.atlassian.net/browse/BURNDOWN-85

**Comment by nealormsbee** [comment]
Thank you sir!

**Comment by chipzoller** [comment]
Closing, stale.
