### ISSUE TITLE
Fix AWS cloud integration in UI

### ISSUE THREAD

**Issue by ivankube** [kubecost/cost-analyzer-helm-chart#2176]
**Describe the bug**  
When entering Athena Database and Athena Tablename, UI is showing errors: 

athenaDatabase` must be a `object` type, but the final value was: `null` (cast from the value `"athenacurcfn_database"`). If "null" is intended as an empty value be sure to mark the schema as `.nullable()

athenaTable must be a `object` type, but the final value was: `null` (cast from the value `"table name"`). If "null" is intended as an empty value be sure to mark the schema as `.nullable()`

**To Reproduce**  
1. Go to Settings
2. Click on 'Add Cloud Integration"
3. Choose AWS
4. Enter Athen Database and Athen Tablename
5. See errors

**Expected behavior**  
No errors

**Screenshots**  
![Screenshot 2023-04-24 at 9 56 11 AM](https://user-images.githubusercontent.com/97049075/234018645-7740cfce-78fd-4019-b956-c7d49671381b.png)

**Comment by AjayTripathy** [comment]
@jjarrett21 did we repro/get this fixed?

**Comment by jjarrett21** [comment]
@AjayTripathy the fix went in here 

https://github.com/kubecost/cost-analyzer-frontend/pull/1920

**Comment by AjayTripathy** [comment]
Thanks @jjarrett21! Let's just try and close the loop on the public issue next time!

This fix will be ga in 1.103, and is available in 1.103-rc.0

**Comment by jjarrett21** [comment]
@AjayTripathy Gotcha! Didn't realize this was public facing I'll know for next time.
