### ISSUE TITLE
Configuration to swap to either net amortized costs or amortized cost

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#2181]
**What problem are you trying to solve?**
Need kubecost to able to use amortized costs if needed instead of net amortized. Amortized is used in internal tools per 
 enterprise customer.

**Describe the solution you'd like**
Some config via values.yaml or toggle in UI to display **amortized** costs (AWS).

**Describe alternatives you've considered**
Downgrading to older release

**How would users interact with this feature?**
Set the value in via helm OR toggle in UI.

**Comment by dwbrown2** [comment]
@mmurph3 expected in 103! @kwombach12 to confirm.

**Comment by kwombach12** [comment]
@dwbrown2 103 will deliver:
ListCost
NetCost
AmortizedNetCost
InvoicedCost
Don't think we will get 'amortized'

**Comment by dwbrown2** [comment]
@kwombach12 @Sean-Holcomb if we have Net Amortized isn't it really easy to show Amortized?

**Comment by kwombach12** [comment]
I would assume thats correct, but I'll defer to @Sean-Holcomb

**Comment by mmurph3** [comment]
@Sean-Holcomb We were checking the v1.103  to view the Amortized Cost but we see Amortized Net Cost as the default. My understanding is we were going to show `amortized cost` as the default.

<img width="330" alt="image" src="https://user-images.githubusercontent.com/36980248/236832781-613cf130-41ec-47cd-98a2-325f115ea6d0.png">

**Comment by kwombach12** [comment]
@mmurph3 we don't have amortized costs in 103

**Comment by mmurph3** [comment]
@kwombach12 could we get a custom image to include the ability to get amortized cost prior to v1.104?

**Comment by kwombach12** [comment]
Yea we can do that. Let me talk to them team and get an ETA on that.

**Comment by mmurph3** [comment]
@kwombach12 thanks! Looking forward to an update.

**Comment by chipzoller** [comment]
Closing. Cloud Cost Explorer now (2.2.3 shown) features the following cost metrics:

![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/29008123/1c22716f-21cd-4612-a446-88dfe21de923)
