### ISSUE TITLE
"container_cpu_allocation" metrics drops below the amount of requested CPUs

### ISSUE THREAD

**Issue by ivankube** [kubecost/cost-analyzer-helm-chart#2184]
**Describe the bug**  
"container_cpu_allocation" metrics drops below the amount of requested CPUs

**To Reproduce**  
1. `test-1` cluster, "thomasn-demo" namespace
2. Execute "kube_pod_container_resource_requests{resource="cpu", job="kubecost", namespace="thomasn-demo", container="cost-model"}" to see requests
3. Execute "container_cpu_allocation{namespace="thomasn-demo", container="cost-model"}` query for 6h
4. See the drops

**Expected behavior**  
container_cpu_allocation stays at least at the level of the request

**Screenshots**  
[container_cpu_allocation.pdf](https://github.com/kubecost/cost-analyzer-helm-chart/files/11335965/container_cpu_allocation.pdf)

**Comment by AjayTripathy** [comment]
Graph looks like a scrape of KSM/request data was missed and we replaced with usage. What is the actual impact here?

**Comment by ivankube** [comment]
I'm checking with the customer on the impact. Originally, they thought that https://github.com/opencost/opencost/pull/1770 was a not complete fix of the issue.

**Comment by ivankube** [comment]
@AjayTripathy user replied "From what I understood from reading the Opencost model, the `container_cpu_allocation` metric is used to calculate cost for a container, which is then aggregated depending on the end user’s query. So, if the metric seems inaccurate, it raises concerns about the accuracy of cost numbers reported by Kubecost as well."

From a quick glance, Kubecost is using this metric in a few places:

https://github.com/opencost/opencost/blob/323f6e5cf074eac6ebcbb19b9690837fd99cc846/pkg/costmodel/costmodel.go#L229

https://github.com/opencost/opencost-helm-chart/blob/19c15f172292e5d2311985a85570785a6dc59c2e/examples/dashboard/kube-prometheus-stack-opencost-dashboard.json#L679

https://github.com/kubecost/cost-analyzer-frontend/blob/5b2dcb95171b12116a3bd23e3163114b9a5cff09/src/pages/ClusterSizing/queries.ts#L4

https://github.com/kubecost/cost-analyzer-frontend/blob/5b2dcb95171b12116a3bd23e3163114b9a5cff09/src/pages/ClusterSizing/queries.ts#L23

https://github.com/kubecost/cost-analyzer-frontend/blob/5b2dcb95171b12116a3bd23e3163114b9a5cff09/src/pages/ClusterSizing/queries.ts#L29

https://github.com/kubecost/cost-analyzer-helm-chart/blob/522c51b34121294c6f4c2f1423022938cdb14622/cost-analyzer/values.yaml#L617

https://github.com/kubecost/cost-analyzer-helm-chart/blob/522c51b34121294c6f4c2f1423022938cdb14622/cost-analyzer/values.yaml#L621

**Comment by ivankube** [comment]
Is it going to be fixed?
