### ISSUE TITLE
Allocation API is not returning the idle cost for small windows

### ISSUE THREAD

**Issue by ivankube** [kubecost/cost-analyzer-helm-chart#2190]
**Describe the bug**  
Allocation UI and API does not return idle with window less than 5 hours.

**To Reproduce**  
1. Check Allocation API with window 1h, see no idle

**Expected behavior**  
API either needs to display idle for short windows like 1h, 2h, etc or documentation needs to be updated.

**Please share the support case, if any**  
[3939](https://kubecost.zendesk.com/agent/tickets/3939)

**Comment by kwombach12** [comment]
@michaelmdresser is this a known limitation or a bug? If its a known limitation, we should add some UI/UX elements to help the user understand this

**Comment by michaelmdresser** [comment]
This sounds like a bug.

**Comment by AjayTripathy** [comment]
@ivankube can you share a repro and the URL you used to access?

/model/allocation?aggregate=namespace&window=1h&shareIdle=false&idle=true&idleByNode=false&shareTenancyCosts=false&shareNamespaces=&shareCost=NaN&shareSplit=weighted&chartType=costovertime&costUnit=cumulative&step=hour

returns to me

**Comment by dwbrown2** [comment]
@ivankube would be great if you can share today so we can prioritize if needed for next week's release

**Comment by ivankube** [comment]
Sure! Two examples below -- Allocation API is returning idle for 5h, is not returning for 1h. 

`curl multi.test.kubecost.io/model/allocation -d window=1h -d idle=separate -G | jq > idle-1h.txt`
[idle-1h.txt](https://github.com/kubecost/cost-analyzer-helm-chart/files/11356061/idle-1h.txt)


 `curl multi.test.kubecost.io/model/allocation -d window=5h -d idle=separate -G | jq > idle-5h.txt`
[idle-5h.txt](https://github.com/kubecost/cost-analyzer-helm-chart/files/11356062/idle-5h.txt)


cat idle-1h.txt | grep idle
  "message": "ETL: Allocation: QueryAllocation([2023-04-28T16:47:01+0000, 2023-04-28T17:47:01+0000), [cluster node namespace pod container]) from StoreDriver[1h] 1.256782ms [query 956.572µs] [idle/tenancy 18.737µs] [external 179ns] [aggregate 280.91µs] [accumulate 249ns] [stop 135ns]"

cat idle-5h.txt | grep idle
      "__idle__": {
        "name": "__idle__",
      "__idle__": {
        "name": "__idle__",
  "message": "ETL: Allocation: QueryAllocation([2023-04-28T12:47:08+0000, 2023-04-28T17:47:08+0000), [cluster node namespace pod container]) from StoreDriver[1h] 15.272881ms [query 13.058636ms] [idle/tenancy 36.198µs] [external 167ns] [aggregate 2.177299ms] [accumulate 446ns] [stop 135ns]"

**Comment by ameijer** [comment]
I've spent a few hours looking into this today. Here is a summary of my findings: 

1. This cannot be reproduced reliably on nightly, locally with multi-test data, or on https://etl-fed.se-staging.kubecost.xyz
2. On multi test, I notice that it is always the last 3 hours that do not have idle. For example, https://multi.test.kubecost.io/model/allocation?window=12h&idle=separate&cache=false yields 12 results, but the last (most recent) 3 do not have idle entries. I am wondering if this is a latent reconciliation issue.
3. On my local cluster, when I poll the endpoint during boot (with multi-cloud ETL and prometheus, the idle keys are missing initially but then get added a short time later

I am wondering if this is something with reconciliation, then. My next avenue to try and duplicate this is to connect my local install of kubecost to the same set of cloud providers that multi test is connected to

**Comment by ameijer** [comment]
Update - after discussing with @AjayTripathy , we think this is a data delay issue and not a reconciliation one. Looking at the last few hours on multi test, the most recent 3 hours do seem to be significantly different from the others: 
![image](https://user-images.githubusercontent.com/6842995/235543787-d6dbff2e-09ff-4f81-98d6-3a5c2a13531e.png)

It might be that in this deployment, the delay gets us into trouble here. We might need to figure out a way to reduce the delay, or document this behavior

**Comment by ameijer** [comment]
This morning I ran some tests to see which clusters were present/not present in the most recent data.

Here are the hits from each of the three clusters during the last 2 hours: 

```
$ curl https://multi.test.kubecost.io/model/allocation?window=2h -s | jq | grep -c 'az-test-1-multi-cloud'
0
$ curl https://multi.test.kubecost.io/model/allocation?window=2h -s | jq | grep -c 'gcp-test-1-multi-cloud'
0
$ curl https://multi.test.kubecost.io/model/allocation?window=2h -s | jq | grep -c 'aws-test-1-multi-cloud'
1244
```

Only AWS-keyed data is present. 

And here are counts from the last 6 hours: 

```
$ curl https://multi.test.kubecost.io/model/allocation?window=6h -s | jq | grep -c 'aws-test-1-multi-cloud'
3740
$ curl https://multi.test.kubecost.io/model/allocation?window=6h -s | jq | grep -c 'az-test-1-multi-cloud'
727
$ curl https://multi.test.kubecost.io/model/allocation?window=6h -s | jq | grep -c 'gcp-test-1-multi-cloud'
1954
```

Beyond 2-3 hours, all 3 clusters have data. 

Based on this data, it looks like only one cluster's data (AWS) is available for the last 2-3 hours. As a result, we must be holding off on computing idle until we have all the cluster information, which is not available until a few hours later.

**Comment by ameijer** [comment]
We are going to go with an 'expected behavior' resolution on this and downgrade its priority. When using thanos, we deliberately wait 3 hours via the thanos offset before incorporating the data. @ivankube beyond just missing idle, you likely are not getting complete data for such a recent timeframe anyway - it is only for a subset of the clusters.

**Comment by AjayTripathy** [comment]
@ivankube I would just double check w/ user that this is a 3h delay, and that it's on a thanos/multicluster environment, and its only the most recent 3h.
