### ISSUE TITLE
Split grafana sidecar image name and image version config

### ISSUE THREAD

**Issue by cbankston-alk** [kubecost/cost-analyzer-helm-chart#2191]
**What problem are you trying to solve?**
I'm trying to update the `kiwigrid/k8s-sidecar` image to leverage a pull through cache registry, to remove dependencies on Docker Hub. Since the image name and version are [stored in the same key/value](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/charts/grafana/values.yaml#L259), updating this reference will prevent us from receiving automatic updates to this image version when it's incremented in the helm chart, and will require us to increment the image version manually as we upgrade helm chart versions.

**Describe the solution you'd like**
Split the image name and version into separate key/value configs, similar to how [other images are being configured](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/charts/grafana/values.yaml#L27-L28) in this same chart.

**Describe alternatives you've considered**
Pinning to the specific image version and taking on the manual effort to keep it up to date when we upgrade helm charts. My team most likely will not allow this.

**How would users interact with this feature?**
This would allow users to override the grafana sidecar image name without taking on the responsibility of updating image versions.

**Comment by thomasvn** [comment]
Thanks for the feedback @cbankston-alk, this seems do-able! I believe we'll just need to separate the current [`.Values.sidecar.image`](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.102/cost-analyzer/charts/grafana/templates/deployment.yaml#L93) into `.Values.sidecar.image.repository` and `.Values.sidecar.image.tag` similar to [this example](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.102/cost-analyzer/charts/grafana/templates/deployment.yaml#L109).
