### ISSUE TITLE
Use a single source for the configmap-reload image

### ISSUE THREAD

**Issue by cbankston-alk** [kubecost/cost-analyzer-helm-chart#2192]
**What problem are you trying to solve?**
I am seeing two different images being used for the **configmap-reload** image, [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.99.0/cost-analyzer/charts/prometheus/values.yaml#L322) and [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.99.0/cost-analyzer/values-eks-cost-monitoring.yaml#L152).

I'd prefer to use the bitnami/configmap-reload image if possible, but I'd like to reduce the risk of the jimmidyson/configmap-reload image version being incremented in the prometheus chart to a version that's not available for the bitnami/configmap-reload image.

It's not clear if these images are being maintained by the same maintainer and if both images will keep their versions in sync.

**Describe the solution you'd like**
The bitnami/configmap-reload image seems to be receiving more frequent updates, so I'd prefer a migration away from the jimmidyson/configmap-reload image.

**Describe alternatives you've considered**
Accepting the risk that versions could get out of sync and having to catch this in a non-prod environment.

**How would users interact with this feature?**
I think this is a behind-the-scenes change that could help reduce user confusion and possibly improve the security posture of this chart.

**Comment by kwombach12** [comment]
@AjayTripathy can you provide us some more context on the 2 images?

**Comment by cbankston-alk** [comment]
The versions are not kept in sync between images due to one image prefixes their version with the letter `v`, while the other image doesn't.

Because of this, it's not possible to use the `bitnami/configmap-reload` image without also hardcoding the image version in my values files, which will prevent the image version from being automatically updated when upgrading to the latest helm chart version.

**Comment by thomasvn** [comment]
Hi @cbankston-alk ! Both links you sent for the configmap-reload image get deployed to the [prometheus-server pod](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.102/cost-analyzer/charts/prometheus/templates/server-deployment.yaml#L48-L79). Therefore this Helm chart never runs both `jimmidyson/configmap-reload` and `public.ecr.aws/bitnami/configmap-reload`, just one or the other.

As a result, I don’t think synchronization between images is an issue here. If you prefer to run the image `public.ecr.aws/bitnami/configmap-reload`, you can specify that in your `values.yaml` file! (example [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.102.0/cost-analyzer/values-eks-cost-monitoring.yaml#L142-L174))

**Comment by cbankston-alk** [comment]
@thomasvn thanks for your response!

I have switched over to the `public.ecr.aws/bitnami/configmap-reload` image as it seems to be somewhat suggested/supported as a possibility, but when doing this I am not able to leave the image version unpinned. Because of this, when I upgrade helm chart versions in the future, I will need to evaluate if the helm chart has updated the version pinning for this image, and then manually update the version I've pinned to match. This step is easy to forget, and for this reason I am claiming synchronization between images is an issue.

Here's some questions I have:

1. What is the purpose of this repo mentioning the possibility of using the `public.ecr.aws/bitnami/configmap-reload` image in its example configurations?
2. Is this image actually supported for use by this helm chart?
3. Are there any plans to migrate to the `bitnami/configmap-reload` image, or away from images hosted only on Docker Hub?

Additionally, I see Kubecost pushes their images to public.ecr.aws and that has been a huge help to us so far. Would it be possible for kubecost to push the `jimmidyson/configmap-reload` image to ecr-public somehow, so that all dependencies can be pulled from the same place?

**Comment by thomasvn** [comment]
@linhlam-kc Would you be able to comment on the use of `public.ecr.aws/bitnami/configmap-reload` in `values-eks-cost-monitoring.yaml`? From my understanding this is just an example of how you can configure the Prometheus server's configmapReload container, however this is not currently the default functionality of the chart.

**Comment by linhlam-kc** [comment]
@thomasvn You are correct, configmap-reload is optional but not a hard requirement. `public.ecr.aws/bitnami/configmap-reload` is an alternative configmap-reload image managed by Bitnami. We use it in the collaboration with AWS to comply with AWS best practices. From my understanding, not allowing latest tag is an AWS best practice to ensure the container application is accidentally upgraded to unstable version.

**Comment by thomasvn** [comment]
@cbankston-alk. Closing for now. Feel free to re-open if you have a follow up question!
