### ISSUE TITLE
Currency setting not followed on cluster-inspect

### ISSUE THREAD

**Issue by kc-creynold** [kubecost/cost-analyzer-helm-chart#2196]
**Describe the bug**  
The cluster inspect page doesn't follow NON USD currency setting on 102.2

**To Reproduce**  

Set currency to EUR in settings, then got to a cluster on the cluster-inspect page.  Pricing falls back to USD:

https://demo.kubecost.xyz/cluster-inspect?clusterId=kc-demo-prod&cloudId=kc-demo-prod

**Expected behavior**  

Cluster Inspect page should be following currency

---

**Comment by dwbrown2** [comment]
@kwombach12 @aligon good to mark as fixed?

**Comment by kwombach12** [comment]
Yes - it is fixed for me in the latest RC
