### ISSUE TITLE
Hide Cluster Sizing Recommendations if Cluster Controller is not installed

### ISSUE THREAD

**Issue by rossfisherkc** [kubecost/cost-analyzer-helm-chart#2199]
Installing the Cluster Controller is optional:
https://blog.kubecost.com/blog/one-click-request-sizing/#step-1-install-kubecost-with-cluster-controller-enabled

However, we still show Cluster Sizing Recommendations:

![](https://kubecost.zendesk.com/attachments/token/jWlZqlRl9lMFZURoY4riom2kx/?name=image.png)

```
error fetching current cluster information: unable to get most recent valid asset set: could not obtain latest valid asset set (an AssetSet where all Assets (i.e. Nodes) have NodeType != "" and TotalCost > 0.0
```

Since installing the Cluster Controller is optional, and required for 1-Click Request Sizing, we should either:
1. Instruct users on how to install the cluster controller (optimal)
2. Hide the feature in the UI if not installed (prevents the error)

Also note
```
This looks like a case of malformed asset data. This error comes from a query on assets of type node over a 24h window with a 1h step, filtered by the cluster in question.If we could have a look at the query output it would be useful to validate whether it is indeed the case that all Node assets in the response are missing the TotalCost and NodeType properties
```

**Comment by kwombach12** [comment]
Thanks @rossfisherkc this makes a lot of sense to me. We will look at this in 104

**Comment by zorrobyte** [comment]
Case here:
https://kubecost.zendesk.com/agent/tickets/3940

Customer would rather not share their use case publicly and have left comments in the case.

Thanks @kwombach12 !

**Comment by thomasvn** [comment]
@kwombach12 @rossfisherkc I don't believe the cluster controller is required for the `/cluster-sizing` Cluster Sizing Recommendations.

@michaelmdresser @biancaburtoiu Could you confirm?

**Comment by michaelmdresser** [comment]
@thomasvn That is correct. Cluster Sizing Recommendations do not require Cluster Controller to be enabled.

Cluster Controller has the capability to implement Kubecost's recommendations, but the recommendations themselves never have (and never will) require Cluster Controller to be enabled.

**Comment by kwombach12** [comment]
@rossfisherkc since cluster controller is not required for recommendations, can we close this issue?
