### ISSUE TITLE
 Allocation UI - Custom Date Window and some preset Windows do not allow daily view

### ISSUE THREAD

**Issue by ivankube** [kubecost/cost-analyzer-helm-chart#2200]
**Describe the bug**  
When setting custom date ranges in allocation, the default stepped view is weekly and daily is not available

**To Reproduce**  
1. Allocation UI
2. Choose Custom Date Window
3. Check the Step Size options

**Expected behavior**  
Daily view should be available.

**Screenshots**  
https://multi.test.kubecost.io/allocations?window=2023-01-29T00%3A00%3A00Z%2C2023-02-26T00%3A00%3A00Z

![Screenshot 2023-04-28 at 6 34 15 PM](https://user-images.githubusercontent.com/97049075/235265024-5c6b6b0c-fe8e-4f5c-afdc-16d5d81fccab.png)

https://multi.test.kubecost.io/allocations?window=90d

![Screenshot 2023-04-28 at 6 34 41 PM](https://user-images.githubusercontent.com/97049075/235265028-3035ae93-6f9f-4628-b5c6-4d40426dd084.png)

**Please share the support case, if any**  
https://kubecost.zendesk.com/agent/tickets/3951

**Comment by kwombach12** [comment]
@ivankube I believe the reason for this is because you are querying data >90days old. By default we only store daily resolution of data for 90 days.

**Comment by ivankube** [comment]
@kwombach12 is this configurable?

Another customer has the follow settings:

```
- name: ETL_DAILY_STORE_DURATION_DAYS 
value: "730" 
- name: ETL_HOURLY_STORE_DURATION_HOURS 
value: "49" 
- name: ETL_WEEKLY_STORE_DURATION_WEEKS 
value: "53" 
```

and see only "Weekly" and "Default" options when they choose 90d or larger window on the Allocation page.

**Comment by kwombach12** [comment]
@ivankube AH I see the issue now. Yes, those ETL Store values are configurable, but it the UI is adjusting based on those values. I will file a bug now.

**Comment by dwbrown2** [comment]
I'd argue P0/1. @AjayTripathy @teevans know if it's a quick one we can pick up?

**Comment by AjayTripathy** [comment]
I think this is as simple as jsut adding "daily" back as an option. I'm ok to give users that option.

**Comment by AjayTripathy** [comment]
That being said if you select a resolution for which there is no data, we'd show an empty graph instead of a good error message.

**Comment by thomasvn** [comment]
@ivankube Current workaround would be to manually set the `stepSize` in the URL. This works in v1.102.2

```
/allocations?window=90d&stepSize=day
```

**Comment by passionInfinite** [comment]
@thomasvn What is the equivalent parameter for stepSize in the allocation API? We want to set step size while retrieving data from API.

**Comment by kwombach12** [comment]
@passionInfinite the allocation API has a field called 'step' which you can use to set the step size. We are updating our docs to reflect this.

**Comment by chipzoller** [comment]
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.
