### ISSUE TITLE
Add support for OpenShift DeploymentConfig aggregation

### ISSUE THREAD

**Issue by rossfisherkc** [kubecost/cost-analyzer-helm-chart#2207]
**Description**
As an OpenShift user, I would like Kubecost to support cost allocation reports based on the "DeploymentConfig" objects, which are specific to OpenShift. These objects are part of the apps.openshift.io/v1 API and provide a slightly different behavior compared to the native Kubernetes Deployment objects.

**Use case**
The user would like to have "DeploymentConfig" objects managed natively in Kubecost, similar to how the Argo Rollout controller has been recently supported. This would allow OpenShift users to leverage DeploymentConfig objects for cost allocation and reporting directly within Kubecost.

**Proposed solution**
Add support for the OpenShift DeploymentConfig object in Kubecost, allowing it to be used as a controller kind for aggregation purposes.

Update the documentation to include instructions on how to configure Kubecost for OpenShift environments using DeploymentConfig objects.

Add any necessary code or configuration changes to support DeploymentConfig objects as part of Kubecost's cost allocation and reporting capabilities.

**Related issues/PRs**
None

**Additional context**
User conversation: https://kubecost.zendesk.com/agent/tickets/3934

**Comment by kwombach12** [comment]
Thanks @rossfisherkc will look to tackle this soon!

**Comment by chipzoller** [comment]
Closing, stale.
