### ISSUE TITLE
Shared Cost Settings Changes not populating in Settings page after saving

### ISSUE THREAD

**Issue by patrick-tavares** [kubecost/cost-analyzer-helm-chart#2211]
**Describe the bug**  
If any changes are made to `Settings -> Shared Cost` and the `Save` button is clicked, the changes are saved but do not populate on subsequent `Settings` page loads. As a result, though `Monitor -> Allocations` and other areas reflect these updated config changes, a user is unaware of the current settings since they are not visible. In addition, subsequent `'Save` button clicks will save empty config settings, undoing any previously saved `Shared Cost` settings. 

**To Reproduce**  
1. Go to the `Shared Cost` section under `Settings`.
2. Make any `Shared Cost` configuration changes and click the `Save` button.
3. After the successful save modal, scroll back to the `Shared Cost` section to observe empty values
4. Visit `Monitor -> Allocation` to observe that the saved shared cost settings are in fact working
5. Go back to `Settings` section and click the `Save` button.
6. Go back to `Monitor -> Allocation` to observe that previous shared cost settings have been removed.

**Expected behavior**  
Any saved changes to `Shared Cost` should be displayed as current configuration under `Settings`

**Screenshots**  
[Screencast from 2023-05-02 08-31-03.webm](https://user-images.githubusercontent.com/30978122/235686738-67548546-5192-46ff-b98a-4331969a1b72.webm)

**Comment by kwombach12** [comment]
@patrick-tavares what deployment are you using? I cant repro this in the latest RC

**Comment by teevans** [comment]
Closing after working with patrick to verify it's fixed in latest.
