### ISSUE TITLE
public.ecr.aws/bitnami/configmap-reload:0.7.1 not multi-arch

### ISSUE THREAD

**Issue by andrewhibbert** [kubecost/cost-analyzer-helm-chart#2219]
**Describe the bug**  

public.ecr.aws/bitnami/configmap-reload:0.7.1 not multi-arch

**To Reproduce**  
Run the following:
```
-> $ docker buildx imagetools inspect public.ecr.aws/bitnami/configmap-reload:0.7.1 --raw
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 6655,
      "digest": "sha256:e1863761ef793efda68147cef83f9c107371f412b222d1cbaef9f6bb21665aea"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 30893459,
         "digest": "sha256:1d8866550bdd02551d6874e99aa828dd95b7434c6a25168765d46251cc230469"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 9767507,
         "digest": "sha256:6719dc63faf42f281e364b53f073e910721f17af32c009f77f0fef3aacb84d66"
      }
   ]
}%
```

**Expected behavior**  

Expecting multiple manifests/images of which is amd64 and arm64 are included

**Comment by kwombach12** [comment]
@andrewhibbert Could you provide a little more detail on the issue you're facing and the expected behavior?

**Comment by thomasvn** [comment]
@andrewhibbert This image is currently used in the [values-eks-cost-monitoring.yaml](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.103/cost-analyzer/values-eks-cost-monitoring.yaml#L154) as an example, but this is not the default image used when running Kubecost and I don't believe the image is maintained by Kubecost.

@linhlam-kc, could you help provide more context here?

**Comment by thomasvn** [comment]
@andrewhibbert Additionally, this configmap-reload is optional when deploying Kubecost! You can completely remove the following lines if needed:

https://github.com/kubecost/cost-analyzer-helm-chart/blob/7b160fa8ecfb9e976eada6cf2652ca1c2a5555ea/cost-analyzer/values-eks-cost-monitoring.yaml#L142-L174

**Comment by linhlam-kc** [comment]
Thank you @thomasvn the configmap-reload image is optional. Users can also consider to use the image from https://hub.docker.com/r/jimmidyson/configmap-reload/tags which support multi-arch. This is the repo that our standard Helm chart is using.

**Comment by thomasvn** [comment]
@andrewhibbert Closing for now. Feel free to re-open if you have a follow up question!
