### ISSUE TITLE
Indicate to users that Kubecost only displays namespaces which have workloads in them

### ISSUE THREAD

**Issue by thomasvn** [kubecost/cost-analyzer-helm-chart#2220]
**What problem are you trying to solve?**
I use "Namespaces" as a unit of measure in chargeback/showback programs. However, there are more namespaces that exist on the cluster than are shown in Kubecost.

```
$ kubectl get namespaces
NAME              STATUS   AGE
default           Active   46h
kube-node-lease   Active   46h
kube-public       Active   46h
kube-system       Active   46h
kubecost          Active   46h
```

<img width="1265" alt="Screenshot 2023-05-04 at 9 00 23 AM" src="https://user-images.githubusercontent.com/11251627/236265016-c02ac135-d71a-49ba-9285-95204e1bcced.png">

This is likely because there have not been any workloads running in the `default`, `kube-node-lease`, and `kube-public` namespaces in the last 7 days.

**Describe the solution you'd like**
A frontend indicator that Kubecost will only list namespaces which had workloads running in them. Also some accompanying documentation [here](https://docs.kubecost.com/using-kubecost/navigating-the-kubecost-ui/cost-allocation).

**Describe alternatives you've considered**
n/a

**How would users interact with this feature?**
More clarity for users.

**Comment by kwombach12** [comment]
@thomasvn this is a great callout. I think we can at least start by adding this to our documentation.

**Comment by kwombach12** [comment]
@bstuder99 can you help us with this please?

**Comment by brstuder** [comment]
Sure. I would suggest we add this into the Allocations doc, can make a quick fix for this

**Comment by brstuder** [comment]
Added notice in this section: https://docs.kubecost.com/using-kubecost/navigating-the-kubecost-ui/cost-allocation#aggregate-by-filters
The notice gives a bit of visual flair, but if this is too obscurely placed in between other details about aggregation, let me know how I can approve this. Otherwise I'll see this as closed

**Comment by kwombach12** [comment]
I dont think a 'notice' is warranted here - I think it makes the docs a bit too 'crowded'. I'd propose we add a to the line below "Date Range":
`Select the date range of the report by setting specific start and end dates, or by using one of the preset options. Kubecost will show the relevant Kubernetes Allocations which have run a workload in the specified timeframe.`

@thomasvn what do you think?

**Comment by thomasvn** [comment]
@kwombach12 @bstuder99 I do agree that this section of the docs is beginning to get a little bit crowded with all the different caveats we're adding in here. Would a dropdown menu listing be more helpful? Or maybe a bulleted list instead of notices?

Also, I do think this information belongs under the "Aggregate By" heading, because this same issue can probably occur for any aggregation which is not directly mapped to a workload. For example Namespace, Label, Department, Environment, Owner, Product, Team.

**Comment by chipzoller** [comment]
Closing, stale.
