### ISSUE TITLE
Adjust wording on `/cluster-inspect` tooltip

### ISSUE THREAD

**Issue by thomasvn** [kubecost/cost-analyzer-helm-chart#2221]
## What problem are you trying to solve?
Currently, all tooltips on the `/cluster-inspect` view are worded similar to the following:

> Maximum number of pods for time frame selected.

However, this can be slightly confusing because the value actually accounts for _**all**_ pods which have existed (running, started, or stopped) within this time frame. It is not a `max()` for a single timestamp within this time frame.

<img width="1260" alt="Screenshot 2023-05-04 at 9 06 52 AM" src="https://user-images.githubusercontent.com/11251627/236267119-3f7dc722-f82c-4f56-bc6c-2d873b93543e.png">

## Describe the solution you'd like
For greater clarity, I believe it should be worded like the following.

> Number of unique pods which were monitored for time frame selected.

## Describe alternatives you've considered

n/a

## How would users interact with this feature?

More understandability for teams given access to the Kubecost instance.

**Comment by kwombach12** [comment]
+1 to this copy update. Will log and see if we can crank this out in 103.

**Comment by chipzoller** [comment]
Closing, completed.
