### ISSUE TITLE
Unable to upgrade kubecost using terraform helm provider on 1.25

### ISSUE THREAD

**Issue by llamahunter** [kubecost/cost-analyzer-helm-chart#2225]
Thanks for your interest in Kubecost!  To ensure you get the help you need, please follow these guidelines:

- If you have questions about product functionality/usage or need assistance with product installation/configuration, please email support@kubecost.com, where our support engineering team will be happy to help!
- If you have a reproducible bug or a feature request, you're in the right place.  Please include the information requested below.

---
# For reproducible bugs, please provide the following

**Describe the bug**  
Trying to update helm chart on k8s 1.25 fails due to attempts to reference PSP

**To Reproduce**  
1. apply helm chart update via terraform apply, changing some values.yaml

**Expected behavior**  
Update succeeds

**Actual behavior**
│ Error: unable to build kubernetes objects from current release manifest: [resource mapping not found for name: "kubecost-grafana" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
│ ensure CRDs are installed first, resource mapping not found for name: "kubecost-cost-analyzer-psp" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
│ ensure CRDs are installed first]

**Logs**
```
NAME    	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART                	APP VERSION
kubecost	kubecost 	1       	2023-03-22 21:30:51.042542 -0700 PDT	deployed	cost-analyzer-1.101.2	1.101.2
```

**What impact will this have on your ability to get value out of Kubecost?**
Can not update anymore

**Comment by llamahunter** [comment]
Note that I have tried turning off all the psp things in values.yaml as well.  However, this shouldn't be necessary? Your helm charts should not be trying to use PSPs if they aren't a supported feature of the k8s deployment version.
```
podSecurityPolicy:
  enabled: false
grafana:
  rbac:
    pspEnabled: false
```

**Comment by kwombach12** [comment]
@thomasvn Can you take a look at this one?

**Comment by thomasvn** [comment]
Hi @llamahunter, this chart should be able to handle the absence of PSPs based on the work done in PR https://github.com/kubecost/cost-analyzer-helm-chart/pull/1824

Could you clarify the order of operations here? Did you have an existing install of Kubecost on k8s v1.24, then upgrade your cluster to k8s v1.25 and then begin seeing these errors?

**Comment by jcharcalla** [comment]
Was this cluster recently upgraded to v1.25? 

If so my suspicion is that your previous Kubecost `v1.101.2` install has PSP enabled. According to the [helm documentation ](https://helm.sh/docs/topics/kubernetes_apis/#updating-api-versions-of-a-release-manifest) releases should be updated to disable deprecated API's prior to upgrading Kubernetes.

> If you don't update a release as suggested previously, you will have an error similar to the following when trying to upgrade a release in a Kubernetes version where its API version(s) is/are removed:

> Error: UPGRADE FAILED: current release manifest contains removed kubernetes api(s)
for this kubernetes version and it is therefore unable to build the kubernetes
objects for performing the diff. error from kubernetes: unable to recognize "":
no matches for kind "Deployment" in version "apps/v1beta1"

> Helm fails in this scenario because it attempts to create a diff patch between the current deployed release (which contains the Kubernetes APIs that are removed in this Kubernetes version) against the chart you are passing with the updated/supported API versions. The underlying reason for failure is that when Kubernetes removes an API version, the Kubernetes Go client library can no longer parse the deprecated objects and Helm therefore fails when calling the library. Helm unfortunately is unable to recover from this situation and is no longer able to manage such a release. See [Updating API Versions of a Release Manifest](https://helm.sh/docs/topics/kubernetes_apis/#updating-api-versions-of-a-release-manifest) for more details on how to recover from this scenario.

While the Helm documentation suggest this can be resolved via manually editing the manifest, I have not seen this work. On the two occasions I have seen this issue the only solution was to [backup the Kubecost ETL](https://github.com/kubecost/etl-backup) and Prometheus data (Or release / reattach the PV's), delete the Kubecost namespace and clusterRoles and then re-install Kubecost and restore the backed up data.

There is also a brief note in the [Kubecost documentation](https://docs.kubecost.com/troubleshooting/troubleshoot-install#issue-with-kubernetes-v1.25-helm-commands-fail-when-podsecuritypolicy-crd-is-missing-for-kubecost-gr).

**Comment by llamahunter** [comment]
> Hi @llamahunter, this chart should be able to handle the absence of PSPs based on the work done in PR #1824
> 
> Could you clarify the order of operations here? Did you have an existing install of Kubecost on k8s v1.24, then upgrade your cluster to k8s v1.25 and then begin seeing these errors?

Cluster was running 1.24 with kubecost deployed. Cluster was upgraded to 1.25. Then tried to do an update of kubecost helm chart changing a values.yaml. Now cannot update because something in the helm chart is still trying to reference nonexistent PSPs in 1.25.

I even tried setting all the psp things I could find in the values.yaml to false to turn them off, but somehow they still get enabled.

**Comment by llamahunter** [comment]
> Was this cluster recently upgraded to v1.25?
> 
> If so my suspicion is that your previous Kubecost `v1.101.2` install has PSP enabled. According to the [helm documentation ](https://helm.sh/docs/topics/kubernetes_apis/#updating-api-versions-of-a-release-manifest) releases should be updated to disable deprecated API's prior to upgrading Kubernetes.

So, if you don't do this, you poison your kubecost deployment when you upgrade to 1.25? That seems... unfortunate. Especially since the helm chart seemingly has the PSPs turned on by default.

https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L526

**Comment by llamahunter** [comment]
> There is also a brief note in the [Kubecost documentation](https://docs.kubecost.com/troubleshooting/troubleshoot-install#issue-with-kubernetes-v1.25-helm-commands-fail-when-podsecuritypolicy-crd-is-missing-for-kubecost-gr).

The docs say "To prevent this Helm error state please upgrade Kubecost to at least v1.99 prior to upgrading Kubernetes to v1.25."

But it was at 1.101.2 prior to the v1.25 upgrade, and that seems to not have helped.

**Comment by llamahunter** [comment]
So, I need to back up the ETL data, destroy the deployment, then recreate again (now with all the values.yaml settings that EXPLICITLY disable all four pspEnabled options, and then restore the ETL data?

**Comment by jcharcalla** [comment]
Yes, because you are on v1.101.2, you may already have [ETL Backups](https://docs.kubecost.com/install-and-configure/install/etl-backup) enabled on Kubecost. If backups are enabled Kubecost will restore the ETL files automatically.

Once you uninstall and reinstall Kubecost, PSPs will be automatically disabled since the cluster is now at v1.25. The PR @thomasvn references added that functionality to the Helm chart.

To be clear this is an issue with Kubernetes and Helm which impacts any application that is still using deprecated API's prior to upgrading Kubernetes, not just Kubecost. It is best practice to identify and upgrade or reconfigure deployments using deprecated API's prior to upgrading Kuberntes. There are several open source tools available such as [kubent](https://github.com/doitintl/kube-no-trouble) which assist in this process.

**Comment by llamahunter** [comment]
ok, not happy about it, but backed up ETL, deleted kubecost, reimported ETL data, and now it seems fine.

**Comment by AjayTripathy** [comment]
Hey @jcharcalla why can't the PSPs simply be deleted and the new chart installed on top? Have you tried doing it that way?

**Comment by jcharcalla** [comment]
@AjayTripathy Yes, we tried that. The PSP objects are removed when the cluster is upgraded to v1.25.

That is at the root of the issue, as PSP no longer exists the previous helm install no longer matches the current cluster state.
