### ISSUE TITLE
Unable to configure Workload Identity-based, GCP Cloud Integration via the UI

### ISSUE THREAD

**Issue by patrick-tavares** [kubecost/cost-analyzer-helm-chart#2230]
**Describe the bug**  
When attempting to configure GCP Cloud Integration using the recommended `Workload Identity` method specified in the documentation (https://docs.kubecost.com/install-and-configure/install/cloud-integration/gcp-out-of-cluster#1.-configuring-via-the-kubecost-ui) the user is unable to Update/Save the configuration. Per the documentation, when using the `Workload Identity` integration method, the user should leave the `GCP Service Key` blank and just fill in the `GCP Project Id` and `GCP Billing Database` fields. When doing this, however, the `Upate` button will not activate with a blank `GCP Service Key` field.

**To Reproduce**  
1. Go to `Settings` -> `Cloud Integrations` section.
2. Click on the `Add Cloud Integration` button and choose `GCP`
3. Fill in the `GCP Project Id` and `GCP Billing Database` fields while leaving the  `GCP Service Key` field blank.
4. Notice that the `Update` button/link never illuminates/activates.

**Expected behavior**  
The `Update` button/link should activate as long as the `GCP Project Id` and `GCP Billing Database` fields are filled in.

**Screenshots** 
[Screencast from 2023-05-09 09-15-37.webm](https://github.com/kubecost/cost-analyzer-helm-chart/assets/30978122/faf231c6-853e-4571-886d-e5a70dcf1255)

**Comment by kwombach12** [comment]
@patrick-tavares looking through the docs - It looks like configuring through the UI is a separate approach from using the Workload Identity method. It appears that the workload identity method requires configuring the values.yaml file.

**Comment by patrick-tavares** [comment]
Though the docs recommend configuring things through the values.yaml file, they still imply that WI can be configured via the UI. It sounds like we need to decide if this is a bug or incorrect documentation ;)

**Comment by kwombach12** [comment]
@bstuder99 Can we make this a tad more clear that it should be done through the values.yaml and not through the UI: https://docs.kubecost.com/install-and-configure/install/cloud-integration/gcp-out-of-cluster#2.-configuring-using-values.yaml-recommended

**Comment by patrick-tavares** [comment]
Based on this PR for our front-end repo (private), the UI should support the WI config: https://github.com/kubecost/cost-analyzer-frontend/pull/1121

**Comment by kwombach12** [comment]
AH good catch @patrick-tavares .  It seems our FE is requiring all fields and that appears to be incorrect in this case. I have filed a bug to get this fixed.

**Comment by brstuder** [comment]
@kwombach12 Can you send me the bug so I can track it?

**Comment by kwombach12** [comment]
https://kubecost.atlassian.net/browse/BURNDOWN-115

**Comment by nealormsbee** [comment]
Hi folks, a PR to address this issue has been merged in 1.104. You can check it out in https://nightly.kubecost.io/keyinstructions. Closing.
