### ISSUE TITLE
Add support for init containers

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2231]
**What problem are you trying to solve?**
Not all metrics seem to be gathered when trying to monitor allocation usage for a pod with init containers. Specifically, it seems that an init-container's minutes aren't being measured, leading to no costs for these containers. I tested with [various init-containers](https://github.com/keithhand/helm-init-container-test) to confirm that it doesn't seem to be the length of time the init-container runs. 

```json
"init": {
            "name": "init",
            "start": "2023-04-28T00:00:15Z",
            "end": "2023-04-29T00:00:00Z",
            "cpuCoreRequestAverage": 0,
            "cpuCoreUsageAverage": 0.027028109797289014,
            "cpuCost": 0,
            "gpuCost": 0,
            "networkCost": 0,
            "loadBalancerCost": 0,
            "pvCost": 0,
            "ramByteRequestAverage": 0,
            "ramByteUsageAverage": 491049610.67611986,
            "ramCost": 0,
            "sharedCost": 0,
            "externalCost": 0
          },
   "istio-proxy": {
            "name": "istio-proxy",
            "start": "2023-04-28T00:00:00Z",
            "end": "2023-04-29T00:00:00Z",
            "cpuCoreRequestAverage": 0.040256944444444435,
            "cpuCoreUsageAverage": 0.016484367681634898,
            "cpuCost": 0.013950310913958383,
            "gpuCost": 0,
            "networkCost": 0.06132358857116362,
            "loadBalancerCost": 0,
            "pvCost": 0,
            "ramByteRequestAverage": 168849863.1111111,
            "ramByteUsageAverage": 672130117.7248731,
            "ramCost": 0.007305929526456059,
            "sharedCost": 0.0008425052889484719,
            "externalCost": 0
          }
```

**Describe the solution you'd like**
Better accuracy regarding pod/init-container pricing

**Describe alternatives you've considered**
Ignore init-container resources

**How would users interact with this feature?**
See accurate container pricing for init-containers in a pod.

**Comment by kwombach12** [comment]
thanks @keithhand can you log this in our FR tracker?

**Comment by jessegoodier** [comment]
I'm not sure if this is relevant, but take a look at this- init container missing from `container_memory_allocation_bytes` but is in `container_memory_working_set_bytes`
https://jesse-prom-proxy.test-1.aws.kubecost.xyz/graph?g0.expr=container_memory_allocation_bytes%7Bnamespace%3D%22qa%22%2Cpod%3D%22init-container-pod-5dbf6b8fdb-2h9b4%22%7D&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=2d&g1.expr=container_memory_working_set_bytes%7Bpod%3D%22init-container-pod-5dbf6b8fdb-2h9b4%22%2Ccontainer!%3D%22POD%22%7D&g1.tab=0&g1.stacked=0&g1.show_exemplars=0&g1.range_input=2d
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/31039225/8f3f8f54-a8d8-47cf-b875-b951237fa9f3)

**Comment by jessegoodier** [comment]
test pod: https://github.com/jessegoodier/qa-pods/blob/main/init-container-pod.yaml

**Comment by kwombach12** [comment]
@teevans are init-containers something we expect to handle today?

**Comment by teevans** [comment]
I suspect not, @AjayTripathy should this just magically work?

**Comment by chipzoller** [comment]
Closing, stale.
