### ISSUE TITLE
Fix  "Allocation Recurring Update" alerts aggregated by cluster or namespace

### ISSUE THREAD

**Issue by ivankube** [kubecost/cost-analyzer-helm-chart#2233]
**Describe the bug**  
Alert "Allocation Recurring Update" aggregated by cluster or namespace either returns an empty result or not the full result.

The customer's alert aggregated by cluster worked but aggregated by namespace did not work.

In my reproduction, both of the alerts returned empty output once, then both of them returned some costs but missed namespaces and clusters. 

**To Reproduce**  
1. Go to demo.kubecost.xyz
2. Click on Alerts --> Create Alert --> Allocation Recurring Update --> Window 7d --> Aggregation by Cluster/Namespae. add your email
3. Click "Test Alert"

**Expected behavior**  
The alert should always work. 

**Screenshots**  
Empty
![Screenshot 2023-05-09 at 3 58 34 PM](https://github.com/kubecost/cost-analyzer-helm-chart/assets/97049075/f1f184ce-39d8-4be2-ae58-a5141c6354e5)
![Screenshot 2023-05-09 at 3 58 51 PM](https://github.com/kubecost/cost-analyzer-helm-chart/assets/97049075/cbdee1b5-b230-4adc-8764-15470347087a)
![Screenshot 2023-05-09 at 3 59 14 PM](https://github.com/kubecost/cost-analyzer-helm-chart/assets/97049075/446f99ee-510f-42e1-9552-ecca029f15f3)
![Screenshot 2023-05-09 at 4 00 08 PM](https://github.com/kubecost/cost-analyzer-helm-chart/assets/97049075/59e0af50-7cf6-477a-b7f6-0973c57ddf14)

Compare with 
https://demo.kubecost.xyz/allocations?filters=W10%3D&context=W10%3D&agg=namespace
https://demo.kubecost.xyz/allocations?filters=W10%3D&context=W10%3D&agg=cluster 

**Please share the support case, if any**  
https://kubecost.zendesk.com/agent/tickets/4096

**Comment by BouchaaraAdil** [comment]
O11Y-513

**Comment by kwombach12** [comment]
Thanks @ivankube We will be adding the ability to send saved reports on a configurable cadence to the reports page in 104. Would that resolve this issue (assuming the reports are sent correctly :) )?

**Comment by ivankube** [comment]
Regular cadence sound awesome. Reports should also have a correct and complete information.

**Comment by mmurph3** [comment]
@kwombach12 thanks. The higher priority here is getting the report to send complete information as it doesn't mirror the info created in the kubecost console when tested. This is a p0 for an enterprise customer.

**Comment by kwombach12** [comment]
@mmurph3 totally agree. We will do thorough testing once this feature is implemented to ensure the correct report data is sent.

**Comment by mmurph3** [comment]
@kwombach12 business impact/statement from enterprise customer:

`We wanted to present that to our engineers in a monthly meeting in order to push them use kubecost, but since the feature is not there we are not going to do it, in the other hand teams that are using kubecost already needs it and they have OKRs to reduce cost based on it`

**Comment by kwombach12** [comment]
This will be fixed in 104 release on 6/6!

**Comment by ameijer** [comment]
@ivankube, would you be willing to test out the new feature on multi-test? To duplicate this functionality, go to reports, and create a new report with the same parameters. Save the report, then add a schedule to it to send your email a PDF daily.

**Comment by ivankube** [comment]
@ameijer I got an error:

![Screenshot 2023-06-01 at 11 57 01 AM](https://github.com/kubecost/cost-analyzer-helm-chart/assets/97049075/a12d431c-02b2-438a-886e-feb41bdff734)

**Comment by ameijer** [comment]
@ivankube I had the same issue - @avrodrigues5 showed me how to fix it, you need to press enter after putting in your email

cc @jjarrett21 , this was the problem you and I corresponded about a few weeks ago

**Comment by ivankube** [comment]
thank you - it's not very intuitive that I needed to press Enter after entering email.

What time of the day I'll receive reports for the Daily schedule?

**Comment by ameijer** [comment]
You will receive reports at midnight GMT

**Comment by jjarrett21** [comment]
@ameijer @ivankube 
<img width="259" alt="Screen Shot 2023-06-01 at 10 21 29 AM" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/14066631/8b537f2a-c26d-4c81-ba63-076d9da97555">
<img width="477" alt="Screen Shot 2023-06-01 at 10 21 19 AM" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/14066631/d53a033f-00ee-44ad-9bc3-690980b6f5a1">

**Comment by ivankube** [comment]
I received the report - looks good to me.

**Comment by ameijer** [comment]
thanks @ivankube - going to close this one then
