### ISSUE TITLE
Enable Budget API to support custom K8s label

### ISSUE THREAD

**Issue by linhlam-kc** [kubecost/cost-analyzer-helm-chart#2237]
**What problem are you trying to solve?**
The budget API doesn’t support customized labels, which partner needs to allow users to specify and track spending limits for specific projects or teams. This is an important feature for many of partner's users

**Describe the solution you'd like**
Add `label` as an option in the Kubecost's Budget UI and Kubecost's Budget API along with the current options such as `namespace` or `cluster`. For example, the API payload can look like this:

```json
...
  "targetType": "label",
  "target": "<key>:<value>",
 ...
```

**Describe alternatives you've considered**
No workaround as of now

**How would users interact with this feature?**
Users can add `label` as a targetType in the Kubecost's Budget UI or API to retrieve budget alert notification message.

**Comment by chipzoller** [comment]
This has already been completed.
