### ISSUE TITLE
Add cluster name to a report that is created from "Allocation Recurring Updates" alert

### ISSUE THREAD

**Issue by ivankube** [kubecost/cost-analyzer-helm-chart#2251]
**What problem are you trying to solve?**
User is switching context for accessing multiple clusters. They want to create an "Allocation Recurring Update"  alert aggregated by namespace. Reports do not have cluster name in them.

**Describe the solution you'd like**
Add cluster name to "Allocation Recurring Update" report and maybe others.

**Describe alternatives you've considered**
Using Alert Subject.

**How would users interact with this feature?**
They'll receive more informative reports. 

https://kubecost.zendesk.com/agent/tickets/4122

**Comment by kwombach12** [comment]
I like this idea! We are working on revamping our recurring reports in 104 - I will see if we can add cluster name as part of the new implemetation.

**Comment by kwombach12** [comment]
@ivankube Users can do a multi-aggregation report with cluster & like namespace - this would show the cluster name. does that satisfy the FR?

**Comment by ivankube** [comment]
@kwombach12 This issue is opened for alerts. Could you provide steps from creating an alert with multi-aggregation?

**Comment by kwombach12** [comment]
@ivankube It seems users aren't able to do multi-aggregation through alerts today. We will deliver auto-sending Reports in 104 so users will be able to create a report with multi-aggregation and then have it sent out an a recurring basis. Sorry for the confusion.

**Comment by sellers** [comment]
Recently, the "Switch Context" item has been removed from the left panel and into "Settings".  I can appreciate the logic behind that but it does mean that a user loses the visibility of which cluster they are on as they browse around more than just in the reports.  Having the "Context" visible on more than just the Overview page would be helpful.

**Comment by kwombach12** [comment]
@sellers I think thats a great point. I will open an internal feature request to make the current primary cluster more clear.

**Comment by chipzoller** [comment]
Closing as stale post 2.x. For future bugs and feature requests that do not specifically pertain to the Helm chart, please direct them to [features-bugs](https://github.com/kubecost/features-bugs/).
