### ISSUE TITLE
Option to disable the Overview page

### ISSUE THREAD

**Issue by thomasvn** [kubecost/cost-analyzer-helm-chart#2256]
**What problem are you trying to solve?**
For users with large environments (many clusters, nodes, pods, containers, metrics), the Overview page can be slow and loading the page multiple times can cause the Kubecost pod to die due to OOM (out of memory)

I believe this is due to the fact that the Overview page runs a multitude of unique allocations, assets, clusterInfo, and savings queries.

**Describe the solution you'd like**
Allow the user to disable the Overview page if they wish. Kubecost will then default to the Allocations page.

**Describe alternatives you've considered**
Current alternatives which could ease some of the load, are (1) [query service replicas](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.103/cost-analyzer/values.yaml#L812), and (2) [cache proxy](https://github.com/kubecost/cost-analyzer-helm-chart/pull/2248). Both may require more adoption to understand their impact to this problem.

**How would users interact with this feature?**
Helm config

**Comment by thomasvn** [comment]
For context, the Overview page currently has the most Zendesk tickets categorized as "Bug" or "Performance". (Ref: [zendesk dashboard](https://kubecost.zendesk.com/explore/dashboard/580135A57A59E734FB47103DC28E52EE2591FBD7CF4E6A2344220C03B4F01064), ask @kirbsauce for access)

**Comment by kwombach12** [comment]
@thomasvn we are working on speeding up the overview page in 104! Lets check back in after that. I think allowing for customization of which pages users see is a bit of a rabbit hole.

**Comment by thomasvn** [comment]
@kwombach12 Yeah I'd agree, thanks for the update! I'll check back in after v1.104

**Comment by chipzoller** [comment]
Closing as I think this is irrelevant now. Not aware of any current complaints with Overview page loading latency after 2.x.
