### ISSUE TITLE
Customer request: Migrate from beta to GA GCP APIs

### ISSUE THREAD

**Issue by rossfisherkc** [kubecost/cost-analyzer-helm-chart#2258]
* horizontalpodautoscalers.v2beta1.autoscaling: This API was deprecated in Kubernetes version 1.23 and is no longer served as of version 1.25. Migrate to the autoscaling/v2 API version [cloud.google.com](https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-25).

* cronjobs.v1beta1.batch: This API was deprecated in Kubernetes version 1.21 and is no longer served as of version 1.25. Migrate to the batch/v1 API version [cloud.google.com](https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-25).

* poddisruptionbudgets.v1beta1.policy: This API was deprecated in Kubernetes version 1.21 and is no longer served as of version 1.25. Migrate to the policy/v1 API version [cloud.google.com](https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-25).

Full list:
horizontalpodautoscalers.v2beta1.autoscaling 
cronjobs.v1beta1.batch 
poddisruptionbudgets.v1beta1.policy 
poddisruptionbudgets.v1beta1.policy 
horizontalpodautoscalers.v2beta1.autoscaling 
cronjobs.v1beta1.batch

ZD Case:
https://kubecost.zendesk.com/agent/tickets/4224

**Comment by kwombach12** [comment]
Thanks @rossfisherkc I have logged a ticket for us to correct this

**Comment by enricojonas** [comment]
@kwombach12 any update on this?

**Comment by kwombach12** [comment]
@enricojonas We haven't started work on this just yet, we will look to get this in our next release.

**Comment by chipzoller** [comment]
These have already been done.
