### ISSUE TITLE
Custom Prometheus Sharding Support 

### ISSUE THREAD

**Issue by hghtwr** [kubecost/cost-analyzer-helm-chart#2261]
Hello all, 

we are using a sharded prometheus with different service endpoints. Data from prometheus is regularly pushed into VictoriaMetrics (VM). 

Now I got the following problem: 

1. If I set ```global.prometheus.fqdn``` to one of the shards of prometheus it only scrapes metrics from 1/4 of the targets.
2. If I use VM's for ```global.prometheus.fqdn``` the pod will not find the prometheus configuration file at startup. 

Is there any way to seperate the settings where to find the configuration and where to receive metrics from?

Thanks!

**Comment by kwombach12** [comment]
@thomasvn can you take a look at this?

**Comment by thomasvn** [comment]
Hey @hghtwr! Is the issue here that [Kubecost metrics](https://docs.kubecost.com/architecture/user-metrics) are not landing in any of the Prometheus shards, or in VictoriaMetrics?

Could you share the error you receive when you set `global.prometheus.fqdn=your.victoriametrics.endpoint`?

**Comment by ep4sh** [comment]
Hi @thomasvn, I'm facing very similar issue, the error from the logs:
```
cost-model 2023-10-13T11:54:32.504716314Z ERR Asset ETL: ComputeAssets: clusterManagementQuery: Prometheus communication error: 400 (Bad Request) URL: 'http://vmselect-vm-stack.victoriametrics.svc:8481/api/v │
cost-model ' Query: 'sum_over_time((avg(kubecost_cluster_management_cost{}) by (cluster_id))[714m:1m]) * 0.016667': retrying                                                                                    │
cost-model 2023-10-13T11:54:32.504885642Z ERR Asset ETL: ComputeAssets: clusterManagementQuery: Prometheus communication error: 400 (Bad Request) URL: 'http://vmselect-vm-stack.victoriametrics.svc:8481/api/v │
cost-model ' Query: 'sum_over_time((avg(kubecost_cluster_management_cost{}) by (cluster_id))[60m:1m] offset 354m) * 0.016667': retrying 

```


As far I understood, there is a difference in VM and Prometheus endpoints:
```
curl 'http://localhost:9090/api/v1/query?query=up&time=2015-07-01T20:10:51.781Z'
curl 'http://localhost:8481/select/0/prometheus/api/v1/query?query=up&time=2021-02-22T19:10:30.781Z'

```

**Comment by thomasvn** [comment]
Thanks for the context @ep4sh. Based on your logs, it seems like the queries to VictoriaMetrics (VM) is hitting HTTP400 Bad Request.

As you mentioned, Prometheus and VM might have different query endpoints? As a result, could you try the following configuration?

```yaml
global:
  prometheus:
    fqdn: http://vmselect-vm-stack.victoriametrics.svc:8481/select/0/prometheus/
```

**Comment by hghtwr** [comment]
Hi all, 

sorry for not closing this earlier, for us it seems like it's working now. 
For this we use the following VM endpoint: 
```http://<local-svc-adress>.svc.cluster.local:8481/select/999/prometheus```

**Comment by thomasvn** [comment]
Thanks for following up here @hghtwr!

**Comment by thomasvn** [comment]
@ep4sh I'm going to close the issue for now. If neither of the above solutions suffice, please feel free to reach back out here!
