### ISSUE TITLE
Allocations Multi Aggregation is not preserving a filter if the filter is set up first

### ISSUE THREAD

**Issue by ivankube** [kubecost/cost-analyzer-helm-chart#2262]
**Describe the bug**  
Multi Aggregation on Allocations page is not preserving a filter

**To Reproduce**  
1. Set up any filter on Allocations page
2. Choose any Multi Aggregation
3. See that filter is missing

**Expected behavior**  
Filters should be preserved. 

**Please share the support case, if any**  
https://kubecost.zendesk.com/agent/tickets/4189

**Comment by kwombach12** [comment]
@ivankube this will be resolved in 104

**Comment by chipzoller** [comment]
Closing, resolved.
