### ISSUE TITLE
continuous request resizing not working with cluster controller.

### ISSUE THREAD

**Issue by ankit-kumar-7** [kubecost/cost-analyzer-helm-chart#2263]
**Describe the bug**  
I have enabled cluster-controller in my cluster to allow continuous request right sizing. the cluster-controller is running fine but after I annotated a deployment with the required values. I can see the following error in the logs.

**To Reproduce**  
1. deployed kubecost with cluster controller enabled
2. annotated a deployment with the values mentioned in https://docs.kubecost.com/using-kubecost/navigating-the-kubecost-ui/savings/auto-request-sizing/continuous-request-sizing

**Expected behavior**  
The cluster autoscaler should update deployment resources based on recommendation.

**Screenshots**  
<img width="1445" alt="Screenshot 2023-05-22 at 9 15 53 AM" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/97100327/d7ae241f-9a2c-4e65-b2c0-5b5db6ae90af">

**Collect logs (please complete the following information):**
```Run loop attempt failed consecutively. Waiting a bit longer before retrying. error="failed to create sizing patch for workload 'mt-bots/deployment/dtl-dlm-pythonb': failed to get recommendation for '{Namespace:mt-bots ControllerKind:deployment ControllerName:dtl-dlm-pythonb ContainerName:dtl-dlm-pythonb}' '{Window:7d TargetUtilizationCPU:0xc000918368 TargetUtilizationMemory:0xc000918370}': unmarshaling recommendation: json: cannot unmarshal object into Go value of type []recommendationservice.Recommendation"```
```2023-05-22T03:14:02Z ERR Error unmarshaling request sizing plan in apply handler: unexpected end of JSON input```

**Comment by kwombach12** [comment]
@michaelmdresser are you able to repro this?

**Comment by michaelmdresser** [comment]
@ankit-kumar-7 what version of Kubecost are you on? If this is the issue I think it is (https://github.com/kubecost/cost-analyzer-helm-chart/issues/2136), I believe this was fixed in v1.103 of Kubecost.

**Comment by ankit-kumar-7** [comment]
We were using v1.102.0 of kubecost. It is working in v1.103.0 Thanks @michaelmdresser
