### ISSUE TITLE
Ability to filter on Charge Types (i.e. CUR filed name "line_item_line_item_type" ) in Cloud Costs page

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#2271]
**What problem are you trying to solve?**
Unable to filter by charge type in the Kubecost UI.

**Describe the solution you'd like**
A requirement is There is filtering of the `line_item_line_item_type` field that is used to calculate amortized cost, and we'd like to make sure we have the flexibility we need

**How would users interact with this feature?**
They want to be able to filter by `line_item_line_item_type` in the kubecost UI (cloud costs page)

**Comment by mmurph3** [comment]
f the line_item_line_item type as dimension can not be kept in KC, can some values be filtered in the SQL backend to only show costs associated with only selected values of the dimension? 

```
WHERE line_item_line_item_type IN (
		'SavingsPlanCoveredUsage',
		'DiscountedUsage',
		'Usage'
	)
```
cc @Sean-Holcomb

**Comment by mmurph3** [comment]
Our queries use
`"(line_item_line_item_type = 'Usage' OR line_item_line_item_type = 'DiscountedUsage' OR line_item_line_item_type = 'SavingsPlanCoveredUsage' OR line_item_line_item_type = 'EdpDiscount' OR line_item_line_item_type = 'PrivateRateDiscount')" `
which is what matches the results shown in the cost explorer.

**Comment by OS-dawitelias** [comment]
We would like you to match to how we report, not to explorer since you are not providing us the ability to filter on the "line_item_line_item_type".

Please filter  to show :

WHERE line_item_line_item_type IN (
		'SavingsPlanCoveredUsage',
		'DiscountedUsage',
		'Usage'
	)


Is this something you can customize for us?

**Comment by Sean-Holcomb** [comment]
Your best bet would be to create a view of your CUR table in Athena. You can apply those filters to the view and point you Kubecost configuration at the View instead of the CUR table. https://docs.aws.amazon.com/athena/latest/ug/create-view.html

**Comment by chipzoller** [comment]
Closed, stale.
