### ISSUE TITLE
Allocation API on-demand is not aggregating by container by default

### ISSUE THREAD

**Issue by ivankube** [kubecost/cost-analyzer-helm-chart#2272]
**Describe the bug**  
Allocation Compute API  does not aggregate by container by default and returns empty name field

**To Reproduce**  
1. Hit /model/allocation/compute
2. Observe empty name 

**Expected behavior**  
Allocation Compute API should return data aggregated by container, where each allocation’s `name` field will be in the path format of`cluster//node//namespace//pod//container`. 
This is the way it's used to work prior to v1.103 + Allocation Compute API with aggregation and Allocation API with or without aggregation 
output have the same  format as described above. 

**Collect logs (please complete the following information):**
v1.102.0 Allocation on-demand without an aggregation
{
  "code": 200,
  "status": "success",
  "data": [
    {
      "cluster-one//__unmounted__/__unmounted__/__unmounted__": {
        "name": "cluster-one//__unmounted__/__unmounted__/__unmounted__",
        "properties": {
          "cluster": "cluster-one",
          "container": "__unmounted__",
          "namespace": "__unmounted__",
          "pod": "__unmounted__"
        },
        "window": {
          "start": "2023-05-12T00:00:00Z",
          "end": "2023-05-13T00:00:00Z"

v1.103.2 Allocation API on-demand without an aggregation:

  "code": 200,
  "status": "success",
  "data": [
    {
      "": {
        "name": "",
        "properties": {
          "cluster": "cluster-one"
        },
        "window": {
          "start": "2023-05-12T00:00:00Z",
          "end": "2023-05-13T00:00:00Z"
        },

**Please share the support case, if any**  
https://kubecost.zendesk.com/agent/tickets/4171

**Comment by kwombach12** [comment]
Thanks @ivankube. I will log a bug for this.

**Comment by chipzoller** [comment]
Closing, stale.
