### ISSUE TITLE
Cloud Cost API is not returning labels.component and properties.name

### ISSUE THREAD

**Issue by ivankube** [kubecost/cost-analyzer-helm-chart#2273]
Cloud Cost API is not returning labels.component and properties.name

**To Reproduce**  
1. Hit  /cloudCost/top
3. See error

**Expected behavior**  
Assets API returns both properties.name and labels.component. Cloud Cost API should return them as well.. 

**Collect logs (please complete the following information):**

```
{
  "code": 200,
  "data": {
    "sets": [
      {
        "cloudCosts": {
          "GCP/'< REDACTED >'/analytics-REDACTED/Storage/Cloud SQL/'< REDACTED >'": {
            "properties": {
              "providerID": "< REDACTED >",
              "provider": "GCP",
              "accountID": "<REDACTED>",
              "invoiceEntityID": "< REDACTED >",
              "service": "Cloud SQL",
              "category": "Storage"
            },
            "window": {
              "start": "2023-04-20T00:00:00Z",
              "end": "2023-04-21T00:00:00Z"
            },
            "listCost": {
              "cost": "< REDACTED >",
              "kubernetesPercent": 0
            },
            "netCost": {
              "cost": "< REDACTED >",
              "kubernetesPercent": 0
            },
            "amortizedNetCost": {
              "cost": "< REDACTED >",
              "kubernetesPercent": 0
            },
            "invoicedCost": {
              "cost": "< REDACTED >",
              "kubernetesPercent": 0
            }
          }
        }
      }
    ]
  }

**Please share the support case, if any**  
https://kubecost.zendesk.com/agent/tickets/4184

**Comment by kwombach12** [comment]
Thanks @ivankube I will log a bug for this. @Sean-Holcomb Are you aware of this issue?

**Comment by Sean-Holcomb** [comment]
Name is not part of the CloudCost spec and is not expected. Labels are only present if that particular item has labels

**Comment by ivankube** [comment]
According to the customer, they have labels and they are not displayed in API output.

**Comment by Sean-Holcomb** [comment]
I am still seeing tags in top for GCP
```
"GCP/< REDACTED >/< REDACTED >/Compute/Compute Engine/< REDACTED >": {
                        "properties": {
                            "providerID": "< REDACTED >",
                            "provider": "GCP",
                            "accountID": "< REDACTED >",
                            "invoiceEntityID": "< REDACTED >",
                            "service": "Compute Engine",
                            "category": "Compute",
                            "labels": {
                                "goog-gke-node": "",
                                "goog-k8s-cluster-location": "us-central1-c",
                                "goog-k8s-cluster-name": "< REDACTED >",
                                "goog-k8s-node-pool-name": "< REDACTED >"
                            }
                        },
                        "window": {
                            "start": "2023-05-25T00:00:00Z",
                            "end": "2023-05-26T00:00:00Z"
                        },
                        "listCost": {
                            "cost": 0.8041360000000002,
                            "kubernetesPercent": 1
                        },
                        "netCost": {
                            "cost": 0.8041360000000002,
                            "kubernetesPercent": 1
                        },
                        "amortizedNetCost": {
                            "cost": 0.8041360000000002,
                            "kubernetesPercent": 1
                        },
                        "invoicedCost": {
                            "cost": 0.8041360000000002,
                            "kubernetesPercent": 1
                        },
                        "amortizedCost": {
                            "cost": 0.8041360000000002,
                            "kubernetesPercent": 1
                        }
                    },
   ```
   Is the user able to check their big query data to show that the  corresponding line item does have tags that are not showing up?

**Comment by ivankube** [comment]
Yes, they posted Big Query data with labels in https://kubecost.zendesk.com/agent/tickets/4184. If you don't have access, I'll post a screenshot here.

**Comment by david-semeniuk** [comment]
Hey! 
Maybe some of miscommunication was here. I want to add some clarifications.
The main problem - is migrating from Assests API to Cloud Cost API.

Previously, we have created dashboards using Assets API and had an important breakdowns for our cloud spends (those were in labels.component and properties.name).  But when we migrated to Cloud Cost API we clearly understand that those breakdowns were lost in new API.
Seems like it wasn't lost for Compute Engine but you can easily check it when comparing BigQuery costs or Cloud SQL costs from GCP.

**Comment by Sean-Holcomb** [comment]
It is the case that properties.name is not in CloudCost right now, but it is not the case that label.component should be missing. 

I posted an internal note an that ticket but it appears to be closed. I was hoping you could run a BigQuery query for me to help understand the issue better.

```
SELECT DISTINCT service.description, resource.name, properties.name, labels.component
FROM ${YOUR_TABLE_NAME} 
WHERE DATE(date) = "2023-04-18" AND service.description = "Cloud SQL"
```

In terms of sharing the results, you could do so on that ticket or reach out to me on the Kubecost Slack, or we could find another channel that works better for you.

**Comment by david-semeniuk** [comment]
Thank you for attention into this! 
I found a workaround how I can reach what I need. Only /cloudCost/top endpoint supports combination of those breakdowns, but it's not straight-forward.
I need to pass params {"aggreagte": "label:component,providerID"} otherwise I'll get nulls. And then I can hardcode providerID based on costs in the cloud and get properties.name.

It would be good if you implement understandable providerID in the future.
Thank you in advance!

**Comment by Sean-Holcomb** [comment]
Glad to hear you found something that works, more details on CloudCost is something that is on our radar. In particular we are looking to more closely follow the schema laid out by the FinOps Foundation in the [Focus Spec](https://github.com/finopsfoundation/finops-open-cost-usage-spec/blob/main/specification_sheet_import.md). For your particular use case the field  "Vendor Usage Type" seems like the best match for properties.name. So hopefully more on that in the future.

I will Close this ticket for now, as it seems that your short term needs have been addressed on this issue.
