### ISSUE TITLE
Custom GCE Nodes Break Cluster Sizing Recommendations on GKE

### ISSUE THREAD

**Issue by rossfisherkc** [kubecost/cost-analyzer-helm-chart#2277]
We have encountered a persistent issue regarding the display of data in the cluster-sizing. We initially encountered this issue while using version 1.102 and subsequently upgraded to version 1.103, however, the problem remains unresolved.

When trying to view the data, the following error message is returned:
{ status: 500, message: '{"code":500,"data":null,"message":"error getting monthly node cluster rates: could not compute monthly node price: did not find pricing for node type custom-16-32768"}' }

We confirmed that we're using the Kubecost's node exporter. It was suggested to us that we set custom pricing for the node type "custom-16-32768" using the CSV Pricing feature. However, we would like to avoid manual adjustments or configurations.

Further details:

Our setup involves the use of GKE, not Openshift on GCP.
Our Prometheus Metrics on the /diagnostics page didn't provide any error messages that could relate to this issue.
As the issue persists even after upgrading versions and confirming our setup, we believe there is an underlying issue that needs to be addressed. I've added this bug report to our prioritization list for consideration for fixing.

This issue hinders our ability to effectively monitor and manage our cluster, so we would appreciate a resolution as soon as possible.

Thank you for your attention to this matter.

See case:
https://kubecost.zendesk.com/agent/tickets/4154

Note that this issue may be expected considering the PRs @michaelmdresser mentioned here:
https://kubecost.slack.com/archives/G01MN4R06MB/p1684770159276599

**Comment by kwombach12** [comment]
@michaelmdresser can you repro this?

**Comment by michaelmdresser** [comment]
Yes. Create a GKE cluster using a custom machine type (https://cloud.google.com/compute/docs/instances/creating-instance-with-custom-machine-type#gcloud):
```sh
gcloud container clusters create \
    "michael-custom-type" \
    --region "<>" \
    --release-channel "stable" \
    --machine-type "custom-4-5120" \
    --num-nodes 2
```

Install KC with a standard `helm install`.

Wait for it to start, port forward, load the UI.

Assets page showing custom type:
<img width="683" alt="image" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/17585786/462ea822-f518-4841-92c7-2c7e89d1fac1">

Cluster sizing page with reproduced error:
<img width="704" alt="image" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/17585786/c823f53c-6b95-4621-90ae-0c31e675ef4d">

**Comment by kwombach12** [comment]
Thanks @michaelmdresser I will log a bug for us to resolve this.
