### ISSUE TITLE
Change -0 to 0 on the Allocation page and Allocation API

### ISSUE THREAD

**Issue by ivankube** [kubecost/cost-analyzer-helm-chart#2281]
**Describe the bug**  
Customer is getting negative numbers and -0s on Allocation UI and Allocation API.

**Expected behavior**  
Round very small numbers to 0
Replace -0 with 0

**Screenshots**  
![1fva81lhhr1a88-image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/97049075/2db509cb-d12a-458e-811a-347ccca0c9b9)
![1fva81lhhr1bkd-image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/97049075/4ea00bcf-aeed-432f-8849-1c03783d2bca)
![1fva81lhhr1bsf-image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/97049075/c8bef21e-f8da-45a2-8dcd-10fc4dc94085)

**Collect logs (please complete the following information):**
Allocation API

```
```minutes: -0.05, 
cpuCores: 0, 
cpuCoreRequestAverage: 0.1, 
cpuCoreUsageAverage: 0, 
cpuCoreHours: -0.00008, 
cpuCost: -0.00138, 
cpuCostAdjustment: 0, 
cpuEfficiency: 0, 
gpuCount: 0, 
gpuHours: 0, 
gpuCost: 0, 
gpuCostAdjustment: 0, 
networkTransferBytes: 0, 
networkReceiveBytes: 0, 
networkCost: 0, 
networkCrossZoneCost: 0, 
networkCrossRegionCost: 0, 
networkInternetCost: 0, 
networkCostAdjustment: 0, 
loadBalancerCost: 0, 
loadBalancerCostAdjustment: 0, 
pvBytes: 0, 
pvByteHours: 0, 
pvCost: 0, 
pvs: null, 
pvCostAdjustment: 0, 
ramBytes: 0, 
ramByteRequestAverage: 20971520, 
ramByteUsageAverage: 0, 
ramByteHours: -17476.26667, 
ramCost: -0.00001, 
ramCostAdjustment: 0, 
ramEfficiency: 0, 
externalCost: 0, 
sharedCost: 0, 
totalCost: -0.00138, 
totalEfficiency: 0, 
rawAllocationOnly: null``` 

**Please share the support case, if any**  
https://kubecost.zendesk.com/agent/tickets/4128

**Comment by kwombach12** [comment]
Thanks @ivankube I agree that we should clean this up.
