### ISSUE TITLE
Add official support for GKE Autopilot

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#2282]
**What problem are you trying to solve?**
Accurate Kubernetes cost allocation for [GKE Autopilot](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview) clusters.

[Autopilot is now the default mode of operation for Google Kubernetes Engine clusters.](https://cloud.google.com/blog/products/containers-kubernetes/gke-autopilot-is-now-default-mode-of-cluster-operation)

We've tested it a few times unsuccessfully. Quite a few modifications need to be made to our deployment even to get Kubecost deployed. On top of that, Autopilot clusters have much tighter restrictions around the control plane API and what workloads can access.

Reference:
https://kubecost.slack.com/archives/C01CW6V54CQ/p1683146712396509

**Describe the solution you'd like**
Official support for GKE Autopilot in Kubecost, including reconciliation.

**Describe alternatives you've considered**
Not running Kubecost on Autopilot clusters

**How would users interact with this feature?**
Code changes? Customized helm templates/values?

**Comment by kwombach12** [comment]
@srpomeroy Thanks for logging this - something to consider for 105

**Comment by srpomeroy** [comment]
More conversations
https://kubecost.slack.com/archives/G01MN4R06MB/p1695677407128239

https://kubecost.slack.com/archives/C0324E0F9L5/p1695669081558209

**Comment by chipzoller** [comment]
This has internally been marked as done. Closing. See also https://docs.kubecost.com/install-and-configure/install/provider-installations/gke-autopilot-install.
