### ISSUE TITLE
Overview page time range (window) consistency

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#2286]
**What problem are you trying to solve?**
The top left of the Overview page says "Last 7 days" which gives the reader the impression that all numbers/charts represent 7 days of data. However the "Possible Savings" and maybe others represents a Monthly savings. This has caused confusion for Enterprise customers.
<img width="1390" alt="overview1" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/17748044/b1507eef-aadd-4b7e-9afb-0046a41d2195">

To confirm this, compare the Overview page "Possible Savings" with the Savings page "Estimated monthly savings available", and they should match.
<img width="1354" alt="savings1" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/17748044/3ed9e969-ab22-4222-9d40-57c98a621dda">

**Describe the solution you'd like**
Preferably have all data presented on the overview page would represent 7 days. if thats not possible, add a clearly visible text with the actual window displayed.

**Comment by MrJW27** [comment]
@kwombach12 - Can we escalate this please and get an ETA? thank you

Edit: looks like this will be fixed on the v1.104 release

**Comment by kwombach12** [comment]
I believe @nealormsbee already has a PR out for a fix here! https://github.com/kubecost/cost-analyzer-frontend/pull/2077

**Comment by nealormsbee** [comment]
Yep, this is fixed in 104 :+1:

**Comment by chipzoller** [comment]
Fixed. Closing.
