### ISSUE TITLE
Advanced Reports Error 500 CloudCost Store is empty

### ISSUE THREAD

**Issue by Joseph-Irving** [kubecost/cost-analyzer-helm-chart#2291]
---

**Describe the bug**  
After upgrading from 101.2 to 102.2, the advanced reports page no longer displays any data.
In the browser I'm seeing this error:
```
index-c81f0471.js:165 Uncaught (in promise) Error: Got a non-2XX response code.
        Status: 500
        Reason: {"code":500,"data":null,"message":"failed to fetch cloud cost data: CloudCost Store is empty"}
    at Object.fetch (index-c81f0471.js:165:59016)
    at async index-c81f0471.js:541:17378
```
Diagnostics say that everything is fine, I still seem to be able to see all our assets and kubernetes resources in the other areas.

I can see this error in the frontend container
```
[31/May/2023:09:07:31 +0000] "GET /model/allocation/external?window=7d&aggregate=namespace&accumulate=true&shareTenancyCosts=true&shareNamespaces=&shareLabels=&shareOverhead=0&cloudBreakdown=service&cloudJoin=label%3Akubernetes_namespace HTTP/1.1" 500 94 "https://redacted.com/advanced-reporting?breakdown=service" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "217.18.21.2,10.140.30.134"
```
But I can't see any errors in the cost-model container.
Also tried upgrading to 103.x and the same thing occurred.

**Screenshots**  
![Screenshot 2023-05-31 at 10 01 50](https://github.com/kubecost/cost-analyzer-helm-chart/assets/15195889/b5ab4fc7-4912-4eca-abd5-2456cdd67328)

**Comment by kwombach12** [comment]
Thanks @Joseph-Irving. Are you using our new Cloud Costs API?

**Comment by Joseph-Irving** [comment]
I don't really know, it's not something I've explicitly enabled.
Is there an easy way to find out?
Seems like it needs explicit turning on from the docs https://docs.kubecost.com/apis/apis-overview/cloud-cost-api

**Comment by kwombach12** [comment]
@Joseph-Irving yea by default, cloud costs is off. To enable, you can see our documentation here: https://docs.kubecost.com/using-kubecost/navigating-the-kubecost-ui/cloud-costs-explorer. 

You aren't required to use it, so we will investigate this issue to see why this is happening

**Comment by Joseph-Irving** [comment]
ok, I tried enabling the cloud cost explorer and it is now working again, thanks.

**Comment by thomasvn** [comment]
Closing this one as it seems like you've got it working. Feel free to re-open if you've got a follow-up here!
