### ISSUE TITLE
Add pills that contain the tags for cloud resources on each line item on the cloud costs page

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#2292]
**What problem are you trying to solve?**
It's not easy to verify the tags in the UI for each line item listed in the cloud cost page

**Describe the solution you'd like**
Would like the key value pair listed with each line item in the cloud cost page. Similar to previous versions and what's available today in the assets page
<img width="972" alt="image" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/36980248/6a57c9ce-b76f-4d70-9c15-bb985f18d0bf">

**Describe alternatives you've considered**
Looking at the api json output

**How would users interact with this feature?**
Users would query and filter for specific items, including tags/labels and validate the out of cluster resources have these tags associated with them

**Comment by kwombach12** [comment]
Thanks @mmurph3 we will take a look at this in future releases!

**Comment by wamak9** [comment]
+1

**Comment by chipzoller** [comment]
These "pills" are available per each row in the Cloud Costs page once drilled in. Closing.
