### ISSUE TITLE
Allocations Custom Date Picker not sending correct window in the API call

### ISSUE THREAD

**Issue by passionInfinite** [kubecost/cost-analyzer-helm-chart#2304]
Thanks for your interest in Kubecost!  To ensure you get the help you need, please follow these guidelines:

- If you have questions about product functionality/usage or need assistance with product installation/configuration, please email support@kubecost.com, where our support engineering team will be happy to help!
- If you have a reproducible bug or a feature request, you're in the right place.  Please include the information requested below.

---
# For reproducible bugs, please provide the following

**Describe the bug**  
In the Allocations Page in Dashboard when the custom start and end date is selected, the corresponding endpoint call (`/model/allocation/view`) uses incorrect date for the end date.  For example: if the dates from the picker is selected as April 01, 2023 and end date as April 29th, 2023 then the corresponding API call uses window as 
`window=2023-04-01T00%3A00%3A00Z%2C2023-04-30T00%3A00%3A00Z`

The end date seems to be 1 date ahead then what's selected in the date picker.

**To Reproduce**  
1. Go to 'Allocations Page'
2. Open the Network tab in inspect.
3. Click on '7 days' and select custom range: start date as April 01, 2023 and end date as April 30, 2023 
4. Click on the `/model/allocation/view` API call and select Parameters of the request.
5. Check the window parameter the end date is 1 date ahead then selected.

**Expected behavior**  
What ever start and end date is selected must be exactly passed to the model API endpoint call.

**Screenshots**  
![Screenshot 2023-06-02 at 11 24 22 AM](https://github.com/kubecost/cost-analyzer-helm-chart/assets/16861318/32b1a5a9-2a30-452f-835a-32ead873112e)

**Collect logs (please complete the following information):**
- Run `helm ls` and paste the output here:
- If the pod is stuck in init, run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-init` and paste output here:
- If a page is broken or not loading, open your javascript developer console and paste the ouput here:
- Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-server` and paste the output here:
- Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-model` and paste the output here:
- Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-frontend` and paste the output here:

**Please share the support case, if any**  
This is most commonly a Zendesk ticket number or link.

**What impact will this have on your ability to get value out of Kubecost?**
The allocation cost is incorrectly shown because of this issue.

**Comment by kwombach12** [comment]
Thanks @passionInfinite we will resolve this ASAP

**Comment by kirbsauce** [comment]
@kwombach12 has this been scheduled?

**Comment by kwombach12** [comment]
@kirbsauce I have this as a critical issue for 104

**Comment by kirbsauce** [comment]
thanks @kwombach12 , much appreciated!

**Comment by thomasvn** [comment]
> For example: if the dates from the picker is selected as April 01, 2023 and end date as April 29th, 2023 then the corresponding API call uses window as
`window=2023-04-01T00:00:00Z,2023-04-30T00:00:00Z`

@kwombach12 @kirbsauce I believe this behavior is correct? In order to capture all 24hrs of data for April 29th, we need to set the window to the 0th hour of April 30th?

**Comment by kirbsauce** [comment]
@thomasvn to weigh in as the author, but I would expect this to pick up data from 4/30 00:00:00 as a corner case. I guess the accuracy depends on if we're using < or <=.  Agree semantics play a part in this.

**Comment by kwombach12** [comment]
@thomasvn you are correct. We use the 0th hour of the following day to ensure we get all data from the previous day. Closing this issue as this is WAI
