### ISSUE TITLE
Add Log Format and Log Level to kubecost-network-costs, similar to kubecost-model

### ISSUE THREAD

**Issue by timroh** [kubecost/cost-analyzer-helm-chart#2309]
Hi,

we have recently deployed Kubecost enterprise and ran into inconsistencies in logging configuration between kubecost-network-costs and kubecost-model. While kubecost-model supports LOG_LEVEL and LOG_FORMAT and allows logging in JSON format, kubecost-network-costs only supports the -v flag for configuring the log-level and no configuration options for log format.

We would like to
 - use JSON logging everywhere for easier log parsing without configuring any parsing rulesets.
 - use the same parameters on all containers to make logging configuration easier to understand and consistent across kubecost components.

**Comment by kwombach12** [comment]
@TimRoh This makes sense to me. We will look to tackle this in a future release

**Comment by chipzoller** [comment]
Captured in https://github.com/kubecost/features-bugs/issues/81. Closing this.
