### ISSUE TITLE
KSM metric names are outdated 

### ISSUE THREAD

**Issue by dorsegal** [kubecost/cost-analyzer-helm-chart#2312]
When running diagnostic I can see an error with KSM
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/7013837/de5508ef-8d87-4596-ba70-293c03b203dd)

I am using my own KSM with latest version and according to their docs https://github.com/kubernetes/kube-state-metrics/blob/main/docs/node-metrics.md
Those metrics should be change to:
`kube_node_status_allocatable_cpu_cores` ->  `kube_node_status_allocatable{resource="cpu"}`
`kube_node_status_capacity_cpu_cores` -> `kube_node_status_capacity{resource="cpu"}`

Versions
- Kubecost 1.103.4 AWS optimized
- KSM 2.7.0

**Comment by kwombach12** [comment]
@thomasvn can you take a look at this one?

**Comment by thomasvn** [comment]
Hey @dorsegal! By default, Kubecost should be [emitting KSM metrics](https://docs.kubecost.com/architecture/user-metrics). Is this something you disabled (following [this doc](https://docs.kubecost.com/architecture/ksm-metrics))?

**Comment by dorsegal** [comment]
@thomasvn Yes I have disabled KSMV1metrics because we are using our own KSM and we had duplications.

I deployed Kubecost using helm-chart and this is the settings I have regarding KSM
```
kubecostMetrics:
  emitKsmV1Metrics: false

prometheus
  kube-state-metrics
    disabled: true
```

> (following [this doc](https://docs.kubecost.com/architecture/ksm-metrics))
 
After reading this I added 
`emitKsmV1MetricsOnly: true` to `kubecostMetrics` Should it fix my issue?

**Comment by thomasvn** [comment]
Yes! Using the following config should fix your issue, as Kubecost does depend on a few KSMv1 metrics.

```yaml
kubecostMetrics:
  emitKsmV1MetricsOnly: true 
  emitKsmV1Metrics: false
```

**Comment by dorsegal** [comment]
Ok so after enabling it I still had duplications and I had omit these metrics
```
kubecostProductConfigs
  metricsConfigs:
    disabledMetrics:
      - kube_node_status_allocatable
      - kube_node_status_capacity
      - kube_namespace_labels
      - kube_pod_labels
      - kube_pod_owner
      - kube_node_status_condition
      - kube_node_labels
```

eventually leaving only 
```
kube_node_status_allocatable_cpu_cores
kube_node_status_capacity_cpu_cores
```

**Comment by dorsegal** [comment]
Another issue in diagnostic pages 

### 1.104.0
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/7013837/e435f44d-68f7-4468-85e7-46cec74ec89d)


It looks like the query for diagnostic was changed


### 1.103.4
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/7013837/adeb187a-a0e8-4529-9e0c-4e1c9f58c9b5)

`absent_over_time(kube_node_status_capacity_cpu_cores[5m]` -> `absent_over_time(kube_node_status_capacity_cpu_cores[5m] )%!(EXTRA string=)`

I don't know if this is intentionally or by mistake but my current prometheus implementation (victoria-metrics) does not support `%!(EXTRA string=)`

**Comment by kwombach12** [comment]
@nealormsbee This is related to the diagnostics issue we are currently working on correct?

**Comment by qwe765** [comment]
I have the same issue as @dorsegal with version 1.104.0. I use my own KSM (v2.6.0) and Prometheus (build v2.36.2). 
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/58135000/a4314138-2db5-49cc-8c9b-dc05406410b1)
Logs from pod:
```
2023-06-12T15:09:31.149586601Z ERR prometheus diagnostic kubecostRecordingRuleCPUUsage failed with error: Prometheus communication error: absent_over_time(kubecost_container_cpu_usage_irate[5m] )%!!(MISSING)(EXTRA string=)
2023-06-12T15:09:31.150385983Z ERR prometheus diagnostic cadvisorWorkingSetBytesMetric failed with error: Prometheus communication error: absent_over_time(container_memory_working_set_bytes{container="cost-model", container!="POD", instance!=""}[5m] )%!!(MISSING)(EXTRA string=)
2023-06-12T15:09:31.151138871Z ERR prometheus diagnostic ksmMetric failed with error: Prometheus communication error: absent_over_time(kube_pod_container_resource_requests{resource="memory", unit="byte"}[5m] )%!!(MISSING)(EXTRA string=)
2023-06-12T15:09:31.155568465Z ERR prometheus diagnostic ksmCpuCapacityMetric failed with error: Prometheus communication error: absent_over_time(kube_node_status_capacity_cpu_cores[5m] )%!!(MISSING)(EXTRA string=)
2023-06-12T15:09:31.156324172Z ERR prometheus diagnostic ksmAllocatableCpuCoresMetric failed with error: Prometheus communication error: absent_over_time(kube_node_status_allocatable_cpu_cores[5m] )%!!(MISSING)(EXTRA string=)
2023-06-12T15:09:31.157074127Z ERR prometheus diagnostic cadvisorMetric failed with error: Prometheus communication error: absent_over_time(container_cpu_usage_seconds_total[5m] )%!!(MISSING)(EXTRA string=)
```

Is these queries is broken or some other issue here?
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/58135000/8c477286-5c4a-4e5c-ba57-4674613e2e22)

**Comment by nealormsbee** [comment]
@kwombach12 yes it is.

@qwe765 @dorsegal the `%!(EXTRA string=)` substring is indeed not supported by Prometheus; it's a bug. That is the text returned by Golang when an extra format parameter is assigned to `fmt.Sprintf()`. An example would be

```golang
name := "Neal"
myString := fmt.Sprintf("Hello, %s", name, "")
// myString is now "Hello, Neal%!(EXTRA string="")
```

This was addressed in [this PR](https://github.com/opencost/opencost/pull/1981) a few days ago. I believe it will be resolved in the 1.104.1 patch we plan to build today. cc @nik-kc @cliffcolvin to keep me honest here.

I do not believe this addresses the original issue where we have older versions of KSM metrics. That one is new to me:

> `kube_node_status_allocatable_cpu_cores` -> `kube_node_status_allocatable{resource="cpu"}`

**Comment by thomasvn** [comment]
@dorsegal @qwe765 When you get the chance, could you upgrade to v1.104.1 and check the diagnostics page again?

**Comment by qwe765** [comment]
I use images from Amazon ECR Public Gallery, here 1.104.0 latest version
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/58135000/83b7f4ff-ea2a-436a-be70-2826732fa487)

**Comment by jabbera** [comment]
> @dorsegal @qwe765 When you get the chance, could you upgrade to v1.104.1 and check the diagnostics page again?

I upgraded to 1.104.0 and hit this issue. 1.104.1-rc2 fixes it.

**Comment by qwe765** [comment]
I updated version to 1.104.1 and it helped solve the problem. thank you!
