### ISSUE TITLE
Ability to aggregate and/or  filter by gcp project in allocations page to understand which cluster belongs to which project

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#2313]
**What problem are you trying to solve?**
 My use case is I want to select the data from Allocation for a certain project only.  I can aggregate by cluster, but I don't know which cluster belong to which project, or if the cluster has the same name but different project then if they will be sum togethe

**Describe the solution you'd like**
Project custom label or ability to filter by gcp project (auto complete/drop down preferred) in allocations so user can aggregate and filter by gcp project and understand which project the cluster being displayed is in.

**Describe alternatives you've considered**
labeling/tagging

**How would users interact with this feature?**
See above

**Comment by mmurph3** [comment]
Don't see the project info in the api response:


```
{id: "gcp-test-1-multi-cloud", name: "gcp-test-1-multi-cloud", cpuCost: 12.782495279872297, gpuCost: 0,…}
averageCpuUtilization
: 
0.2593038930631137
averageRamUtilization
: 
0.9158477197405742
cpuCost
: 
12.782495279872297
efficiency
: 
0.5263036199871198
externalCost
: 
0
gpuCost
: 
0
id
: 
"gcp-test-1-multi-cloud"
loadBalancerCost
: 
18.650000000000006
name
: 
"gcp-test-1-multi-cloud"
networkCost
: 
16.1744807645504
pvCost
: 
7.804154387820737
ramCost
: 
8.761325742819274
sharedCost
: 
13.62791487407642
totalCost
: 
77.80037104913913
```

**Comment by kwombach12** [comment]
Thanks @mmurph3 I dont think we have the 'GCP Project' data in the allocations api yet, but its something we can look to add in a future release

**Comment by chipzoller** [comment]
Closing, stale.
