### ISSUE TITLE
SAML- Is there an Unauthorized Page in Kubecost UI when the group filters don't match?

### ISSUE THREAD

**Issue by srisek** [kubecost/cost-analyzer-helm-chart#2314]
Currently we are using SAML (OKTA) to configure access to Kubecost. Below is a context of the configuration we are using with the corresponding entries in the group_filter config map.

SAML Config:

rbac:
  enabled: true
  groups:
    - name: admin
      enabled: true
      assertionName: kubecost_groups
      assertionValues:
        - "AD-Admin"
        - "AD-Operator"
    - name: readOnly
      enabled: true
      assertionName: kubecost_groups
      assertionValues:
        - "AD-KUBECOST-Analyzer"
  customGroups:
    - assertionName: kubecost_groups

group_filter Config Map:

{
  "AD-Admin": {
    "allocationFilters": [
      {
        "namespace": "*",
        "cluster": "*"
      }
    ]
  },
  "AD-Operator": {
    "allocationFilters": [
      {
        "namespace": "*",
        "cluster": "*"
      }
    ]
  },
  "AD-KUBECOST-Analyzer": {
    "allocationFilters": [
      {
        "namespace": "",
        "cluster": "*"
      }
    ]
  }
}

I am looking out to provide access to the users who belong only to these groups. When the SAML response contains any other groups apart from the above for a user , it should not authorize the user to view the UI. Is there a specific configuration that can be enabled to display "Not Authorized" / "Access Denied"

As of now with the above configuration, when a user belongs to the AD-Admin or Ad-Operator , the UI is displayed with full admin mode and if a user doesn't belong to a any of the above groups it is defaulting to the user to access the UI in read only mode.

Would it be nice if the user access is denied if no groups are matched from the group filters config map.

**Comment by kwombach12** [comment]
@thomasvn Can you take a look at this please?

**Comment by thomasvn** [comment]
@srisek To check my understanding, if a user does not belong to Okta Groups `AD-Admin`, `AD-Operator`, or `AD-KUBECOST-Analyzer`, then they should not be able to load the Kubecost UI. Correct? This should be true even without the `configmap/group-filters`.

**Comment by srisek** [comment]
The users are able to load the UI even if they are not a part of  AD-Admin, AD-Operator, or AD-KUBECOST-Analyzer groups. Seeing this in the logs 

for example below one, for example, the user is only a part of these groups and able to get to UI in readonly mode instead of access denied

2023-06-09T18:24:42.776191976Z INF No filters found for I-Terraform-SiteAdmin-Team
2023-06-09T18:24:42.776289922Z INF No filters found for I-ADMIN
2023-06-09T18:24:42.777121348Z INF No filters found for I-Staff

**Comment by thomasvn** [comment]
Ok, thanks for those details! This doesn't seem like the expected behavior for Okta SAML, and I'm unable to reproduce the issue. When I login with a user who is not part of an approved group, the Okta SSO page shows me:
> User is not assigned to this application.

Could you remove your `configmap/group-filters` and try again? Could you also send the following to support@kubecost.com so we can take a closer look?

* [Bug Report](https://docs.kubecost.com/troubleshooting/bug-report)
* `helm get values kubecost`
* A [HAR file](https://docs.kubecost.com/troubleshooting/capture-a-har-file) when authenticating into Kubecost with a user not part of `AD-Admin`, `AD-Operator`, or `AD-KUBECOST-Analyzer` groups

**Comment by chipzoller** [comment]
Closing, stale.
