### ISSUE TITLE
Misclassified GCP network costs

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2317]
**Describe the bug**  
After deploying Kubecost on GKE and enabling network costs, some costs related to GCP are classified as Internet rather than In-Zone, leading to higher perceived network costs on objects like Google Cloud Storage.

**To Reproduce**  
1. Deploy a cluster on GCP that has access to a GCP bucket (for example, Thanos using a GCP bucket for the backend).
2. Deploy Kubecost with Network Costs and the `networkCosts.config.services.google-cloud-services: true` setting.
3. After network traffic has been monitored, see the incorrect classification.

**Expected behavior**  
Network requests made within GCP are classified as within GCP, so no network charges get applied.

**Screenshots**  
<img width="1210" alt="image" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/43491549/807ed65e-0563-454a-9732-ec1befcaa637">

More detailed screenshots with GCP billing data can be found in the original [Zendesk ticket](https://kubecost.zendesk.com/agent/tickets/4287)

**Collect logs (please complete the following information):**
Reproduced and accessible within the KC GCP account:

```
gcloud container clusters get-credentials keith-repro-zd4287 --zone us-central1-c --project guestbook-227502
```

**Please share the support case, if any**  
[ZD 4287](https://kubecost.zendesk.com/agent/tickets/4287)

I also found this [GitHub issue](https://github.com/kubecost/cost-analyzer-helm-chart/issues/1720), which may be related to the same problem.

**What impact will this have on your ability to get value out of Kubecost?**
More accurate network costs on GCP with the configuration `networkCosts.config.services.google-cloud-services: true` flag.

**Comment by kwombach12** [comment]
Thanks @keithhand I have filed a bug for this. We will take a look ASAP

**Comment by keithhand** [comment]
Interestingly, when the customer who brought this up enabled cloud integration, it didn't seem like we were getting any adjustments from the cloud bill, either. Not sure if this is related, but without reconciliation, it's significantly increasing costs when network costs are enabled.

Last seven days. When we were investigating, most of these charges seemed related to GCP services.
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/43491549/751fbc02-3d43-4af3-bde7-ad19d579e604)

**Comment by AjayTripathy** [comment]
I think the primary issue to focus on here is the adjustments not coming in since that's the simplest way for costs to align vs correctly classifying all. costs. @keithhand are you seeing adjustments anywhere else? Can you make sure they are using the GCP Detailed Billing Report?

**Comment by keithhand** [comment]
Update from the User: Detailed billing is not enabled, which would help explain why reconciliation isn't occurring. I suggested updating the billing report or manually specifying the GCP services within the network costs configuration: https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L744-L752.

**Comment by chipzoller** [comment]
Looks complete, otherwise stale.
