### ISSUE TITLE
Table in new adv reporting page that summarizes Date Range, Total Cloud Costs, Total Kubernetes Costs and Combined Total 

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#2320]
**What problem are you trying to solve?**
From the tests I see, it doesn't illustrate clearly the total spend for Cloud Infrastructure/Resources, kubernetes costs and the combined total costs.

**Describe the solution you'd like**
A table on the page that summarizes the above.

**Describe alternatives you've considered**
Adding the total costs up manually 

**How would users interact with this feature?**
Users would create a report for cloud resources and kubernetes in 'adv report - cost centers'. The report would provide a summary table

**Comment by kwombach12** [comment]
@mmurph3 I believe we have a 'Cloud' column in the cost center reports which shows the total spend for cloud resources. We also have a 'Costs' column for combined total costs.

**Comment by chipzoller** [comment]
Kubecost now has the Collections feature which should address this.
