### ISSUE TITLE
Export Adv Reporting - costcenters to pdf, csv and  scheduled cadences

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#2321]
**What problem are you trying to solve?**
I'm able to create a report but I cannot send it out on a scheduled cadence or export it. 

**Describe the solution you'd like**
I'd like the flexibility available in allocations, assets, cloud reports. Need reports explaining the costs of the entire stack (k8s and cloud costs) for showback/chargeback.

**Describe alternatives you've considered**
screenshot

**How would users interact with this feature?**
Create a report, download it to pdf and/or csv. 
Create a report and schedule a cadence at which to send it out.

**Comment by kwombach12** [comment]
@mmurph3 Totally agree with you here. We will try to get this in 106

**Comment by chipzoller** [comment]
This is already in the product. Closing.
