### ISSUE TITLE
Enable Spec Cost Prediction API to support JSON format

### ISSUE THREAD

**Issue by linhlam-kc** [kubecost/cost-analyzer-helm-chart#2322]
**What problem are you trying to solve?**
Enable Spec Cost Prediction API to support JSON format. As of now, [Spec Cost Prediction API ] (https://docs.kubecost.com/apis/apis-overview/spec-cost-prediction-api) only supports YAML format. It will help other K8s native solution such as Kyverno easily adopts this API to integrate with their solution. 

**Describe the solution you'd like**
[Spec Cost Prediction API ] (https://docs.kubecost.com/apis/apis-overview/spec-cost-prediction-api) accepts payload in JSON format.

**Describe alternatives you've considered**
N/A

**How would users interact with this feature?**
Another K8s native solution that natively use JSON can adopts this API easily to integrate with Kubecost.

**Comment by chipzoller** [comment]
Triaged internally.
