### ISSUE TITLE
Add `LOG_FORMAT` environment variable to cluster controller

### ISSUE THREAD

**Issue by simonellefsen** [kubecost/cost-analyzer-helm-chart#2327]
**What problem are you trying to solve?**
The problem with ansi coloring of log data is when we forward the logs to a search engine where strings like "[0mERR" makes it almost impossible to search for log data.

Maybe there already is a way to do this, but then I could not find any documentation on the subject.

I tried adding the environment variable NO_COLOR but also that did not seem to work (I was just guessing/hoping that the logger you are using might support this)

**Describe the solution you'd like**
A option to disable ansi coloring of log output.

**How would users interact with this feature?**
No impact as far as I can tell.

**Comment by kwombach12** [comment]
@thomasvn are you aware of anyway to disable the color in the logs output? If not, this is a good candidate for a future release.

**Comment by thomasvn** [comment]
@simonellefsen An alternative option to remove coloring of log output would be to set the following. Some more details at the bottom of [this README](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/README.md). Let us know if this would work!

```yaml
kubecostModel:
  extraEnv:
  - name: LOG_FORMAT
    value: json
```

**Comment by simonellefsen** [comment]
So yes, the LOG_FORMAT="json" works for the kubecostModel, thanks

But it does not seem to work for the clusterController.

I tried with CC_LOG_FORMAT="json" and LOG_FORMAT="json"

**Comment by thomasvn** [comment]
Yes, I don't believe cluster controller supports the `LOG_FORMAT` environment variable yet. @michaelmdresser to confirm?

**Comment by michaelmdresser** [comment]
> Yes, I don't believe cluster controller supports the LOG_FORMAT environment variable yet. @michaelmdresser to confirm?

Correct. Cluster Controller does not currently support configuring the log format, nor does it have color toggling. This is a relatively straightforward thing to add, we just need to find the time for it.

**Comment by thomasvn** [comment]
Thanks @michaelmdresser! @kwombach12, when you get back can we re-triage this and see if this enhancement request can make it into v1.105?

**Comment by kwombach12** [comment]
@thomasvn I dont think we will have the time to add this in 105. Lets add to our FR tracker for a future release

**Comment by chipzoller** [comment]
Captured in https://github.com/kubecost/features-bugs/issues/81. Closing this.
