### ISSUE TITLE
Support for S3 buckets with Object Lock enabled for federated ETL.

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#2332]
**What problem are you trying to solve?**
We have a customer that prefers to enable [S3 Object lock](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html) on their buckets. They were not able to get federated ETL to work properly until they disabled object locking. When enabled the following error occurred.

```
ERR ETL: Containerstats: Failed to write ETL file '**<REDACTED>**' to federated storage: upload s3 object: 
Content-MD5 OR x-amz-checksum- HTTP header is required for Put Object requests with Object Lock parameters
```

They have currently disabled object locking as a work around.

In researching the issue it was determined Kubecost may use a fork of Thanos's object store under the hood, which in turn may utilize minio.

- https://github.com/opencost/opencost/blob/be9feb279d4374885bb3ba433e795ac6813ea7a9/go.mod#L40
- https://github.com/opencost/opencost/blob/be9feb279d4374885bb3ba433e795ac6813ea7a9/pkg/storage/s3storage.go#L116-L119

It also appears this feature may have been added to minio last year.

- https://github.com/minio/minio/discussions/15723
- https://github.com/minio/minio/issues/14885

**Describe the solution you'd like**
Update Kubecost to include checksum support (If the linked minio feature is relevant) and document how to enable this support if needed.

**Comment by chipzoller** [comment]
Closing, stale.
