### ISSUE TITLE
Support for prepend wilcard

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#2337]
**What problem are you trying to solve?**
It's not possible to do prepend wildcards. This makes it difficult to filter because many ns' end with -example so we'd like to see everything that ends in -example.

**Describe the solution you'd like**
Ability to prepend a wildcard.

**Describe alternatives you've considered**
Appending wildcards but this does not work as intended.

**How would users interact with this feature?**
Aggregate by k8s object and add a filter `*-example`

If we need to prioritize - doing ns agg and filter by all ns' using using a *-example with filter.

**Comment by kwombach12** [comment]
@mmurph3 I certainly see the need for this. Lets prioritize for a future release

**Comment by chipzoller** [comment]
Filters now have an "ends with" selection so effectively the same thing. Closing.
