### ISSUE TITLE
File Backup showing disabled in UI

### ISSUE THREAD

**Issue by praveenkumar0566** [kubecost/cost-analyzer-helm-chart#2338]
**Describe the bug**  
The FileBackup feature in UI shows disabled even after enabling all necessary values, The files are getting backed up to S3 bucket though. 

**To Reproduce**  
Enable File Backup feature, UI shows disabled

1. Go to the Diagnostics page
2. scroll down to file backup section
3. shows disabled

**Expected behavior**  
The UI should show **Enabled**

**Screenshots**  
![1fva81likarv6n-image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/102574445/de32dc48-bcd7-4413-877e-9095e916c083)

**Bug report**
Please generate a bug report and attach the resulting `kubecost-bug-report.txt` here:
[kubecost-bug-report.txt](https://github.com/kubecost/cost-analyzer-helm-chart/files/11737206/kubecost-bug-report.txt)
This is the internal demo cluster bug report
https://demo.kubecost.xyz/settings

**Please share the support case, if any**  
https://kubecost.zendesk.com/agent/tickets/4320

**Comment by kwombach12** [comment]
@praveenkumar0566 Thanks for logging this. I have created a bug report and we will address in our next release

**Comment by wamak9** [comment]
This is a long standing issue, happening since 1.94.x I think.

**Comment by kwombach12** [comment]
@wamak9 We have an issue filed for this and will try to resolve in the next release

**Comment by wamak9** [comment]
Bump @kwombach12

**Comment by kwombach12** [comment]
@wamak9 This should be fixed in the 105 release that went out last week!

**Comment by wamak9** [comment]
so, fix is basically say enabled ?

cc: @kwombach12 

I ran into a issue where there is no back up happened for the whole month of June and I have to rebuild the whole ETL.
for more details please talk to Ivan Cherapau


So, it would be more ideal just to mention when the back was done  and for what time period it was done as well.

**Comment by kwombach12** [comment]
@wamak9 The fix that went in updates the value that 'File Backup' is based on. We now leverage the `bucketStoreEnabled` value to check if the ETL is backed up to a cloud bucket.

**Comment by kwombach12** [comment]
For some context, `bucketStoreEnabled` is equivalent to ETL_BUCKET_CONFIG (helm var: `$etlBucketConfigSecret`) set to something besides an empty string

**Comment by kwombach12** [comment]
Closing this issue as we believe it was resolved in 1.105
