### ISSUE TITLE
Case sensitivity in external tags/labels 

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#2343]
**Describe the bug**  

I have an AWS S3 bucket tagged "Custom-Tag:kubecost", when aggregating by the label "Custom-Tag" or filtering by the label "Custom-Tag:kubecost" on the Cloud Costs page no results are returned.

There appears to be an issue related to the case and `-` to `_` remapping as aggregating by the label "custom_tag" or filtering by the label "custom_tag:kubecost" does produce the expected results. 

Additionally, the UI is partially displaying the case correctly...
<img width="832" alt="Screenshot 2023-06-13 at 2 38 19 PM" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/17748044/3c02c307-6fce-4b19-8470-8a515bedf3c7">

This was tested on Kubecost v1.104.0

**To Reproduce**  

1. Go to '[https://demo.kubecost.xyz/cloud](https://demo.kubecost.xyz/cloud)'
2. Aggregate by 'Custom-Tag' and see no results.
3. Aggregate by 'custom_tag' and see the expected results.

**Screenshots**  
AWS Config
<img width="1171" alt="Screenshot 2023-06-13 at 2 07 50 PM" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/17748044/046831b6-f294-408d-8132-0e78be4a6f48">

<img width="1217" alt="Screenshot 2023-06-13 at 2 08 05 PM" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/17748044/a9506c71-3508-44ce-8f7e-030bb671a0ad">

Aggregate by "Custom-Tag" (does not work)
<img width="1351" alt="Screenshot 2023-06-13 at 2 38 19 PM" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/17748044/fe3f4180-b535-4c41-b595-396afa5ef135">

Aggregate by "Custom_Tag" (does not work)
<img width="1418" alt="Screenshot 2023-06-13 at 2 10 18 PM" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/17748044/4e5c75dd-7c5e-4f44-9a21-990cddd28e1e">

Aggregate by "custom-tag" (does not work)
<img width="1351" alt="Screenshot 2023-06-13 at 2 43 09 PM" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/17748044/b9882eab-f27a-4236-b362-9ae4e897eb54">

Aggregate by "custom_tag" (does work)
<img width="1435" alt="Screenshot 2023-06-13 at 2 09 34 PM" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/17748044/e2144484-0769-43dc-9072-f6fa6cb174cd">

**Please share the support case, if any**  
https://kubecost.zendesk.com/agent/tickets/4263

**Comment by thomasvn** [comment]
Thanks @jcharcalla! I've logged this as a bug and we'll look to address this soon.

**Comment by danielpsf-grover** [comment]
This is such a critical issue for us that is causing issues with adopting Kubecost as the main cost tool within our company. Any status update on when this is going to be addressed?

**Comment by teevans** [comment]
@kwombach12 do we have a matching Jira issue for this?

**Comment by kwombach12** [comment]
@teevans we do: https://kubecost.atlassian.net/browse/BURNDOWN-148

**Comment by chipzoller** [comment]
Internally archived. Looks like has been documented [here](https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations#step-1-setting-up-a-cur) as a known limitation. Closing.
