### ISSUE TITLE
add ingressClassName to grafana chart

### ISSUE THREAD

**Issue by FernandoMiguel** [kubecost/cost-analyzer-helm-chart#2351]
**What problem are you trying to solve?**
We have different ingress classes, and need to expose bundled grafana

**Describe the solution you'd like**
for https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/charts/grafana/templates/ingress.yaml to include
```
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
```

**Describe alternatives you've considered**
other than port-fw, we are unable to access grafana

**How would users interact with this feature?**

**Comment by thomasvn** [comment]
@FernandoMiguel I think this is a good idea! Although, have you tried `https://kubecost.my.com/grafana/`? Currently, Grafana is configured to be served at that path by the Nginx running in the `cost-analyzer-frontend` container ([code ref](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.104/cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml#L270-L283)).

**Comment by FernandoMiguel** [comment]
That path shows a blank page. I didn't investigate further.

**Comment by FernandoMiguel** [comment]
FYI I am seeing this in developer tools when accessing /grafana
<img width="1681" alt="image" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/168366/551174a1-f324-4592-ae68-5eec3e547ce9">

this is on 1.103.4 (since I can get 104.0/1 to get healthy)

**Comment by thomasvn** [comment]
@FernandoMiguel Could you try using the exact path `/grafana/`?

**Comment by FernandoMiguel** [comment]
I can try, but even pressing the existing button from the kubecost settings page, with a URI to a specific dashboard, also leads to the same blank page

**Comment by thomasvn** [comment]
@FernandoMiguel Ok let me know how it goes when you try! Could you also try the following:

1. Go to `https://kubecost.my.com/request-sizing`
2. Click on a container
3. Click on the link to Grafana
