### ISSUE TITLE
Export CSV on Request Sizing Recommendations in the new UI

### ISSUE THREAD

**Issue by Tutuviz** [kubecost/cost-analyzer-helm-chart#2354]
**What problem are you trying to solve?**
In the new UI, I'm unable to generate the csv export of Request Sizing Recommendations (`/request-sizing`), only the Allocations (`/alocations`)

**Describe the solution you'd like**
I would love to have this feature in the new UI since the data is already there but i can only paginate through it

**Describe alternatives you've considered**
For now, the Classic UI is available to get the csv export, if was not there, the only data that I could get was with the allocation tab

**Comment by rossfisherkc** [comment]
Hey, @Tutuviz !

Looks like we added it in 1.104!
https://github.com/kubecost/cost-analyzer-helm-chart/releases
