### ISSUE TITLE
Outdated prometheus version

### ISSUE THREAD

**Issue by z0rc** [kubecost/cost-analyzer-helm-chart#2363]
**Describe the bug**  
Kubecost deploys outdated unsupported prometheus version

**To Reproduce**  

1. Deploy kubecost with default values
2. Deployed Prometheus version is 2.35.0

**Expected behavior**  
Prometheus version should be either latest, or at least LTS, see https://prometheus.io/docs/introduction/release-cycle/. With latest version prom memory footprint is reduced by ~15% which helps to operate kubecost in medium or big sized clusters.

**Screenshots**  
Not applicable.

**What impact will this have on your ability to get value out of Kubecost?**

**Bug report**
Unrelated.

**Please share the support case, if any**  
None.

**Comment by thomasvn** [comment]
Thanks @z0rc! This has been discussed internally within Kubecost as well. This should be no issue doing this with fresh installs of Kubecost but we will need to test this for existing installs of Kubecost.

If you're interested in upgrading your Prometheus immediately, you can do so by setting [.Values.prometheus.server.image.tag=v2.45.0](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.104/cost-analyzer/charts/prometheus/values.yaml#L548).

**Comment by z0rc** [comment]
@thomasvn I'm aware of this value. My question is more about sane defaults and how kubecost handles keeping them up to date.

**Comment by thomasvn** [comment]
@z0rc Understood. I'll update here as we continue to discuss internally.

**Comment by chipzoller** [comment]
No longer an issue. Prometheus is being maintained in modern releases. Closing.
