### ISSUE TITLE
The kubecostModel.utcOffset setting breaks the data if set to a negative value

### ISSUE THREAD

**Issue by maeghan-porter** [kubecost/cost-analyzer-helm-chart#2364]
**What problem are you trying to solve?**
I was setting the value `kubecostModel.utcOffset` on my helm install which doesn't actually show up in the values.yaml [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/c5a9176ec04ea9fe901060475b0868a13c159316/cost-analyzer/values.yaml#L387) or in the docs, however this is set as a default of "+00:00" in the aws eks-optimitzed values.yaml [here](https://raw.githubusercontent.com/kubecost/cost-analyzer-helm-chart/develop/cost-analyzer/values-eks-cost-monitoring.yaml). So, I googled to find that EST is UTC-05:00 and set the value to "-05:00" and it broke my install in the way described in the thread. No data showing up. Yet I saw no errors in the logs that indicated any issue.

**Describe the solution you'd like**
There is either a bug with this setting, something weird AWS is doing maybe, or this just needs to be better documented to make it clear what value is expected here.

**Describe alternatives you've considered**
The only alternative was to use the default setting of `+00:00` since I don't know how to make this work the way I would expect.

**How would users interact with this feature?**
This setting should work to set the utcoffset.

**Comment by thomasvn** [comment]
Thanks @maeghan-porter! In most cases I believe the default value for `kubecostModel.utcOffset` is recommended.

@linhlam-kc Could you comment on what the recommendation here is?

https://github.com/kubecost/cost-analyzer-helm-chart/blob/ae78cb78976efb8e0e632e32d30000a376d23004/cost-analyzer/values-eks-cost-monitoring.yaml#L59-L63

**Comment by chipzoller** [comment]
Closing, stale.
