### ISSUE TITLE
query service replica logs in bug report, PV storage checks in diagnostics

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#2366]
**What problem are you trying to solve?**
QSR will be used by large customers and the size of the PV should be monitored to avoid running out of space.

**Describe the solution you'd like**
Currently, on diagnostics we have:
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/31039225/62fc3389-17fa-497e-8d4c-c355adca04bb)

Add something like this for QSR PV. Potentially add a recommended size using our PV API:

```sh
curl -sg 'https://etl-fed.se-staging.kubecost.xyz/model/savings/persistentVolumeSizing?headroomPercent=5000&filterClusters=federated-primary' \
|jq -r '.recommendations[]'
```

Also add to Warnings:
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/31039225/23cd9a44-8520-4d19-989f-93a1b9dadc14)

gather pod logs in bug report:
```
/model/podLogs?selector=app%3Dquery-service&timeFrame=24h
```

Summary:
- [ ] PV size check / optionally add recommendation in diagnostics
- [ ]  Warnings on bell icon in UI
- [x] podLogs in bug report

**Describe alternatives you've considered**

updating doc for manual steps: <https://docs.kubecost.com/install-and-configure/install/etl-backup/query-service-replicas>

**How would users interact with this feature?**

**Comment by nealormsbee** [comment]
@jjarrett21 we were talking about things that might be good to pick up today if you finish converting the diagnostics page early. This could fit the bill pretty well and is also in diagnostics -- your head will be fresh on the code. Want to take a run at it?

EDIT: I guess the bell-icon warnings are outside of diagnostics but ¯\\_(ツ)_/¯

**Comment by jessegoodier** [comment]
> @jjarrett21 we were talking about things that might be good to pick up today if you finish converting the diagnostics page early. This could fit the bill pretty well and is also in diagnostics -- your head will be fresh on the code. Want to take a run at it?
> 
> EDIT: I guess the bell-icon warnings are outside of diagnostics but ¯\_(ツ)_/¯

thanks @nealormsbee  and @jjarrett21 ! The podLogs are #1 priority- if we could get that into 1.105. 

The others would be amazing. Please let me know if you need help testing.

**Comment by jessegoodier** [comment]
Thanks guys! I would say the #1 priority is the podLogs in the bug report.

**Comment by nealormsbee** [comment]
@jessegoodier the above PR will enable the QS pod logs. We haven't done the rest but I'm putting it on the list for 106 now. That PR is pretty simple. My hope is that it can be reviewed and merged Monday, then frontend will actually code freeze for the week and we'll have the pod logs available in bug reports.

**Comment by jessegoodier** [comment]
sounds great, thanks for the background info-

**Comment by chipzoller** [comment]
Query service replicas are no more. Closing.
