### ISSUE TITLE
HA support for Fed ETL

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#2371]
**What problem are you trying to solve?**
Please see internal [JIRA ticket](https://kubecost.atlassian.net/browse/CORE-331).

**Describe the solution you'd like**
We need an official HA solution for Fed ETL. Our current solution would not work for this arch https://docs.kubecost.com/install-and-configure/advanced-configuration/high-availability. Please see JIRA.

**Describe alternatives you've considered**
N/A

**How would users interact with this feature?**

**Comment by thomasvn** [comment]
Thanks @mmurph3 I think this is a good idea. I'll defer to @kwombach12 for product input once he returns.

**Comment by kwombach12** [comment]
@mmurph3 from the thread in the jira ticket, it seems the guide has been updated. Anything else needed here?

**Comment by chipzoller** [comment]
Closing, no longer relevant.
