### ISSUE TITLE
DescribeAddresses and DescribeVolumes fails with valid IRSA config

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#2377]
When using IRSA, Kubecost cannot access aws ec2 resources and logs the following messages even when the service account has the correct policy.

I back tested this with 1.101 and 1.102 and all versions have the issue.

error message:

WRN unable to get addresses: operation error EC2: DescribeAddresses, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: c63cf5bd-27d3-4919-8251-08fcf7ce7151, InvalidIdentityToken: No OpenIDConnect provider found in your account for https://oidc.eks.ca-central-1.amazonaws.com/id/2086E4D4C3BEAFFF61F3617142CA5DCC

WRN unable to get disks: operation error EC2: DescribeVolumes, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, failed to retrieve credentials, operation error STS: AssumeRoleWithWebIdentity, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: 97337482-f0e2-489d-b8e6-c9108a264d8e, InvalidIdentityToken: No OpenIDConnect provider found in your account for https://oidc.eks.ca-central-1.amazonaws.com/id/2086E4D4C3BEAFFF61F3617142CA5DCC

**To Reproduce**  

1. create a policy:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "KubecostSavingsAccess",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeAddresses",
                "ec2:DescribeVolumes"
            ],
            "Resource": "*"
        }
    ]
}
```

create an IRSA account with the policy: 
```sh
>eksctl create iamserviceaccount \
    --name kubecost-serviceaccount \
    --namespace kubecost \
    --cluster jesse-temp --region ca-central-1 \
    --attach-policy-arn arn:aws:iam::297945954695:policy/jesse-temp-savings-policy \
    --override-existing-serviceaccounts \
    --approve
```

install kubecost and view logs
```sh
helm install kubecost kubecost/cost-analyzer --version 1.104.1 \
  --set serviceAccount.create=false --set serviceAccount.name=kubecost-serviceaccount
```

**Expected behavior**  
no errors

**What impact will this have on your ability to get value out of Kubecost?**
savings reports broken for 
/orphaned-resources

**Comment by jessegoodier** [comment]
More testing: spot feed works with the same cluster. So IRSA itself is working.

**Comment by srpomeroy** [comment]
Not directly related but important to reference.
https://github.com/kubecost/cost-analyzer-helm-chart/issues/2167

**Comment by srpomeroy** [comment]
@jcharcalla Called out that it may be related to disabled regions. Similar error state to SCP disallowed regions.
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/15660532/459571b8-575f-42c5-8a26-9ab844517651)

![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/15660532/b6bd8806-9dcf-4afa-ab7b-8fdf5a5d7614)

**Comment by thomasvn** [comment]
@jessegoodier @srpomeroy Thanks for reproducing! I've logged this as a bug and we'll aim to resolve soon.

**Comment by pwouavre** [comment]
Hello,
 
I have the exact same issue here using kubecost version 1.104.4 ;)
Have a nice day !

**Comment by danjmccay** [comment]
I'm seeing the same issue. In IAM, I can see the linked role is accessing ap-southeast-1 when all of our resources are in eu-west-1.
<img width="728" alt="image" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/52407749/610eaa42-ce22-4f3f-bbc2-207c31f17369">

**Comment by srpomeroy** [comment]
> I'm seeing the same issue. In IAM, I can see the linked role is accessing ap-southeast-1 when all of our resources are in eu-west-1. <img alt="image" width="728" src="https://user-images.githubusercontent.com/52407749/253606187-610eaa42-ce22-4f3f-bbc2-207c31f17369.png">

That is normal. Kubecost currently looks for resources in all provider regions in order to populate the orphaned resources report.

**Comment by andrewhharmon** [comment]
I'm seeing this issue as well. No workaround at the moment?

**Comment by jessegoodier** [comment]
No workaround yet. There are a few variables, we are looking into this and well keep you updated when a fix is ready.

**Comment by cyphrsonic** [comment]
Are there any updates on a workaround to this issue? I'm working on doing an initial deployment via helm, and these errors are making it harder to spot the actual issues with my configuration.

**Comment by AjayTripathy** [comment]
I would propose we simply remove these logs or drop their warn level in an upcoming release. cc @cliffcolvin for additional triage

**Comment by danielrolfes2307** [comment]
Hi, any new developments and/or workarounds?

**Comment by jessegoodier** [comment]
> Hi, any new developments and/or workarounds?

We do need to update our documentation, thanks for the reminder.

This is resolved as of Kubecost 1.106. 
Are you using IRSA? Just be sure it has a policy that allows:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "DescribeCloudResources",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeAddresses",
                "ec2:DescribeVolumes"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by danielrolfes2307** [comment]
@jessegoodier 
I'm running Helm chart: 1.106.4 and still see the issue (?)
"You are not authorized to perform this operation. User: xxxx: assumed-role/kubecost-iam-role-20231103140434006600000002/1699343400001785339 is   not authorized to perform: ec2:DescribeVolumes with an explicit deny in a service  control policy"

It still seems to use these actions on "inactive" regions. I dont see the issue in the active regions.

**Comment by jessegoodier** [comment]
> @jessegoodier I'm running Helm chart: 1.106.4 and still see the issue (?) "You are not authorized to perform this operation. User: xxxx: assumed-role/kubecost-iam-role-20231103140434006600000002/1699343400001785339 is not authorized to perform: ec2:DescribeVolumes with an explicit deny in a service control policy"
> 
> It still seems to use these actions on "inactive" regions. I dont see the issue in the active regions.

Okay, let me see where we are on this.

**Comment by srpomeroy** [comment]
I don't believe AWS provides an API for determining available regions. Kubecost takes the brute force option of querying all regions and using the HTTP response codes to determine if we can query the region for resources.

A potential enhancement could be to provide a list of regions to query or avoid.
Or something like an adaptive backoff process that will scale back how often a region is queried as long as it's erroring out.

**Comment by danielrolfes2307** [comment]
@jessegoodier 
Do you mind reopening the issue again? Thanks :)

**Comment by chipzoller** [comment]
As it seems like this is a Kubecost application issue and not something related to the Helm chart, I'm transferring to the appropriate repository.
