### ISSUE TITLE
Cluster detail efficiency tooltip shows incorrect time range compared to time frame selected.

### ISSUE THREAD

**Issue by MikeFindsThings** [kubecost/cost-analyzer-helm-chart#2381]
Thanks for your interest in Kubecost! To ensure you get the help you need, please follow these guidelines:

- If you have questions about product functionality/usage or need assistance with product installation/configuration, please email <support@kubecost.com>, where our support engineering team will be happy to help!
- If you have a reproducible bug, you're in the right place. Please include the information requested below.

---

**Describe the bug**  
When hovering over the efficiency metric of the cluster detail page the tooltip states "Percentage of cluster resources, weighted by cost, **used over the last 7 days**.". This tooltip always shows "used over the last 7 days" regardless of time range selected. 

**To Reproduce**  
Navigate to [the Kubecost UI](https://demo.kubecost.xyz)
Select [any cluster](https://demo.kubecost.xyz/cluster-inspect?clusterId=kc-demo-dev&cloudId=mc_kc-demo_kc-demo-dev_eastus)
Hover mouse over Efficiency in the top summary portion
View tooltip stating "Percentage of cluster resources, weighted by cost, **used over the last 7 days**."
In the top right, change the date range from "Last 7 days" to any other date range
Hover mouse over Efficiency in the top summary portion
Observe tooltip

**Expected behavior**  
Efficiency tooltip shows same language as other tooltips (ie: "The total cost of your cluster **for the time frame selected**

**Screenshots**  
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/30030760/ca2e007c-a496-4fcc-83ed-fc98b5b19cb9)
7 days selected

![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/30030760/b8145b6a-c70e-420a-b783-54467f5dfe32)
90 days selected

**What impact will this have on your ability to get value out of Kubecost?**
Tooltips provide clarity to less experienced users, increasing adoption of recommendations. 

**Please share the support case, if any**  
[This is most commonly a Zendesk ticket number or link.](https://kubecost.zendesk.com/agent/tickets/4447)

**Comment by kwombach12** [comment]
@MikeFindsThings Thanks for catching this. We will cleanup ASAP

**Comment by chipzoller** [comment]
This has been addressed. Closing.
