### ISSUE TITLE
Add support for IDR currency

### ISSUE THREAD

**Issue by MikeFindsThings** [kubecost/cost-analyzer-helm-chart#2385]
**What problem are you trying to solve?**
IDR is not a currently supported currency

**Describe the solution you'd like**
For IDR to be supported

**Describe alternatives you've considered**
Manually converting from USD to IDR

**How would users interact with this feature?**

**Comment by kwombach12** [comment]
@MikeFindsThings Thanks for logging this. This should be a quick add we can execute in an upcoming release

**Comment by nealormsbee** [comment]
Support for IDR will be included in the 1.105 release!
