### ISSUE TITLE
Show running average of idle by node  for specified date range

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#2389]
**What problem are you trying to solve?**
Workload capacity fluctuates and can be unpredictable. Customer gets hit with heavy and hard hitting traffic and traffic can 10x out of nowhere. Because of this, a certain level of overhead must be tracked and available at any given time.

**Describe the solution you'd like**
provide a running average of idle by node via the API for a specified date range. Enterprise customer uses API and exports data to a third party business analytics tool.

**Describe alternatives you've considered**
Calculating this manually.

**How would users interact with this feature?**
Customer would grab average_idle from our allocation api and average _idle costs key value pair would be returned. Example:

```
             {
                "start": "2023-06-22T00:00:00Z",
                "end": "2023-06-23T00:00:00Z",
                "items": [
                    {
                        "name": "__idle__",
                        "average_idle":  13.279745628909364**
                        "cost": 13.279745628909364,
                        "efficiency": 0
                    },
                    {
                        "name": "ip-192-168-60-124.us-west-2.compute.internal",
                        "cost": 15.589886456061402,
                        "efficiency": 0.24647685770081754
                    }
```

**Comment by kwombach12** [comment]
Thanks @mmurph3 I see the need for this - we will revisit in a future release

**Comment by chipzoller** [comment]
Stale, closing.
