### ISSUE TITLE
Split name and version number of kubecost/kubecost-network-costs

### ISSUE THREAD

**Issue by MikeFindsThings** [kubecost/cost-analyzer-helm-chart#2401]
**What problem are you trying to solve?**
Client is trying to update kubecost/kubecost-network-costs. Since the image name and version are [stored in the same key/value](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/charts/grafana/values.yaml#L259), updating this reference will prevent us from receiving automatic updates to this image version when it's incremented in the helm chart, and will require them to increment the image version manually as they upgrade helm chart versions.

**Describe the solution you'd like**
Split the image name and version into separate key/value configs, similar to how [other images are being configured](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/charts/grafana/values.yaml#L27-L28) in this same chart.

**Describe alternatives you've considered**
Pinning to the specific image version and taking on the manual effort to keep it up to date when we upgrade helm charts. My team most likely will not allow this.

**How would users interact with this feature?**
This would allow users to override the grafana sidecar image name without taking on the responsibility of updating image versions.

**Comment by MikeFindsThings** [comment]
This is basically a clone of [this issue](https://github.com/kubecost/cost-analyzer-helm-chart/issues/2191), but for a different image.

**Comment by kwombach12** [comment]
@teevans @cliffcolvin Is this a quick fix we can make in 106?
