### ISSUE TITLE
Abandoned workloads doesn't support all Owner types

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2410]
**Describe the bug**  
Some options on the abandoned workloads savings page don't obtain valid "Owner" details. This can be seen under the `stress-ng` workload on [demo.kubecost.xyz](https://demo.kubecost.xyz/abandoned-workloads?profile=production). This was noticed with Jobs and Replicaset types but might be related to others. 

**To Reproduce**  

1. Go to the Abandoned workload savings page with a Job type deployed.
2. Expand the workload and see the missing details.

**Expected behavior**  
All "pod owner" types have support on this page.

**Screenshots**  
Example with working and non-working workloads.
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/43491549/6721dec6-63d5-4d47-a45f-a170f588248d)

**What impact will this have on your ability to get value out of Kubecost?**
Ability to filter/see details for all "pod owner" types.

**Please share the support case, if any**  
[ZD 4488](https://kubecost.zendesk.com/agent/tickets/4488)

**Comment by kwombach12** [comment]
Thanks @keithhand I have logged this issue and the team will take a look as soon as they can!

**Comment by passionInfinite** [comment]
Hello @keithhand  and @kwombach12 ,

Any update on this one?

**Comment by kwombach12** [comment]
We have some fixes going out for this in the 106 release.

**Comment by chipzoller** [comment]
Closing, stale.
