### ISSUE TITLE
Date picker for weekly ETLs always returns unclear windows

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2412]
**Describe the bug**  
If you are selecting a window that is using the "weekly" step size, you are unable to get an accurate representation of the window you select. This behavior is likely because weekly data always starts/ends on Sunday/Saturday, so the information you see in the UI matches this window. 

**To Reproduce**  

1. Go to an Asset or Allocation report
2. View a month's worth of data (i.e., April 1 - April 30)
3. See the title "Cumulative cost for 1 April 2023 through 30 April 2023"
4. Hover the bar chart information to get a more precise indication of the actual data represented (April 2 - May 7) 
5. You can adjust the start/end windows and get similar data sets, while the title will update accordingly. 

**Expected behavior**  
Data displayed to the user should match the window they select.

**Screenshots**  
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/43491549/18c24c3f-4514-4eba-83b2-2bfc3be5aca1)
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/43491549/77cd2039-35ea-42e9-bd2e-7206dae5a2f5)

**What impact will this have on your ability to get value out of Kubecost?**
Allow the user to have more accurate results when querying specific windows. 

**Please share the support case, if any**  
[ZD 4488](https://kubecost.zendesk.com/agent/tickets/4488)

**Comment by jessegoodier** [comment]
Thanks @keithhand!

We may need 2 enhancements for this one @kwombach12? 
1. UI: monthly and weekly window selector
2. build monthly ETLs so we have a full month regardless of when the week start/end is.

**Comment by keithhand** [comment]
Both of those sound like decent plans. If we plan on doing that, we should likely limit date selection to correlate with those window sets; to prevent a user from selecting a non-standard date range (Last four weeks with a Wednesday start date)

**Comment by kwombach12** [comment]
@keithhand I totally agree. We want to make sure that users receive the data for the exact dates they select and I think the best way to do this is to limit them so that they can only select weeks (sunday to sunday) if they are requesting data older than what they have available in their daily ETL. 

I am going to update this to an enhancement given there aren't any 'bugs' right now. Just a poor user experience that needs improving. Please add this to our FR tracker as I would consider this high impact

**Comment by chipzoller** [comment]
Closing, stale.
