### ISSUE TITLE
enhancement: add usage to request sizing UI and CSV

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#2414]
**What problem are you trying to solve?**

In /request-sizing, you currently have to click the container to see the current usage. This is also not in the in CSV if downloaded.

**Describe the solution you'd like**

Either add an option to allow which fields to simply display or add cpu and memory usage to UI

**Describe alternatives you've considered**

Please let me know if you have ideas

**How would users interact with this feature?**

UI enhancement

**Comment by jessegoodier** [comment]
jira kc-16

**Comment by Karthik-Chowdary** [comment]
- It would be great if we can customize the column we want to see on the requests sizing. Like a checkbox I can select the columns I want to look at, this way it is customizable and overcrowding can be reduced on the page.

- Having to go though hundred/thousands of pods to check their usage by clicking on each line item is not optimal
 
- Requested, Usage(Peak Usage), Recommendation(Based on peak usage) for CPU/Memory should be visible in a single view

**Comment by kwombach12** [comment]
@Karthik-Chowdary Thanks for this feedback! I will make sure we have feature requests to handle each of these use cases

**Comment by Karthik-Chowdary** [comment]
Any updates on which release is planned to have this enhancement?

**Comment by kwombach12** [comment]
@Karthik-Chowdary We are considering this for our 1.107 release!

**Comment by chipzoller** [comment]
Closing. Filed internally in Jira.
