### ISSUE TITLE
enhancement: ability to show a pod annotation/label in request sizing

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#2415]
**What problem are you trying to solve?**

Teams have automated builds that routinely deploy pods and they are most easily identified by an annotation. It would be helpful to display this annotation in request-sizing

**Describe the solution you'd like**

Really open to how to do this, but something like:
1. add helm values for which annotations are allowed to be displayed on /request-sizing
2. have configurable field list for which options to display on /request-sizing. Consider: #2414 

**Describe alternatives you've considered**

NA

**How would users interact with this feature?**

UI enhancement

**Comment by jessegoodier** [comment]
jira: kc-17

**Comment by Karthik-Chowdary** [comment]
This will really be helpful in our use cases. If there is a configurable way to display pod data we collect

Ex: If a Key is provided which is part of pod labels or annotations it should be able to display value. Ideally $key will end up being a column on UI with its values in rows.

Also helpful in the API to have the KV pair in request sizing

**Comment by chipzoller** [comment]
Tracked internally. Closing.
