### ISSUE TITLE
Incorrect cpu ram and gpu hourly cost on GPU nodes

### ISSUE THREAD

**Issue by ian-lmcb** [kubecost/cost-analyzer-helm-chart#2418]
**Describe the bug**  
It looks like prices aren't correct when a GPU is added to a node.

In a test Suse Rancher RKE2 cluster running on AWS EC2, where all instance_types are labeled `rke2`, we're seeing that when a node has a GPU added to it the CPU and RAM hourly cost metrics become much smaller and do no match what we expect.

To test this we specified custom pricing using multiples of 730 so the hourly costs should be whole numbers. So e.g. setting all custom prices to 730 we found that nodes without a GPU have `node_cpu_hourly_cost` and `node_ram_hourly_cost` metrics set to 1.0 as expected (with `node_gpu_hourly_cost` at 0), but on the node with a GPU we get 0.0492 instead, also for `node_gpu_hourly_cost`. It appears each of the metrics values have been divided by approximately 20.325.

Also tried making each price a different multiple of 730, so e.g. 1*730 for cpu, 2*730 for ram, and 3*730 for gpu and we got corresponding hourly costs of 0.0265, 0.0531, and 0.0796 on the gpu node (and the expected 1, 2, 3 for the non-gpu nodes). So the ratio was maintained but the values are divided by a different factor now, they're all divided by about 37.7.

As another data point, our gpu node didn't have the gpu reported correctly initially. Before we fixed it the cpu and ram hourly costs were set to 1.0 for the gpu node, but once we fixed the rke2 config so kubernetes could see the gpu resource we saw the hourly costs switch the values mentioned above.

We see the same behavior after clearing out the custom pricing, albeit with the default values.

So it appears that when a GPU is present the computation for the hourly cost metrics is doing some extra math that isn't right.

**To Reproduce**  

1. Set up Suse Rancher RKE2 running on AWS (although probably this will manifest in other k8s setups)
2. Add a non-GPU and a GPU instance each to the cluster
3. Install kubecost with custom pricing e.g.
```yaml
kubecostProductConfigs:
  defaultModelPricing:
    CPU: 730.0
    spotCPU: 730.0
    RAM: 730.0
    spotRAM: 730.0
    GPU: 730.0
    spotGPU: 730.0
    storage: 730.0
    zoneNetworkEgress: 730.0
    regionNetworkEgress: 730.0
    internetNetworkEgress: 730.0
    enabled: true
```
4. Observe the `node_cpu_hourly_cost` and `node_ram_hourly_cost` metrics for the two nodes do not agree, they are only the expected 1.0 on the non-gpu node.

**Expected behavior**  
GPU instances should still have 1.0 as their cpu and ram hourly cost, as well the GPU cost should be 1.0 per gpu hour

**What impact will this have on your ability to get value out of Kubecost?**
Correct prices on GPU nodes in on-prem or other non-cloud kubernetes environments

**Bug report**
[kubecost-bug-report.txt](https://github.com/kubecost/cost-analyzer-helm-chart/files/11972545/kubecost-bug-report.txt)

**Please share the support case, if any**  
#4545
https://kubecost.slack.com/archives/CE76NJE6S/p1688662623438579

**Comment by ian-lmcb** [comment]
Btw, we found this also repros with opencost and opened https://github.com/opencost/opencost/issues/2029

**Comment by kwombach12** [comment]
@ian-lmcb Thanks for the investigation. Let's fix on the opencost side first and that will make it easy for us to roll into Kubecost!

**Comment by ian-lmcb** [comment]
@kwombach12 I see @mattray commented on the opencost issue that kubecost support is tracking the issue. Just want to check that there isn't a case of each side waiting for the other here

**Comment by kwombach12** [comment]
@ian-lmcb thanks for double checking! The Kubecost team will fix this issue in the opencost repo

**Comment by pawel-lmcb** [comment]
Hello, any updates on this issue? Thank you!

**Comment by kwombach12** [comment]
@pawel-lmcb I'm going to close this so we can use the [Opencost Issue](https://github.com/opencost/opencost/issues/2029) to track the work for this. The issue still appears open, so please feel free to submit a PR!
