### ISSUE TITLE
Inconsistent Cost Report - allocation response values

### ISSUE THREAD

**Issue by steveizzle** [kubecost/cost-analyzer-helm-chart#2424]
**Describe the bug**  
When i do a request against the Allocation API or simply use the kubecost UI and create a report with a fixed time frame, i dont get consistent values when retrying with the same time frame. 

**To Reproduce**  

1. Create a request for example against: /model/allocation?accumulate=true&aggregate=namespace&idle=true&idleByNode=true&shareIdle=true&shareNamespaces=kube-system,kubecost,monitoring,kubernetes-dashboard,flux-system,starboard-operator,kyverno,falco&shareSplit=weighted&shareTenancyCosts=true&window=2023-06-23T00:00:00Z,2023-07-07T00:00:00Z
2. Get Response, Sum up total cost for example
3. Create the same request again
4. Get Response, Sum up total cost for example
5. Total Cost (and therefore some costs in the different namespaces are different, even with the same window)

I can see in the response that the start and end values are different in the two responses, e.g.: 

```
diff test-196.json test-153.json
13c13
<     "end": "2023-07-06T15:00:00Z",
---
>     "end": "2023-07-05T00:00:00Z",
```

This also happens on the Monitor or Report page of the UI

**Expected behavior**  

I would expect a consistent response.

**Comment by kirbsauce** [comment]
Hi @steveizzle , can you tell us what version you're using?  In addition, could you see if the API exhibits the same behavior when the window is more in the past, for example a one week window on June?

**Comment by chipzoller** [comment]
Closing, stale.
