### ISSUE TITLE
Cloud Cost reports via ui not saving custom labels

### ISSUE THREAD

**Issue by ChrisMusgrove** [kubecost/cost-analyzer-helm-chart#2426]
**Describe the bug**  
When creating a report, adding a label to search by generates the correct data we require. However, when saving the report and exiting the label criteria is removed and report switches back to a different setting.

**To Reproduce**  

1. Go to reports in the UI
2. generate a cloud cost report
3. Add a label to search by
4. save the report
5. close and reopen the report
6. Expected data is no longer there, search by label is not saved

**Expected behavior**  
Saved report saves in state where label is kept, allowing reporting

**What impact will this have on your ability to get value out of Kubecost?**
Unable to use automated reporting as requirement will not save

**Bug report**
[kubecost-bug-report.txt](https://github.com/kubecost/cost-analyzer-helm-chart/files/12000432/kubecost-bug-report.txt)

**Please share the support case, if any**  
4529

**Comment by kirbsauce** [comment]
@kwombach12 , diagnosis by support team feels this needs reviewed by engineering.

**Comment by kwombach12** [comment]
Thanks @kirbsauce We will take a look!

**Comment by rossfisherkc** [comment]
@ChrisMusgrove this should be fixed in 1.105 or abouts, mind re-testing?

**Comment by ChrisMusgrove** [comment]
@rossfisherkc working as expected now thank you
