### ISSUE TITLE
CPU Recommended on model/savings/requestSizingV2 shows the same value (v1.104.1)

### ISSUE THREAD

**Issue by kyuure** [kubecost/cost-analyzer-helm-chart#2435]
**Describe the bug**  
When calling for model/savings/requestSizingV2, CPU Recommended shows the same 10m values regardless of the CPU usage and CPU request. From the diagnostic page, I can see this alert

Description: If the 'kubecost_container_cpu_usage_irate' recording rule is not set up, Allocation pipeline build may put pressure on your Prometheus due to the use of a subquery. [Learn More](https://docs.kubecost.com/install-and-configure/install/custom-prom)

Query:absent_over_time(kubecost_container_cpu_usage_irate{}[5m] )

Result: [{"metric":{},"values":[{"timestamp":1689230480,"value":1}]}]

**To Reproduce**  

1. Hit API /model/savings/requestSizingV2?window=7d&targetCPUUtilization=0.8&targetRAMUtilization=0.8
2. All of the recommendations shows 10m values.

**Expected behavior**  
CPU Recommended should show different results based on current usage.

**What impact will this have on your ability to get value out of Kubecost?**
Invalid recommended values.

**Comment by kirbsauce** [comment]
Hi @kyuure.  Could you confirm that you're running the most recent version? Also, are you using your own Prometheus or the one bundled with Kubecost?

**Comment by kirbsauce** [comment]
In addition, are you seeing the same values in the UI?

**Comment by kyuure** [comment]
Thanks for the reply. I think this is related to #2392. After fixing (our own) prometheus recording rule, the recommendation shows valid data. But this is weird as it only occur after upgrading Kubecost to v1.104.1.
