### ISSUE TITLE
Workload Savings page can not get data in Breakdown table

### ISSUE THREAD

**Issue by txjjjjj** [kubecost/cost-analyzer-helm-chart#2443]
**Screenshots**  

<img width="1248" alt="image" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/60080355/0e3aeeac-a6a4-4fe5-aebf-0719fcbc3b14">
http://localhost:9090/model/allocation?window=48h&aggregate=&idle=false&accumulate=false&step=24h&filter=cluster%3A%22cluster-one%22%2Bnamespace%3A%22myns%22%2BcontrollerKind%3A%22statefulset%22%2BcontrollerName%3A%22myapp%22%2Bcontainer%3A%22nexus%22
<img width="775" alt="image" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/60080355/bd6733db-80f4-493e-afe1-d1371a1831c7">

env aws eks:
```
helm install kubecost cost-analyzer \
--repo https://kubecost.github.io/cost-analyzer/  \
--namespace kubecost --create-namespace \
--set prometheus.nodeExporter.enabled=false \
--set prometheus.serviceAccounts.nodeExporter.create=false
```

version: 1.105.0

all is ok except those two
<img width="582" alt="image" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/60080355/fc50bf24-36e9-4fd3-85a2-ff87a1e90f1a">

**Comment by kirbsauce** [comment]
Hi @txjjjjj.  Based on your report, could you repost this to support@kubecost.com where we can have a support engineer dig deeper?
