### ISSUE TITLE
I am getting output but getting 0 total cost

### ISSUE THREAD

**Issue by GauravJain98** [kubecost/cost-analyzer-helm-chart#2446]
Thanks for your interest in Kubecost! To ensure you get the help you need, please follow these guidelines:

- If you have questions about product functionality/usage or need assistance with product installation/configuration, please email <support@kubecost.com>, where our support engineering team will be happy to help!
- If you have a reproducible bug, you're in the right place. Please include the information requested below.

---

**Describe the bug**  

**To Reproduce**  

1. Already have [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)

2. Apply the following terraform resource

```hcl
resource "helm_release" "kubecost" {
  name = "kubecost"
  namespace = "kubecost"
  create_namespace = true
  repository = "https://kubecost.github.io/cost-analyzer"
  chart = "cost-analyzer"

  version = "1.105"

  set {
    name = "global.prometheus.enabled"
    value = false
  }

  set {
    name = "global.prometheus.fqdn"
    value = "http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090"
  }

  depends_on = [ helm_release.prometheus ]
}
```

3. Run 
`kubectl port-forward --namespace kubecost deployment/kubecost-cost-analyzer 9090`

**Expected behavior**  
Getting 0 total cost but getting namespace based costs

**Screenshots**  
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/19913130/64441b31-263b-412b-b95c-63585db4f55c)

**What impact will this have on your ability to get value out of Kubecost?**
not able to use kubecosts

**Comment by jcharcalla** [comment]
Hello @GauravJain98 

Have you been able to successfully deploy Kubecost using the bundled Prometheus? We typically recommend this to confirm things are working correctly prior to trying the advanced bring your own Prometheus configuration.

Based on the screenshot provided, it appears Kubecost may be missing metrics from itself or KSM. Please ensure the appropriate scrape jobs have been configured on your existing Prometheus server. You can find more information in our docs: https://docs.kubecost.com/install-and-configure/install/custom-prom

**Comment by GauravJain98** [comment]
@jcharcalla  thanks a lot 
this helped but the data i am getting is still not accurate 
these are for today 
any 
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/19913130/76edce39-241a-48ab-bcda-0de7c4faec6e)
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/19913130/48455c4f-24a6-4ad4-98ab-e95b3488f87b)

the additionalScrapeConfig for kubecost is there 
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/19913130/4849cfff-ded3-46c0-8ba2-9311319484c3)

**Comment by jcharcalla** [comment]
Is your cluster doing any auto scaling, i.e. is it possible there have been 18 unique total instances today?

Kubecost will also not display any empty/unused namespaces.

Let us know if that does not explain what you are seeing.

**Comment by GauravJain98** [comment]
@jcharcalla 
it is working as far i can tell
Thanks a lot for the assistance
