### ISSUE TITLE
Failed to find cluster node type 'Standard_E4ds_v5'

### ISSUE THREAD

**Issue by Mahagon** [kubecost/cost-analyzer-helm-chart#2450]
Hi

our kubecost deployment is unable to retrieve the pricing for [Standard_E4ds_v5](https://learn.microsoft.com/en-us/azure/virtual-machines/edv5-edsv5-series#edsv5-series).
The other Azure resource pricings are fine (Storage accounts...).

Do i need to configure something additionally?

Log entry:
```
cost-model 2023-07-24T09:20:01.180946663Z ERR savings: cluster sizing: failed to get monthly cluster rates: failed to find cluster node type 'Standard_E4ds_v5' in region 'germanywestcentral': can't find type 'E4ds v5' in Azure region 'germanywestcentral'
cost-model 2023-07-24T09:20:01.180985101Z WRN got error failed to get monthly cluster rates: failed to find cluster node type 'Standard_E4ds_v5' in region 'germanywestcentral': can't find type 'E4ds v5' in Azure region 'germanywestcentral' for metric clusterSizing%%Development, not adding to cache

```

**Comment by kwombach12** [comment]
@kirbsauce Can someone on support take a look at this?

**Comment by kirbsauce** [comment]
sure @kwombach12 !

@Mahagon , to ensure we get you to the right support person, could you resubmit this to support@kubecost.com or post in the #support channel of our Slack Workspace?

**Comment by Mahagon** [comment]
Sure, i will do that, thank you :)
