### ISSUE TITLE
use explicit protocol selection for all Service port names.

### ISSUE THREAD

**Issue by bt-macole** [kubecost/cost-analyzer-helm-chart#2452]
**What problem are you trying to solve?**
All Service port names use explicit protocol selection except for node-exporter-service

App protocol names should use [explicit-protocol-selection](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection)
 
https://github.com/kubecost/cost-analyzer-helm-chart/blob/69ef398c5e7356eae6489b2cf5383f7720d48baf/cost-analyzer/charts/prometheus/templates/node-exporter-service.yaml#L35

**Describe the solution you'd like**
prefix the port name with `tcp-` so it conforms with `<protocol>[-<suffix>]` naming convention.

**Describe alternatives you've considered**
Could patch the port name or use `appProtocol`

**Comment by kwombach12** [comment]
@bt-macole Is this important to your ability to use Kubecost? Or is this simply a naming convention you'd like Kubecost to adopt?

**Comment by bt-macole** [comment]
it is required for anything using istio in production, so if we wanted to set up access to the dashboard via an ingressgateway we'd need to comply with that naming convention.

for experimenting with kubecost it is not required, but it may be a requirement for us to use kubecost in prod.

**Comment by thomasvn** [comment]
@bt-macole Understood. Would you be interested in authoring a PR for this?

**Comment by Ayush9026** [comment]
dfd

**Comment by Ayush9026** [comment]
@thomasvn  sir i will author PR for this.

**Comment by chipzoller** [comment]
@Ayush9026, are you still interested in taking this?

**Comment by Ayush9026** [comment]
Yes @chipzoller I will resolve this if i am unable
 i'll give others to take this issue.

**Comment by ghost** [comment]
I'm going to create the PR for this, since this has been sitting for a little while. Thanks for the suggestion!
