### ISSUE TITLE
Unable to create multiaggregate cloud cost reports

### ISSUE THREAD

**Issue by ChrisMusgrove** [kubecost/cost-analyzer-helm-chart#2453]
Describe the bug
When creating a cloud cost report in either yaml or on the UI you are unable to create/save the report

To Reproduce

UI
Go to reports in the UI
generate a cloud cost report
Create a multiaggregate report
save the report
close and reopen the report
Expected data is no longer there
Expected behavior
Saved report saves in state where label is kept, allowing reporting

YAML
    - title: "Cloud test 00"
      window: "7d"
      aggregateBy: "label:squads,service,accountID"
      filters: 
      - property: "Labels"
        value: "squads:__unallocated__"

report creates successfully, and displays correctly in UI reports screen:
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/95920377/d2d1c0ac-8bc0-4f8e-aadd-ddaf639907e8)

report opens incorrectly:
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/95920377/75d37970-1217-4635-94a6-3077ccdfbc1f)

What impact will this have on your ability to get value out of Kubecost?
Unable to use automated reporting as requirement will not save

Bug report
[kubecost-bug-report (1).txt](https://github.com/kubecost/cost-analyzer-helm-chart/files/12173984/kubecost-bug-report.1.txt)

**Comment by ChrisMusgrove** [comment]
Please not this works fine whilst created in the UI and unsaved, you can use the report as intended whilst it is in an unsaved state and it displays correctly, it is only on saving that the report breaks.

**Comment by kwombach12** [comment]
@kirbsauce Is there someone on support who can take a look at this?

**Comment by kirbsauce** [comment]
Sure @kwombach12

**Comment by kirbsauce** [comment]
Hi @ChrisMusgrove , in reading your description, are you saying the label is not being saved?  In other words, if you open the saved report and add back in the label you would get the desired results?

**Comment by ChrisMusgrove** [comment]
Hi @kirbsauce No the whole report is not saving correctly with any multiaggregated report. If you try to save a report with just service and account you get the same behavior. It looks almost like it is trying to run a single agrregate report and combining the whole string together once it is saved as when you open it it has crushed the line together.

Opening the saved report gives no data at all, as it looks to be searching something that doesnt exist.

**Comment by kirbsauce** [comment]
thanks @ChrisMusgrove.  I'm having a hard time reproducing this for engineering.  Would it be too much to ask to do a quick loom or other video so I can see exactly what you're doing?  I'm focusing on the UI side of things but believe it's all connected.

**Comment by ChrisMusgrove** [comment]
Hi @kirbsauce sure thing we can do a call, i would say its easier to reproduce in the yaml file than on the UI, it seems to affect it mostly when labels are added

**Comment by ChrisMusgrove** [comment]
YAML
- title: "Cloud test 00"
window: "7d"
aggregateBy: "label:squads,service,accountID"

using this in v 1.105 should reproduce the error

**Comment by kirbsauce** [comment]
Thanks for the YAML!  Would you be able to do a quick video for us in lieu of a call?  We often use www.loom.com but feel free to use whatever tool you like.

**Comment by avrodrigues5** [comment]
@kirbsauce I put in a [fix](https://github.com/kubecost/kubecost-cost-model/pull/1651) and @cliffcolvin made a cherry-pick and put it in the patch released yesterday via [PR](https://github.com/kubecost/kubecost-cost-model/pull/1662). So the YAML failing for multi aggregation should be resolved in 105.1 release.

**Comment by kirbsauce** [comment]
Thanks @avrodrigues5 !  @ChrisMusgrove , let's proceed with the UI video (if you're willing), and we'll try the YAML fix when we push the 105.1 patch.  Sound good?

**Comment by ChrisMusgrove** [comment]
@kirbsauce just tried again via the UI but now completely unable to save a multiaggregate cloud report, can only do it via the yaml

**Comment by kirbsauce** [comment]
I was experiencing this too when trying to repro.  I've already filed
internal issue for this and waiting for Product to triage.

cc: @Kai Wombacher ***@***.***>

**Comment by ChrisMusgrove** [comment]
Brilliant, as long as it works one way thats good for us, happy to wait for the 1.105.1 release and then test

**Comment by kirbsauce** [comment]
Thank you for your patience!  If not already done so, you can subscribe to
our releases in this repository so you'll know as soon as it drops.  I look
forward to the results.

**Comment by chipzoller** [comment]
Looks to be fixed in a prior version. Closing.
