### ISSUE TITLE
Allow query-service's fullname to be overriden

### ISSUE THREAD

**Issue by jrRibeiro** [kubecost/cost-analyzer-helm-chart#2455]
**What problem are you trying to solve?**
Currently, the `query-service.fullname` variable used to [create](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.105.0/cost-analyzer/templates/query-service-deployment-template.yaml#L6) the deployment can't be overridden. 
It should be possible to override the fullname, which is useful when release names have more than 63 chars or if you just can't use the release-name for some reason.

**Describe the solution you'd like**
Add a new value to fully override the `query-service.fullname` variable.

**Describe alternatives you've considered**
There's none.

**How would users interact with this feature?**
Set a `queryServiceFullnameOverride` variable to override the `query-service.fullname` variable.

**Comment by jessegoodier** [comment]
@jrRibeiro 
I see you also did the PR for the truncate. Do you prefer this?
We can support both, but just curious as to what the motivation for the current PR is?

https://github.com/kubecost/cost-analyzer-helm-chart/pull/2367

**Comment by jrRibeiro** [comment]
> 

The truncate should always be in-place as a safeguard, either we truncate or not the name.

But yes, the symptom was the same, pods created by the statefulset, although the statefulset name is truncated to 63 chars,pods created by the statefulset have the name with a "-N" suffix, surpassing the 63 characters.

We could truncate the statefulset further to take into account the suffix added to the pod names, or just allow to fully override the statefulset name, which I think it's simpler (and that cost-analyzer is already doing).

**Comment by thomasvn** [comment]
@jrRibeiro Just curious, could you clarify why overriding `query-service.fullname` would be beneficial, but currently [`cost-analyzer.fullname`](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.105.0/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L6) is functioning ok for you?

**Comment by jrRibeiro** [comment]
> @jrRibeiro Just curious, could you clarify why overriding `query-service.fullname` would be beneficial, but currently [`cost-analyzer.fullname`](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.105.0/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L6) is functioning ok for you?

`cost-analyzer.fullname` is working precisely because, in its definition, I can [use a fullnameOverride](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/_helpers.tpl#L21-L22) to define its value, which is what the opened PR does. 

That way, the fullname doesn't contain the release-name in the query service as well, which is what I'm trying to achieve for the aforementioned reasons.

**Comment by thomasvn** [comment]
@jrRibeiro Oh thanks for clarifying! That makes sense. So something like the following change work for you?

```mustache
{{- define "query-service.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- printf "%s-%s" .Values.fullnameOverride "query-service" | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name "query-service" | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
```

**Comment by jrRibeiro** [comment]
@thomasvn Yes, that would work as well. The only issue with that solution is that the fullnameOverride was first defined in the cost-analyzer context, meaning some deployments (like mine) are setting that to `cost-analyzer` or something like that and it becomes weird to have the query-service named `cost-analyzer-query-service`as they are different services. That's why I added a new `queryServiceFullnameOverride`

**Comment by jessegoodier** [comment]
merged.
