### ISSUE TITLE
CNY currency support

### ISSUE THREAD

**Issue by dz902** [kubecost/cost-analyzer-helm-chart#2459]
**What problem are you trying to solve?**
Support for CNY currency

**Describe the solution you'd like**
Support for CNY currency

**Describe alternatives you've considered**
Manual conversion

**How would users interact with this feature?**

**Comment by kwombach12** [comment]
@dz902 We do have support for CNY currency 
<img width="545" alt="Screenshot 2023-07-27 at 2 16 30 PM" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/86785820/61a78163-a490-4d0d-bc36-702e5af4303c">

We do not do currency conversions - rather, you can configure our UI to match the currency of the data flowing into Kubecost

**Comment by kwombach12** [comment]
We will update our documentation to make this more clear.
