### ISSUE TITLE
Add `LOG_FORMAT` as global variable or add it to all components: `kubecost-metrics`

### ISSUE THREAD

**Issue by wiktor2200** [kubecost/cost-analyzer-helm-chart#2460]
**What problem are you trying to solve?**
I've set `LOG_FORMAT` to `json` in `kubecost-model` but still `kubecost-metrics` emits logs in not ingest friendly way.

**Describe the solution you'd like**
I think every component should include `extraEnv` parameter to set proper `LOG_FORMAT`. Plus it would be nice to have it global to just set on highest level for all of them.

It may be connected with similar: #2327 #2309 issues, so I'm linking them to better visibility.

**Comment by kwombach12** [comment]
@wiktor2200 Thanks for logging this! I will add to our internal feature request tracking tool.

**Comment by chipzoller** [comment]
Closing, stale.

**Comment by chipzoller** [comment]
Captured in https://github.com/kubecost/features-bugs/issues/81. Closing this.
