### ISSUE TITLE
Introduce a set of Prometheus metrics/alert rules that would allow to asses Kubecost processing function health

### ISSUE THREAD

**Issue by tomsucho** [kubecost/cost-analyzer-helm-chart#2461]
**What problem are you trying to solve?**
Prometheus metrics & alerting is a standard way of monitor apps running on top of k8s. Having a dedicated set metrics for Kubecost app for assessing its own overall processing health, we could define alerting rules to get notified in cases where it would stop processing, but the overall pod status would look healthy. If the metrics are there already it would be only about creating alerting rules, so that users don't have to scratch their heads what metrics to track and when to consider something not working.

**Describe the solution you'd like**
- add metrics that would allow to asses health of Kubecost processing, to be able to define alert rules for Prometheus (if not in there already).
- add alert rules to Helm chart to get standard Prometheus alerting on processing malfunctions.

**Describe alternatives you've considered**
- webhook notifications for MS Teams, confgiured from the UI, but this is a nice addon as in my view each app should expose its own set of metrics for Prometheus which would allow to assess its own health/processing status and get alerted on any potential malfunction types, just like all other apps are doing.

**How would users interact with this feature?**

**Comment by kwombach12** [comment]
@tomsucho We actually have [Kubecost Health Alerts](https://docs.kubecost.com/using-kubecost/navigating-the-kubecost-ui/alerts#monitor-kubecost-health) available today which monitor the health of the data flowing into the Kubecost Application. These alerts include detection for any errors or abnormalities in our ETL pipeline which pulls from Prometheus. Are there other metrics/monitoring you are interested in?

**Comment by tomsucho** [comment]
@kwombach12 I don't want to set this up in UI and sent it over webhook directly somewhere. What I would want is alerting rules for Prometheus that I could load into it, to get those as Prometheus alerts and then send/route through Alertmanager to various endpoints, just like we do for any other alerts coming from apps running on k8s cluster.

**Comment by kwombach12** [comment]
@tomsucho I will add this to our backlog of enhancements. Are there specific Prometheus metricsalerts that you're interesting in? I'd like to make sure those are integrated into our standard Kubecost health alerts.

**Comment by tomsucho** [comment]
@kwombach12 that's part of this ticket request - basically I don't know myself which metrics exist already and which ones would make sense to monitor to make sure Kubecost is processing fine. So what I think would be good to do is as follows:
1. Identify what metrics already exist and what could be added to improve monitoring/alerting of Kubecost itself in case there are gaps in currently available metrics.
2. Create alerting rules for Prometheus for each metric that exists already. Add description to the alert so that the alert hints the user how to fix it. Maybe even have a link to docs/runbook in the alert description/message itself.
3. Overtime if new metrics are added create alerting rules accordingly. 
End goal being if any of the functions of Kubecosts fail, the user should be alerted on it, rather then seeing inaccurate costs or invalid data.

**Comment by kwombach12** [comment]
@tomsucho Gotcha. Thanks for this feedback. I have added this to our backlog of feature request

**Comment by chipzoller** [comment]
Closing, we have diagnostics now which are being enhanced further.
