### ISSUE TITLE
Improve network costs allocation & visibility

### ISSUE THREAD

**Issue by tomsucho** [kubecost/cost-analyzer-helm-chart#2464]
**What problem are you trying to solve?**

The bytes sent reported per pod indicate accounting is done for EKS services range i.e. 172.20./12 which is just a virtal address space in k8s (ClusterIP svcs'es), and one can't really tell whether this traffic is in-zone or cross-zone, since the target service backing pods can live on various nodes/zones in a regional cluster. We should basically not see in pod traffic history any destination IPs from this range, as that is most likely miscounting that traffic as in-zone only?

**Describe the solution you'd like**
- traffic destined to any IP part of 172.20/12 should not yet be accounted as in-zone, as that can only be assed after DNAT operation occured and the packet has a final real pod destination IP set on it, which could end up being pod on another subnet/zone and thus should account for corss-zone traffic and not in-zone.

**Describe alternatives you've considered**
- NA

**How would users interact with this feature?**
- NA

**Comment by thomasvn** [comment]
@tomsucho Thanks for the report! Yes, by default IP addresses within 172.16.0.0/12 are classified as "in-zone". Same is true for 10.0.0.0/8 and 192.168.0.0/16 as they are Private Address Ranges defined in [RFC-1918](https://datatracker.ietf.org/doc/html/rfc1918).

If you have a multi-zone Kubernetes cluster, you can disable this default behavior by commenting out the line(s) below:
https://github.com/kubecost/cost-analyzer-helm-chart/blob/8f3381a81fc43be6c3a536992be12dad2f965b48/cost-analyzer/values.yaml#L742-L752

**Comment by tomsucho** [comment]
@thomasvn yes this is what I done already, but the 172.20./12 still appears. This is how my values cfg looks like:
```       in-zone:
        # Loopback Addresses in "IANA IPv4 Special-Purpose Address Registry"
        - "127.0.0.0/8"
        # IPv4 Link Local Address Space
        - "169.254.0.0/16"
      direct-classification:
        - region: $(REGION_NAME)
          zone: $(REGION_NAME)a
          ips:
            - "10.x.x.x/24"
        - region: $(REGION_NAME)
          zone: $(REGION_NAME)b
          ips:
            - "10.x.y.x/24"
        - region: $(REGION_NAME)
          zone: $(REGION_NAME)c
          ips:
            - "10.x.z.x/24"     
``` 
so for 10./8 private range, which we use for private subnets for EKS I can provide classification accordingly. However for 172.20./12 I'm not able to provide this ofc. I'm not quite sure why we actually are seeing both 10./8 ranges and 172.20/12 ? Initially I thought it is happening maybe only for svc'es for which there is no actual backing pod like kube api server (172.20.0.1), which are actually just AWS interface endpoints, but then I noticed it does also show up for kube-dns svc which is just a standard k8s service backed by CoreDNS deployment pods. Tho that uses UDP most likely since it's DNS traffic, maybe that's a difference. Lastly, I noticed that for cost-analyzer pod itself I can see it talks heavily with 172.20.30.76 which is a Prometheus svc on my cluster, so looks like it is a general thing for any pods talking to in-cluster svc'es.

**Comment by chipzoller** [comment]
Since this is an older issue, I'd encourage you to try the latest Kubecost 2.0 which also carries many enhancements for the Network Costs component. If this is still valid, please feel free to either comment so we can reopen or, better, open a new issue with the new version numbers.
