### ISSUE TITLE
Update deprecated horizontalPodAutoscaler API

### ISSUE THREAD

**Issue by davidegreenwald** [kubecost/cost-analyzer-helm-chart#2465]
`autoscaling/v2beta1` is deprecated and no longer available in Kubernetes 1.26+

I see this present in two places:
- https://github.com/kubecost/cost-analyzer-helm-chart/blob/7b9471a985edede4fb4f5be7bc1648d4d23cb810/cost-analyzer/charts/thanos/templates/query-horizontalpodautoscaler.yaml#L4
- https://github.com/kubecost/cost-analyzer-helm-chart/blob/7b9471a985edede4fb4f5be7bc1648d4d23cb810/cost-analyzer/charts/thanos/templates/query-frontend-horizontalpodautoscaler.yaml#L4

**Comment by kwombach12** [comment]
@thomasvn Is this a change you can quickly make?

**Comment by thomasvn** [comment]
@davidegreenwald Thanks for reporting! Is the recommendation to upgrade to `apiVersion: autoscaling/v2`?

**Comment by davidegreenwald** [comment]
@thomasvn That's right. The v2 API has been GA since [Kubernetes 1.23](https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/#horizontalpodautoscaler-v2-graduates-to-ga).

**Comment by Ayush9026** [comment]
@davidegreenwald and @thomasvn sir i made changes and upgraded apiVersion: autoscaling/v2  and created PR . PR merge requires 1 approving review. Please review it  https://github.com/kubecost/openshift-helm-chart/pull/27  .

**Comment by thomasvn** [comment]
@Ayush9026 Thanks for your contribution to the openshift-helm-chart! Are you interested in authoring a PR to address the issue in this repo as well?

**Comment by Ayush9026** [comment]
Thanks @thomasvn sir I'd be happy to help with the issue in this repository as well. Looking forward to contributing.

**Comment by chipzoller** [comment]
@Ayush9026, are you still interested in adding this?

**Comment by chipzoller** [comment]
No more HPAs in the chart. Closing as no longer relevant.
