### ISSUE TITLE
Add support for AWS gp3 volumes as default

### ISSUE THREAD

**Issue by mdiianni** [kubecost/cost-analyzer-helm-chart#2470]
**What problem are you trying to solve?**
Simply transition from gp2 to gp3 volumes, widely and generally available for quite a long time, also supported by all AWS instance families.

**Describe the solution you'd like**
Create Kubernetes physical volumes using AWS gp3 type volumes.

**Describe alternatives you've considered**
Add an override to the helm chart values.

**How would users interact with this feature?**
Transparent, no action required.

**Comment by kwombach12** [comment]
@thomasvn is this something you can help with?

**Comment by thomasvn** [comment]
Thanks for the suggestion @mdiianni! Given the [Kubernetes' default storageclass for aws-ebs](https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs) is `gp2`, I think it's safest for this Helm chart to stick with the default. I'm also concerned with the migration of existing users from `gp2` to `gp3`.

If interested in using `gp3` in your deployment, feel free to modify the `storageClass` here!
https://github.com/kubecost/cost-analyzer-helm-chart/blob/8f3381a81fc43be6c3a536992be12dad2f965b48/cost-analyzer/values.yaml#L557-L565

**Comment by mdiianni** [comment]
Thanks for the reply. I will explore the alternative and possibly comment
to outcome of the migration aiming for zero downtime and data loss.

Regards
