### ISSUE TITLE
Move Grafana Dashboards to Files (JSON)

### ISSUE THREAD

**Issue by osterman** [kubecost/cost-analyzer-helm-chart#25]
## what
* Can we move these dashboards to files instead then modify the chart to include them?

![image](https://user-images.githubusercontent.com/52489/57413836-90d88a00-71aa-11e9-9a30-7569f4a4cb2f.png)

## why
this will make it easier for 
- (a) you to maintain them since you can just drop a file in without packing it all on one line
- (b) for others use them if not using your grafana, since grafana supports pulling dashboards from a URL, so we could pull them using the github raw url

## references
* https://github.com/helm/helm/blob/master/docs/chart_template_guide/accessing_files.md

**Comment by dwbrown2** [comment]
Dashboards currently live here: https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/charts/grafana/values.yaml#L178

**Comment by AjayTripathy** [comment]
I've put out #32 to address this issue.
