### ISSUE TITLE
Are there any plugins that can change UI language to chinese?

### ISSUE THREAD

**Issue by gitlilei2019** [kubecost/cost-analyzer-helm-chart#2525]
### Problem Statement

http://localhost:9090/overview can change language to chinese?

### Solution Description

http://localhost:9090/overview can change language to chinese?

**Comment by kwombach12** [comment]
@gitlilei2019 Unfortunately, Kubecost only supports English right now. There are a number of browser plug-ins you can use that should help change the language though: https://chrome.google.com/webstore/detail/advanced-page-language-sw/mhgjlbolkmcookadjpolimbddngjgbol
