### ISSUE TITLE
Cluster-controller tolerations

### ISSUE THREAD

**Issue by headj-origami** [kubecost/cost-analyzer-helm-chart#2526]
### Problem Statement

The cluster-controller Deployment in the kubecost helm chart does not make use of tolerations set in the chart's values file. 

This leaves the resulting pods with no tolerations, and unable to be scheduled on clusters with no untainted nodes.

**To Reproduce**
1. Deploy the cost-analyzer helm chart with the following values:
`-n kubecost --set clusterController.enabled=true --set tolerations[0].key=someKey`
or
```
clusterController:
  enabled: true

tolerations:
  - key: someKey
```
3. Get the tolerations for the resulting Deployment:
`kubectl get deployment kubecost-cluster-controller -n kubecost -o json | jq .spec.template.spec.tolerations`

### Solution Description

The Deployment should contain the tolerations set in the `.Values.tolerations` value.

### Alternatives

A separate tolerations key for cluster-controller could be added within the values structure, which sets the tolerations in the Deployment.

### Additional Context

Observed in Kubecost v1.105.1
This is occurring on Amazon EKS on kubernetes v1.22, but I do not believe this is platform-specific.

The issue appears to be within the helm chart templates, as [the deployment in question](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/kubecost-cluster-controller-template.yaml) does not make use of the global (or any other) tolerations key from the values file.

**Comment by kwombach12** [comment]
Thanks @headj-origami. We will add this to our backlog
