### ISSUE TITLE
API for Recommendation with Complex and Simple Option

### ISSUE THREAD

**Issue by ajayp2608** [kubecost/cost-analyzer-helm-chart#2557]
### Problem Statement

There is no Option in the Recommendation API to select the Complex and Simple Option, which we see it on UI.
So documentation needs update on this.

### Solution Description

There is no Option in the Recommendation API to select the Complex and Simple Option, which we see it on UI.
So documentation needs update on this.

### Alternatives

There is no Option in the Recommendation API to select the Complex and Simple Option, which we see it on UI.

### Additional Context

There is no Option in the Recommendation API to select the Complex and Simple Option, which we see it on UI.

**Comment by kwombach12** [comment]
@ajayp2608 Is [this](https://docs.kubecost.com/apis/apis-overview/api-request-right-sizing-v2) the Recommendation API you're referring to? This API is used to power our _Container_ Sizing Recommendations. [Here](https://github.com/kubecost/docs/issues/714) is an issue I just opened for us to add documentation for the _Cluster_ Sizing API which is the page in our UI which has simple & complex recommendations.

**Comment by chipzoller** [comment]
This seems like a docs issue and not a Helm chart one. If that so, are we ok to close since there is an analog issue created in kubecost/docs?

**Comment by kwombach12** [comment]
@chipzoller Yup! I created a corresponding docs issue [here](https://github.com/kubecost/docs/issues/714) so I will close this one out.
