### ISSUE TITLE
Why is the default topNItems so small? 

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#2564]
### Problem Statement

I thought this was originally configured as 10,000+ as many users have more than a 1,000 items. Also, it would be helpful to document this flag more, i.e. explain that this is the topN most expensive items per day. 

https://github.com/kubecost/cost-analyzer-helm-chart/blob/a9198777ecd6d1f68f38afb7e42d7cc13e17a1f8/cost-analyzer/values.yaml#L463C1-L464C1

### Solution Description

Proposal is to increase default topN + document.

### Alternatives

Leave as is. 

### Additional Context

*

**Comment by chipzoller** [comment]
@thomasvn, any sense since you added this in #2240 if this is the appropriate value?

**Comment by thomasvn** [comment]
@kwombach12 @Sean-Holcomb Thoughts on increasing to 10,000? And providing more details in the docs about performance implications?

**Comment by kwombach12** [comment]
For me, the higher the better assuming minimal/no performance implications.

**Comment by Sean-Holcomb** [comment]
I don't have strong opinions on this, since topN will not exist post waterfowl

**Comment by kwombach12** [comment]
@Sean-Holcomb Wow thats awsome. @dwbrown2 I suggest we close this seeing a waterfowl should make this obsolete in 107.

**Comment by dwbrown2** [comment]
I'm good with that! @Sean-Holcomb just let us know if that's coming after 107... thanks all!
