### ISSUE TITLE
allow setting priority class name on prometheus-node-exporter

### ISSUE THREAD

**Issue by trondhindenes** [kubecost/cost-analyzer-helm-chart#2565]
### Problem Statement

Prometheus-node-exporter might be downprioritized and stuck in Pending on "well-packed" nodes. It would be good to have the option of setting a priorityClassName to give these pods a higher chance of getting scheduled

### Solution Description

just surface a priorityClassName attr.

**Comment by kwombach12** [comment]
@trondhindenes This makes sense. I will file an ticket for our team to tackle this.

**Comment by dwbrown2** [comment]
Can this be done here? https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/charts/prometheus/values.yaml#L442

**Comment by trondhindenes** [comment]
ah, good find. Maybe - I'm not a Helm expert so I don't know how "subchart" values work. Maybe all that's needed is a bit of documentation, both for this issue and https://github.com/kubecost/cost-analyzer-helm-chart/issues/2566#issuecomment-1707316417 . 

Especially since the readme displays some prometheus parameters if there's actually a lot more possible parameters for configuring prometheus then that should probably be called out clearly. My assumption was that https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/README.md and the "top-level" values file was the complete list of configurable things.

**Comment by chipzoller** [comment]
We have some updates to do on the README, but the value is already present for Prometheus.

**Comment by chipzoller** [comment]
Capability is already present.
