### ISSUE TITLE
[Feature] Allow setting requests/limits on node-exporter

### ISSUE THREAD

**Issue by trondhindenes** [kubecost/cost-analyzer-helm-chart#2566]
### Problem Statement

Node-exporter pods are created without any resource requests/limits. It would be great if it was possible to set these.

### Solution Description

allow setting node-exporter resource dict.

**Comment by kwombach12** [comment]
Thanks @trondhindenes I can see how this would be valuable. I will file a ticket for this

**Comment by kwombach12** [comment]
@trondhindenes After some investigation, it seems this is in fact possible today! https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/charts/prometheus/values.yaml#L501. Please let us know if you have any other issues or ideas!
