### ISSUE TITLE
Add the Open Cost implementation of CSV export S3 bucket and other cloud targets for BI integration

### ISSUE THREAD

**Issue by Chandra-afs** [kubecost/cost-analyzer-helm-chart#2582]
### Problem Statement

Problem: Kubecost data needs to be integrated with BI and other custom FinOps tools . The following solution would help achieve this.

1. Please refer to the open cost implementation of CSV export to S3 bucket and other cloud targets. This really helps to integrate with existing BI and FinOps tools.
https://www.opencost.io/docs/integrations/csv-export

2. By doing this you can also provide/enable the current API based CSV export of cost data to include dates. Currently json export have dates. csv export is simple and nice, but dates on them would make it more usable.

### Solution Description

1. Please refer to the open cost implementation of CSV export to S3 bucket and other cloud targets. This really helps to integrate with existing BI and FinOps tools.
https://www.opencost.io/docs/integrations/csv-export

2. By doing this you can also provide/enable the current API based CSV export of cost data to include dates. Currently json export have dates. csv export is simple and nice, but dates on them would make it more usable.

**Comment by kwombach12** [comment]
@Chandra-afs Kubecost does provide access to our APIs which power all the data that you see in our UI. You can also opt to download any reports you see in the UI as a .csv. [Here is a blog](https://blog.kubecost.com/blog/integrate-kubecost-with-datadog/) we published on how users can intregrate Kubecost Data into a Datadog Dashboard.

**Comment by Chandra-afs** [comment]
You may reopen this because the blog does not match with what is being asked. Blog is in particular to data log integration. The ask is an export option for the data, so we can integrate any custom solution and not to a particular tool. The open cost option of exporting the data to a bucket or storage for example is more generic and any tooling can consume it. We do not use data dog. Also sub ask in this request is adding date field to csv file that is exported out for kubecost, which does not have a date.

**Comment by chipzoller** [comment]
We are transitioning all feature requests and bug reports to a new repository. The feature requested here is not specific to the Helm chart and should be created in the new repository [here](https://github.com/kubecost/features-bugs). The issue templates are being created now so please wait a couple of hours before filing a request, or, alternatively product management can handle this internally.

**Comment by chipzoller** [comment]
Logged in https://github.com/kubecost/features-bugs/issues/1
