### ISSUE TITLE
[Feature] Support a Custom Secret for the OIDC Secret

### ISSUE THREAD

**Issue by knechtionscoding** [kubecost/cost-analyzer-helm-chart#2612]
### Problem Statement

In the current configuration the OIDC Client Secret has to be put into the values.yaml.

This shouldn't be required. Especially in a GitOps model where values.yaml is committed back to the repo. This exposes the secret improperly.

### Solution Description

A oidc.customSecret field should be supported to provide the k8s secret that should be loaded/used instead.  Then all secret sources can be used including:

- External Secrets
- Sealed Secrets
- SOPs
- Vault

**Comment by kwombach12** [comment]
@knechtionscoding this makes a lot of sense to me, @thomasvn is this something you could take a look at?

**Comment by knechtionscoding** [comment]
@kwombach12 I'm happy to pick it up and submit a PR, I was planning on doing so in about 60 minutes anyway, so unless there are specific concerns I'm happy to do it and just have it reviewed.

**Comment by kwombach12** [comment]
@knechtionscoding That would be terrific! We would appreciate the contribution and look forward to reviewing the PR.
