### ISSUE TITLE
Support for Kubernetes 1.25+

### ISSUE THREAD

**Issue by jondkelley** [kubecost/cost-analyzer-helm-chart#2619]
### Problem Statement

As of Kubernetes 1.25 and beyond (1.28 is out already) these APIs are depreciated:

From kube-state-metrics:v1.9.8
```
/tools/cache/reflector.go:108: Failed to list *v1beta1.CronJob: the server could not find the requested resource
/tools/cache/reflector.go:108: Failed to list *v2beta1.HorizontalPodAutoscaler: the server could not find the requested resource
/tools/cache/reflector.go:108: Failed to list *v1beta1.PodDisruptionBudget: the server could not find the requested resource
```
These resource versions no longer exist in 1.25. We run GKE 1.26.

This causes errors in the cluster logs, and on cloud platforms such as Google GKE it prevents automatic cluster upgrades from occurring.

### Solution Description

Removal of invalid API requests, either by an update to kube-state-metrics or another solution not requiring this component.

Either that, or some working ability to disable these metrics, as adding these options in the documentation did not work:
```
helm upgrade --install kubecost \
  --repo https://kubecost.github.io/cost-analyzer/ cost-analyzer \
  --namespace kubecost --create-namespace \
  --set networkCosts.enabled=true \
  --set prometheus.kube-state-metrics.disabled=false \
  --set prometheus.kube-state-metrics.collectors.cronjobs=false \
  --set prometheus.kube-state-metrics.collectors.horizontalpodautoscalers=false \
  --set prometheus.kube-state-metrics.collectors.poddisruptionbudgets=false
  ```

### Additional Context

A feature or fix to work on newer versions of K8 is important because clusters cannot auto-upgrade if services call invalid API versions.

**Comment by jondkelley** [comment]
Related to https://github.com/kubecost/cost-analyzer-helm-chart/issues/2445, however a new helm release has been tagged here and this issue still persists.

**Comment by kwombach12** [comment]
@jondkelley In our upcoming 1.107 release (Nov 1) we are disabling KSM by default so you should be safe to ignore these errors.

**Comment by jarl-tornroos** [comment]
@kwombach12 what advantages or reasons might there be to enable KSM in 1.107, especially if it's disabled by default?
Will it function differently than the current release with KSM disabled?

**Comment by thomasvn** [comment]
@jarl-tornroos Kubecost's functionality won't change if you have KSM enabled or disabled. As @kwombach12 mentions, it'll be disabled by default in v1.107 PR https://github.com/kubecost/cost-analyzer-helm-chart/pull/2573.

The primary advantage of enabling KSM in your environment, is for high availability purposes. Specifically, if `deployment/kubecost-cost-analyzer` were to be down, your `deployment/kube-state-metrics` would still be emitting metrics such as `kube_node_status_capacity_cpu_cores` ([docs ref](https://docs.kubecost.com/architecture/ksm-metrics)) which Prometheus could scrape.

**Comment by chipzoller** [comment]
Since KSM is now disabled by default and will remain disabled, closing this for now.
