### ISSUE TITLE
[Feature] Add support for use IAM Role instead Access and Secret Keys

### ISSUE THREAD

**Issue by vinycloud** [kubecost/cost-analyzer-helm-chart#2636]
### Problem Statement

In company that I work, we install kubecost but we can't use IAM users, Access Key and Secret Keys. And to configure Cloud Costs I need to pass Access and Secret Key. 

### Solution Description

I think if possible add IAM Role to configure this costs it's perfect and more secury.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
@thomasvn @jessegoodier, can you confirm this is only a Helm chart change and not an application change?

**Comment by jessegoodier** [comment]
It is possible with managed identities (simple annotation on the SA). We have a doc forthcoming.

@bstuder99 can share when it is published.

**Comment by jessegoodier** [comment]
When I read this I had been thinking about something else.
We already support this, and it is what we recommend here: https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations
Does this help @vinycloud? 

Also, if your kubecost primary is not in your AWS payer account, this is the streamlined guide: https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations/aws-cur-setup
