### ISSUE TITLE
1.106.3 helm chart not uploaded to ECR Public Gallery

### ISSUE THREAD

**Issue by vferreria-hs** [kubecost/cost-analyzer-helm-chart#2656]
https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.106.3 was release ~5 days ago, but is still not available in the Amazon ECR Public Gallery: https://gallery.ecr.aws/kubecost/cost-analyzer 

Will the Amazon ECR Public Gallery be updated? Thanks!

**Comment by jessegoodier** [comment]
This has been pushed. We ran into a bug with the most recent helm version. @chipzoller has more details.

Thanks for bringing it to our attention!

**Comment by chipzoller** [comment]
Chart is currently available [here](https://gallery.ecr.aws/kubecost/cost-analyzer).
