### ISSUE TITLE
[Feature] Fix/tighen permissions in main ClusterRole

### ISSUE THREAD

**Issue by chipzoller** [kubecost/cost-analyzer-helm-chart#2658]
### Problem Statement

The main ClusterRole has now incorrect and obsolete permissions which do not align with Kubernetes releases for the past long while.

### Solution Description

Adjust the permissions in the cost-analyzer's ClusterRole.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by dwbrown2** [comment]
Just curious, what Kubernetes versions are we currently aiming to support?

**Comment by chipzoller** [comment]
This is another open question we really need to resolve, but functionally I see no reason to support anything below about 1.19-1.20.

**Comment by chipzoller** [comment]
PR #2662
