### ISSUE TITLE
Have Grafana dashboards use an existing data source without name "Prometheus"

### ISSUE THREAD

**Issue by omerlh** [kubecost/cost-analyzer-helm-chart#266]
**Describe the bug**
When installing the dashboards using the config maps, and having an external grafana and Prometheus the following error is displayed on all the panels:

Datasource named Prometheus was not found

This is because my Prometheus datasource is not called "Prometheus".

**To Reproduce**
1. Deploy grafana and define a different prometheus datasource with some name
2. Deploy the dashboards with the charts (using `grafana.sidecar.dashboards.enabled = true`)
3. See the error

**Expected behavior**
Allow to choose the data source from all existing Prometheus data source. A big benefit will be to provide the dashboards using Jsonnet.

**Comment by dwbrown2** [comment]
Matt, mind taking a look?

**Comment by dwbrown2** [comment]
We have https://github.com/kubecost/cost-analyzer-helm-chart/pull/293 open to address. Any feedback on this approach, @omerlh?

**Comment by omerlh** [comment]
This is not my issue. I need to change the data source in the dashboards, not the one created by the chart. I have my own Grafana instance. Ideally, having something like mixin project that allows you to select the data source + cluster selector in each query.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dwbrown2** [comment]
Understood, let us investigate different paths forward.

**Comment by omerlh** [comment]
I was able to solve this easily with jsonnet:
```jsonnet
{
    local prometheusTemplate = {
          current: {
            text: 'default',
            value: 'default',
          },
          hide: 0,
          label: null,
          name: 'datasource',
          options: [],
          query: 'prometheus',
          refresh: 1,
          regex: '',
          type: 'datasource',
        },

    grafanaDashboards+:: {
        [name]:
            rawDashboards[name] + {
                editable: false,
                templating+: {
                    list: std.map(
                        function(template)
                            if std.objectHas(template, 'datasource') then 
                                template {
                                    datasource: "$datasource"
                                }
                            else template,
                        super.list
                    ) + [prometheusTemplate],
                },
                panels: 
                    std.map(
                        function(panel)
                            panel {
                                datasource: "$datasource",
                                styles: if std.objectHas(panel, 'styles') then  [ 
                                    super.styles[0] + if std.objectHas(super.styles[0], 'linkUrl') && super.styles[0].linkUrl != "" then
                                    {
                                        linkUrl+: '&var-datasource=$datasource'
                                    } else {},
                                ] else [],
                            },
                        super.panels
                    )
            },
        for name in std.objectFields(rawDashboards)
    }
}
```

This short script just adds a variable that let you choose which Prometheus to use :)

**Comment by dwbrown2** [comment]
Very cool! :)

I did some investigating last night... does it look like you can also do this directly with the Grafana chart? I would need to test this approach but just wanted to share in case it also looked promising:

https://github.com/helm/charts/blob/master/stable/grafana/values.yaml#L293

**Comment by omerlh** [comment]
It's not the same - using Jsonnet I was able to modify the dashboard json... this part just define which datasources to load

**Comment by dwbrown2** [comment]
Good stuff! Shall we mark this as closed for now?

**Comment by omerlh** [comment]
Yes
