### ISSUE TITLE
[Feature] Add storageClass option for Prometheus server in the Helm chart

### ISSUE THREAD

**Issue by igoratencompass** [kubecost/cost-analyzer-helm-chart#2709]
### Problem Statement

Option to specify a StorageClass for the packaged Prometheus server different from the default one.

### Solution Description

I want to be able to set a StorageClass for the packaged Prometheus server different from the default SC.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by dwbrown2** [comment]
This offer what you need? https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/charts/prometheus/values.yaml#L769

**Comment by chipzoller** [comment]
As pointed out, this ability is already present. Template results when enabling a value other than `"-"`:

```yaml
accessModes:
  - ReadWriteOnce
storageClassName: "foo"
resources:
  requests:
    storage: "32Gi"
```
