### ISSUE TITLE
[Bug] AWS ELB and Keycloak

### ISSUE THREAD

**Issue by xmploryg** [kubecost/cost-analyzer-helm-chart#2740]
### Kubecost Helm Chart Version

latest

### Kubernetes Version

AWS EKS 1.25

### Kubernetes Platform

EKS

### Description

I am currently experiencing two issues. 
1. The helm chart Service works with an ACM certificate tied to an ELB but the listening ports are not being configured in AWS and they are not sticky. Anytime the chart is updated the service even if there are no changes to that section of the chart will nock out the manual changes made to the ELB listening ports and reset the associated security group. 
2. The OIDC section for Keycloak works but there doesnt appear to be a way to manage group access its either all or none. 

Hopefully someone on the team can assist with this. If this is a bug or if its a failing on my part to properly configure the chart values. 

### Steps to reproduce

Deploy the chart with an AWS ELB contoller and ACM along with keycloack OIDC in front. 

### Expected behavior

See Description. 

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Can you point to the sections in the values you're configuring impacted by these points?

**Comment by xmploryg** [comment]
Sure. I'm OOO today but I'll post on Monday. The Service section and I
added an OIDC section like the docs where Keycloak example is given. I can
post the actual values info in detail on Monday.

**Comment by chipzoller** [comment]
Ping on this.

**Comment by chipzoller** [comment]
Closing until more details provided.
