### ISSUE TITLE
How to limit kube api server calls from kube-network-costs daemonset?

### ISSUE THREAD

**Issue by zakariais** [kubecost/cost-analyzer-helm-chart#2756]
Hi,
When we do high parallel scaling in our cluster, we get issue with kube api server going down
The root cause we saw is there 70% calls to kube api server are done from kubecost which overloads it and we have to delete the daemonset to get the api server back.
Any way we can limit the calls of it to kube api server?
We are using aws managed eks 1.24 version.

**Comment by chipzoller** [comment]
As stated in the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) in this repository, please keep issues relevant to the Helm chart only. This seems like a general question. Please either open a support ticket or bring this to the [Kubecost Slack workspace](https://kubecost.com/join-slack).

**Comment by dwbrown2** [comment]
We could also move this issue here: https://github.com/kubecost/features-bugs

@zakariais I've never heard of this happening, so it's surprising. Would definitely like to learn more.

**Comment by chipzoller** [comment]
Thread was opened in Kubecost Slack, #general channel [here](https://kubecost.slack.com/archives/CE76NJE6S/p1700053252514449).
