### ISSUE TITLE
[Feature] kubecost-cost-analyzer service session affinity 

### ISSUE THREAD

**Issue by sebbrandt87** [kubecost/cost-analyzer-helm-chart#2757]
### Problem Statement

The Helm template related to the `kubecost-cost-analyzer` Service must be extended to be able to define `sessionAffinity` and `sessionAffinityConfig`. With a SAML authentication and multiple Pods being scheduled, we need to respect the connection to the Pod which initiated the authentication.

### Solution Description

Add the needed Helm template parts.

### Additional Context

https://kubernetes.io/docs/reference/networking/virtual-ips/#session-affinity

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
What is the driver for this need?

**Comment by jessegoodier** [comment]
@sebbrandt87 We added the StatefulSet into 1.107.1 which will be out today.

Thanks again for that contribution!

What are you seeing when the session affinity isn't configured? 

And, do you want us to add the template, or are you planning to?

**Comment by sebbrandt87** [comment]
Added the case why it is needed into the opened issue **Problem Statement**
PR is 👇
