### ISSUE TITLE
[Bug] No mention of disabling kube-state-metrics by default in 1.107.0 release notes

### ISSUE THREAD

**Issue by csheppard00** [kubecost/cost-analyzer-helm-chart#2759]
### Kubecost Helm Chart Version

1.107.0

### Kubernetes Version

1.25

### Kubernetes Platform

EKS

### Description

Your release notes don't mention disabling kube-state-metrics by default.

### Steps to reproduce

1. Look at release notes

### Expected behavior

Mention major changes in release notes.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
You're right, thank you. Just fixed that in the release notes.
