### ISSUE TITLE
[Bug]  Replaced ConfigMap reloader with quay.io

### ISSUE THREAD

**Issue by FernandoMiguel** [kubecost/cost-analyzer-helm-chart#2762]
### Kubecost Helm Chart Version

1.107.1

### Kubernetes Version

1.27

### Kubernetes Platform

EKS

### Description

v1.107.1 has replaced ConfigMap reloader with a quay.io hosted one
https://github.com/kubecost/cost-analyzer-helm-chart/pull/2698

for us users using `values-eks-cost-monitoring.yaml` that defaults to `public.ecr.aws/bitnami/configmap-reload`
https://github.com/kubecost/cost-analyzer-helm-chart/blob/d0f89f9/cost-analyzer/values-eks-cost-monitoring.yaml#L154

so the upgrade from 1.106.x to 1.107.1 is broken
the changelog does not mention this breaking change on a minor release.
`values-eks-cost-monitoring.yaml` is also not updated to reflect this

### Steps to reproduce

1. upgrade from 1.106.x to 1.107.1

### Expected behavior

for prometheus pods to come back healthy

### Impact

restarting failed container=prometheus-server-configmap-reload

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Closed in #2763

**Comment by FernandoMiguel** [comment]
@chipzoller thanks!!
