### ISSUE TITLE
[Question] Prometheus scrape_timeout differences

### ISSUE THREAD

**Issue by FernandoMiguel** [kubecost/cost-analyzer-helm-chart#2765]
### Problem Statement

what is the reason for these two values to be different?

https://github.com/kubecost/cost-analyzer-helm-chart/blob/9775aae/cost-analyzer/values-eks-cost-monitoring.yaml#L126
https://github.com/kubecost/cost-analyzer-helm-chart/blob/9775aae/cost-analyzer/values.yaml#L702

Thanks in advance

### Solution Description

N/A

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Probably none. Feel free to open a PR.

**Comment by FernandoMiguel** [comment]
@chipzoller but i would not know which one is a better default :(

**Comment by chipzoller** [comment]
@thomasvn ??

**Comment by thomasvn** [comment]
@FernandoMiguel Unsure the reasoning why each of those `values.yaml` files redeclare the `scrape_timeout` and set different values. I'd recommend setting your `scrape_timeout` to 60s as this is what the Prometheus subchart sets as a default:

https://github.com/kubecost/cost-analyzer-helm-chart/blob/6b1e9a35ccb8471294ab609737ae0a09b8744d6a/cost-analyzer/charts/prometheus/values.yaml#L600

**Comment by chipzoller** [comment]
Seems like this is answered so closing for now. Feel free to respond if you need anything else.
