### ISSUE TITLE
prometheus arm image on public ECR

### ISSUE THREAD

**Issue by egeturgay** [kubecost/cost-analyzer-helm-chart#2803]
### Kubecost Helm Chart Version

v1.107.1

### Kubernetes Version

1.27

### Kubernetes Platform

EKS

### Description

ARM image for prometheus:v2.35.0 is present along with the right manifest but v2.47.2 is absent. Could you please push the prometheus image for ARM?

### Steps to reproduce

docker pull kubecost/prometheus:v2.47.2 to pull an image manifest, not amd image so ARM is supported

### Expected behavior

not to fail

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Done. Please confirm on your end.

**Comment by chipzoller** [comment]
Closing. Please comment if you still do not see it.
