### ISSUE TITLE
Implement Dark/Light Mode Toggle

### ISSUE THREAD

**Issue by Ayush9026** [kubecost/cost-analyzer-helm-chart#2826]
### Problem Statement

The website currently does not supports both dark and light modes, and a toggle button is provided for users to switch between them. However, there may be room for improvement or additional features that contributors can work on

### Solution Description

- [ ] Ensure the toggle button functionality is working correctly.
- [ ] Allow users to choose their preferred mode and remember the preference.
- [ ] Improve the design and aesthetics of dark and light modes.

### Additional Context

As marked in  Screenshot below.

![Kubecost Website](https://github.com/kubecost/cost-analyzer-helm-chart/assets/114745463/8fae0067-68ff-4209-93fa-96921953f552)

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
This is not a Helm chart issue and per the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) we state isn't appropriate for this repository. I have created this a feature request in our internal website repo.
