### ISSUE TITLE
Allow product to match multiple labels and/or relabelling in Prometheus

### ISSUE THREAD

**Issue by minac** [kubecost/cost-analyzer-helm-chart#288]
**What problem are you trying to solve?**
There are some workloads in our clusters over which we don't have full labeling control. The main examples are workloads installed by GKE and Operator created workloads (e.g. `prometheus-operator`). These workloads have their own labeling which doesn't always match ours. The result is a bigger `__unallocated__` bucket.

**Describe the solution you'd like**
One idea to get around this would be to allow for multiple labels to match kubecost's `product`. 
For example GKE-installed workloads tend to use the `k8s-app` label instead of `app`. If we could say that both these labels mean the same, they would be grouped correctly and not left unallocated.

**Describe alternatives you've considered**
An alternative / complementary idea would be to provide a way in kubecost's interface to use Prometheus' relabelling features. That way we could say that a set of labels we know of should be grouped into one specific product like `gke-infra` or `prometheus`.

**How would users interact with this feature?**
Ideally through the kubecost settings interface.

I'm not sure either of these is doable and they are lower in the priority list, but I thought I'd raise them.
Thanks!

**Comment by dwbrown2** [comment]
Thanks for the very detailed message! I have good news to report... this is already supported in our product today. You should be able to simply pass a CSV list of labels, example provided:

![image](https://user-images.githubusercontent.com/298359/74577453-0a748400-4f44-11ea-9bc5-f5d15b758fd1.png)

Let me know if you need anything else related to this request :)

**Comment by minac** [comment]
Hi @dwbrown2. Thank you for the update, that's great!

However, I tried adding the second label as part of comma-separated value (`app,k8s-app`), but the External Costs stop working as a result. 
Reverting to only one label works with the External Costs.

A follow-up question on this, how can I set the product labels in the `values.yaml` (or some other config) file? The idea is that I can deploy the same base configuration to all clusters.

Thank you.

**Comment by dwbrown2** [comment]
Miguel, that is great feedback. We do have a change to make in order to support external cloud costs mapping to multiple labels. Adding Ajay to review.

We can also get these label parameters added to this configs block: http://docs.kubecost.com/getting-started#install-configs

**Comment by minac** [comment]
Thank you @dwbrown2. 

I cannot find an example of how to set the label, for say a product, [in the config file](https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/values.yaml#L265-L291), nor in the [README](https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/README.md). Can you please provide one? Thanks!

**Comment by dwbrown2** [comment]
@minac we have a bit of work on our end to support labels in this config file. I'll follow up with an example.

**Comment by minac** [comment]
The part of being able to configure two labels to mean the same thing is completed.
It would be nice to be able to use selectors to group what's left in the 'Unallocated' category into meaningful things. For example, a big chunk of what goes into that category are GKE workloads and operator-created workloads. Which we know about these workloads, but cannot control the labeling for them, so they all end up in the same 'Unallocated' bucket when they could be relabelled using Prometheus (or something else) and grouped into for example 'GKE components'.

**Comment by dwbrown2** [comment]
Great input! We have some ideas in the works that may be able to provide early visibility into these unallocated workloads. I suspect it will be really helpful to get your further input after this initial feature release. I'll plan to follow once we start iterating on solutions.

**Comment by minac** [comment]
Hey @dwbrown2! It's been a while. 👋 
Do you have any news on this issue? Namely the `unallocated` workloads? It would be nice if we could group a bunch of workloads into a `gke` bucket or something. We know these workloads, but have no control over their labeling so they remain `unallocated`.

**Comment by dwbrown2** [comment]
We're going to discuss this week! Would being able to filter by say `app=""` and then view cost data by controller, pod, etc. meet your need? It sounds like no, but I just want to confirm. It sounds like the proposal would be to maintain a sort synthetic mapping in our product? 

Do you have an example `gke` workload? Are these mostly workloads in `kube-system`?

**Comment by minac** [comment]
The filter by `app` and then by another attribute is nice, and already available when I use the `/detail.html#&agg=product` aggregated view. So no, it's not what I'm asking here.

For example, when I aggregate by product there is always an `__unallocated__` in my top 5. This is mostly because workloads we do not control don't have the `app` label. If we could, for instance, have anything under `kube-system` show up as `gke` instead of unallocated (on Kubecost's side), it would be correct and reduce/eliminate what is essentially an `unknown` line item.
Does this make sense?

Thanks!

**Comment by dwbrown2** [comment]
@minac I absolutely understand the challenge you are trying to solve. So far we have aimed to reflect the current/historical state of Kubernetes. The primary option that I see here would be to develop another labeling/mapping system in our application that you could completely control. We will discuss more in our team meeting this week about how we could potentially support this. 

One workaround would be to label/annotate the namespace and then have specific controllers/workloads override this with their labels. That approach would have clear limitations though. 

As a side note, we are now adding the ability to filter by `app=__unallocated__` so that you can get more granularity for these specific workloads directly in our application.

**Comment by dwbrown2** [comment]
Update: we are just finishing PRs to allow multi-aggregation in the frontend. When completed, this would allow you to aggregate by the `k8s-app` label in addition to the `app` label. It may not perfectly mirror this request but may get us closer.

**Comment by dwbrown2** [comment]
Now in Kubecost [nightly builds](https://github.com/kubecost/docs/blob/master/release-process.md#nightly-releases), coming to production soon! 

Also, just wanted to highlight that you can also very easily drill into unallocated with 1-click with the Allocation UI.
