### ISSUE TITLE
[Bug] duplicate prometheus security context

### ISSUE THREAD

**Issue by sstarcher** [kubecost/cost-analyzer-helm-chart#2926]
### Kubecost Helm Chart Version

1.108.1

### Kubernetes Version

na

### Kubernetes Platform

EKS

### Description

entry is duplicated if you hit this else clause causing a collision

https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/prometheus-server-deployment.yaml#L69C21-L69C21

### Steps to reproduce

na

### Expected behavior

na

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Thanks for the report. I've sent PR #2930 for the fix but FYI the current plan is to remove the ConfigMap reloader from both Prometheus and Grafana for 2.0 (see PR #2908).
