### ISSUE TITLE
Allow modification of cost-analyzer-checks cronjob schedule

### ISSUE THREAD

**Issue by mcculloughsco** [kubecost/cost-analyzer-helm-chart#295]
**What problem are you trying to solve?**
We run clusters that have scheduled scale-downs during the weekend to save on cost. Kubernetes CronJobs have a [fundamental limitation](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#cron-job-limitations) where if the cronjob controller has missed 100 scheduled starts, the cronjob will not schedule further jobs. The cost-analyzer-check cronjob by default runs every 10 minutes, which means by the end of a weekend the cronjob will have missed 100+ scheduled runs.

**Describe the solution you'd like**
We would like to be able to define our own schedule for the cost-analyzer-check cronjob through a templated value. This way, we could schedule the cronjob to run only when our clusters will be spun-up and thus not encounter the 100 missed starts limitation. 

So for example, the global configuration in values.yaml:
```
kubecostChecks:
  schedule: "*/10 * * * 1-5"
```

Would then set the schedule of the cronjob in cost-analyzer-checks-template.yaml

```
spec:
  schedule: "*/10 * * * 1-5"
```

**Describe alternatives you've considered**
Currently, we manually delete and recreate the cost-analyzer-check cronjob, but this solution doesn't scale well with multiple clusters. We've considered writing our own service to manage cronjobs and restart them if they get into a bad state. However, we feel like this could be an issue that others running the cost-analyzer may run into, and thus configuration of the values here would be better. 

**How would users interact with this feature?**
Helm values.

**Comment by mikesplain** [comment]
Thanks for the great writeup Scott, unfortunately this is a pretty annoying issue for us.  It would be great if this value were configurable.  Thanks!

**Comment by AjayTripathy** [comment]
Hi @mcculloughsco, thanks for the detailed request! I had a chance to quickly review over the weekend and this definitely looks like something we can support. Let me follow up with a proposed solution. We may even want to adjust the default based on this feedback.

**Comment by AjayTripathy** [comment]
#307 makes the cronjob schedule configurable. However, note that if it isn't running around UTC midnight servertime on Sunday, the weekly update email will not be sent.

**Comment by mcculloughsco** [comment]
Thanks for the fix @AjayTripathy! We've run that fix for the last couple weeks and it's running perfectly! We will keep the note about the weekly update emails in mind.
