### ISSUE TITLE
Allow for aggregation by Job in Allocation view

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#298]

**Comment by dwbrown2** [comment]
@nikovacevic this is kinda support today with `ControllerType` in the Allocation view today. Would you call it done or would you want to do more?

cc @kirbsauce

**Comment by nikovacevic** [comment]
This will be addressed in the current work-in-progress on multi-aggregation!

**Comment by dwbrown2** [comment]
Referenced PR merged, will be available in next release.
