### ISSUE TITLE
[Bug] Issues with additionalLabels for aggregator

### ISSUE THREAD

**Issue by pjaak** [kubecost/cost-analyzer-helm-chart#3050]
### Kubecost Helm Chart Version

2.0.1

### Kubernetes Version

1.28.3

### Kubernetes Platform

Other (specify in description)

### Description

When adding add `global.additionalLabels` with aggregator stateful set enabled, it fails to deploy because their is an issue with the labels. Error received is:

`
selector does not match template labels 
`

After some digging I found that the template `aggregator-statefulset.yaml` had duplicate label sections:
<img width="445" alt="image" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/45154743/2a453e2a-8333-445c-bb56-c3a6353472e3">
However instead it should look something like this:
<img width="522" alt="image" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/45154743/029cc7e8-d846-48e2-8c64-a56fede1b341">

### Steps to reproduce

1. Enable aggregator statefulset.
2. Add additionalLabels.
3. Deploy

### Expected behavior

Expected no deployment issues and additional labels applied.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by dwbrown2** [comment]
Thank you for reporting @pjaak! 

@jessegoodier @chipzoller would either of you be able to triage?

**Comment by chipzoller** [comment]
Sent fix in #3053
