### ISSUE TITLE
Remove `basic-health` pod from ./cost-analyzer/templates directory

### ISSUE THREAD

**Issue by thomasvn** [kubecost/cost-analyzer-helm-chart#3069]
### Kubecost Helm Chart Version

2.0.2

### Kubernetes Version

1.28

### Kubernetes Platform

GKE

### Description

A GitOps depoyment of the Kubecost Helm Chart typically goes (1) `helm template` to render the k8s manifests and commit them to version control, then (2) `kubectl apply`

When running `helm template` it seems everything under the `./cost-analyzer/templates` directory is being templatized, including the CI tests which creates the `basic-health` pod. If possible, removing the CI tests from this directory could solve the issue?

### Steps to reproduce

TODO

### Expected behavior

TODO

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
We want to keep that because this is what enables `helm test`. For users who want to template their chart and omit tests, they should use the flag `--skip-tests`

**Comment by chipzoller** [comment]
```sh
$ helm template kubecost cost-analyzer/ | egrep basic-health
# Source: cost-analyzer/templates/tests/basic-health.yaml
  name: basic-health

$ helm template kubecost cost-analyzer/ --skip-tests | egrep basic-health
$ 
```

**Comment by thomasvn** [comment]
Ah perfect, thanks for the clarification!
