### ISSUE TITLE
[Feature] Allow the 'cloudIntegrationSecret' sanity check to be disabled

### ISSUE THREAD

**Issue by ravnalexquinn** [kubecost/cost-analyzer-helm-chart#3078]
### Problem Statement

The addition of the sanity check (that cannot be disabled presently) prevents the deployment of cost-analyzer by argocd, which runs a 'helm template' command to generate k8s manifests and then separately applies the rendered manifests. The helm template command is unable to process the 'lookup' function call included in the sanity check due to the fact that helm does not contact the k8s API during the process (as long as the '--dry-run=server' arg isn't provided), and so the templating fails due to the sanity check. 

See here the helm documentation for the 'lookup' function which explains this behaviour at the bottom: https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function

For cost-analyzer to be deployable with argocd, the sanity check would need to either be bypassed or made able to recognise when a k8s api connection is not present. 

As stated in the PR by @chipzoller here that added the check - https://github.com/kubecost/cost-analyzer-helm-chart/pull/3048
"It could potentially impact users who use tools or generate manifests from helm template".
Argocd is one CD tool which is impacted in that predicted way. 

### Solution Description

A nice solution would be to allow the sanity check to be toggled on/off with an '.enabled' flag. The flag would be set 'true' by default, allowing affected users to be able to actively disable it if required. 

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Although this was specifically tested to ensure `helm template` would continue to work, it seems Argo CD has further requirements when internally generating manifests. I note they have a feature to support Helm's `lookup` function [here](https://github.com/argoproj/argo-cd/issues/5202).

**Comment by chipzoller** [comment]
When I test this locally with Helm 3.13, a `helm template` completes successfully without the destination Secret existing. When I attempt to `helm install`, it fails as expected. What is Argo CD doing differently here which causes it to fail?

**Comment by chipzoller** [comment]
I sent #3083 after confirming this behavior on my end in Argo CD 2.10. Let me know your feedback here if you can.

**Comment by ravnalexquinn** [comment]
Thanks Chip, the PR looks great. Also greatly appreciate the speed of the response
