### ISSUE TITLE
Label filters not working as expected on out of cluster costs

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#313]
Using the label filter `app=myapp` on the Allocation view, causes all external costs to be filtered away. Here is an example request:

`/outOfClusterCosts?start=2020-3-1&end=2020-3-2&aggregator=namespace&req=577747&filterType=labels&filterValue=app=cost-analyzer` 

Reported by Miguel

**Comment by dwbrown2** [comment]
Ajay, Niko confirmed this requires a backend change.

**Comment by nikovacevic** [comment]
@AjayTripathy feel free to assign back to me if you want me to check out those queries

**Comment by minac** [comment]
This issue is still happening on version 1.55.

**Comment by dwbrown2** [comment]
@nikovacevic, I'm also able to recreate on v1.55 after filtering by `app=cost-analyzer`

Does this look like a reversion? Let me know how I can help

**Comment by nikovacevic** [comment]
@dwbrown2 Let's discuss today. The only "app" label we have in BigQuery is `app=jenkins`. To get that cost-analyzer label, it's now `kubernetes_label_app=cost-analyzer`, but we don't have any cost data sharing that label. We need to be more clear about the naming convention we intend to support for out-of-cluster costs.

**Comment by dwbrown2** [comment]
Niko, thanks a ton for looking at this and sorry for miscommunication on my end. This looks like the right solution to me for now.

**Comment by minac** [comment]
This seems to be solved in the latest version. I'm happy to close if true.
