### ISSUE TITLE
[Feature] Missing SecurityContext for cloud-cost Container

### ISSUE THREAD

**Issue by marcelkdevk** [kubecost/cost-analyzer-helm-chart#3187]
### Problem Statement

If cloudCost is enabled there is no possibility to set the securityContext for the container.

### Solution Description

Expanding _helpers.tpl file with a section below line 1053 with something like:
  {{- if .Values.global.containerSecurityContext }}
  securityContext:
    {{- toYaml .Values.global.containerSecurityContext | nindent 4 }}
  {{- end }}

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by AjayTripathy** [comment]
Might be a good one for @williamkubecost to pick up?

**Comment by ghost** [comment]
@marcelkdevk Thank you for your suggestion! I'll review this and provide an update once I have more info.

**Comment by ghost** [comment]
@marcelkdevk submitted a PR for this, thanks again for the suggestion!

**Comment by marcelkdevk** [comment]
Thanks a lot for adding it so quickly, @williamkubecost and @chipzoller!
