### ISSUE TITLE
[Feature] Support `image` property under `forecasting` so ECR only needs to update the base URL, but not the tag

### ISSUE THREAD

**Issue by pragmaticivan** [kubecost/cost-analyzer-helm-chart#3213]
### Problem Statement

When the helm chart is updated and forecasting image is bumped, anyone using the chart with a different registry such as ECr, also needs to bump the forecast image tag, since it only accepts the `fullImageName` property.

### Solution Description

Support `image` property only for `public.ecr.aws/kubecost/kubecost-modeling` where the tag is added by the helm chart.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by dwbrown2** [comment]
@chipzoller @michaelmdresser seems reasonable to be consistent here with other images?

**Comment by chipzoller** [comment]
Yes, we should do this.

**Comment by chipzoller** [comment]
Superseded by #3280. Closing.

**Comment by pragmaticivan** [comment]
All good, but note that this ticket was created before the other one (Mar 27). vs this ticket (Mar 8)
