### ISSUE TITLE
[Feature] Add support for populating federated-store.yaml via values.yaml

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#3216]
### Problem Statement

Many customers rely on automation in the form of IaC and CI/CD pipelines to deploy their applications.
It can be a burden to manage and maintain a secret using that approach, including updating values, base64 encoding, deploying, etc.

This file in particular, does not have any sensitive information in it if using something like AWS IAM Roles for Service Accounts (IRSA).

### Solution Description

The Kubecost Cost-Analayzer chart recently added the ability to maintain the cloud-integration secret as part of the values.yaml. A similar approach would be welcomed for managing the federated-store.yaml secret.

https://github.com/kubecost/cost-analyzer-helm-chart/blob/c5a0816e57831afe2741206606c27ec65e1328c3/cost-analyzer/values.yaml#L3196-L3238

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by dwbrown2** [comment]
@AjayTripathy any concerns on your end for supporting?

@cliffcolvin guessing this would be quick, but let us know if not.

**Comment by ghost** [comment]
I grabbed this, I think the PR is relatively straightforward.

**Comment by eahangari-8x8** [comment]
Hello, I hope you are doing well. 
I have a problem with installing kubecost using the argocd. In the values.yaml I see kubecostModel.federatedStorageConfigSecret which is commented and I tried to uncomment it and provide the secret name which I have it already there
but I get the following error: 

```
The federated storage config secret 'kubecost-object-store' does not exist or does not contain the expected key 'federated-store.yaml' Use --debug flag to render out invalid YAML
```

the secret kubecost-object-store is there with the correct key. 
I really appreciate it if you can help me with it.
Thanks

**Comment by thomasvn** [comment]
Hey @eahangari-8x8! It seems like the issue you're facing is slightly different than this Github Issue. Regarding your issue, have you followed the steps in [these docs](https://docs.kubecost.com/install-and-configure/install/multi-cluster/federated-etl#step-1-storage-configuration)? Specifically, check the following:

- Is the name of the k8s secret correct in the `values.yaml`, and is it in the same namespace?
- Does the k8s secret have a key named `federated-store.yaml`?

If you have any follow ups, I'd recommend reaching out to support@kubecost.com!

**Comment by eahangari-8x8** [comment]
Hi @thomasvn Thanks for your answer, yeah I have the secret in my kubecost ns 
![Screenshot 2024-06-27 at 12 37 18 PM](https://github.com/kubecost/cost-analyzer-helm-chart/assets/94546109/9f5cdbab-a361-4706-8d6f-24ee09dccb0c)

**Comment by srpomeroy** [comment]
@eahangari-8x8 Argo CD does not support templating a chart which uses the [lookup function](https://github.com/kubecost/cost-analyzer-helm-chart/blob/4e0340aa522875a311762a00f94dc2f8f8d63ffe/cost-analyzer/templates/_helpers.tpl#L218).

Can you try setting the following values?

```yaml
global:
  platforms:
    cicd:
      enabled: true 
      skipSanityChecks: true
```

**Comment by eahangari-8x8** [comment]
Hi @srpomeroy, Awesome man it works 😎  thank you so much. 🫡
