### ISSUE TITLE
[Bug] Grafana dashboards can no longer be deployed when using external Grafana

### ISSUE THREAD

**Issue by fheinecke** [kubecost/cost-analyzer-helm-chart#3219]
### Kubecost Helm Chart Version

v2.1.0

### Kubernetes Version

1.29

### Kubernetes Platform

EKS

### Description

Grafana dashboards can no longer be deployed when using external Grafana. This broke as a part of the v2.0.0 release. The cause of the issue is [this PR](https://github.com/kubecost/cost-analyzer-helm-chart/pull/2995/files#diff-513f39324e012e2b503ef6cae2767be6a0ae3049904be16ecc6657ed623a421eR4), which now requires `(eq (include "cost-analyzer.grafanaEnabled" .) "true")` to deploy any of the dashboards. This field is only true if [`global.grafana.enabled`](https://github.com/kubecost/cost-analyzer-helm-chart/pull/2995/files#diff-42b4c83c646cbd406a4cbfaa8a5cd2213440b3ed7e58f6e00a28c750fd9f13feR1059), which is also used as the only check [here](https://github.com/kubecost/cost-analyzer-helm-chart/pull/2995/files#diff-1fb59cfa043caf8b19336067922248eaedcc2a13b7aee7000247e066ec6ae24aR1) that determines if Grafana should be deployed with the chart.

### Steps to reproduce

1. Deploy kubecost, following the Grafana configuration guide on the v2.1 docs: https://docs.kubecost.com/install-and-configure/advanced-configuration/custom-grafana
2. Dashboard configmaps are not deployed

### Expected behavior

Dashboard configmaps should be deployed without also deploying Grafana

### Impact

Can no longer see historical data via single pane of glass

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by fheinecke** [comment]
I can file a PR to remove this check if desired - just need to know first if that is the correct solution.

**Comment by AjayTripathy** [comment]
@fheinecke I still think we want the ability to not deploy the configmaps. Can we replace this check with another one to control turning this off?

**Comment by fheinecke** [comment]
@AjayTripathy Yea that'd be great. Ideally the chart would support every combination of "grafana deployed <true|false>" and "grafana dashboards deployed <true|false>". In other words, dashboard deployment should be independent of grafana deployment.

Do you want me to file a PR for this or will Kubecost org handle it?

**Comment by AjayTripathy** [comment]
Would love a PR @fheinecke !

**Comment by ohayak** [comment]
I just encountred this today I confirn @fheinecke  solution
just replace `{{- if and (.Values.grafana.sidecar.dashboards.enabled ) (eq (include "cost-analyzer.grafanaEnabled" .) "true") -}}`  with `{{- if .Values.grafana.sidecar.dashboards.enabled }}`. in all grafana dashboards config maps

**Comment by AjayTripathy** [comment]
Cool, would take a PR @ohayak

**Comment by fheinecke** [comment]
This looks like it was fixed in https://github.com/kubecost/cost-analyzer-helm-chart/pull/3291. Thanks everybody!
