### ISSUE TITLE
[Bug] Collections has no pagination inside category view

### ISSUE THREAD

**Issue by Hronom** [kubecost/cost-analyzer-helm-chart#3242]
### Kubecost Helm Chart Version

2.1.0

### Kubernetes Version

2.1.0

### Kubernetes Platform

EKS

### Description

In collections when you select aggregation by category that has a lot of items there no pagination, so you can't see all items.

Select category aggregation:
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/429993/74629d04-b7f7-4ac0-bf69-b04a7c1cbebd)

View don't have pagination even if there a lot more elements:
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/429993/70c5255f-180b-442b-9f3c-f83a4ab0a058)

### Steps to reproduce

1. Navigate to collections
2. Create category that has a lot of collections
3. Select aggregation by category in collections
4. Click on category that has a lot of collections and you will see that you not able to check them all or paginate

### Expected behavior

Be able to paginate in category with a lot of collections

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by dwbrown2** [comment]
Currently being reviewed and aiming to get this addressed in our current (2.2) release!

**Comment by dwbrown2** [comment]
This is now implemented and currently being tested! Still expected to be part of 2.2 release.

**Comment by nealormsbee** [comment]
2.2.0 was released on Friday, and Collections now supports paging when aggregated by category!

The buttons are styled a little strangely and will be updated in a patch, but the functionality is there :)
<img width="1165" alt="image" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/981904/084e70ed-a049-4b57-a125-3533e336135a">


Closing this issue. Thanks for helping us improve the product, @Hronom.
