### ISSUE TITLE
[Bug]  Error when you try setup the Azure Cloud Billing Integration

### ISSUE THREAD

**Issue by ghost** [kubecost/cost-analyzer-helm-chart#3260]
### Kubecost Helm Chart Version

2.1.1

### Kubernetes Version

1.27.9

### Kubernetes Platform

AKS

### Description

I can not setup the Azure Cloud Billing Integration

I followed the steps showed in the guide: https://docs.kubecost.com/install-and-configure/install/cloud-integration/azure-out-of-cluster

When I try to deploy the latest setup I got the error

```
Error: execution error at (cost-analyzer/charts/cost-analyzer/templates/NOTES.txt:5:4): The cloud integration secret 'kubecost-integration' does not exist or does not contain the expected key 'cloud-integration.json'
If you are using `--dry-run`, please add `--dry-run=server`. This requires Helm 3.13+.
helm.go:84: [debug] execution error at (cost-analyzer/charts/cost-analyzer/templates/NOTES.txt:5:4): The cloud integration secret 'kubecost-integration' does not exist or does not contain the expected key 'cloud-integration.json'
If you are using `--dry-run`, please add `--dry-run=server`. This requires Helm 3.13
```

### Steps to reproduce

1. Step 1: Export Azure cost report
2. Step 2: Provide access to Azure Storage API

### Expected behavior

The application should be upgraded or deployed.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Has the Secret been created as the doc instructs? If so, are you using a CD tool like Argo CD to deploy Kubecost?

**Comment by fjvela** [comment]
- yes
- yes

**Comment by irodman-trimble** [comment]
If you're using Argo, you may need to add the following if also deploying via a Helm chart (see https://github.com/kubecost/cost-analyzer-helm-chart/issues/3078) -
```yaml
global:
  platforms:
    cicd:
      enabled: true
      skipSanityChecks: true
```
```sh
$ git blame cost-analyzer/values.yaml | grep skipSanity
ad06f06b8 (gcp-cherry-pick-bot[bot] 2024-02-07 15:14:57 -0500  250)       skipSanityChecks: false  # If true, skip all sanity/existence checks for resources like Secrets.
$ git blame cost-analyzer/templates/_helpers.tpl | grep skipSanity
ad06f06b8 (gcp-cherry-pick-bot[bot] 2024-02-07 15:14:57 -0500  169) Skip the check if CI/CD is enabled and skipSanityChecks is set. Argo CD, for example, does not
ad06f06b8 (gcp-cherry-pick-bot[bot] 2024-02-07 15:14:57 -0500  174) {{- if not (and .Values.global.platforms.cicd.enabled .Values.global.platforms.cicd.skipSanityChecks) }}
2f8d93f81 (gcp-cherry-pick-bot[bot] 2024-02-12 07:07:25 -0500  187) Skip the check if CI/CD is enabled and skipSanityChecks is set. Argo CD, for example, does not
2f8d93f81 (gcp-cherry-pick-bot[bot] 2024-02-12 07:07:25 -0500  192) {{- if not (and .Values.global.platforms.cicd.enabled .Values.global.platforms.cicd.skipSanityChecks) }}
```
Link in this repo at https://github.com/kubecost/cost-analyzer-helm-chart/commit/ad06f06b8

**Comment by chipzoller** [comment]
Closing, complete. Please use recommend Helm values.
