### ISSUE TITLE
Allow Kubecost backends to talk to one another instead of the frontend browser app

### ISSUE THREAD

**Issue by minac** [kubecost/cost-analyzer-helm-chart#332]
**What problem are you trying to solve?**
We use HTTP Auth to shield the Kubecost frontends from the world. When we try to add a new cluster to the interface the new cluster cannot be reached because it seems that the frontend app is not passing the `Authorization` header onward and hits an HTTP Auth 401 in the next cluster.

Trying to solve this on our side, I created an internal headless service that matches the `kubecost-cost-analyzer` service with annotations to give it an internal DNS name via `externalDNS`.

The service works, but adding a new Kubecost cluster from the index page fails with `Warning: No platform host found at http://myotherkubecostserver/model` from `helper.js` on line 1000.
The problem seems to be that the browser app is the one doing all the work, so it doesn't know about the internal DNS of the cluster.

**Describe the solution you'd like**
I would like for the Kubecost frontend to use the Kubecost backend/server to add/communicate with other clusters. If it did so, it would allow bypassing external auth systems because the backend is aware of internal DNS (from `externalDNS`).

**Describe alternatives you've considered**
The alternative would be to solve the `Authorization` header part in the frontend (see above) to allow frontends to communicate between themselves without getting HTTP 401s.

**How would users interact with this feature?**
If done right, the users wouldn't even know about this feature. :)

**Comment by quangngotan95** [comment]
👍 on this. Internally, most of our services use an istio-proxy sidecar to communicate directly with other services. So it'll be great if we have an option to add a sidecar into the frontend pod as well.

**Comment by dwbrown2** [comment]
This will be a longer-term effort, but Part 1 of this completed [here](https://github.com/kubecost/cost-analyzer-helm-chart/pull/402)!  Will be great to get your feedback on our next planned steps.

**Comment by minac** [comment]
:tada: on the implementation of secrets for communication between frontends. 

We are in the process of re-evaluating how we do auth internally, so we won't implement it just yet (due to cross namespace and secret duplications), but congratulations.

@dwbrown2 This solves the original request, so feel free to close this issue.

**Comment by kirbsauce** [comment]
Closing based on direction from @minac
