### ISSUE TITLE
[Bug] grafana ingress

### ISSUE THREAD

**Issue by ns-rkusumoto** [kubecost/cost-analyzer-helm-chart#3366]
### Kubecost Helm Chart Version

2.2.2

### Kubernetes Version

1.29

### Kubernetes Platform

EKS

### Description

grafana ingress fixes:
servicePort and ingressPath should be based on grafana instead of cost-analyzer.

{{- $servicePort := .Values.grafana.service.port -}}
{{- $ingressPath := .Values.grafana.ingress.path -}}

missing ingressClassName
spec:
{{- if .Values.grafana.ingress.className }}
  ingressClassName: {{ .Values.grafana.ingress.className }}
{{- end }}

### Steps to reproduce

1. {{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
ignores .Values.grafana.service.port and .Values.grafana.ingress.path
2. there is no spec.ingressClassName in grafana-ingress.yaml template

### Expected behavior

grafana ingress gets built as expected.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by jessegoodier** [comment]
Can you clarify the goal here @ns-rkusumoto ? 

I don't think our intention is to support an ingress directly to grafana as it would require other changes to the grafana.ini. 

Grafana is accessed via kubecost/grafana/ with the current design.

**Comment by ns-rkusumoto** [comment]
got it

**Comment by ns-rkusumoto** [comment]
I'm having an odd behavior with kubecost/grafana, I'm using an AWS ingress load balancer but kubecost is wanting to take https://kubecost/grafana and rewrite it as http://kubecost:9090/grafana.

Do I need to expose 9090 on my ingress?

**Comment by jessegoodier** [comment]
no, normal 80/443 works. if you go to 
/request-sizing in the ui and click a container, what happens?

**Comment by ns-rkusumoto** [comment]
ok, think it was a fluke.  I managed to get grafana to show up via some of the links.

**Comment by jessegoodier** [comment]
SG
be sure to use the trailing /
