### ISSUE TITLE
failed to create resource: namespaces "kubecost" not found

### ISSUE THREAD

**Issue by mikesplain** [kubecost/cost-analyzer-helm-chart#342]
**Describe the bug**
In chart version `1.54.1` it looks a change was made to allow grafana templates to [move to different namespaces](https://github.com/kubecost/cost-analyzer-helm-chart/pull/329).  The new default value is `kubecost`.

**To Reproduce**
1. Install kubecost in a namespace not called `kubecost`.

**Expected behavior**
Templates would respect the namespace they're installed into by default.

I'd expect the [default value](https://github.com/kubecost/cost-analyzer-helm-chart/pull/329/files#diff-b85b4513ccb2e26e15bc8a0a6b9ffa71R260) to be nil, therefore it would be loaded into the namespace the user selects when installing the release and only utilizing `namespace_dashboards` when overriding to a non release namespace.

**Comment by dwbrown2** [comment]
Thanks for reporting, Mike! We're investigating now.

**Comment by AjayTripathy** [comment]
Thanks for pointing this out. Fixed in #343

**Comment by dwbrown2** [comment]
Mike, this should be fixed in our last release, v1.55.0 

Let me know if we can get you anything else here!
