### ISSUE TITLE
Cannot set billing/pricing region info before initial startup

### ISSUE THREAD

**Issue by Zenmodai** [kubecost/cost-analyzer-helm-chart#346]
**Describe the bug**
At the moment you can set the currency in the values.yaml to EUR, but this will give an error during the initial download of the pricing data, since the default pricing info region is set to 'US'. This region info cannot be changed currently in the values.yaml. It can only be changed after installation in the settings page of the web frontend. So the current adaption will result in an error.

**To Reproduce**
1. Install with currency EUR
2. After installation check the log of the kubecost-cost-analyzer pod and the cost-model container.
3. There you can see the logs of the pricing info download and the error message.

**Expected behavior**
If the possibility to set the currency to EUR exists, then you should also be able to set the correct pricing/billing region for this currency to actually work. This should be possibly from the startup and not only after installation via manual configuration.

**Collect logs (please complete the following information):**
 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-model` and paste the output here:
```
provider.go:257] Found ProviderID starting with "azure", using Azure Provider
providerconfig.go:52] Could not find Custom Pricing file at path '/var/configs/azure.json'
router.go:962] No product-configs configmap found at installtime, using existing configs: configmaps "product-configs" not found
azureprovider.go:450] Using ratecard query OfferDurableId eq 'MS-AZR-0003p' and Currency eq 'EUR' and Locale eq 'en-US' and RegionInfo eq 'US'
router.go:1133] Failed to download pricing data: commerce.RateCardClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="" Message="Invalid region info:us and currency code:EUR combination specified\r\nParameter name: Currency"
```

**Comment by dwbrown2** [comment]
Thanks for pointing this out!! Definitely something we should support. Can you confirm that you're on Azure?

**Comment by Zenmodai** [comment]
Yes, I am on Azure.
