### ISSUE TITLE
[Bug] Broken link in values comment

### ISSUE THREAD

**Issue by chipzoller** [kubecost/cost-analyzer-helm-chart#3473]
### Kubecost Helm Chart Version

develop

### Kubernetes Version

1.29

### Kubernetes Platform

K3d

### Description

The link to https://docs.kubecost.com/apis/apis-overview/filters-api shown [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L2777C13-L2777C69) is broken.

### Steps to reproduce

1. Try to access the link https://docs.kubecost.com/apis/apis-overview/filters-api

### Expected behavior

All links referenced in Helm values work. It appears the link should reference https://docs.kubecost.com/apis/filters-api instead.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by dwbrown2** [comment]
I also believe this is the right link.
