### ISSUE TITLE
 Warning: Helm release "kubecost" was created but has a failed status. 

### ISSUE THREAD

**Issue by kaykhan** [kubecost/cost-analyzer-helm-chart#3479]
I am trying to install kubecost via helm but it timesout after 5 minutes with the following

>  Warning: Helm release "kubecost" was created but has a failed status. 

```
resource "helm_release" "kubecost" {
  name             = local.name
  namespace        = local.helm_chart_namespace
  create_namespace = true
  version          = "2.2.5"

  repository = "https://kubecost.github.io/cost-analyzer"
  chart      = "cost-analyzer"

  values = []

  depends_on = [
  ]
}
```

It shows up in a failed state but the notes comes back as successfully installed.

**helm ls -n kubecost**

>  NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS	CHART              	APP VERSION
> kubecost	kubecost 	1       	2024-06-18 11:30:36.855357113 +0100 BST	failed	cost-analyzer-2.2.5	2.2.5
>  

 
**helm get notes kubecost -n kubecost**

>  NOTES:
> --------------------------------------------------
> Kubecost 2.2.5 has been successfully installed.
> 
> Kubecost 2.x is a major upgrade from previous versions and includes major new features including a brand new API Backend. Please review the following documentation to ensure a smooth transition: https://docs.kubecost.com/install-and-configure/install/kubecostv2
> 
> When pods are Ready, you can enable port-forwarding with the following command:
> 
>     kubectl port-forward --namespace kubecost deployment/kubecost-cost-analyzer 9090
> 
> Then, navigate to http://localhost:9090 in a web browser.
> 
> Please allow 25 minutes for Kubecost to gather metrics. A progress indicator will appear at the top of the UI.
> 
> Having installation issues? View our Troubleshooting Guide at http://docs.kubecost.com/troubleshoot-install

what is happening here?

**Comment by chipzoller** [comment]
How are you installing, with what values, and in what platform or K8s version?

**Comment by kaykhan** [comment]
> How are you installing, with what values, and in what platform or K8s version?

No values are passed

AWS EKS 1.30

**Comment by chipzoller** [comment]
Starting in EKS 1.30, they are no longer configuring the `gp2` StorageClass as a cluster default. See release notes [here](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions-standard.html#kubernetes-1.30). If you did not follow any of their suggestions, Kubecost will not be able to start because the persistent volumes cannot be provisioned. You can check in your environment to see if that is the case.

**Comment by kaykhan** [comment]
> Starting in EKS 1.30, they are no longer configuring the `gp2` StorageClass as a cluster default. See release notes [here](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions-standard.html#kubernetes-1.30). If you did not follow any of their suggestions, Kubecost will not be able to start because the persistent volumes cannot be provisioned. You can check in your environment to see if that is the case.

I can see that their are pvc which have been bound. Are we sure it is to do with the volumes as this suggests otherwise?

**kubectl get pvc -n kubecost**  
```
NAME                         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
kubecost-cost-analyzer       Bound    pvc-aa6edb44-76de-434b-8dd3-bfb4d64768f7   32Gi       RWO            gp2            <unset>                 70m
kubecost-prometheus-server   Bound    pvc-2ddee964-3e81-456c-8587-5abd11d9bf80   32Gi       RWO            gp2            <unset>                 70m
```

Further looking at the pods i can see the forecasting is 0/1 (the issue could be here) 

```
NAME                                              READY   STATUS    RESTARTS       AGE
pod/kubecost-cost-analyzer-7d8fcf8db-5x9gd        4/4     Running   0              70m
pod/kubecost-forecasting-678f86f6b8-5fljx         0/1     Running   2 (3m4s ago)   70m
pod/kubecost-grafana-74cff4b575-84dpg             2/2     Running   0              70m
pod/kubecost-prometheus-server-865777c6cd-59c2c   1/1     Running   0              70m
```

The events of that pod show an issue with the health check

**kubectl describe pod/kubecost-forecasting-678f86f6b8-5fljx  -n kubecost**

```
Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  Warning  Unhealthy  13m (x407 over 73m)    kubelet  Readiness probe failed: Get "http://[2a05:d01c:516:b40c:a6fb::b]:5000/healthz": dial tcp [2a05:d01c:516:b40c:a6fb::b]:5000: connect: connection refused
  Warning  Unhealthy  3m18s (x418 over 73m)  kubelet  Liveness probe failed: Get "http://[2a05:d01c:516:b40c:a6fb::b]:5000/healthz": dial tcp [2a05:d01c:516:b40c:a6fb::b]:5000: connect: connection refused
  ```
  
  A detail worth mentioning here is that the cluster is using IPV6. I wonder if that is causing an issue with the readiness and livenesspobes?

**Comment by chipzoller** [comment]
Forecasting does not support IPv6 at this time. See [this issue](https://github.com/kubecost/features-bugs/issues/73).

**Comment by chipzoller** [comment]
I was able to successfully deploy Kubecost 2.2.5 on EKS 1.30 myself using default settings and after making one of the suggested changes per the release notes (configuring the PVCs to use the `gp2` StorageClass explicitly).

**Comment by kaykhan** [comment]
> Forecasting does not support IPv6 at this time. See [this issue](https://github.com/kubecost/features-bugs/issues/73).

Is there a workaround for this ? Is it just readiness probe and lvieness probes that are failing in an ipv6 only cluster? If so is it possible to mute those probes for now? Not sure the implications of that.

**Comment by chipzoller** [comment]
For now, you will have to disable the forecasting container in your Helm values.

**Comment by kaykhan** [comment]
thank you, i understand better as mentioned in that issue the underlining gunicorn server needs to support binding to both ipv6 and ipv4.
