### ISSUE TITLE
[Bug] Network Costs container always binds to 0.0.0.0 interface

### ISSUE THREAD

**Issue by konstantindobroliubov** [kubecost/cost-analyzer-helm-chart#3517]
### Kubecost Helm Chart Version

2.2.2

### Kubernetes Version

1.29

### Kubernetes Platform

EKS

### Description

network-costs daemonset deployed with helm chart creates daemon Pods.
In every Pod, I see:

```
/net # netstat -lntu | grep 3001
tcp        0      0 0.0.0.0:3001            0.0.0.0:*               LISTEN
```

Which means that `/rust/bin/network-costs-rs` binary which does all the magic uses IPv4 interface.
That makes it useless in IPv6-only environments.

### Steps to reproduce

1. Deploy helm chart with network-costs DaemonSet in IPv6-only environment.
2. SSH into the pod.
3. From the pod, run: `wget -O- http://0.0.0.0:3001/metrics`

### Expected behavior

Ideally, detect available interfaces on a startup and bind to `::` if running in IPv6 environment. 
Another option - just allow to override this parameter via helm chart flag.

### Impact

Network-costs don't work in IPv6-only clusters.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Previously logged at https://github.com/kubecost/features-bugs/issues/27
