### ISSUE TITLE
UID too long - dashboard pod-utilization-multi-cluster.json

### ISSUE THREAD

**Issue by ghost** [kubecost/cost-analyzer-helm-chart#3541]
### Kubecost Helm Chart Version

2.3.2

### Kubernetes Version

1.29

### Kubernetes Platform

EKS

### Description

Hi,

for latest `2.3.2` helm chart version with grafana/prometheus enabled we noticed a lof of errors:

```
logger=provisioning.dashboard type=file name=default t=2024-07-12T08:49:24.219438586Z level=error msg="failed to save dashboard" file=/tmp/dashboards/pod-utilization-multi-cluster.json error="uid too long, max 40 characters"
```

It looks like a https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/grafana-dashboards/pod-utilization-multi-cluster.json#L785 should be adjusted to something max 40 charactes - otherwise the dashboard cannto be processed (also noticed in this case kubecost links to Grafana stopped working).

### Steps to reproduce

1. Install latest helm chart (2.3.2) with grafana default settings
2. Observe grafana logs

### Expected behavior

No errors for Grafana dashboards

### Impact

Alerts regarding errors logged, non-working links

### Logs

```Shell
logger=provisioning.dashboard type=file name=default t=2024-07-12T08:49:24.219438586Z level=error msg="failed to save dashboard" file=/tmp/dashboards/pod-utilization-multi-cluster.json error="uid too long, max 40 characters"
```
```


### Slack discussion

_No response_

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by thomasvn** [comment]
Thanks @nowyp for reporting the issue! I've opened PR https://github.com/kubecost/cost-analyzer-helm-chart/pull/3543 which I believe has the fix. Let me know what you think.

**Comment by ghost** [comment]
@thomasvn LGTM! Thanks for quick reaction.

**Comment by ghost** [comment]
Hi, did you include it on 2.3.3? I still see this error after the latest upgrade.

**Comment by thomasvn** [comment]
Hi @nowyp I didn't include this as part of the patch release v2.3.3. @jessegoodier Do we think this should be part of the next patch release v2.3.4? If so we can cherry-pick this PR.
