### ISSUE TITLE
Add option to set azure client secret key in values.yaml 

### ISSUE THREAD

**Issue by Zenmodai** [kubecost/cost-analyzer-helm-chart#357]
**Describe the bug**
I tested the option to set the azure billing information via the vales.yaml, that was added with [PR](https://github.com/kubecost/cost-analyzer-helm-chart/pull/350). But after installation and container/pod startup the billing information cannot be downloaded from Azure. In the download link the subscription id is missing, therefore it fails with 'identity not found'.

Only when I add the 'Azure Client Secret' via the web frontend in the 'General settings', I can verify via the container logs, that the download of the billing information works. 
In the kubernetes configmap for the pricing the values are available, so this step works. Only the billing information download doesn't work. Not sure why the identity in the download link is empty and why it works after adding the azure client secret key.

**To Reproduce**
1. Add the Azure subscription, tenant and client ids to the values.yaml and install kubecost
2. After installation and startup check the log of the cost-model container, there you will see the output that the download of the billing information failed, because of missing identity.
3. Go to the web frontend and manually add the secret key in the empty field for it.
4. Wait 1-2 minutes and check log again, then the download worked.

**Expected behavior**
Add option to set the azure client secret key in the values.yaml.

**Collect logs (please complete the following information):**
```
provider.go:257] Found ProviderID starting with "azure", using Azure Provider
providerconfig.go:52] Could not find Custom Pricing file at path '/var/configs/azure.json'
router.go:962] No product-configs configmap found at installtime, using existing configs: configmaps "product-configs" not found
azureprovider.go:450] Using ratecard query OfferDurableId eq 'MS-AZR-0003p' and Currency eq 'EUR' and Locale eq 'en-US' and RegionInfo eq 'NL'
router.go:1133] Failed to download pricing data: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions//providers/Microsoft.Commerce/RateCard?%24filter=OfferDurableId+eq+%27MS-AZR-0003p%27+and+Currency+eq+%27EUR%27+and+Locale+eq+%27en-US%27+and+RegionInfo+eq+%27NL%27&api-version=2015-06-01-preview: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"} 
```

**Comment by dwbrown2** [comment]
Thanks for reporting! That PR you referenced was part one of supporting this path, we do still need to support adding a secret here. We should be able to prioritize in our next sprint.

**Comment by Zenmodai** [comment]
@dwbrown2 Is there an update regarding this? Or is this already done and I missed it?

**Comment by AjayTripathy** [comment]
This has been complete as of 1.62.0 @Zenmodai
