### ISSUE TITLE
Support large headers in the frontend nginx

### ISSUE THREAD

**Issue by michaelajr** [kubecost/cost-analyzer-helm-chart#361]
For our use case, the internal nginx for the frontend needs to support large headers. We pass a lot of cookies around internally so every request has several cookies in the headers. We also (at least for now) have the app behind an authentication proxy - the auth cookie is large for some people.

Obviously the auth cookie is not used by the KubeCost frontend - it is just an internal auth proxy to protect the endpoint. But the cookie is still passed.

So you need to add something like this...

```
server {
    large_client_header_buffers 4 32k;
}
```
...to the server block in the `cost-analyzer-frontend-config-map-template.yaml`

We have patched the chart and are hosting it internally - but it would be great if we did not have to do that. I can issue a PR for the fix, but still wanted to open the issue.

**Comment by AjayTripathy** [comment]
A PR would be awesome, but we're happy to do it if you don't have time!

**Comment by kirbsauce** [comment]
@AjayTripathy , is this an easy enough fix to get in anytime soon?

@michaelajr , are you still using the patch in your chart for this?

**Comment by AjayTripathy** [comment]
We can get this in, just curious of impact / if this is still an issue / if @michaelajr is still maintaining a fork / was interested in submitting a PR

**Comment by MichaelMeelisRTL** [comment]
I can confirm that this is still a problem. I just found this bug after a day of debugging and it fixed my problem. So a fix would be great :)

**Comment by mcwienczek** [comment]
PR with the fix has been opened: https://github.com/kubecost/cost-analyzer-helm-chart/pull/1003

**Comment by michaelajr** [comment]
Hey - sorry - meant to respond earlier - looks like a PR is in - and yes - that's the exact change to make.

**Comment by kirbsauce** [comment]
Thanks @michaelajr!  Looks pretty straightforward.  We'll get this asap.  Appreciate the contribution!

**Comment by kirbsauce** [comment]
PR merged.  Thanks again everyone!
