### ISSUE TITLE
Support service account annotiations

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#362]
See https://github.com/kubecost/cost-model/issues/266

To make it easier to use EKS service accounts to credential pods, we need to add the ability to annotate service accounts.

**Comment by michaelajr** [comment]
While you're at it, you should also allow the service type to be set to `LoadBalancer`.  This would allow us to add the annotation for AWS ELBs.

**Comment by AjayTripathy** [comment]
Hi @michaelajr -- I believe we already support setting the service type here: https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/values.yaml#L132

To clarify-- you mean you want the ability to annotate the service to attach it to an AWS ELB?

**Comment by sppwf** [comment]
@AjayTripathy Annotations support for "ServiceAccount", not for "Service"
this Template - https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/templates/cost-analyzer-service-account-template.yaml

```
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
```

also n Values.yam file
```
serviceAccount:
  annotations: {}
```

**Comment by dwbrown2** [comment]
Completed several months ago, let us know if there's more we can do here!
