### ISSUE TITLE
Add option to give authentication details for adding a new cluster

### ISSUE THREAD

**Issue by Zenmodai** [kubecost/cost-analyzer-helm-chart#364]
**What problem are you trying to solve?**
Currently for testing, I use an ingress with 'Basic authentication' to secure the access to Kubecost. Kubecost is deployed on 2 clusters. 
I want to add both clusters to the Kubecost site of the other one. So I can overview the costs for both clusters from both Kubecost instances. But I cannot add one cluster to the other, because I cannot authenticate while adding the new cluster instance to the other one. 
So the call fails with HTTP 401 Unauthorized and the add process isn't working.

**Describe the solution you'd like**
Please add an option to give authentication details (user, password, etc.) while adding a new cluster. So the call for adding a new cluster works, if you use (ingress) basic authentication for Kubecost.

**Describe alternatives you've considered**
No pretty alternative here

**How would users interact with this feature?**
Via frontend and/or the values.yaml

**Comment by dwbrown2** [comment]
@Zenmodai thanks for this input! We support basic auth today when adding clusters at install-time ([docs](https://github.com/kubecost/docs/blob/master/multi-cluster.md#add-at-install-time)) by opening a new window for this authorized endpoint. 

We are actively exploring ways to support this more seamlessly + securely. Just curious, would you be ok referencing a secret or auth credentials directly in values.yaml? Would you prefer to add credentials in the frontend or via values.yaml?

**Comment by Zenmodai** [comment]
@dwbrown2 thanks for the fast reply. 
It would probably be best to have both solutions (frontend and values.yaml). Let's say I have two environments (dev and staging). 
The dev env will be recreated every night and the staging env will be static. So for dev that will be recreated very often, it would be best to have the solution with the values.yaml file. 
But for staging, that will not be recreated often, the solution with the frontend, to manually add other clusters would make things easier.
A secret would be the cleaner solution. But please make it possible to also give custom keys for username and password for basic authentication as an example.

**Comment by dwbrown2** [comment]
@Zenmodai continuing to investigate solutions... if you're already going to store this information in Git. A short-term solution could be to pass these credentials directly in the endpoint provided to Kubecost. [More detail](https://stackoverflow.com/questions/2716990/http-basic-authentication-credentials-passed-in-url-and-encryption).

I agree that a secret is probably the right long-term solution too.

**Comment by minac** [comment]
I think what @Zenmodai is asking for is close to what we described here: https://github.com/kubecost/cost-analyzer-helm-chart/issues/332.

I believe this is a common ask because it's unlikely that you want to have Kubecost exposed to the public, and many teams don't require a full-blown SAML solution for it.

Ideally, one would be able to specify a secrets file or pass the credentials as environment variables. Then Kubecost (probably it's Nginx part?) would take that info to authenticate on the other cluster. 

The current solution of showing the multiple clusters as generic Kubernetes clusters without cost info is ok, but if Kubecost actually went past the auth part, then one could really have costs for all clusters being shown in the index page.

Does this help define the request?

**Comment by minac** [comment]
Seems like v1.57.2 solves this issue.

**Comment by dwbrown2** [comment]
This is done in the helm chart, but we have a lot more architecture changes on the way that will make it easier to navigate between environments!

**Comment by kirbsauce** [comment]
@dwbrown2 , seems like the original issue has been addressed.  close?

**Comment by dwbrown2** [comment]
Yep, this should be resolved! I'll close for now but please feel free to reopen at any point if there's more we can explore.
