### ISSUE TITLE
[Feature] Add ability to define resources for Cluster Controller

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/cost-analyzer-helm-chart#3641]
### Problem Statement

The cluster controller template does not currently support setting resources requests and limits in the pod spec.

### Solution Description

Add the ability to set resources on the cluster controller deployment.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by kwombach12** [comment]
Good catch @srpomeroy. cc: @chipzoller maybe we can work this into our 2.5 plan for KC actions assuming its a quick fix

**Comment by irizzant** [comment]
I think that https://github.com/kubecost/cost-analyzer-helm-chart/tree/develop/cost-analyzer is not aligned with https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml.

If you check the latter, there are many more options to set resources, still the one for cluster controller is missing

**Comment by chipzoller** [comment]
This is simple to address so we'll take care of it.

**Comment by chipzoller** [comment]
PR up at #3679
