### ISSUE TITLE
[Bug]  length of network insight is 0 as a result no need to write data

### ISSUE THREAD

**Issue by davidt-gh** [kubecost/cost-analyzer-helm-chart#3703]
### Kubecost Helm Chart Version

1.0.5

### Kubernetes Version

1.30

### Kubernetes Platform

EKS

### Description

Just installed new KubeCost but got some errors on the agent
[kubecost-cloud-agent.log](https://github.com/user-attachments/files/17293322/kubecost-cloud-agent.log)

### Steps to reproduce

1. Install helm chart

### Expected behavior

No errors

### Screenshots

![image](https://github.com/user-attachments/assets/308f09bf-dc94-4dc4-a074-fff64e893866)

### Logs

```Shell
attached
```

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Seems like this is a Kubecost cloud agent issue, and if so please open a ticket at support.kubecost.com.
