### ISSUE TITLE
[Bug] cost-analyzer-frontend nginx errors

### ISSUE THREAD

**Issue by cbonilla-liquid** [kubecost/cost-analyzer-helm-chart#3708]
### Kubecost Helm Chart Version

2.3.3

### Kubernetes Version

1.31

### Kubernetes Platform

EKS

### Description

`kubecost-cost-analyzer` pod is in `CrashLoopBackOff` because `cost-analyzer-frontend` container has errors.
`kubecost-cost-analyzer-b7db88b7b-6pc45                        3/4     CrashLoopBackOff `

I would like to know how to solve this issue.

### Steps to reproduce

`kubectl logs kubecost-cost-analyzer-b7db88b7b-6pc45 -n tools -c cost-analyzer-frontend`

2024/10/11 12:42:07 [emerg] 1#1: chown("/var/lib/nginx/tmp/client_body", 65532) failed (1: Operation not permitted)
nginx: [emerg] chown("/var/lib/nginx/tmp/client_body", 65532) failed (1: Operation not permitted)

### Expected behavior

No nginx errors on `cost-analyzer-frontend` container

### Impact

Can't access kubecost UI

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Please provide additional details on how/where you install Kubecost and with what values.

**Comment by cbonilla-liquid** [comment]
Hi, I've deployed it using Helm charts approach (using ArgoCD). 
Any specific values I should provide for helping on debugging the issue? I haven't changed default values of `kubecostFrontend:`section

**Comment by chipzoller** [comment]
Can you show the Application resource you used?

**Comment by chipzoller** [comment]
I just installed Kubecost 2.4.1 on an EKS 1.31 cluster using EKS values without issue.

**Comment by cbonilla-liquid** [comment]
@chipzoller Could you please share how you did it? I tried again from scratch and same problem. Thanks

**Comment by cbonilla-liquid** [comment]
I was able to fix it by changing `containerSecurityContext`permissions. Will close it.
