### ISSUE TITLE
[Bug] OKE install crashes with: provider is required

### ISSUE THREAD

**Issue by tcrowder-infios** [kubecost/cost-analyzer-helm-chart#3715]
### Kubecost Helm Chart Version

2.4.1

### Kubernetes Version

1.30.1

### Kubernetes Platform

Other (specify in description)

### Description

Support for Oracle Cloud was added in 2.4, but there doesn't appear to be any documentation surrounding it on the docs site.

Installing the helm chart from the default install produces the following for the cost analyzer:

```
DBG Recording prices...
panic: provider is required: failed to convert cost model provider

goroutine 1 [running]:
github.com/kubecost/kubecost-cost-model/pkg/cmd/costmodel.Initialize(0xc0014b1500)
	/app/kubecost-cost-model/pkg/cmd/costmodel/costmodel.go:1436 +0x267d
github.com/kubecost/kubecost-cost-model/pkg/cmd/costmodel.Execute(0x1?)
	/app/kubecost-cost-model/pkg/cmd/costmodel/costmodel.go:1997 +0x117
github.com/kubecost/kubecost-cost-model/pkg/cmd.Execute.newCostModelCommand.func1(0xc000f91b00?, {0x4ffdd0a?, 0x4?, 0x4ffdd0e?})
	/app/kubecost-cost-model/pkg/cmd/commands.go:69 +0x2f
github.com/spf13/cobra.(*Command).execute(0xc000d40f08, {0x8c5f600, 0x0, 0x0})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:916 +0x882
github.com/spf13/cobra.(*Command).ExecuteC(0xc00156ec08)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x38d
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
github.com/opencost/opencost/pkg/cmd.Execute(0x0?, {0xc00143fed0, 0x7, 0x7})
	/app/opencost/pkg/cmd/commands.go:61 +0x3a5
github.com/kubecost/kubecost-cost-model/pkg/cmd.Execute()
	/app/kubecost-cost-model/pkg/cmd/commands.go:44 +0x356
main.main()
	/app/kubecost-cost-model/cmd/costmodel/main.go:14 +0x13
```

### Steps to reproduce

1. Have an OKE cluster
2. Install via `helm install kubecost cost-analyzer --repo https://kubecost.github.io/cost-analyzer/ --namespace kubecost --create-namespace --set kubecostToken="bm9Ad2F5Lm9yYWNsZS5zdWNrcw==xm343yadf98"`
3. cost-model container crashes
4. Get the pod logs for the cost-model container

### Expected behavior

All pods to become Ready

### Impact

Yes, it doesn't work and documentation appears non-existent despite stating support for OCI and OKE in 2.4

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
As I understand it, this should be addressed in the upcoming 2.4.2 (which is not a Helm-related change). Closing this, but upon release if you continue to see this please log something at https://support.kubecost.com.
