### ISSUE TITLE
[Bug] Networks costs calculation for Kubernetes inner-cluster services

### ISSUE THREAD

**Issue by tadeha** [kubecost/cost-analyzer-helm-chart#3720]
### Kubecost Helm Chart Version

2.4.1

### Kubernetes Version

1.28.13

### Kubernetes Platform

EKS

### Issue Description:

We encountered some confusion while configuring network costs using the `destinations.in-zone` and `destinations.in-region` options. Based on the documentation, we expected traffic to be categorized correctly.

However, when the destination is a Kubernetes service (containing a Cluster IP) with a private IP address (e.g., 172.20.x.x), the metrics show that egress from the source to the service is within the same zone (`same_zone`). In our test case, the pod behind the service was actually located in a different availability zone, which didn’t match what the metrics showed. This suggests that the configuration may not always reflect the actual network topology accurately.

### Steps to reproduce

1. **In-Zone CIDR Ranges:**  
   The following CIDR blocks are defined for in-zone traffic:
   ```plaintext
   - 127.0.0.0/8
   - 169.254.0.0/16
   - 172.16.0.0/12
   - 192.168.0.0/16
   ```

2. **In-Region CIDR Ranges:**  
   These include the public and private CIDRs associated with our AWS VPC.

3. **Pod Setup:**  
   We deployed two pods: one acts as a server and the other as a client. To distribute them across different availability zones, we used node affinity rules. The client sends data to the server, which is set up with a service to receive the incoming data.

4. **Issue with Metrics Reporting:**  
   The `kubecost_pod_network_egress_bytes_total` metric for the client incorrectly indicates `same_region="true", same_zone="true"` despite the pods being located in separate zones.

### Expected behavior

The `kubecost_pod_network_egress_bytes_total` metric for the client is expected to show `same_zone="false"` since the pods are in different availability zones. However, it incorrectly displays `same_zone="true"` along with `same_region="true"`

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
I think this may not be a Helm chart specific question so could you log this at support.kubecost.com instead, please?

**Comment by mbolt35** [comment]
@chipzoller  This seems more related to network costs configuration that it does helm? 

They specifically note in step 1: 

The following CIDR blocks are defined for in-zone traffic:
```
- 127.0.0.0/8
- 169.254.0.0/16
- 172.16.0.0/12
- 192.168.0.0/16
```

> However, when the destination is a Kubernetes service (containing a Cluster IP) with a private IP address (e.g., 172.20.x.x), the metrics show that egress from the source to the service is within the same zone

Based on this description, I interpret as the traffic destination is some IP: `172.20.x.x`, and it's being classified as in-zone. This would make sense, as their in-zone configuration has the CIDR range: `- 172.16.0.0/12` which would include the IPs:
`172.16.0.0 -> 172.31.255.255` which includes their destination IP: `172.20.x.x`

Definitely not a bug.

**Comment by tadeha** [comment]
> @chipzoller This seems more related to network costs configuration that it does helm?
> 
> They specifically note in step 1:
> 
> The following CIDR blocks are defined for in-zone traffic:
> 
> ```
> - 127.0.0.0/8
> - 169.254.0.0/16
> - 172.16.0.0/12
> - 192.168.0.0/16
> ```
> 
> > However, when the destination is a Kubernetes service (containing a Cluster IP) with a private IP address (e.g., 172.20.x.x), the metrics show that egress from the source to the service is within the same zone
> 
> Based on this description, I interpret as the traffic destination is some IP: `172.20.x.x`, and it's being classified as in-zone. This would make sense, as their in-zone configuration has the CIDR range: `- 172.16.0.0/12` which would include the IPs: `172.16.0.0 -> 172.31.255.255` which includes their destination IP: `172.20.x.x`
> 
> Definitely not a bug.

Now, think about the scenario where it's removed from the list. How would Kubecost determine the AZ using the service's ClusterIP in that case?

**Comment by mbolt35** [comment]
@tadeha It will resolve the target to a Node, then uses the zone and region labels on the Node to compare with the source.
