### ISSUE TITLE
[Bug] Creation of collections and reports returns errors

### ISSUE THREAD

**Issue by ravnalexquinn** [kubecost/cost-analyzer-helm-chart#3734]
### Kubecost Helm Chart Version

2.4.2

### Kubernetes Version

1.30

### Kubernetes Platform

AKS

### Description

There are 2 issues being reported:

1: When you navigate to the 'Collections' tab and click 'Create New Collection', a pop-up appears with the text 'Failed to create collection' - See image 1.
There appear to be no logs relating to this at all in the pod.

2: When you navigate to the 'Reports' tab, click 'Create a report', then click 'Allocation report', then click 'Save' with any name, a pop-up appears in the top right with the text 'Failed to save report'. Again, there seem to be no relevant logs relating to these errors.

Please advise on what may be the cause for this, or what further information I can obtain (and from where) to help you produce a fix for these 2 issues.

### Steps to reproduce

(Copied from above)
 
1. When you navigate to the 'Collections' tab and click 'Create New Collection', a pop-up appears with the text 'Failed to create collection' - See image 1.
There appear to be no logs relating to this at all in the pod.

2: When you navigate to the 'Reports' tab, click 'Create a report', then click 'Allocation report', then click 'Save' with any name, a pop-up appears in the top right with the text 'Failed to save report'. Again, there seem to be no relevant logs relating to these errors.

### Expected behavior

You should be able to create collections and reports without seeing error pop-ups.

### Impact

The collection and reports functionalities are completely unusable.

### Screenshots

![collections-error](https://github.com/user-attachments/assets/52009f53-4366-4c8e-9709-748782d40948)
![reports-error](https://github.com/user-attachments/assets/53c1f5b1-ac72-4b13-9b72-52036c40ee07)

### Logs

```Shell
No relevant log lines seem to be present in the cost-analyzer pod's containers.
```

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Thank you for filing this issue, however it doesn't appear to be a Helm chart issue. Per our [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md), would you please file a support ticket at https://support.kubecost.com?
