### ISSUE TITLE
[Feature] more complex filters in alerts

### ISSUE THREAD

**Issue by rafal-skurka** [kubecost/cost-analyzer-helm-chart#3740]
### Problem Statement

In alerts, we can filter only on one dimension, e.g namespace, label etc. Would be great to have more complex alerts filters otherwise some alerts are impossible to do.

### Solution Description

Make more complex filters like in reports.

### Additional Context

The same issue - https://github.com/kubecost/cost-analyzer-helm-chart/issues/1834

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
As this is not a Helm specific request, please file at https://support.kubecost.com.
