### ISSUE TITLE
Clarification Needed on Node and Pod Count Calculation in Kubecost UI

### ISSUE THREAD

**Issue by Prasunamadasu** [kubecost/cost-analyzer-helm-chart#3747]
Hello!

I am using the free version of Kubecost (version 2.4.3) and I'm trying to understand how Kubecost calculates node and pod counts as displayed in the cluster details of its UI. I have noticed a discrepancy between the counts provided by Prometheus queries and those shown in Kubecost when filtering for the last 24 hours.

**Kubecost UI (cluster details):**
Node count: 85
Pod count: 1239

**Prometheus Queries:**
count(last_over_time(kube_node_labels[24h])) = 159
count(last_over_time(kube_pod_labels[24h])) = 2344

The differences in these counts are a bit confusing. Could you please explain how Kubecost calculates these metrics? Why might there be a discrepancy between Prometheus query results and what is displayed in the UI?

Additionally, are there specific Prometheus queries that would more closely match Kubecost's calculation method for these counts?

Understanding the methodology behind these numbers would be greatly appreciated. Thank you for your assistance!

**Comment by chipzoller** [comment]
Hello. For general Kubecost inquiries please either use Slack or the support portal at https://support.kubecost.com.
