### ISSUE TITLE
[Bug] Unable to retrieve 15 days of data using the Allocation API, even though the UI shows data for the same 15-day period

### ISSUE THREAD

**Issue by alisachen** [kubecost/cost-analyzer-helm-chart#3758]
### Kubecost Helm Chart Version

v2.4.3

### Kubernetes Version

1.31

### Kubernetes Platform

EKS

### Description

Unable to retrieve 15 days of data using the Allocation API, even though the UI shows data for the same 15-day period.
curl  https://kubecost.api.non-prod-uw2.hponecloud.io/model/allocation?window=2024-12-01T00:00:00Z,2024-12-01T23:59:59Z&accumulate=true&aggregate=namespace
response: {"code":200,"data":[null]}

But access the kubecost.api.non-prod-uw2.hponecloud.io in browser, it can show the data.

### Steps to reproduce

1. curl https://kubecost.api.non-prod-uw2.hponecloud.io/model/allocation?window=2024-12-01T00:00:00Z,2024-12-01T23:59:59Z&accumulate=true&aggregate=namespace
2. access the kubecost.api.non-prod-uw2.hponecloud.io in browser

### Expected behavior

Able to retrieve 15 days of data using the Allocation API

### Impact

can not use the API to get the data

### Screenshots

![image](https://github.com/user-attachments/assets/77acc29d-db36-4d10-91f9-a74870e4af7d)

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
As stated in the issue guidelines, please use support.kubecost.com for issues which are not Helm chart related
