### ISSUE TITLE
Could you provide images that support older CPUs at lower levels?

### ISSUE THREAD

**Issue by halcyon-r** [kubecost/cost-analyzer-helm-chart#3759]
### Problem Statement

I encountered the following error when trying to run kubecost on kubernetes v1.28.

```
$ kubect-n kubecost logs -f kubecost-forecasting-6566c59577-hfmpm
Fatal glibc error: CPU does not support x86-64-v2
```

The images I used are:
```
gcr.io/kubecost1/kubecost-modeling:v0.1.17
gcr.io/kubecost1/cost-model:prod-2.4.3
gcr.io/kubecost1/frontend:prod-2.4.3
```

I tried to use other versions of these images and found they all have this problem.

So could you provide images that support lower CPU models? Thank you.

### Solution Description

Provide images that can run kubecost on a CPU that does not support x86-64-v2.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
For all issues and requests which are not Helm chart specific, please use the support portal at https://support.kubecost.com.
