### ISSUE TITLE
Expose cache configurability

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#378]
Teams are increasingly running our product in "headless" mode with secondary Thanos deployments. Proposal is to allow users to manage cache settings in these deployments to reduce resource consumption. 

Potential paths I see:

1. Expose `kubecostProductConfigs.costModelCache.enabled` to allow for disabling. I believe this covers 90% of immediate needs. 

2. Expose `kubecostProductConfigs.costModelCacheWindows` where this can be set to values like `1,2,7,30` or `[]`. This approach seems more flexible but likely more complex to implement.

The only risk that I see is that our frontend may be slower in these deployments. We could either 1) provide option to disable frontend outright or 2) provide a warning in UI that cache is disabled.

@nikovacevic @AjayTripathy what do you think?

**Comment by dwbrown2** [comment]
From Ajay, he doesn't necessarily like the variable name. He would vote for something like `kubecostProductConfigs.costModel.cache`. He also proposed starting with something like option #1 and looking at add more functionality in the future. @nikovacevic let me know what you think!

**Comment by nikovacevic** [comment]
+1 on Ajay's variable name
+1 on keeping it simple with an enabled/disabled flag to start.

Setting windows could be an enhancement, but AFAIK we don't have anyone who wants the cache, but wants a completely different set of windows, do we?

**Comment by dwbrown2** [comment]
I like this approach too but want to just highlight one risk. Exposing `kubecostProductConfigs.costModel.cache` is exposing application internals. You could imagine this would lead us down a path towards `kubecostProductConfigs.costModel.cache` and `kubecostProductConfigs.savings.cache` etc, etc. This may become cumbersome for teams to manage. One idea to simplify would be to potentially just expose `kubecostProductConfigs.cache.enabled`.

**Comment by dwbrown2** [comment]
Part one of this is complete with `kubecostModel.warmSavingsCache` and `kubecostModel.warmCache` flags.

**Comment by AjayTripathy** [comment]
7d/30d caches are deprecated in favor of etl pipeline-- closing for now.
