### ISSUE TITLE
Run as nonroot user (PSP ON)

### ISSUE THREAD

**Issue by li-adrienloiseau** [kubecost/cost-analyzer-helm-chart#388]
Hello,
I'm using the latest chart with PSP ON on my EKS cluster:
`eks.privileged     false          RunAsAny   MustRunAsNonRoot   MustRunAs   MustRunAs   false            configMap,emptyDir,secret
`

**What problem are you trying to solve?**
Running this chart as nonroot user

**Describe the solution you'd like**
The image gcr.io/kubecost1/checks:prod-1.55.1 on kind: CronJob (cost-analyzer-checks) must run asnonroot user (todo: set empty securityContext)

**Comment by dwbrown2** [comment]
Thanks for reporting, Adrien! We'll investigate this in our upcoming sprint but let us know if you're interested in collaborating on this improvement.

Also, for additional context, this pod powers alerts & email updates. Here's an [architecture overview](https://github.com/kubecost/docs/blob/master/architecture.md).

**Comment by AjayTripathy** [comment]
I think this should be as simple as setting the SecurityContext on the checks pod-- no root capabilities are needed as far as I know.

**Comment by dwbrown2** [comment]
@li-adrienloiseau, was ajay's comment helpful? Let us know if it would be useful for us to add to our helm chart still.

**Comment by pierluigilenoci** [comment]
Hi @li-adrienloiseau this PR https://github.com/kubecost/cost-analyzer-helm-chart/pull/756/files should fix the issue.

**Comment by pierluigilenoci** [comment]
@AjayTripathy @dwbrown2 version 1.73.0 fix this issue. Very good! 👍

**Comment by pierluigilenoci** [comment]
But I've still a problem with Network Policy for kubecostCheck. Ref: https://github.com/kubecost/cost-analyzer-helm-chart/issues/761

**Comment by dwbrown2** [comment]
This core issue should be addressed. Closing while we look at #761. 

Please let us know if there are questions.
