### ISSUE TITLE
Support custom AWS tags for cost allocation

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#39]
Today, the commercial Kubecost product allocates out-of-cluster AWS costs by a fixed set of tags (e.g. `kubernetes_namespace`). We should instead allow these to be easily configured on the frontend. 

We should also support the ability to have multiple tags per individual Kubernetes concept (e.g. k8s_namespace and k8s/ns). This part can be considered out of scope for this issue if necessary.

**Comment by dwbrown2** [comment]
Work is underway on this.

**Comment by joerocklin** [comment]
Any updates on this?

**Comment by dwbrown2** [comment]
@joerocklin we now support a `customAggregation` parameter on the /outOfClusterCosts endpoint. Example use below. Is this format helpful? We have two related tasks in our backlog: 1) expose configuring this in the frontend and 2) migrating this data to the aggregated cost model endpoint. The latter requires a good bit of refactoring.

```
model/outOfClusterCosts?start=2020-1-13&end=2020-1-14&customAggregation=namespace
```

Happy to discuss further on our call today!

**Comment by dwbrown2** [comment]
Work finalized several months ago.. these values are not configurable in values.yaml. Please feel free to reopen if we can add more here!
