### ISSUE TITLE
Make Grafana datasource name configurable

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#399]
Allow users to template values for Grafana's dataSourceName:

https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/values.yaml#L286

**Comment by AjayTripathy** [comment]
This is done-- https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L389
