### ISSUE TITLE
Expose an option to disable persistent storage

### ISSUE THREAD

**Issue by alexbrand** [kubecost/cost-analyzer-helm-chart#4]
For testing purposes, it makes it easier if I don't have to worry about provisioning persistent storage. 

It would be nice to have an option in the helm values file to use emptyDir volumes instead of persistent volume claims.

**Comment by dwbrown2** [comment]
I investigated this quickly. I think we could pretty easily support Prometheus being deployed without a PV. I don't know how we would do this with our own product configs. I guess if the user chose this path then they would know that our configs would get blown up occasionally? Would using a `glusterfs` volume improve reliability a bit? @AjayTripathy any thoughts?

**Comment by AjayTripathy** [comment]
I went ahead and made it easy to turn off the Prometheus PV's. There are some changes to do this with our configs and it should be made clear that configs would get blown up.
