### ISSUE TITLE
Abandoned workloads page not loading

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#408]
Experienced in kc-integration cluster on our final prod candidate tonight. Pod had restarted soon before this. 

![image](https://user-images.githubusercontent.com/298359/79939242-74f9e280-8413-11ea-87b8-cfd9121eac6c.png)

**Comment by AjayTripathy** [comment]
Note that prometheus went down during this time period: kubecost-prometheus-server-6d5cbbb6cd-jqgj6         2/2     Running     0          9m8s

**Comment by nikovacevic** [comment]
Prometheus being down could definitely cause that error. I'll add checks to protect against that case.

**Comment by dwbrown2** [comment]
Sounds good! Sorry for reporting this with so little context. Found it in the middle of release. Let me know if I can share more.

**Comment by dwbrown2** [comment]
@nikovacevic, I believe this is fixed but just wanted to double check

**Comment by nikovacevic** [comment]
> @nikovacevic, I believe this is fixed but just wanted to double check

PR with that fix is awaiting review https://github.com/AjayTripathy/cost-analyzer-frontend/pull/63
