### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by rehevkor5** [kubecost/cost-analyzer-helm-chart#415]
**What problem are you trying to solve?**

We'd like to try using this but it does not have any software license.

**Describe the solution you'd like**

Add a license file to the repository, in the same way as done by eg. https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Describe alternatives you've considered**

None.

**How would users interact with this feature?**

They would read the license and know whether it's suitable for them to use or not.

**Comment by dwbrown2** [comment]
Thanks for reporting, Shannon! We plan to update this soon. Just curious, are there licenses that work or don't work for you and your team?

**Comment by nicholasklick** [comment]
Any progress on this? We at GitLab are interested in utilizing this chart.

**Comment by dwbrown2** [comment]
@nicholasklick, thanks for the message. I don't believe we've connected with anyone from your team. Would love to hear how we can best support your use case. Would you want to discuss soon?

**Comment by dwbrown2** [comment]
Apache 2.0 license added. Please let me know if we can share more information here!
