### ISSUE TITLE
Filter by ClusterID for Multi-cluster Grafana charts

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#426]
For multi-cluster deployments, we should give users the option views all clusters in a single Grafana dashboard. I see two parts two this:

1) ability to use Thanos datasource
2) allow filtering by clusterID

**Comment by AjayTripathy** [comment]
Part #1 is done.

**Comment by kirbsauce** [comment]
@AjayTripathy , any update on Part 2?

**Comment by dwbrown2** [comment]
We've done this for 1 dashboard, but very few users have noticed. I'm calling this low priority for now.

**Comment by AjayTripathy** [comment]
Tend to agree there. The grafana changes are a bit finnicky.

**Comment by kirbsauce** [comment]
@dwbrown2 , ok to close?

**Comment by dwbrown2** [comment]
SGTM, but anyone feel free to re-open if they are interested in working on this.
