### ISSUE TITLE
Unexpected model response:  'aggregateCostModel' request fails

### ISSUE THREAD

**Issue by Zenmodai** [kubecost/cost-analyzer-helm-chart#440]
**Describe the bug**
The cost aggregation doesn't work anymore. When opening the allocation page it only shows an error. The aggregateCostModel request fails. We use an external Prometheus, if this should somehow matter here.

**To Reproduce**
Not sure, since it only happened on one cluster without any changes. Another cluster with basically the same configuration has no problems.

**Expected behavior**
There shouldn't be any errors because of metrics with the same labelset. Since Kubecost itself creates and manages them. So if a problem occurs with a labelset, it should replace/delete those.

**Collect logs (please complete the following information):**
There are no errors in the prometheus or cost-analyzer pods during the execution of the request even afterwards. I only see the error in the browser console and allocation page of kubecost.

Request:
`https://kubecost.test123.io/model/aggregatedCostModel?window=1d&offset=1m&aggregation=namespace&allocateIdle=false&timeSeries=true&efficiency=true&aggregationSubfield=&sharedNamespaces=&sharedSplit=weighted&sharedLabelNames=&sharedLabelValues=&sharedSplit=weighted&req=709293`

Return-Error:
{"code":500,"data":null,"message":"Error: error computing aggregate cost model: vector cannot contain metrics with the same labelset"}

**Comment by dwbrown2** [comment]
@Zenmodai thanks for reporting. Can you please share a [bug report](http://docs.kubecost.com/bug-report) with team@kubecost.com? Either that or send us logs from the cost-model container in our pod?

**Comment by Zenmodai** [comment]
@dwbrown2 
The cost-model container log before and after the the request was made:

I0505 06:08:44.406393       1 profiling.go:14] [Profiler] 7.338551434s: ComputeAggregateCostModel(duration=2d, offet=1m, field=namespace)
I0505 06:08:49.832221       1 main.go:528] [Info] caching 2d cluster costs for 17m0s
I0505 06:08:49.832239       1 main.go:561] aggregation: warm cache: 2d
I0505 06:10:18.524066       1 main.go:513] [Info] aggregation: cache warming defaults: 1d:1m::::namespace::::weighted:false:false:true
I0505 06:10:18.524110       1 aggregation.go:1166] Logging cache items...
I0505 06:10:22.546623       1 costmodel.go:2832] [Profiler] 4.022441384s: costDataRange(24.000000h): Prom/k8s Queries: 
 - PodLabels took 1.801776227s
 - Normalization took 1.810326556s
 - GPURequests took 2.000085424s
 - RAMUsage took 2.009442066s
 - CPUUsage took 2.899946522s
 - RAMRequests took 3.505823178s
 - CPURequests took 3.611765779s
 - RAMAllocations took 3.919061723s
 - CPUAllocations took 4.022248282s
I0505 06:10:22.588664       1 profiling.go:14] [Profiler] 4.064569622s: ComputeAggregateCostModel(duration=1d, offet=1m, field=namespace)
I0505 06:10:28.221435       1 main.go:528] [Info] caching 1d cluster costs for 11m0s
I0505 06:10:28.221452       1 main.go:545] aggregation: warm cache: 1d
I0505 06:10:34.747072       1 aggregation.go:1166] Logging cache items...
I0505 06:10:34.748334       1 log.go:19] [Info] savings: cache hit Summary:Production
I0505 06:10:34.749361       1 aggregation.go:1166] Logging cache items...
I0505 06:10:34.786624       1 aggregation.go:1166] Logging cache items...
I0505 06:10:43.755538       1 costmodel.go:2832] [Profiler] 9.008413422s: costDataRange(24.000000h): Prom/k8s Queries: 
 - GPURequests took 1.380390358s
 - PVPodAllocation took 1.771266065s
 - PVRequests took 1.774646916s
 - PVCost took 1.777076653s
 - NetZoneRequests took 1.871692383s
 - NetRegionRequests took 1.88214874s
 - Daemonsets took 1.882227041s
 - NetInternetRequests took 2.271747528s
 - DeploymentLabels took 2.27919434s
 - ServiceLabels took 2.481788901s
 - RAMUsage took 3.471839461s
 - PodLabels took 3.605179076s
 - Normalization took 3.974189452s
 - CPURequests took 4.298994861s
 - CPUUsage took 4.387871704s
 - RAMRequests took 6.498272092s
 - CPUAllocations took 8.115023022s
 - RAMAllocations took 9.008215418s
I0505 06:10:43.790511       1 profiling.go:14] [Profiler] 9.043470151s: ComputeAggregateCostModel(duration=1d, offet=1m, field=namespace)
I0505 06:10:43.790605       1 profiling.go:14] [Profiler] 9.041283319s: ComputeAggregateCostModel(duration=1d, offet=1m, field=deployment)
I0505 06:10:43.790622       1 profiling.go:14] [Profiler] 9.004023755s: ComputeAggregateCostModel(duration=1d, offet=1m, field=label)
I0505 06:10:51.918533       1 aggregation.go:1166] Logging cache items...
I0505 06:10:51.950969       1 aggregation.go:1166] Logging cache items...
I0505 06:10:55.753064       1 costmodel.go:2832] [Profiler] 3.834475138s: costDataRange(24.000000h): Prom/k8s Queries: 
 - PodLabels took 1.219615629s
 - GPURequests took 1.501307585s
 - Normalization took 1.8067963s
 - RAMUsage took 2.602992931s
 - CPUUsage took 2.605356266s
 - RAMRequests took 3.314008274s
 - CPURequests took 3.613448898s
 - RAMAllocations took 3.715862546s
 - CPUAllocations took 3.834123333s
I0505 06:10:55.792393       1 profiling.go:14] [Profiler] 3.873895834s: ComputeAggregateCostModel(duration=1d, offet=1m, field=namespace)
I0505 06:10:55.792424       1 profiling.go:14] [Profiler] 3.841483744s: ComputeAggregateCostModel(duration=1d, offet=1m, field=namespace)

![Kubecost-Error](https://user-images.githubusercontent.com/47887818/81040491-c3938c00-8eab-11ea-9c71-f09b18b32238.png)
I also attached a screenshot with the error. As I mentioned I only see the error in the browser, strangely nothing in the logs, as you can see.

**Comment by dwbrown2** [comment]
Unfortunately nothing that helps here. Can you please share a [bug report](http://docs.kubecost.com/bug-report) with team@kubecost.com? I suspect this may be occurring in another pod, e.g. kube-state-metrics.

**Comment by Zenmodai** [comment]
After upgrading Kubecost to the just released latest version 1.58.0, at least now I see errors in the log. I also checked the prometheus and kube-state-metrics pods, but there were no errors there.

`I0507 06:43:19.092853       1 profiling.go:14] [Profiler] 3.149589214s: ComputeAggregateCostModel(duration=403m, offet=, field=container)
E0507 06:43:19.092876       1 log.go:11] [Error] ETL: ComputeAllocation: ComputeAggregateCostModel: vector cannot contain metrics with the same labelset
I0507 06:43:19.092897       1 log.go:23] [Profiler] 3.149660714s: ETL run: completed [2020-05-07T00:00:00, 2020-05-08T00:00:00]
E0507 06:43:19.092905       1 log.go:11] [Error] ETL error: vector cannot contain metrics with the same labelset
I0507 06:43:58.118612       1 costmodel.go:996] Kubecost prometheus metrics not currently available. Ingest this server's /metrics endpoint to get that data.
I0507 06:43:58.360163       1 aggregation.go:1194] Logging cache items...
I0507 06:43:58.367963       1 aggregation.go:1194] Logging cache items...
I0507 06:44:02.952888       1 costmodel.go:2811] [Profiler] 4.592650444s: costDataRange(24.000000h): Prom/k8s Queries: `

`E0506 12:03:44.138944       1 log.go:11] [Error] ETL error: empty data for range: 1440m offset 15123m
E0506 12:03:44.222672       1 log.go:11] [Error] ETL: ComputeAllocation: ComputeAggregateCostModel: empty data for range: 1440m offset 16563m: error computing normalization max(count_over_time(kube_pod_container_resource_requests_memory_bytes{}[1h] )) for start=2020-04-24 01:00:44.138 +0000 UTC, end=2020-04-25 00:00:44.138 +0000 UTC, window=1h0m0s, res=3600.000000: normalization data is empty: time window may be invalid or kube-state-metrics or node-exporter may not be running
I0506 12:03:44.222742       1 log.go:23] [Profiler] 83.873283ms: ETL build: coverage [2020-04-24T00:00:00, 2020-05-06T12:00:11]`

Maybe this helps? I run the bug report from the settings and checked the created textfile, but there wasn't any other output, that was noteworthy or that contained any further errors.

Prometheus and the kube-state-metrics pods are running, also multiple node-exporter.

**Comment by nikovacevic** [comment]
It would be very helpful to see the full [bug report](http://docs.kubecost.com/bug-report), which you can email to team@kubecost.com.

It might further help us isolate the issue if you could send us:
- Prometheus version
- contents of `https://kubecost.test123.io/model/metrics`

**Comment by nikovacevic** [comment]
This error is most likely caused by Prometheus configuration, which can be resolved with relabel configs, particularly the Prometheus Operator relabel config in our Custom Prometheus documentation: https://github.com/kubecost/docs/blob/master/custom-prom.md#cadvisor-metric-labels

To determine whether or not the relabel config above will resolve the issue, take the following diagnostic steps:

1. Run this query, expecting to see no errors. If an error does occur, there is a problem with the metrics your cAdvisor is emitting.
```
container_memory_working_set_bytes{container_name!="",container_name!="POD", instance!=""}[24h]
```

2. Run this query, expecting to see the error "vector cannot contain metrics with the same labelset". If an error occurs here, but not above, then the relabel config should resolve the problem.
```
label_replace(count_over_time(container_memory_working_set_bytes{container_name!="",container_name!="POD", instance!=""}[24h]), "node", "$1", "instance","(.+)")
```

**Comment by Zenmodai** [comment]
The queries behaved as you expected. So I rolled out the configuration changes yesterday and I verified it just now. The queries work without errors now and I can see the cost allocation again as well. So the issues has been resolved.

Thanks for the help.

**Comment by hverma95** [comment]
Hi @nikovacevic ,

We are also getting an error which is kind of related to the above discussion. Posting it below:
**ERROR**:

Unexpected model response: Error: error computing aggregate cost model: No data error: error computing normalization for start=2021-11-29 17:01:13.919686569 +0000 +0000, end=2021-11-30 17:01:13.919686569 +0000 +0000, res=1h0m0s: getNormalizations


Reference screenshot:
![image](https://user-images.githubusercontent.com/73820551/144095666-7f028829-260e-4909-a276-3fd1ca59ed2e.png)


See if you could assist here ?

**Comment by kbrwn** [comment]
@hverma95 Please upgrade to the latest release of kubecost ([v1.88.1](https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.88.1)) and report back if you are still having this issue.
