### ISSUE TITLE
Allow for custom namespaces (different from `kubecost`) when using a flat manifest instead of helm

### ISSUE THREAD

**Issue by minac** [kubecost/cost-analyzer-helm-chart#445]
**What problem are you trying to solve?**
For our production, it's ok (for now) to keep everything `kubecost` in a `kubecost` namespace. However, we have dynamic stagings that are namespaced, so we need to say what the namespace is.

**Describe the solution you'd like**
Create an entry in `values.yaml` for the namespace variable and use that in every template when a namespace is mentioned.

**Describe alternatives you've considered**
Right now I'm hacking it with a mix of `yq` and `sed` actions on top of the output from `helm`. 

Another alternative would be for the namespace to be an ENV variable.

**How would users interact with this feature?**
They would change the namespace variable from the default `kubecost` to whatever they needed.

**Comment by minac** [comment]
For reference, this is sort of what I'm doing:

```
yq write --inplace --doc '*' "path/to/bundle/file" 'metadata.namespace' '<%= namespace %>'
sed -i '' 's/namespace: kubecost/namespace: <%= namespace %>/g' path/to/bundle/file
sed -i '' 's/\.kubecost/\.<%= namespace %>/g' path/to/bundle/file
```

**Comment by AjayTripathy** [comment]
Hi @minac , my understanding is that installing with helm -n <namespace> or even generating the template with -n <namespace> should should cause any resources installed without an explicit namespace to be installed in <namespace> . To clarify, are there resources not being installed in <namespace> by default, or is this just an improvement to make all the namespaces explicit?

**Comment by AjayTripathy** [comment]
Ah sorry-- this is when installing from a flat manifest. I was able to reproduce this and edited the title to reflect that this is when generating a flat manifest.

**Comment by minac** [comment]
Yes, that’s what I meant! Sorry, thanks Ajay!

**Comment by AjayTripathy** [comment]
Hi Miguel, wondering if a quick fix would then be to generate the manifest yourself with helm commands. This seemed to work for me.

In helm 2
`
kubectl create namespace kc
helm fetch kubecost/cost-analyzer
helm template cost-analyzer-1.58.0.tgz --name kubecost --namespace kc > kubecost.yaml
kubectl apply -f kubecost.yaml --namespace kc
`
 In helm 3 I believe helm fetch becomes helm pull.

If this doesn't work for you let me know and we can explore other options.

**Comment by AjayTripathy** [comment]
^^ @minac did this end up working for you? Let me know.

**Comment by minac** [comment]
Sorry for the delay. Yes, thank you, it worked.
