### ISSUE TITLE
Secret `kubecost-grafana` `admin-password` changes every time

### ISSUE THREAD

**Issue by minac** [kubecost/cost-analyzer-helm-chart#448]
**Describe the bug**
Every time I deploy a new version of Kubecost the secret `admin-password` under `kubecost-grafana` changes. This is not a problem, but a nuisance because of how it reads in the PRs.

**To Reproduce**
1. `helm template kubecost --namespace kubecost ./cost-analyzer/ --values ../values.yaml`

**Expected behavior**
I would expect the secret not to change unless it was changed intentionally.

**Screenshots**
N/A

**Collect logs (please complete the following information):**
N/A

**Comment by dwbrown2** [comment]
We're aiming to upgrade Grafana (https://github.com/kubecost/cost-analyzer-helm-chart/issues/450). My hope is that this change will resolve this, but if not we will investigate further!

**Comment by dwbrown2** [comment]
Expecting this to be resolved with commit https://github.com/kubecost/cost-analyzer-helm-chart/pull/457/commits/899498f339e769ad23a9f35b4c47d95802a904e6!

**Comment by dwbrown2** [comment]
Should be resolved in latest, let us know if causes any more troubles!
