### ISSUE TITLE
Upgrade to Grafana v6.0.0

### ISSUE THREAD

**Issue by shawnshuang** [kubecost/cost-analyzer-helm-chart#450]
I see that the cost analyzer uses [v5.3.1](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/charts/grafana/Chart.yaml#L1) of Grafana.

With v6.0.0, Grafana [introduced](https://grafana.com/docs/grafana/latest/guides/whats-new-in-v6-0/#explore-and-prometheus) a new Prometheus query editor that seems to function similarly to the [Prometheus expression browser](https://prometheus.io/docs/visualization/browser/). Here's a [recording](https://www.youtube.com/watch?v=YDkCgQ802aY&feature=youtu.be&t=2526) from PromCon 2018 that showcases the new query editor.

Our team was having a lot of trouble exposing the expression browser (i.e. `/graph`) from the Prometheus server bundled with Kubecost over an ingress at a path (e.g. `k8s-cluster.com/kubecost/prometheus/graph`, `k8s-cluster.com/kubecost/prometheus`, or `k8s-cluster.com/kubecost/graph`).

A lot of the documentation we were reading on this seemed to suggest port forwarding instead. Port forwarding works for our non-production environments, but we don't want to grant the ability to port forward in production.

It would be nice if Kubeceost used at least v6.0.0 of Grafana so that we could use Grafana's new Prometheus query editor rather than trying to figure out how to expose the Prometheus expression browser in our infrastructure setup.

**Comment by dwbrown2** [comment]
Hi Shawn, we have this [open issue](https://github.com/kubecost/cost-analyzer-helm-chart/issues/320) due to several incompatible Grafana flag changes. Let us quickly investigate if we can get to  v6.0.0 for you though!

**Comment by shawnshuang** [comment]
@dwbrown2 Am I safe to assume that this issue can be closed? I believe I see the upgrade to Grafana being made to develop [here](https://github.com/kubecost/cost-analyzer-helm-chart/pull/457) and then to master [here](https://github.com/kubecost/cost-analyzer-helm-chart/pull/471). (If so, thanks for looking into this!)

**Comment by dwbrown2** [comment]
Yep, this should be complete! Let us know if you need anything else.

**Comment by shawnshuang** [comment]
Awesome, thanks for looking into this!
