### ISSUE TITLE
Consider disabling partial responses from thanos right now

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#451]
https://github.com/thanos-io/thanos/blob/master/docs/components/query.md#partial-response-strategy

We should consider setting partial response strategy to false, or it is possible during a store downtime that data is wrong/incomplete.

**Comment by kirbsauce** [comment]
@AjayTripathy , is this condition still possible or have we addressed it?

**Comment by AjayTripathy** [comment]
Thanos stability has improved a lot in the last year, so I think this can be closed/left to the user if they're using BYO thanos.
