### ISSUE TITLE
Why there are no tags in images used?

### ISSUE THREAD

**Issue by botzill** [kubecost/cost-analyzer-helm-chart#49]
I see no image tags here: https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/values.yaml#L24.

I'm using https://github.com/keel-hq/keel and very helpful when there is defined image repo and tag to be able to easily do updates. 

Thx!

**Comment by dwbrown2** [comment]
+@AjayTripathy for comment on this

I believe tags are passed via Chart.Version today.

**Comment by AjayTripathy** [comment]
We currently set tags in lockstep with the chart version: ie chart 1.24 must use tag 1.24.0 for all kubecost containers. So you can set the version via helm chart version. Is this not compatible with keel? If not, what would you like to see here?

**Comment by botzill** [comment]
Yes I see the tag added as: `        - image: {{ .Values.kubecostInit.image }}:prod-{{ $.Chart.Version }}`. This means that I have to manually add it in `values`. I guess that's OK, I can add them. 

But there can be cases when we increment the helm version, because we did some changes related to helm chart, and we may also want to increase its chart version. So, what I'm saying is that image tags should be separated fro helm version.

**Comment by dwbrown2** [comment]
I defer to @AjayTripathy on this. I see your point. I believe Ajay has been intentional about moving all of these versions numbers in lockstep. 

My only concern is that this would create problems for teams that use `--reuse-values` in their installs, often because they are fully automated.

**Comment by AjayTripathy** [comment]
Let's support this by marking the containers correctly with AppVersion and the charts themselves with chart version.

**Comment by AjayTripathy** [comment]
@botzill we have PR #60 to address this.

**Comment by AjayTripathy** [comment]
Went ahead and merged this-- let me know if there's still something you need here and feel free to re-open this issue if so.
