### ISSUE TITLE
Allow to create grafana dashboards configmaps

### ISSUE THREAD

**Issue by botzill** [kubecost/cost-analyzer-helm-chart#51]
Allow creating grafana dashboards config maps even if grafana is not installed with this chart. If we already have grafana installed and we create this config maps, on restart it should take them as well, no?

**Comment by dwbrown2** [comment]
@botzill if I'm understanding your question correctly, the dashboard ConfigMaps should still get created when [grafana.sidecar.dashboards.enabled](https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/values.yaml#L86) is true. 

Today, these ConfigMaps don't automatically get picked up by your existing Grafana deployment though... are you asking them to get picked up by your existing Grafana install?

Apologies if I misunderstood your question.

**Comment by botzill** [comment]
Hi. Yes, I was thinking to somehow be able to install them into existing
grafana installation automatically.

Is this possible?

Thx.

**Comment by dwbrown2** [comment]
I like this idea, I'm not aware of a solution yet. I would need to investigate further. 

@Nuru, have you automated this step yet?

**Comment by Nuru** [comment]
This was implemented in [release v1.26](https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.26), although not properly documented. If you set
```
global:
  grafana:
    enabled: false
grafana:
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: false
```
then this chart will not install Grafana but will install `ConfigMaps` for Grafana dashboards that will be picked up by the Grafana sidecar if you have Grafana with the [dashboard sidecar](https://github.com/helm/charts/tree/master/stable/grafana#sidecar-for-dashboards) already installed. (The `grafana.datasources.enabled: false` is not strictly required, but a good idea IMHO.)

**Comment by botzill** [comment]
I see, yes that I was looking for, it works, thx!

**Comment by AjayTripathy** [comment]
Closing since this seems done. Feel free to open another issue if support for other ways of auto-picking up the dashboards needs support.
