### ISSUE TITLE
Problem initializing a second pod

### ISSUE THREAD

**Issue by Zenmodai** [kubecost/cost-analyzer-helm-chart#515]
**Describe the bug**
I updated to the new version today and tested the feature regarding the support of multiple replica for the kubecost pod. But I encountered a problem during the init of the second pod. This init failed or is stuck, because the persistent storage cannot be attached to the second pod.
The storage has an access mode of ReadWriteOnce and there is also no pod/node affinity specified in the deployment configuration. So most likely, if you have multiple nodes, the second kubecost pod will be provisioned on another node and then the attaching of the storage fails. So the second pod cannot be initialized. I didn't find any documentation for considerations here.
 
**To Reproduce**
1. Update your already existing kubecost deployment and use at least 2 replicas. If you have multiple kubernetes nodes, this will fail.

**Expected behavior**
You should either set the access mode of the used storage to ReadWriteMany or specify an affinity in the deployment configuration, so the pods will provisioned on the same node. 
Or maybe another solution is possible here. 

**Collect logs:**
Warning   FailedAttachVolume     pod/kubecost-cost-analyzer-84854b7cb9-bg6k9        
Multi-Attach error for volume "pvc-5e5553f1-0112-4546-98f7-8686c464ac4e" 
Volume is already used by pod(s) ...

**Comment by dwbrown2** [comment]
Hi @Zenmodai, you can accomplish this today by deploying without the cost-analyzer PV and then setting configs via values/configmap. We officially support HA mode in business/enterprise tier, so reach out to team@kubecost.com if you want to learn more.

**Comment by Zenmodai** [comment]
@dwbrown2  ok, thanks for the answer. HA mode was just something I wanted to test.
Then additionally I also have a more general question. As long as I set all configs via the values.yaml, is the PV then not necessary anymore? Can I just remove it?

**Comment by dwbrown2** [comment]
You can indeed remove it. The only impact is that any config changes made in the UI will not persist after a pod restart.

**Comment by Zenmodai** [comment]
ok, thanks for information. Then this issue can be closed.
