### ISSUE TITLE
Default datasource can overlap with other default datasources

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#516]
"default" datasource may collide with people using other default datasources. Instead let's change to "kubecost-default" or similar and dynamically set the name of the datasource we'd like to use:

https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/grafana-datasource-template.yaml#L47

cc @gracedo

**Comment by dwbrown2** [comment]
what would happen if "kubecost-default" didn't exist?

**Comment by AjayTripathy** [comment]
You won't have a datasource and this would fail, but we should always be creating kubecost-default. For byo-prometheus, kubecost-default would be set to that value.

**Comment by AjayTripathy** [comment]
This is now called "default-kubecost".
