### ISSUE TITLE
Support AssumeRole on a master payer ARN in AWS.

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#523]
**What problem are you trying to solve?**
CUR access cross account. Because the file owner is AWS and not the master payer, to do a cross-account access of CUR would require an assumerole of an IAM in the master account.

**Describe the solution you'd like**
1. Add a field in helm chart to do supply the ARN of the role within the master account to assume
2. Make sure the existing IAM role for the kubecost pod has permissions to assume that role
3. For Athena access, we use the assumed master payer role ARN instead of  the provisioned pod role

**Comment by AjayTripathy** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/pull/525
https://github.com/kubecost/cost-model/pull/453

Should be what's required.

**Comment by dwbrown2** [comment]
Now complete in v1.61!
