### ISSUE TITLE
helm install with nodeselector

### ISSUE THREAD

**Issue by mikedizzle** [kubecost/cost-analyzer-helm-chart#530]
Maybe I'm missing something:

I'm running an AKS cluster with both Windows and Linux node pools. I have several pods of the solution that won't run complaining of Windows errors when I run a describe. I tried to install the helm chart with --set nodeSelector."beta\.kubernetes\.io/os"=linux to have the pods install in the Linux node pool but that doesn't seem to be work. 

when I do a describe pod none of them seem like they took the nodeSelector argument from the helm command

Like I said, I'm sure I'm missing something not sure what. Seems like it's mostly the grafana pods. The pods that are running have been scheduled on Linux.

NAME                                               READY   STATUS              RESTARTS   AGE
cost-analyzer-checks-1593639000-dd5m7              0/1     ImagePullBackOff    0          27m
cost-analyzer-checks-1593639600-x8zg8              0/1     ImagePullBackOff    0          17m
cost-analyzer-checks-1593640200-fx5hq              0/1     ImagePullBackOff    0          7m24s
kubecost-cost-analyzer-5647db7fb-qqgdf             3/3     Running             0          27m
kubecost-grafana-6c547987f-xvl4t                   0/3     ContainerCreating   0          27m
kubecost-kube-state-metrics-57f8864f5b-sxkjp       0/1     ContainerCreating   0          27m
kubecost-prometheus-alertmanager-7cdff76d5-68j5l   0/2     ContainerCreating   0          27m
kubecost-prometheus-node-exporter-5kjgz            0/1     ContainerCreating   0          28m
kubecost-prometheus-node-exporter-8z6mf            1/1     Running             0          28m
kubecost-prometheus-node-exporter-fz2sn            1/1     Running             0          28m
kubecost-prometheus-node-exporter-xx999            0/1     ContainerCreating   0          27m
kubecost-prometheus-server-68fd684cbf-hmfz7        0/2     ContainerCreating   0          27m

**Comment by dwbrown2** [comment]
Hi @mikedizzle looks like you have the node selector successfully applied to our core pod (cost-analyzer)! You should be able to also pass a nodeselector for each of the Kubecost dependancies:

// Grafana block
https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/values.yaml#L320

// Prometheus server block
https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/values.yaml#L188

Other blocks to pass this param should be `prometheus.kube-state-metrics` and `prometheus.nodeExporter`. Here's the full list of [supported references](https://github.com/kubecost/cost-analyzer-helm-chart/search?q=nodeSelector&unscoped_q=nodeSelector).

You can also optionally disable the checks pod if you are not using notifications. Let me know if this helps!

**Comment by mikedizzle** [comment]
My mistake is that I deployed my windows nodepool without a taint. That cleared it up any helm install issues. Thanks!
