### ISSUE TITLE
 Api authentication

### ISSUE THREAD

**Issue by thawkins** [kubecost/cost-analyzer-helm-chart#534]
Are there any authentication mechanisms available for the kubecost apis?

there does not seem to be any documented. 

Tim Hawkins CTO@Redflaggroup

**Comment by dwbrown2** [comment]
Hi @thawkins, sorry for the delay. We just returned from a US hoilday. We support a range of SAML options on our enterprise plan. More info [here](https://github.com/kubecost/docs/blob/master/user-management.md). We also support basic auth + Oauth proxy on our business tier. Let me know if we can share more!

**Comment by AjayTripathy** [comment]
Hey @thawkins, does the above satisfy your usecase? Anything else we can get you here?

**Comment by kirbsauce** [comment]
Hi @thawkins , closing this out for now, but please reopen if you feel it's unresolved. Happy to help!
