### ISSUE TITLE
Request Sizing Recommendations page drop metrics after deployment rolling update

### ISSUE THREAD

**Issue by abaskakau** [kubecost/cost-analyzer-helm-chart#551]
**Describe the bug**
Seems like cost sizing recommendations are being calculated based on pod names. When k8s deployment get modified (pod name changes), Kubecost doesn't propose last pod metrics over the specified time window.

Moreover, it looks like all Kubecost metrics are being calculated the same way, including cost efficiency

**To Reproduce**
1. Go to Request Sizing Recommendations at Kubecost UI
2. Screenshot current recommendations for specific deployment
3. Modify the deployment
4. See the difference

**Expected behavior**
Kubecost should store the metrics based on deployment name or specific tag and do not change request percentiles after deployment modifications

**Screenshots**
<img width="1443" alt="Screenshot 2020-07-15 at 13 39 18" src="https://user-images.githubusercontent.com/6757508/87536827-63d31180-c6a2-11ea-9d25-2e35e328ecc5.png">
<img width="1443" alt="Screenshot 2020-07-15 at 13 39 28" src="https://user-images.githubusercontent.com/6757508/87536834-66ce0200-c6a2-11ea-99e6-256b26a16648.png">

Right after the deployment modification:
<img width="1443" alt="Screenshot 2020-07-15 at 13 44 32" src="https://user-images.githubusercontent.com/6757508/87536895-76e5e180-c6a2-11ea-9006-f24a07133d0e.png">

After collecting new metrics:
<img width="1440" alt="Screenshot 2020-07-15 at 14 01 50" src="https://user-images.githubusercontent.com/6757508/87537719-c082fc00-c6a3-11ea-94f3-55163416882e.png">

**Comment by abaskakau** [comment]
I've modified aggregation rules inside Kubecost prometheus and seems that it helped.
But I'm still looking forward for non-workaround solution

**Comment by dwbrown2** [comment]
Hi @abaskakau, thanks for reporting. Today this feature does look at the usage history of active pods. When we worked with early users on this, we found that when they made a change to a deployment that affected the pods' resource usage, they don't want to have 29.5d of data using old pods skewing the 0.5d of new data. Sounds like it would be helpful for you to see previous pods as well? Do you have a specific situation in mind where this would be most helpful?

**Comment by kirbsauce** [comment]
Hi @abaskakau.  I just wanted to follow up to see if you have any more thoughts or information regarding your report.  We're always interested to hear user feedback!

**Comment by dwbrown2** [comment]
@michaelmdresser historical pods are now reflected in new algorithm correct?

**Comment by michaelmdresser** [comment]
Historical pods are reflected now. I expect that this behavior won't occur any more, but I haven't tested it specifically.

**Comment by dwbrown2** [comment]
That's my understanding too. @abaskakau can you let us know if you experience on a recent Kubecost release?
