### ISSUE TITLE
deployment on CentOS7 blocked because of AppArmor

### ISSUE THREAD

**Issue by rptaylor** [kubecost/cost-analyzer-helm-chart#552]
**Describe the bug**
When trying to deploy kubecost on a CentOS7 cluster using Helm 3, I follow the instructions from https://kubecost.com/install  , but the grafana pod is blocked:
```
kubecost-grafana-6c547987f-5dmcl                    0/3     Blocked     0          17h
```

The reason is
```
    state:
      waiting:
        reason: Blocked
  hostIP: 10.0.0.4
  message: 'Cannot enforce AppArmor: AppArmor is not enabled on the host'
```

The PSP is kubecost-grafana and it includes
```
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
```

If I manually `kubectl edit podsecuritypolicy kubecost-grafana` and remove the 2 apparmor lines, it works.
Instead of requiring manual configuration modifications for kubecost to work on CentOS7, could there be a Helm chart variable like apparmor.enabled , or some other way to detect whether apparmor should be enabled?

**To Reproduce**
Deploy kubecost with Helm 3 on a CentOS7 k8s cluster that has the PodSecurityPolicy admission controller enabled.

**Expected behavior**
Kubecost should be supported on CentOS7 and the Helm chart should provide the proper configuration for the grafana pod to start running. Instead, the Helm chart specifies that apparmor should be enabled in the kubecost-grafana podsecuritypolicy.
But Apparmor is not available on CentOS7 so the deployment does not work.

**Comment by rptaylor** [comment]
Similar to https://github.com/helm/charts/pull/9128

**Comment by dwbrown2** [comment]
Thanks for reporting @rptaylor! You should be able to get around this issue by setting this [psp flag](https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/charts/grafana/values.yaml#L3) in our Grafana subchart to false.  Let me know if that meets your immediate need.

**Comment by rptaylor** [comment]
@dwbrown2 Thanks. Unfortunately I don't think that will help much. If pspEnabled is false, it looks like the PSP for grafana, and RBAC rule to use that PSP, will not be created. But if grafana does not have permission to use any PSP , it will still be unable to run on a cluster with the PSP admission controller enabled (which I think is the default k8s behaviour now).

This appears to be solved in the upstream Grafana chart via https://github.com/helm/charts/pull/9128 
in chart version 1.22.1 via commit https://github.com/helm/charts/commit/2f316acc4167ca527a5da0a3932421e05974d7cd#diff-835de242b97ddff99940fe9c087db33f

Any chance to bring this improvement from the upstream Grafana chart into the Kubecost chart?

Thanks!

**Comment by dwbrown2** [comment]
Got it, so in your case you still need the psp to be created? I see this old issue Grafana stable issue: https://github.com/helm/charts/issues/9090

@AjayTripathy thoughts on this?
