### ISSUE TITLE
kubecost.yaml is empty

### ISSUE THREAD

**Issue by hadim** [kubecost/cost-analyzer-helm-chart#562]
https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/kubecost.yaml is empty.

**Comment by AjayTripathy** [comment]
Apologies, this broken when we migrated our build systems from helm2->helm3. Fix coming shortly.

**Comment by hadim** [comment]
Could you also generate it for https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.62.0/kubecost.yaml ?

Thanks!

**Comment by AjayTripathy** [comment]
I just generated a new file and merged it to master and develop-- does that work for you? I'd like to avoid doing a force push to the v1.62.0 tag if at all possible.

**Comment by hadim** [comment]
Is `master` the same as the 1.62.0 tag?

**Comment by hadim** [comment]
All seems good so far. Thanks again.

**Comment by AjayTripathy** [comment]
No problem, thanks for the report. Master right now is 1.62.0+the additional file, and we keep master essentially locked to releases (new changes go to the develop branch until a release is ready)
