### ISSUE TITLE
Parse error at   **cost-analyzer/templates/_helpers.tpl:133**  unexpected "=" in operand

### ISSUE THREAD

**Issue by j-hedtke** [kubecost/cost-analyzer-helm-chart#566]
https://github.com/kubecost/cost-analyzer-helm-chart/blob/4e9fd75f041c5b8957ed342621f367e489169f13/cost-analyzer/templates/_helpers.tpl#L133

**Comment by dwbrown2** [comment]
@j-hedtke thanks for reporting. are you able to share steps to recreate?

**Comment by dwbrown2** [comment]
@mbolt35 as FYI

**Comment by j-hedtke** [comment]
@dwbrown2 it happens on install

**Comment by dwbrown2** [comment]
@j-hedtke can you share how and where you installing? I am not able to recreate on install or upgrade.

**Comment by j-hedtke** [comment]
@dwbrown2 yea, I'm running this: 

helm install kubecost/cost-analyzer --namespace <namespace> --name cost-analyzer --values values.yaml

**Comment by dwbrown2** [comment]
Thank you, can you share the output to these commands? 

```helm version```
```kubectl version```

Also, just want to make sure you are removing brackets in that command...

**Comment by j-hedtke** [comment]
I'm running helm 2.9.1 client and server and kubectl client 1.12.7 server 1.14.10-gke.42

And yes, of course

**Comment by AjayTripathy** [comment]
Hi @j-hedtke , I wasn't able to reproduce on a later version of helm2. Is there any chance you'd be able to upgrade to the latest, or at least a later version of helm2?

```./helm version
Client: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}

./helm install kubecost/cost-analyzer --namespace kc --name cost-analyzer
NAME:   cost-analyzer
LAST DEPLOYED: Tue Jul 28 19:14:35 2020
NAMESPACE: kc
STATUS: DEPLOYED

RESOURCES:
==> v1/ClusterRole
NAME                               AGE
cost-analyzer                      3s
cost-analyzer-grafana-clusterrole  3s

==> v1/ClusterRoleBinding
...
```

**Comment by j-hedtke** [comment]
@AjayTripathy @dwbrown2 upgrading to 2.16.9 fixed it. Thanks guys!

**Comment by j-hedtke** [comment]
@AjayTripathy @dwbrown2 upgrading to 2.16.9 fixed it. Thanks guys!

**Comment by dwbrown2** [comment]
Glad to hear, @j-hedtke! Let me know if we can help with anything else.
