### ISSUE TITLE
Secret cloud-service-key is not correctly mounted due to property missmatch

### ISSUE THREAD

**Issue by KealanM** [kubecost/cost-analyzer-helm-chart#575]
**Describe the bug**
When using the helm chart to install and using the helm value kubecostProductConfigs.createServiceKeySecret to generate the kubernetes secret there is a mismatch in property names with respect to getting the new secret mounted by the kubecost cost analyzer deployment template. Please refer to these searches to see the properties and the associated uses 
createServiceKeySecret: https://github.com/kubecost/cost-analyzer-helm-chart/search?q=createServiceKeySecret&unscoped_q=createServiceKeySecret
createServiceKey https://github.com/kubecost/cost-analyzer-helm-chart/search?q=createServiceKey&unscoped_q=createServiceKey

**To Reproduce**
1. Run the following Command 
`helm install --set kubecostProductConfigs.createServiceKeySecret=true,kubecostProductConfigs.awsServiceKeyName=dummy --namespace kubecost-test kubecost/cost-analyzer --debug --dry-run > dryrun.yaml`
2. Inspect the dryruin.yaml output and you will see that
a) That the service secret is correctly generated
`apiVersion: v1
kind: Secret
metadata:
  name: cloud-service-key
type: Opaque
stringData:
  service-key.json: |-
    {
      "aws_access_key_id": "dummy",
      "aws_secret_access_key": ""
    }`
b) The secret is not correctly mounted in the cost-analyzer deployment

**Expected behavior**
One property such drive this behaviour and as its documented in the values value it should be the createServiceKeySecret value that is used.

**Comment by AjayTripathy** [comment]
Thank you so much for this report! I've created https://github.com/kubecost/cost-analyzer-helm-chart/pull/577 to address, we expect to release it in the next few days in a minor release.

**Comment by AjayTripathy** [comment]
@KealanM this should be fixed-- feel free to re-open if you experience any issues.
