### ISSUE TITLE
cost-model failing to configure from pricing-configs configmap for AWS

### ISSUE THREAD

**Issue by KealanM** [kubecost/cost-analyzer-helm-chart#578]
**Describe the bug**
If the pricing-configs configmap is deployed when you set the aws settings in the kubecostProductConfig section cost model is failing to properly configure itself. This means install time configuration is not functioning. 

**To Reproduce**
1. Run the following to install kubecost 
`helm install --set kubecostProductConfigs.createServiceKeySecret=true,kubecostProductConfigs.awsServiceKeyName=dummy --namespace kubecost-test kubecost/cost-analyzer `
2. wait for cost analyzer to come up and view the logs from the cost-model container you will see 
`
I0807 16:30:54.889994       1 provider.go:275] Found ProviderID starting with "aws", using AWS Provider
I0807 16:30:54.893331       1 router.go:1020] ERROR UPDATING pricing-configs CONFIG: No such field: AwsServiceKeyName in obj`

**Expected behavior**
cost-model should properly configure itself without errors.

I did a bit of digging and it looks like the aws provider in cost model is looking for ServiceKeyName not AwsServiceKeyName. As a test I edited the config map to change the property name here https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-pricing-configmap.yaml#L83 to match what the aws provider class was expecting and it seemed to come up ok. Not sure if that's the fix or if you want to fix it in cost-model itself.

**Comment by AjayTripathy** [comment]
@KealanM -- thanks again. We just need to remove that field from the configmap, actually-- we're migrating to not supplying the sensitive data in the configmap at all. https://github.com/kubecost/cost-analyzer-helm-chart/pull/579 should do this. After that, awsServiceKeyName should only be used here: https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/aws-service-key-secret.yaml#L12

The way this is supposed to work is: you use an existing secret or embed values in helm template. Then that gets picked up here in the code: https://github.com/kubecost/cost-model/blob/a9674a4b7f034dbe547d90d427b58c8f65914624/pkg/cloud/awsprovider.go#L111 . I'll test https://github.com/kubecost/cost-analyzer-helm-chart/pull/579 and https://github.com/kubecost/cost-analyzer-helm-chart/pull/578 to make sure this is working, and merge to develop when that's done. We're doing a patch release on Tuesday morning PST and this will make it in.

**Comment by AjayTripathy** [comment]
@KealanM this should be fixed, let me know if you're still experiencing issues.
