### ISSUE TITLE
Kubecost token and product key should be set via a secret name - not as a plain text value

### ISSUE THREAD

**Issue by michaelajr** [kubecost/cost-analyzer-helm-chart#582]
We use argocd to install our charts - and I would rather not pass these in the clear. Would be nice to be able to use them from a secret.

**Comment by michaelajr** [comment]
If we can mount the secret as ENV vars - can the vars be referenced from the CM?

**Comment by dwbrown2** [comment]
Hey @michaelajr, sorry for not getting back last week. Now that you have a product key you no longer need to worry about the token, so you can drop that from your install. 

Happy to look at supporting something more for your product key. Would you ideally want to use an existing secret?  We don't currently read product key out of an env variable, though-- we manually read it out of the supplied configmap and into a file on our end, so there's no way for you to easily implement this yourself. 

To help understand prioritization, is this blocking anything on your end today? We expect we should be able to support something here by next release. Also, just as an FYI, this key and your data isn't egressed anywhere, so it being compromised would not pose risk to data leaking.

**Comment by michaelajr** [comment]
Moving this to Slack

**Comment by dwbrown2** [comment]
This feature was added ~6 months ago to Kubecost. Here's the [values link](https://github.com/kubecost/cost-analyzer-helm-chart/blob/02cf3c10bcda604fcf0c31eb0903dc810b07ec60/cost-analyzer/values.yaml#L660). Please let me know if we can get you anything else at this point, Michael! 

cc @kirbsauce
