### ISSUE TITLE
filename typo: cost-analyzer-helm-chart-develop/cost-analyzer/templates/cost-analyzer-cluser-role-template.yaml

### ISSUE THREAD

**Issue by admun** [kubecost/cost-analyzer-helm-chart#584]
**Describe the bug**

as title, the file should probably be named cost-analyzer-cluster-role-template.yaml

**Comment by kirbsauce** [comment]
fixed in commit 3aec326900976d8e8b5071763e1cb9ebb3f278ee

thanks @admun !!!
