### ISSUE TITLE
Move PriorityClass out of v1beta1

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#589]
PriorityClass is out of v1beta1 in k8s 1.17. To support this, we should migrate it to v1-- but doing this may break PriorityClass in older versions. We should migrate and maintain backwards compatibility.

**Comment by dwbrown2** [comment]
@AjayTripathy we created this for startup prioritization purposes. Does these same reasons still exist?

**Comment by dwbrown2** [comment]
@mbolt35 @AjayTripathy this looks done with #591... is that correct?

**Comment by AjayTripathy** [comment]
Yep! Closing.
