### ISSUE TITLE
Improve persistence customization

### ISSUE THREAD

**Issue by sebastien-prudhomme** [kubecost/cost-analyzer-helm-chart#59]
Hi,

A good practice in Helm chart for persistence is to enable user to customize it further:

- `storageClass` for people having multiple storage backends
- `annotations` for instance for people using backup solutions that rely on volume annotations
- `accessModes`
- also using a preexisting volume claim is often possible in a lot of charts

So i created this issue to talk about that :-)

**Comment by dwbrown2** [comment]
Good idea! No concerns here for any of these configuration options. How about you @AjayTripathy?

**Comment by AjayTripathy** [comment]
This looks like a great idea to me-- @sebastien-prudhomme would you like to look at this? :)

**Comment by dwbrown2** [comment]
I know `storageClass` is now supported. Anything else outstanding here?

**Comment by dwbrown2** [comment]
We now support ability to use an existing claim! I believe `annotation` and `accessModes` remain outstanding.

**Comment by dwbrown2** [comment]
This should largely be done now, so I'm going to close. There may be one or two other minor storage options but we haven't had any other requests. Please feel free to re-open or open a new ticket if there are other needs!

cc @kirbsauce
