### ISSUE TITLE
PSP API version causing errors in recent builds

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#590]
A report from Manuel after he tried to enable PodSecurityPolicy in the chart but got an error related with the apiVersion extensions/v1beta1. This apiVersion have been removed in k8s 1.16+

We just want to be careful about backwards compatibility.

**Comment by dwbrown2** [comment]
@mbolt35 this now complete?

**Comment by AjayTripathy** [comment]
This should work now, yeah.
