### ISSUE TITLE
Aggregate allocation on multiple labels

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#598]
Today the /allocation API supports aggregating data by multiple breakdowns, e.g. get data by both namespace and label. We have a user that really needs to break data down by two different labels, e.g. `app` & `environment`. 

Open questions:
* Do we need to expose this in /aggregatedCostModel as well? I don't see it as a hard requirement
* What will `name` field look like in response? Something like `app=cost-analyzer;environment=prod`?

Example request:
```
/allocation=label:project,label:run_id
```

**Comment by dwbrown2** [comment]
@nikovacevic any guidance here for calvin?!

**Comment by nikovacevic** [comment]
Sup @itscalvinwang a few starting ideas here:
- The function to look at here will be `func (as *AllocationSet) AggregateBy` on [line 314 of pkg/kubecost/allocation.go](https://github.com/kubecost/kubecost-cost-model/blob/develop/pkg/kubecost/allocation.go#L314)
- We already support multi-aggregation via the `generateKey` function [here](https://github.com/kubecost/kubecost-cost-model/blob/7c16042b10b13dd1bb28a43697e4f84144125a38/pkg/kubecost/allocation.go#L673) and you should find a helpful TO DO there.

Regarding @dwbrown2's questions, my feedback is:
- I don't think we need this in AggregatedCostModel API, unless users really demand it. Sounds messy from the standpoint of syntax and complexity in the API adapter. If users need this, they can use the Allocation API.
- Today, for `aggregate=label:app`, we get names like `"app=cost-analyzer"`, so making it comma- or semicolon-delimited sounds right to me. Either way.

I propose requests should look like this: http://demo.kubecost.io/model/allocation?window=today&aggregate=label:project,label:app

Hit me up directly with any questions!

**Comment by itscalvinwang** [comment]
https://github.com/kubecost/kubecost-cost-model/pull/215
https://github.com/kubecost/kubecost-cost-model/pull/217
