### ISSUE TITLE
Current release not installable due to missing images

### ISSUE THREAD

**Issue by dennisjac** [kubecost/cost-analyzer-helm-chart#599]
Hi,
I just tried to install the current release via helm3 but it seems the necessary images are not available. The installation of the chart seems to run fine but the container doesn't start because it cannot find the image `ajaytripathy/kubecost-cost-model:prod-1.64.0`. Looking at docker-hub the latest version available there seems to be `prod-1.51.2`.

**Comment by dwbrown2** [comment]
Hi @dennisjac! This image (and others in the project) are now moved to a GCR image repo. This one can now be found at `gcr.io/kubecost1/cost-model`

This value is configurable in values.yaml here: https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L94 

Let me know if this helps and if you have any issues using this new repo!

**Comment by dennisjac** [comment]
Apparently I was using an outdated values file which overrode the image sources. Getting this up-to-date fixed things, sorry!

**Comment by dwbrown2** [comment]
All good, glad that helped! Let me know if we can share input anywhere else.
