### ISSUE TITLE
Allow setting labels/annotations on deployed objects, especially Deployments/Services

### ISSUE THREAD

**Issue by llamahunter** [kubecost/cost-analyzer-helm-chart#610]
**What problem are you trying to solve?**
Ownership tracking of kubecost itself

**Describe the solution you'd like**
Allow setting labels and annotations on helm chart deployed objects

**Describe alternatives you've considered**
Possibly there's an undocumented kubecostDeployment.labels variable?  It seems to just apply to the costanalyzer, tho.

**How would users interact with this feature?**
Set additional, optional variables to set labels/annotations on objects for external ownership tracking by other tools.

**Comment by dwbrown2** [comment]
Hey @llamahunter! Thanks for this request. Any more insight into your target use case and what specific pods/resources you want these applied to? We have this option for settings annotations:

https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/values.yaml#L29
https://github.com/kubecost/cost-analyzer-helm-chart/blob/966468bfb98a36be7b8633b04a18455bdd9c443b/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L21-L23

Also, Prometheus and other subcharts currently support passing `podLabels` and `deploymentAnnotations` .

**Comment by llamahunter** [comment]
I'd like to be able to put the labels and annotations on the Deployment.  We have a mutating admission webhook that copies the list of our custom 'ownership tracking' labels and annotations down to various subobjects, eventually to pods.  Rather than having people have to tag stuff deep in the pod spec in a pod template in a job spec of a CronJob, for instance, they just set stuff on the CronJob, and the tags make their way to the right places.

*one* of the reasons for copying tags down is so that something like kubecost can report on their cost.  We use them for other reasons, too, tho.  We are determining if we will use kubecost or something else for cost tracking, so being able to tell kube cost to label its own resources appropriately to track costs would be nice.

**Comment by dwbrown2** [comment]
Yep, makes total sense. Thanks so sharing. It looks like the links above give you what you need for annotations. We just want to add support for custom labels. Does that sound right to you?

**Comment by llamahunter** [comment]
If there were a `.Values.global.podLabels` that let me set various tracking labels on pods created by the helm chart, that would be good. Also need to set labels on Service objects, tho, for ownership tracking, since they consume resources, too.

**Comment by dwbrown2** [comment]
Thanks, Richard! You can complete this with Prometheus, Alertmanager, etc in our chart today. I like the idea of adding to other pods as well.

**Comment by llamahunter** [comment]
Any chance kubecost will get this feature soon?  Seems desirable/obvious to be able to track kubecost resource usage with kubecost.

**Comment by AjayTripathy** [comment]
Hi @llamahunter  -- this makes sense to me and we expect to have this in the next release. I think a quick way we could do this is add a global label that then gets turned into a commonLabel: https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/_helpers.tpl#L101 .

**Comment by AjayTripathy** [comment]
However, that being said, currently only namespace labels make their way down to pods in our cost aggregations. Is the feature request on the cost allocation side to have label aggregations take into account controller labels as well?

**Comment by llamahunter** [comment]
any chance that custom labels and annotations will be coming soon?  we're waiting on this. Want to be able to apply kubecost to itself.

**Comment by AjayTripathy** [comment]
Hi @llamahunter sorry this did not get updated-- does setting .Values.kubecostDeployment.labels this with custom deployment labels work for you? https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L9

**Comment by dwbrown2** [comment]
@llamahunter let us know if this looks good to you, because I believe this should be supported.

**Comment by dwbrown2** [comment]
Closing because this is now supported, please re-open if you have any questions!
