### ISSUE TITLE
Network costs container create error

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#615]
A new user is hitting this on their OpenShift cluster:

```
Error: container create failed: time="2020-09-19T13:44:36Z" level=warning msg="exit status 1" time="2020-09-19T13:44:36Z" level=error msg="container_linux.go:348: starting container process caused \"process_linux.go:438: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/proc/1681/net\\\\\\\" to rootfs \\\\\\\"/var/lib/containers/storage/overlay/aeab41b275325f1b358db0a2f2a631e76ae2a182193d4ae55faff43c3c2cced2/merged\\\\\\\" at \\\\\\\"/var/lib/containers/storage/overlay/aeab41b275325f1b358db0a2f2a631e76ae2a182193d4ae55faff43c3c2cced2/merged/net\\\\\\\" caused \\\\\\\"permission denied\\\\\\\"\\\"\"" container_linux.go:348: starting container process caused "process_linux.go:438: container init caused \"rootfs_linux.go:58: mounting \\\"/proc/1681/net\\\" to rootfs \\\"/var/lib/containers/storage/overlay
```

**Comment by dwbrown2** [comment]
So by default we mount to `/proc` and it looks like that is failing for some reason. We've seen a past docker bug that was solved by using another mount/host path. Here's how you can pass different values in our helm chart: 

```
networkCosts:
  hostProc:
    hostPath: /proc
    mountPath: /host-proc
```

**Comment by dwbrown2** [comment]
@mbolt35 update from team is that it looks like OpenShift is blocking the mount. They've reached out to Red Hat.

**Comment by henry-zektser-vineti** [comment]
My manual fix: 
```
      command:
        - /bin/sh
      args:
        - '-c'
        - >-
          ln -s /hostproc/net /net && ln -s /hostproc/sys/net/netfilter
          /netfilter && /go/bin/app
```

Per redhat: host mounting / or /proc is fine, it just can't seem to mount subdirectories of /proc..

**Comment by mbolt35** [comment]
Ok, if you are able to mount `/proc`, then we do have a solution in place: [The hostProc value](https://github.com/kubecost/cost-analyzer-helm-chart/blob/0b4287bb090155020c52b08e5c09836353b6a390/cost-analyzer/templates/cost-analyzer-network-costs-template.yaml#L80-L84)

So, in your values:
```yaml
networkCosts:
  enabled: true
  image: gcr.io/kubecost1/kubecost-network-costs:v13.6
  ...
  hostProc:
    hostPath: /proc
    mountPath: /host-proc
```

`hostPath` just targets the node's `/proc` directory, and generally, you'll want to use a different mount path name. The mount path will be used to mount to volume and also point the network-costs pod to the right location.

**Comment by kirbsauce** [comment]
@dwbrown2 , ok to close this out?

**Comment by dwbrown2** [comment]
Yep, this should be addressed. cc @mbolt35 unless he knows otherwise.
