### ISSUE TITLE
Sample TLS config for prometheus.

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#62]
See: https://github.com/kubecost/cost-model/issues/77

Some deployments require auth for intra-app communication, we should provide an example of how to do this.

**Comment by dwbrown2** [comment]
Marking as out of scope for now... to be revisited.

**Comment by dwbrown2** [comment]
This should now be complete. @AjayTripathy please reopen if I'm mistaken.

**Comment by AjayTripathy** [comment]
Yes, this is complete.
