### ISSUE TITLE
Possible to run behind Traefik when hosted under subpath?

### ISSUE THREAD

**Issue by aodj** [kubecost/cost-analyzer-helm-chart#636]
**What problem are you trying to solve?**
I'm running Traefik with a number of admin websites hosted under subpaths similar to `example.com/prometheus`, `example.com/grafana`, etc and want to expose kubecost in the same manner.

**Describe the solution you'd like**
The nginx config to support non-root paths.

**Describe alternatives you've considered**
Using Traefik to route to the service is straight forward, but when the host is `example.com/kubecost` the nginx frontend containers receive requests for a path of `/kubecost` rather than the expected `/`:

```
2020/10/07 11:23:48 [error] 21#21: *307 open() "/var/www/kubecost" failed (2: No such file or directory), client: 172.16.1.68, server: _, request: "GET /kubecost HTTP/1.1", host: "example.com"
```

Trafik can also strip prefixes off incoming requests, to allow the nginx pod to accept the incoming requests on the `/` path, however the responses to load various assets such as css or js, doensn't include the desired subpath. This is mentioned in the [Traefik docs](https://doc.traefik.io/traefik/middlewares/stripprefix/#prefixes): 

> If your backend is serving assets (e.g., images or Javascript files), chances are it must return properly constructed relative URLs.
Continuing on the example, the backend should return /products/shoes/image.png (and not /images.png which Traefik would likely not be able to associate with the same backend). 

**How would users interact with this feature?**
They would specify the expected subpath in the values.yaml

**Additional Info**
I filed an identical ticket for the [cloudhut/Kowl](https://github.com/cloudhut/kowl/issues/107) project which includes some discussion of how other software such as Grafana, handles this ([link](https://github.com/cloudhut/kowl/issues/107#issuecomment-672334399)).

**Comment by AjayTripathy** [comment]
Hi @aodj , curious if this nginx ingress example helps answer the question: https://github.com/kubecost/docs/blob/master/ingress-examples.md#non-root-path-example

I've not personally run kubecost at a non-root path behind Traefik, but I believe that stripping the prefixes should be sufficient here, as that is what we have done for running at nonroot paths via nginx.

**Comment by aodj** [comment]
I'll take a look, thanks.

**Comment by dwbrown2** [comment]
@aodj have any outstanding questions here?

**Comment by dwbrown2** [comment]
I'm going to close because this should be supported. Please re-open if you have any questions!
