### ISSUE TITLE
cost-analyzer healthy error

### ISSUE THREAD

**Issue by nbet** [kubecost/cost-analyzer-helm-chart#664]
**Describe the bug**
when installing Kubecost, cost-analyzer is running but healthy check failed

**To Reproduce**
3. See error
liulangshaoniandeMacBook-Pro:cost-analyzer fangpeng$ kubectl -n kubecost get po
NAME                                                READY   STATUS      RESTARTS   AGE
cost-analyzer-checks-1604478600-tbltz               0/1     Completed   0          29m
cost-analyzer-checks-1604479200-mw8c8               0/1     Completed   0          19m
cost-analyzer-checks-1604479800-m7jwh               0/1     Completed   0          8m58s
kubecost-cost-analyzer-59c746fdc8-fsg6c             0/3     Running     0          40m
kubecost-grafana-8499cb5f8d-8jzsk                   3/3     Running     0          5h4m
kubecost-kube-state-metrics-69786f4c8-znpwj         1/1     Running     0          5h4m
kubecost-prometheus-alertmanager-7bbb84c7f5-2g5t9   2/2     Running     0          5h4m
kubecost-prometheus-node-exporter-58ldr             1/1     Running     0          4h56m
kubecost-prometheus-node-exporter-lgdtp             1/1     Running     0          4h56m
kubecost-prometheus-node-exporter-pskqt             1/1     Running     0          4h56m
kubecost-prometheus-server-8945f94c-85tv8           2/2     Running     0          5h4m

**Expected behavior**

**Screenshots**

**Collect logs (please complete the following information):**

 - Run `helm ls` and paste the output here:
liulangshaoniandeMacBook-Pro:cost-analyzer fangpeng$ helm ls | grep kubecost
kubecost                            	8       	Wed Nov  4 15:45:09 2020	DEPLOYED	cost-analyzer-1.62.0                                        	kubecost 

 - If the pod is stuck in init, run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-init` and paste output here:

 - If a page is broken or not loading, open your javascript developer console and paste the ouput here:

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-server` and paste the output here:
liulangshaoniandeMacBook-Pro:cost-analyzer fangpeng$ kubectl -n kubecost logs kubecost-cost-analyzer-59c746fdc8-fsg6c -c cost-analyzer-server
2020/11/04 08:19:20 Thanos is disabled for the API endpoints.
time="2020-11-04T08:19:20Z" level=info msg="start event store..." source="store.go:111"
2020/11/04 08:19:20 Server is ready. 

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-model` and paste the output here:
liulangshaoniandeMacBook-Pro:cost-analyzer fangpeng$ kubectl -n kubecost logs kubecost-cost-analyzer-59c746fdc8-fsg6c 
error: a container name must be specified for pod kubecost-cost-analyzer-59c746fdc8-fsg6c, choose one of: [cost-model cost-analyzer-frontend cost-analyzer-server] or one of the init containers: [config-db-perms-fix]
liulangshaoniandeMacBook-Pro:cost-analyzer fangpeng$ kubectl -n kubecost logs kubecost-cost-analyzer-59c746fdc8-fsg6c -c cost-model
I1104 08:19:12.735100       1 router.go:940] Starting cost-model (git commit "")
I1104 08:19:12.737404       1 router.go:992] Success: retrieved the 'up' query against prometheus at: http://kubecost-prometheus-server.kubecost
I1104 08:19:12.738151       1 clustercache.go:92] NAMESPACE: kubecost
I1104 08:19:12.738322       1 reflector.go:122] Starting reflector *v1.DaemonSet (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.738762       1 reflector.go:160] Listing and watching *v1.DaemonSet from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.738356       1 reflector.go:122] Starting reflector *v1.Node (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.738789       1 reflector.go:160] Listing and watching *v1.Node from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.738801       1 reflector.go:122] Starting reflector *v1.Service (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.738829       1 reflector.go:160] Listing and watching *v1.Service from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.738800       1 reflector.go:122] Starting reflector *v1.Deployment (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.738843       1 reflector.go:160] Listing and watching *v1.Deployment from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.738905       1 reflector.go:122] Starting reflector *v1.Pod (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.738924       1 reflector.go:160] Listing and watching *v1.Pod from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.738916       1 reflector.go:122] Starting reflector *v1.ReplicaSet (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.739120       1 reflector.go:122] Starting reflector *v1.Namespace (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.739138       1 reflector.go:122] Starting reflector *v1.StatefulSet (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.739152       1 reflector.go:160] Listing and watching *v1.ReplicaSet from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.739154       1 reflector.go:160] Listing and watching *v1.Namespace from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.739156       1 reflector.go:160] Listing and watching *v1.StatefulSet from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.739124       1 reflector.go:122] Starting reflector *v1.ConfigMap (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.739240       1 reflector.go:122] Starting reflector *v1.PersistentVolume (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.739256       1 reflector.go:160] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.739261       1 reflector.go:160] Listing and watching *v1.PersistentVolume from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.739772       1 reflector.go:122] Starting reflector *v1.StorageClass (0s) from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.739784       1 reflector.go:160] Listing and watching *v1.StorageClass from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
I1104 08:19:12.838907       1 watchcontroller.go:195] Starting *v1.Pod controller
I1104 08:19:12.838924       1 watchcontroller.go:195] Starting *v1.Service controller
I1104 08:19:12.838923       1 watchcontroller.go:195] Starting *v1.StatefulSet controller
I1104 08:19:12.838937       1 watchcontroller.go:195] Starting *v1.Deployment controller
I1104 08:19:12.838947       1 watchcontroller.go:195] Starting *v1.ReplicaSet controller
I1104 08:19:12.838959       1 watchcontroller.go:195] Starting *v1.PersistentVolume controller
I1104 08:19:12.838967       1 watchcontroller.go:195] Starting *v1.Namespace controller
I1104 08:19:12.838977       1 watchcontroller.go:195] Starting *v1.Node controller
I1104 08:19:12.838911       1 watchcontroller.go:195] Starting *v1.DaemonSet controller
I1104 08:19:12.838994       1 watchcontroller.go:195] Starting *v1.ConfigMap controller
I1104 08:19:12.838994       1 watchcontroller.go:195] Starting *v1.StorageClass controller
I1104 08:19:12.839743       1 provider.go:275] Found ProviderID starting with "aws", using AWS Provider
I1104 08:19:12.844650       1 router.go:1036] No pricing-configs configmap found at installtime, using existing configs: configmaps "pricing-configs" not found
I1104 08:19:12.848961       1 router.go:1044] No app-configs configmap found at installtime, using existing configs: configmaps "app-configs" not found
I1104 08:19:12.853002       1 router.go:1044] No product-configs configmap found at installtime, using existing configs: configmaps "product-configs" not found
I1104 08:19:12.853449       1 awsprovider.go:601] starting download of "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.json", which is quite large ...
I1104 08:19:14.235602       1 awsprovider.go:607] Finished downloading "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.json"
W1104 08:28:16.771835       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.ConfigMap ended with: too old resource version: 38827441 (38828780)
I1104 08:28:17.771949       1 reflector.go:160] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
W1104 08:34:33.788176       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.ConfigMap ended with: too old resource version: 38829061 (38829942)
I1104 08:34:34.788294       1 reflector.go:160] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
W1104 08:42:58.805480       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.ConfigMap ended with: too old resource version: 38830202 (38831325)
I1104 08:42:59.805559       1 reflector.go:160] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
W1104 08:48:26.822247       1 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *v1.ConfigMap ended with: too old resource version: 38831699 (38832308)
I1104 08:48:27.822367       1 reflector.go:160] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-frontend` and paste the output here:
liulangshaoniandeMacBook-Pro:cost-analyzer fangpeng$ kubectl -n kubecost logs kubecost-cost-analyzer-59c746fdc8-fsg6c -c cost-analyzer-frontend
2020/11/04 08:19:20 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2

**Comment by dwbrown2** [comment]
@AjayTripathy mind reviewing this?

**Comment by AjayTripathy** [comment]
Hi @nbet , based on the lack of errors in the logs I suspect this is just pricing data being slow to download. We will have a PR merged shortly to only download regional pricing on startup, https://github.com/kubecost/cost-model/pull/593 . That should speed up the pod startup time for you.

**Comment by ChuckkNorris** [comment]
Not sure if it's related, but I'm also getting an error when following the Helm v3 instructions to install Kubecost in a cluster.
```
chucknorris@lfuller-5520:~$ kubectl get pods -n kubecost
NAME                                               READY   STATUS      RESTARTS   AGE
cost-analyzer-checks-1610133600-t7x7h              0/1     Completed   0          5m51s
kubecost-cost-analyzer-6b65d676d-gsbkv             3/3     Running     0          5m56s
kubecost-grafana-558fcb4788-2h6j2                  3/3     Running     0          5m56s
kubecost-kube-state-metrics-88d684f5d-ssk5g        1/1     Running     0          5m56s
kubecost-prometheus-alertmanager-f9cff5795-wzws5   2/2     Running     0          5m56s
kubecost-prometheus-node-exporter-6bz2j            1/1     Running     0          5m56s
kubecost-prometheus-node-exporter-h7xr7            1/1     Running     0          5m56s
kubecost-prometheus-server-7bf5654977-n89kv        2/2     Running     0          5m56s

chucknorris@lfuller-5520:~$ kubectl logs -n kubecost cost-analyzer-checks-1610133600-t7x7h
Starting...
Error: Error: connect ECONNREFUSED 10.0.54.50:9003
    at Object.dispatchError (/node/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:60:19)
    at Request.<anonymous> (/node/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:674:20)
    at Request.emit (events.js:326:22)
    at Request.onRequestError (/node/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:314:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) undefined
```

**Comment by AjayTripathy** [comment]
Hi @ChuckkNorris I suspect that this is also due to the checks pod running before the cost-analyzer pod is ready. Note the ages here: 
```
cost-analyzer-checks-1610133600-t7x7h              0/1     Completed   0          5m51s
kubecost-cost-analyzer-6b65d676d-gsbkv             3/3     Running     0          5m56s
```

The checks pod likely ran before kubecost-cost-analyzer. This isn't a major concern, as this pod just runs our alerts.

**Comment by dwbrown2** [comment]
@ChuckkNorris I just wanted to follow up to see if this issue is persistent or causing any loss of functionality. Let me know if we can get you anything.

**Comment by kirbsauce** [comment]
Hi @nbet and @ChuckkNorris.  Just wanted to let you know I'm going to close this issue, but if there is lingering concerns, don't hesitate to reopen it!
