### ISSUE TITLE
Please add support for imagePullSecrets K8s feature

### ISSUE THREAD

**Issue by esteban1983cl** [kubecost/cost-analyzer-helm-chart#668]
**What problem are you trying to solve?**
I need pull images using imagePullSecret kubernetes feature

**Describe the solution you'd like**
Due docker increase pull limits errors, sometimes my pods can't work

**Describe alternatives you've considered**
Add imagePullSecrets in chart template files

**How would users interact with this feature?**
Updating values.yaml file

**Comment by dwbrown2** [comment]
Thanks for this request, Esteban! What containers do you need this for? 

It should be supported for Prometheus, kube-state-metrics, and other deps. Here are current references: https://github.com/kubecost/cost-analyzer-helm-chart/search?q=imagePullSecrets%3A

**Comment by esteban1983cl** [comment]
HI @dwbrown2 I need support for kubecost containers, not prometheus, for example I have the follow containers

gcr.io/kubecost1/checks:prod-1.53.2
gcr.io/kubecost1/frontend:prod-1.53.2
gcr.io/kubecost1/server:prod-1.53.2
gcr.io/kubecost1/cost-model:prod-1.53.2

Thanks

**Comment by dwbrown2** [comment]
@esteban1983cl happy to look at this with you. Also, we'd welcome a contribution if you are interested.

**Comment by dwbrown2** [comment]
@itscalvinwang I believe this is now supported, correct?

Any chance you can add a PR #? 

Also, @esteban1983cl let us know if there's anything else we can get you!

**Comment by dwbrown2** [comment]
My apologies, I see https://github.com/kubecost/cost-analyzer-helm-chart/issues/668 referenced.

Esteban, let us know if this meet yours needs!
