### ISSUE TITLE
Cost savings calculator recommends incompatible instances

### ISSUE THREAD

**Issue by treyhyde** [kubecost/cost-analyzer-helm-chart#673]
**Describe the bug**

The cluster-sizing / savings utility recommends A1 instances (ARM) even though none of my workloads support that architecture.

**To Reproduce**

1) Have x86-64 workloads
2) Click "savings"
3) Behold, arm64 recommendation

**Expected behavior**

Recommendations for x86-64 architectures

**Screenshots**

<img width="885" alt="Screen Shot 2020-11-10 at 5 25 10 PM" src="https://user-images.githubusercontent.com/62077/98753685-c18a1880-2379-11eb-9e4e-4a9eae4455e9.png">

**Comment by dwbrown2** [comment]
Thanks for reporting, @treyhyde! We're going to investigate just after Kubecon. 

We've talked to several teams that want to see the cost difference between x86 and arm and therefore we are considering the options to filter by chipset architecture. Would that be useful in your case? 

cc @nikovacevic

**Comment by treyhyde** [comment]
I'm very curious about utilizing ARM.  An architectural shift is a pretty different exercise than an instance sizing and capacity one.  Two different use cases, two different UIs.   If ARM is a recommendation, it would need to look at all my images to see if there are alternative arch available.   In this case, seeing that istio and knative are the foundation of this cluster, an analyzer should know it's not worth the conversation until "upstream" supports this arch.   Also, in this case, we are only a month in to "official" support for ARM on EKS.  Gap analysis (effort) vs benefit.

**Comment by dwbrown2** [comment]
@treyhyde you should now be able to filter by chipset type in recent versions! let me know if we can get you anything else.

**Comment by treyhyde** [comment]
> @treyhyde you should now be able to filter by chipset type in recent versions! let me know if we can get you anything else.

Thanks.  That works.   Unfortunately, with the latest kubecost, all the recommendations reduce resiliency and (by kubecost's estimation) cost significantly more than my current config.

**Comment by dwbrown2** [comment]
@treyhyde can you share more about what mean by "reduce resiliency"?

**Comment by treyhyde** [comment]
Suggesting 2 instances at a higher cost rather than say 10 instances with a total cost significantly lower.   A failure would cut 50% capacity in the former but only 10% in the latter.

**Comment by treyhyde** [comment]
<img width="844" alt="Screen Shot 2021-03-24 at 11 59 12 AM" src="https://user-images.githubusercontent.com/62077/112368524-69084780-8c98-11eb-8c2f-45c258e105ad.png">

**Comment by dwbrown2** [comment]
Just curious, what's the context for this environment, e.g. dev, prod, etc? And are you under-provisioned today, e.g. at risk of CPU throttling?
