### ISSUE TITLE
Question - How to use external Grafana?

### ISSUE THREAD

**Issue by vikas027** [kubecost/cost-analyzer-helm-chart#681]
There is an option to use an external Prometheus in `README.md` but I can't find an option to use an external Grafana?

**Comment by dwbrown2** [comment]
Hi @vikas027, this resource should give you what you need! Let me know if you have questions.

https://github.com/kubecost/docs/blob/master/custom-prom.md#custom-grafana

**Comment by vikas027** [comment]
Thanks, @dwbrown2  . Let me try it out, I will raise an issue if required.
