### ISSUE TITLE
Query timeout after upgrade

### ISSUE THREAD

**Issue by Zenmodai** [kubecost/cost-analyzer-helm-chart#683]
**Describe the bug**
After upgrading Kubecost from v1.66.0 to v1.69.0, we are seeing query timeouts, when opening the Health section in the kubecost dashboard. The two options, which are stuck loading are:
- Network issues detected
- Daily cluster costs increased 10% or more

In the browser console, you can see the Prometheus queries are stuck pending or abort with a timeout.

We are using an external Prometheus and have the persistent storage deactivated, since we are setting all configuration with the helm deployment.

**To Reproduce**
1. Upgrade the version, while the persistent storage is deactivated ?
2. Open the health menu in the kubecost dashboard.

**Expected behavior**
The Prometheus queries should work the same way as before the upgrade. Nothing was changed, only the version was upgraded.

**Collect logs (please complete the following information):**
In the pod logs from the cost-model container, you can see the query timeout messages:
`I1123 10:40:52.846624       1 router.go:274] Error returned to client: 'query timed out in expression evaluation' parsing query '
		sum(rate(node_cpu_seconds_total[48h])) by (cluster_id, mode) / ignoring(mode)
		group_left sum(rate(node_cpu_seconds_total[48h])) by (cluster_id)
	'
I1123 10:41:04.665865       1 router.go:274] Error returned to client: 'query timed out in expression evaluation' parsing query '
		sum(rate(node_cpu_seconds_total[48h])) by (cluster_id, mode) / ignoring(mode)
		group_left sum(rate(node_cpu_seconds_total[48h])) by (cluster_id)`

There is also another error message, but I am not sure, if this is connected or not:
`I1123 10:34:10.247630       1 log.go:32] [Warning] Allocation ETL: Save error: Allocation ETL: error creating file '/var/configs/db/etl/v3/allocations/1606089600-1606176000': open /var/configs/db/etl/v3/allocations/1606089600-1606176000: no such file or directory`

**Comment by dwbrown2** [comment]
@Zenmodai thanks for the report. I'm surprised to see, as there are no recent changes to these health checks.

Would you be able to send us a [bug report](http://docs.kubecost.com/bug-report) to team@kubecost.com?

Also, cc'ing @nikovacevic in regards to the ETL save error.

**Comment by Zenmodai** [comment]
After creating the bug report, I checked the exported prometheus logs, it seems to be a problem with our prometheus instance:

`level=error ts=2020-11-24T12:00:48.022Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:361: Failed to list *v1.Endpoints: Get \"https://10.255.0.1:443/api/v1/namespaces/dev-team-a/endpoints?limit=500&resourceVersion=0\": dial tcp 10.255.0.1:443: connect: connection refused"
level=error ts=2020-11-24T12:00:48.022Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:362: Failed to list *v1.Service: Get \"https://10.255.0.1:443/api/v1/namespaces/dev-team-b/services?limit=500&resourceVersion=0\": dial tcp 10.255.0.1:443: connect: connection refused"
level=error ts=2020-11-24T12:00:48.022Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:363: Failed to list *v1.Pod: Get \"https://10.255.0.1:443/api/v1/namespaces/dev-team-c/pods?limit=500&resourceVersion=0\": dial tcp 10.255.0.1:443: connect: connection refused"`

Those error messages reapeat themselves in different variants for all our namespaces. So it is not related to the kubecost upgrade. I verified it with the older v1.66.0 version, the problem is the same here. The two prometheus queries kubecost runs just seems to trigger the problem/errors. 

The only thing worth mentioning seems to be the ETL warning/error log messages, as I mentioned before. The next log message is from the time the prometheus queries run in the timeout, because of our prometheus problems:

`log.go:47] [Info] Allocation ETL: Query [2020-11-22T11:59:35+0000, 2020-11-24T11:59:35+0000)
I1124 11:59:35.127885       1 log.go:47] [Info] Allocation ETL: Query [2020-11-22T11:59:35+0000, 2020-11-24T11:59:35+0000)
I1124 11:59:35.133336       1 log.go:32] [Warning] Asset ETL: Disk.Minutes exceeds window: 1441.00 > 1440.00
I1124 11:59:35.133348       1 log.go:32] [Warning] Asset ETL: Disk.Minutes exceeds window: 1441.00 > 1440.00
I1124 11:59:35.155877       1 log.go:62] [Profiler] 29.222241ms: Allocation ETL: adapter: 2.0d
I1124 11:59:35.159744       1 log.go:62] [Profiler] 31.943203ms: Allocation ETL: adapter: 2.0d`

The other on from before: 
`I1123 10:34:10.247630 1 log.go:32] [Warning] Allocation ETL: Save error: Allocation ETL: error creating file '/var/configs/db/etl/v3/allocations/1606089600-1606176000': open /var/configs/db/etl/v3/allocations/1606089600-1606176000: no such file or directory`

So if you think the ETL log messages are not that important/can be disregarded, then I guess we can close this bug. As this is a problem with our prometheus.

**Comment by dwbrown2** [comment]
@nikovacevic or @AjayTripathy do you mind commenting on this ETL message? I don't believe this message is worrisome but just want to double check.

**Comment by AjayTripathy** [comment]
this does mean that the ETL could not save to disk-- but this should be removed and was likely from a time where our ETL filepath varied depending on which PV you were using. Later versions should not have this.
