### ISSUE TITLE
Customizing cluster cpu request alarm threshold

### ISSUE THREAD

**Issue by Shivam9268** [kubecost/cost-analyzer-helm-chart#687]
**What problem are you trying to solve?**
We are constantly receiving notifications via slack hook from kubecost: ALERT:  :You are requesting 80.73% of your total cluster CPU.
We want to increase this alarm threshold to 90% or so. How can we do that.

**Describe the solution you'd like**
Any way to set the cluster cpu thresholds.

**Comment by dwbrown2** [comment]
@Shivam9268 thanks for this suggestion! Right now, this value in our product alerts is not configurable. I do think the threshold you propose does make sense though. 

Are there other values you want to customize/change? If so, you should be able to do this directly in Alertmanager with our metrics.

**Comment by dwbrown2** [comment]
Actually, @Shivam9268 it appears the current threshold for this alert is 90%. 

@AjayTripathy do you know why this would be firing before the alert threshold?

**Comment by Shivam9268** [comment]
Hi @dwbrown2, thanks for your response. Are there any updates for ways to customize these alerts?

**Comment by AjayTripathy** [comment]
Sorry for the late response. It may be possible that the alert is firing during the spike but by the time the alert is ready to send, it drops a bit. Any chance you have the history of the spike? You can look at CPU utilization % over time by running 
`SUM(kube_pod_container_resource_requests_cpu_cores) / SUM(kube_node_status_allocatable_cpu_cores) * 100` as a query range in prometheus

Regarding configurability, we're working on making our thresholds configurable from helm values-- we'll have an update here soon.

**Comment by Shivam9268** [comment]
Hi @AjayTripathy, thanks for reaching out. The above query during the time of the alert `You are requesting 80.14% of your total cluster CPU` gives this result:
![image](https://user-images.githubusercontent.com/22556869/102304277-188b9a80-3f83-11eb-8b29-5e662ac44cf4.png)
The peak usage during the time was 90%. It would be really awesome if we could tweak some of these thresholds or disable some alerts altogether.

**Comment by dwbrown2** [comment]
Hey @Shivam9268, thanks for this feedback! We'll increasingly add more and more configuration options in the future.  Leveraging AlertManager in the short-term is the recommended path for getting full control for these alerts and others!

**Comment by kirbsauce** [comment]
Hi @Shivam9268 , just wanted to check back with you on this issue.  While we are still interested in adding more options in the future, our recommendation remains leveraging AlertManager to resolve the issue.

Closing for now, but feel free to reopen the conversation if need be!
