### ISSUE TITLE
`ServiceMonitor` doesn't seem to work by default

### ISSUE THREAD

**Issue by dcherman** [kubecost/cost-analyzer-helm-chart#69]
Once the service monitor template is rendered, the selector includes an `app: cost-analyzer` label that is not included in the set of common labels, so it does not work out of the box.

https://github.com/kubecost/cost-analyzer-helm-chart/blob/004faa402e9e833c16fedf4f3b795b11f8e9b7ff/cost-analyzer/templates/_helpers.tpl#L46-L61

I've confirmed that either removing the selector from the ServiceMonitor or adding the label to the service fixes the problem.

**Comment by AjayTripathy** [comment]
Hi @dcherman thanks for this report. Looking into this now.

**Comment by AjayTripathy** [comment]
removing the selector label seems to create the following error:

Ajays-MacBook-Pro-2:cost-analyzer atripathy$ helm upgrade kubecost .
UPGRADE FAILED
Error: Deployment.apps "kubecost-cost-analyzer" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/instance":"kubecost", "app.kubernetes.io/name":"cost-analyzer"}: `selector` does not match template `labels`
Error: UPGRADE FAILED: Deployment.apps "kubecost-cost-analyzer" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/instance":"kubecost", "app.kubernetes.io/name":"cost-analyzer"}: `selector` does not match template `labels`

So I think the fix to maintain compatibility is to add the label to the service

**Comment by dcherman** [comment]
I'd agree with that with one caveat, and that's the key of the label should be configurable.  It looks like the original intent was to add the `app` field in order to identify kubecost resources for cost tracking, but the key used for `app` is configurable, so that opens the possibility that a user might need to change that depending on their needs; right now, it doesn't look like there is a way to add arbitrary labels to many of the resources created here.

From the docs:

> Note: In API version apps/v1, a Deployment’s label selector is immutable after it gets created.

So I'd agree that for backwards compatibility, we should probably add the label to the service, hopefully in addition to allowing the key of the label to be configurable.

Ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#label-selector-updates

**Comment by dwbrown2** [comment]
@AjayTripathy should have a basic fix for this in the 1.30 release, which is expected this weekend.

We haven't made the key for the label configurable yet. I propose we open a new issue for this, but let me know if you want to handle differently

**Comment by dcherman** [comment]
Yep, that sounds perfectly acceptable to me.  I'm not likely to change the label personally, however since the label key is configurable in kubecost, I figured it should be configurable in the chart.

**Comment by dwbrown2** [comment]
Cool, I just created #71. Please feel free to make additions. 

Will close this issue out, but we can re-open if there are other outstanding tasks here. Thanks again for reporting this!
