### ISSUE TITLE
support pull from different docker registry

### ISSUE THREAD

**Issue by hchhabada** [kubecost/cost-analyzer-helm-chart#693]
**What problem are you trying to solve?**

Due to the docker pull limit limitation, we host images in the local registry and pull from there.
kubecost does not support customization of adding different registry host and secrets

**Describe the solution you'd like**

1. Support for adding the different docker registry host, pass
```
global:
  repository:
    useSecret: false
    installSecret: true
    secretName: "registrysecret"
    host: "example.com"
    user:
    pass:
```

2. registry_secret.yaml in cost-analyzer templates
```
{{ if and .Values.global.repository.useSecret .Values.global.repository.installSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.repository.secretName }}
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.global.repository.host (printf "%s:%s" .Values.global.repository.user .Values.global.repository.pass | b64enc) | b64enc }}
type: kubernetes.io/dockerconfigjson
  {{ end }}
```

3. support in all the service account yaml for adding secrets:
```
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cost-analyzer.serviceAccountName" . }}
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
secrets:
  - name: registrySecret
imagePullSecrets:
  - name: {{ .Values.global.repository.secretName }}
{{- end }}
```
4. support for adding different registry host in the image
`image: "{{ .Values.global.repository.host }}/{{ .Values.sidecar.image }}"`

**Describe alternatives you've considered**

Applying a patch after pulling cost-analyzer-helm-chart source from kubecost

**How would users interact with this feature?**

1. users will enable registry secret, set registry host

**Comment by dwbrown2** [comment]
@hchhabada I know we've discussed this multiple times... you're all set here correct?

**Comment by dwbrown2** [comment]
Closing because we now support pulling all Kubecost images from different repos!
