### ISSUE TITLE
Install without grafana and prometheus?

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#7]
See previous discussion here: https://github.com/kubecost/cost-model/issues/31

In short, this is doable but there is enough trickiness that we ideally like to work with teams to make sure this is a smooth experience (e.g. ensure all dependancies are there, Prom isn't being throttled, etc.)

Documentation available here: http://docs.kubecost.com/custom-prom

**Comment by botzill** [comment]
Thx @dwbrown2. Is there smth I can help with?

**Comment by dwbrown2** [comment]
@botzill it would be great to work with you on this! 

I can think of a number of things that would be helpful here. One would be readiness/health probes. You could also look at Helm pre-install hooks to check for dependancies, etc. 

We're also open to other ideas. What sounds most interesting to you?

**Comment by dwbrown2** [comment]
@AjayTripathy might have other ideas too.

**Comment by AjayTripathy** [comment]
These would both be helpful for reliably shipping with custom Prometheus/Grafana! There are a number of other items that I can think of. 
* It would be cool to integrate with service discovery systems to auto discover your Prometheus. 
* [Federation](https://prometheus.io/docs/prometheus/latest/federation/) could also pull this data into your prometheus.
* We also want some way of automatically adding our recording rules to a bring-your-own prometheus setup.
What kind of work is most interesting to you @botzill ?

**Comment by mdaniel** [comment]
As a pragmatic issue, we'll want to prioritize surfacing a chart variable that switches off the `node-exporter` because right now if one has an existing `node-exporter` daemonset, it bombs the chart install because the embedded prom chart waits for its new N-E to be ready, and they will not given the `hostNetwork: true` port conflict

> kubecost             0s          Warning   FailedScheduling          pod/kubecost-prometheus-node-exporter-9rgtx                        0/11 nodes are available: 11 node(s) didn't have free ports for the requested pod ports.
> Error: release kubecost failed: timed out waiting for the condition

**Comment by mdaniel** [comment]
As an update, after [reading the fine manual](https://github.com/helm/helm/blob/v2.13.1/docs/chart_template_guide/subcharts_and_globals.md#overriding-values-of-a-child-chart) it seems one can reach into subcharts and fiddle with their values, so I was able to get the helm chart to install via:

```console
$ helm install kubecost/cost-analyzer --debug --wait --namespace kubecost --name kubecost \
    --set kubecostToken="sekrit" \
    --set prometheus.nodeExporter.enabled=false \
    --set prometheus.serviceAccounts.nodeExporter.create=false
```

I would strongly recommend mentioning those two flags on [the Kubecost install guide](https://kubecost.com/install)

**Comment by dwbrown2** [comment]
@mdaniel will definitely get this added! thank you. 

surprisingly, i've seen this same situation not cause errors on previous installs. do you know if your team didn't install `node-exporter` with helm? i'll investigate a bit to understand why we've haven't seen this behavior in the past.

**Comment by dwbrown2** [comment]
Brief explanation added to our Troublehsooting Guide while I continue to investigate: http://docs.kubecost.com/troubleshoot-install

This page is linked directly from the Kubecost install guide. Always open to feedback :)

**Comment by mdaniel** [comment]
> do you know if your team didn't install node-exporter with helm?

That depends on what you mean by "with helm":

```console
$ helm status prom
LAST DEPLOYED: Mon Feb  4 21:00:13 2019
NAMESPACE: prom
STATUS: DEPLOYED

RESOURCES:
==> v1/ConfigMap
NAME                    DATA  AGE
prom-prometheus-server  3     87d

==> v1/Pod(related)
NAME                                               READY  STATUS   RESTARTS  AGE
prom-prometheus-kube-state-metrics-bcc7747c-j7mwx  1/1    Running  0         7d17h
prom-prometheus-node-exporter-4skkf                1/1    Running  1         87d
...
```

With `helm`, for sure; with **kubecost**'s helm, for sure not -- that's exactly what the `--set prometheus.nodeExporter.enabled=false` needed to explicitly turn off kubecost's version of node exporter because they were fighting for control over the host port

That's why I mentioned in slack that those install instructions must have been for the few cluster admins who were not already running Prom, which I would have thought would have been 100% of the audience but clearly not

**Comment by dwbrown2** [comment]
Oh we've definitely had lots of teams encounter this situation (i.e. existing Prom installation), we just haven't seen the install process blow up like this. Maybe because your team didn't install from helm stable? Still haven't been able to repro. 

Either way, we've added this to our configuration options and install troubleshooting documentation.

**Comment by botzill** [comment]
Tested this, seems to work ok. 

Thx a lot for adding this feature!

**Comment by dwbrown2** [comment]
This integration is now [documented](http://docs.kubecost.com/custom-prom) more broadly. Closing for now, feel free to reopen with questions at any time.
