### ISSUE TITLE
.Values.nodeSelector is not respected across all resouces

### ISSUE THREAD

**Issue by MattJeanes** [kubecost/cost-analyzer-helm-chart#712]
**Describe the bug**
`.Values.nodeSelector` is not respected across all resources. In my case, I have a Windows node and kubecost was trying (and failing) to deploy pods / jobs onto the Windows node.

The resources I've noticed potentially affected are:
- https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-checks-template.yaml
- https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-network-costs-template.yaml
- https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-prometheus-postgres-adapter-deployment.yaml

There may be others too, note how these daemonsets / deployments do not use the `.Values.nodeSelector` in their YAML.

**To Reproduce**
1. Have a Windows node in your cluster
2. Run `helm install kubecost/cost-analyzer --namespace kubecost --set nodeSelector."kubernetes\\.io/os"=linux` in a bash-like shell
3. Note how the nodeSelector is not respected on all resources and (may) try to provision kubecost pods on a Windows node, 

**Expected behavior**
When a `nodeSelector` is set, it should be respected across all the pods, etc in a Helm chart.

**Collect logs (please complete the following information):**
N/A - I have since fixed the issue by adding a taint to my Windows node, there were pods failing with errors like `ImagePullBackOff` since they were not multi-platform images

**Comment by AjayTripathy** [comment]
I've created #721 to address this. Thanks for the report!

**Comment by MattJeanes** [comment]
Thank you, much appreciated!

**Comment by dwbrown2** [comment]
@MattJeanes this should be available in our last two releases! Can we get you anything else?

**Comment by MattJeanes** [comment]
That's all, thank you very much
