### ISSUE TITLE
Special characters not working on Asset filtering

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#719]
**Describe the bug**
When supplying a Tag/Label asset filter in Assets the value `namespace:kubecost` provides expected matching results but `kubernetes_namespace:kubecost` does not

Here's an example API request that fails. This is generated from the frontend. 

/assets?window=6d&aggregate=service&accumulate=false&filterLabels=kubernetes_namespace%3Akubecost&sharedMonthlyCost=1000&req=1609978087322

**Comment by dwbrown2** [comment]
@itscalvinwang could you take a look since I think you worked on this recently? 

@AjayTripathy as FYI in case he knows more.

**Comment by itscalvinwang** [comment]
On initial glance, my suspicion is that the underscore is the problematic character. I know that when our code writes to Prometheus, any illegal character (which "_" is) gets sanitized to become a hyphen ("-") before writing and after reading.

I'll take a look today/Monday if time permits but my main priority is making sure alerts are looking good for release.

**Comment by dwbrown2** [comment]
Yes, I suspect it's Prom's treatment of underscore as well. Let's try to get this fixed for Tuesday's release if possible but support keeping alerts as the top priority!

**Comment by dwbrown2** [comment]
Fixed in v1.74
