### ISSUE TITLE
Certain custom windows not support in Allocation details view

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#729]
When viewing cumulative costs by namespace over a custom time window, the Cost Allocation subpages shows an empty table despite having non-zero values for the corresponding table cells in the Cost Allocation page:

* RAM Cost: /metric.html?id=ram&ns=kube-system&window=2021-01-01T00:00:00Z,2021-01-05T23:59:59Z
* CPU Cost: /metric.html?id=cpu&ns=kube-system&window=2021-01-01T00:00:00Z,2021-01-05T23:59:59Z
* PV Cost: /metric.html?id=pv&ns=kube-system&window=2021-01-01T00:00:00Z,2021-01-05T23:59:59Z
* Network costs: /network.html?ns=kube-system&window=2021-01-01T00:00:00Z,2021-01-05T23:59:59Zd (Only for the 

Network costs page, I get this Unable to retrieve network costs. See developer console for more info. message in the table, found this error {status: "error", errorType: "bad_data", error: "invalid parameter 'query': 1:97: parse error: missing unit character in duration"} printed out in the developer console; I also noticed the Network costs links from the Cost Allocation page appends an extra d to the end of the window query param, I tried removing it (i.e. /network.html?ns=kube-system&window=2021-01-01T00:00:00Z,2021-01-05T23:59:59Z) but still got the same error as described above)

**Comment by AjayTripathy** [comment]
This is fixed in 1.73.0
