### ISSUE TITLE
networkCosts don't work with PSP enabled

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-analyzer-helm-chart#741]
**Describe the bug**
networkCosts pod is not able to start if the cluster uses a Pod Security Policy.

From k8s events:
```
2m17s       Warning   FailedCreate        daemonset/cost-analyzer-network-costs   Error creating: pods "cost-analyzer-network-costs-" is forbidden: unable to validate against any pod security policy: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.containers[0].hostPort: Invalid value: 3001: Host port 3001 is not allowed to be used. Allowed ports: [] spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].hostPort: Invalid value: 3001: Host port 3001 is not allowed to be used. Allowed ports: [] spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.containers[0].hostPort: Invalid value: 3001: Host port 3001 is not allowed to be used. Allowed ports: []]
```

This also happens with kubecostChecks but @garreeoke told me via Slack that this problem will be fixed in the next release.

From k8s events:
```
22m         Warning   Failed                   pod/cost-analyzer-checks-1611075600-zrcd7       Error: container has runAsNonRoot and image will run as root
```

**To Reproduce**
Deploy kubecost with networkCosts enabled in a cluster with this policy deployed:
https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/policy/restricted-psp.yaml

**Expected behavior**
networkCosts is able to run.

**Comment by dwbrown2** [comment]
The network-costs DaemonSet specifically needs to access hostNetwork, so I'm not sure this will work. @mbolt35 for comment

The latter issue should indeed be resolved.

**Comment by pierluigilenoci** [comment]
In this case, a privileged PSP capable of doing this must also be provided in the chart. As is already done with https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/templates/cost-analyzer-psp.template.yaml.
If it is not possible to integrate it with the chart, it should be described in the installation guide how to generate it, IMHO.

**Comment by dwbrown2** [comment]
I'll let @mbolt35 comment further, but does this not get you what is needed? https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/templates/network-costs-psp.template.yaml

**Comment by mbolt35** [comment]
@pierluigilenoci I think @dwbrown2 is correct here: Flag to enable is here: https://github.com/kubecost/cost-analyzer-helm-chart/blob/c10e9475b51612d36da8f04618174a98cc62f8fd/cost-analyzer/values.yaml#L386-L387

**Comment by pierluigilenoci** [comment]
> https://github.com/kubecost/cost-analyzer-helm-chart/blob/c10e9475b51612d36da8f04618174a98cc62f8fd/cost-analyzer/values.yaml#L386-L387

Enabling this not solve the issue. This [log](https://github.com/kubecost/cost-analyzer-helm-chart/issues/741#issue-791949633) is exactly a Kubecost installation with that flag enabled.

**Comment by pierluigilenoci** [comment]
Our configuration: 
```
    networkCosts:
      enabled: true
      podSecurityPolicy:
        enabled: true
```

**Comment by pierluigilenoci** [comment]
In your [PSP](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/network-costs-psp.template.yaml) probably is missing this `hostNetwork: true` and `hostPorts`.

Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#host-namespaces

**Comment by pierluigilenoci** [comment]
I tried to use version 1.73.0 but the network-costs pod still doesn't work correctly. 

From K8s events:

```
Error creating: pods "cost-analyzer-network-costs-" is forbidden: unable to validate against any pod security policy: [spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.containers[0].hostPort: Invalid value: 3001: Host port 3001 is not allowed to be used. Allowed ports: [] spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].hostPort: Invalid value: 3001: Host port 3001 is not allowed to be used. Allowed ports: [] spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].hostPort: Invalid value: 3001: Host port 3001 is not allowed to be used. Allowed ports: []]
```

**Comment by mbolt35** [comment]
Looks like we need to update `hostPath` as well - reading up on this. PR will remain open until we figure it out. Thanks for all the info @pierluigilenoci!

```
Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used
```

**Comment by dwbrown2** [comment]
@pierluigilenoci are you able to verify that https://github.com/kubecost/cost-analyzer-helm-chart/pull/762 meets your needs?

**Comment by pierluigilenoci** [comment]
@dwbrown2 It would seem correct. As soon as you do a staging build I can test it on our cluster and see what happens.

**Comment by dwbrown2** [comment]
@pierluigilenoci can you let us know if there's anything else you need here? This will be in our 1.74 build coming shortly!

**Comment by pierluigilenoci** [comment]
@dwbrown2 works like a charm!

**Comment by pierluigilenoci** [comment]
Thank you!

**Comment by pierluigilenoci** [comment]
@dwbrown2 I celebrated too early. 

@mbolt35 the pod seems running in a proper way.

```
I0211 16:13:51.866596       1 networktrafficlogger.go:77] [REDACTED]
I0211 16:13:51.866599       1 networktrafficlogger.go:80]   -> Dest: 10.5.0.252, [RZ] Total Bytes: 176954, Total GB: 0.00
I0211 16:13:51.866602       1 networktrafficlogger.go:81]      [REDACTED]
I0211 16:13:51.866606       1 networktrafficlogger.go:80]   -> Dest: 10.5.0.253, [RZ] Total Bytes: 96674, Total GB: 0.00
I0211 16:13:51.866609       1 networktrafficlogger.go:81]      [REDACTED]
I0211 16:13:51.866612       1 networktrafficlogger.go:80]   -> Dest: 10.5.1.10, [RZ] Total Bytes: 5288, Total GB: 0.00
I0211 16:13:51.866615       1 networktrafficlogger.go:81]      [REDACTED]
I0211 16:13:51.866618       1 networktrafficlogger.go:80]   -> Dest: 10.5.1.156, [RZ] Total Bytes: 1728, Total GB: 0.00
I0211 16:13:51.866621       1 networktrafficlogger.go:81]      [REDACTED]
I0211 16:13:51.866623       1 networktrafficlogger.go:80]   -> Dest: 10.5.1.17, [RZ] Total Bytes: 720, Total GB: 0.00
I0211 16:13:51.866627       1 networktrafficlogger.go:81]      [REDACTED]
I0211 16:13:51.866632       1 networktrafficlogger.go:76] Source: 10.5.2.70
I0211 16:13:51.866635       1 networktrafficlogger.go:77] [REDACTED]
I0211 16:13:51.866638       1 networktrafficlogger.go:80]   -> Dest: 10.5.1.170, [RZ] Total Bytes: 123886, Total GB: 0.00
I0211 16:13:51.866641       1 networktrafficlogger.go:81]      [REDACTED]
```

But inside the dashboard, I keep seeing this

<img width="291" alt="Screenshot 2021-02-11 at 17 31 47" src="https://user-images.githubusercontent.com/36044817/107667285-bbb11580-6c8f-11eb-94f4-09b3b6308763.png">

My configuration:
```yaml
    networkCosts:
      enabled: true
      podSecurityPolicy:
        enabled: true
```

**Comment by pierluigilenoci** [comment]
Found it. The annotation for Prometheus is missing from the definition of the Daemonset. 
New issue here https://github.com/kubecost/cost-analyzer-helm-chart/issues/770
