### ISSUE TITLE
Include this chart inside Artifact Hub

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-analyzer-helm-chart#742]
**What problem are you trying to solve?**
The chart is not listed in Artifact Hub. https://artifacthub.io/

**Describe the solution you'd like**
I would like the chart to be listed in the Artifact Hub. This guarantees uniformity and quality to the chart (as well as visibility to the project)

This is the guide to being accepted:
https://artifacthub.io/docs/topics/repositories/

**Comment by pierluigilenoci** [comment]
@dwbrown2 any feedback?

**Comment by dwbrown2** [comment]
We are reviewing this soon @pierluigilenoci. We will share updates when we have them.

**Comment by dwbrown2** [comment]
v1 available here: https://artifacthub.io/packages/helm/kubecost/cost-analyzer

@AjayTripathy are you going to add README next?

**Comment by pierluigilenoci** [comment]
@dwbrown2 thx! I think this ticket can be closed now.

**Comment by dwbrown2** [comment]
Waiting on @AjayTripathy to add a README and then we can close!

**Comment by AjayTripathy** [comment]
Done!
