### ISSUE TITLE
Helm chart values undocumented

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-analyzer-helm-chart#745]
**What problem are you trying to solve?**

There are many completely undocumented configuration possibilities within the chart.

To give some examples:
```
kubecostToken
kubecostFrontend.tls.enabled
grafana.sidecar.dashboards.enabled (this is more related to Grafana chart but anyway)
```

**Describe the solution you'd like**
I'll like to have all the options well documented in the chart README.md so you don't have to guess or go to the chart templates to understand how it works. I want to suggest improving the readability of the whole documentation.

**Comment by dwbrown2** [comment]
Strong +1 from me. Let's get more documentation added here.

**Comment by dwbrown2** [comment]
First PR https://github.com/kubecost/cost-analyzer-helm-chart/pull/753 is out

**Comment by dwbrown2** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/pull/757 added with more to come

**Comment by pierluigilenoci** [comment]
`networkCosts.trafficLogging` is not documented

**Comment by dwbrown2** [comment]
It's rarely used and therefore documented on the [network-allocation docs](https://github.com/kubecost/docs/blob/master/network-allocation.md#kubernetes-network-traffic-metrics) page.

**Comment by pierluigilenoci** [comment]
Sparse documentation is not effective for using the chart. IMHO the chart [README.md](https://github.com/kubecost/cost-analyzer-helm-chart#kubecost-helm-chart) should contain all `values` and cross-references to in-depth documentation.

**Comment by dwbrown2** [comment]
I actually disagree, @pierluigilenoci. If we include all config options, this file will be more than 3k lines long. That will be a bad user experience for most. 

My proposal is that we references our subcharts. For example, we can include this for Prometheus. 


For more Prometheus configuration options, reference: [prometheus/values.yaml](https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/charts/prometheus/values.yaml)

**Comment by pierluigilenoci** [comment]
Obviously, it makes no sense to document the configuration options for the sub-charts, for that just refer to the official documentation of the sub-charts. I'm talking about the exclusive configurations of kubecost. For example: 

- kubecostFrontend.tls.enabled
- networkCosts.trafficLogging

To be able to understand how to configure these options I had to go through the templates of the chart.

**Comment by dwbrown2** [comment]
Glad we're in agreement on that! 

`networkCosts.trafficLogging` is now included
`kubecostFrontend.tls.enabled` is technically part of enterprise, so that's why it was not included

I'm not aware of any other missing config options, are you?

**Comment by dwbrown2** [comment]
Marking as closed as I don't see any others right now we need documented.

**Comment by pierluigilenoci** [comment]
@dwbrown2 
I found one:
```
kubecostModel:
  utcOffset: "+01:00"
```

**Comment by pierluigilenoci** [comment]
Also the new networkPolicy parameters are not documented:
```
networkPolicy:
  enabled: true
  denyEgress: false
  sameNamespace: false
  namespace: xxx
```
