### ISSUE TITLE
Getting "connection refused" when connecting to Openshift built-in Prometheus

### ISSUE THREAD

**Issue by LH8PPL** [kubecost/cost-analyzer-helm-chart#752]
**Describe the bug**
Getting "connection refused" when connecting to Openshift built-in Prometheus .

**To Reproduce**
1. Configure the Openshift built-in Prometheus url.
2. See error

**Expected behavior**
Can you please explain and give example how to connect with token?

**Comment by dwbrown2** [comment]
@LH8PPL would you be able to share any more context? For example, where are you seeing this error? Can you share the full log? Also, how are you deploying our product? Were you able to successfully deploy with the bundled Prometheus initially?

**Comment by LH8PPL** [comment]
1. I am deploying it with the helm chart on a Openshift 3.11.
2. All settings are default except for the Prometheus (openshift built-in) and Grafana (latest Grafana helm chart) URLs.
3. company security, cant paste the log here.
4. seeing the error in the cost analyzer pod logs.
5. didn't deploy the bundled Prometheus.

**Comment by dwbrown2** [comment]
Can you deploy with our bundled Prometheus first? It sounds like you may have some sort of auth on your Prometheus. Kubecost should support but hard to comment without knowing more.

**Comment by LH8PPL** [comment]
> Can you deploy with our bundled Prometheus first? It sounds like you may have some sort of auth on your Prometheus. Kubecost should support but hard to comment without knowing more.

as i said it needs token auth....
do you know how to configure it in cost analyzer?
can you give me an example?

**Comment by dwbrown2** [comment]
Apologies -- we have a different concept of a token in our product... 

I believe this is the feature you are looking for: https://github.com/kubecost/cost-analyzer-helm-chart/blob/c10e9475b51612d36da8f04618174a98cc62f8fd/cost-analyzer/values.yaml#L8

**Comment by kirbsauce** [comment]
Hi @LH8PPL! Just wanted to check in to see if you were able to successfully connect to your own Prometheus?  Happy to help in any way we can!

**Comment by kirbsauce** [comment]
Closing for now but feel free to reopen the conversation if need be!
