### ISSUE TITLE
Tolerations missing from job cost-analyzer-checks

### ISSUE THREAD

**Issue by Zenmodai** [kubecost/cost-analyzer-helm-chart#758]
**Describe the bug**
With the last release, you added the support of nodeselectors through all resources. But you did not add tolerations to the job cost-analyzer-checks as well, which results in provisioning errors/problems.

**Expected behavior**
Please add this settings for the job as well or remove the nodeselectors for the job. Also currently there are general options for nodeselector and tolerations, but also a networkcosts specific option for tolerations. Please use the general options for all resources. There is no need to have different tolerations here.

In "cost-analyzer-checks-template.yaml", you can see that only nodeSelector is used and not tolerations.
[https://github.com/kubecost/cost-analyzer-helm-chart/blob/7a43a04391d9cbba648b0c8395a0671aa81ae263/cost-analyzer/templates/cost-analyzer-checks-template.yaml#L62](https://github.com/kubecost/cost-analyzer-helm-chart/blob/7a43a04391d9cbba648b0c8395a0671aa81ae263/cost-analyzer/templates/cost-analyzer-checks-template.yaml#L62)

**Comment by pierluigilenoci** [comment]
Hi @li-adrienloiseau the version 1.73.0 should have this setting.
https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L226

**Comment by Zenmodai** [comment]
The version 1.73.0 only has the setting for nodeSelector, not tolerations, for the cost-analyzer-checks jobs. The tolerations setting is not put through. 
[https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-checks-template.yaml](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-checks-template.yaml)

**Comment by pierluigilenoci** [comment]
Howevere `tolerations` are here: https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L228

**Comment by pierluigilenoci** [comment]
Ok, now I understand.
Missing here: https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-checks-template.yaml#L62-L64

**Comment by dwbrown2** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/pull/780 is now outstanding! That look good @Zenmodai @pierluigilenoci?

**Comment by pierluigilenoci** [comment]
@dwbrown2 almost good. It is better do define separate tolerations/nodeselector for any element of the software. Ref: https://github.com/kubecost/cost-analyzer-helm-chart/issues/772

**Comment by michaelmdresser** [comment]
Closing this issue because it seems to be addressed. We'll leave #772 open.
