### ISSUE TITLE
Support all three of HTTP_PROXY, HTTPS_PROXY and NO_PROXY

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#759]
**What problem are you trying to solve?**
Better control for using HTTP/S proxies.

Remove the fields:   useHttps:, proxyIP and proxyPort
Add the fields httpProxyUrl, httpsProxyUrl and noProxy
Set the envs HTTP_PROXY, HTTPS_PROXY and NO_PROXY with the values specified in #2, without trying to manipulate them.

**Comment by dwbrown2** [comment]
@AjayTripathy any updates here?

**Comment by AjayTripathy** [comment]
This has been fixed!
