### ISSUE TITLE
Use a separate nodeselector for network-costs

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#772]
Network-costs needs a separate nodeselector so users can configure what nodes they run on easily.

**Comment by Zenmodai** [comment]
@AjayTripathy Please see issue #758, currently tolerations is missing for the cost-analyzer-checks job, only nodeselector can be configured and is put through. Please add tolerations throughput.

**Comment by pierluigilenoci** [comment]
I need this fix too! Thx!

**Comment by pierluigilenoci** [comment]
@AjayTripathy is there any chance to see this change soon?

**Comment by AjayTripathy** [comment]
@pierluigilenoci yep-- we're planning for this in our upcoming release next week, currently scheduled for Tuesday PST

**Comment by mbolt35** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/pull/806

**Comment by dwbrown2** [comment]
Thanks, @mbolt35! 

Marking this as closed. Still expected in our release tomorrow. Let me know if there are any questions!
