### ISSUE TITLE
"Datasource named default-kubecost was not found" 

### ISSUE THREAD

**Issue by qfliu** [kubecost/cost-analyzer-helm-chart#775]
**Describe the bug**
When I use the default helm chart, Grafana dashboard does not show anything. I tried to edit the dashboard and got `Datasource named default-kubecost was not found` error. When I check the dropdown of datasource, I see there is a default one and that one shows me values.

**To Reproduce**
- Use command on install instruction page to deploy `helm install kubecost kubecost/cost-analyzer --namespace kubecost --set kubecostToken="ZWRtdW5kQHR1YnVsYXJsYWJzLmNvbQ==xm343yadf98"`
- Run `kubectl port-forward --namespace kubecost deployment/kubecost-cost-analyzer 9090` locally
- Open Kubecost UI. On the "Overview" page, open `CLUSTER METRICS`

**Expected behavior**
Grafana should work in default chart

**Screenshots**
<img width="1666" alt="Screen Shot 2021-02-15 at 3 58 05 PM" src="https://user-images.githubusercontent.com/1855935/108003276-1fe11b80-6fa7-11eb-9198-a35ae039b1c0.png">
<img width="1648" alt="Screen Shot 2021-02-15 at 3 58 13 PM" src="https://user-images.githubusercontent.com/1855935/108003284-240d3900-6fa7-11eb-963d-1a4e5a396051.png">

**Collect logs (please complete the following information):**

 - Run `helm ls` and paste the output here:
 ```
NAME    	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART               	APP VERSION
kubecost	kubecost 	1       	2021-02-15 15:43:35.787446 -0800 PST	deployed	cost-analyzer-1.74.0	1.74.0
```

**Comment by dwbrown2** [comment]
@qfliu thanks for the thorough report! 

@AjayTripathy would you be able to review?

**Comment by AjayTripathy** [comment]
Hi @qfliu , I wasn't able to reproduce this. Can you run:
`kubectl logs kubecost-grafana-6df5cc66b6-nbvjd -n kubecost -c grafana-sc-datasources`
and
`kubectl get configmap -n kubecost grafana-datasource -o yaml`
Then share the results?

**Comment by qfliu** [comment]
Actually, I was looking at it again today and I see stuff loading now. I waited a few hours yesterday and nothing was showing up. I guess I just needed to wait longer. Thanks for looking into this.

**Comment by qfliu** [comment]
@AjayTripathy  I have got the issue again. This happened when I was deploying it to a namespace other than kubecost.

`kubectl logs kubecost-grafana-6df5cc66b6-nbvjd -n kubecost -c grafana-sc-datasources` output:
```
[2021-02-25 01:15:08] Starting collector
[2021-02-25 01:15:08] No folder annotation was provided, defaulting to k8s-sidecar-target-directory
[2021-02-25 01:15:08] Selected resource type: ('configmap',)
[2021-02-25 01:15:08] Config for cluster api loaded...
[2021-02-25 01:15:08] Unique filenames will not be enforced.
[2021-02-25 01:15:11] Working on configmap ops/grafana-datasource
[2021-02-25 01:15:11] File in configmap datasource.yaml ADDED
```

`kubectl get configmap -n kubecost grafana-datasource -o yaml`output:
```
apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - access: proxy
      name: "default-kubecost"
      isDefault: false
      type: prometheus
      url: http://monitoring-prometheus-server.ops
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: ops
  creationTimestamp: "2021-02-25T01:14:56Z"
  labels:
    app: cost-analyzer
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cost-analyzer
    helm.sh/chart: cost-analyzer-1.74.0
    kubecost_grafana_datasource: "1"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:datasource.yaml: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:helm.sh/chart: {}
          f:kubecost_grafana_datasource: {}
    manager: Go-http-client
    operation: Update
    time: "2021-02-25T01:14:56Z"
  name: grafana-datasource
  namespace: ops
  resourceVersion: "184454392"
  selfLink: /api/v1/namespaces/ops/configmaps/grafana-datasource
  uid: 30f5ce4d-c188-48a0-8230-37fb1e9af07a
```

**Comment by AjayTripathy** [comment]
Hi @qfliu sorry for the late response. I can't reproduce this but we're hopeful that https://github.com/kubecost/cost-analyzer-helm-chart/pull/787 will resolve some of the flakiness here.

**Comment by qfliu** [comment]
@AjayTripathy Does the pr you mentioned fix cases when there are multiple prometheus datasources? I tried deploying kubecost in 2 different kubernetes clusters under different namespaces (both are not kubecost) and none of them worked. Is there some things I need to be careful of when setting the namespace/release name?

**Comment by qfliu** [comment]
Setting the following values worked for me:
```
namespace_datasources: ops # override the default namespace here
namespace_dashboards: ops # override the default namespace here
```

I just missed them before, but I am not sure why the resulting configmaps are the same.

**Comment by qfliu** [comment]
Ok, actually, it did not work... that datasource was created manually by me... it was me being stupid...

**Comment by qfliu** [comment]
@AjayTripathy We were able to fix the issue if we restart the grafana container after everything is running. It seems to us that there is a race condition with datasource.yaml file generation and grafana container generation.

**Comment by dwbrown2** [comment]
@AjayTripathy should this race condition be gone with new datasources change?

**Comment by AjayTripathy** [comment]
I believe so, but I wasn't able to exactly reproduce this race condition. Let's re-open if it happens again.
