### ISSUE TITLE
Enable Slack notification for new releases

### ISSUE THREAD

**Issue by csfangy** [kubecost/cost-analyzer-helm-chart#778]
Request: Want to set up a notification on Slack's Github app to watch the releases via the generic command `/github subscribe kubecost/cost-analyzer-helm-chart`

Solution:
Github org owner to install Slack integration on Github.

**Comment by dwbrown2** [comment]
We have the Github app added to the kubecost Slack workspace and receive updates there. Is there anything else that need to be done? I'm less familiar with different options available.

**Comment by dwbrown2** [comment]
@csfangy I believe this is done, but please drop a comment if I'm mistaken.

**Comment by csfangy** [comment]
I'm not sure if he meant enabling this? https://github.com/integrations/slack. He wants to subscribe inside his slack to the cost-analyzer-helm-chart github. If you're done this, then I think that solves it!

**Comment by dwbrown2** [comment]
Yep, that's the integration we added to the Kubecost workspace. You should be able to do this to your own channel/workspace if that's preferred. That solve for you?

**Comment by csfangy** [comment]
@dwbrown2 perfect! I'll go back to the requestor to activate
