### ISSUE TITLE
mountPath must be unique

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-analyzer-helm-chart#783]
**Describe the bug**
Inside your chart you defined two mount points:

Ref: https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L257-L264

One is `serviceKeySecretName` to connect to the cloud provider, the other is `azureStorageSecretName` to connect to the Azure Storage account but the chart uses the same mount point for both.

Ref: https://github.com/kubecost/cost-analyzer-helm-chart/issues/414

If you do so you get this error from Helm:
```installation failed: Deployment.apps \"cost-analyzer\" is invalid: spec.template.spec.containers[0].volumeMounts[2].mountPath: Invalid value: \"/var/secrets\": must be unique```

**To Reproduce**
Install Cost-Analyzer in Azure with both secrets provided.

**Expected behavior**
Helm is able to install the chart.

**Comment by pierluigilenoci** [comment]
@Sean-Holcomb could you please fix this before the new release?

**Comment by pierluigilenoci** [comment]
If you want to store multiple secrets in the same folder you need to use Projected Volume:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-projected-volume-storage/

**Comment by Sean-Holcomb** [comment]
@pierluigilenoci Thanks for the heads up, I just changed the mount path to `/var/azure-storage-config` and it will be in the next release

**Comment by pierluigilenoci** [comment]
@Sean-Holcomb thx
