### ISSUE TITLE
Dependency vulnerability detected in ajaytripathy/kubecost-frontend:prod

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#79]
See output from Aqua

![image004](https://user-images.githubusercontent.com/298359/62237670-44a27d80-b386-11e9-965c-0b762085205c.jpg)

**Comment by AjayTripathy** [comment]
The dependency on the high severity vulnerability has been upgraded and will be released in 1.37.0

**Comment by dwbrown2** [comment]
This libgcrypt version appears to be part of stable nginx. I think it's best to wait for them to upgrade... I don't see a fix version yet.

**Comment by dwbrown2** [comment]
Closing now that this high impact issue is resolved. Waiting on nginx stable to pick up the other.
