### ISSUE TITLE
Diagnostics page should show warning instead of error on failed reservation query

### ISSUE THREAD

**Issue by garreeoke** [kubecost/cost-analyzer-helm-chart#799]
**Describe the bug**
Diagnostic page shows error on failed Athena query regarding reservations. 

**To Reproduce**
1. Setup cloud integrations with an account that does not use reservations

**Expected behavior**
Should show warning as some queries may fail as in the case where reservations are not used. Could also obfuscate other potential issues since it says Metrics are not found.

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/17861748/109314290-01c4b800-77fe-11eb-85b6-8a926a610cb7.png)
![image (1)](https://user-images.githubusercontent.com/17861748/109314292-025d4e80-77fe-11eb-9f2d-88ed4844f065.png)

**Comment by dwbrown2** [comment]
@AjayTripathy who would be best for taking a look at this one?

**Comment by AjayTripathy** [comment]
Should be done! https://github.com/kubecost/cost-model/pull/744
