### ISSUE TITLE
Currency Change request

### ISSUE THREAD

**Issue by anubhav25gupta** [kubecost/cost-analyzer-helm-chart#80]
Hi,

I need price listings in €(EURO), I am able to enable Custom Pricing and able to change it to euro. But some of the tabs still needs to be modified as below:

1).  The Savings panel/tab still showing price details in $(Dollar).

2).  The 'Switch Clusters' tab showing the total price / month in $ instead of €.

3).  After exporting the price to CSV files via allocation tab, The CSV is taking garbage value of 'â‚¬' instead of '€'.

Kindly address these fix in your next release.

**Comment by dwbrown2** [comment]
Number 3 is done and will be available in our next release! What's the relative priority on the other two? Are there other features/issues that are higher priority for you?

**Comment by anubhav25gupta** [comment]
Thanks for performing number 3. 
I am looking out the cost for Europe region and that is why the importance of € symbol is much more prior in every sense. I can see the dashboards in the Euro symbol but point 1 and 2 has to be covered also in order to represent the kubecost software to my customers.

**Comment by dwbrown2** [comment]
Hi @anubhav25gupta, I'm pretty sure all of these were long ago addressed but let me know if there are still outstanding requests here!

**Comment by dwbrown2** [comment]
Closing because I think these have all been addressed for a while, please feel free to reopen if we can get you anything else!
