### ISSUE TITLE
Verify Athena configuration with test button

### ISSUE THREAD

**Issue by garreeoke** [kubecost/cost-analyzer-helm-chart#812]
**What problem are you trying to solve?**
Verify Athena configuration is correct within UI

**Describe the solution you'd like**
Test button on the configuration page

**How would users interact with this feature?**
After configuring Athena setup can hit test button to ensure it is able to connect.

**Comment by dwbrown2** [comment]
@AjayTripathy for comment

**Comment by dwbrown2** [comment]
This feels like a solid solution, but could we alternatively have a diagnostic test that auto refreshes any times there is an update?

**Comment by dwbrown2** [comment]
@Sean-Holcomb is it fair to sat this is part of your current cloud diagnostics effort?!

**Comment by Sean-Holcomb** [comment]
Yes that is correct. Status for configured cloud providers is high on the list for diagnostics.

**Comment by dwbrown2** [comment]
Nice, let's share updates here when available if that sounds good to you!

**Comment by kbrwn** [comment]
Cloud diagnostics was added a while ago. Closing.
