### ISSUE TITLE
Reports View: CSV downloader does not download new efficiency / external costs columns

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#813]
**What problem are you trying to solve?**
We added a bunch of cool features to the page but didn't update the CSV downloader!

**Describe the solution you'd like**
The CSV download functionality should include these columns

**Comment by andreb89** [comment]
@AjayTripathy Any update on this? 
As workaround we are currently using the API, but for regular users, the simple download would be better, as long as it contains all cost columns.

**Comment by AjayTripathy** [comment]
Hi @andreb89 -- this is straightforward enough. we can get it added to our next sprint.

**Comment by AjayTripathy** [comment]
The external costs are downloaded. We'll look to add efficiency to it as well.

**Comment by dwbrown2** [comment]
PR merged for this. It's now available in our [nightly builds](https://github.com/kubecost/docs/blob/master/release-process.md#nightly-releases) and coming to prod next week. Let us know if there's more we can do here!
