### ISSUE TITLE
Multiple Kubecost datasource in a single Grafana installation.

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-analyzer-helm-chart#817]
**What problem are you trying to solve?**
If you have more than one datasource from different Kubecost installations, the dashboard that is opened from the links of the Kubecost UI does not pull up the right datasource that needs to be adjusted by hand. 

**Describe the solution you'd like**
The correct datasource name should be added in the installation (ie the Helm Chart) and then the parameter added in the UI in this way: `&var-datasource=mycustomdatasource`

**How would users interact with this feature?**
They see the dashboard with the correct data instead of having to manually choose the right datasource.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-231) by [Unito](https://www.unito.io)

**Comment by pierluigilenoci** [comment]
Ref: https://github.com/kubecost/cost-analyzer-helm-chart/issues/744

**Comment by pierluigilenoci** [comment]
@AjayTripathy any feedback?

**Comment by pierluigilenoci** [comment]
@AjayTripathy any news?

**Comment by pierluigilenoci** [comment]
@dwbrown2 four months has passed, is there any news?

**Comment by dwbrown2** [comment]
No updates, but PRs are welcome @pierluigilenoci!

**Comment by pierluigilenoci** [comment]
@kirbsauce any update?

**Comment by kirbsauce** [comment]
Hi @pierluigilenoci , no updates for this one as the number of affected users hasn't increased and workaround still exists,  so priority remains the same.

**Comment by kirbsauce** [comment]
Hi @pierluigilenoci .  Still no change in priority. Any change in priority or status will be reflected here via release tag and/or associated PR.

**Comment by pierluigilenoci** [comment]
![hopes-and-dreams-barney-hopes](https://github.com/kubecost/cost-analyzer-helm-chart/assets/36044817/f19fc732-ce5a-40fb-a736-674ca7fdf700)
