### ISSUE TITLE
Configuration options are not updated from value 'true' to 'false'

### ISSUE THREAD

**Issue by andreb89** [kubecost/cost-analyzer-helm-chart#818]
**Describe the bug**
Configuration options are not updated from value 'true' to 'false'. Currently options are only updated, if they were changed from 'false' to 'true'.
[defaultIdle option](https://github.com/kubecost/cost-analyzer-helm-chart/blob/420566166906b76e8e532d26bf0178f4d09a263c/cost-analyzer/values.yaml#L629)
`defaultIdle: true` is set in the pricing configmap
`defaultIdle: false` is NOT set in the pricing configmap, option is left out

`{{- if .Values.kubecostProductConfigs.defaultIdle }}`
[pricing configmap](https://github.com/kubecost/cost-analyzer-helm-chart/blob/420566166906b76e8e532d26bf0178f4d09a263c/cost-analyzer/templates/cost-analyzer-pricing-configmap.yaml#L70)

It will only set the option on the pricing configmap, if it is true. But if you have an already installed cost-analyzer and want to update it with `defaultIdle: false`, then it will remove the option from the pricing configmap and not overwrite/change the config in the persistent storage.

This problem includes other configuration options as well, which use the same value check.

**To Reproduce**
1. Install cost-analyzer with `defaultIdle: true`
2. Check the settings in the dashboard after the installation, that the option is set
3. Update cost-analyzer with `defaultIdle: false`
4. Check the settings in the dashboard again after the update. The option is still set to true
5. The config file in the persistent storage (e.g. azure.json) still has the option with the value 'true'
6. The configmap does not have the option anymore. So the config json will not update this option apparently.

**Expected behavior**
If you set the option `defaultIdle: false`, then it should actually work, even after running a cost-analyzer update. This problem includes other configuration options as well, which use the same value check.

**Comment by AjayTripathy** [comment]
Hi @andreb89 , thanks for this report. I realize this isn't ideal but can you try `"false"` instead of just `false` ? That should solve the immediate problem and we'll look to document this behavior better.

**Comment by andreb89** [comment]
@AjayTripathy Yes, it's not a clean solution. But I applied the workaround and it solved the immediate problem. Thanks for the fast reply.
