### ISSUE TITLE
Consider Using Prometheus statefulsets by default

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#82]
It should already work and implementation would be as simple as setting 
server.statefulSet.enabled in the prometheus block of values.yaml

Considerations would be statefulsets were only GA as of k8s 1.9

**Comment by dwbrown2** [comment]
Does this impact users if they want to run Prometheus w/o an attached PV?

**Comment by dwbrown2** [comment]
I think current defaults seem fine but we could document this option? I do not believe this would work with Thanos. But let me know what you think.
