### ISSUE TITLE
Label/Tag filter in Asset dashboard for Azure out-of-cluster costs does not work

### ISSUE THREAD

**Issue by andreb89** [kubecost/cost-analyzer-helm-chart#821]
**Describe the bug**
Label/Tag filter in Asset dashboard for Azure out-of-cluster costs does not work currently. 
I remember, that there were some problems with the JSON formatting for the Tags field in the csv report. Could there still be a problem here? I added at the end of this bug report an example tag entry from the csv.
I also tried setting the label mapping for `environment_external_label: "kubernetes_label_environment" `and rebuilding the ETL as well, but it didn't help, the tag filter still isn't doing anything. 

**To Reproduce**
1. Go to Asset dashboard and enter a label/tag filter, e.g.: environment=dev
2. Nothing is shown as the result

**Expected behavior**
After selecting a label/tag filter the specific objects should be shown in the Asset dashboard. But nothing is found and the result is an empty list.

**Screenshots**
![Screenshot from 2021-03-17 14-49-49](https://user-images.githubusercontent.com/78923723/111482448-33ada800-8734-11eb-84e7-dd0097f89dbd.png)

**Collect logs (please complete the following information):**
There are no errors in the cost-model container during the filter execution.

Example entry from the CSV Azure cost-report:

```
Tags (Tags)
--
"environment": "dev","project": "testproject"
```

@Sean-Holcomb Please take a look.

**Comment by Sean-Holcomb** [comment]
"I also tried setting the label mapping for environment_external_label: "kubernetes_label_environment" and rebuilding the ETL as well, but it didn't help, the tag filter still isn't doing anything." 
Can you describe in a little more detail what you tried here? Out of the box "environment_external_label" is looking for 
```
Tags (Tags)
--
"kubernetes_label_environment": "dev","project": "testproject"
```
and it would then create the label to be filtered environment:dev

You can reconfigure "environment_external_label" to be "environment" in values.yaml. If you update the file `helm upgrade` with it attached, then rebuild ETL you should get your expected result. If this is the process you already did please let me know.

**Comment by andreb89** [comment]
@Sean-Holcomb Thanks for the help and clarification. Seems that I misunderstood that part. 
After using `environment_external_label: environment` the label/tag filter works now for `environment=dev`. 
So I will close this bug.
