### ISSUE TITLE
Weekly Update - Configurable option to Incorporate idle costs

### ISSUE THREAD

**Issue by garreeoke** [kubecost/cost-analyzer-helm-chart#822]
**What problem are you trying to solve?**
Have the ability to incorporate idle costs in to the weekly update.

**Describe the solution you'd like**
Be able to configure in yaml or ui to enable the weekly update to incorporate idle costs.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-232) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
I'm supportive, but how do we clearly show this in the weekly report? We could show in a separate column similar to Reports view.

**Comment by csfangy** [comment]
@dwbrown2 separate column is okay, but in this particular scenario the user wants to see the same data as in the Cost Allocation UI with Idle Cost turned on. The idea is for all the teams to be looking at their total costs + their proportional Idle assignment as their final number.

**Comment by dwbrown2** [comment]
This is being reviewed now!

**Comment by kirbsauce** [comment]
@dwbrown2 , do you know if this was ever rolled out?
