### ISSUE TITLE
If multiple Product labels are set, external costs are not allocated.

### ISSUE THREAD

**Issue by garreeoke** [kubecost/cost-analyzer-helm-chart#829]
**Describe the bug**
If multiple labels are set for Product Label are set, external costs are not being shown in cost allocation or reports.

**To Reproduce**
1. Setup cloud integration and tag an external resource (I.e. S3 bucket) using the default product label (app). Verify the external resource is allocated and showing on cost allocation/reports screens when aggregating by product.
2. In settings set the Product label to app,dude 
3. Go back to cost allocation/reports screen, aggregate by product. External costs will be 0.

**Expected behavior**
External costs to show with multiple product labels specified.

**Screenshots**
One Label
![Screen Shot 2021-03-18 at 6 10 11 PM](https://user-images.githubusercontent.com/17861748/112061560-e65a7d80-8b1b-11eb-85bd-c9232fc7bb94.png)
![Screen Shot 2021-03-18 at 6 11 35 PM](https://user-images.githubusercontent.com/17861748/112061572-ea869b00-8b1b-11eb-8937-1e689f991ed7.png)

Two labels
![Screen Shot 2021-03-18 at 6 21 13 PM](https://user-images.githubusercontent.com/17861748/112061621-ff632e80-8b1b-11eb-8b72-1ae56f6bf9a0.png)
![Screen Shot 2021-03-18 at 6 19 54 PM](https://user-images.githubusercontent.com/17861748/112061639-05f1a600-8b1c-11eb-9bb5-6aca15c7afba.png)

**Comment by AjayTripathy** [comment]
Draft PR out to fix this! Expect to merge tomorrow and deploy to nightly soon after.

**Comment by dwbrown2** [comment]
Great! Would you mind adding a description & test to the PR?

Webb
Kubecost, Co-founder

ᐧ

**Comment by nikovacevic** [comment]
I agree that there is a misalignment here that needs to be addressed, but I'd like to challenge the premise. What if the external allocations have the labels:
```json
{
  "app": "cost-analyzer",
  "dude": "wheres-my-car"
}
```
In this case, the given allocations belong to two "products": `cost-analyzer` and `wheres-my-car`. Is the expected behavior for this case defined somewhere? What do we expect should happen?

**Comment by csfangy** [comment]
@AjayTripathy @nikovacevic just checking again to see if this fix is being shipped today as part of the release?

**Comment by andreb89** [comment]
@AjayTripathy @dwbrown2 To add on to the last comment of @nikovacevic 
Could you please clarify what the expected and actual behavior is, if multiple labels for products are used? Will the labels be used as ...||... or ...&&... ?

**Comment by AjayTripathy** [comment]
Yes, this has been shipped and is in the latest release.

Using multiple labels for products is an || match-- you don't need both labels to assign the pod to the product view.

If multiple products are used, this would list the external cost under both products.

**Comment by andreb89** [comment]
I tested it and can confirm, multiple product labels are working now. So this bug can be closed.

**Comment by dwbrown2** [comment]
Great to hear, @andreb89! Re-open if we can get you anything else here.
