### ISSUE TITLE
Generated Service name is incorrect

### ISSUE THREAD

**Issue by dcherman** [kubecost/cost-analyzer-helm-chart#83]
In https://github.com/kubecost/cost-analyzer-helm-chart/pull/76/files, it looks like the name of the service was changed to be hard-coded to `kubecost-cost-analyzer`, however that goes against the Helm norms where the release name is part of the generated service name.

It also broke the ingress definition since the ingress spec does use the generated / full name for the target service which no longer matches:

https://github.com/kubecost/cost-analyzer-helm-chart/blob/1c4c624b0e33c620c9f4ed5bffbe5c6065c008c0/cost-analyzer/templates/cost-analyzer-ingress-template.yaml#L34

**Comment by AjayTripathy** [comment]
Thanks for this report @dcherman -- it does indeed appear that we broke the ingress file. We ended up having to hardcode the servicename because it needs to be passed to prometheus as a scrape endpoint from values.yaml. 

We can definitely fix the ingress file to hardcode this instead of using $fullName, but I'm not sure I see an easy solution to pass a scrape endpoint to prometheus that is dynamically generated.

**Comment by dcherman** [comment]
@AjayTripathy What about using the workaround detailed in https://github.com/helm/helm/issues/3558?  I just tried it in a test chart locally and it seems to work

**Comment by AjayTripathy** [comment]
Ah, if parent helper template definitions work within the subcharts this workaround would work. If you happen to have a PR for that we'd accept it, if not we should be able to do this in our upcoming release.

**Comment by dwbrown2** [comment]
What's the specific use case for a having dynamic service name? Seems like a good idea, but why exactly does it need to change? I ask because this also makes troubleshooting issues slightly more challenging.

**Comment by dcherman** [comment]
@AjayTripathy I can try to cook something up if you'd like.  Might be tomorrow though.

@dwbrown2 I don't have a use case personally since I will only have a single kubecost installation in the cluster, but it seems incorrect to have all of your other resources have names based on the helm release *except* the service, and doesn't follow standard helm manifest naming.  If there's a reasonable workaround that'd let us conform to the standards, it seems like a good idea to do it.

**Comment by dcherman** [comment]
So it turns out this was more difficult than anticipated.  While you can access parent helpers in the context of the child since they're global, the template/helper is evaluated in the child's context, meaning that things like `Chart.Name` are not correct, and I couldn't find a reasonable way to workaround that.

Instead, I decided to keep part of the service name hard-coded and just prepend the release name to it which works fine and still accomplishes the goal of allowing multiple kubecost charts to co-exist, even if it's not the ideal solution.

**Comment by AjayTripathy** [comment]
@dcherman this seems like a good compromise. Couple of small fixes then I think this is ready to merge and ship in the next release.
