### ISSUE TITLE
Configure the ability to change the imagePullPolicy configuration for Kubecost Check

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-analyzer-helm-chart#833]
**What problem are you trying to solve?**

When quay.io is down the cron fails. Configuring the pods with `imagePullPolicy: IfNotPresent` mitigates the problem. 

**Describe the solution you'd like**
Add here the same configuration option of other components:
https://github.com/kubecost/cost-analyzer-helm-chart/blob/142398384b0d299e814c4717730c834d741acfe2/cost-analyzer/templates/cost-analyzer-checks-template.yaml#L41

**Comment by andreb89** [comment]
For further information, here is the link to the incident: [Quay.io image pulls failing](https://status.quay.io/incidents/vfs19hmq660h)
Even though the incident is set as 'resolved', it seems there are still problems regarding image pulling.

**Comment by pierluigilenoci** [comment]
@AjayTripathy @mbolt35 could you please take a look?

**Comment by dwbrown2** [comment]
This pod is being deprecated. We will share updates when we have them.

**Comment by kirbsauce** [comment]
@dwbrown2 , I believe the checks pod has in fact been deprecated and it's my understanding we don't run a cron job anymore, so this can be closed out?

**Comment by dwbrown2** [comment]
That's correct, @kirbsauce! This has now been fully deprecated so closing now.
