### ISSUE TITLE
Need a way to modify the from address in kubecost notifications

### ISSUE THREAD

**Issue by venugopalthati** [kubecost/cost-analyzer-helm-chart#835]
**Describe the bug**
When I do the test run of weekly spending alerts at the namespace level, I am receiving emails from Kubecost <notify@kubecost.com>. Need a way to override this from address with custom email address.

**To Reproduce**
Configure any weekly notification and do the test run to get the notification.

**Expected behavior**
Expecting to receive an email from the custom DL

**Screenshots**

![image](https://user-images.githubusercontent.com/5384400/112181934-3c3e2c80-8bd3-11eb-95cb-e49b10a147b6.png)

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-234) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
@venugopalthati thanks for the report! Can you share any more context on the challenges you're facing? 

I'm trying to determine if the would be to send from your own internal SMTP servers or send from a different address. We've discussed the former but not the latter to date.

**Comment by steveizzle** [comment]
Own internal SMTP would be great. Especially for enterprises where infosec may have obligations about using a third party for sending mails

**Comment by AdamStack18** [comment]
@vgokul984 I will discuss this with the product team and get back to you early next week.

**Comment by dwbrown2** [comment]
Current plan is to design a solution in 1.96 to prepare for an initial implementations. Are there any requirements around this that we should keep in mind, e.g. auth.

**Comment by LaikaN57** [comment]
> Are there any requirements around this that we should keep in mind, e.g. auth.

@dwbrown2 Speaking of auth...

Working around email security for a while has shown me the lack of good documentation around it and end-users not typically know about email security. As you gear up for release, I would ensure that you have **really really (really)** good documentation around setting up DMARC/DKIM/SPF.

I have found some documentation written by https://sendgrid.com/ and https://dmarcian.com/ to be most recently helpful to me in similar setups.

Most of the confusion usually comes from understanding what "from" address a particular technology is checking against and around what DMARC/DKIM/SPF actually validate.

**Comment by kirbsauce** [comment]
hi @vgokul984 !  I wanted to give you an update on this issue.  Unfortunately this isn't going to make the next release as we had hoped.  We'll be re-evaluating it in an upcoming product planning meeting, at which time we'll have a better ETA.  Apologies for any inconvenience.

cc: @dwbrown2 @Adam-Stack-PM

**Comment by Jose-Matsuda** [comment]
Are there any updates regarding this issue? Thanks!

**Comment by Adam-Stack-PM** [comment]
@Jose-Matsuda, thanks for the note.  Will leave this to our great product people to chime in. 

@kwombach12 & @dwbrown2, After the release goes out could you update this ticket with product direction  and thoughts on the idea?

**Comment by kwombach12** [comment]
We have not been able to pick up this issue yet, but I will add it to the list of features for our next release

**Comment by dwbrown2** [comment]
We've reviewed previously and just had concerns around spam abuse... let's discuss as part of next release. I think this will mean supporting custom email providers. Let us know if anybody has input.

**Comment by abdennour** [comment]
@dwbrown2  Since Kubecost can run on k8s on-prem,thus supporting configuring the SMTP server should be a high priority.
As an enterprise customer, i am gonna open a Feature Request as well.

**Comment by chipzoller** [comment]
Custom SMTP server support is coming in 2.3 (with ability to customize sender email address). Enterprise only feature.
