### ISSUE TITLE
Product label "app.kubernetes.io/name" not working correctly in cost allocation view for aggregation product

### ISSUE THREAD

**Issue by andreb89** [kubecost/cost-analyzer-helm-chart#838]
**Describe the bug**
I changed the "Product Label" setting from the default app to app.kubernetes.io/name
Before in the cost allocation view with aggregation product (Url: .../detail.html#&agg=product) the query was working and the table below lists all applications with this label. 
After the change and choosing this aggregation, it just keeps loading. Only after running this a few times I finally get an error in the browser console and results also show up.

`Uncaught Error: Syntax error, unrecognized expression: #label_app.kubernetes.io/name--storage
    at Function.oe.error (jquery.min.3.3.1.js:2)
    at oe.tokenize (jquery.min.3.3.1.js:2)
    at oe.select (jquery.min.3.3.1.js:2)
    at Function.oe [as find] (jquery.min.3.3.1.js:2)
    at w.fn.init.find (jquery.min.3.3.1.js:2)
    at new w.fn.init (jquery.min.3.3.1.js:2)
    at w (jquery.min.3.3.1.js:2)
    at updateStorageCost (detail.html:2175)
    at detail.html:743
    at Object.success (detail.html:468)
    at u (jquery.min.3.3.1.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.3.3.1.js:2)
    at k (jquery.min.3.3.1.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.3.3.1.js:2)
    at XMLHttpRequest.sentryWrapped (helpers.ts:87)`

In the Reports view I can use the breakdown filter "Product" without issues and it will show results with the label like app_kubernetes_io_name=generic-service

What I noticed is that in the Url for Reports the labet gets encoded like app.kubernetes.io%2Fname, but in the Url for the Cost Allocation it says: 
`model/aggregatedCostModel?window=1d&offset=1m&aggregation=label&allocateIdle=false&timeSeries=true&efficiency=true&aggregationSubfield=app.kubernetes.io/name&sharedNamespaces=&sharedSplit=weighted&sharedLabelNames=&sharedLabelValues=&sharedSplit=weighted&req=817094`

aggregationSubfield=app.kubernetes.io/name => this is not encoded, could this be the issue?

Please take a look.

**To Reproduce**
1. Change "Product Label" setting from the default app to app.kubernetes.io/name
2. Open Cost Allocation and use the product aggregation
3. It just keeps loading, after trying it a few times the java script error is shown in the console and results are sjown

**Expected behavior**
Filter Product with recommended K8s label "app.kubernetes.io/name" should work in the cost allocation view as well.

**Screenshots**
![Screenshot from 2021-03-26 13-42-28](https://user-images.githubusercontent.com/78923723/112633235-64c76000-8e39-11eb-98f6-cb5b26eab000.png)

**Comment by dwbrown2** [comment]
@andreb89 what kubecost version are you running? i just tested on v1.76 and wasn't able to reproduce. 

he's the test environment: http://demo.kubecost.io/detail.html#&window=7d&offset=1m&agg=environment

this may just be the cache rebuilding.

**Comment by andreb89** [comment]
@dwbrown2 I am using Kubecost v1.76.0, I just opended the test environment and adjusted the product label as mentioned. At least now http://demo.kubecost.io/detail.html#&agg=product is just loading.

**Comment by andreb89** [comment]
Hmm... now it works on your demo environment. But for me even on another environment of ours which had Kubecost deployed with this label, it still doesn't work. So the initial cache was already built with this.

**Comment by dwbrown2** [comment]
Is everything working as expected on reports.html? This page is expected to replace the current Allocation page soon.

**Comment by andreb89** [comment]
Yes, the reports.html page is working without problems, also using the filters works much faster there.

**Comment by dwbrown2** [comment]
@andreb89 are you able to use that page for now or are you missing functionality from the Allocation page? FYI, reports.html will the new replacement for details.html

**Comment by andreb89** [comment]
@dwbrown2 Reports.html should be ok for now. Can you give an estimate when you will make the switch?

**Comment by kirbsauce** [comment]
Hi @andreb89 , is it safe to assume you've upgraded and this issue is now resolved?

**Comment by andreb89** [comment]
@kirbsauce Yes, after upgrading the problem has been resolved. You can close this issue.

**Comment by kirbsauce** [comment]
thanks @andreb89!
