### ISSUE TITLE
Kubecost authentication

### ISSUE THREAD

**Issue by zippyopstraining** [kubecost/cost-analyzer-helm-chart#843]
Hello, 
     How can i add authenticaion for kubecost? There is saml, kubecostproduct info in helm chart. where do i add authentication?i am using my on-premises kubernetes where i installed kubecost.

**Comment by dwbrown2** [comment]
Hi @zippyopstraining can you share what type of auth you looking to add? Here's a couple refs:

1. You can add saml with our enterprise product
2. You can add basic auth with a standard ingress -- https://github.com/kubecost/docs/blob/master/ingress-examples.md#basic-auth-example

**Comment by zippyopstraining** [comment]
Hi Mr.dwbrown, 
     i am looking for ldab authentication because i dont want basic authentication .can we integrate with kubecost?

**Comment by dwbrown2** [comment]
@zippyopstraining happy to have a discussion about the different options shared above! Feel free to reach out to team@kubecost.com if that would be helpful.

**Comment by dwbrown2** [comment]
Hi @fl-max, we have a simple ingress in our helm chart. You can see values available here -- https://github.com/kubecost/cost-analyzer-helm-chart/blob/f00068f629eee16de52fc78b00e0254c09ce9b78/cost-analyzer/values.yaml#L220-L232

Just wanted to note that SAML-based RBAC can't actually be done with just an ingress.

**Comment by kirbsauce** [comment]
Hi @zippyopstraining , @fl-max.  Closing this issue out for now as it seems there are no followups needed.  Feel free to re-open if you feel there is anything outstanding and we'll be happy to help!
