### ISSUE TITLE
APIs not accessible after SSO implementation

### ISSUE THREAD

**Issue by vikas-gb** [kubecost/cost-analyzer-helm-chart#844]
APIs not accessible after SSO implementation

**To Reproduce**
Enable SSO through SAML authentication
curl https://<HOSTNAME>/model/allocation?window=today doesn't return any data

**Expected behavior**

**Comment by AjayTripathy** [comment]
Thanks for this @vikas-gb. How would you want to authenticate your API clients here? Is supporting a path to access the cluster via a basic auth token sufficient? Note that anyone with this basic auth token would be able to then short-circuit your SAML authentication/authorization.

**Comment by dwbrown2** [comment]
@vikas-gb these APIs are intentionally only available when either 1) authenticated or 2) accessing inside the cluster. Can you share a bit more on your use case / needs?

**Comment by vikas-gb** [comment]
@AjayTripathy - Basic Auth Token for API authentication is sufficient. 
@dwbrown2 - We have few teams using APIs for their cost analysis who do not have access to the cluster and cannot use port forwarding. They only have access to the Primary Kubecost URL

**Comment by dwbrown2** [comment]
Can we not just setup an ingress with basic auth to meet your needs?

**Comment by vikas-gb** [comment]
@dwbrown2 @AjayTripathy - We have a specific requirement from one of the teams for " details/documentation on how to do Auth2.0 access  using Okta as the authorization server". If you can provide an estimate when this will be available, it would be great

**Comment by dwbrown2** [comment]
@vikas-gb were you able to see my previous comment? I do not think it is a good idea for us to poke holes in SAML authentication for you. If we're going to do this on our end, I believe we should take a different approach.

**Comment by vikas-gb** [comment]
@dwbrown2 - I missed your comment. 
You mean SAML authentication will be used for UI access but basic auth for API requests? Can you please share the instructions, we can review and update

**Comment by dwbrown2** [comment]
@vikas-gb you would be able to do this with a modified version of [this ingress](https://github.com/kubecost/docs/blob/master/ingress-examples.md#basic-auth-example). Would you like us to update and share with you?

Note: I just want to be very careful about how this is used. If this is put into place it would effectively be a way around SAML authentication.

**Comment by dwbrown2** [comment]
@AjayTripathy shared offline, so closing now. Please feel free to reopen if needed!
