### ISSUE TITLE
Istio enable for kubecost

### ISSUE THREAD

**Issue by zippyopstraining** [kubecost/cost-analyzer-helm-chart#847]
i enabled istio for my namespace "kubecost" and then installed kubecost model . i facing issue "Unable to reach your Kubecost backend, please ensure the service is reachable ". i have tried all troubelshooting steps. if i enable istio for kubecost, kubecost couldnot connect to any kubernetes objects. error: failed to list deployments, pods,etc Get https://<ip> connect. connection refused. is istio work for kubecost?

**Comment by dwbrown2** [comment]
@zippyopstraining we have sample PR https://github.com/kubecost/cost-analyzer-helm-chart/pull/850 out for testing now... we'll continue to share updates and test solutions but let us know if you have any feedback on early progress. 

Let us know if you do apply these changes locally too!

**Comment by dwbrown2** [comment]
@zippyopstraining this should now be available in our nightly releases if you want to test! 

https://github.com/kubecost/docs/blob/master/release-process.md#nightly-releases

**Comment by zippyopstraining** [comment]
thank you . will test it and comeback to you Mr. dwbrown2.

**Comment by dwbrown2** [comment]
all set @zippyopstraining? let us know if we can help with anything.

**Comment by dwbrown2** [comment]
@zippyopstraining this is now available in production! please re-open at any point if you hit any issues.
