### ISSUE TITLE
Move Grafana deployment dashboard to relative time window

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#85]
Deployment/Statefulset/Daemonset utilization metrics is installed with a preset absolute time range of Feb 5 to Feb 19, 2019. Obviously this is not a generally helpful default. Please change the default to a relative time frame. I suggest "Last 7 days".

**Comment by dwbrown2** [comment]
This does not appear to be an issue when using this dashboard with our core product because we pass a time window. It only happens when you visit the dashboard directly.

**Comment by dwbrown2** [comment]
Addressed by outstanding pr https://github.com/kubecost/cost-analyzer-helm-chart/pull/278

**Comment by minac** [comment]
@dwbrown2 I think we can close this one. :)

**Comment by dwbrown2** [comment]
Yep, agreed :)
