### ISSUE TITLE
Extend external label mapping with owner_external_label

### ISSUE THREAD

**Issue by andreb89** [kubecost/cost-analyzer-helm-chart#855]
**What problem are you trying to solve?**
Kubecost already supports the mapping of external labels like team (team_external_label). Because we have sub-teams/projects under a team unit, we need to also have the external mapping of the owner label. So we can use the owner label for the complete team and the actual team label for the sub-team/project.

So please extend your current external label mapping to include the owner label (owner_external_label), which Kubecost already uses inside the cluster. 

**Describe the solution you'd like**
Support the mapping of external owner label to the internal owner label for external resources.

**How would users interact with this feature?**
Add another config entry in the values.yaml under labelMappingConfigs for owner_external_label

**Comment by dwbrown2** [comment]
@andreb89 it sounds like this would just be as simple as adding an `owner_external_label` to [this block](https://github.com/kubecost/cost-analyzer-helm-chart/blob/57fd8b8018bd18a819c9a261ff3c7847d03d2471/cost-analyzer/values.yaml#L631-L641) and then having it flow through to Allocation and other pages?

I also think we there's an opportunity to add a new concept, Project, which a lot of teams use. 

I think there's a bigger question of should we be using YAML/configs to do this or should this matching just be done in Saved Reports. cc @nikovacevic in case he has thoughts!

**Comment by andreb89** [comment]
@dwbrown2 For the helm chart at least this should be easy to implement. I am not sure, if you need to make other changes in the e.g. cost-model as well for this.
And yes, project would be a great addition as another external label. 

I don't really mind where to configure this. But at the very least, it should be easier to add new external labels to Kubecost for mapping of concepts from outside to inside the cluster.

**Comment by nikovacevic** [comment]
I'm in favor of this change. We'll have to make some small changes to the product, but some of them have already been flagged, e.g. we have some comments like this lying around:
```go
// TODO OwnerExternalLabel (seems like it should exist, but doesn't?)
```

**Comment by andreb89** [comment]
@dwbrown2 @nikovacevic 
Any update here? More external label mapping would be great.

**Comment by nikovacevic** [comment]
@andreb89 we recently made some changes to labels (see https://github.com/kubecost/cost-model/pull/839) that prepared us to address this. Now, it's just a matter of testing and merging this PR: https://github.com/kubecost/cost-analyzer-helm-chart/pull/1010

If not this current release (scheduled for later today) then expect it to come in the next one. Thanks for checking in!
