### ISSUE TITLE
Kubecost Prometheus with Thanos Receivers Configuration

### ISSUE THREAD

**Issue by heartTorres** [kubecost/cost-analyzer-helm-chart#856]
Hello our cluster is already using Thanos Receivers.
Now that we have kubecost set up, we are planning to integrate its prometheus server with our set up in thanos.
But I have not found in the Kubecost documentation on how to configure the prometheus config with Thanos.
We installed the kubecost via helm.

**Comment by dwbrown2** [comment]
Hi @heartTorres! We support Thanos under our enterprise plan. Reach out to team@kubecost.com if you want to learn more!

**Comment by heartTorres** [comment]
hi @dwbrown2, we already reached out to Rob from team support. Based on the architecture, Kubecost is integrated with Thanos by sidecar.  I'll be closing this one now. We'll contact the team@kubecost.com. Thanks!
