### ISSUE TITLE
Support for Custom Costs

### ISSUE THREAD

**Issue by robfaraj** [kubecost/cost-analyzer-helm-chart#860]
**What problem are you trying to solve?**

Track custom costs that are neither in-cluster or a  managed service from a cloud provider (ex. RDS, GCS, etc...). 

Examples: 

* 3rd party costs that live outside of cloud provider (ex. Elasticsearch, Mongo Atlas, etc...)
* Variable licenses (ex. Slack)
* Variable head count costs

**Describe the solution you'd like**

The option to extend the existing external costs solution to support custom metrics or duplicate specifically for this feature. The association by namespace, service, cluster, label, etc...is important to preserve. 

**Describe alternatives you've considered**

1. Managing this completely outside of Kubecost
1. Using Shared Costs monthly monetary field (current distributions aren't sufficient)

**How would users interact with this feature?**

**Input**

1.  appending to the existing Athena DB or BigQuery table to add these custom items
1. providing a CSV pipeline of these  custom items (this approach will help support all envs including air-gapped)

**Output**

1. Add values to existing External Cost column in reports + including in line item drilldown view
1. Add additional column "Custom Costs"

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-235) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
This could in theory be done today by adding to an Athana table, which would add to external costs... has that approach been explored? We should be able to make this more stable by using our custom provider pipeline. 

I like the idea but our UI doesn't support the addition of another column right now.

**Comment by robfaraj** [comment]
For the envs w/access to Athena that could be a great solution. Any place I can point users to start this exploration?

Custom provider pipeline supporting custom costs seems to allow for greater adoption (ex. air-gapped, non-AWS, etc..)

**Comment by dwbrown2** [comment]
You should be able to just [insert](https://docs.aws.amazon.com/athena/latest/ug/insert-into.html) rows into the Athena table, but I would consider this experimental and is not something we have thoroughly tested. @AjayTripathy may have additional input.

**Comment by kirbsauce** [comment]
@robfaraj , based on what you're seeing, is this something we should continue to pursue?
