### ISSUE TITLE
1.79.0 miss checks image

### ISSUE THREAD

**Issue by ywyt738** [kubecost/cost-analyzer-helm-chart#872]
gcr.io/kubecost1/checks:prod-1.79.0 or quay.io/kubecost1/checks:prod-1.79.0 missed in charts v.1.79.0

**Comment by AjayTripathy** [comment]
Hi @ywyt738 , take a look at our patch notes: https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.79.0

We've deprecated this pod and moved its functionality into the cost-model.
