### ISSUE TITLE
Easily search / filter saved reports

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#879]
A growing number of teams have many saved reports stored.. that's a good thing! However, it can be hard to find a specific report once you have many saved. We've discussed UI changes to help with this. 

There's also the ability to help teams easily search/filter these reports. I believe a simple textbox that filters reports would be a great start. It could just filter against report name initially. This could be expanded over time. Something a simple as this is one option... 

![image](https://user-images.githubusercontent.com/298359/117087205-a209f200-ad03-11eb-81c1-f6dacde4f2cd.png)

**Comment by dwbrown2** [comment]
Assigning to @SheepGotoHeaven for initial input!

**Comment by SheepGotoHeaven** [comment]
+1 on this. A search bar would be super useful here.

Maybe one day it would make sense to filter reports on other attributes? But no need to jump the gun there.

**Comment by nealormsbee** [comment]
This was done at some point and I never came back to close the issue. Cleaning it up now
<img width="1009" alt="Screen Shot 2022-01-04 at 3 31 21 PM" src="https://user-images.githubusercontent.com/981904/148120216-98103f35-af72-486b-9159-0947e07be134.png">
