### ISSUE TITLE
Add API filters to request-sizing

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#881]
More users are looking to filter this data in new and interesting ways. One recent request was to allow teams to easily filter this data by their `team` label. Others want to integrate with CI/CD platforms and filter for a single pod or a pod-prefix. 

As a broader them, I think it could be useful to start bringing the Allocation filters to all workload-based Savings APIs.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-236) by [Unito](https://www.unito.io)

**Comment by DKeeling01** [comment]
Received a request today to also filter data by their `owner` label. Would we be able to revisit this request in the near future?

**Comment by michaelmdresser** [comment]
I believe @jjarrett21 is currently working on filters for the new request sizing page. I'm not sure if owner/team/etc. are included in that, but he probably knows!

**Comment by dwbrown2** [comment]
@DKeeling01 this is currently supported in Savings UI. Know what's missing?

<img width="905" alt="image" src="https://user-images.githubusercontent.com/298359/202608715-51a06c59-46bb-41ed-8598-a59381e6baa8.png">

**Comment by dwbrown2** [comment]
This was delivered to the Kubecost multiple releases ago!
