### ISSUE TITLE
[FR] Use a defined priorityClass for cost-analyzer pod

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-analyzer-helm-chart#885]
**What problem are you trying to solve?**

Creating a `priorityClass` with the chart instead of using one already defined in the cluster makes priority management more complex. 

**Describe the solution you'd like**

I wish I could use a defined `priorityClass` instead of having to [create a new one with the chart](https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/values.yaml#L258-L260). As is already for [networkCost](https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/values.yaml#L490).

**Describe alternatives you've considered**

No alternative

**How would users interact with this feature?**

Not relevant

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-237) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
Thanks for the suggestion, @pierluigilenoci! I agree this would be nice to add, but the clear alternative would be creating a new priorityClass. Because of this I'd like to more this as low priority relative to your other requests.

**Comment by pierluigilenoci** [comment]
@dwbrown2 any news about this?

**Comment by dwbrown2** [comment]
Still considered relatively low priority and PRs welcome. Let us know if there's a high impact situation.

**Comment by pierluigilenoci** [comment]
@dwbrown2 still nothing?

**Comment by dwbrown2** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/issues/885#issuecomment-904230674

**Comment by pierluigilenoci** [comment]
![hopes-and-dreams-barney-hopes](https://github.com/kubecost/cost-analyzer-helm-chart/assets/36044817/a6b3d084-32b8-485c-a0f6-2f2f7589d578)
