### ISSUE TITLE
Hide Slack Webhook in UI

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#886]
Slack webhooks should be optionally hidden from the UI, as they can be sensitive.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-238) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
What's driving the sensitivity? Can we just redact these in UI or do we need to redact on backend?

**Comment by AjayTripathy** [comment]
I think we want to redact these from the backend as well and make them write-only from the UI. The issue is that anyone can spam the webhook without authenticating if it becomes known.

**Comment by kbrwn** [comment]
@nealormsbee I am pretty sure the new alerts UI does not do this.

**Comment by nealormsbee** [comment]
You are correct, it does not.

**Comment by nealormsbee** [comment]
Adding this to my queue for the week.
