### ISSUE TITLE
Service should use fullname

### ISSUE THREAD

**Issue by sstarcher** [kubecost/cost-analyzer-helm-chart#89]
Installed via helm service currently does not use the fullname helper.  This results in `cost-analyzer-cost-analyzer` if the release is the same as the chart vs the proper `cost-analyzer`

version 1.41.0

**Comment by dwbrown2** [comment]
I believe this has been fixed long ago, but adding @AjayTripathy to confirm.

**Comment by AjayTripathy** [comment]
Yes, this is fixed-- @sstarcher  please let us know if you're still experiencing issues here.
