### ISSUE TITLE
Allow users to automate sending of saved reports accessible through UI

### ISSUE THREAD

**Issue by stacy-tumarkin** [kubecost/cost-analyzer-helm-chart#895]
Several customers/users have asked us to be able to automate sending saved reports they've created in the UI to their end consumers of data.

Either via API call or through the UI itself, it would be great to be able to set up an export of the saved report to be sent at some regular cadence to an endpoint (email, file directory, etc)

The alerts functionality doesn't have the ability to return data in the same format as saved reports.

I could see this being integrated into alerts or Saved Reports, depending on how engineering wants to design it.

gz#560

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-239) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
@stacy-tumarkin this is exactly what the recurring reports feature ultimately aims to be! Can you share any more on this part? 

>The alerts functionality doesn't have the ability to return data in the same format as saved reports.

Would love to hear what format would be desired. 

cc @mbolt35

**Comment by etsyamitra** [comment]
Thanks Stacey for creating this, would be great to have the html templates(with all the colors :)) emailed to us which would get lots more attention from users.
Am also curious if saved reports would save the metrics or would we involve computing the queries corresponding to each saved report every time user tries to load the report.
We have been running into timeouts on opening reports..so would be great to have a saved metrics on specific window (static), This might not be related to this ticket but curious on your thoughts.

**Comment by dwbrown2** [comment]
@etsyamitra would pdf format be desirable? We are actively discussing https://github.com/kubecost/cost-analyzer-helm-chart/issues/863.

**Comment by etsyamitra** [comment]
Sorry for the delay, pdf would be great :) but ideal would be js/html templates which reduces clicks on user end!

<img width="1103" alt="Screen Shot 2021-05-24 at 2 42 16 PM" src="https://user-images.githubusercontent.com/75339656/119410808-3f6e9b00-bc9e-11eb-9742-9de808db517a.png">

**Comment by dwbrown2** [comment]
Very helpful! We're actually talking with the Looker team now too about integrations. Would sending reports from Looker directly be of interest?

**Comment by sebradloff** [comment]
This might be tangentially related, but we would love to download the data in the breakdown section of the Savings page as a csv. I'm trying to filter across a few different dimensions to determine which controllers we should be rightsizing first not necessarily by savings but by efficiency score AND ram/cpu usage over a certain amount signifying a "bad neighbor" that could be really harmful to the other pods in the cluster/nodes.

**Comment by dwbrown2** [comment]
@sebastien-prudhomme love this idea for adding more detail to `/savings/requestSizing`. Any more you can share on the desire for CSV vs JSON? Our default was going to be to expose this data in JSON format initially.

**Comment by sebradloff** [comment]
@dwbrown2 In terms of CSV vs JSON, we like CSV for now because I can easily import that into Google Sheets, slice and dice the data in all the ways we need and then have discussions with teams .

**Comment by dwbrown2** [comment]
@sebradloff we'll be doing some work on CSV export this week for assets. Let's see if we can get it as part of that, if not we'll look at opening a new issue.

**Comment by dwbrown2** [comment]
@sebastien-prudhomme now in our nightly builds for you! I believe @AjayTripathy shared more but let me know if I can provide additional detail.
