### ISSUE TITLE
Filter cost by deployment in kubecost report

### ISSUE THREAD

**Issue by etsyamitra** [kubecost/cost-analyzer-helm-chart#898]
**What problem are you trying to solve?**
being able to set up filter on deployment/controller, current we are able to group by controller but not have filter on them.
Most of the times we might just need the cost of deployment over time without diving into pod level details(cause these involve lots of metrics which takes long rendering based on size of deployment)
<img width="731" alt="Screen Shot 2021-05-17 at 1 16 52 PM" src="https://user-images.githubusercontent.com/75339656/118550930-28fe9780-b712-11eb-9d2a-bf0a381a7c19.png">

**Describe the solution you'd like**
Add support for filter on 'controller' in Reports

**How would users interact with this feature?**

**Comment by dwbrown2** [comment]
Thank you for the report, @etsyamitra! 

Does the pod prefix filter on the legacy Allocation page give you what you need? Demo reference: http://demo.kubecost.io/detail.html

I'm trying to decide if we need both a pod prefix + a controller filter on this new page... 

cc @nikovacevic

**Comment by etsyamitra** [comment]
Thanks that works on 'cost allocation' tab but have been told to use 'reports' moving onwards which would the great place to have this feature. Either of that works, controller seems more ideal cause we could have multiple deployments which has same initials

**Comment by dwbrown2** [comment]
Thanks, @etsyamitra! 

@nikovacevic any chance you could weigh in on difficulty for an upcoming sprint? We originally added pod prefix support because certain services, e.g. kubeflow I believe, kick off jobs with common prefixes but no controller.

**Comment by nikovacevic** [comment]
Pretty sure that this could be done rather quickly with only front-end changes. Implementation could use filtering by controller, pod, or both. All such filters should support wildcard operator for "prefix-type" filtering. Hope that helps!

**Comment by nikovacevic** [comment]
cc @SheepGotoHeaven

**Comment by SheepGotoHeaven** [comment]
+1 @nikovacevic. This ought to be a straightforward filter to add to the frontend. I'll add it to my task queue for the week.

**Comment by SheepGotoHeaven** [comment]
@etsyamitra this is now addressed by a pull request in our frontend repo. Next release there will be support for filtering by controller and pod, as well as controller kind (deployment, statefulset) unless that addition is vetoed.

Also (this isn't explained in the UI yet): please know that as @nikovacevic noted, most filters, including these three new additions, support wildcard suffix matching. E.g. filtering by controller with `kube*` will yield all controllers beginning with the "kube" prefix.

Cheers and thanks. Hope this helps with your use case. I'll come back and close the issue once the PR is merged if there are no objections.
