### ISSUE TITLE
AWS Deployment missing region

### ISSUE THREAD

**Issue by sstarcher** [kubecost/cost-analyzer-helm-chart#90]
**Describe the bug**
Error in the logs `cost-analyzer-7d84df98f9-bwvwn:cost-model I0909 12:58:15.784836       1 awsprovider.go:647] Skipping AWS spot data download: MissingRegion: could not find region configuration`

**To Reproduce**
Deploy via helm to AWS

**Expected behavior**
The ability to discover or set a region

**Comment by dwbrown2** [comment]
Hey @sstarcher, this region field is for accessing spot node feed (optional feature) in an S3 bucket. This data can actually live in any region, which can be different than your k8s clusters, so I'm not sure how to auto discover this. Let me know if you have any ideas or if I'm missing anything. 

More info on configuration here: http://docs.kubecost.com/getting-started.html#spot-nodes

**Comment by sstarcher** [comment]
Should it just default to a region? Currently the chart can't set it at all
so it just fails.

**Comment by dwbrown2** [comment]
This feature should not be working on the default install. It requires the service key and other info provided in the link above. We just log this to let users troubleshoot when they do start adding this info. It sounds like a more intuitive logging statement would be helpful?

**Comment by sstarcher** [comment]
Sure a more intuitive log like not logging it when not being used, but as far as I can tell if the service key was added and other info provided it could still not work as the chart does not support setting the region?  Is that correct?

**Comment by dwbrown2** [comment]
This has to be configured in our product today (Settings) but we could support it in Helm. Is that what you are looking for? Let me know if you want to discuss your specific use case.

**Comment by sstarcher** [comment]
Would this region setting be something I see after I added a service key?  As under settings, I don't currently see this.  On a general statement, I would prefer all configuration be as code and not done in the UI so it's easily reproducible.

**Comment by dwbrown2** [comment]
Enabling this feature is done under Spot Instance Configuration in Settings and it should not require a service key to access.

I completely agree about wanting these to be reproducible. That being said, I do believe a number of our product features are better configured via API than from YAML configuration before installation. I could see this being a fit for values.yaml.

**Comment by dwbrown2** [comment]
@sstarcher these parameters are now directly configurable at install time! Example value shown here: https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/values.yaml#L282

Let me know if we can get you anything else here. If not, I'll mark this as closed.

**Comment by sstarcher** [comment]
Excellent thank you
