### ISSUE TITLE
Kubecost Notifications on Deployments level

### ISSUE THREAD

**Issue by etsyamitra** [kubecost/cost-analyzer-helm-chart#900]
**What problem are you trying to solve?**
Current we have kubecost notifications at the 'namespace' and 'project/cluster' level. It does not give a fair estimate of multiple deployments changes within the same namespace which is causing the alert. I understand there are cost metrics on deployment and other labels which would be great to have notified on.

**Describe the solution you'd like**
Add notification on group by "deployment/controller" level 
- could be set optional to users to add alerts for specific ones
- moving average alerts on each deployment
- considering the efficiency as a metric during alert, like if a deployment has been scaled up notifying only when it is below 20% efficient over past day, or efficiency fell below 10% than moving average which could be good signal to downscale them.

**Describe alternatives you've considered**

**Comment by dwbrown2** [comment]
Thank you for this, @etsyamitra! We're actively looking at adding different aggregations right now... with an initial focus on labels. We're also going to see about adding the ability to group by deployment. This by default would show you every deployment in your cluster consuming resources. Would this be helpful? 

You can already alert on spend changes by deployment -- https://github.com/kubecost/docs/blob/master/alerts.md#type-spend-change and efficiency by deployment -- https://github.com/kubecost/docs/blob/master/alerts.md#type-efficiency 

Are either of those immediately useful? 

cc @mbolt35 as FYI

**Comment by etsyamitra** [comment]
Thanks that would be awesome, could you please clarify which version would have that change, or let me know once we have it on deployment and labels. The docs shows the efficiency grouped by namespace, please let me know if am missing something.

**Comment by dwbrown2** [comment]
@etsyamitra this feature is actively under investigation. We'll share updates/docs as soon as possible!

**Comment by dwbrown2** [comment]
This is now available in our latest release candidate! More info available here -- https://github.com/kubecost/docs/blob/master/alerts.md#type-recurring-update

**Comment by kbrwn** [comment]
@etsyamitra I am going to close out this issue. If you need further assistance with Alerts please email support@kubecost.com or contact us on slack.
