### ISSUE TITLE
Obscure slackwebhookurl in the kubecost ui

### ISSUE THREAD

**Issue by etsyamitra** [kubecost/cost-analyzer-helm-chart#903]
**What problem are you trying to solve?**
Slackwebhook uri in Notifications tab would be sensitive fields for an organization

**Describe the solution you'd like**
Drive webhookuri through secrets to not log the value in ui (maybe a checkbox that it is enabled would suffice)

**Describe alternatives you've considered**
encrypt and display

**How would users interact with this feature?**

**Comment by AjayTripathy** [comment]
Thanks for this! Looks like a duplicate of #886 ?

**Comment by etsyamitra** [comment]
perfect thanks for creating this
