### ISSUE TITLE
Greater visibility into cloud provider discounts

### ISSUE THREAD

**Issue by etsyamitra** [kubecost/cost-analyzer-helm-chart#908]
**What problem are you trying to solve?**
Kubecost pulls the discounts from billing or through the settings page. However its not transparent to end users if the discounts actually match up or were they applied twice in case it was configured in kubecost settings besides connected to billing database.

**Describe the solution you'd like**
Have separate tab in cost allocation/reports for discounts. Currently kubecost pulls only the cummulative costs but this could be obtained by pulling the discounts and total costs attributes in billing db as well. A simple estimate in terms of % would also be great for each resource type and deployment.

**Describe alternatives you've considered**

**How would users interact with this feature?**

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-240) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
@etsyamitra thanks for this request! It might be interesting to discuss further, but we've actually been thinking that it would be helpful to show applied discount in the Allocation/Asset detail view. Would that be helpful for you?

![image](https://user-images.githubusercontent.com/298359/119603733-a07f9700-bda2-11eb-8e50-202b2e404d2e.png)

**Comment by etsyamitra** [comment]
Thanks that would be great, could you please confirm that it would work for GCP as well. That is kubecost being able to pull discounts from gcp billing database.

**Comment by dwbrown2** [comment]
@kirbsauce yep, this is a new feature related to this request

@etsyamitra is this helpful? think there's more we can do here?
