### ISSUE TITLE
Migrate the ingress and rbac roles from v1beta1

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#915]
These are going away in v1.22+. Samples on how to do this are available linked from this issue and PR:  https://github.com/kubecost/cost-analyzer-helm-chart/issues/589

**Comment by pierluigilenoci** [comment]
@AjayTripathy I suggest to do something like this https://github.com/oauth2-proxy/manifests/pull/37/files to maintain backwards compatibility but remove annoying error messages as soon as possible.

**Comment by pierluigilenoci** [comment]
@dwbrown2 two months have passed, is there any news?

**Comment by AjayTripathy** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/pull/977/files should bring us to compatibility with 1.22 for most components.

**Comment by kirbsauce** [comment]
As far as I can tell, this is now resolved with 1.84.  Closing for now but please reopen if I've missed something.
