### ISSUE TITLE
Multi-Cloud Assets Pipeline is broken on /allocations.html

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#918]
When using 2+ cloud providers, tagging data is not correctly shown on /allocations.html or in the API. However, the data is still available on /details.html. 

Our recommendation for now is to use /detail.html until we can get this fixed

gz#314

**Comment by kbrwn** [comment]
@AjayTripathy is this still an issue?

**Comment by AjayTripathy** [comment]
Nope! Thanks for following up Kyle!
