### ISSUE TITLE
Ability to set nodeSelector

### ISSUE THREAD

**Issue by Mokto** [kubecost/cost-analyzer-helm-chart#92]
**What problem are you trying to solve?**
I want to be able to run kubecost on a specific node

Thanks!

**Comment by dwbrown2** [comment]
I support this! What's your particular rationale for this? I just want to get a sense for the urgency/impact.

**Comment by Mokto** [comment]
Reduce cost ;) 

To run this on a spot instance.

**Comment by Mokto** [comment]
I could make a pull request on this tomorrow. If this can help you.

**Comment by dwbrown2** [comment]
A pull request is definitely welcome here! 

Obviously just be cautious about running a monitoring solution like this on a node that may have a higher likelihood of going down... our pod writes data to your Prometheus, so you may miss data and our frontend would not be available during pod restart.

**Comment by Mokto** [comment]
Ah, you're right ! I was thinking of replicating the kubecost deployments, maybe ?

But if I can't scale Kubecost, I want to be able to run it on an ondemand instance anyways, so nodeSelector is still useful ;)

**Comment by dwbrown2** [comment]
You can replicate Kubecost but you would also need to replicate Prometheus, etc if you want to do something similar with those pods. That can be complicated. 

But I agree with you that this is useful for more reasons than just running on spot!

**Comment by Mokto** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/pull/93

**Comment by dwbrown2** [comment]
Call this done? Anything else we can do here?

**Comment by Mokto** [comment]
Yes, thanks. If I'm right it's not deployed yet, but we can close this.

**Comment by dwbrown2** [comment]
Should be in our build early next week! You can deploy from master though if you want it today :)
