### ISSUE TITLE
Add ImagePullSecrets to thanos charts.

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#920]
Many of our charts already support imagepullsecrets-- but it appears our thanos charts do not. We'll want to get these added.

https://github.com/kubecost/cost-analyzer-helm-chart/pull/922

**Comment by AjayTripathy** [comment]
https://github.com/kubecost/cost-analyzer-helm-chart/pull/922 for the in-progress PR

**Comment by kirbsauce** [comment]
@AjayTripathy , assume this can be closed with the merge of #922 ?  Also imagine it was released in 1.83?

**Comment by AjayTripathy** [comment]
Yes, this can be closed.
