### ISSUE TITLE
Support integration with Alibaba Cloud

### ISSUE THREAD

**Issue by stacy-tumarkin** [kubecost/cost-analyzer-helm-chart#927]
We have Enterprise users running k8s in Alibaba Cloud, and it's the [third biggest cloud provider in the world (first in APAC)](https://www.alibabacloud.com/blog/alibaba-named-by-gartner-as-third-biggest-global-provider-for-iaas-and-first-in-asia-pacific_596191). 

Supporting an integration with Ali Cloud would allow us to more effectively serve cost-conscious teams in APAC.

This would be a longer-term initiative for sure, but given that our userbase has already requested it, and it would give us the opportunity to help a lot of new users find cost savings, I think it's worth seriously exploring!

gz#381

**Comment by xtaje** [comment]
Are there any pointers or documentation on how the cloud API integrations work? At least for the pricing API, we might be able to contribute some work.

**Comment by mattray** [comment]
@xtaje I'm not sure if there's a guide for onboarding new platforms, but the relevant code appears to be here:
https://github.com/opencost/opencost/tree/develop/pkg/cloud

Take a look at this as well:
https://github.com/opencost/opencost/blob/develop/CONTRIBUTING.md

**Comment by AjayTripathy** [comment]
Hey @xtaje here's an even more in-depth guide designed to help folks walk through an implementation. It is a work-in-progress so please let me know if you have any feedback! https://docs.google.com/document/d/1JVPCeQmvGU88aw0bJJjtTzdl5RhhOqT7FPs2szuHBkc/edit

**Comment by dwbrown2** [comment]
I've recently seen a couple other users request an integration here. Would love to see if we can prioritize soon. @xtaje is this something you would be interested in working on?

**Comment by xtaje** [comment]
> I've recently seen a couple other users request an integration here. Would love to see if we can prioritize soon. @xtaje is this something you would be interested in working on?

Possibly, but would need to discuss with our team and see how it fits in on our roadmap.

**Comment by Adam-Stack-PM** [comment]
Closing based on https://github.com/kubecost/kubecost-cost-model/issues/1055
