### ISSUE TITLE
Abandoned-workloads view shows pods with heavy network traffic when duration set to 7d or 30d 

### ISSUE THREAD

**Issue by kbrwn** [kubecost/cost-analyzer-helm-chart#934]
**Describe the bug**
Abandoned-workloads view shows pods with heavy network traffic when the Duration is set to 7d or 30d.  2 day duration shows the expected results. This view appears to be utilizing prometheus queries that may timeout or receive only a partial result when a cluster has a significant amount of pods and 7d+ duration is selected.

**Expected behavior**
Abandoned-workloads view should properly show pods with heavy network usage in all available durations (2d, 7d, 30d).

gz#395

gz#370

**Comment by dwbrown2** [comment]
@mbolt35 currently reviewing! Plan is to move these metrics to ETL pipeline.

**Comment by mbolt35** [comment]
This should be resolved in next release

**Comment by dwbrown2** [comment]
Resolved 1.83 -- https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.83.0
