### ISSUE TITLE
Filter inactive namespaces

### ISSUE THREAD

**Issue by xhejtman** [kubecost/cost-analyzer-helm-chart#937]
Hello,

I think it would be a nice feature, if one can select only active namespaces are displayed in Overview or maybe also in Cost Allocation. 

Now it shows all namespaces that were used. I would appreciate an option to hide inactive, i.e., those without running pod. 

gz#402

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-241) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
@xhejtman Kubecost should only show data for namespaces that have pods incurring costs during the selected time window. A filter can further change the default Allocation view for you.

**Comment by xhejtman** [comment]
So there might be a bug then?

I have a namespace that shows:

Allocations

Average resources consumed over measured time window
RAM Allocated: 21.96 GB
CPU Allocated: 6.00 CPUs
GPU Allocated: 1.00 GPUs
Storage Allocated: 0.00 GB

Deployments
No running resources found
StatefulSets
No running resources found
> matlab $899.85/mo
Containers
No running containers detected in this namespace


so, apparently, there is no pod running, it reports storage allocated 0.00, so it should be ignored?

**Comment by dwbrown2** [comment]
Would you be able to share a screenshot? It's not clear to me where these metrics are coming from.

**Comment by xhejtman** [comment]
[Namespace _ Kubecost.pdf](https://github.com/kubecost/cost-analyzer-helm-chart/files/6660925/Namespace._.Kubecost.pdf)

**Comment by dwbrown2** [comment]
This shows there was a stateful set running at some point during the measured window. You are saying you do not believe that was true?

**Comment by xhejtman** [comment]
it **has been** running at some point. And my request was to filter out these namespaces and keep only those that are currently running.

**Comment by dwbrown2** [comment]
@xhejtman is there any more context that you can share for what you would be aiming to do or what problem you'd be trying to solve?

**Comment by xhejtman** [comment]
Well, it seems that cost analyzer shows even non-active namespaces, i.e., namespaces that have no running pods. I would like to have an option, to filter out these namespaces and show only active, i.e., namespaces with at least one running pod.

**Comment by dwbrown2** [comment]
Can share more about what you are hoping to do with this data/view?

Kubecost currently shows workloads that were active during the measured historical period. We do have the ability to greatly shorten this window, i.e. reduce 1 hour or less. This would require some UI changes though.

**Comment by xhejtman** [comment]
I was hoping to see only running pods and their cost. But also letting an option to see all namespaces to see costs even for not running ones.

**Comment by dwbrown2** [comment]
Can you share more on why you want this? I'm trying to understand what you are looking to do this with this data.

**Comment by xhejtman** [comment]
Well, I wanted quick way to see, what is currently running and how $$ intensive. We have relatively many short-live namespaces.
