### ISSUE TITLE
Option to Filter by Node Labels in Cost allocation page

### ISSUE THREAD

**Issue by gbvikas** [kubecost/cost-analyzer-helm-chart#938]
Option to filter nodes by specific label in Cost allocation page

gz#405

**Comment by dwbrown2** [comment]
@gbvikas thanks so much for the request! Is there any chance you have other context/details on the use case you have in mind for this filter?

**Comment by gbvikas** [comment]
@dwbrown2 - not all the workloads have common labels. Third party Operators and dependent workloads have their own labels. We need to identify the cost based on node labels

**Comment by AjayTripathy** [comment]
Hi @gbvikas based on our discussion this morning, it sounds like this + a little scripting against our API will work for now. Let me know if we can get you anything else related here.
