### ISSUE TITLE
what is the use of this server? 

### ISSUE THREAD

**Issue by kitianFresh** [kubecost/cost-analyzer-helm-chart#940]
https://github.com/kubecost/cost-analyzer-helm-chart/blob/cabe3b42fca0ec9e38fbb610a2036361b4ebf247/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L639

I know the cost-model is used for collect metrics and compute costs, the frontend display ui, but what the server is 

gz#425

**Comment by dwbrown2** [comment]
@kitianFresh this is the kubecost webserver that routes traffic to the appropriate backend service, including the cost-model. It can also be used to proxy traffic to a (bundled) Grafana deployment.

**Comment by kitianFresh** [comment]
thanks for answer, so, what is the differences between the web server and Nginx.  you mean the server is just encapsulate some backend api to do proxy?

**Comment by kitianFresh** [comment]
@dwbrown2 thanks for answer, so, what is the differences between the web server and Nginx.  you mean the server is just encapsulate some backend api to do proxy?

**Comment by AjayTripathy** [comment]
Hi @kitianFresh , our nginx (cost-analyzer-frontend) is the both the frontend web server and proxies traffic to grafana/cost-analyzer-server/cost-model
