### ISSUE TITLE
Set grouping option for Controller Allocation and Service Allocation at Overview page by custom label mappings

### ISSUE THREAD

**Issue by iusergii** [kubecost/cost-analyzer-helm-chart#941]
**What problem are you trying to solve?**
I'd like to have the ability to configure label aggregation for pie charts on the overview page in the same way as it done for Controller Allocation and Service Allocation. 
Display pie charts by "Product", "Team", "Environment", "Owner", etc.

gz#433

**Comment by dwbrown2** [comment]
thanks, @iusergii! I believe progress here could be tracked under https://github.com/kubecost/cost-analyzer-helm-chart/issues/947

**Comment by iusergii** [comment]
@dwbrown2 thanks, closing in favor #947
