### ISSUE TITLE
Allow to filter disk in savings

### ISSUE THREAD

**Issue by xhejtman** [kubecost/cost-analyzer-helm-chart#942]
We are using templated filters for local disks to only /dev/sd* and /dev/nvme* devices. This is because RKE2 + containerd shows many irrelevant devices in metrics. E.g., every running pod is reported as overlay filesystem that has size and usage the same as underlaying file system, or if you mount NFS PVC, it is counted as well. So we filtered out everything except real devices for local disks. It works ok except saving stats. They use all the received metrics and make recommendation misleading, e.g. a node that has real disk 500GB only gets recommendation to "shrink" the device to 50TB, just because it mounts 50TB volume over NFS. If you allow to set disk filter, it would make more sense.

gz#434

gz#424

gz#421

gz#507

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-242) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment]
@xhejtman thanks for reporting! Let us think about a general solution that wouldn't require too much user config. 

one idea is to use our cloud reconciliation pipelines for this.
