### ISSUE TITLE
Cost allocation based on Project/Account labels

### ISSUE THREAD

**Issue by kbrwn** [kubecost/cost-analyzer-helm-chart#946]
**What problem are you trying to solve?**
More robust GCP project based cost allocation.

**Describe the solution you'd like**

Instead of labelling each resource with kubernetes_namespace tag,  Kubecost should read the labels at GCP project level and assign all the cost within that project to particular namespace based on labels.

This is a customer request.

gz#444

**Comment by dwbrown2** [comment]
@Sean-Holcomb am I mistaken, or can this already be done?

**Comment by Sean-Holcomb** [comment]
It sounds like they are saying they want to propagate certain labels from parent to child for cloud assets, but that connection isn't necessarily available in the cur. It also kind of seems like a very specific use case, with the more general problem being better group tagging of cloud assets.

**Comment by dwbrown2** [comment]
Ah yes, I see what you mean now! Most users will have multiple teams, namespaces, etc in a single GCP project. Would love to learn more though. @kbrwn is there an easy way for us to connect with this user to learn more?

**Comment by gbvikas** [comment]
Currently we have two types of GCP projects.
1. Shared by multiple teams/BUs
2. Dedicated for specific BU/Team.. 

In Shared GCP Projects, we do add labels at resource level. 
But in dedicated Projects, we need all the resources(external cost) within that project to be assigned to a specific <kubernetes_namspace>. This will avoid labelling all resources with the same <kubernetes_namspace> tag within that project

**Comment by Sean-Holcomb** [comment]
I wonder if something we could do here is labeling rules, where the presence of certain labels on a line item, would override a certain asset property @dwbrown2 I am not sure if this would actually solve @gbvikas problem, but at least be a step in the right direction of making labeling less arduous.

**Comment by alexdmoss** [comment]
Just to add, currently looking at kubecost and this would be an incredibly useful feature for us also - we have a lot of projects in the "(2) - Dedicated" category that @gbvikas describes above.

**Comment by AjayTripathy** [comment]
We will want to do something similar with Account Labels in AWS. Let's bump the priority here since it's not a GCP-only feature. Expected ETA for a design of how the mapping is stored in a configmap shortly after holidays and implementation to follow!

**Comment by valdisrigdon** [comment]
We would love to be able to add AWS tags to on an AWS account, and have those as defaults for resources instead of having to tag all the resources in the account.

**Comment by SteveGoodenough** [comment]
This would be great for us as a GCP user; we use namespaces for each service on k8s but they get their own projects (2; non-prod and prod) for all other GCP assets they use.

There are certain things like Datastore (Firestore in Datastore mode) where you cannot use labels so this would solve it all with a single project level label.

**Comment by dwbrown2** [comment]
@biancaburtoiu have any docs/guidance on how to use this new feature? would love to see it in action when ready! 

cc @AdamStack18

**Comment by biancaburtoiu** [comment]
I've got some [brief documentation](https://github.com/kubecost/docs/pull/221) ready for this as well! @dwbrown2

**Comment by AdamStack18** [comment]
Re-opening this item while we work on launching GCP labels. 

cc @biancaburtoiu

**Comment by Adam-Stack-PM** [comment]
@biancaburtoiu Will #279 and the connected PR close this issue?

**Comment by biancaburtoiu** [comment]
@Adam-Stack-PM Yes. I've also scale-tested this with 10x asset and label counts and performance is not significantly affected. cc @AjayTripathy

**Comment by Adam-Stack-PM** [comment]
Closing based on the above comment. Re-open if needed.
