### ISSUE TITLE
Support GPU by request strings other than "nvidia/com/gpu".

### ISSUE THREAD

**Issue by kbrwn** [kubecost/cost-analyzer-helm-chart#948]
**What problem are you trying to solve?**
GPU can be defined by `k8s.amazonaws.com/vgpu` or `amd.com/gpu` and other request strings depending on the GPU provider and set up. Kubecost is currently hardcoded to use nvidia/com/gpu: https://github.com/kubecost/cost-model/blob/develop/pkg/costmodel/costmodel.go#L173

**Describe the solution you'd like**
Support other common GPU request strings as well as virtual gpu request string `vgpu`

**How would users interact with this feature?**

Users should be able to set the GPU request string in the values.yaml or the settings page. 

gz#451

gz#388

gz#466

**Comment by AjayTripathy** [comment]
I'm guessing we may want to make this resource definition configurable since providers will use different notations, but I'm open to hardcoding the common cases and quickly adding k8s.amazonaws.com/vgpu

**Comment by dwbrown2** [comment]
My two cents: I vote we start with a fixed list and explore this being configurable later.

**Comment by dwbrown2** [comment]
@AjayTripathy planning to pick up this week. 

@AjayTripathy can you let us know if you can't tackle this week?

**Comment by AjayTripathy** [comment]
https://github.com/kubecost/cost-model/pull/843/commits/88afa004710a0426004a6befeb527c9b5a84ae09 should address!

**Comment by dwbrown2** [comment]
@csfangy were you able to confirm if this met their needs?

**Comment by csfangy** [comment]
@dwbrown2 followed up! waiting to hear back today.

**Comment by kirbsauce** [comment]
Closing for now.  @csfangy , feel free to reopen if necessary.

**Comment by baddoub** [comment]
Hi,
I am digging up this ticket because we are facing the same issue with AMD gpus. Is there any timeline add the support the AMD GPUs ?

**Comment by AjayTripathy** [comment]
Hi @baddoub , we're launching beta support in enterprise for AMD GPU monitoring. No timeline yet on when that will make it open source. Please reach out if you'd like early access.

**Comment by baddoub** [comment]
Hi @AjayTripathy! That's awesome news. Will definitely reach out on slack. Thanks for the heads up.

**Comment by chipzoller** [comment]
Since this issue does not pertain specifically to the Helm chart, I've opened https://github.com/kubecost/features-bugs/issues/121 and will close this. Please subscribe to that issue for updates.
