### ISSUE TITLE
Composite Reporting

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-analyzer-helm-chart#958]
Do we have any ability to deliver a "composite report?"

**What problem are you trying to solve?**
that is to say in the ui i can drill down into resources, but when i export the report it’s just whatever view i have currently selected.

**Describe the solution you'd like**
like it’d be nice if i could show charges per cluster, as well as details about the items.  right now each view exports individually
like one view to show charges per namespace, then break that down by resource in each namespace.

**Describe alternatives you've considered**
none mentioned

**How would users interact with this feature?**
via the standard UI views

gz#486

**Comment by dwbrown2** [comment]
It sounds to me like multi-aggregation (already available via our API, and coming to our frontend) would likely accomplish this!  

cc @nikovacevic

**Comment by nikovacevic** [comment]
I'm not certain that's what Kirby is talking about, but perhaps it's a stepping-stone on the way there.

@kirbsauce, if you were able to aggregate by `(namespace, controller)` and export that, such that the results looked like:
| Name | CPU | RAM | Total |
|---|---|---|---|
| kubecost/kubecost-cost-analyer | 10.00 | 20.00 | 30.00 |
| kubecost/kubecost-grafana | 10.00 | 20.00 | 30.00 |
| kubecost/kubecost-prometheus-server | 10.00 | 20.00 | 30.00 |
| default/redis | 10.00 | 20.00 | 30.00 |

would that satisfy this idea? Or are you suggesting something more "composite," as in "composed of several layers," whereby you get to see namespace-level details and controller-level details within each namespace, like drill-down? (Maybe something with sections, sub-totals, etc.)

**Comment by nikovacevic** [comment]
Fang and I just followed up and agreed that the customer asking for this is going to just give his customers access to Kubecost, itself, to directly use the drill-down capability in the UI. Regardless, we'll go on developing multi-agg, which could be a good proxy for this kind of idea in the short-term.
