### ISSUE TITLE
Built-in prometheus high memory usage with 'Savings' recording rules

### ISSUE THREAD

**Issue by B-Souty** [kubecost/cost-analyzer-helm-chart#963]
**Describe the bug**
Enabling "Savings" recording rules increase prometheus memory usage by a lot. In my case prometheus went from using ~2.3GB to ~7.3GB 

I'm using the built-in prometheus on a small-ish staging cluster (~60 nodes). The person who previously worked on kubecost disabled the Saving recording rules. After taking over I noticed some warning messages in kubecost saying `Savings Recording Rules do not exist.` and mention in the doc that those recording rules were enabling certain product features so I tried enabling them.

**To Reproduce**
1. Enable/Disable recording rules at `prometheus.serverFiles.rules` and monitor memory usage

**Expected behavior**
Wasn't expecting much change.

gz#500

**Comment by mbolt35** [comment]
@B-Souty That’s very surprising. Especially given that the recording rules use very small windows of time. What version of Prometheus are you guys using?

**Comment by B-Souty** [comment]
@mbolt35 Actually I just had another look at the graph in grafana, it turns out my timezone settings were wrong. The increase in memory coincide in fact with when I added a pretty big scrape config which makes more sense. Sorry for the confusion.
