### ISSUE TITLE
What are the node exporters used for? 

### ISSUE THREAD

**Issue by B-Souty** [kubecost/cost-analyzer-helm-chart#964]
Hi, we deployed kubecost in a staging cluster with the node exporter **disabled** and kubecost seems to be working perfectly fine without it.

We then configured the bundled Prometheus to scrape our existing node exporters and didn't see any change in kubecost.

gz#504

**Comment by dwbrown2** [comment]
Hi @B-Souty is this resource helpful for you? https://github.com/kubecost/docs/blob/master/diagnostics.md#node-exporter-metrics-available

Let me know if we can share more!

**Comment by B-Souty** [comment]
@dwbrown2 It does help. Thanks a lot.
