### ISSUE TITLE
kubecost-aws pod crashing

### ISSUE THREAD

**Issue by KarthikContainers** [kubecost/cost-analyzer-helm-chart#969]
**Describe the bug**
While installing kubecost via helm chart, aws-store pod keeps crashing(even after providing metering credentials).

**To Reproduce**
Followed a modified version of instructions [here](https://github.com/kubecost/docs/blob/master/aws-marketplace-install.md).
1. Created a service account:
`
eksctl create iamserviceaccount \
    --name kubecost-cost-analyzer \
    --namespace kubecost \
    --cluster Democluster \
    --attach-policy-arn arn:aws:iam::<aws-account-id>:policy/MarketplaceRegisterUsage \
    --approve \
    --override-existing-serviceaccounts
`
    
2. In awsstore-values.yaml set kubecost-cost-analyzer to false.
`
awsstore:
  annotations:
    eks.amazonaws.com/role-arn: <rolearn-created-above>
  imageNameAndVersion: 117940112483.dkr.ecr.us-east-1.amazonaws.com/8cc31d15-33f6-49fe-8d6c-e9c0366cefa0/cg-142668492/gcr.io/kubecost1/awsstore:1.61.3-latest
serviceAccount:
  create: false
  name: kubecost-cost-analyzer
  annotations:
    {}
  `
3. Did helm install
`
helm install kubecost kubecost/cost-analyzer --namespace kubecost --set kubecostToken="a25pbW1hQGFtYXpvbi5jb20=xm343yadf98" \
--set kubecostModel.image=117940112483.dkr.ecr.us-east-1.amazonaws.com/8cc31d15-33f6-49fe-8d6c-e9c0366cefa0/cg-142668492/gcr.io/kubecost1/cost-model \
--set kubecostFrontend.image=117940112483.dkr.ecr.us-east-1.amazonaws.com/8cc31d15-33f6-49fe-8d6c-e9c0366cefa0/cg-142668492/gcr.io/kubecost1/frontend \
--set kubecost.image=117940112483.dkr.ecr.us-east-1.amazonaws.com/8cc31d15-33f6-49fe-8d6c-e9c0366cefa0/cg-142668492/gcr.io/kubecost1/server \
--set kubecostChecks.enabled=false \
--set prometheus.alertmanager.enabled=false \
--set prometheus.nodeExporter.enabled=false \
--set imageVersion="1.61.3-latest" \
--set global.grafana.enabled=false \
--set global.grafana.proxy=false \
-f awsstore-values.yaml
`
4. After the install:
Went to iam role created in step 1, edited the roles trust relationship condition Value from `system:serviceaccount:kubecost:kubecost-cost-analyzer`
to
`system:serviceaccount:kubecost:awsstore-serviceaccount`
5. Restart the pod.
6. This got the 403 error to go away but the aws-store pod still crashes.

**Expected behavior**
Aws-store pod doesn't crash after required permissions are provided.

**Screenshots**

**Collect logs (please complete the following information):**

 - Run `helm ls` and paste the output here:
 `
 NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
 `
 `
 cost-analyzer-1625866517        kubecost        1               2021-07-09 21:35:49.136474886 +0000 UTC deployed        cost-analyzer-1.82.2    1.82.2 
 `

 - If the pod is stuck in init, run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-init` and paste output here:
 Not stuck in init

 - If a page is broken or not loading, open your javascript developer console and paste the ouput here:
 Page is not broken.

gz#531

**Comment by AjayTripathy** [comment]
Hi @KarthikContainers , can you provide logs for the awsstore pod?

kubectl logs <aws-store-pod-name> -n kubecost ?

**Comment by KarthikContainers** [comment]
I0707 22:36:31.990747    1 main.go:28] Read region from metadata us-east-2
I0707 22:36:31.990876    1 main.go:38] Using productcode 8c05xx7cvu5tkm1okk9f2ol9c

This is all I am getting. thanks.

**Comment by AjayTripathy** [comment]
Hi @KarthikContainers , looks like the pod is running successfuly but k8s is still terminating with an exit code of 0. This exit code implies that the specified container command completed 'sucessfully', but too often for Kubernetes to accept as working. We can look to make a quick fix to the awsstore container to make it pause a bit longer before terminating, but this should be working :)

**Comment by KarthikContainers** [comment]
Hello created a pull request that possibly fixes this issue, please take a look.
https://github.com/kubecost/cost-analyzer-helm-chart/pull/995

**Comment by AjayTripathy** [comment]
Thank you @KarthikContainers ! Very much appreciated. I'll close this-- the fix will be in our nightly and make it into our next prod release.
