### ISSUE TITLE
Allow breakdown by Account/Project/Provider inside Assets

### ISSUE THREAD

**Issue by csfangy** [kubecost/cost-analyzer-helm-chart#970]
**What problem are you trying to solve?**
For large payer accounts/subscriptions, it'd be great to be able to breakdown by account inside Assets. Especially useful for multi-cloud users. It becomes a one stop shop for everything.

**Describe the solution you'd like**
Breakdown by Accounts to see all the summarized account level costs.
![image](https://user-images.githubusercontent.com/28571850/125329971-22585f00-e314-11eb-891c-33f56cbde1d3.png)

**Describe alternatives you've considered**
Filter by specific accounts/projects in the additional filtering section.
![image](https://user-images.githubusercontent.com/28571850/125330005-300de480-e314-11eb-8669-cb94bf02ae82.png)

**How would users interact with this feature?**
Mostly for the non-technical users who are looking at OOC costs for reporting purposes.

gz#540

**Comment by csfangy** [comment]
@Sean-Holcomb feel free to add your comments/thoughts!

**Comment by dwbrown2** [comment]
GCP also has the concept of a billing_account_id, in addition to Project. 

Sean and I also discussed the value in supporting Provider breakdown, e.g. AWS, GCP, Azure, on-prem.

**Comment by kaelanspatel** [comment]
As of https://github.com/kubecost/cost-analyzer-frontend/pull/341 and v1.84 this is done.
