### ISSUE TITLE
Support for Workload Identities

### ISSUE THREAD

**Issue by voidshard** [kubecost/cost-analyzer-helm-chart#986]
**What problem are you trying to solve?**
When deploying on GCP a service account key is currently required by the Kubecost pod. This is somewhat cumbersome and ideally we would support Workload Identities. Currently without a service account key secret kubecost errors & dies (in my case, no configuration is mounted & only the PROMETHEUS_SERVER_ENDPOINT env var is set), even when a Workload Identity is configured granting all perms it actually requires. That is, I believe the helm chart includes a secret that users can use for evaluation (so in theory a user building with helm will always have a secret included), but having kubecost require this to be set when it's not strictly needed seems suboptimal.

**Describe the solution you'd like**
I'm not really a kubecost expert here or familiar with the long term game plan; but In the most straightforward approach we could have kubecost print a warning if a service account key isn't found / isn't configured, but attempt to continue anyhow. Presumably kubecost would print said warning them attempt to collect the GCP data it requires & succeed (to it's great surprise I guess).

**Describe alternatives you've considered**
We could also have some configuration around how kubecost should authenticate itself with GCP and act/error accordingly (we may do this in addition).

**How would users interact with this feature?**
Ideally a user would setup a WI for each GCP cluster they oversee & then add it to the kubecost ServiceAccount either via the UI or helm/kustomize. 

gz#573

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-243) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment]
Hi @voidshard thank you for this feedback! We'll add this to our roadmap. This might be as simple as removing our check for a key to connect to billing data if WIs "just work" with the google cloud SDK.

**Comment by dwbrown2** [comment]
Currently on backlog, marking as help wanted for now.

**Comment by anasinnyk** [comment]
Hi there
what is this issue status? Does it have any progress?

**Comment by AjayTripathy** [comment]
Thank you so much for the PR! Let's continue discussion there but that should help!

**Comment by keithhand** [comment]
Do we have an update on adding support for this?

**Comment by Adam-Stack-PM** [comment]
@keithhand, Not yet. Looks like the attached PR is close to being merged for v1.97. Then will need to review Sean's issue for an upcoming release.

**Comment by BenCoughlan15** [comment]
Eagerly awaiting this. 🙂

**Comment by BenCoughlan15** [comment]
Hey, is this scheduled at all?

**Comment by Adam-Stack-PM** [comment]
@BenCoughlan15, Thanks for the nudge here. I will sync with the team on Monday and follow up here on Tuesday. 

Note to engineer on rotation please keep the need-follow-up label on this issue.

**Comment by biancaburtoiu** [comment]
I'm looking at implementing this as part of the support rotation. I'll share further updates as the PR(s) go through the review process. Thanks for the patience! 

cc @Adam-Stack-PM

**Comment by biancaburtoiu** [comment]
I've made the necessary adjustments to introduce GCP integration via Workload Identity, to be released in 1.98. Will link our updated public docs shortly after the release. Thanks everyone for your patience and please let us know if you have further questions!

cc @Adam-Stack-PM

**Comment by BenCoughlan15** [comment]
Awesome, can't wait, thanks all!

**Comment by BenCoughlan15** [comment]
Hey @biancaburtoiu - I've seen release 1.98 rc1 has gone in, do we still expect to ship this feature with 1.98?

**Comment by biancaburtoiu** [comment]
Hi @BenCoughlan15, thank you for checking in! That's right, this feature is part of the rc1 and is on track to be included in 1.98. Please let us know if you are able to set it up and whether you've encountered any issues along the way!

**Comment by BenCoughlan15** [comment]
Awesome, thanks, I'll give it a whirl :)
