### ISSUE TITLE
Relative Path Not Working For "configure your external cloud settings" Link

### ISSUE THREAD

**Issue by Cbarr-hub** [kubecost/cost-analyzer-helm-chart#992]
**Describe the bug**
In the kubecost dashboard, under the Assets tab, there's a link to configure your external cloud settings. This link works as intended if kubecost is the root path but doesnt function properly if kubecost is working under a sub path.
![image](https://user-images.githubusercontent.com/85138056/126690324-79ead533-0ba0-4998-bb50-6588b5d51883.png)

When clicked, it takes you to <domain>/settings.html#out-of-cluster-box Instead of <domain>/kubecost/settings.html#out-of-cluster-box 

Other links work as expected.

gz#593

**Comment by AjayTripathy** [comment]
Thanks @Cbarr-hub , @nealormsbee can you take a quick look?

**Comment by nealormsbee** [comment]
PR with a solution opened 👍 

Thanks for the report @Cbarr-hub !
